### PR TITLE
UCP/TAG: Fixes for RNDV PUT Zcopy scheme

### LINKED ISSUE #4474: [mtt] hang in mpi-small-tests/misc/collmeas with TLS=tcp
Configuration
```
OMPI: 4.0.2rc3
MOFED: MLNX_OFED_LINUX-4.6-1.0.1.1
Module: hpcx-gcc-debug (2019-11-18)
Test module: mtt-tests/hpcx-gcc
Nodes: jazz x2 (ppn=28(x2), nodelist=jazz[06-07])
```

MTT log: http://hpcweb.lab.mtl.com//hpc/mtl_scrap/users/mtt/scratch/ucx_ompi/20191118_080139_90265_12330_jazz06.swx.labs.mlnx/html/test_stdout_W9e2EX.txt

Waited for 18 hours.

Cmd:
`mpirun -np 56 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt --bind-to core -x UCX_NET_DEVICES=p2p2 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=tcp -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/local/benchmarks/daily/next/2019-11-18/mtt-tests-gcc/installs/PPyF/tests/mpi-small-tests/mtt-tests.git/mpi-small-tests/misc/collmeas`

Output:
```
Mon Nov 18 08:11:54 2019[1,0]<stderr>:  16777216 &   38603.04 &  262590.87 &  419909.45 \\
Mon Nov 18 08:11:54 2019[1,0]<stderr>:  16777224 &   41186.50 &  262663.43 &  420991.87 \\
Mon Nov 18 08:11:54 2019[1,0]<stderr>:  25165824 &   64955.41 &  325506.29 &  507606.64 \\
Mon Nov 18 08:11:54 2019[1,0]<stderr>:  33554424 &   90266.42 &  448594.40 &  697592.51 \\
Mon Nov 18 08:11:54 2019[1,0]<stderr>:  33554432 &   91616.20 &  452351.37 &  697265.39 \\
Mon Nov 18 08:11:54 2019[1,0]<stderr>:
Mon Nov 18 08:11:54 2019[1,0]<stderr>:Collective=Allreduce, Communicator=WORLD
Mon Nov 18 08:11:54 2019[1,0]<stderr>:========================================
node=jazz06, pid=101998:

node=jazz06, pid=101996:
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

1. Fixes RNDV PUT Zcopy scheme when posted received buffer is larger than send buffer.
2. Fixes incorrect `ucs_assert()` condition.

## Why ?

1. Fixes #4474, reproduced: 
- for TCP: `tcp/test_ucp_tag_match_rndv.post_larger_recv/0 <tcp>` hangs.
- for IB: 
```
[ RUN      ] rcx/test_ucp_tag_match_rndv.post_larger_recv/0 <rc_x>
[hpc-test-node-gpu01:15977:0:15977] ib_mlx5_log.c:139  Local protection on mlx5_0:1/IB (synd 0x4 vend 0x53 hw_synd 0/157)
[hpc-test-node-gpu01:15977:0:15977] ib_mlx5_log.c:139  RC QP 0x320a4 wqe[3]: RDMA_WRITE s-- [rva 0x1816050 rkey 0x36d33c] [va 0x1838130 len 32 lkey 0x36d841]
```
2. RNDV RTS header can have `address == 0` in case of non-contig datatype or RNDV GET Zcopy scheme can't be used for data transfer.
this leads to test failure for DC and RC transports:
``` 
[ RUN      ] dcx/test_ucp_tag_match_rndv.exp_huge_mix/1 <dc_x>
[hpc-test-node-gpu01:20063:0:20063]     offload.c:540  Assertion `(rndv_rts_hdr->address != 0) || !(((req->send.datatype) & UCP_DATATYPE_CLASS_MASK) == UCP_DATATYPE_CONTIG)' failed

/labhome/dmitrygla/work_auto/ucx/src/ucp/tag/offload.c: [ ucp_tag_offload_sw_rndv() ]
      ...
      537     rndv_rts_hdr = ucs_alloca(rndv_hdr_len);
      538     packed_len   = ucp_tag_rndv_rts_pack(rndv_rts_hdr, req);
      539     ucs_assert((rndv_rts_hdr->address != 0) || !UCP_DT_IS_CONTIG(req->send.datatype));
==>   540     return uct_ep_tag_rndv_request(ep->uct_eps[req->send.lane], req->send.tag.tag,
      541                                    rndv_rts_hdr, packed_len, 0);
      542 }
      543

==== backtrace (tid:  20063) ====
 0 0x000000000009e87b ucp_tag_offload_sw_rndv()  /labhome/dmitrygla/work_auto/ucx/src/ucp/tag/offload.c:540
 1 0x00000000000948be ucp_request_try_send()  /labhome/dmitrygla/work_auto/ucx/src/ucp/core/ucp_request.inl:171
 2 0x000000000076d0e2 test_ucp_tag::send_nb()  /labhome/dmitrygla/work_auto/ucx/test/gtest/ucp/test_ucp_tag.cc:188
 3 0x0000000000714098 test_ucp_tag_match_rndv_exp_huge_mix_Test::test_body()  /labhome/dmitrygla/work_auto/ucx/test/gtest/ucp/test_ucp_tag_match.cc:702
 4 0x000000000054632a ucs::test_base::run()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/test.cc:280
 5 0x00000000005464ed ucs::test_base::TestBodyProxy()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/test.cc:306
 6 0x00000000006872e2 ucp_test::TestBody()  /labhome/dmitrygla/work_auto/ucx/test/gtest/ucp/ucp_test.h:144
 7 0x0000000000527c1c testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest-all.cc:3562
 8 0x0000000000522dfa testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest-all.cc:3598
 9 0x000000000050a111 testing::Test::Run()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest-all.cc:3635
10 0x000000000050a8ec testing::TestInfo::Run()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest-all.cc:3812
11 0x000000000050af7c testing::TestCase::Run()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest-all.cc:3930
12 0x00000000005117d4 testing::internal::UnitTestImpl::RunAllTests()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest-all.cc:5808
13 0x0000000000528ffa testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest-all.cc:3562
14 0x0000000000523c5c testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest-all.cc:3598
15 0x0000000000510410 testing::UnitTest::Run()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest-all.cc:5422
16 0x00000000005323d3 RUN_ALL_TESTS()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/gtest.h:20059
17 0x00000000005322bd main()  /labhome/dmitrygla/work_auto/ucx/test/gtest/common/main.cc:102
18 0x0000000000021c05 __libc_start_main()  ???:0
19 0x0000000000504a29 _start()  ???:0
=================================
```

## How ?

1. Fixes `if` statement that checks whether we need to use RNDV pipeline or not: RNDV pipeline has to be used when RNDV PUT Zcopy scheme isn't requested (i.e. `RNDV_SCHEME=auto`) and the send buffer is inaccessible from CPU and fragmented RNR send is received from a receiver (i.e. RTR size < the length of the send buffer).
2. Fixes `ucs_assert()` by adding a check for RNDV scheme used for data transfer.

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/e31725be9dd05ca99e4c55f47e60bc43a8e05897/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/050a3c16c85f3e4aa73d39365dd2fbc9e4fd3c9e/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/6acdb5bbce7553c856d3bb7eafc548bdff69ce2b/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/5b2a8f0c1f3e27f4871e6ea2425ac24b7b94d403/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/64024afdb842f58811f045ef3f6b471fa2a40ab5/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/eb213726e141aa44535ed6c7d5122c5bdde4ddfd/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/f48f6dc3660856f6ad89db7c8cd64f8078499592/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/a254203df6b14a7b337852387222fdb569197ae3/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/24f39f0e28e1f46e449b4cbb2f2ae25487697fb9/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/c10ecfe5a21cf7d378bc9e4d559ff0267d42a0b9/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/bcd4192be3075490c92cf3033a0125cb05efcca3/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/4a8931fb70b98c5e2e466fd5405d633596b53314/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/d6594402d9bb53e9a0c7e6ab12585df36903359b/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/37409bee9692742383acdc2319817635697cea9e/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/cc1c1f54e54b8495ef916a20a1f158832520a4eb/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/0ced2233a377d75d4819740c4dccd552906b2d6d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/393a4c3dafd08891257abfa734a5a1073b889040/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/59b0c82803c03d869e2be491ac714518fba4ba6e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/9de7aafd2c9a4830021013196ac93f646b12e6ea/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/a494c13e2063f580b43bc174c6fe81a4d8629782/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/53777396889e0b4e02db72c3f7f889f3d3486502/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/422bc43e483642301b3d9844bc1889df18e81357/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/b8c085bc6ffd9bf9421f2d28533ae363ab9b2f4e/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/db815f08b40620890bfb98bea3cad042dc2636c9/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3fafe1e5f465b3e38c7aa2fd2e0ec8b2/raw/76a2538c07c1a5f7f7f2b8802579411731e4dd96/hpc-test-node-new_W2) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/95029b3888084cf23fb398104da8c361789c9bbc/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/3fd2d456bc57f637990eff0504194f372ea170a0/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/e725dc05067e8ee32f4ab5c12f70e76742edb9d7/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/56c3e694178a56b33a152b2219d5d9ae9ee19af4/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/cdcca4d78c1f3fef10884fca1d842e0cc5c10ecc/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/aa19ed1159fe1d35c9f1d85a33f85af6e1276355/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/237b7d7681f1481abdc07d6fc5c4950e539d91b5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/7f11ffa62b062df123895c4020dcfabd7724dae5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/5a3ea6b82f4ab1e73c43390feef572ae5616a22a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/6cc4cc37f0c2808216a812b95007194719e118a2/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/2cc2684de1453b7ace4dbdc8dd51c20d93b6703e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/87daaa8cd0841f72f4f0caa0146bdfba8ca82009/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/5db11566c6dffa9e50c0c336657ae2b225e5f08c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/5dbcb3f5ee9bd8c108ff352b0919b7cd4021b291/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/b553c4396ff9b4187b1a201a84751962d8440b86/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/b343cec12a1e99347b1f40ec9a42c09e505988f9/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/89a4586a89687a7a3c0ca50833644f7102730dcf/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/37ed469a74ad1c9a7029a9b6a4676948fe9feb90/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/a98da48d03d88f0a2fb1dad17cc8f84e5e07b3d1/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/44222a36e9521d9d7d91de6d76922e2581075a11/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/23436ce1e360bb64a5ea7a96265fe6272e7a9e4b/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/7c9f518cc3228fedb3ebf5b409ebcb16cd315bb3/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/ca89742bc11edeeadd431419b2d49fed8ab60ccb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/0647b25209857b6ee76065811b4fc37d9546cb20/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1fc25bdc611c48f7326c0d0b738eb935/raw/c69061efa58c4ac592900e0d45d2bb59b1cf4243/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/fe1d8ad9874ffbb0036a6f7e01b1c74352aa2e81/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/b318eb260484878bd780432eb69847df9e09439f/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/c1fbffa22316cdf5f3c5c7e1a316e50a06c24a39/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/c50a260fd588d90ed616b0c78b80a7d2317e6fc7/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/d84579b951e99b991e1d8b8a8e37dd706985731f/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/3f0573e3237c4b3df762fe47a861562702c66cf9/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/6e7031e57484335bade5834e188737dc416ff20d/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/535c8d721cd9b784928ac0d3eb34757961de1694/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/b176e7e7f3ad965648573d37b10aeac22cb11f61/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/d55a37c5c1f417eb110aea96b207cfd4f7139742/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/b902903db9a7479ceb9a60b8ad27be1ab1b4c710/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/2e3030fb56e7b6c8daf94578d54ffd929b3cde33/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/829b72169599cc95ce6dcadf3cef158221a51e5b/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/514445365ffa78e267f121d8bbfe44b6748d2f71/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/c4befbec5e8cf8972dfbcc7705434e338ab75aef/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/e890cdb089eeb04da5c957ed7f4976541753dd2a/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/7e45b0b0849ed2e16cbfbe1a92899137a946c05c/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/6d07b0a6ff3474dc9f37e71e1b2aa321b093e909/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/7ef095c0ec00911a7beda9ac877b092cb718737b/hpc-test-node-new_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/be3a14750314ef90e8a70a27180ad6976aa897f1/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/fbd0f8bda6f86c017f06ee16e15e8f31ae3bafb8/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/95140f03fbecc90c06525f36adc26aeabecf4dd5/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/c02ce5e029198463e3d9a6fed43b1c57668b4f29/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/578239c5851fca7f8ac58b0ebae29685cb13b328/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1a019cd462c3ddf941af76f525a2abb1/raw/17db194f1a5bb2ca1f4da21e938988b18575b7ad/hpc-test-node-new_W0) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/f243d87916b78703503805c6e63fd77fe95753dc/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/d9fff6e13cd207fdbaefa1964a150ecf3b61956a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/fa61faa33dd1e089a75c0b983537a25a6b5be0a6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/f31ad1e1a7ae0d4b6283ef835e52bef3f4ce009c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/038129e71c9bdcca6ba7dd5a2e9c27ef91185ba8/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/e998330343a7f7c3fc23c9e8bf5f63d362466141/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/81297e73c5a16e631fea4ed0527121155302baa8/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/f064999343476af96c2a537b4aa8ec9f2c96f774/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/01e74a42e9e3791cd8656b4fc55e79218f99998a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/30749907a4a862e68678085951bc76804a2f5058/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/563c4d2a75faeb81577329831d1c7b49b2b3e052/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/8b7cb5313d3ee11966e20d01efcc1de5e4eee2cf/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/506d576cafb2b90bf8e0d9172cf0bf39600b1514/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/5e6a1588652eb3c117f5d29bc75407da2c220568/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/5e31b8e6a4b8ef942d34fb4cf85d96b1b4bb4d86/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/b5231903f909028f8b31402af1731062af8dd56b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/38bab0fbe15ac4af3470d73166de8f9aac154f69/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/e6ee64dc0ffd4cc8496e94614a9fb05aa8300cd2/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/aff48bbc7c5feb6ebff6506b918aae776e231407/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/380d70269d620258e887364d5684546a54e348fb/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/f0b91b9ba578591c8ba05013ee80f048b9cb7a2f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/6a800c8bf44cb6e59ded999dada79d7564e8ae45/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/b85d4c77fb1dca758be2bd07a4a569ee84a9b4f4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/4224e1fc5b059694da1e1480edc78a2f72315501/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/70669bd014beecbbad920619460b9a60/raw/c1903efca93d590597fc5c48734269dab0fd8174/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/e6ca838df4be4fc9bd4bb89d7df593678481ee73/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/3df5b5c260bb19fb9243ecfb18431c5d98b6a6fd/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/26756b4085c3858e4798d646e4d10cca308821aa/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/2969bd9a9c42b457bc911052fe65730930315cc8/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/6297090ac7d413706d4f6d2cc6049bd40ddb1dd2/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/ddec3c29ddcd9a3dba0d8f25def8272b72e4421a/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/4d4bc26472ad5ea84f6292387ae09070cebf9888/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/6a865c3815aa8b47bf3264191c32a455d106ff37/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/30d25d7e40ce8ecc89ed0b29342d8c2428d05625/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/a7f5e6a8a272733a8cd2d1b27d96e36ed840d8a8/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/dfdda77f2b0f50ec2eccaeed50639b94ffd1a072/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/6f38a385fab6e2d1ff4d21915819f5169198efbe/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/3a44fb2d693cded5cf58eaa27b75ae9e624ab345/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/1cb34cd696ffa3d318e8543cc396b8c67b4d30e0/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/bd669537aff44957b9b6dd0f3356b63cfe45dc56/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/3009680e407ac97b26f740542143ebc47d4aa483/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/7e87e5a8a3ce4eac0a2fc3ea726163e0c40676f5/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/b38ea6191cb721c02ad41768abb3161bf5ea8023/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/2e386c660da234b69a044307652fe07056953002/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/84fe75663a477584a50c2b0a14defe016f9197c4/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/9386de28fdd5aa9dc1c3e42456f33bfcb9355254/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/17258d2d2eb7d0bfc01c85b1df94a48001cc307b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/bee955e08c514dd6d272c842825f3a43c68e0760/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/8e0b7522f579c9c6c69f503c17ccdabcfd6d5965/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/87ff6fe4b1d1d4717682b316525781af/raw/c66cd6cb9f6112d766e90d949e44edf8da88d6f3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@brminich @hopoepg could you review pls?

**Comment by dmitrygx** [comment]
@brminich @hoopoepg @burredy could you review pls?

**Comment by dmitrygx** [comment]
@brminich @hoopoepg @bureddy could you review pls?

File: src/ucp/tag/rndv.c [hunk 1]
```diff
@@ -948,9 +958,10 @@ UCS_PROFILE_FUNC_VOID(ucp_rndv_frag_send_put_completion, (self, status),
     }
 
     req->send.state.dt.offset += freq->send.length;
+    ucs_assert(req->send.state.dt.offset <= req->send.length);
 
     /* send ATP for last fragment of the rndv request */
-    if (req->send.length == req->send.state.dt.offset) {
+    if (req->send.state.dt.offset == req->send.length) {
```
Comment (brminich) [inline src/ucp/tag/rndv.c]: no need to swap

File: src/ucp/tag/rndv.c [hunk 2]
```diff
@@ -104,8 +96,16 @@ static size_t ucp_tag_rndv_rtr_pack(void *dest, void *arg)
 
     /* Pack remote keys (which can be empty list) */
     if (UCP_DT_IS_CONTIG(rreq->recv.datatype)) {
+        /* Adjust the real receive length by the length that is expected
+         * to be sent (i.e. it has to be minimum between the length of
+         * the receive buffer and the length specified in the RTS header)
```
Comment (brminich) [inline src/ucp/tag/rndv.c]: this looks like invalid assumption. It is possible that receive and send buffer lengths will be different. And `ucp_tag_rndv_rtr_pack` takes the length of receive buffer

File: src/ucp/tag/rndv.c (hunk 1 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: done

File: src/ucp/tag/rndv.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: why? a receiver registers minimum between receive size and send size (from RTS)
we have to ask send to us only send size rather than recv size (if they are not equal)

**Comment by dmitrygx** [comment]
> what is required for rc/dc tests to fail?

@brminich need to do RNDV when send and receive sizes < minimum GET Zcopy sizes supported by UCT and `RNDV_SCHEME=auto`

File: src/ucp/tag/offload.c [hunk 3]
```diff
@@ -537,7 +537,9 @@ ucs_status_t ucp_tag_offload_sw_rndv(uct_pending_req_t *self)
     rndv_hdr_len = sizeof(ucp_rndv_rts_hdr_t) + ucp_ep_config(ep)->tag.rndv.rkey_size;
     rndv_rts_hdr = ucs_alloca(rndv_hdr_len);
     packed_len   = ucp_tag_rndv_rts_pack(rndv_rts_hdr, req);
-    ucs_assert((rndv_rts_hdr->address != 0) || !UCP_DT_IS_CONTIG(req->send.datatype));
+    ucs_assert((rndv_rts_hdr->address != 0) || !UCP_DT_IS_CONTIG(req->send.datatype) ||
+               !ucp_rndv_is_get_zcopy(req->send.mem_type,
```
Comment (yosefe) [inline src/ucp/tag/offload.c]: how is this related to fixing tcp?

File: src/ucp/tag/rndv.c [hunk 4]
```diff
@@ -622,6 +630,8 @@ static void ucp_rndv_send_frag_rtr(ucp_worker_h worker, ucp_request_t *rndv_req,
         freq->recv.state.dt.contig.md_map = 0;
         freq->recv.frag.rreq              = rreq;
         freq->recv.frag.offset            = offset;
+        ucp_rndv_set_recv_tag_info(freq, rreq->recv.tag.info.sender_tag,
```
Comment (yosefe) [inline src/ucp/tag/rndv.c]: why is this needed for fragments? it worked without it before..
AFAIR pipelined RDNV is not used for TCP.. ?
seems we need to adjust frag size by sender length, in line 605?

File: src/ucp/tag/rndv.c [hunk 5]
```diff
@@ -716,7 +725,8 @@ UCS_PROFILE_FUNC_VOID(ucp_rndv_matched, (worker, rreq, rndv_rts_hdr),
         }
         /* put protocol is allowed - register receive buffer memory for rma */
         ucp_request_recv_buffer_reg(rreq, ucp_ep_config(ep)->key.rma_bw_md_map,
-                                    ucs_min(rreq->recv.length, rndv_rts_hdr->size));
+                                    ucs_min(rreq->recv.length,
```
Comment (yosefe) [inline src/ucp/tag/rndv.c]: this change does not seem needed as well, rreq->recv.tag.info.length and rndv_rts_hdr->size are the same

Comment (brminich) [reply src/ucp/tag/rndv.c]: can't they be different when receiver posts bigger than actual data buffer?

Comment (yosefe) [reply src/ucp/tag/rndv.c]: line 669 sets req->recv.tag.info.length to rndv_rts_hdr->size, i don't see anything else changes it..

File: src/ucp/tag/offload.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/tag/offload.c]: it fixes another problem reproduced when I added the test (DC/RC related):
https://github.com/openucx/ucx/pull/4579#issue-352777513 (the second item in `WHY?`)
unfortunately, can't split it to another PR as the one test reproduces two problems

File: src/ucp/tag/rndv.c (hunk 5 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: > line 669 sets req->recv.tag.info.length to rndv_rts_hdr->size, i don't see anything else changes it..

I just wanted to align it with the place where we assign value to RTR length to make it consistent

File: src/ucp/tag/rndv.c (hunk 4 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: > seems we need to adjust frag size by sender length, in line 605?

looks like smth similar is done by #4450 (it's adjusted on a sender side)

> AFAIR pipelined RDNV is not used for TCP.. ?

this PR fixes it to not use pipelined RNDV for TCP when send or recv buffer isn't CUDA

> why is this needed for fragments? it worked without it before..

this is needed to have this value initialized and use it on `src/ucp/tag/rndv.c:99` as it common code for PIPELINE and PUT Zcopy

File: src/ucp/tag/rndv.c (hunk 5 above)
Comment (yosefe) [reply src/ucp/tag/rndv.c]: pls revert, "info" is used to return sender len to user, it should not be used for anything else

Comment (brminich) [reply src/ucp/tag/rndv.c]: right, thought it was just `rreq->recv.length` before

File: src/ucp/tag/rndv.c (hunk 4 above)
Comment (yosefe) [reply src/ucp/tag/rndv.c]: > this PR fixes it to not use pipelined RNDV for TCP when send or recv buffer isn't CUDA

Can we skip this function altogether in this case?
it's weird that we call pipelined flow on receiver but make sender think it's regular rndv put

Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: > Can we skip this function altogether in this case?

then we need some indication in `ucp_tag_rndv_rtr_pack()` what the protocol will be used (RNDV pipeline or RNDV PUT Zcopy) to do smth like:
```
rndv_rtr_hdr->size    = (!rndv_pipeline ? ucs_min(rreq->recv.length,
                                                  rreq->recv.tag.info.length) : 
                         rreq->recv.length);
```

> it's weird that we call pipelined flow on receiver but make sender think it's regular rndv put

the receiver asks the sender to do RNDV pipeline scheme if receive buffer is CUDA and (`RNDV_SCHEME == auto`), RTR size in this case < the send buffer size in this case, so sender uses RNDV pipeline scheme.

Comment (yosefe) [reply src/ucp/tag/rndv.c]: can we add length field to ucp_request::send.rndv_rtr ?

Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: > can we add length field to ucp_request::send.rndv_rtr ?

sure, this is under `union` where there are other structures that are larger (e.g. `struct rndv_put`)
done

File: src/ucp/tag/rndv.c (hunk 5 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: done

**Comment by bureddy** [comment]
looks fine to me. observed same issue in  https://github.com/openucx/ucx/pull/4450 Jenkins

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/6c2a159ea1bc1aaea23d19e893c19c099d8af201/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/cf57a6dfe0098a67dcf8e42923077c7d831bfdd5/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/fb79410398b754bb2ccff2d434b7a21466be6c46/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/d32b2b11ed3e6faf4f4f0d43059480cbcf26cc9e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/91ff846855f0ec751505c6c8c39f3ee8765ba3e0/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/985c3693d70a5a6290455135542c5ed7c6a3532d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/9f98d648f5e327f32365e07a3463183d001daa05/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/7a710de66336a30fb00ae403449442f3713da853/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/01ea81fa5e091c3b35c813109cce85d595b32f3a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/830b33b4b05f21d52ab98dbfc80e8aed0dccf393/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/bf153c7b0dc1fd3d3abcd98798ab8a876457c0b9/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/5a9337f17509954bdf4b223c1bbf5ebab7602d28/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/ae228b5eb171520fee4af7a4da116d825b8ec567/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/29b7647918a2bcacef1dc7aa04c1ffc61330a4fa/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/f7c80d29d1ee0246b0c82cf9f7949842bf51eb4b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/9e415e5cfab1bc1ef190403665f7456c60ab4091/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/3b3266e149783868832f9b413d136a34bfeedad8/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/fcb81d54f6ad5ad2744c4b41656178983e10cc32/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/dff58e90584aca974de82b447a54317e49663d13/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/02aee3eb8e9e2b4ed1dde63fec74c51e4963d732/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/7033cd50e0f45988614ae8362c1a95d8deb490d1/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/654270291aa84759128c8b58bfca57c5990710ce/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/2ea4efbfcefa563c5222e020c071f68766484eed/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/df8b95051e04b136192ee3580a57d974cba2a171/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/50af7ebf6018576567c8b2c19b203eb6/raw/076839cc313c827682cf4dbcde1b31a830a51b54/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
> looks fine to me. observed same issue in #4450 Jenkins

@bureddy thank you!
@brminich @yosefe could you review pls?

File: test/gtest/ucp/test_ucp_tag_match.cc [hunk 6]
```diff
@@ -446,7 +450,46 @@ UCS_TEST_P(test_ucp_tag_match, sync_send_unexp) {
...
+    {
+        std::vector<ucp_test_param> result;
+        generate_test_params_variant(ctx_params, name,
+                                     test_case_name + "/rndv_" +
+                                     rndv_schemes[RNDV_SCHEME_AUTO],
+                                     tls, RNDV_SCHEME_AUTO, result);
+        generate_test_params_variant(ctx_params, name,
+                                     test_case_name + "/rndv_" +
+                                     rndv_schemes[RNDV_SCHEME_PUT_ZCOPY],
+                                     tls, RNDV_SCHEME_PUT_ZCOPY, result);
```
Comment (brminich) [inline test/gtest/ucp/test_ucp_tag_match.cc]: maybe add GET as well (for those who supports it)?

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_tag_match.cc]: @brminich yes, it's good idea
I copied the same approach as in `test_ucp_tag_xfer.cc` - looks like they only use "auto" and "put_zcopy" to not test GET Zcopy twice.
Only TCP doesn't support GET Zcopy, will check a way on how to check the support for a specific scheme before ucp_init() done

Comment (brminich) [reply test/gtest/ucp/test_ucp_tag_match.cc]: you can generate variants for all and then skip if not supported

File: src/ucp/core/ucp_request.h [hunk 7]
```diff
@@ -167,7 +167,8 @@ struct ucp_request {
 
                 struct {
                     uintptr_t         remote_request; /* pointer to the send request on receiver side */
-                    ucp_request_t     *rreq;
+                    ucp_request_t     *rreq;          /* pointer to the receive request */
+                    size_t            length;         /* the length of the data that could be sent */
```
Comment (yosefe) [inline src/ucp/core/ucp_request.h]: .. that should be fetched from sender side */

File: src/ucp/tag/rndv.c [hunk 8]
```diff
@@ -420,7 +413,8 @@ UCS_PROFILE_FUNC(ucs_status_t, ucp_rndv_progress_rma_get_zcopy, (self),
         ucp_rndv_recv_data_init(rndv_req->send.rndv_get.rreq,
                                 rndv_req->send.length);
         ucp_rndv_req_send_rtr(rndv_req, rndv_req->send.rndv_get.rreq,
-                              rndv_req->send.rndv_get.remote_request);
+                              rndv_req->send.rndv_get.remote_request,
+                              rndv_req->send.length);
```
Comment (yosefe) [inline src/ucp/tag/rndv.c]: before this PR it was rreq->recv.length, is that the same?

File: src/ucp/tag/rndv.c [hunk 9]
```diff
@@ -715,15 +709,17 @@ UCS_PROFILE_FUNC_VOID(ucp_rndv_matched, (worker, rreq, rndv_rts_hdr),
             }
         }
         /* put protocol is allowed - register receive buffer memory for rma */
+        ucs_assert(rndv_rts_hdr->size <= rreq->recv.length);
```
Comment (yosefe) [inline src/ucp/tag/rndv.c]: why assert? this should be MESSAGE_TRUNCATED error

File: src/ucp/tag/rndv.c [hunk 10]
```diff
@@ -715,15 +709,17 @@ UCS_PROFILE_FUNC_VOID(ucp_rndv_matched, (worker, rreq, rndv_rts_hdr),
...
         ucp_request_recv_buffer_reg(rreq, ucp_ep_config(ep)->key.rma_bw_md_map,
-                                    ucs_min(rreq->recv.length, rndv_rts_hdr->size));
+                                    rndv_rts_hdr->size);
```
Comment (yosefe) [inline src/ucp/tag/rndv.c]: should do ucs_min

File: src/ucp/tag/rndv.c [hunk 11]
```diff
@@ -715,15 +709,17 @@ UCS_PROFILE_FUNC_VOID(ucp_rndv_matched, (worker, rreq, rndv_rts_hdr),
...
     }
 
     /* The sender didn't specify its address in the RTS, or the rndv mode was
      * configured to PUT, or GET rndv mode is unsupported - send an RTR and
      * the sender will send the data with active message or put_zcopy. */
     ucp_rndv_recv_data_init(rreq, rndv_rts_hdr->size);
-    ucp_rndv_req_send_rtr(rndv_req, rreq, rndv_rts_hdr->sreq.reqptr);
+    ucp_rndv_req_send_rtr(rndv_req, rreq, rndv_rts_hdr->sreq.reqptr,
+                          rndv_rts_hdr->size);
```
Comment (yosefe) [inline src/ucp/tag/rndv.c]: i think it should be ucs_min here as well

File: src/ucp/tag/rndv.c (hunk 9 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: it's checked before this (line 676), so here it has to be always `true`

File: src/ucp/tag/rndv.c (hunk 10 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: Since we already checked it on 676 line:
` if (ucs_unlikely(rreq->recv.length < rndv_rts_hdr->size)) {`

it's guaranteed that `rndv_rts_hdr->size <= rreq->recv.length` and we can directly use `rndv_rts_hdr->size` here

File: src/ucp/tag/rndv.c (hunk 11 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: we can directly use `rndv_rts_hdr->size` here

File: src/ucp/core/ucp_request.h (hunk 7 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_request.h]: 👍 
done

File: src/ucp/tag/rndv.c (hunk 8 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: no, this is different values
`rreq->recv.length` - posted by a receiver
`rndv_req->send.length` - received from RTS

here is just a fallback from GET to PUT scheme, so we should use `rndv_req->send.length` in order to use RNDV PUT instead of RNDV pipeline
we should post send

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/26a0eb5bd17a348771e277b8dd9154a7d8c055eb/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/5d6b8a0e124fd60e440bad0c4a835ca4e008bc3b/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/eaf7507b798f48e6b9e924207b376f55c4d3943a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/4e80b1ee28dcdf7982f5bb0fc6f1d6644e4b8f49/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/51ce1b412216c166c09cb221a12d87928842ab9b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/aea280e4e22eb400c41dd7681d05e2d46fa31e21/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/0a7d2f14ee5421dc1c5e29cf684b43da2ca3de03/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/3273f62aa3a702e5e6709a0e20b82cee44484e6a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/a932503a6f3ec0b6a91140c2bbc5e1f5ac08661d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/49a726d6fc45553d35ef45d08c3dd05b33539721/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/401596ed9067956c0feeea5bd3a201395321ffb0/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/0be8f5bbc9b2cd9c5255ecd5cdf0ebddfbd1560a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/6d60961a56ade7c3197861ff218f91e49b319440/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/cd3291c45b512c2b03079cb2eb0ecc97f4282ade/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/6368f9adba49678c472ec0f9ecf9b6bd7db5f7a7/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/60e2c955d93b2b9dcf5c6fcbe76fe3be4312ed57/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/3ff7140a6c6b57915ac32f85c9d21abf07eee9f9/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/fbfac4f032e6195a6e341c6f95a42ffcf3cbe524/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/7b772e6f2c9bce5b3f75fd3cb0482e8e20628426/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/bb99b77cb51e9f7adb95a4c8215799ae52465692/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/74abe8d25d9cfad963097cbcd3c8a3abdb50fe7a/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/74d4e1d0a59159fe35e4e3bd870d3e5b8971fc0b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/978fa2be4e77093217f20b84068e640adbb58c4a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/b9efe611839cb6c7ec55831981e44129c6afa616/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8871b44be74dd44f2db8848fac075a0f/raw/40a8758c7d1c6357000a5d2be5d4b0cec59a071b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/3f38b3c1ec8b0058381da2c1af67ca54374a39ce/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/196ad20767945816eeca8ee80cb2fc04f8660666/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/afd8ecc94c55857877b963f77321dc55537c2d44/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/56145d1f5c8874a40d74560f413cfb845de8a72d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/f5df301554c1e9516bd9bfa23b3a49ffcb2361c4/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/71e6bbf3e3a16faf3cfddcefaf0ee3137210037c/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/71b0932cadf1641ad5b3e04c9e6414359ba219e6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/90da13f16788f9097e0e74e0a7ad95f2e3aee6b8/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/1919cdb07e08aeef12296e3c9f67e46a75a93c53/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/3b566a6a85764a27ac0c449d3bb941abf5bd97ba/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/6b9710f9310b6c7a9eca25b174cb9a68ec428b53/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/ef967330a7bd84b070f9c21ea1a756fbd7bdccd3/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/f7efe05a2cc67d589c463f01c3086fbe91cfa323/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/20ec80935f5315d3502f17ad49f08c205a7f143f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/2b0aee11672efbce366166ad3e5cb2250db992dd/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/7a43826b9385e7956d3119cb1377f48815c21b8d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/12b27d01e0d916e87b23c4d9d9cd3d73b84ef23a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/26f494ed31813e3455316e5337e6c1e0d64e7e4b/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/32752d0df9748bdb76b59cdcbf9db3ace8c6026a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/f46b4b45e718387b916c83a681543f94cc12a4d9/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/8f783925c1fb07701fb8334e8004027c203a52f2/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/f2d949bdd7755c7cc1ba182d00a506491852e868/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/27cc298310284d3cfc9dbdc0730754c360867689/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/84bf512ee4a7c0aa7d8c6648824a88c8165602bf/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0865a8c0620464340e2eeca19fd60bc5/raw/de49dc28454de9c13225f02281ed3bdfb2752aff/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@yosefe could you take a look? your comments were fixed/answered

File: test/gtest/ucp/test_ucp_tag_match.cc (hunk 6 above)
Comment (brminich) [reply test/gtest/ucp/test_ucp_tag_match.cc]: where do u check if certain RNDV scheme is supported?

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_tag_match.cc]: > where do u check if certain RNDV scheme is supported?

actually, there are no needs to check it, since UCP has a fallback on SW RNDV if certain RNDV scheme is not supported

File: src/ucp/tag/rndv.c (hunk 8 above)
Comment (yosefe) [reply src/ucp/tag/rndv.c]: what is the point to send back sender's buffer size?
how would the sender know the receive buffer size?

File: src/ucp/tag/rndv.c (hunk 9 above)
Comment (yosefe) [reply src/ucp/tag/rndv.c]: ok

File: src/ucp/tag/rndv.c (hunk 8 above)
Comment (yosefe) [reply src/ucp/tag/rndv.c]: ok, it's because when sender size is too big we just reject immediately? so it's to distinguish from pipelined protocol?

File: src/ucp/tag/rndv.c (hunk 10 above)
Comment (yosefe) [reply src/ucp/tag/rndv.c]: ok

File: src/ucp/tag/rndv.c (hunk 8 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: > what is the point to send back sender's buffer size?
> how would the sender know the receive buffer size?

do you mean that we need to do `MIN(TAG_SEND::length; RTR::length)` on a sender side?
but then we send in an RTR packet a length that we couldn't really receive, since we register a receive buffer with the length = `RTS::length`

Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: > ok, it's because when sender size is too big we just reject immediately? 

yes, it's and we could use it directly w/o doing MIN

> so it's to distinguish from pipelined protocol?

yes, then a sender won't use RNDV pipeline protocol, since `TAG_SEND::length == RTR::length`
when a receiver is going to use RNDV pipeline protocol (e.g. a rceive buffer is CUDA buffer), it sends `RTR::length = MIN(frag_size, receive_buf_size)`

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/174ce806d21017783e61b9b613481a5e6a7a7234/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/cbffd92d1fa73cc2c0d87ecc02309f37520607a3/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/bf17aae039aaedf3e0112f434fe3ff38e1d95aa5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/ab4d435d52799f31f72ea3a7cdfb4ec487506c82/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/8c30605e15494264cf94e28a7755c36ea72ebb01/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/7f955fa6e52198e126cc5b83949a6a6eea99aa9b/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/c2faa4efaf6ca1f5b844d223a7eb1c5af645da44/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/10a7b5cd7994c522fede628592d0a703b9685af7/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/18f75d4e0cce63abc2e8a590ecb80de0adf736af/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/7e84a3891ca5a20a85a9019ee37d31ed95313c44/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/0a0579ed23d2b722ea9b2634cb7c3916f3706832/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/086f0e29432918fa40e49b1bc132adfb155635ce/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/a4f1ae761298378284f762b3fdb73398ce1df0f6/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/cd61907319b422d2ade1a4b07316453b28481d0e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/8c4814ed956c3e03f86757b481fddee7b09fd526/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/103f007f686b9bac3f34a7e039deaa33b729f5eb/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/66d3e60ab6a9aa4420e90b258af2b1a4e9dd2d22/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/9782533701a8f00a26995aaa8b5de3c365d56df7/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/516afd4c8bfae43bfc8f7702c09eda90b259dc2e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/7bf3866811f60a1dd6bb01c4c30e8a2ad373895b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/bc6d897dcbb4d4a0d15122aebb584a1dc1f844e3/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/ea12ebc8d62d160f7a8f630705f7d7e1195417b0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/7f5635ee2a46c46a45be8bccf0c48221689ea9e5/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/8c5b4177245bba02d75e2f81c4d92616c47d2334/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/12f0eec2c0903a73af048a3ed00eb069/raw/f7a12c2117e25d9d34dd35d7d86791d9070a2bec/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
VM storage issue: `[2019-12-21T12:13:51.702Z] error: Bad owner/group: /scrap/jenkins/workspace/ucx/build-test/ucx-1.8.0.tar.gz`
bot:pipe:retest
