### PR TITLE
UCT/TCP: Handle peer failure in case of CONNECT_TO_EP

### LINKED ISSUE #6015: tcp/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/5 <tcp/tag,cm,mt> fails on hpc-arm-cavium-jenkins
### Describe the bug
http://hpc-master.lab.mtl.com:8080/blue/rest/organizations/jenkins/pipelines/ucx/runs/8544/nodes/64/steps/383/log/?start=0
```
[2020-12-10T09:10:59.014Z] [ RUN      ] tcp/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/5 <tcp/tag,cm,mt>
[2020-12-10T09:10:59.014Z] [     INFO ] Testing 10.209.44.19:0
[2020-12-10T09:10:59.014Z] [     INFO ] server listening on 10.209.44.19:39733
[2020-12-10T09:10:59.014Z] [     INFO ] < UCT EP 0xffff380022d0 isn't associated with UCP EP and was not scheduled to be discarded on UCP Worker 0xfafe20 >
[2020-12-10T09:10:59.014Z] [hpc-arm-cavium-jenkins:10991:0:10991]      tcp_cm.c:83   Assertion `(old_conn_state == UCT_TCP_EP_CONN_STATE_RECV_MAGIC_NUMBER) || ((old_conn_state == UCT_TCP_EP_CONN_STATE_CLOSED) && (ep->conn_retries == 0) && (ep->flags & UCT_TCP_EP_FLAG_CONNECT_TO_EP))' failed
[2020-12-10T09:10:59.014Z] ==== backtrace (tid:  10991) ====
[2020-12-10T09:10:59.014Z]  0  /scrap/jenkins/workspace/ucx-5/build-test/src/ucs/.libs/libucs.so.0(ucs_fatal_error_message+0xe8) [0xffffbe725334]
[2020-12-10T09:10:59.014Z]  1  /scrap/jenkins/workspace/ucx-5/build-test/src/ucs/.libs/libucs.so.0(ucs_fatal_error_format+0xbc) [0xffffbe7253f4]
[2020-12-10T09:10:59.014Z]  2  /scrap/jenkins/workspace/ucx-5/build-test/src/uct/.libs/libuct.so.0(uct_tcp_cm_change_conn_state+0x2f8) [0xffffbe6c5750]
[2020-12-10T09:10:59.014Z]  3  /scrap/jenkins/workspace/ucx-5/build-test/src/uct/.libs/libuct.so.0(uct_tcp_ep_connect_to_ep+0xb8) [0xffffbe6bff5c]
[2020-12-10T09:10:59.014Z]  4  /scrap/jenkins/workspace/ucx-5/build-test/src/ucp/.libs/libucp.so.0(ucp_wireup_connect_local+0x1c4) [0xffffbe61019c]
[2020-12-10T09:10:59.014Z]  5  /scrap/jenkins/workspace/ucx-5/build-test/src/ucp/.libs/libucp.so.0(+0x977f4) [0xffffbe6177f4]
[2020-12-10T09:10:59.014Z]  6  /scrap/jenkins/workspace/ucx-5/build-test/src/ucs/.libs/libucs.so.0(+0x1e254) [0xffffbe71e254]
[2020-12-10T09:10:59.014Z]  7  /scrap/jenkins/workspace/ucx-5/build-test/src/ucp/.libs/libucp.so.0(ucp_worker_progress+0x48) [0xffffbe5b4a48]
[2020-12-10T09:10:59.014Z]  8  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x83fb50]
[2020-12-10T09:10:59.014Z]  9  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x836ce0]
[2020-12-10T09:10:59.014Z] 10  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x8082b0]
[2020-12-10T09:10:59.014Z] 11  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x580508]
[2020-12-10T09:10:59.014Z] 12  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x563d1c]
[2020-12-10T09:10:59.014Z] 13  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x561468]
[2020-12-10T09:10:59.014Z] 14  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x561174]
[2020-12-10T09:10:59.014Z] 15  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x560ec0]
[2020-12-10T09:10:59.014Z] 16  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x550d68]
[2020-12-10T09:10:59.014Z] 17  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x564b8c]
[2020-12-10T09:10:59.014Z] 18  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x550864]
[2020-12-10T09:10:59.014Z] 19  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x56cdac]
[2020-12-10T09:10:59.014Z] 20  /lib64/libc.so.6(__libc_start_main+0xf0) [0xffffbdf315d4]
[2020-12-10T09:10:59.014Z] 21  /scrap/jenkins/workspace/ucx-5/build-test/test/gtest/gtest() [0x53e074]
[2020-12-10T09:10:59.014Z] =================================
[2020-12-10T09:10:59.014Z] Sending notification to mikhailb@nvidia.com
[2020-12-10T09:11:00.931Z] [hpc-arm-cavium-jenkins:10991:0:10991] Process frozen...
```

### LINKED ISSUE #6161: TCP assertion failure in cm
http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/9273/pipeline/232

```
[2021-01-19T22:27:28.738Z] [ RUN      ] all/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/1 <all/tag,mt>
[2021-01-19T22:27:28.738Z] [     INFO ] Testing 10.209.44.19:0
[2021-01-19T22:27:28.738Z] [     INFO ] server listening on 10.209.44.19:41369
[2021-01-19T22:27:28.738Z] [     INFO ] < UCT EP 0xffff300011a0 isn't associated with UCP EP and was not scheduled to be discarded on UCP Worker 0x10290f0 >
[2021-01-19T22:27:28.738Z] [hpc-arm-cavium-jenkins:23377:0:23377]      tcp_cm.c:83   Assertion `(old_conn_state == UCT_TCP_EP_CONN_STATE_RECV_MAGIC_NUMBER) || ((old_conn_state == UCT_TCP_EP_CONN_STATE_CLOSED) && (ep->conn_retries == 0) && (ep->flags & UCT_TCP_EP_FLAG_CONNECT_TO_EP))' failed
[2021-01-19T22:27:28.738Z] 
[2021-01-19T22:27:28.738Z] /scrap/jenkins/workspace/ucx-8/contrib/../src/uct/tcp/tcp_cm.c: [ uct_tcp_cm_change_conn_state() ]
[2021-01-19T22:27:28.738Z]       ...
[2021-01-19T22:27:28.738Z]        77         break;
[2021-01-19T22:27:28.738Z]        78     case UCT_TCP_EP_CONN_STATE_ACCEPTING:
[2021-01-19T22:27:28.738Z]        79         ucs_assert((old_conn_state == UCT_TCP_EP_CONN_STATE_RECV_MAGIC_NUMBER) ||
[2021-01-19T22:27:28.738Z] ==>    80                    ((old_conn_state == UCT_TCP_EP_CONN_STATE_CLOSED) &&
[2021-01-19T22:27:28.738Z]        81                     (ep->conn_retries == 0) &&
[2021-01-19T22:27:28.738Z]        82                     (ep->flags & UCT_TCP_EP_FLAG_CONNECT_TO_EP)));
[2021-01-19T22:27:28.738Z]        83         uct_tcp_iface_outstanding_inc(iface);
[2021-01-19T22:27:28.738Z] 
[2021-01-19T22:27:30.652Z] ==== backtrace (tid:  23377) ====
[2021-01-19T22:27:30.652Z]  0 0x0000000000056b90 ucs_debug_print_backtrace()  /scrap/jenkins/workspace/ucx-8/contrib/../src/ucs/debug/debug.c:656
[2021-01-19T22:27:30.652Z]  1 0x0000000000028b44 uct_tcp_cm_change_conn_state()  /scrap/jenkins/workspace/ucx-8/contrib/../src/uct/tcp/tcp_cm.c:80
[2021-01-19T22:27:30.652Z]  2 0x0000000000020be4 uct_tcp_ep_connect_to_ep()  /scrap/jenkins/workspace/ucx-8/contrib/../src/uct/tcp/tcp_ep.c:725
[2021-01-19T22:27:30.652Z]  3 0x000000000001517c uct_ep_connect_to_ep()  /scrap/jenkins/workspace/ucx-8/contrib/../src/uct/base/uct_iface.c:489
[2021-01-19T22:27:30.652Z]  4 0x000000000001517c uct_ep_connect_to_ep()  /scrap/jenkins/workspace/ucx-8/contrib/../src/uct/base/uct_iface.c:489
[2021-01-19T22:27:30.652Z]  5 0x0000000000093cbc ucp_wireup_connect_local()  /scrap/jenkins/workspace/ucx-8/contrib/../src/ucp/wireup/wireup.c:316
[2021-01-19T22:27:30.652Z]  6 0x0000000000098cf4 ucp_cm_client_connect_progress()  /scrap/jenkins/workspace/ucx-8/contrib/../src/ucp/wireup/wireup_cm.c:468
[2021-01-19T22:27:30.652Z]  7 0x000000000004c554 ucs_callbackq_slow_proxy()  /scrap/jenkins/workspace/ucx-8/contrib/../src/ucs/datastruct/callbackq.c:400
[2021-01-19T22:27:30.652Z]  8 0x000000000004c554 ucs_callbackq_enter()  /scrap/jenkins/workspace/ucx-8/contrib/../src/ucs/datastruct/callbackq.c:62
[2021-01-19T22:27:30.652Z]  9 0x000000000004c554 ucs_callbackq_slow_proxy()  /scrap/jenkins/workspace/ucx-8/contrib/../src/ucs/datastruct/callbackq.c:402
[2021-01-19T22:27:30.652Z] 10 0x000000000003ac40 ucs_callbackq_dispatch()  /scrap/jenkins/workspace/ucx-8/contrib/../src/ucs/datastruct/callbackq.h:211
[2021-01-19T22:27:30.653Z] 11 0x000000000003ac40 uct_worker_progress()  /scrap/jenkins/workspace/ucx-8/contrib/../src/uct/api/uct.h:2436
[2021-01-19T22:27:30.653Z] 12 0x000000000003ac40 ucp_worker_progress()  /scrap/jenkins/workspace/ucx-8/contrib/../src/ucp/core/ucp_worker.c:2407
[2021-01-19T22:27:30.653Z] 13 0x0000000000873e18 ucp_test_base::entity::progress()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:870
[2021-01-19T22:27:30.653Z] 14 0x0000000000873eac ucp_test::progress()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:155
[2021-01-19T22:27:30.653Z] 15 0x0000000000857c58 test_ucp_sockaddr::one_sided_disconnect()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:497
[2021-01-19T22:27:30.653Z] 16 0x0000000000847214 test_ucp_sockaddr_destroy_ep_on_err_onesided_client_sforce_Test::test_body()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:913
[2021-01-19T22:27:30.653Z] 17 0x000000000059a43c ucs::test_base::run()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/test.cc:344
[2021-01-19T22:27:30.653Z] 18 0x000000000059a43c ucs::test_base::TestBodyProxy()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/test.cc:370
[2021-01-19T22:27:30.653Z] 19 0x000000000057cb2c HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3562
[2021-01-19T22:27:30.653Z] 20 0x000000000057cb2c testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3598
[2021-01-19T22:27:30.653Z] 21 0x00000000005712e4 testing::Test::Run()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3635
[2021-01-19T22:27:30.653Z] 22 0x00000000005713b4 testing::TestInfo::Run()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3812
[2021-01-19T22:27:30.653Z] 23 0x0000000000571524 testing::TestCase::Run()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3930
[2021-01-19T22:27:30.653Z] 24 0x0000000000575934 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:5808
[2021-01-19T22:27:30.653Z] 25 0x0000000000575c50 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:5725
[2021-01-19T22:27:30.653Z] 26 0x0000000000575c50 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:3618
[2021-01-19T22:27:30.653Z] 27 0x0000000000575c50 testing::UnitTest::Run()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest-all.cc:5422
[2021-01-19T22:27:30.653Z] 28 0x000000000051da78 RUN_ALL_TESTS()  /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/gtest.h:20059
[2021-01-19T22:27:30.653Z] 29 0x00000000000215d4 __libc_start_main()  :0
[2021-01-19T22:27:30.653Z] 30 0x000000000055bc1c _start()  :0
[2021-01-19T22:27:30.653Z] =================================
[2021-01-19T22:27:30.653Z] Sending notification to lgenkin@nvidia.com
[2021-01-19T22:27:38.783Z] [hpc-arm-cavium-jenkins:23377:0:23377] Process frozen...
[2021-01-20T00:52:36.326Z] make: *** [test] Terminated
script returned exit code 124
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Handle peer failure in case of CONNECT_TO_EP.

## Why ?

Fixes #6161 
Fixes #6015

## How ?

1. Fix minor comment typos and improve documentations of some code snippets.
2. Introduce `uct_tcp_ep_ptr_map_get()` function + common the function to check flags set.
3. Update `uct_tcp_ep_connect_to_ep()` (i.e. implementation of `uct_ep_connect_to_ep()` API function) to check whether an EP that has to accept a connection from a peer is on PTR MAP or not. If this EP doesn't exist in the EP PTR MAP, report `UCS_ERR_UNREACHABLE` status, since the peer was already connected and then disconnected from the local side.

### CODE REVIEW

**Comment by dmitrygx** [comment]
@brminich @hoopoepg could you review pls?

File: src/uct/tcp/tcp_ep.c [hunk 1]
```diff
@@ -714,16 +739,24 @@ ucs_status_t uct_tcp_ep_connect_to_ep(uct_ep_h tl_ep,
...
+        /* EPs which are created as CONNECT_TO_EP has to be full-duplex, set RX
          * capability as well as TX (that's set in uct_tcp_ep_connect()) */
         uct_tcp_ep_add_ctx_cap(ep, UCT_TCP_EP_FLAG_CTX_TYPE_RX);
 
         uct_tcp_ep_ptr_map_del(ep);
 
         /* Use remote peer connection sequence number value, since the EP has to
-         * send the CONN_REQ to the peer has to find its EP in the EP PTR map */
+         * send the CONN_REQ to the peer which has to find its EP in the its EP
+         * PTR map */
```
Comment (brminich) [inline src/uct/tcp/tcp_ep.c:750]: imo, previous comment was better, now you have double `its`

**Review by brminich — APPROVED** [review]
also please check code formatting warning

File: src/uct/tcp/tcp_ep.c (hunk 1 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: fixed

**Review by brminich — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

File: src/uct/tcp/tcp_ep.c [hunk 2]
```diff
@@ -714,16 +739,24 @@ ucs_status_t uct_tcp_ep_connect_to_ep(uct_ep_h tl_ep,
...
         uct_tcp_ep_ptr_map_del(ep);
 
-        /* Use remote peer connection sequence number value, since the EP has to
-         * send the CONN_REQ to the peer has to find its EP in the EP PTR map */
+        /* Use the peer's EP PTR map key, since the EP has to send the CONN_REQ
+         * to the peer which has to find an EP created for this connection in
+         * the EP PTR map */
         ep->cm_id.ptr_map_key = addr->ptr_map_key;
         return uct_tcp_ep_connect(ep);
+    } else if (uct_tcp_ep_ptr_map_get(iface, ep->cm_id.ptr_map_key) == NULL) {
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:753]: is it possible we just didn't receive a connect request (SYN) from remote side yet, at his point, and this is the reason ptr_map_get() would return NULL?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c:753]: if we didn't receive a connection request from a peer for some reason, it has to find the EP in PTR MAP (the found EP will be equal to an EP for which `uct_ep_connect_to_ep()` was called)
Also, during debugging the issue I saw that we were connected with the peer (so, our EP was deleted from PTR MAP) and disconnected then

**Comment by dmitrygx** [comment]
@yosefe fixed the comment as we discussed and moved a check of the existence of an EP in a PTR MAP at the beginning of the function after checking for `CONNECTED` state.
is it ok now?

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe @brminich ok to merge?
