### PR TITLE
UCT/UCS/KEEPALIVE: Fix overflow when recording file create time

### LINKED ISSUE #7269: fp failures in ucs_time_from_sec()
### Describe the bug

We observe very occasional failures at startup (1 in 10^3) with the following call stack

 ```
59: Caught signal 8 (Floating point exception: floating-point invalid operation)
 59: ==== backtrace (tid: 164869) ====
 59:  0 0x0000000000012b30 .annobin_sigaction.c()  sigaction.c:0
 59:  1 0x000000000006da96 ucs_time_from_sec()  /path/to/ucx-1.10.0/src/ucs/time/time.h:81
 59:  2 0x000000000006da96 ucs_time_from_timespec()  /path/to/ucx-1.10.0/src/ucs/time/time.h:90
 59:  3 0x000000000006da96 ucs_sys_get_file_time()  /path/to/ucx-1.10.0/src/ucs/sys/sys.c:1470
 59:  4 0x000000000001568b uct_mm_iface_t_init()  /path/to/ucx-1.10.0/src/uct/sm/mm/base/mm_iface.c:640
 59:  5 0x000000000001568b uct_mm_iface_t_new()  /path/to/ucx-1.10.0/src/uct/sm/mm/base/mm_iface.c:727
...
        MPI_Init()

```

```
/**
 * Convert seconds to UCS time units.
 */
static inline ucs_time_t ucs_time_from_sec(double sec)
{
  return (ucs_time_t)(sec * ucs_time_sec_value() + 0.5);
```
neither sec nor ucs_time_sec_value() appear invalid, but potentially the cast to unsigned long is problematic. 

### Steps to Reproduce
- Command line : N/A
- UCX 1.10

### Setup and versions
- AMD 7742 x86_64
- Red Hat Enterprise Linux release 8.3 (Ootpa)
- Kernel 4.18.0-240.10.1.el8_3.x86_64
 
### Additional information (depending on the issue)
- OpenMPI 4.1

### PR DESCRIPTION
**Pull request by yosefe**
## Why
Fix #7269

### CODE REVIEW

**Review by dmitrygx — APPROVED** [review]

File: src/uct/base/uct_iface.c [hunk 1]
```diff
@@ -842,21 +839,25 @@ static ucs_status_t uct_iface_schedule_ep_err(uct_ep_h ep, ucs_status_t status)
...
+        status = uct_ep_keepalive_create(pid, ka_p);
     } else {
-        status = ucs_sys_get_file_time((*ka)->proc, UCS_SYS_FILE_TIME_CTIME,
+        ka     = *ka_p;
+        status = ucs_sys_get_file_time(ka->proc, UCS_SYS_FILE_TIME_CTIME,
                                        &create_time);
-        if ((status != UCS_OK) || ((*ka)->start_time != create_time)) {
+        if ((status != UCS_OK) ||
+            (ka->start_time.tv_sec != create_time.tv_sec) ||
+            (ka->start_time.tv_sec != create_time.tv_sec)) {
```
Comment (hoopoepg) [inline src/uct/base/uct_iface.c:860]: tv_sec->tv_nsec ???

**Review by hoopoepg — APPROVED** [review]
