### PR TITLE
UCM/UCS/CONFIG: Fix compile errors for ppc64

### LINKED ISSUE #7618: compiling error
make install
Making install in src/ucm
make[1]: Entering directory '/home/jinchen/TEST/ucx-1.11.2/src/ucm'
Making install in .
make[2]: Entering directory '/home/jinchen/TEST/ucx-1.11.2/src/ucm'
  CC       event/libucm_la-event.lo
  CC       malloc/libucm_la-malloc_hook.lo
  CC       mmap/libucm_la-install.lo
  CC       util/libucm_la-replace.lo
  CC       util/libucm_la-log.lo
  CC       util/libucm_la-reloc.lo
  CC       util/libucm_la-sys.lo
  CC       bistro/libucm_la-bistro.lo
  CC       bistro/libucm_la-bistro_x86_64.lo
  CC       bistro/libucm_la-bistro_aarch64.lo
  CC       bistro/libucm_la-bistro_ppc64.lo
"bistro/bistro_ppc64.c", line 157: error #1144: arithmetic on pointer to void or function type
      func += 8;
           ^

"bistro/bistro_ppc64.c", line 158: error #1144: arithmetic on pointer to void or function type
      hook += 8;
           ^

2 errors detected in the compilation of "bistro/bistro_ppc64.c".

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix compile errors for ppc64.

## Why ?

Fixes #7618.

## How ?

1. Use `UCX_PTR_BYTE_OFFSET` macro for pointer arithmetic.
2. Check `__ppc_get_timebase()` function existence.

### CODE REVIEW

**Review by yosefe — APPROVED** [review]

File: src/ucs/arch/ppc64/cpu.h [hunk 1]
```diff
@@ -41,12 +41,12 @@ BEGIN_C_DECLS
 
 static inline uint64_t ucs_arch_read_hres_clock()
 {
-#ifndef HAVE_SYS_PLATFORM_PPC_H
+#if HAVE_DECL___PPC_GET_TIMEBASE && defined(HAVE___PPC_GET_TIMEBASE)
```
Comment (yosefe) [inline src/ucs/arch/ppc64/cpu.h:44]: WDYT to use one macro?
```
AC_CHECK_DECLS([__ppc_get_timebase_freq], 
               [AC_CHECK_FUNCS([__ppc_get_timebase_freq])], [],
               [[#include <sys/platform/ppc.h>]])

```

Then:
```
static inline uint64_t ucs_arch_read_hres_clock()
{
#ifdef HAVE___PPC_GET_TIMEBASE
    return __ppc_get_timebase();
#else
```

Comment (dmitrygx) [reply src/ucs/arch/ppc64/cpu.h]: done.
also, found that `AC_CHECK_FUNCS` couldn't be used for `__ppc_get_timebase()` - it reports that it is undefined.
using `AC_COMPILE_IFELSE` which allows including header file helps to fix it

File: config/m4/sysdep.m4 [hunk 2]
```diff
@@ -104,15 +104,30 @@ AC_CHECK_HEADERS([sys/platform/ppc.h])
...
+# PowerPC query for getting TB.
+# Note: AC_CHECK_FUNCS doesn't work for checking __ppc_get_timebase()
+#
+AC_COMPILE_IFELSE([AC_LANG_SOURCE([[
+                    #include <sys/platform/ppc.h>
+
+					int main(int argc, char** argv) {
+						__ppc_get_timebase();
+						return 0;
+					} ]])],
```
Comment (yosefe) [inline config/m4/sysdep.m4:122]: why check_funcs not enough?
maybe need ac_link_ifelse?

Comment (yosefe) [reply config/m4/sysdep.m4:122]: also indent seems wrong

Comment (dmitrygx) [reply config/m4/sysdep.m4]: > maybe need ac_link_ifelse?

done

> also indent seems wrong

fixed

File: config/m4/sysdep.m4 [hunk 3]
```diff
@@ -113,17 +113,18 @@ AC_CHECK_DECL([__ppc_get_timebase_freq],
...
+
+				int main(int argc, char** argv)
+                {
+					__ppc_get_timebase();
+					return 0;
+				} ]])],
+                [AC_MSG_RESULT([yes])
+                __ppc_get_timebase_happy=yes],
+                [AC_MSG_RESULT([no])
+                __ppc_get_timebase_happy=no])
```
Comment (yosefe) [inline config/m4/sysdep.m4:127]: use only spaces for indent

File: config/m4/sysdep.m4 [hunk 4]
```diff
@@ -96,12 +96,41 @@ AC_CHECK_DECLS([ethtool_cmd_speed, SPEED_UNKNOWN], [], [],
...
+if test "x$__ppc_get_timebase_happy" == xyes; then
+    AC_DEFINE([HAVE___PPC_GET_TIMEBASE], [1],
+              [Define to 1 if you have the `__ppc_get_timebase' function.])
```
Comment (yosefe) [inline config/m4/sysdep.m4:130]: can move this inside the AC_LINK_IFELSE?

File: config/m4/sysdep.m4 (hunk 3 above)
Comment (dmitrygx) [reply config/m4/sysdep.m4]: done

File: config/m4/sysdep.m4 [hunk 5]
```diff
@@ -96,12 +96,41 @@ AC_CHECK_DECLS([ethtool_cmd_speed, SPEED_UNKNOWN], [], [],
...
+              [#include <sys/platform/ppc.h>])
+
+
+#
+# PowerPC query for getting TB.
+# Note: AC_CHECK_FUNCS doesn't work for checking __ppc_get_timebase()
+#
+AC_LINK_IFELSE([AC_LANG_SOURCE([[
+                #include <sys/platform/ppc.h>
+
```
Comment (yosefe) [inline config/m4/sysdep.m4:118]: remove spaceline

File: config/m4/sysdep.m4 [hunk 6]
```diff
@@ -96,12 +96,41 @@ AC_CHECK_DECLS([ethtool_cmd_speed, SPEED_UNKNOWN], [], [],
...
+                int main(int argc, char** argv)
+                {
```
Comment (yosefe) [inline config/m4/sysdep.m4:120]: can put bracket on prev line to shorten

File: config/m4/sysdep.m4 (hunk 4 above)
Comment (yosefe) [reply config/m4/sysdep.m4:130]: to avoid __ppc_get_timebase_happy var

Comment (dmitrygx) [reply config/m4/sysdep.m4]: done

File: config/m4/sysdep.m4 [hunk 7]
```diff
@@ -96,12 +96,38 @@ AC_CHECK_DECLS([ethtool_cmd_speed, SPEED_UNKNOWN], [], [],
...
+                    __ppc_get_timebase();
+                    return 0;
+                } ]])],
+                [AC_MSG_RESULT([no])
+                 AC_DEFINE([HAVE___PPC_GET_TIMEBASE], [1],
+                           [Define to 1 if you have the `__ppc_get_timebase'\
+                            function.])],
```
Comment (yosefe) [inline config/m4/sysdep.m4:127]: [__ppc_get_timebase is defined in ppc.h]

File: config/m4/sysdep.m4 (hunk 5 above)
Comment (dmitrygx) [reply config/m4/sysdep.m4]: done

File: config/m4/sysdep.m4 (hunk 6 above)
Comment (dmitrygx) [reply config/m4/sysdep.m4]: done

File: config/m4/sysdep.m4 (hunk 7 above)
Comment (dmitrygx) [reply config/m4/sysdep.m4]: done

**Review by yosefe — APPROVED** [review]
