### PR TITLE
UCT/IB/DC: Refactoring of FC send operations

### LINKED ISSUE #6904: [MTT] dc_mlx5_ep.c:1414 Assertion `uct_dc_mlx5_iface_dci_has_outstanding(iface, ep->dci)' failed: iface 0x24bbec0 ep 0x25a3090: dci leak detected: dci=6 fc_wnd=128
Configuration
```
OMPI: 4.1.2a1
MOFED: MLNX_OFED_LINUX-5.1-2.5.8.0
Module: hpcx-gcc-debug (2021-06-04)
Test module: mtt-tests/hpcx-gcc
Nodes: jazz x2 (ppn=28(x2), nodelist=jazz[16,20])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210604_012514_102524_23116_jazz16.swx.labs.mlnx/html/test_stdout_AEhEKZ.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ompi/bin/mpirun -np 56 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to socket -x UCX_NET_DEVICES=mlx5_3:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc_x,self,sm -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/local/benchmarks/daily/next/2021-06-04/mtt-tests-gcc/installs/LFtZ/tests/imb-datacheck/mtt-tests.git/imb/src/IMB-MPI1 -npmin 56 -iter 1000 -mem 0.9`
 
Output:
```sh
Fri Jun  4 02:10:29 2021[1,0]<stdout>:#-----------------------------------------------------------------------------
Fri Jun  4 02:10:29 2021[1,0]<stdout>:# Benchmarking Alltoall 
Fri Jun  4 02:10:29 2021[1,0]<stdout>:# #processes = 56 
Fri Jun  4 02:10:29 2021[1,0]<stdout>:#-----------------------------------------------------------------------------
Fri Jun  4 02:10:29 2021[1,0]<stdout>:       #bytes #repetitions  t_min[usec]  t_max[usec]  t_avg[usec]      defects
Fri Jun  4 02:10:29 2021[1,0]<stdout>:            0         1000         0.04         0.04         0.04         0.00Fri Jun  4 02:10:29 2021[1,0]<stdout>:            1         1000        23.99        24.33        24.13         0.00
Fri Jun  4 02:10:29 2021[1,0]<stdout>:            2         1000        30.43        30.87        30.70         0.00
Fri Jun  4 02:10:29 2021[1,0]<stdout>:            4         1000        24.92        25.12        25.06         0.00
Fri Jun  4 02:10:29 2021[1,0]<stdout>:            8         1000        41.50        41.73        41.64         0.00
Fri Jun  4 02:10:29 2021[1,0]<stdout>:           16         1000        27.68        28.05        27.99         0.00
Fri Jun  4 02:10:29 2021[1,0]<stdout>:           32         1000        31.93        32.35        32.24         0.00
Fri Jun  4 02:10:29 2021[1,0]<stdout>:           64         1000        48.92        49.16        49.10         0.00
Fri Jun  4 02:10:30 2021[1,0]<stdout>:          128         1000        48.45        48.97        48.85         0.00
Fri Jun  4 02:10:30 2021[1,0]<stdout>:          256         1000        82.66        83.47        83.28         0.00
Fri Jun  4 02:10:30 2021[1,0]<stdout>:          512         1000       154.91       159.80       159.50         0.00
Fri Jun  4 02:10:31 2021[1,0]<stdout>:         1024         1000       224.64       230.38       229.76         0.00
Fri Jun  4 02:10:32 2021[1,0]<stdout>:         2048         1000       360.64       366.70       365.42         0.00
Fri Jun  4 02:10:35 2021[1,0]<stdout>:         4096         1000       762.10       778.82       774.93         0.00
Fri Jun  4 02:10:40 2021[1,0]<stdout>:         8192         1000      1274.73      1294.05      1289.68         0.00
Fri Jun  4 02:10:47 2021[1,0]<stdout>:        16384         1000      2429.25      2467.27      2456.96         0.00
Fri Jun  4 02:10:58 2021[1,0]<stdout>:        32768         1000      4715.55      4799.22      4785.59         0.00
Fri Jun  4 02:10:59 2021[1,46]<stderr>:[jazz16:168419:0:168419]  dc_mlx5_ep.c:1414 Assertion `uct_dc_mlx5_iface_dci_has_outstanding(iface, ep->dci)' failed: iface 0x24bbec0 ep 0x25a3090: dci leak detected: dci=6 fc_wnd=128
Fri Jun  4 02:11:03 2021[1,46]<stderr>:==== backtrace (tid: 168419) ====
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 0 0x000000000006e821 uct_dc_mlx5_ep_check_fc()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/dc/dc_mlx5_ep.c:1412
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 1 0x0000000000072e58 uct_dc_mlx5_ep_am_bcopy()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/dc/dc_mlx5_ep.c:375
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 2 0x0000000000095665 uct_ep_am_bcopy()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/api/uct.h:2844
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 3 0x0000000000095665 ucp_tag_eager_bcopy_multi()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucp/tag/eager_snd.c:141
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 4 0x000000000006deb1 uct_rc_iface_invoke_pending_cb()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/rc/base/rc_iface.h:528
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 5 0x000000000006deb1 uct_dc_mlx5_iface_dci_do_common_pending_tx()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/dc/dc_mlx5_ep.c:1252
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 6 0x000000000006e085 uct_dc_mlx5_iface_dci_do_dcs_pending_tx()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/dc/dc_mlx5_ep.c:1289
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 7 0x00000000000539c0 ucs_arbiter_dispatch_nonempty()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/datastruct/arbiter.c:321
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 8 0x000000000007b13a ucs_arbiter_dispatch()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/datastruct/arbiter.h:386
Fri Jun  4 02:11:03 2021[1,46]<stderr>: 9 0x000000000007b13a uct_dc_mlx5_iface_progress_pending()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/dc/dc_mlx5_ep.h:320
Fri Jun  4 02:11:03 2021[1,46]<stderr>:10 0x000000000007b13a uct_dc_mlx5_poll_tx()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/dc/dc_mlx5.c:254
Fri Jun  4 02:11:03 2021[1,46]<stderr>:11 0x000000000007b13a uct_dc_mlx5_iface_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/dc/dc_mlx5.c:271
Fri Jun  4 02:11:03 2021[1,46]<stderr>:12 0x000000000007b13a uct_dc_mlx5_iface_progress_ll()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/ib/dc/dc_mlx5.c:281
Fri Jun  4 02:11:03 2021[1,46]<stderr>:13 0x0000000000049f2a ucs_callbackq_dispatch()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/datastruct/callbackq.h:211
Fri Jun  4 02:11:03 2021[1,46]<stderr>:14 0x0000000000049f2a uct_worker_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/api/uct.h:2592
Fri Jun  4 02:11:03 2021[1,46]<stderr>:15 0x0000000000049f2a ucp_worker_progress()  /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucp/core/ucp_worker.c:2615
Fri Jun  4 02:11:03 2021[1,46]<stderr>:16 0x00000000000365bc opal_progress()  /build-result/src/hpcx-gcc-redhat7.6/ompi-535358e/opal/runtime/opal_progress.c:231
Fri Jun  4 02:11:03 2021[1,46]<stderr>:17 0x000000000004d52d sync_wait_st()  /build-result/src/hpcx-gcc-redhat7.6/ompi-535358e/ompi/../opal/threads/wait_sync.h:83
Fri Jun  4 02:11:03 2021[1,46]<stderr>:18 0x000000000004d52d ompi_request_default_wait_all()  /build-result/src/hpcx-gcc-redhat7.6/ompi-535358e/ompi/request/req_wait.c:243
Fri Jun  4 02:11:03 2021[1,46]<stderr>:19 0x000000000008da88 ompi_coll_base_alltoall_intra_basic_linear()  /build-result/src/hpcx-gcc-redhat7.6/ompi-535358e/ompi/mca/coll/base/coll_base_alltoall.c:672
Fri Jun  4 02:11:03 2021[1,46]<stderr>:20 0x0000000000005736 ompi_coll_tuned_alltoall_intra_dec_fixed()  /build-result/src/hpcx-gcc-redhat7.6/ompi-535358e/ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:407
Fri Jun  4 02:11:03 2021[1,46]<stderr>:21 0x000000000005f7a1 PMPI_Alltoall()  /build-result/src/hpcx-gcc-redhat7.6/ompi-535358e/ompi/mpi/c/profile/palltoall.c:110
Fri Jun  4 02:11:03 2021[1,46]<stderr>:22 0x000000000040ddb4 IMB_alltoall()  ???:0
Fri Jun  4 02:11:03 2021[1,46]<stderr>:23 0x00000000004072b8 IMB_init_buffers_iter()  ???:0
Fri Jun  4 02:11:03 2021[1,46]<stderr>:24 0x00000000004022c8 main()  ???:0
Fri Jun  4 02:11:03 2021[1,46]<stderr>:25 0x00000000000223d5 __libc_start_main()  ???:0
Fri Jun  4 02:11:03 2021[1,46]<stderr>:26 0x0000000000401d29 _start()  ???:0
Fri Jun  4 02:11:03 2021[1,46]<stderr>:=================================
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] *** Process received signal ***
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] Signal: Aborted (6)
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] Signal code:  (-6)
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 0] /lib64/libpthread.so.0(+0xf5d0)[0x7f75621595d0]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 1] /lib64/libc.so.6(gsignal+0x37)[0x7f7561db3207]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 2] /lib64/libc.so.6(abort+0x148)[0x7f7561db48f8]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 3] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/libucs.so.0(ucs_fatal_error_message+0x5d)[0x7f7553a867fd]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 4] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/libucs.so.0(ucs_fatal_error_format+0xd6)[0x7f7553a86986]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 5] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/ucx/libuct_ib.so.0(+0x6e821)[0x7f75533b4821]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 6] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/ucx/libuct_ib.so.0(uFri Jun  4 02:11:03 2021[1,46]<stderr>:ct_dc_mlx5_ep_am_bcopy+0xdf8)[0x7f75533b8e58]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 7] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/libucp.so.0(+0x95665)[0x7f7558222665]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 8] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/ucx/libuct_ib.so.0(uct_dc_mlx5_iface_dci_do_common_pending_tx+0x41)[0x7f75533b3eb1]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [ 9] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/ucx/libuct_ib.so.0(uct_dc_mlx5_iface_dci_do_dcs_pending_tx+0x25)[0x7f75533b4085]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [10] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/libucs.so.0(ucs_arbiter_dispatch_nonempty+0x100)[0x7f7553a7b9c0]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [11] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/ucx/libuct_ib.so.0(+0x7b13a)[0x7f75533c113a]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [12] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ucx/debug/lib/libucp.so.0(ucp_worker_progress+0x6a)[0x7f75581d6f2a]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [13] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ompi/lib/libopen-pal.so.40(opal_progress+0x2c)[0x7f75617ec5bc]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [14] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ompi/lib/libmpi.so.40(ompi_request_default_wait_all+0xed)[0x7f75623b352d]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [15] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ompi/lib/libmpi.so.40(ompi_coll_base_alltoall_intra_basic_linear+0x298)[0x7f75623f3a88]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [16] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ompi/lib/openmpi/mca_coll_tuned.so(ompi_coll_tuned_alltoall_intra_dec_fixed+0xb6)[0x7f755082f736]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [17] /hpc/local/benchmarks/daily/next/2021-06-04/hpcx-gcc-redhat7.6/ompi/lib/libmpi.so.40(MPI_Alltoall+0x41)[0x7f75623c57a1]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [18] /hpc/local/benchmarks/daily/next/2021-06-04/mtt-tests-gcc/installs/LFtZ/tests/imb-datacheck/mtt-tests.git/imb/src/IMB-MPI1[0x40ddb4]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [19] /hpc/local/benchmarks/daily/next/2021-06-04/mtt-tests-gcc/installs/LFtZ/tests/imb-datacheck/mtt-tests.git/imb/src/IMB-MPI1[0x4072b8]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [20] /hpc/local/benchmarks/daily/next/2021-06-04/mtt-tests-gcc/installs/LFtZ/tests/imb-datacheck/mtt-tests.git/imb/src/IMB-MPI1[0x4022c8]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [21] /lib64/libc.so.6(__libc_start_main+0xf5)[0x7f7561d9f3d5]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] [22] /hpc/local/benchmarks/daily/next/2021-06-04/mtt-tests-gcc/installs/LFtZ/tests/imb-datacheck/mtt-tests.git/imb/src/IMB-MPI1[0x401d29]
Fri Jun  4 02:11:03 2021[1,46]<stderr>:[jazz16:168419] *** End of error message ***--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Refactoring of FC send operations.

## Why ?

Fixes #6904
1. Fixes comments from #6850.
2. Get rid of calling DCI put operations in case of failure.
3. Remove `uct_dc_mlx5_ep_fc_ctrl()` function and do sending of `FC_HARD_REQ`/`FC_PURE_GRANT` directly.

## How ?

1. Add comment in DCI put, re-organize code in `uct_dc_mlx5_ep_fc_hard_req_send()` to make it more readable.
2. Don't do DCI put in case of failure or not expired timeout - just delete added EP from hash in case of failure from sending FC_HARD_REQ (it is better, since it handles not only `UCS_ERR_NO_RESOURCE` failures).
3. Introduce `uct_dc_mlx5_ep_fc_pure_grant_send()`/`uct_dc_mlx5_ep_fc_hard_req_send()` functions and use them directly instead of `uct_dc_mlx5_ep_fc_ctrl()` which is passed to RC iface ops.

### CODE REVIEW

File: src/uct/ib/dc/dc_mlx5_ep.h [hunk 1]
```diff
@@ -379,8 +379,10 @@ uct_dc_mlx5_iface_dci_put(uct_dc_mlx5_iface_t *iface, uint8_t dci_index)
         return;
     }
 
-    ep = uct_dc_mlx5_ep_from_dci(iface, dci_index);
+    /* Release endpoint's DCI below, if the endpoint does not have outstanding
+     * operations */
```
Comment (yosefe) [inline src/uct/ib/dc/dc_mlx5_ep.h:383]: pls move this comment to line 370

**Comment by dmitrygx** [comment]
@brminich @hoopoepg could you review pls?

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 2]
```diff
@@ -883,138 +883,110 @@ ucs_status_t uct_dc_mlx5_iface_tag_recv_cancel(uct_iface_h tl_iface,
...
-                                     txqp, txwq, MLX5_OPCODE_SEND_IMM,
-                                     &sender.payload, sizeof(sender.payload),
-                                     op, sender.ep, iface->rx.dct.qp_num,
-                                     0, 0, &dc_ep->av,
-                                     uct_dc_mlx5_ep_get_grh(dc_ep),
-                                     uct_ib_mlx5_wqe_av_size(&dc_ep->av),
-                                     MLX5_WQE_CTRL_SOLICITED, INT_MAX);
-    }
+    fc_entry->seq       = sender.payload.seq;
+    fc_entry->send_time = send_time;
```
Comment (hoopoepg) [inline src/uct/ib/dc/dc_mlx5_ep.c:976]: unaligned ```=```

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 3]
```diff
@@ -1404,18 +1380,43 @@ ucs_status_t uct_dc_mlx5_ep_check_fc(uct_dc_mlx5_iface_t *iface,
...
+        if (ucs_likely((ep->fc.fc_wnd > 0) ||
+                       ((now - fc_entry->send_time) <
+                                iface->tx.fc_hard_req_timeout))) {
+            goto out_set_status;
+        }
+    } else {
+        ucs_assert(ep->fc.fc_wnd ==
+                           iface->super.super.config.fc_hard_thresh);
+        fc_entry = &kh_value(&iface->tx.fc_hash, it);
+    }
```
Comment (brminich) [inline src/uct/ib/dc/dc_mlx5_ep.c:1404]: why is it moved from `uct_dc_mlx5_ep_fc_hard_req_send`? Imo we could try to resend grant for all type of packets, not only for `ep_check`

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 4]
```diff
@@ -883,138 +883,110 @@ ucs_status_t uct_dc_mlx5_iface_tag_recv_cancel(uct_iface_h tl_iface,
...
-        }
+    if (!iface->ud_common.config.compact_av || ah_attr.is_global) {
+        av.dqp_dct |= UCT_IB_MLX5_EXTENDED_UD_AV;
+    }
 
-        /* Note av initialization is copied from exp verbs */
-        av.stat_rate_sl = ib_iface->config.sl; /* (attr->static_rate << 4) | attr->sl */
-        av.fl_mlid      = ib_iface->path_bits[0] & 0x7f;
+    UCT_DC_MLX5_CHECK_DCI_RES(iface, ep);
+    UCT_DC_MLX5_IFACE_TXQP_GET(iface, ep, txqp, txwq);
```
Comment (brminich) [inline src/uct/ib/dc/dc_mlx5_ep.c:939]: Maybe better take dci at the beginning of func and release it later if some error occured.
The case when there is no dci may happen quite often (and repeatedly), so with current approach we will always do extra  work (create AH, etc) for no reason

**Review by brminich — CHANGES_REQUESTED** [review]

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 5]
```diff
@@ -883,138 +883,110 @@ ucs_status_t uct_dc_mlx5_iface_tag_recv_cancel(uct_iface_h tl_iface,
...
-                                                uct_dc_mlx5_iface_t);
-    uct_ib_iface_t *ib_iface   = &iface->super.super.super;
-    struct ibv_ah_attr ah_attr = {.is_global = 0};
-    uint8_t init_dci_index     = dc_ep->dci;
-    uct_dc_mlx5_ep_fc_entry_t *fc_entry;
+    uct_dc_mlx5_iface_t *iface  = ucs_derived_of(ep->super.super.iface,
+                                                 uct_dc_mlx5_iface_t);
+    uct_ib_iface_t *ib_iface    = &iface->super.super.super;
+    uintptr_t sender_ep         = (uintptr_t)fc_req->sender.ep;
+    struct ibv_ah_attr ah_attr  = {.is_global = 0};
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.c]: removed

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 6]
```diff
@@ -883,138 +883,110 @@ ucs_status_t uct_dc_mlx5_iface_tag_recv_cancel(uct_iface_h tl_iface,
...
-    ucs_time_t now;
-    khiter_t it;
-    int ret;
+    ucs_status_t status;
 
     UCT_DC_MLX5_TXQP_DECL(txqp, txwq);
 
     ucs_assert((sizeof(uint8_t) + sizeof(sender_ep)) <=
-                UCT_IB_MLX5_AV_FULL_SIZE);
+                       UCT_IB_MLX5_AV_FULL_SIZE);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.c]: removed

File: src/uct/ib/dc/dc_mlx5_ep.c (hunk 4 above)
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.c]: make sense, done

File: src/uct/ib/dc/dc_mlx5_ep.c (hunk 2 above)
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.c]: done

File: src/uct/ib/dc/dc_mlx5_ep.c (hunk 3 above)
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.c:1407]: `uct_dc_mlx5_ep_check_fc()` is used for all type of packets and for EP_CHECK operation.
it is moved here to have two functions:
- uct_dc_mlx5_ep_fc_hard_req_send()
- uct_dc_mlx5_ep_fc_pure_grant_send()
instead of `uct_rc_fc_ctrl()`

**Comment by dmitrygx** [comment]
@brminich could you review pls?

File: src/uct/ib/dc/dc_mlx5.c [hunk 7]
```diff
@@ -1030,19 +1030,22 @@ void uct_dc_mlx5_iface_cleanup_fc_ep(uct_dc_mlx5_iface_t *iface)
...
 {
-    uct_rc_pending_req_t *freq = ucs_derived_of(self, uct_rc_pending_req_t);
-    uct_dc_mlx5_ep_t *ep       = ucs_derived_of(freq->ep, uct_dc_mlx5_ep_t);
-    uct_rc_iface_t *iface      = ucs_derived_of(ep->super.super.iface,
-                                                uct_rc_iface_t);
+    uct_dc_fc_request_t *fc_req = ucs_derived_of(self, uct_dc_fc_request_t);
+    uct_dc_mlx5_ep_t *ep        = ucs_derived_of(fc_req->super.ep,
+                                                 uct_dc_mlx5_ep_t);
+    uct_dc_mlx5_iface_t *iface  = ucs_derived_of(ep->super.super.iface,
+                                                 uct_dc_mlx5_iface_t);
```
Comment (brminich) [inline src/uct/ib/dc/dc_mlx5.c:1037]: you can take rc iface here, like it was before.
then you can make simpler assert (like it was done before as well:)
`ucs_assert_always(iface->config.fc_enabled);`

**Review by brminich — APPROVED** [review]
looks ok, besides minor comment

File: src/uct/ib/dc/dc_mlx5.c (hunk 7 above)
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5.c]: good catch, done

File: src/uct/ib/dc/dc_mlx5_ep.h [hunk 8]
```diff
@@ -479,6 +495,7 @@ uct_dc_mlx5_iface_dci_get(uct_dc_mlx5_iface_t *iface, uct_dc_mlx5_ep_t *ep)
     ucs_assert(!iface->super.super.config.tx_moderation);
 
     if (uct_dc_mlx5_iface_is_dci_rand(iface)) {
+        ucs_assert(ep->dci != UCT_DC_MLX5_EP_NO_DCI);
```
Comment (yosefe) [inline src/uct/ib/dc/dc_mlx5_ep.h:498]: why needed?

File: src/uct/ib/rc/base/rc_iface.h [hunk 9]
```diff
@@ -178,19 +178,36 @@ struct uct_rc_iface_config {
...
-                                       unsigned flags);
-    unsigned             (*cleanup_qp)(void *arg);
-    void                 (*ep_post_check)(uct_ep_h tl_ep);
+    uct_ib_iface_ops_t                super;
+    uct_rc_iface_init_rx_func_t       init_rx;
+    uct_rc_iface_cleanup_rx_func_t    cleanup_rx;
+    uct_rc_iface_fc_ctrl_func_t       fc_ctrl;
+    uct_rc_iface_fc_handler_func_t    fc_handler;
+    uct_rc_iface_cleanup_qp_func_t    cleanup_qp;
+    uct_rc_iface_ep_post_check_func_t ep_post_check;
```
Comment (yosefe) [inline src/uct/ib/rc/base/rc_iface.h:210]: why need to change it in this PR?

Comment (dmitrygx) [reply src/uct/ib/rc/base/rc_iface.h:210]: this is needed to do casting to `uct_rc_iface_fc_ctrl_func_t`

Comment (yosefe) [reply src/uct/ib/rc/base/rc_iface.h:210]: ok

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 10]
```diff
@@ -1404,18 +1383,43 @@ ucs_status_t uct_dc_mlx5_ep_check_fc(uct_dc_mlx5_iface_t *iface,
...
+
+        goto out;
     }
 
-    return ((ep->fc.fc_wnd > 0) || (status != UCS_OK)) ?
-           status : UCS_ERR_NO_RESOURCE;
+out_set_status:
+    status = ucs_likely(ep->fc.fc_wnd > 0) ? UCS_OK : UCS_ERR_NO_RESOURCE;
+out:
+    uct_dc_mlx5_ep_check_dci_leak(ep);
```
Comment (yosefe) [inline src/uct/ib/dc/dc_mlx5_ep.c:1421]: in this PR: instead of checking dci_leak, need to dci_put if we're going to return status!=UCS_OK - because if we return !=OK, it means called will not send anything, which may lead to leak

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 11]
```diff
@@ -1478,6 +1482,7 @@ uct_dc_mlx5_ep_check(uct_ep_h tl_ep, unsigned flags, uct_completion_t *comp)
         (ep->flags & UCT_DC_MLX5_EP_FLAG_KEEPALIVE_POSTED)) {
         /* in case if EP has DCI and some TX resources are involved in
          * communications, then keepalive operation is not needed */
+        uct_dc_mlx5_ep_check_dci_leak(ep);
```
Comment (yosefe) [inline src/uct/ib/dc/dc_mlx5_ep.c:1485]: move leak check func to next PR

File: src/uct/ib/dc/dc_mlx5_ep.c (hunk 10 above)
Comment (yosefe) [reply src/uct/ib/dc/dc_mlx5_ep.c:1421]: update: don't dci_put since it will force re-allocating of dci while waiting for ep resources (flow control). just remove leak check from this PR.

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 12]
```diff
@@ -1404,18 +1383,43 @@ ucs_status_t uct_dc_mlx5_ep_check_fc(uct_dc_mlx5_iface_t *iface,
...
+    if (ucs_unlikely(ret == UCS_KH_PUT_FAILED)) {
+        ucs_error("failed to create hash entry for fc hard req");
+        status = UCS_ERR_NO_MEMORY;
+        goto out;
+    } else if (ret == UCS_KH_PUT_KEY_PRESENT) {
+        fc_entry = &kh_value(&iface->tx.fc_hash, it);
+
+        /* Do not resend FC request if timeout is not reached, or window is
+         * still not empty */
+        if (ucs_likely((ep->fc.fc_wnd > 0) ||
```
[the remark this answers is not in the document]
Comment (yosefe) [reply src/uct/ib/dc/dc_mlx5_ep.c:1398]: - remove ep from hash when it's destroyed
- assert fc_wnd<=0 + comment

File: src/uct/ib/dc/dc_mlx5_ep.h (hunk 8 above)
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.h:487]: updated: this was a fix for Coverity issue (false-positive):
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=19271&view=logs&j=42a93636-9ba0-5067-13f1-66c03328bbdd&t=156e1e98-827e-5d32-6ea8-39712540f036&l=2524
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/19271/logs/184

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 13]
```diff
@@ -972,11 +971,9 @@ uct_dc_mlx5_ep_fc_hard_req_send(uct_dc_mlx5_ep_t *ep,
     UCT_DC_MLX5_IFACE_TXQP_GET(iface, ep, txqp, txwq);
 
     sender.ep                = (uint64_t)ep;
-    sender.payload.seq       = iface->tx.fc_seq++;
+    sender.payload.seq       = fc_entry->seq;
```
Comment (yosefe) [inline src/uct/ib/dc/dc_mlx5_ep.c:974]: pls pass just "seq" without fc_entry. we need to make show the function does not change fc hash state

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 14]
```diff
@@ -1394,21 +1391,30 @@ ucs_status_t uct_dc_mlx5_ep_check_fc(uct_dc_mlx5_iface_t *iface,
...
             goto out_set_status;
         }
     } else {
-        ucs_assert(ep->fc.fc_wnd ==
-                           iface->super.super.config.fc_hard_thresh);
+        ucs_assertv(ep->fc.fc_wnd ==
+                            iface->super.super.config.fc_hard_thresh,
+                    "ep %p: fc_wnd=%u fc_hard_thresh=%u",
+                    ep, ep->fc.fc_wnd,
+                    iface->super.super.config.fc_hard_thresh);
```
Comment (yosefe) [inline src/uct/ib/dc/dc_mlx5_ep.c:1408]: IMO this assert is redundant

File: src/uct/ib/dc/dc_mlx5_ep.c [hunk 15]
```diff
@@ -1394,21 +1391,30 @@ ucs_status_t uct_dc_mlx5_ep_check_fc(uct_dc_mlx5_iface_t *iface,
         fc_entry = &kh_value(&iface->tx.fc_hash, it);
 
         /* Do not resend FC request if timeout is not reached, or window is
-         * still not empty */
-        if (ucs_likely((ep->fc.fc_wnd > 0) ||
+         * still not empty (fc_wnd == fc_hard_thresh when FC_HARD_REQ packet
+         * was sent and the endpoint was added to FC hash, but the user data
+         * wasn't sent to a peer and fc_wnd wasn't decremented as a result) */
+        if (ucs_likely((ep->fc.fc_wnd ==
+                                iface->super.super.config.fc_hard_thresh) ||
```
Comment (yosefe) [inline src/uct/ib/dc/dc_mlx5_ep.c:1398]: do we really need to check ep->fc.fc_wnd==fc_hard_thresh?
worse case we will send yet another hard_req after some time?

File: src/uct/ib/dc/dc_mlx5_ep.h [hunk 16]
```diff
@@ -481,6 +481,11 @@ uct_dc_mlx5_iface_dci_get(uct_dc_mlx5_iface_t *iface, uct_dc_mlx5_ep_t *ep)
     ucs_assert(!iface->super.super.config.tx_moderation);
 
     if (uct_dc_mlx5_iface_is_dci_rand(iface)) {
+        /* Coverity wrongly assumes that the endpoint could check TX DCI
+         * resources on IFACE without DCI held, but DCI random policy guarantees
+         * that DCI is always set in the ep->dci */
```
Comment (yosefe) [inline src/uct/ib/dc/dc_mlx5_ep.h:486]: maybe shorter:
/* Silence Coverity - in random policy the endpoint always has an assigned DCI */

File: src/uct/ib/dc/dc_mlx5_ep.c (hunk 13 above)
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.c:974]: sorry, I missed this...
done

File: src/uct/ib/dc/dc_mlx5_ep.c (hunk 3 above)
Comment (yosefe) [reply src/uct/ib/dc/dc_mlx5_ep.c]: the current version of this, where hash access is outside of uct_dc_mlx5_ep_fc_hard_req_send, seems better to me

File: src/uct/ib/dc/dc_mlx5_ep.c (hunk 14 above)
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.c:1408]: removed

File: src/uct/ib/dc/dc_mlx5_ep.c (hunk 15 above)
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.c:1398]: > worse case we will send yet another hard_req after some time?

yes, after `iface->tx.fc_hard_req_timeout`
removed

**Review by yosefe — APPROVED** [review]

File: src/uct/ib/dc/dc_mlx5_ep.c (hunk 3 above)
Comment (dmitrygx) [reply src/uct/ib/dc/dc_mlx5_ep.c]: > the current version of this, where hash access is outside of uct_dc_mlx5_ep_fc_hard_req_send, seems better to me

ok, good

**Comment by dmitrygx** [comment]
MTT/IO-demo testing passed and the PR fixes:
```
dc_mlx5_ep.c:1414 Assertion `uct_dc_mlx5_iface_dci_has_outstanding(iface, ep->dci)' failed: iface 0x15aa010 ep 0x16c1e50: dci leak detected: dci=7 fc_wnd=128
```
