### PR TITLE
GTEST/UCP: Improve stability of peer failure tests

### LINKED ISSUE #3627: shm_ib/test_ucp_peer_failure.force_close/2 fails from time to time on boo31
```
12:30:27 [ RUN      ] shm_ib/test_ucp_peer_failure.force_close/2
12:30:35 [1558690235.656589] [boo31:15851:0]      ucp_test.cc:205  UCX  ERROR request 0x57e4928 completed with error Endpoint timeout
12:30:35 /scrap/jenkins/workspace/hpc-ucx-pr/label/boo31/worker/3/contrib/../test/gtest/ucp/test_ucp_peer_failure.cc:282: Failure
12:30:35 Value of: UCS_PTR_IS_ERR(req)
12:30:35   Actual: true
12:30:35 Expected: false
12:30:39 /scrap/jenkins/workspace/hpc-ucx-pr/label/boo31/worker/3/contrib/../test/gtest/common/test.cc:265: Failure
12:30:39 Failed
12:30:39 Got 1 errors during the test
12:30:39 
[  FAILED  ] shm_ib/test_ucp_peer_failure.force_close/2, where GetParam() = shm,ib (12073 ms)
```

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10368/label=boo31,worker=3/consoleFull

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What

Implement deferred setting of relatively small UD EP timeout (`3 sec`, instead of default one - `5 min`) for Wireup/Aux UCT/UD EP and for data UCT/UD EPs.

## Why ?

Fixes #3627, #3630, #3577, #3364, #3679

## How ?

UCT/UD EP peer timeout for sender's UCP EP is set directly from UCP test code after initialization (e.g. wireup for RC transports or UD EP early peer failure detection - when puts some `send_nb()`s on a sender) done.

### CODE REVIEW

File: test/gtest/ucp/test_ucp_peer_failure.cc [hunk 1]
```diff
@@ -287,6 +289,23 @@ void test_ucp_peer_failure::do_test(size_t msg_size, int pre_msg_count,
...
+#if HAVE_IB
+    /* Since UCT/UD EP has a SW implementation of reliablity on which peer
+     * failure mechanism is based, we should set small UCT/UD EP timeout
+     * for UCT/UD EPs for sender's UCP EP to reduce testing time */
+    ucp_ep_config_t *ep_config = ucp_ep_config(failing_sender());
+    for (ucp_lane_index_t lane = 0; lane < ep_config->key.num_lanes; ++lane) {
+        ucp_rsc_index_t rsc_index  = ep_config->key.lanes[lane].rsc_index;
+        if (rsc_index != UCP_NULL_RESOURCE) {
+            ucp_worker_iface_t *wiface = ucp_worker_iface(sender().worker(), rsc_index);
+            if (wiface->iface->ops.iface_flush == uct_ud_iface_flush) {
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_peer_failure.cc]: minor: i would check for uct_ud_iface_handle_failure instead of flush, and also comment that we are doing this to check if the iface is ud transport
and include ud_iface.h

File: test/gtest/ucp/test_ucp_peer_failure.cc [hunk 2]
```diff
@@ -287,6 +289,23 @@ void test_ucp_peer_failure::do_test(size_t msg_size, int pre_msg_count,
 
     EXPECT_EQ(UCS_OK, m_err_status);
 
+#if HAVE_IB
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_peer_failure.cc]: maybe extract this code to helper function: `void set_ud_trimeout()`

File: test/gtest/ucp/test_ucp_peer_failure.cc [hunk 3]
```diff
@@ -287,6 +289,23 @@ void test_ucp_peer_failure::do_test(size_t msg_size, int pre_msg_count,
...
+    /* Since UCT/UD EP has a SW implementation of reliablity on which peer
+     * failure mechanism is based, we should set small UCT/UD EP timeout
+     * for UCT/UD EPs for sender's UCP EP to reduce testing time */
+    ucp_ep_config_t *ep_config = ucp_ep_config(failing_sender());
+    for (ucp_lane_index_t lane = 0; lane < ep_config->key.num_lanes; ++lane) {
+        ucp_rsc_index_t rsc_index  = ep_config->key.lanes[lane].rsc_index;
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_peer_failure.cc]: minor: 2 spaces instead of one..

File: test/gtest/ucp/test_ucp_peer_failure.cc [hunk 4]
```diff
@@ -287,6 +289,23 @@ void test_ucp_peer_failure::do_test(size_t msg_size, int pre_msg_count,
 
     EXPECT_EQ(UCS_OK, m_err_status);
 
+#if HAVE_IB
+    /* Since UCT/UD EP has a SW implementation of reliablity on which peer
+     * failure mechanism is based, we should set small UCT/UD EP timeout
+     * for UCT/UD EPs for sender's UCP EP to reduce testing time */
+    ucp_ep_config_t *ep_config = ucp_ep_config(failing_sender());
+    for (ucp_lane_index_t lane = 0; lane < ep_config->key.num_lanes; ++lane) {
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_peer_failure.cc]: for simplicity: we can just go over all rsc_index values. no need to limit ourselves to the lanes in ucp_ep

File: test/gtest/ucp/test_ucp_peer_failure.cc (hunk 2 above)
Comment (dmitrygladkov) [reply test/gtest/ucp/test_ucp_peer_failure.cc]: done
this is extracted to `void ucp_test_base::entity::set_ib_ud_timeout(double timeout_sec)`

File: test/gtest/ucp/test_ucp_peer_failure.cc (hunk 4 above)
Comment (dmitrygladkov) [reply test/gtest/ucp/test_ucp_peer_failure.cc]: > for simplicity: we can just go over all rsc_index value

good catch! done

File: test/gtest/ucp/test_ucp_peer_failure.cc (hunk 3 above)
Comment (dmitrygladkov) [reply test/gtest/ucp/test_ucp_peer_failure.cc]: fixed

File: test/gtest/ucp/test_ucp_peer_failure.cc (hunk 1 above)
Comment (dmitrygladkov) [reply test/gtest/ucp/test_ucp_peer_failure.cc]: discussed offline
we will go with `uct_ud_iface_flush` as it is now

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10667/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 24-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/21274df0040de72e5d768c5ea86105fde0f67ac2/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/84b78eabbc4c0e7a2eed23d32b0b67993dfd5711/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/d225ad560737d6d3a3af95d302e43cfcc3593482/hpc-test-node3_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/3faeeb1af48ad39c7b2a7edfafc3875d40ac638f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/df1c9ed6e7f47b2e2ecd9c2717c6faa6e189e7b6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/13f669103e0e2f4c0318f83b77ef255f4d5ce56c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/c98d8259d5f009b49e4825b6c0e0091b3d8360fc/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/794a5bf9aa8c8e79f5f4d9e3d45f4915f9a4523a/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/b9e26e3f8741ecfb79befc59379a2f15d201d561/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/aa31866be824a7ba7b02382f1ac07fb0d3b0a376/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/3c25a9fb421e06bfedc528ea0951ac18e5ea5f42/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/78449c0a0b6ff5405280e65f133d2de8c76b4540/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/45d92eccbcb4e728bce12c3134ce9e04f61658bb/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/b6398f77a572650155a04bca220eca6093eec4f1/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/bc2ed2051624dc1fbb045f543496b32df64cb465/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/e4818d0a72513e7bce2a70638399aa477b11b70f/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/fcfcd8979e8c39432f50327c53d99bd0450ff79a/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/d31507c718ffc65efa3e2e3795713cd5fd557db1/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/f66449d98ada474372654724d1f8d0931849d412/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/4d28d3410f6872266eb5dde6180f2180e84e9ec7/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/313e9178e7e57d11fcbf0a3a4907c62544ce0ed8/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/f5e74832fe4fd5c0bdba8cffd74e29c82f99e7a7/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/9ee1b901aac8c40424c42c3c64820b62d45af936/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/8a4859c4dcad4b63d0162f78ef64e40cf0f2de05/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/14762ab9d1b5eb8f60ab09c50876057d2b484912/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/b5594bc72734a23b07cace998e0290657ed4716f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/6dbe18f59bfbc4edae0e756f9ab66b020e806759/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/58ae47c785fec19b0ca88c0da00a1fe0e0e39d9f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/939531918ece0786d6cc24117e2f0683ca23c9be/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/773fd947ecd237ee235c5de578b8c2e8118a1d9e/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/1b08e90ff83a94602dc40b3aaf87511417b7b201/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/8df95baf5088daef91eceb8eff89f13fb27d4867/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/83b6a91e279553e1001c255577b1078c/raw/356a9f00d031b85b6cad61a4db61babe0c1f4c99/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10671/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 25-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/02b031cbd24d5629eaac40e669377930b4ce8691/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/4e88d0c4f890168a41d1ac298a5d6a6b81fdb28a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/c83b4196c6df1909b167c534ae58209aecf8dcc2/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/5a8500652ee876515e8911bb4d71c80ba3bcd249/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/81739c76f91b88f03af15775f6edc8659a5eccae/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/740fbf26e713b54f772f11314d26d958fc773a16/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/5891d025e1e9980f2ae53862e03e288304738396/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/55a677a4ae97f1887d8c0822807c768a06984887/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/62128605e7eb2df736ec671c4230c6cefe068cf0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/83e428284cd762ec3dbe191cdb655500186a66e3/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/afec4376de6a75841d55eb51e1ba57bc44ce4e8d/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/a39026fa4eaea62d89aefc2fbf040c2473e45591/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/2870aaad3b78dffac3f2c32857f0a617b50230b6/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/973f0f3821e8f4a97a4c93972bcae6ccddbd100d/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/a1abfba092a35fec5bddb43100fc8ad83e260250/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/738a31af13cc7b13bf82c95a0c1aa6ce8aab1605/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/042db6126861f758fb99fc8cb0221e859c0c0b97/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/ea7ae40d9163a4a59ccc1ba78bac38e2d2ecb42f/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/b0e7ed20173b588178e367b6cb4b0536570c73a6/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/7cfb295a753d3212e068340c2f6508b108f5a7d8/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/4f592ffb75177ddda5a7b414e038cd5dd0d7c16c/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/f5b7fa57d1e83b1d992ad39ec2a6e2139c78680e/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/fb4d36c69ebc9faba4657d29b28345b259b3b4eb/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/b990e0d7e45d5da98c4673b18032b2574c829017/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/3ae215b86ea83ce22f66865d299ad551de177581/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/938d1e5d77e5d0cc94845baa5519e03c81b66c2e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/18fa0d6562a8353ea921c10c0cd0c7be0efef45d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/e7419ab6fcef52873a52351d1f01aec97f5e46ec/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/0e38db09156dda82d8ed618a37afb6747a53b919/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/6b43394f8be90bcc0f9226aa1c1105da1cb788e1/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/2e7126038e977fa87aaba34d5390b95f49b0c215/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/0fffac5d45044d156614ad9600a692f90b588e1d/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4c977b1801276bae98c56f7f11c51e75/raw/b2d5332bf7bcee428b6f1fb6d7cb686e28ea234c/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
bot:pipe:retest

File: test/gtest/ucp/ucp_test.cc [hunk 5]
```diff
@@ -5,6 +5,11 @@
 
 #include "ucp_test.h"
 
+#include <ucp/core/ucp_ep.inl>
```
Comment (yosefe) [inline test/gtest/ucp/ucp_test.cc]: can we include ucp_worker.h instead?
need to wrap in extern C?

File: test/gtest/ucp/ucp_test.cc [hunk 6]
```diff
@@ -659,6 +664,23 @@ void ucp_test_base::entity::warn_existing_eps() const {
     }
 }
 
+void ucp_test_base::entity::set_ib_ud_timeout(double timeout_sec)
+{
+#if HAVE_IB
+    for (ucp_rsc_index_t rsc_index = 0;
+         rsc_index < this->ucph()->num_tls; ++rsc_index) {
```
Comment (yosefe) [inline test/gtest/ucp/ucp_test.cc]: "this->" is redundant

File: test/gtest/ucp/ucp_test.cc [hunk 7]
```diff
@@ -659,6 +664,23 @@ void ucp_test_base::entity::warn_existing_eps() const {
...
+        ucp_worker_iface_t *wiface =
+            ucp_worker_iface(this->worker(), rsc_index);
```
Comment (yosefe) [inline test/gtest/ucp/ucp_test.cc]: "this->" is redundant

**Comment by dmitrygladkov** [comment]
@evgeny-leksikov could you review pls?

File: test/gtest/ucp/ucp_test.cc [hunk 8]
```diff
@@ -668,19 +669,33 @@ void ucp_test_base::entity::set_ib_ud_timeout(double timeout_sec)
...
+            }
+
             iface->config.peer_timeout = ucs_time_from_sec(timeout_sec);
+            uct_ud_leave(iface);
         }
     }
 #endif
 }
 
+void ucp_test_base::entity::set_ib_ud_timeout()
```
Comment (yosefe) [inline test/gtest/ucp/ucp_test.cc]: let's move this to err handling test, rename to restore_ib_ud_timeout

File: src/ucs/debug/log.c [hunk 9]
```diff
@@ -148,6 +148,10 @@ ucs_log_default_handler(const char *file, unsigned line, const char *function,
             ucs_log_print(buffer_size, short_file, line, level, &tv, log_line);
             log_line = strtok_r(NULL, "\n", &saveptr);
         }
+
+        if (level == UCS_LOG_LEVEL_ERROR) {
+            ucs_assert(0);
```
Comment (evgeny-leksikov) [inline src/ucs/debug/log.c]: leftover?

File: test/gtest/ucp/ucp_test.cc [hunk 10]
```diff
@@ -668,19 +669,33 @@ void ucp_test_base::entity::set_ib_ud_timeout(double timeout_sec)
...
-        ucp_worker_iface_t *wiface =
-            ucp_worker_iface(this->worker(), rsc_index);
+         rsc_index < ucph()->num_tls; ++rsc_index) {
+        ucp_worker_iface_t *wiface = ucp_worker_iface(worker(), rsc_index);
         // check if the iface is ud transport
         if (wiface->iface->ops.iface_flush == uct_ud_iface_flush) {
             uct_ud_iface_t *iface =
                 ucs_derived_of(wiface->iface, uct_ud_iface_t);
+
+            uct_ud_enter(iface);
```
Comment (evgeny-leksikov) [inline test/gtest/ucp/ucp_test.cc]: 👍

File: test/gtest/ucp/ucp_test.h [hunk 11]
```diff
@@ -105,6 +105,8 @@ class ucp_test_base : public ucs::test_base {
 
         void set_ib_ud_timeout(double timeout_sec);
 
+        void set_ib_ud_timeout();
```
Comment (evgeny-leksikov) [inline test/gtest/ucp/ucp_test.h]: maybe rename to "reset" or "restore"?

File: test/gtest/ucp/ucp_test.cc [hunk 12]
```diff
@@ -668,19 +669,33 @@ void ucp_test_base::entity::set_ib_ud_timeout(double timeout_sec)
...
             iface->config.peer_timeout = ucs_time_from_sec(timeout_sec);
+            uct_ud_leave(iface);
         }
     }
 #endif
 }
 
+void ucp_test_base::entity::set_ib_ud_timeout()
+{
+    if (m_default_ib_ud_timeout_sec) {
```
Comment (evgeny-leksikov) [inline test/gtest/ucp/ucp_test.cc]: shouldn't we reset `m_default_ib_ud_timeout_sec = 0`?

File: test/gtest/ucp/ucp_test.h [hunk 13]
```diff
@@ -103,6 +103,8 @@ class ucp_test_base : public ucs::test_base {
 
         void warn_existing_eps() const;
 
+        double set_ib_ud_timeout(double timeout_sec);
```
Comment (evgeny-leksikov) [inline test/gtest/ucp/ucp_test.h]: "setter" which returns old value is not obvious. IMO, better to add corresponding "getter". Why did you remove "reset"/"restore" method? That looked better too.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10680/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10681/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 7 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 25-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/c4a4b26af876faf4a30cc834dd90b9db329a7a25/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/9ba3463e6151a83f2c6f7b3996099fef0d67af2a/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/8e868eddc5251d99e8dea8394a931528447360fd/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/fae92b5e4cbdebe7abbdff52cd4be22399c3a064/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/5888171b4f792f00303caeef509d7f8487ada205/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/39c3d8647bd26ef5d8cb62ffe9984d1f7d58702e/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/3ca1c8815418ad4a6fedb4ae39805566812f9269/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/472fe639e28bbe78aa7726950e0547c8dae9f509/vulcan-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/d10e0b72cfc9c0cd0673137daf7ac82fcdaca159/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/4e027cdc250c8323dac578df40ef82b7d8695c43/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/f4045ad5c61eb6d2f83f449db6873d1d4db1ebab/hpc-test-node-upstream_W0) | :question: UNKNOWN
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/77b4fe11b28a30f103a2f08775faf43faf218f2a/hpc-test-node-upstream_W1) | :question: UNKNOWN
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/5b71ddede43eb3cfeea9adaf21713f7784582b23/hpc-test-node-upstream_W2) | :question: UNKNOWN
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/0784efe960b397572173f3d08a8e4a7e1bd31e86/hpc-test-node-upstream_W3) | :question: UNKNOWN
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/37f9588b26bbb4aea0bacc422c1960904c0dbc78/hpc-test-node2_W0) | :question: UNKNOWN
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/bf52f165ae11247f0d5233bd24d62959b82c43a2/hpc-test-node2_W1) | :question: UNKNOWN
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/011e471bcb831eb1a8d6512dada7d8587521b7ad/hpc-test-node2_W2) | :question: UNKNOWN
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/d20642eef00e648041b24e6b8f7b9a3e322d6084/hpc-test-node2_W3) | :question: UNKNOWN
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/56426d2a6ff011027997bb02200b58f82b80ad4d/hpc-test-node3_W0) | :question: UNKNOWN
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/f30e436915096d134ee24db9ac1de2ed08d49e76/hpc-test-node3_W1) | :question: UNKNOWN
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/3081d2bcea3eb7118d5fbf93b40855ec1e44dc8b/hpc-test-node3_W2) | :question: UNKNOWN
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/d7f536595d81a764cbb9add9654317970bfae8af/hpc-test-node3_W3) | :question: UNKNOWN
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/dbf9e9fddd6889081956c9b6cac384946d2f824b/hpc-test-node_W0) | :question: UNKNOWN
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/97618c6993d743239095960a73475e4dc4d30ac0/hpc-test-node_W1) | :question: UNKNOWN
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/9d5975c7c6a08d50ecfebb8414e5973d5f56f88d/hpc-test-node_W2) | :question: UNKNOWN
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/654f2c4f6b3966102ade9436b852e7c24b2f18a2/hpc-test-node_W3) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/d0c6611cbaad69ce4e368013013ac579018e8608/r-vmb-ppc-jenkins_W0) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/4d7fc5959f1d55822f88ac551dd0c94c58dd6f48/r-vmb-ppc-jenkins_W1) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/135b38d42ae2d341946d3cfe1ca7ea4c33e9e35b/r-vmb-ppc-jenkins_W2) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/4844918645cf4e698cecb73516207ad50133ced0/r-vmb-ppc-jenkins_W3) | :question: UNKNOWN
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/08fb5e2ae0061035e0d90aae42c9d435166bc005/vulcan-jenkins_W0) | :question: UNKNOWN
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/e6268cca7e6cf5e6ee231372186d43de63fb82ff/vulcan-jenkins_W1) | :question: UNKNOWN
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ede59ecd04a69d35df7944bfb76a3133/raw/dcaf72a9d1b7bf98470e115ff33c10f0d98b2738/vulcan-jenkins_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 7 of 27 workers (click for details)</summary>

**Note:** the logs will be deleted after 25-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/85e4921cef4721511d07f895d34ede222ba49faf/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/839c9ca4150a376cb5d21c812aa9c7fd5e290781/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/01b31a3ead8e16ae8a1b45b8188b902a478646c1/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/e2e12b773551d1a01a127ae7fbb07d9ff577df1b/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/28e6b9af8bc9e0cc2c87a41349937c13c93c769c/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/1997c1d582483412d02d32cbc6cb2032661547ed/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/f6813e92428ebb8f97a8abb161e2ee6e0824f6c1/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/278ef4cbdbc9d2c30e44fd084eca157dc204a167/vulcan-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/14dd090b4bf091a23bcc730f5a7ba4b1fe37632a/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/cd0dec5310e346252ff4942652bc6549397c3276/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/b93d880296f3b89af5b22c9614c4c3f45412003c/hpc-test-node-upstream_W0) | :question: UNKNOWN
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/14579e8854ee5ac1268422e469d33dfddc954b3c/hpc-test-node-upstream_W2) | :question: UNKNOWN
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/d660e7d434be76d5e28e3220cedc00dae4d63288/hpc-test-node2_W0) | :question: UNKNOWN
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/75a9a843eb1da767796eb1349630d8727c3f68f8/hpc-test-node2_W1) | :question: UNKNOWN
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/b6e06e8158d91f68f4520342b9800d5e02dec32b/hpc-test-node2_W2) | :question: UNKNOWN
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/28535b40af4a22575a65aa18f54d637ba41a6560/hpc-test-node2_W3) | :question: UNKNOWN
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/ed41e847f47154e5bcf4fff912a6386ef25f92b4/hpc-test-node3_W0) | :question: UNKNOWN
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/984d60554baad2fe1308732a560983bcac35d08d/hpc-test-node3_W1) | :question: UNKNOWN
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/1b5067ad487de5e76d541eb2b0b4bf24d5546999/hpc-test-node3_W2) | :question: UNKNOWN
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/d05c1d4829d7eff7419280f5c60b51e4628316e0/hpc-test-node3_W3) | :question: UNKNOWN
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/952efe5dedfb8f4460d739bb23c56ee386c6d3c9/hpc-test-node_W0) | :question: UNKNOWN
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/45a59559f07db0a56b917b1196e41e5f0f6bc990/hpc-test-node_W1) | :question: UNKNOWN
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/5e77c76ad574f9c4afcf061f153cdcf79cb459a8/hpc-test-node_W2) | :question: UNKNOWN
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/02503c5a9b0a67a0434538cc10aff184982cf6c8/hpc-test-node_W3) | :question: UNKNOWN
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/ed0b065433203ade71234c19fc35252b79b41f24/vulcan-jenkins_W0) | :question: UNKNOWN
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/972ca858562fac4d5e1a8418da01bd2c5eb3145b/vulcan-jenkins_W1) | :question: UNKNOWN
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7612344c6e5cf5e3fe4eaa52efd6e8cf/raw/796c9c25975669684ed26b379aa6459148b1cb54/vulcan-jenkins_W3) | :question: UNKNOWN

File: test/gtest/ucp/ucp_test.h (hunk 13 above)
Comment (dmitrygladkov) [reply test/gtest/ucp/ucp_test.h]: do you think that's better to implement the following approach -
0. `test_ucp_peer_failure::m_prev_timeout = 0.;`
1. `test_ucp_peer_failure::m_prev_timeout = ucp_test::get_ib_ud_timeout();` to get the current value for futher restore (e.g. at the end of the `init()`)
2. `ucp_test::set_ib_ud_timeout(3.);`
...`// testing`
3. `test_ucp_peer_failure::restore_ib_ud_timeout();`

looks like it makes it's more complicated

Comment (evgeny-leksikov) [reply test/gtest/ucp/ucp_test.h]: no, something one from getter with local variable or reset with `test_ucp_peer_failure::m_prev_timeout` member

Comment (dmitrygladkov) [reply test/gtest/ucp/ucp_test.h]: Got it, it should be something like:

> getter with local variable

1. `old_val = get_*;`
2. `set_*(3.);`
... `// testing`
4. `set_*(old_val);`

> reset with `test_ucp_peer_failure::m_prev_timeout` member

here, we still need to get the `test_ucp_peer_failure::m_prev_timeout` velue somehow before do `restore_*`

Comment (evgeny-leksikov) [reply test/gtest/ucp/ucp_test.h]: yep

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10682/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 25-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/f5a8b62c22c3d94f54aa5b892c5ac73af6116123/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/ec0aefa31cb364b330038ba2f3bd566953818113/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/3e9a4897e4e6dce4739167e200ae4190d04d1fd5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/90bcc95804061a90ea0244659e8c5ced54ed7d95/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/8e2a8d1194d063c30576b2dbd1b0492fb469f8af/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/2cccb212f1877143c29f5bbb5605c9db5db98d7c/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/914a5708fa498c904914a5df6dd01bcf519dc419/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/36617cb2dd616454e0d21ee018d541ac50c993f3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/a8f065f9da9968bae0b9798a8a2e6adae0ef976a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/f03b6ae6ab5adde0a029b059a7030f162c328ff0/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/d888f92952dd6a3d5bb16c36094276d9da771318/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/827bcb94d498743c010c5c0eaabe5b7cfd56a20a/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/180c3db45aff22ae695e6dc1b191f70c5cba9c91/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/57774d0a09ddb70a85e8e7b3c539f8de2102fc6e/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/19a0d943d1e323027254ed5c88d1cb9688b939a1/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/4d079d1a33a9a223cae56a7cde2c76d95bc69b25/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/1a47748984563bedd26b4ca5c7f0ad9fc1ec969a/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/088f42e61929bb8222486368d6c9d01a8b0bf14b/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/ccf13015079c6902974b5a8356af6f6a483c68ff/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/8095785dde9ecc0d26868614531f64a113c7f74f/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/1437a8fac4bdc4f009086c242b4b4cdcc05dbeaa/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/5f139352cf763c439f76289d00e2c7825ea1b702/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/b1ba4645f7196bdd384f716fb870500ca7274d13/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/e07f8ca14de1b914c895c64cd7ee069900eeba29/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/57d245a33831be4400cb56f1292e412a6a57333f/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/3ec6af9f7304d9af7685cf8fab88c83be7135444/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/e30ddede94e035ee0e8e705c404a0e9b28a25fb6/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/a8997e3e1a34353b95a0335aef36a485a52ab689/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/9ae4dadc268167c5185fa5653f048e62b42ab59f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/df178e2188109539c4f46ccfdd4db12c24ef9f24/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/7152cc512fce74e61d3ccdf9a5e1b85fdd8dd662/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/53226af0541866724d8dff1415345b670d6818e9/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a8cc4faa800b20df42325e709144c577/raw/9fb542be639e41471deb9778191529b5ae1c610c/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
@yosefe is it ok to go with the current approach for `set_ib_ud_timeout` that returns previous timeout value?

**Comment by yosefe** [comment]
@dmitrygladkov yes. can you pls close all issues which were fixed by this PR with an appropriate comment? 10x
