### PR TITLE
 UCP/TAG: Ensure pipeline fragment size matches PUT/GET limits

### LINKED ISSUE #5260: Failure in rc/test_ucp_tag_mem_type.xfer_mismatch_length/55
### Describe the bug
Happened here: https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/6805/logs/155 on swx-rdmz-ucx-gpu-02

```
2020-06-09T01:19:15.1290779Z [ RUN      ] rc/test_ucp_tag_mem_type.xfer_mismatch_length/55 <rc_v,cuda_copy,rocm_copy>
2020-06-09T01:19:15.1806058Z [     INFO ] TEST: host <-> cuda length :9437270
2020-06-09T01:19:15.2400191Z [swx-rdmz-ucx-gpu-02:13714:0:13714]        rndv.c:506  Assertion `rndv_req->send.length >= (offset + length)' failed: send_length=43, offset=0, length=65
2020-06-09T01:19:15.6653101Z 
2020-06-09T01:19:15.6655238Z /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c: [ ucp_rndv_progress_rma_get_zcopy_inner() ]
2020-06-09T01:19:15.6656776Z       ...
2020-06-09T01:19:15.6657373Z       501 
2020-06-09T01:19:15.6658061Z       502     /* ensure that tail (rest of message) is over min_zcopy */
2020-06-09T01:19:15.6659198Z       503     ucs_assertv(rndv_req->send.length >= (offset + length),
2020-06-09T01:19:15.6660095Z ==>   504                 "send_length=%zu, offset=%zu, length=%zu",
2020-06-09T01:19:15.6661169Z       505                 rndv_req->send.length, offset, length);
2020-06-09T01:19:15.6662344Z       506     tail = rndv_req->send.length - (offset + length);
2020-06-09T01:19:15.6663246Z       507     if (ucs_unlikely((tail != 0) && (tail < min_zcopy))) {
2020-06-09T01:19:15.6663866Z 
2020-06-09T01:19:16.0843470Z ==== backtrace (tid:  13714) ====
2020-06-09T01:19:16.0845435Z  0 0x0000000000059b18 ucs_debug_print_backtrace()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucs/debug/debug.c:656
2020-06-09T01:19:16.0847378Z  1 0x0000000000055cde ucp_rndv_progress_rma_get_zcopy_inner()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c:504
2020-06-09T01:19:16.0849383Z  2 0x0000000000055cde ucp_rndv_progress_rma_get_zcopy()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c:435
2020-06-09T01:19:16.0850754Z  3 0x000000000005bc0d ucp_request_try_send()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/core/ucp_request.inl:213
2020-06-09T01:19:16.0852254Z  4 0x000000000005bc0d ucp_request_send()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/core/ucp_request.inl:248
2020-06-09T01:19:16.0853775Z  5 0x000000000005bc0d ucp_rndv_send_frag_get_mem_type()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c:765
2020-06-09T01:19:16.0855138Z  6 0x000000000005bc0d ucp_rndv_recv_start_get_pipeline()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c:823
2020-06-09T01:19:16.0856469Z  7 0x000000000005bc0d ucp_rndv_matched_inner()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c:1123
2020-06-09T01:19:16.0857744Z  8 0x000000000005bc0d ucp_rndv_matched()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c:1042
2020-06-09T01:19:16.0859051Z  9 0x000000000005dcae ucp_rndv_process_rts()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c:1160
2020-06-09T01:19:16.0860349Z 10 0x000000000005dcae ucp_rndv_process_rts()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c:1164
2020-06-09T01:19:16.0861661Z 11 0x000000000005df46 ucp_rndv_rts_handler_inner()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c:1184
2020-06-09T01:19:16.0863030Z 12 0x000000000002fff3 uct_iface_invoke_am()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/uct/base/uct_iface.h:635
2020-06-09T01:19:16.0864429Z 13 0x000000000002fff3 uct_rc_verbs_iface_handle_am()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/uct/ib/rc/verbs/rc_verbs_impl.h:96
2020-06-09T01:19:16.0865871Z 14 0x000000000002fff3 uct_rc_verbs_iface_poll_rx_common()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/uct/ib/rc/verbs/rc_verbs_impl.h:125
2020-06-09T01:19:16.0867342Z 15 0x000000000002fff3 uct_rc_verbs_iface_progress()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/uct/ib/rc/verbs/rc_verbs_iface.c:133
2020-06-09T01:19:16.0868718Z 16 0x000000000002eb6a ucs_callbackq_dispatch()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucs/datastruct/callbackq.h:211
2020-06-09T01:19:16.0870047Z 17 0x000000000002eb6a uct_worker_progress()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/uct/api/uct.h:2342
2020-06-09T01:19:16.0871359Z 18 0x000000000002eb6a ucp_worker_progress()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../src/ucp/core/ucp_worker.c:2032
2020-06-09T01:19:16.0872772Z 19 0x0000000000865bdb ucp_test_base::entity::progress()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:736
2020-06-09T01:19:16.0874168Z 20 0x0000000000865c87 ucp_test::progress()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:138
2020-06-09T01:19:16.0875787Z 21 0x00000000007f2930 test_ucp_tag::wait()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/test_ucp_tag.cc:129
2020-06-09T01:19:16.0877237Z 22 0x00000000007e7840 test_ucp_tag_mem_type::do_xfer()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/test_ucp_tag_mem_type.cc:132
2020-06-09T01:19:16.0878812Z 23 0x00000000007ec39a test_ucp_tag_mem_type_xfer_mismatch_length_Test::test_body()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/test_ucp_tag_mem_type.cc:204
2020-06-09T01:19:16.0880484Z 24 0x00000000007ec39a test_ucp_tag_mem_type_xfer_mismatch_length_Test::test_body()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/test_ucp_tag_mem_type.cc:205
2020-06-09T01:19:16.0882046Z 25 0x00000000005ae926 ucs::test_base::run()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/test.cc:290
2020-06-09T01:19:16.0883448Z 26 0x00000000005ae926 ucs::test_base::TestBodyProxy()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/test.cc:316
2020-06-09T01:19:16.0885172Z 27 0x0000000000591fc9 HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/gtest-all.cc:3562
2020-06-09T01:19:16.0886666Z 28 0x000000000058620d testing::Test::Run()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/gtest-all.cc:3635
2020-06-09T01:19:16.0888112Z 29 0x00000000005862e5 testing::TestInfo::Run()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/gtest-all.cc:3812
2020-06-09T01:19:16.0889524Z 30 0x000000000058644f testing::TestCase::Run()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/gtest-all.cc:3930
2020-06-09T01:19:16.0891004Z 31 0x000000000058abfd testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/gtest-all.cc:5808
2020-06-09T01:19:16.0892867Z 32 0x000000000058aee0 testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/gtest-all.cc:5725
2020-06-09T01:19:16.0894274Z 33 0x0000000000529488 RUN_ALL_TESTS()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/gtest.h:20059
2020-06-09T01:19:16.0895548Z 34 0x0000000000529488 main()  /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/main.cc:102
2020-06-09T01:19:16.0896401Z 35 0x00000000000223d5 __libc_start_main()  ???:0
2020-06-09T01:19:16.0897066Z 36 0x0000000000570571 _start()  ???:0
2020-06-09T01:19:16.0897620Z =================================
2020-06-09T01:19:16.0898496Z [swx-rdmz-ucx-gpu-02:13714:0:13714] Process frozen...
2020-06-09T03:50:01.3210842Z make: *** [test] Terminated
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Ensure RNDV pipeline fragment size matches PUT/GET limits

## Why ?

Fixes #5260
```
[----------] Global test environment set-up.
[----------] 1 test from rc/test_ucp_tag_mem_type
[ RUN      ] rc/test_ucp_tag_mem_type.xfer_mismatch_length/55 <rc_v,cuda_copy,rocm_copy>
[     INFO ] TEST: host <-> cuda length: 9437270
[       OK ] rc/test_ucp_tag_mem_type.xfer_mismatch_length/55 (236 ms)
[----------] 1 test from rc/test_ucp_tag_mem_type (236 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (237 ms total)
[  PASSED  ] 1 test.
```

## How ?

1. Use the already implemented functionality to ensure that the length of the fragment is over MIN Zcopy and less than MAX Zcopy.
2. Wrap this functionality to the common function.
3. Use it for GET/PUT pipeline fragment size and RNDV Get lane message size calculations.

### CODE REVIEW

**Comment by dmitrygx** [comment]
bot:pipe:retest

File: src/ucp/tag/rndv.c [hunk 1]
```diff
@@ -226,6 +227,47 @@ ucs_status_t ucp_tag_send_start_rndv(ucp_request_t *sreq)
     return status;
 }
 
+static UCS_F_ALWAYS_INLINE void
+ucp_rndv_adjust_zcopy_length(size_t min_zcopy, size_t max_zcopy, size_t align,
```
Comment (brminich) [inline src/ucp/tag/rndv.c:231]: maybe better return resulted `length` instead of making it in/out argument

Comment (dmitrygx) [reply src/ucp/tag/rndv.c:231]: done

**Comment by dmitrygx** [comment]
@yosefe @bureddy could you review pls?

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

**Comment by yosefe** [comment]
@dmitrygx are you sure it fixes #4798? IMO it was fixed by another PR

**Comment by dmitrygx** [comment]
@yosefe sorry, wrong issue was referenced in the PR description. Fixed

File: src/ucp/tag/rndv.c [hunk 2]
```diff
@@ -226,6 +227,49 @@ ucs_status_t ucp_tag_send_start_rndv(ucp_request_t *sreq)
     return status;
 }
 
+static UCS_F_ALWAYS_INLINE size_t
+ucp_rndv_adjust_zcopy_length(size_t min_zcopy, size_t max_zcopy, size_t align,
```
Comment (yosefe) [inline src/ucp/tag/rndv.c:231]: maybe rename to ucp_rndv_adjust_**get**_zcopy_length?

File: src/ucp/tag/rndv.c [hunk 3]
```diff
@@ -818,6 +839,8 @@ ucp_rndv_recv_start_get_pipeline(ucp_worker_h worker, ucp_request_t *rndv_req,
     offset = 0;
     while (offset != size) {
         length = ucs_min(size - offset, max_frag_size);
+        length = ucp_rndv_adjust_zcopy_length(min_zcopy, max_frag_size, 0,
```
Comment (yosefe) [inline src/ucp/tag/rndv.c:842]: maybe unite line 841 into the function ucp_rndv_adjust_zcopy_length ?

File: src/ucp/tag/rndv.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c:231]: we are using this function for pipeline PUT Zcopy

Comment (yosefe) [reply src/ucp/tag/rndv.c:231]: seems it's used for ucp_rndv_send_frag_**get**_mem_type

File: src/ucp/tag/rndv.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c:842]: yes, it would be great
but using this function for `ucp_rndv_progress_rma_get_zcopy` in [src/ucp/tag/rndv.c:543](https://github.com/openucx/ucx/blob/dc6d0b738738e77e6d42275a694af0df582aae28/src/ucp/tag/rndv.c#L543) doesn't allow this, since it calculates `length` another way

Comment (yosefe) [reply src/ucp/tag/rndv.c:842]: > but using this function for `ucp_rndv_progress_rma_get_zcopy` in [src/ucp/tag/rndv.c:543](https://github.com/openucx/ucx/blob/dc6d0b738738e77e6d42275a694af0df582aae28/src/ucp/tag/rndv.c#L543) doesn't allow this, since it calculates `length` another way

i think ucs_min with max_get_zcopy is applicable anyway

File: src/ucp/tag/rndv.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c:231]: this function is used for:
- `ucp_rndv_progress_rma_get_zcopy`
- `ucp_rndv_send_start_put_pipeline`
- `ucp_rndv_recv_start_get_pipeline`

File: src/ucp/tag/rndv.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/tag/rndv.c:842]: > i think ucs_min with max_get_zcopy is applicable anyway

yes, we could do it
done, will push after closing [another discussion](https://github.com/openucx/ucx/pull/5273/files#r439962008)

File: src/ucp/tag/rndv.c [hunk 4]
```diff
@@ -497,37 +543,9 @@ UCS_PROFILE_FUNC(ucs_status_t, ucp_rndv_progress_rma_get_zcopy, (self),
...
-        }
-    }
-
-    ucs_assertv(length >= min_zcopy, "length=%zu, min_zcopy=%zu",
-                length, min_zcopy);
-    ucs_assertv(((rndv_req->send.length - (offset + length)) == 0) ||
-                ((rndv_req->send.length - (offset + length)) >= min_zcopy),
-                "send_length=%zu, offset=%zu, length=%zu, min_zcopy=%zu",
-                rndv_req->send.length, offset, length, min_zcopy);
+    length = ucp_rndv_adjust_zcopy_length(min_zcopy, max_zcopy, align,
```
Comment (yosefe) [inline src/ucp/tag/rndv.c:546]: remove line 543

Comment (dmitrygx) [reply src/ucp/tag/rndv.c:546]: it could't be removed, since it calculates the length of the current chunk - i.e. minimum between current chunk's length and remaining length to be sent

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

File: src/ucp/tag/rndv.c (hunk 4 above)
Comment (yosefe) [reply src/ucp/tag/rndv.c:546]: so, maybe in line 543 do `length = rndv_req->send.length - offset`

Comment (dmitrygx) [reply src/ucp/tag/rndv.c:546]: then we should use `chunk` instead of `max_zcopy`:
```
diff --git a/src/ucp/tag/rndv.c b/src/ucp/tag/rndv.c
index 5ebe0f7..c02f5e9 100644
--- a/src/ucp/tag/rndv.c
+++ b/src/ucp/tag/rndv.c
@@ -535,15 +535,16 @@ UCS_PROFILE_FUNC(ucs_status_t, ucp_rndv_progress_rma_get_zcopy, (self),

     if ((offset == 0) && (remaining > 0) && (rndv_req->send.length > ucp_mtu)) {
         length = ucp_mtu - remaining;
+        chunk  = max_zcopy;
     } else {
         chunk = ucs_align_up((size_t)(ucs_min(rndv_req->send.length /
                                               rndv_req->send.rndv_get.lane_count,
                                               max_zcopy) * config->tag.rndv.scale[lane]),
                              align);
-        length = ucs_min(chunk, rndv_req->send.length - offset);
+        length = rndv_req->send.length - offset;
     }

-    length = ucp_rndv_adjust_zcopy_length(min_zcopy, max_zcopy, align,
+    length = ucp_rndv_adjust_zcopy_length(min_zcopy, chunk, align,
                                           rndv_req->send.length, offset,
                                           length);
```
is it ok?

Comment (yosefe) [reply src/ucp/tag/rndv.c:546]: yeah, only question: why changed `ucp_mtu - remaining` to `max_zcopy` ?

Comment (dmitrygx) [reply src/ucp/tag/rndv.c:546]: > why changed `ucp_mtu - remaining` to `max_zcopy` ?

it was not changed, just need to initialize `chunk` to `max_zcopy` to pass `chunk` instead of `max_zcopy` in `ucp_rndv_adjust_zcopy_length`

Comment (yosefe) [reply src/ucp/tag/rndv.c:546]: > it was not changed, just need to initialize `chunk` to `max_zcopy` to pass `chunk` instead of `max_zcopy` in `ucp_rndv_adjust_zcopy_length`

right, so ok

Comment (dmitrygx) [reply src/ucp/tag/rndv.c]: > > it was not changed, just need to initialize `chunk` to `max_zcopy` to pass `chunk` instead of `max_zcopy` in `ucp_rndv_adjust_zcopy_length`
> 
> right, so ok

done :)

**Comment by brminich** [comment]
error looks relevant
```
[ RUN      ] shm_ib/test_ucp_tag_xfer.test_xfer_len_offset/4 <shm,ib>
[swx-rdmz-ucx-new-02:26124:0:26124]        rndv.c:261  Assertion `result_length > ({ typeof(min_zcopy) _max_a = (min_zcopy); typeof(align) _max_b = (align); (_max_a > _max_b) ? _max_a : _max_b; })' failed

/scrap/azure/agent-07/AZP_WORKSPACE/2/s/contrib/../src/ucp/tag/rndv.c: [ ucp_rndv_adjust_zcopy_length() ]
      ...
      258             /* reduce current length by align or min_zcopy value
      259              * to process it on next round */
      260             ucs_assert(result_length > ucs_max(min_zcopy, align));
==>   261             result_length -= ucs_max(min_zcopy, align);
      262         }
      263     }
      264 

```

**Comment by dmitrygx** [comment]
@yosefe ok to merge?
