### PR TITLE
UCP/WIREUP: Do AM KA over AUX_EP or TMP_EP lanes if conn2iface

### LINKED ISSUE #5192: failure on dc_ud/test_ucp_sockaddr_destroy_ep_on_err.onesided_s2c_cforce
```
[2020-05-22T11:18:10.038Z] [ RUN      ] dc_ud/test_ucp_sockaddr_destroy_ep_on_err.onesided_s2c_cforce/8 <dc_x,ud_v,ud_x,mm>
[2020-05-22T11:18:12.832Z] [     INFO ] Testing 65.65.65.12:0
[2020-05-22T11:18:12.832Z] [     INFO ] server listening on 65.65.65.12:51450
[2020-05-22T11:18:13.393Z] [r-vmb-ppc-jenkins:29862:0:29862]       flush.c:51   Fatal: ep 0x3fff9e820000: unsupported endpoint reconfiguration from 2 to 1 lanes during flush
[2020-05-22T11:18:14.784Z] 
[2020-05-22T11:18:14.784Z] /scrap/jenkins/workspace/ucx/contrib/../src/ucp/rma/flush.c: [ ucp_ep_flush_progress() ]
[2020-05-22T11:18:14.784Z]       ...
[2020-05-22T11:18:14.784Z]        46                                           req->send.flush.num_lanes;
[2020-05-22T11:18:14.784Z]        47         if (diff < 0) {
[2020-05-22T11:18:14.784Z]        48             ucs_fatal("ep %p: unsupported endpoint reconfiguration from %d to %d"
[2020-05-22T11:18:14.784Z] ==>    49                       " lanes during flush", ep, req->send.flush.num_lanes,
[2020-05-22T11:18:14.784Z]        50                       ucp_ep_num_lanes(ep));
[2020-05-22T11:18:14.784Z]        51         }
[2020-05-22T11:18:14.784Z]        52 
[2020-05-22T11:18:14.784Z] 
[2020-05-22T11:18:14.784Z] ==== backtrace (tid:  29862) ====
[2020-05-22T11:18:14.784Z]  0 0x000000000005bc58 ucs_debug_print_backtrace()  /scrap/jenkins/workspace/ucx/contrib/../src/ucs/debug/debug.c:656
[2020-05-22T11:18:14.784Z]  1 0x0000000000047718 ucp_ep_flush_progress()  /scrap/jenkins/workspace/ucx/contrib/../src/ucp/rma/flush.c:49
[2020-05-22T11:18:14.785Z]  2 0x0000000000047998 ucp_ep_flush_completion()  /scrap/jenkins/workspace/ucx/contrib/../src/ucp/rma/flush.c:236
[2020-05-22T11:18:14.785Z]  3 0x0000000000080c4c uct_invoke_completion()  /scrap/jenkins/workspace/ucx/contrib/../src/uct/base/uct_iface.h:651
[2020-05-22T11:18:14.785Z]  4 0x0000000000080c4c uct_ud_iface_dispatch_comp()  /scrap/jenkins/workspace/ucx/contrib/../src/uct/ib/ud/base/ud_inl.h:222
[2020-05-22T11:18:14.785Z]  5 0x0000000000080c4c uct_ud_ep_window_release_inline()  /scrap/jenkins/workspace/ucx/contrib/../src/uct/ib/ud/base/ud_ep.c:173
[2020-05-22T11:18:14.785Z]  6 0x0000000000080c4c uct_ud_ep_process_ack()  /scrap/jenkins/workspace/ucx/contrib/../src/uct/ib/ud/base/ud_ep.c:567
[2020-05-22T11:18:14.785Z]  7 0x0000000000080c4c uct_ud_ep_process_rx()  /scrap/jenkins/workspace/ucx/contrib/../src/uct/ib/ud/base/ud_ep.c:777
[2020-05-22T11:18:14.785Z]  8 0x000000000008a99c uct_ud_mlx5_iface_poll_rx()  /scrap/jenkins/workspace/ucx/contrib/../src/uct/ib/ud/accel/ud_mlx5.c:469
[2020-05-22T11:18:14.785Z]  9 0x000000000008a99c uct_ud_mlx5_iface_progress()  /scrap/jenkins/workspace/ucx/contrib/../src/uct/ib/ud/accel/ud_mlx5.c:518
[2020-05-22T11:18:14.785Z] 10 0x00000000000365d4 ucs_callbackq_dispatch()  /scrap/jenkins/workspace/ucx/contrib/../src/ucs/datastruct/callbackq.h:211
[2020-05-22T11:18:14.785Z] 11 0x00000000000365d4 uct_worker_progress()  /scrap/jenkins/workspace/ucx/contrib/../src/uct/api/uct.h:2350
[2020-05-22T11:18:14.785Z] 12 0x00000000000365d4 ucp_worker_progress()  /scrap/jenkins/workspace/ucx/contrib/../src/ucp/core/ucp_worker.c:2004
[2020-05-22T11:18:14.785Z] 13 0x000000001059841c ucp_test_base::entity::progress()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/ucp/ucp_test.cc:750
[2020-05-22T11:18:14.785Z] 14 0x0000000010598520 ucp_test::progress()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/ucp/ucp_test.cc:152
[2020-05-22T11:18:14.785Z] 15 0x000000001057e6c8 test_ucp_sockaddr::one_sided_disconnect()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:460
[2020-05-22T11:18:14.785Z] 16 0x00000000105669a8 test_ucp_sockaddr_destroy_ep_on_err_onesided_s2c_cforce_Test::test_body()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:755
[2020-05-22T11:18:14.785Z] 17 0x00000000101eea08 ucs::test_base::run()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/test.cc:290
[2020-05-22T11:18:14.785Z] 18 0x00000000101eea08 ucs::test_base::TestBodyProxy()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/test.cc:316
[2020-05-22T11:18:14.785Z] 19 0x00000000103ad020 ucp_test::TestBody()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/ucp/ucp_test.h:171
[2020-05-22T11:18:14.785Z] 20 0x00000000101ca95c HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:3562
[2020-05-22T11:18:14.785Z] 21 0x00000000101ca95c testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:3598
[2020-05-22T11:18:14.785Z] 22 0x00000000101b9aec testing::Test::Run()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:3635
[2020-05-22T11:18:14.785Z] 23 0x00000000101b9c4c testing::TestInfo::Run()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:3812
[2020-05-22T11:18:14.785Z] 24 0x00000000101b9e98 testing::TestCase::Run()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:3930
[2020-05-22T11:18:14.785Z] 25 0x00000000101bfe98 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:5808
[2020-05-22T11:18:14.785Z] 26 0x00000000101c02e4 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:5725
[2020-05-22T11:18:14.785Z] 27 0x00000000101c02e4 HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:3562
[2020-05-22T11:18:14.785Z] 28 0x00000000101c02e4 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:3598
[2020-05-22T11:18:14.785Z] 29 0x00000000101c02e4 testing::UnitTest::Run()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest-all.cc:5422
[2020-05-22T11:18:14.785Z] 30 0x00000000101448c8 RUN_ALL_TESTS()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/gtest.h:20059
[2020-05-22T11:18:14.785Z] 31 0x00000000101448c8 main()  /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/main.cc:102
[2020-05-22T11:18:14.785Z] 32 0x0000000000025100 generic_start_main.isra.0()  libc-start.c:0
[2020-05-22T11:18:14.785Z] 33 0x00000000000252f4 __libc_start_main()  ???:0
[2020-05-22T11:18:14.785Z] =================================
[2020-05-22T11:18:14.785Z] Sending notification to binl@mellanox.com
[2020-05-22T11:18:16.832Z] [r-vmb-ppc-jenkins:29862:0:29862] Process frozen...
[2020-05-22T13:32:30.217Z] make: *** [test] Terminated
```

http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/5032/pipeline/

### LINKED ISSUE #6320: ud/test_ucp_sockaddr_protocols_err.tag_zcopy_64k_unexp_sync/3 fails on r-vmb-ppc-jenkins
### Describe the bug
http://hpc-master.lab.mtl.com:8080/blue/rest/organizations/jenkins/pipelines/ucx/runs/10001/nodes/52/steps/491/log/?start=0
```
[2021-02-11T16:43:46.525Z] [ RUN      ] ud/test_ucp_sockaddr_protocols_err.tag_zcopy_64k_unexp_sync/3 <ud_v,cuda_copy,rocm_copy/recv_stop,mt>
[2021-02-11T16:43:46.786Z] [     INFO ] server listening on 65.65.65.12:59416
[2021-02-11T16:43:47.045Z] [1613061826.790491] [r-vmb-ppc-jenkins:29539:0]          wireup.c:137  UCX  ERROR failed to send wireup: Unsupported operation
[2021-02-11T16:43:47.311Z] [     INFO ] ignoring error Connection reset by remote peer on endpoint 0x3fff7a9f0000
[2021-02-11T16:43:47.311Z] [     INFO ] < operation returned error: Endpoint timeout >
[2021-02-11T16:43:47.311Z] /scrap/jenkins/workspace/ucx-4/contrib/../test/gtest/common/test.cc:353: Failure
[2021-02-11T16:43:47.311Z] Failed
[2021-02-11T16:43:47.311Z] Got 1 errors and 0 warnings during the test
[2021-02-11T16:43:47.311Z] [     INFO ] < /scrap/jenkins/workspace/ucx-4/contrib/../src/ucp/wireup/wireup.c:137 failed to send wireup: Unsupported operation >
[2021-02-11T16:43:47.311Z] [  FAILED  ] ud/test_ucp_sockaddr_protocols_err.tag_zcopy_64k_unexp_sync/3, where GetParam() = ud_v,cuda_copy,rocm_copy/recv_stop,mt (600 ms)
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Do AM keepalive over AUX_EP or TMP_EP lanes if AUX EP or TMP_EP current KA lane is `CONNECT_TO_IFACE` in EP check for WIREUP EP.

## Why ?

Fixes #5192
Fixes #6320

## How ?

During EP check for WIREUP EP: If AUX_EP or TMP_EP lane is `CONNECT_TO_EP`, do AM keepalive using `ucp_wireup_msg_send()` for `UCP_WIREUP_MSG_EP_CHECK` packet and pack resource index of a main EP's lane.

### CODE REVIEW

**Comment by yosefe** [comment]
@dmitrygx did it really fix the issue? how much time did it run w/ the fix?

File: src/ucp/wireup/wireup_ep.c [hunk 1]
```diff
@@ -331,33 +331,60 @@ static ucs_status_t ucp_wireup_ep_flush(uct_ep_h uct_ep, unsigned flags,
...
+        }
+        return uct_ep_check(uct_ep, flags, comp);
+    }
+
+    /* if EP_CHECK is not supported by UCT transport, it has to support a
+     * built-in keepalive mechanism to be able to detect peer failure during
+     * wireup
+     */
+    ucs_assert(wiface->attr.cap.flags & UCT_IFACE_FLAG_EP_KEEPALIVE);
+    return UCS_OK;
```
Comment (yosefe) [inline src/ucp/wireup/wireup_ep.c:369]: can we unite common code with ucp ep keepalive?

Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c:369]: will think how to separate the common part and use it here and there

**Comment by dmitrygx** [comment]
> @dmitrygx did it really fix the issue? how much time did it run w/ the fix?

@yosefe I managed to reproduce the bug, I did the test for ~1 hour and no errors appear with the fix.

**Comment by dmitrygx** [comment]
> > @dmitrygx did it really fix the issue? how much time did it run w/ the fix?
> 
> @yosefe I managed to reproduce the bug, I did the test for ~1 hour and no errors appeared with the fix.

sorry, I was wrong, it fails with the current updates - will check why...

**Comment by dmitrygx** [comment]
@brminich @hoopoepg could you review pls?

File: src/ucp/wireup/wireup_ep.c [hunk 2]
```diff
@@ -331,33 +331,50 @@ static ucs_status_t ucp_wireup_ep_flush(uct_ep_h uct_ep, unsigned flags,
...
+{
+    ucp_worker_h worker = checked_ucp_ep->worker;
+    ucp_worker_iface_t *wiface;
+
+    ucs_assert(rsc_idx != UCP_NULL_RESOURCE);
+    ucs_assert(ucp_ep_remote_id(checked_ucp_ep) == ucp_ep_remote_id(ucp_ep));
+
+    wiface = ucp_worker_iface(worker, rsc_idx);
+    ucs_assert(!strict_ep_check ||
+               (wiface->attr.cap.flags & UCT_IFACE_FLAG_EP_CHECK));
```
Comment (brminich) [inline src/ucp/wireup/wireup_ep.c:347]: do we require this `UCT_IFACE_FLAG_EP_CHECK` flag to do new wireup based KA?
imo, we do not have to do that

Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c:347]: > do we require this `UCT_IFACE_FLAG_EP_CHECK` flag to do new wireup based KA?

if a lane is in ep_check_map, it means that this has `UCT_IFACE_FLAG_EP_CHECK` flag

File: src/ucp/core/ucp_ep.inl [hunk 3]
```diff
@@ -277,4 +277,35 @@ static UCS_F_ALWAYS_INLINE int ucp_ep_use_indirect_id(ucp_ep_h ep)
...
+    ucs_status_t status;
+
+    if (ucp_ep_is_am_keepalive(ucp_ep, rsc_idx, remote_conn_required)) {
+        status = ucp_wireup_msg_send(ucp_ep, UCP_WIREUP_MSG_EP_CHECK,
+                                     UCS_BIT(rsc_idx), NULL);
+        ucs_assert(status == UCS_OK);
+        return status;
+    }
+
+    /* coverity[overrun-local] */
```
Comment (hoopoepg) [inline src/ucp/core/ucp_ep.inl:308]: do we still need this?

File: src/ucp/wireup/wireup_ep.c (hunk 2 above)
Comment (brminich) [reply src/ucp/wireup/wireup_ep.c:347]: why do we need to require `UCT_IFACE_FLAG_EP_CHECK` for UCT eps where we do AM/wireup based KA?
Also can it be that the lane supports `UCT_IFACE_FLAG_EP_CHECK` and `UCT_IFACE_FLAG_CONNECT_TO_IFACE`, but does not support AM?

Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c:347]: >  why do we need to require UCT_IFACE_FLAG_EP_CHECK for UCT eps where we do AM/wireup based KA?

The idea is to do AM/wireup for EP which supports EP check and uses connect_to_idwce method. It is the same as KA for main EPs.

If KA is enabled, it means that error handling is requested and AM is required. So, AM will be sent through either wireup lane or AM lane.

File: src/ucp/core/ucp_ep.inl [hunk 4]
```diff
@@ -277,4 +277,34 @@ static UCS_F_ALWAYS_INLINE int ucp_ep_use_indirect_id(ucp_ep_h ep)
...
+     * keepalive message to check the remote endpoint still exists */
+    return (ep->flags & UCP_EP_FLAG_REMOTE_ID) && /* remote ID defined */
+           ((ep->flags & UCP_EP_FLAG_REMOTE_CONNECTED) || /* wireup completed */
+            !remote_conn_required) && /* wireup completed isn't required */
+           (ucp_worker_iface(ep->worker, rsc_idx)->attr.cap.flags &
+            UCT_IFACE_FLAG_CONNECT_TO_IFACE); /* connect-to-iface */
+}
+
+static UCS_F_ALWAYS_INLINE ucs_status_t
+ucp_ep_do_uct_ep_keepalive(ucp_ep_h ucp_ep, uct_ep_h uct_ep,
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.inl:295]: does not have to be inline funciton

File: src/ucp/core/ucp_ep.inl [hunk 5]
```diff
@@ -277,4 +277,34 @@ static UCS_F_ALWAYS_INLINE int ucp_ep_use_indirect_id(ucp_ep_h ep)
...
+
+    if (ucp_ep_is_am_keepalive(ucp_ep, rsc_idx, remote_conn_required)) {
+        status = ucp_wireup_msg_send(ucp_ep, UCP_WIREUP_MSG_EP_CHECK,
+                                     UCS_BIT(rsc_idx), NULL);
+        ucs_assert(status == UCS_OK);
+        return status;
+    }
+
+    return uct_ep_check(uct_ep, flags, comp);
+}
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.inl]: not needed anymore

File: src/ucp/wireup/wireup_ep.c [hunk 6]
```diff
@@ -331,33 +331,50 @@ static ucs_status_t ucp_wireup_ep_flush(uct_ep_h uct_ep, unsigned flags,
     return UCS_ERR_NO_RESOURCE;
 }
 
+static ucs_status_t
+ucp_wireup_ep_do_check(ucp_ep_h checked_ucp_ep, ucp_ep_h ucp_ep,
+                       uct_ep_h uct_ep, ucp_rsc_index_t rsc_idx, unsigned flags,
+                       uct_completion_t *comp, int strict_ep_check)
+{
+    ucp_worker_h worker = checked_ucp_ep->worker;
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c]: removed

File: src/ucp/wireup/wireup_ep.c [hunk 7]
```diff
@@ -331,33 +331,50 @@ static ucs_status_t ucp_wireup_ep_flush(uct_ep_h uct_ep, unsigned flags,
...
-            return uct_ep_check(wireup_ep->aux_ep, flags, comp);
-        }
-
-        /* if EP_CHECK is not supported by auxiliary transport, it has to
-         * support a built-in keepalive mechanism to be able to detect peer
-         * failure during wireup
-         */
-        ucs_assert(wiface->attr.cap.flags & UCT_IFACE_FLAG_EP_KEEPALIVE);
-        return UCS_OK;
+        return ucp_wireup_ep_do_check(ucp_ep,ucp_ep, wireup_ep->aux_ep,
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c]: fixed

File: src/ucp/wireup/wireup_ep.c [hunk 8]
```diff
@@ -331,33 +331,50 @@ static ucs_status_t ucp_wireup_ep_flush(uct_ep_h uct_ep, unsigned flags,
...
+                                      wireup_ep->aux_rsc_index,
+                                      flags, comp, 0);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c]: done

File: src/ucp/core/ucp_ep.inl (hunk 4 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.inl]: done

File: src/ucp/core/ucp_ep.c [hunk 9]
```diff
@@ -757,16 +756,28 @@ void ucp_ep_cleanup_lanes(ucp_ep_h ep)
...
 }
 
+static int
+ucp_ep_local_disconnect_progress_remove_filter(const ucs_callbackq_elem_t *elem,
+                                               void *arg)
+{
+    ucp_ep_h ep = (ucp_ep_h)arg;
+    ucp_request_t *req;
+
+    if (elem->cb == ucp_ep_local_disconnect_progress) {
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:766]: if (!..) return

File: src/ucp/core/ucp_ep.c [hunk 10]
```diff
@@ -757,16 +756,28 @@ void ucp_ep_cleanup_lanes(ucp_ep_h ep)
...
+        req = (ucp_request_t*)elem->arg;
+        if (ep == req->send.ep) {
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:768]: pls comment and assert (if possible) that this request was done to send EP_REMOVED message

File: src/ucp/core/ucp_ep.c [hunk 11]
```diff
@@ -785,8 +796,24 @@ void ucp_ep_disconnected(ucp_ep_h ep, int force)
         return;
     }
 
-    ucp_ep_match_remove_ep(ep->worker, ep);
+    ucp_ep_match_remove_ep(worker, ep);
     ucp_ep_destroy_internal(ep);
+
+    /* remove pending slow-path functions after EP cleanup, because it does
+     * cleanup lanes which purges all outstanding operation and purged
+     * operations coudl add callbacks on the progress */
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:804]: but can't these callbacks try to access a destroyed ep?
which purged operation can add calllacks?

File: src/ucp/core/ucp_ep.c [hunk 12]
```diff
@@ -2408,24 +2435,54 @@ int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
...
 
+ucs_status_t ucp_ep_do_uct_ep_keepalive(ucp_ep_h ucp_ep, uct_ep_h uct_ep,
+                                        ucp_rsc_index_t rsc_idx, unsigned flags,
+                                        uct_completion_t *comp)
+{
+    ucs_status_t status;
+    ucp_request_t req;
+    ssize_t packed_len;
+
+    ucs_assert((rsc_idx == UCP_NULL_RESOURCE) ||
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:2457]: seems UCP_NULL_RESOURCE is checked in called function?

File: src/ucp/core/ucp_ep.c [hunk 13]
```diff
@@ -2408,24 +2435,54 @@ int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
...
+               (ucp_worker_iface(ucp_ep->worker, rsc_idx)->attr.cap.flags &
+                UCT_IFACE_FLAG_EP_CHECK));
+
+    if (ucp_ep_is_am_keepalive(ucp_ep, rsc_idx)) {
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:2461]: maybe 
if (!am_keepalive) {
 retun ep_check
}

File: src/ucp/core/ucp_ep.c [hunk 14]
```diff
@@ -2437,19 +2494,16 @@ void ucp_ep_do_keepalive(ucp_ep_h ep, ucp_lane_map_t *lane_map)
...
             *lane_map &= ~UCS_BIT(lane);
-        } else {
-            /* coverity[overrun-local] */
-            status = uct_ep_check(ep->uct_eps[lane], 0, NULL);
-            if (status == UCS_OK) {
-                *lane_map &= ~UCS_BIT(lane);
-            } else if (status != UCS_ERR_NO_RESOURCE) {
-                *lane_map &= ~UCS_BIT(lane);
+
+            if (ucs_unlikely(status != UCS_OK)) {
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:2506]: this is slowpath, no need for unlikely
also maybe like this
if (status == NO_RESOURCE)
 continue
else if (status != OK)
 ucs_warn(..)

File: src/ucp/wireup/select.c [hunk 15]
```diff
@@ -233,10 +233,16 @@ ucp_wireup_check_keepalive(const ucp_wireup_select_params_t *select_params,
...
 {
-    ucp_worker_h worker = select_params->ep->worker;
+    ucp_worker_h worker              = select_params->ep->worker;
+    uint64_t required_ep_check_flags = UCT_IFACE_FLAG_EP_CHECK;
     char title_keepalive[128];
     char title_ep_check[128];
 
+    if (ucp_ep_init_flags_has_cm(select_params->ep_init_flags) &&
+        (flags & UCT_IFACE_FLAG_CONNECT_TO_IFACE)) {
+        required_ep_check_flags |= UCT_IFACE_FLAG_AM_BCOPY;
```
Comment (yosefe) [inline src/ucp/wireup/select.c:243]: 1. pls add comment it's needed to send keepalive over amctive messages
2. rename required_ep_check_flags  -> iface_flags

File: src/ucp/core/ucp_ep.c [hunk 16]
```diff
@@ -2408,24 +2435,54 @@ int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
...
+    ssize_t packed_len;
+
+    ucs_assert((rsc_idx == UCP_NULL_RESOURCE) ||
+               (ucp_worker_iface(ucp_ep->worker, rsc_idx)->attr.cap.flags &
+                UCT_IFACE_FLAG_EP_CHECK));
+
+    if (ucp_ep_is_am_keepalive(ucp_ep, rsc_idx)) {
+        ucs_assert(ucp_worker_iface(ucp_ep->worker, rsc_idx)->attr.cap.flags &
+                   UCT_IFACE_FLAG_AM_BCOPY);
+        status = ucp_wireup_msg_prepare(&req, ucp_ep, UCP_WIREUP_MSG_EP_CHECK,
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:2464]: why need to have a request object?
maybe change the context of ucp_wireup_msg_pack function that instead of request it will be a pointer to "struct iovec" array. the function will assume it has 2 elements (wireup msg and address).
need to update wireup_msg_progress to create such iovec[2] as local var and pass it to uct_am_bcopy
if needed the 2nd iovec len can be 0

Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c:2464]: good idea
thank you
done

File: src/ucp/core/ucp_ep.c (hunk 10 above)
Comment (yosefe) [reply src/ucp/core/ucp_ep.c]: maybe we can check progress is wireup_msg_progress?

File: src/ucp/wireup/wireup.c [hunk 17]
```diff
@@ -46,10 +46,13 @@
...
 {
-    ucp_request_t *req = arg;
-    *(ucp_wireup_msg_t*)dest = req->send.wireup;
-    memcpy((ucp_wireup_msg_t*)dest + 1, req->send.buffer, req->send.length);
-    return sizeof(ucp_wireup_msg_t) + req->send.length;
+    struct iovec *wireup_msg_iov = (struct iovec*)arg;
+
+    memcpy(dest, wireup_msg_iov[0].iov_base, wireup_msg_iov[0].iov_len);
+    memcpy(UCS_PTR_BYTE_OFFSET(dest, wireup_msg_iov[0].iov_len),
+           wireup_msg_iov[1].iov_base, wireup_msg_iov[1].iov_len);
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:53]: minor: is it possible to reuse some iov copy function (but only if code will be shorter)?

File: src/ucp/core/ucp_ep.c (hunk 12 above)
Comment (yosefe) [reply src/ucp/core/ucp_ep.c:2465]: ok

File: src/ucp/wireup/wireup.c (hunk 17 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:53]: done

File: src/ucp/core/ucp_ep.c (hunk 11 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c:811]: they don't touch a EP

File: src/ucp/core/ucp_ep.c (hunk 10 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: > maybe we can check progress is wireup_msg_progress?

makes sense, done

File: src/ucp/core/ucp_ep.c [hunk 18]
```diff
@@ -772,10 +772,10 @@ ucp_ep_local_disconnect_progress_remove_filter(const ucs_callbackq_elem_t *elem,
...
     }
 
-    /* we expect that only WIREUP_MSG/EP_REMOVED requests can be remained in the
-     * callback queue, because reply UCP EP created for sending this message is
-     * not exposed to a user */
-    ucs_assert(req->send.wireup.type == UCP_WIREUP_MSG_EP_REMOVED);
+    /* we expect that only EP flush request can be remained in the callback
+     * queue, because reply UCP EP created for sending WIREUP_MSG/EP_REMOVED
+     * message is not exposed to a user */
+    ucs_assert(req->send.uct.func == ucp_wireup_msg_progress);
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:778]: check also UCP_WIREUP_MSG_EP_REMOVED

File: src/ucp/wireup/wireup.c [hunk 19]
```diff
@@ -46,13 +47,11 @@
 
 size_t ucp_wireup_msg_pack(void *dest, void *arg)
 {
-    struct iovec *wireup_msg_iov = (struct iovec*)arg;
+    struct iovec *wireup_msg_iov = (struct iovec*)arg;
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:50]: trailing space

File: src/ucp/core/ucp_ep.c (hunk 18 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: I now understand that it is not correct...
an unreleased request is a flush request
fixed

File: src/ucp/wireup/wireup.c (hunk 19 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup.c]: fixed

File: src/ucp/core/ucp_ep.c [hunk 20]
```diff
@@ -2414,25 +2449,66 @@ int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
...
+
+    if (!ucp_ep_is_am_keepalive(ucp_ep, rsc_idx)) {
+        return uct_ep_check(uct_ep, flags, comp);
+    }
+
+    ucs_assert(ucp_worker_iface(ucp_ep->worker, rsc_idx)->attr.cap.flags &
+               UCT_IFACE_FLAG_AM_BCOPY);
+
+    ucs_assert(rsc_idx != UCP_NULL_RESOURCE);
+    UCS_BITMAP_CLEAR(&tl_bitmap);
```
Comment (dmitrygx) [inline src/ucp/core/ucp_ep.c:2485]: @gleon99 is this correct?
it fails with:
```
static checkers found errors:
Error: CPPCHECK_WARNING (CWE-457):
/src/ucp/core/ucp_ep.c:2485: error[uninitvar]: Uninitialized variable: bits
##[error]static checkers found errors
```

File: src/ucp/wireup/select.c [hunk 21]
```diff
@@ -233,10 +233,18 @@ ucp_wireup_check_keepalive(const ucp_wireup_select_params_t *select_params,
                            const char *title, const char **flag_descs,
                            char *reason, size_t max)
 {
-    ucp_worker_h worker = select_params->ep->worker;
+    ucp_worker_h worker  = select_params->ep->worker;
+    uint64_t iface_flags = UCT_IFACE_FLAG_EP_CHECK;
     char title_keepalive[128];
     char title_ep_check[128];
 
+    if (ucp_ep_init_flags_has_cm(select_params->ep_init_flags) &&
```
Comment (dmitrygx) [inline src/ucp/wireup/select.c:241]: @hoopoepg

Comment (hoopoepg) [reply src/ucp/wireup/select.c:241]: may be add evaluation of AM_BCOPY into ucp_ep_do_keepalive?
in this case we will be able to process KA via ep_check on shm based EP's

Comment (dmitrygx) [reply src/ucp/wireup/select.c]: makes sense
will be needed for CMA/KNEM/CUDA-IPC

File: src/ucp/core/ucp_ep.c [hunk 22]
```diff
@@ -791,8 +810,24 @@ void ucp_ep_disconnected(ucp_ep_h ep, int force)
         return;
     }
 
-    ucp_ep_match_remove_ep(ep->worker, ep);
+    ucp_ep_match_remove_ep(worker, ep);
     ucp_ep_destroy_internal(ep);
+
+    /* remove pending slow-path functions after EP cleanup, because it does
+     * cleanup lanes which purges all outstanding operation and purged
+     * operations coudl add callbacks on the progress */
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: fixed

File: src/ucp/core/ucp_ep.c [hunk 23]
```diff
@@ -2457,16 +2457,18 @@ ucp_ep_is_am_keepalive(ucp_ep_h ucp_ep, ucp_rsc_index_t rsc_idx)
            (rsc_idx != UCP_NULL_RESOURCE) && /* rsc index is not NULL, i.e.
                                                 it is not a CM lane */
            (ucp_worker_iface(ucp_ep->worker, rsc_idx)->attr.cap.flags &
-            UCT_IFACE_FLAG_CONNECT_TO_IFACE); /* connect-to-iface */
+            UCT_IFACE_FLAG_CONNECT_TO_IFACE) && /* connect-to-iface */
+           (ucp_worker_iface(ucp_ep->worker, rsc_idx)->attr.cap.flags &
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:2461]: resolve ucp_worker_iface(ucp_ep->worker, rsc_idx)->attr once and save to *iface_attr

File: src/ucp/wireup/wireup.c [hunk 24]
```diff
@@ -102,11 +102,12 @@ static ucp_lane_index_t ucp_wireup_get_msg_lane(ucp_ep_h ep, uint8_t msg_type)
 
 ucs_status_t ucp_wireup_msg_progress(uct_pending_req_t *self)
 {
-    ucp_request_t *req = ucs_container_of(self, ucp_request_t, send.uct);
-    ucp_ep_h ep        = req->send.ep;
-    struct iovec wireup_msg_iov[2];
+    ucp_request_t *req  = ucs_container_of(self, ucp_request_t, send.uct);
+    ucp_ep_h ep         = req->send.ep;
+    ucs_status_t status = UCS_OK;
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:107]: why need to init status?

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c]: removed

File: src/ucp/core/ucp_ep.c (hunk 23 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: fixed

File: src/ucp/core/ucp_ep.c [hunk 25]
```diff
@@ -2451,15 +2451,18 @@ int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
...
-           (rsc_idx != UCP_NULL_RESOURCE) && /* rsc index is not NULL, i.e.
-                                                it is not a CM lane */
-           (ucp_worker_iface(ucp_ep->worker, rsc_idx)->attr.cap.flags &
-            UCT_IFACE_FLAG_CONNECT_TO_IFACE) && /* connect-to-iface */
-           (ucp_worker_iface(ucp_ep->worker, rsc_idx)->attr.cap.flags &
-            UCT_IFACE_FLAG_AM_BCOPY); /* AM Bcopy support */
+    return /* remote ID defined */
+           (ucp_ep->flags & UCP_EP_FLAG_REMOTE_ID) &&
+           /* rsc index is not NULL, i.e. it is not a CM lane */
+           (rsc_idx != UCP_NULL_RESOURCE) &&
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:2461]: sorry, now i noticed we should check rsc_idx != UCP_NULL_RESOURCE before doing ucp_worker_iface(ucp_ep->worker, rsc_idx);

Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: fixed
hopefully, we will see some error with valgrind
I didn't see with just running gtest/sockaddr

File: src/ucp/core/ucp_ep.c [hunk 26]
```diff
@@ -2414,14 +2449,60 @@ int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
...
      * keepalive message to check the remote endpoint still exists */
-    return (ep->flags & UCP_EP_FLAG_REMOTE_ID) && /* remote ID defined */
-           (ep->flags & UCP_EP_FLAG_REMOTE_CONNECTED) && /* wireup completed */
-           (ucp_ep_get_iface_attr(ep, lane)->cap.flags &
-            UCT_IFACE_FLAG_CONNECT_TO_IFACE); /* connect-to-iface */
+    return /* remote ID defined */
+           (ucp_ep->flags & UCP_EP_FLAG_REMOTE_ID) &&
+           /* rsc index is not NULL, i.e. it is not a CM lane */
+           (rsc_idx != UCP_NULL_RESOURCE) &&
+           /* connect-to-iface */
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: removed

File: src/ucp/core/ucp_ep.c [hunk 27]
```diff
@@ -2414,14 +2449,60 @@ int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
...
+           (wiface->attr.cap.flags & UCT_IFACE_FLAG_CONNECT_TO_IFACE) &&
+           /* AM Bcopy support */
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: removed

File: src/ucp/core/ucp_ep.c [hunk 28]
```diff
@@ -2448,20 +2448,23 @@ int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
...
+
+    if (!(ucp_ep->flags & UCP_EP_FLAG_REMOTE_ID) ||
+        (rsc_idx == UCP_NULL_RESOURCE)) {
+        /* if remote ID isn't defined or rsc index is NULL (i.e. it is CM lane),
+         * don't do AM keepalive */
+        return 0;
+    }
+
+    wiface = ucp_worker_iface(ucp_ep->worker, rsc_idx);
+
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:2466]: minor: remove space line

**Review by yosefe — COMMENTED** [review]
can squash after fix

File: src/ucp/core/ucp_ep.c [hunk 29]
```diff
@@ -2413,15 +2448,64 @@ int ucp_ep_config_test_rndv_support(const ucp_ep_config_t *config)
...
+    return (wiface->attr.cap.flags & UCT_IFACE_FLAG_CONNECT_TO_IFACE) &&
+           (wiface->attr.cap.flags & UCT_IFACE_FLAG_AM_BCOPY);
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:2468]: minor: can use test_all_flags

File: src/ucp/core/ucp_ep.c (hunk 28 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: fixed

File: src/ucp/core/ucp_ep.c (hunk 29 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: fixed

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@brminich could you take a look pls?

**Comment by dmitrygx** [comment]
@yosefe @brminich Jenkins pipe reports that PPC nodes are offline, should we wait for them?

**Review by brminich — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe @brminich ok to merge?
