### PR TITLE
UCT/TCP: Close fd in EP if EP was created

### LINKED ISSUE #5438: tcp/test_ucp_peer_failure.basic/1 failure
```
[2020-07-19T18:49:31.304Z] [ RUN      ] tcp/test_ucp_peer_failure.basic/1 <tcp>
[2020-07-19T18:49:31.304Z] [     INFO ] < connect(fd=16, dest_addr=10.209.44.35:48547) failed: Connection refused >
[2020-07-19T18:49:31.304Z] [     INFO ] < try to increase "net.core.somaxconn", "net.core.netdev_max_backlog", "net.ipv4.tcp_max_syn_backlog" to the maximum value on the remote node or increase UCX_TCP_MAX_CONN_RETRIES (=25) >
[2020-07-19T18:49:31.304Z] [1595184571.188035] [hpc-test-node-upstream-01:25685:0]           sock.c:47   UCX  WARN  failed to close fd 16: Bad file descriptor
[2020-07-19T18:49:31.304Z] [1595184571.188050] [hpc-test-node-upstream-01:25685:0]           sock.c:47   UCX  WARN  failed to close fd 16: Bad file descriptor
[2020-07-19T18:49:31.304Z] [     INFO ] < connect(fd=16, dest_addr=2.1.4.201:50867) failed: Connection refused >
[2020-07-19T18:49:31.304Z] [     INFO ] < try to increase "net.core.somaxconn", "net.core.netdev_max_backlog", "net.ipv4.tcp_max_syn_backlog" to the maximum value on the remote node or increase UCX_TCP_MAX_CONN_RETRIES (=25) >
[2020-07-19T18:49:31.304Z] [1595184571.188133] [hpc-test-node-upstream-01:25685:0]           sock.c:47   UCX  WARN  failed to close fd 16: Bad file descriptor
[2020-07-19T18:49:31.304Z] [1595184571.188143] [hpc-test-node-upstream-01:25685:0]           sock.c:47   UCX  WARN  failed to close fd 16: Bad file descriptor
[2020-07-19T18:49:31.304Z] /scrap/jenkins/workspace/ucx/contrib/../test/gtest/common/test.cc:283: Failure
[2020-07-19T18:49:31.304Z] Failed
[2020-07-19T18:49:31.304Z] Got 4 warnings during the test
[2020-07-19T18:49:31.304Z] [  FAILED  ] tcp/test_ucp_peer_failure.basic/1, where GetParam() = tcp (81 ms)
```
http://hpc-master.lab.mtl.com:8080/blue/rest/organizations/jenkins/pipelines/ucx/runs/6137/nodes/128/steps/1031/log/?start=0

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix "Bad fd" warning from `ucs_close_fd()`

## Why ?

Fixes #5438

## How ?

Need to check whether EP was created or not:
- if  created: close fd from EP
- if not created: close fd from local variable

### CODE REVIEW

File: src/uct/tcp/tcp_ep.c [hunk 1]
```diff
@@ -385,11 +385,12 @@ uct_tcp_ep_create_socket_and_connect(uct_tcp_iface_t *iface,
     if (*ep_p == NULL) {
         uct_tcp_ep_destroy_internal(&ep->super.super);
     }
-err_close_fd:
-    /* fd has to be valid in case of valid EP has been
-     * passed to this function */
-    ucs_assert((*ep_p == NULL) || (fd != -1));
-    ucs_close_fd(&fd);
+err_close_fd:;
```
Comment (brminich) [inline src/uct/tcp/tcp_ep.c:388]: extra `;`

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: fixed

File: src/uct/tcp/tcp_ep.c [hunk 2]
```diff
@@ -386,10 +386,11 @@ uct_tcp_ep_create_socket_and_connect(uct_tcp_iface_t *iface,
...
     }
 err_close_fd:
-    /* fd has to be valid in case of valid EP has been
-     * passed to this function */
-    ucs_assert((*ep_p == NULL) || (fd != -1));
-    ucs_close_fd(&fd);
+    if (ep != NULL) {
+        ucs_close_fd(&ep->fd);
+    } else {
+        ucs_close_fd(&fd);
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:392]: are we closing fd which was not created in this function?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c:392]: no, this fd is created here, but it could be assigned to EP or not. If was assigned, i.e. EP isn't `NULL`, we have to close it from EP to fill by `-1`

Comment (yosefe) [reply src/uct/tcp/tcp_ep.c:392]: ok so why we can't always ucs_close_fd(&fd); ?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c:392]: > ok so why we can't always ucs_close_fd(&fd); ?

to not close then same FD twice from EP there:
https://github.com/openucx/ucx/blob/7f9a7f7a0d67a6143e163c378fbf76f47c15115f/src/uct/tcp/tcp_ep.c#L579

the `ucs_close_fd()` will set -1 to  the EP's fd

Comment (yosefe) [reply src/uct/tcp/tcp_ep.c:392]: looks weird
maybe move line 392 to line 363?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > maybe move line 392 to line 363?

yes, it works
done
