### PR TITLE
GTEST/COMMON: Add more safety margin for the watchdog test

### LINKED ISSUE #3404: failure in test_watchdog.watchdog_timeout
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9432/label=r-vmb-ppc-jenkins,worker=0/console
```
17:21:16 ++ date +%s
17:21:16 + start_time=1553095276
17:21:16 + pid=16561
17:21:16 + wait 16561
17:21:16 + env WATCHDOG_GTEST_TIMEOUT_=5 GTEST_FILTER=test_watchdog.watchdog_timeout ./test/gtest/gtest
17:21:16 + tee watchdog_timeout_test
17:21:18 [     INFO ] checking dcx: yes
17:21:18 [     INFO ] checking ud: yes
17:21:19 [     INFO ] checking udx: yes
17:21:19 [     INFO ] checking rc: yes
17:21:19 [     INFO ] checking rcx: yes
17:21:19 [     INFO ] checking shm_ib: yes
17:21:20 [     INFO ] checking ugni: no
17:21:21 [     INFO ] checking self: yes
17:21:21 [     INFO ] checking tcp: yes
17:21:21 [     INFO ] checking all_rcdc: yes
17:21:21 [     INFO ] checking all: yes
17:21:21 [     INFO ] checking rc_x: yes
17:21:21 [     INFO ] checking ud_mlx5: yes
17:21:21 [     INFO ] checking shm: yes
17:21:21 [     INFO ] checking dc_ud: yes
17:21:22 [     INFO ] checking no_ud_ud_x: yes
17:21:22 [     INFO ] Using random seed of 23154
17:21:22 Note: Google Test filter = test_watchdog.watchdog_timeout
17:21:22 [==========] Running 1 test from 1 test case.
17:21:22 [----------] Global test environment set-up.
17:21:22 [----------] 1 test from test_watchdog, where TypeParam = 
17:21:22 [ RUN      ] test_watchdog.watchdog_timeout
17:21:27 /scrap/jenkins/workspace/hpc-ucx-pr-4/label/r-vmb-ppc-jenkins/worker/0/contrib/../test/gtest/common/test_helpers.cc:42: Failure
17:21:27 Failed
17:21:27 Connection timed out - abort testing
17:21:27 ++ date +%s
17:21:27 + end_time=1553095287
17:21:27 ++ grep -x 'Connection timed out - abort testing' watchdog_timeout_test
17:21:27 + res='Connection timed out - abort testing'
17:21:27 + rm -f watchdog_timeout_test
17:21:27 + '[' 'Connection timed out - abort testing' '!=' 'Connection timed out - abort testing' ']'
17:21:27 + run_time=11
17:21:27 + expected_run_time=10
17:21:27 + '[' 11 -gt 10 ']'
17:21:27 + echo 'Watchdog timeout test takes 11 seconds that' 'is greater than expected 10 seconds'
17:21:27 Watchdog timeout test takes 11 seconds that is greater than expected 10 seconds
17:21:27 + exit 1
17:21:27 
```

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What

Fixes #3404 

## Why ?

Make the testing stable enough under high load

## How ?

Increase `sleep(...)` time (1 minute) value through `WATCHDOG_GTEST_SLEEP_TIME_` env  and expected timeout (5 minutes) in the `test_jenkins.sh` script.

### CODE REVIEW

File: contrib/test_jenkins.sh [hunk 1]
```diff
@@ -937,14 +937,17 @@ run_coverity() {
 }
 
 run_gtest_watchdog_test() {
-	expected_run_time=$1
+	watchdog_timeout=$1
```
Comment (hoopoepg) [inline contrib/test_jenkins.sh]: something wrong with indent?

File: test/gtest/common/test_watchdog.cc [hunk 2]
```diff
@@ -72,23 +72,30 @@ UCS_TEST_F(test_watchdog, watchdog_signal) {
...
     }
-    ASSERT_TRUE(p != NULL);
+    ASSERT_TRUE(gtest_timeout != NULL);
 
-    timeout = atof(p);
+    gtest_sleep_time = getenv("WATCHDOG_GTEST_SLEEP_TIME_");
+    if (gtest_sleep_time == NULL) {
+        UCS_TEST_SKIP_R("WATCHDOG_GTEST_SLEEP_TIME_ is not set");
+    }
+    ASSERT_TRUE(gtest_sleep_time != NULL);
```
Comment (hoopoepg) [inline test/gtest/common/test_watchdog.cc]: can this assert be fired? it is checked few lines above

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9450/ for details (Mellanox internal link).

File: test/gtest/common/test_watchdog.cc (hunk 2 above)
Comment (brminich) [reply test/gtest/common/test_watchdog.cc]: I guess @hoopoepg  means that you just checked that `gtest_sleep_time == NULL`  on line 88

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9454/ for details (Mellanox internal link).

File: test/gtest/common/test_watchdog.cc (hunk 2 above)
Comment (dmitrygladkov) [reply test/gtest/common/test_watchdog.cc]: thanks @hoopoepg @brminich got it. fixed here and in the place from where the code was copied.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9459/ for details (Mellanox internal link).
