### PR TITLE
GTEST/UCP: Fix mmap tests for 0-length RMA

### LINKED ISSUE #5840: failure in  rcx/test_ucp_mmap.reg_mem_type/0
### Describe the bug
Happened in https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/10347/logs/131

```
2020-10-27T19:18:06.3277686Z [----------] 4 tests from rcx/test_ucp_mmap
2020-10-27T19:18:06.3278476Z [ RUN      ] rcx/test_ucp_mmap.reg_mem_type/0 <rc_x>
2020-10-27T19:18:06.4977541Z /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_mmap.cc:178: Failure
2020-10-27T19:18:06.4979836Z Expected: (&ucp_rma_sw_proto) != (rkey->cache.rma_proto), actual: 0xffffa5030948 vs 0xffffa5030948
2020-10-27T19:18:07.1514682Z [  FAILED  ] rcx/test_ucp_mmap.reg_mem_type/0, where GetParam() = rc_x (824 ms)
```

### LINKED ISSUE #5918: rc/test_ucp_mmap.reg_mem_type/1 failure on ppc
```
[2020-11-17T20:14:17.771Z] [ RUN      ] rc/test_ucp_mmap.reg_mem_type/1 <rc_v/map_nb>
[2020-11-17T20:14:18.387Z] /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/ucp/test_ucp_mmap.cc:167: Failure
[2020-11-17T20:14:18.387Z] Expected: (&ucp_rma_sw_proto) != (rkey->cache.rma_proto), actual: 0x3fffb0a22940 vs 0x3fffb0a22940
[2020-11-17T20:14:18.643Z] [  FAILED  ] rc/test_ucp_mmap.reg_mem_type/1, where GetParam() = rc_v/map_nb (676 ms)
```
on r-vmb-ppc-jenkins
Job link: http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/8045/pipeline/770
Log link: http://hpc-master.lab.mtl.com:8080/blue/rest/organizations/jenkins/pipelines/ucx/runs/8045/nodes/73/steps/782/log/?start=0

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix mmap tests for 0-length RMA

## Why ?

Fixes #5840 (#5918)

## How ?

1. Fix code style violations
2. Expect SW proto for TLs with non-RMA offload (all TLs except RC/DC, SHM, SELF) and for TLs with RMA offload, but zero-length (or NULL) buffer

### CODE REVIEW

**Comment by dmitrygx** [comment]
@hoopoepg @brminich could you review pls?

**Review by hoopoepg — APPROVED** [review]

File: test/gtest/ucp/test_ucp_mmap.cc [hunk 1]
```diff
@@ -314,8 +318,12 @@ void test_ucp_mmap::test_length0(unsigned flags)
     status = ucp_mem_map(sender().ucph(), &params, &memh[1]);
     ASSERT_UCS_OK(status);
 
+    bool expect_rma_offload = is_tl_rdma() ||
+                              ((flags & UCP_MEM_MAP_ALLOCATE) &&
+                               is_tl_shm());
+
     for (i = 0; i < buf_num; i++) {
-        test_rkey_management(&sender(), memh[i], true, false);
+        test_rkey_management(&sender(), memh[i], true, expect_rma_offload);
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_mmap.cc:326]: i don't understand how the PR fixes test failure: before the change, we passed expect_rma_offload:false to test_rkey_management(), so the EXPECT_NE should not have been called anyway because of ` if (expect_rma_offload && is_dummy) {`

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_mmap.cc:326]: i.e. SW RMA proto has to be used in case of dummy protocol in case dummy and even if it is RMA offload

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_mmap.cc:326]: @yosefe are you agree with the fix?

Comment (yosefe) [reply test/gtest/ucp/test_ucp_mmap.cc:326]: can't we always pass "false" here for expect_rma_offload?

File: test/gtest/ucp/test_ucp_mmap.cc [hunk 2]
```diff
@@ -163,8 +163,12 @@ void test_ucp_mmap::test_rkey_management(entity *e, ucp_mem_h memh,
...
     }
 
-    if (expect_rma_offload && is_dummy) {
-        EXPECT_NE(&ucp_rma_sw_proto, rkey->cache.rma_proto);
+    if (expect_rma_offload) {
+        if (is_dummy) {
+            EXPECT_EQ(&ucp_rma_sw_proto, rkey->cache.rma_proto);
+        } else {
+            EXPECT_EQ(&ucp_rma_basic_proto, rkey->cache.rma_proto);
+        }
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_mmap.cc:171]: maybe just
```
if (expect_rma_offload && !is_dummy) {
    EXPECT_EQ(&ucp_rma_basic_proto, rkey->cache.rma_proto);
}
```

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_mmap.cc:171]: maybe worth checking that in the case of dummy buffer we select SW proto?

File: test/gtest/ucp/test_ucp_mmap.cc (hunk 1 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_mmap.cc:326]: I think it is better to check what we select in case of dummy proto, so also `rand()` not always covers `0` case. So, here we always will cover it

Comment (yosefe) [reply test/gtest/ucp/test_ucp_mmap.cc:326]: so maybe like this:
```
if (expect_rma_offload) {
            EXPECT_EQ(&ucp_rma_basic_proto, rkey->cache.rma_proto);
     } else {
            EXPECT_EQ(&ucp_rma_sw_proto, rkey->cache.rma_proto);
   }
```

and set expect_rma_offload accordingly

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_mmap.cc:326]: then we have to check `is_dummy()` for tests that use `rand()` to generate message size and `is_dummy` check will be considered in `expect_rma_offload`.
are you ok with it?

File: test/gtest/ucp/test_ucp_mmap.cc (hunk 2 above)
Comment (yosefe) [reply test/gtest/ucp/test_ucp_mmap.cc:171]: maybe this?
```
if (expect_rma_offload && !is_dummy) {
    EXPECT_EQ(&ucp_rma_basic_proto, rkey->cache.rma_proto);
} else {
  EXPECT_EQ(&ucp_rma_sw_proto, rkey->cache.rma_proto);
```

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_mmap.cc:171]: unfortunately, it doesn't work for `shm_ib` test variant, since we couldn't expect whether we could use or not RMA offload. But if we could, it means whether IB (RC or DC) was selected or mmap method=allocation and SHM was selected.

**Comment by dmitrygx** [comment]
@yosefe ping :)

**Review by yosefe — APPROVED** [review]
