### PR TITLE
UCT/UD: Don't report errors for internal endpoints

### LINKED ISSUE #2336: failure in rc/test_ucp_peer_failure_with_rma.status_after_error/3
Happened in:
 http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/label=hpc-arm-hwi01,worker=0/6330/console

```
14:00:23 [----------] 1 test from rc/test_ucp_peer_failure_with_rma
14:00:23 [ RUN      ] rc/test_ucp_peer_failure_with_rma.status_after_error/3
14:00:29 [hpc-arm-hwi01:7645 :0:7645]  ucp_worker.c:368  Fatal: no uct_ep_h 0x1c0d4090 associated with ucp_ep_h on ucp_worker_h 0x1c7f0010
14:00:31 
14:00:31 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../src/ucp/core/ucp_worker.c: [ ucp_worker_iface_error_handler() ]
14:00:31       ...
14:00:31       364     });
14:00:31       365 
14:00:31       366     ucs_fatal("no uct_ep_h %p associated with ucp_ep_h on ucp_worker_h %p",
14:00:31 ==>   367               uct_ep, worker);
14:00:31       368 
14:00:31       369 found_ucp_ep:
14:00:31       370     if (ucp_ep_config(ucp_ep)->key.err_mode == UCP_ERR_HANDLING_MODE_NONE) {
14:00:31 
14:00:32 ==== backtrace ====
14:00:32  0 0x0000000000023c3c ucp_worker_iface_error_handler()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../src/ucp/core/ucp_worker.c:367
14:00:32  1 0x0000000000021aa0 uct_set_ep_failed()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../src/uct/base/uct_iface.c:365
14:00:32  2 0x000000000007d5cc uct_ud_iface_dispatch_async_comps_do()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../src/uct/ib/ud/base/ud_iface.c:770
14:00:32  3 0x0000000000083300 uct_ud_iface_dispatch_zcopy_comps()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../src/uct/ib/ud/base/ud_iface.h:443
14:00:32  4 0x0000000000022164 uct_iface_progress()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../src/uct/api/uct.h:2409
14:00:32  5 0x00000000000447ac ucs_callbackq_slow_proxy()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../src/ucs/datastruct/callbackq.c:393
14:00:32  6 0x0000000000024948 ucs_callbackq_dispatch()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../src/ucs/datastruct/callbackq.h:208
14:00:32  7 0x000000000066c3f0 ucp_test_base::entity::progress()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/ucp/ucp_test.cc:502
14:00:32  8 0x0000000000634578 test_ucp_tag::wait()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/ucp/test_ucp_tag.cc:118
14:00:32  9 0x0000000000634c68 test_ucp_tag::send_b()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/ucp/test_ucp_tag.cc:204
14:00:32 10 0x000000000058edd8 test_ucp_peer_failure::smoke_test()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/ucp/test_ucp_peer_failure.cc:110
14:00:32 11 0x0000000000584a98 test_ucp_peer_failure::init()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/ucp/test_ucp_peer_failure.cc:147
14:00:32 12 0x000000000047e098 ucs::test_base::SetUpProxy()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/common/test.cc:229
14:00:32 13 0x0000000000472b9c HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/common/gtest-all.cc:3562
14:00:32 14 0x00000000004672a8 testing::Test::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/common/gtest-all.cc:3630
14:00:32 15 0x0000000000467424 testing::TestInfo::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/common/gtest-all.cc:3812
14:00:32 16 0x0000000000467594 testing::TestCase::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/common/gtest-all.cc:3930
14:00:32 17 0x000000000046b9a4 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/common/gtest-all.cc:5802
14:00:32 18 0x000000000046bcc0 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/common/gtest-all.cc:5719
14:00:32 19 0x0000000000415e4c RUN_ALL_TESTS()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi01/worker/0/contrib/../test/gtest/common/gtest.h:20059
14:00:32 20 0x0000000000020d64 __libc_start_main()  :0
14:00:32 21 0x0000000000451ccc _start()  :0
14:00:32 ===================
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2336

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7129/ for details (Mellanox internal link).

File: src/uct/ib/ud/base/ud_ep.h [hunk 1]
```diff
@@ -188,9 +188,9 @@ enum {
     UCT_UD_EP_FLAG_ASYNC_COMPS       = UCS_BIT(0), /* set if there are completions that
                                                     * were picked by async thread and queued */
     UCT_UD_EP_FLAG_DISCONNECTED      = UCS_BIT(1), /* set if the endpoint was disconnected */
+    UCT_UD_EP_FLAG_PRIVATE           = UCS_BIT(2), /* EP is was created as internal */
```
Comment (brminich) [inline src/uct/ib/ud/base/ud_ep.h]: where do you set it?

Comment (yosefe) [reply src/uct/ib/ud/base/ud_ep.h]: https://github.com/openucx/ucx/blob/master/src/uct/ib/ud/base/ud_ep.c#L507
