### PR TITLE
UCP/WIREUP: Allow EP check during WIREUP phase

### LINKED ISSUE #6011: hang in rcx/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/7
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/11604/logs/182
```
2020-12-09T19:44:18.3890560Z [ RUN      ] rcx/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/7 <rc_x/stream,cm,mt>
2020-12-09T19:44:19.7736288Z [     INFO ] Testing fe80::ba59:9fff:fe0a:75b9:0
2020-12-09T19:44:19.7756712Z [     INFO ] server listening on fe80::ba59:9fff:fe0a:75b9:34214
2020-12-09T19:44:29.9840841Z /scrap/azure/agent-03/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:700: Failure
2020-12-09T19:44:29.9842674Z Expected: (UCS_INPROGRESS) != (status), actual: 1 vs 1
2020-12-09T19:44:29.9844009Z free not completed EP close request: 0xd1b7b28
2020-12-09T19:59:30.0020556Z /scrap/azure/agent-03/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/test_helpers.cc:53: Failure
2020-12-09T19:59:30.0022368Z Failed
2020-12-09T19:59:30.0023741Z Connection timed out - abort testing
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Allow EP check during WIREUP phase, i.e. UCP will do KA during WIREUP pahse.

## Why ?

The remote peer could be failed or forcibly closed during WIREUP MSG phase, e.g. as in #6011 issue:
- server closes EP forcibly after receiving and handling RDMA CM event "CONNECT REQUEST".
- client receives RDMA CM event "CONNECT RESPONSE".
- client does `rdma_establish()` and UCT informs client about connect completion. CM phase is considered as completed on a client side. Server will start WIREUP MSG phase after from CM's `conn_notify_cb` callback
- client hangs for a while since neither WIREUP "PRE_REQUEST" message nor RDMA CM event "DISCONNECTED" was received.

Fixes #6011.
Enabling KA by default (#6059) will fix the issue fully.

## How ?

Do WIREUP EP check if UCT EP is locally connected or auxiliary UCT EP is not a `NULL` and supports `UCT_IFACE_FLAG_EP_CHECK`; otherwise - return `UCS_OK`.

### CODE REVIEW

File: src/ucp/wireup/wireup_ep.c [hunk 1]
```diff
@@ -330,13 +330,30 @@ static ucs_status_t ucp_wireup_ep_flush(uct_ep_h uct_ep, unsigned flags,
...
 
+static ucs_status_t ucp_wireup_ep_check(uct_ep_h uct_ep, unsigned flags,
+                                        uct_completion_t *comp)
+{
+    ucp_wireup_ep_t *wireup_ep = ucp_wireup_ep(uct_ep);
+    ucp_worker_h worker        = wireup_ep->super.ucp_ep->worker;
+
+    if (wireup_ep->flags & UCP_WIREUP_EP_FLAG_LOCAL_CONNECTED) {
+        return uct_ep_check(wireup_ep->super.uct_ep, flags, comp);
+    } else if ((wireup_ep->aux_ep != NULL) &&
```
Comment (yosefe) [inline src/ucp/wireup/wireup_ep.c:341]: can remove 'else'
BTW, why need to check UCT_IFACE_FLAG_EP_CHECK flag? i would expect UCP keepalive mechanism to check this already

Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c]: removed
The check EP_CHECK flag is needed, since UCP KA mechanism checks it only for iface which `wireup_ep->super.uct_ep` belongs to (e.g. next_ep - RC, aux_ep - UD. but UD doesn't have EP_CHECK support)

Comment (yosefe) [reply src/ucp/wireup/wireup_ep.c]: so we need to make sure only transports which have CHECK support are used as aux_ep

Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c]: then UD couldn't be used as aux_ep

Comment (yosefe) [reply src/ucp/wireup/wireup_ep.c]: ok, is it a problem?
BTW need to make sure UCP would really send keepalive on the ep used for wireup messages, and that ep keepalive list is updated when ep configuration changes

**Comment by dmitrygx** [comment]
depends on #6080 and #6078

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by dmitrygx** [comment]
@hoopoepg could you review pls?

File: src/ucp/wireup/wireup_ep.c (hunk 1 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c]: done, now doing EP check over UCT if connected, and otherwise - over AUX EP

**Comment by dmitrygx** [comment]
re-run tests against the current master, since #6059 was merged

**Comment by dmitrygx** [comment]
bot:pipe:retest

File: src/ucp/core/ucp_ep.c [hunk 2]
```diff
@@ -803,6 +804,10 @@ static void ucp_destroyed_ep_pending_purge(uct_pending_req_t *self, void *arg)
 
 void ucp_ep_destroy_internal(ucp_ep_h ep)
 {
+    if (--ep->ref_cnt != 0) {
```
Comment (Artemy-Mellanox) [inline src/ucp/core/ucp_ep.c:807]: This way we leave ucp_ep visible to keepalive_pregress but not checkable (ep_check returns timeout). Hence warnings in ucp_ep_do_keepalive().

Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: > This way we leave ucp_ep visible to keepalive_progress but not checkable (ep_check returns timeout). Hence warnings in ucp_ep_do_keepalive().

@Artemy-Mellanox good catch, thank you!
moved this check to `ucp_ep_destroy_base()` where UCP EP is about to be removed

**Comment by dmitrygx** [comment]
@yosefe @Artemy-Mellanox could you review pls?

File: src/ucp/core/ucp_ep.c [hunk 3]
```diff
@@ -157,6 +158,14 @@ ucs_status_t ucp_ep_create_base(ucp_worker_h worker, const char *peer_name,
 
 void ucp_ep_destroy_base(ucp_ep_h ep)
 {
+    ucs_assert(!(ep->flags & UCP_EP_FLAG_DESTROYED) && (ep->ref_cnt > 0));
+
+    if (--ep->ref_cnt != 0) {
+        return;
+    }
+
+    ep->flags |= UCP_EP_FLAG_DESTROYED;
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:167]: how does it work if ep is released right after?

File: src/ucp/core/ucp_worker.c [hunk 4]
```diff
@@ -2794,6 +2794,8 @@ ucp_worker_discard_tl_uct_ep(ucp_worker_h worker, uct_ep_h uct_ep,
         return;
     }
 
+    ucs_assert(ucp_ep->ref_cnt != UINT8_MAX);
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:2797]: maybe < UINT8_MAX

File: src/ucp/wireup/select.c [hunk 5]
```diff
@@ -361,6 +361,18 @@ ucp_wireup_select_transport(const ucp_wireup_select_params_t *select_params,
...
+               * and either built-in Keep Alive (i.e. UCT_IFACE_FLAG_EP_KEEPALIVE)
+               * or EP checking (i.e. UCT_IFACE_FLAG_EP_CHECK) */
+              !ucp_worker_keepalive_is_enabled(worker) ||
+              !(select_params->ep_init_flags & UCP_EP_INIT_ERR_MODE_PEER_FAILURE) ||
+              ucp_wireup_check_flags(resource, iface_attr->cap.flags,
+                                      UCT_IFACE_FLAG_EP_KEEPALIVE, criteria->title,
+                                      ucp_wireup_iface_flags, p, endp - p) ||
+              ucp_wireup_check_flags(resource, iface_attr->cap.flags,
+                                     UCT_IFACE_FLAG_EP_CHECK, criteria->title,
+                                     ucp_wireup_iface_flags, p, endp - p)) ||
```
Comment (yosefe) [inline src/ucp/wireup/select.c:375]: maybe use a helper function?

File: src/ucp/wireup/wireup_ep.c [hunk 6]
```diff
@@ -331,13 +331,39 @@ static ucs_status_t ucp_wireup_ep_flush(uct_ep_h uct_ep, unsigned flags,
...
+
+    if (wireup_ep->aux_ep != NULL) {
+        ucs_assert(wireup_ep->aux_rsc_index != UCP_NULL_RESOURCE);
+
+        if (ucp_worker_iface(worker, wireup_ep->aux_rsc_index)->attr.cap.flags &
+            UCT_IFACE_FLAG_EP_CHECK) {
+            return uct_ep_check(wireup_ep->aux_ep, flags, comp);
+        }
+
+        ucs_assert(ucp_worker_iface(worker,
```
Comment (yosefe) [inline src/ucp/wireup/wireup_ep.c:352]: pls add comment

File: src/ucp/core/ucp_ep.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: removed

File: src/ucp/core/ucp_worker.c (hunk 4 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c]: fixed

File: src/ucp/wireup/wireup_ep.c (hunk 6 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup_ep.c:356]: done

File: src/ucp/wireup/select.c (hunk 5 above)
Comment (dmitrygx) [reply src/ucp/wireup/select.c]: added the helper function

File: src/ucp/wireup/select.c [hunk 7]
```diff
@@ -225,6 +225,26 @@ static int ucp_wireup_check_amo_flags(const uct_tl_resource_desc_t *resource,
...
+    return /* if error handling and keepalive were requested, UCT iface has to
+            * support peer failure (i.e. UCT_IFACE_FLAG_ERRHANDLE_PEER_FAILURE)
+            * and either built-in keepalive (i.e. UCT_IFACE_FLAG_EP_KEEPALIVE)
+            * or EP checking (i.e. UCT_IFACE_FLAG_EP_CHECK) */
+           !ucp_worker_keepalive_is_enabled(worker) ||
+           !(select_params->ep_init_flags & UCP_EP_INIT_ERR_MODE_PEER_FAILURE) ||
+           ucp_wireup_check_flags(resource, flags, UCT_IFACE_FLAG_EP_KEEPALIVE, title,
+                                  ucp_wireup_iface_flags, reason, max) ||
+           ucp_wireup_check_flags(resource, flags, UCT_IFACE_FLAG_EP_CHECK, title,
+                                  ucp_wireup_iface_flags, reason, max);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/wireup/select.c:245]: > does it mean that every transport we select must support keepalive or ep_check?

if KA is enabled (now it is by default) and error handling requested, every selected transport has to support built-in KA or ep_check

> it means that before this PR, we could have a case where the user requested err handling mode, but keepalive may not be working because selected transport did not support?

yes, this was a case, e.g. for UD before EP_CHECK was introduced

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe ok to merge?
