### PR TITLE
UCT/IB: Apply ECE returned by ibv_query_ece by default

### LINKED ISSUE #11252: mlx5: ZTR-RTT CC is not enabled by default
### Describe the bug

According to `ucx_info -f`, setting `UCX_RC_VERBS_ECE=0` is supposed to use the "default ECE" settings:

```
# config Enhanced Connection Establishment to establish connection.
#   0         : Use default ECE.
#   auto      : Use maximal supported ECE.
#   otherwise : Set the ECE to the given numeric 32-bit value.
#               This value is used as best-effort and can be adjusted by
#               the transport implementation.
#
#
#
# syntax:    unsigned long: <number>, "inf", or "auto"
# inherits:  UCX_RC_ECE
#
UCX_RC_VERBS_ECE=0
```

On my mlx5 machine, Programmable Congestion Control (PCC) is enabled, and the default ECE options value is 0x30000002.(ZTR-RTT CC: see other <https://developer.nvidia.com/blog/scaling-zero-touch-roce-technology-with-round-trip-time-congestion-control/>)

```
$ sudo mlxconfig -d mlx5_0 query | grep -i DCQCN
ROCE_CC_DCQCN_COMPATIBILITY_MODE            DEVICE_DEFAULT(0)
ROCE_CC_LEGACY_DCQCN_SW                     False(0)
ROCE_CC_LEGACY_DCQCN                        False(0)
```

However, ZTR-RTT CC is not enabled by default. When I ran the following command, no ZTR-RTT CC packets (VENDOR SPECIFIC) were found in the traffic capture.
```
$ UCX_IB_MLX5_DEVX=no UCX_NET_DEVICES=mlx5_0:1 ./install-debug/bin/ucx_perftest  -s 33179419
$ UCX_IB_MLX5_DEVX=no UCX_NET_DEVICES=mlx5_0:1  ./install-debug/bin/ucx_perftest -s 33179419  -t ucp_am_lat 172.1.1.66

$ tshark -r dump.pcap | grep VENDOR
(none)
```

### Observations
By tracing ibv_query_ece and ibv_set_ece using bpftrace, I confirmed that the hardware's preferred options value is indeed 0x30000002:

```
$ sudo bpftrace -e 'uprobe:/usr/lib64/libibverbs.so.1:ibv_query_ece {
    @qqp_num = *(uint32*)((uint8*)arg0 + 52);
    @ece_ptr = arg1
}
uretprobe:/usr/lib64/libibverbs.so.1:ibv_query_ece {
    $v_id = *(uint32*)@ece_ptr;
    $opts = *(uint32*)((uint8*)@ece_ptr + 4);
    $comp_mask = *(uint32*)((uint8*)@ece_ptr + 8);

    printf("ret ibv_query_ece PID %d: QP=%x, ECE(vendor=0x%x, opts=0x%x, comp_mask=0x%x)\n", pid, @qqp_num, $v_id, $opts, $comp_mask);
}
uprobe:/usr/lib64/libibverbs.so.1:ibv_set_ece {
    $qp_num = *(uint32*)((uint8*)arg0 + 52);
    $v_id = *(uint32*)arg1;
    $opts = *(uint32*)((uint8*)arg1 + 4);
    $comp_mask = *(uint32*)((uint8*)arg1 + 8);

    printf("ibv_set_ece PID %d: QP=%x, ECE(vendor=0x%x, opts=0x%x, comp_mask=0x%x)\n", pid, $qp_num, $v_id, $opts, $comp_mask);
}
'
Attaching 3 probes...
ret ibv_query_ece PID 1467464: QP=466, ECE(vendor=0x15b3, opts=0x30000002, comp_mask=0x0)
ibv_set_ece PID 1467464: QP=466, ECE(vendor=0x15b3, opts=0x30000002, comp_mask=0x0)
ret ibv_query_ece PID 1467464: QP=2dd, ECE(vendor=0x15b3, opts=0x30000002, comp_mask=0x0)
ibv_set_ece PID 1467464: QP=2dd, ECE(vendor=0x15b3, opts=0x30000002, comp_mask=0x0)
^C
```

When I explicitly set UCX_RC_ECE to 0x30000002, ZTR-RTT CC becomes active, and VENDOR SPECIFIC packets appear in the capture.

```
$ UCX_RC_ECE=$(printf "%d" 0x30000002)  UCX_IB_MLX5_DEVX=no UCX_NET_DEVICES=mlx5_0:1  ./install-debug/bin/ucx_perftest -s 33179419  -t ucp_am_lat 172.1.1.66
$ UCX_RC_ECE=$(printf "%d" 0x30000002) UCX_IB_MLX5_DEVX=no UCX_NET_DEVICES=mlx5_0:1 ./install-debug/bin/ucx_perftest  -s 33179419
$ tshark -r dump.pcap | grep VENDOR | head
  722   0.000361   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
  778   0.000386   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
 1546   0.000783   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
 1562   0.000792   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
 1876   0.000948   172.1.1.66 → 172.1.1.55   RRoCE 130 VENDOR (Unknown Attribute)
 2367   0.001172   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
 2513   0.001233   172.1.1.66 → 172.1.1.55   RRoCE 130 VENDOR (Unknown Attribute)
 2516   0.001887   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
 2517   0.001887   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
 2519   0.001887   172.1.1.66 → 172.1.1.55   RRoCE 130 VENDOR (Unknown Attribute)
```
Based on these observations, it seems possible that mlx5 requires an explicit ibv_set_ece call with the preferred values to activate ECE, rather than relying on the implicit default behavior.

### Proposed Approach

I found that ZTR-RTT CC becomes functional when ibv_set_ece is explicitly called with the default options retrieved from ibv_query_ece, as shown in the diff below.

Does it seem reasonable to ensure ibv_set_ece is always called with the queried values, even when ece_val is set to DEFAULT? I would appreciate your feedback on whether this is the appropriate way to handle ECE initialization on mlx5 devices.

```c
diff --git a/src/uct/ib/base/ib_device.c b/src/uct/ib/base/ib_device.c
index e01e0712f..51c58624b 100644
--- a/src/uct/ib/base/ib_device.c
+++ b/src/uct/ib/base/ib_device.c
@@ -853,9 +853,11 @@ uct_ib_device_set_ece(uct_ib_device_t *dev, struct ibv_qp *qp, uint32_t ece_val)
     struct ibv_ece ece;
 #endif

+#if !HAVE_DECL_IBV_SET_ECE
     if (ece_val == UCT_IB_DEVICE_ECE_DEFAULT) {
         return UCS_OK;
     }
+#endif

     ucs_assertv_always(md->ece_enable, "device=%s, ece=0x%x",
                        uct_ib_device_name(dev), ece_val);
@@ -867,7 +869,11 @@ uct_ib_device_set_ece(uct_ib_device_t *dev, struct ibv_qp *qp, uint32_t ece_val)
         return UCS_ERR_IO_ERROR;
     }

-    ece.options = ece_val;
+    if (ece_val != UCT_IB_DEVICE_ECE_DEFAULT) {
+        ece.options = ece_val;
+    }
+
+
     if (ibv_set_ece(qp, &ece)) {
         ucs_error("ibv_set_ece(device=%s qpn=0x%x) failed: %m",
                   uct_ib_device_name(dev), qp->qp_num);
```

```
$  UCX_IB_MLX5_DEVX=no UCX_NET_DEVICES=mlx5_0:1  ./install-debug/bin/ucx_perftest -s 33179419  -t ucp_am_lat 172.1.1.66
$ UCX_IB_MLX5_DEVX=no UCX_NET_DEVICES=mlx5_0:1 ./install-debug/bin/ucx_perftest  -s 33179419
$ tshark -r dump.pcap | grep VENDOR  | head
    1   0.000000   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
    8   0.000016   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
   13   0.000021   172.1.1.66 → 172.1.1.55   RRoCE 130 VENDOR (Unknown Attribute)
  165   0.000113   172.1.1.66 → 172.1.1.55   RRoCE 130 VENDOR (Unknown Attribute)
 1371   0.000695   172.1.1.55 → 172.1.1.66   RRoCE 130 VENDOR (Unknown Attribute)
 1372   0.000695   172.1.1.66 → 172.1.1.55   RRoCE 130 VENDOR (Unknown Attribute)
 1562   0.000777   172.1.1.66 → 172.1.1.55   RRoCE 130 VENDOR (Unknown Attribute)
 2935   0.001379   172.1.1.66 → 172.1.1.55   RRoCE 130 VENDOR (Unknown Attribute)
 3120   0.001459   172.1.1.66 → 172.1.1.55   RRoCE 130 VENDOR (Unknown Attribute)

```

### Setup and versions
- ucx version: 48952dcc17d04c3aaad7c0db1d2e0ba850d8dc02
- OS version: x86_64
   - Rockylinux 8.6
   - 4.18.0-372.32.1.el8_6.x86_64
   - doca-ofed-3.2.1-044000.x86_64
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - rdma-core-2510.0.11-1.el8.x86_64
        - libibverbs-2510.0.11-1.el8.x86_64
        - OFED-internal-25.10-1.7.1

### Additional Context / Related Issue

Note that when UCX_RC_ECE is set to auto, ZTR-RTT CC also fails to work. I observed that after ibv_set_ece is executed with auto parameters, a subsequent ibv_query_ece shows that the options have been reset to 0. 

```
$ UCX_RC_ECE=auto UCX_IB_MLX5_DEVX=no UCX_NET_DEVICES=mlx5_0:1 ./install-debug/bin/ucx_perftest  -s 33179419
$ UCX_RC_ECE=auto  UCX_IB_MLX5_DEVX=no UCX_NET_DEVICES=mlx5_0:1  ./install-debug/bin/ucx_perftest -s 33179419  -t ucp_am_lat 172.1.1.66
$ tshark -r dump.pcap | grep VENDOR  | head
(none)
```

### PR DESCRIPTION
**Pull request by tvegas1**
## What?
Fix #11252.

## Why?
Apparently after ibv_query_ece state, we still need to apply with ibv_query_ece before modify to RTS, to request setting it on the QP. RDMA_CM documentation appears to be using a similar flow (https://man7.org/linux/man-pages/man3/rdma_set_local_ece.3.html).
 
## How?
Don't error on default without ibv_*_ece functions support.

### CODE REVIEW

File: src/uct/ib/base/ib_device.c [hunk 1]
```diff
@@ -851,32 +851,35 @@ uct_ib_device_set_ece(uct_ib_device_t *dev, struct ibv_qp *qp, uint32_t ece_val)
     uct_ib_md_t *md = ucs_container_of(dev, uct_ib_md_t, dev);
 #if HAVE_DECL_IBV_SET_ECE
     struct ibv_ece ece;
-#endif
 
-    if (ece_val == UCT_IB_DEVICE_ECE_DEFAULT) {
+    if ((ece_val == UCT_IB_DEVICE_ECE_DEFAULT) && !md->ece_enable) {
```
Comment (yosefe) [inline src/uct/ib/base/ib_device.c]: 1. shall we give out warning if ECE value is default but not supported? can also do it in `UCS_CLASS_INIT_FUNC(uct_rc_iface_t`
2. maybe make uct_ib_device_set_ece function of uct_rc_iface_t so it would access ece config directly?
3. maybe we change the meaning of the config param + update the doc:
 - auto -> set default ECE value
 - inf -> set maximal ECE value
 - any value (incl. 0)  -> set specific value
4. is it possible to add some unit test?

Comment (tvegas1) [reply src/uct/ib/base/ib_device.c]: fixed 1, 2, 3 and basic 4.

File: test/gtest/uct/ib/test_rc.cc [hunk 2]
```diff
@@ -6,6 +6,7 @@
 */
 
 #include "test_rc.h"
+#include <uct/ib/base/ib_device.h>
```
Comment (tvegas1) [inline test/gtest/uct/ib/test_rc.cc]: remove

File: src/uct/ib/base/ib_device.h [hunk 3]
```diff
@@ -69,7 +69,7 @@
 #define UCT_IB_DEVICE_SYSFS_GID_TYPE_FMT  UCT_IB_DEVICE_SYSFS_GID_ATTR_PFX "/types/%d"
 #define UCT_IB_DEVICE_SYSFS_GID_NDEV_FMT  UCT_IB_DEVICE_SYSFS_GID_ATTR_PFX "/ndevs/%d"
 #define UCT_IB_DEVICE_SYSFS_ROCE_TC_FMT   UCT_IB_DEVICE_SYSFS_PFX "/tc/%d/traffic_class"
-#define UCT_IB_DEVICE_ECE_DEFAULT         0x0         /* default ECE */
+#define UCT_IB_DEVICE_ECE_DEFAULT         UINT64_MAX  /* default ECE */
```
Comment (yosefe) [inline src/uct/ib/base/ib_device.h]: seems error prone that ECE_DEFAULT is a sig-extension of EXE_MAX.
maybe we should save the original configuration (self->config.ece = config->ece), except the case where the value is not AUTO and ECE not supported (in such case we keep erroring out)

File: src/uct/ib/rc/base/rc_iface.c [hunk 4]
```diff
@@ -866,20 +864,66 @@ ucs_status_t uct_rc_iface_qp_init(uct_rc_iface_t *iface, struct ibv_qp *qp)
...
+uct_rc_iface_set_ece(uct_rc_iface_t *iface, struct ibv_qp *qp)
+{
+    uint64_t ece_val     = iface->config.ece;
+#if HAVE_DECL_IBV_SET_ECE
+    uct_ib_device_t *dev = uct_ib_iface_device(&iface->super);
+    uct_ib_md_t *md      = ucs_container_of(dev, uct_ib_md_t, dev);
+    struct ibv_ece ece;
+    ucs_log_level_t log_level;
+
+    if ((ece_val == UCT_IB_DEVICE_ECE_DEFAULT) && !md->ece_enable) {
```
Comment (yosefe) [inline src/uct/ib/rc/base/rc_iface.c]: is it enough to check md->ece_enable ?

File: src/uct/ib/rc/base/rc_iface.c [hunk 5]
```diff
@@ -866,20 +864,66 @@ ucs_status_t uct_rc_iface_qp_init(uct_rc_iface_t *iface, struct ibv_qp *qp)
...
+        return UCS_ERR_IO_ERROR;
+    }
+
+    if (ece_val != UCT_IB_DEVICE_ECE_DEFAULT) {
+        ece.options = ece_val;
+    }
+
+    if (ibv_set_ece(qp, &ece)) {
+        log_level = (ece_val == UCT_IB_DEVICE_ECE_DEFAULT?
+                     UCS_LOG_LEVEL_WARN : UCS_LOG_LEVEL_ERROR);
```
Comment (yosefe) [inline src/uct/ib/rc/base/rc_iface.c]: minor: code style

Comment (yosefe) [inline src/uct/ib/rc/base/rc_iface.c]:
```suggestion
        log_level = (ece_val == UCT_IB_DEVICE_ECE_DEFAULT) ?
                     UCS_LOG_LEVEL_DIAG : UCS_LOG_LEVEL_ERROR;
```

Comment (tvegas1) [reply src/uct/ib/rc/base/rc_iface.c]: fixed

Comment (tvegas1) [reply src/uct/ib/rc/base/rc_iface.c]: probably fixed

File: src/uct/ib/rc/base/rc_iface.c (hunk 4 above)
Comment (tvegas1) [reply src/uct/ib/rc/base/rc_iface.c]: md->ece_enable means ibv_query_ece() and ibv_set_ece() sequence succeeded, so i think it is enough

File: src/uct/ib/base/ib_device.h (hunk 3 above)
Comment (tvegas1) [reply src/uct/ib/base/ib_device.h]: fixed

File: src/uct/ib/rc/base/rc_iface.c [hunk 6]
```diff
@@ -611,19 +611,15 @@ UCS_CLASS_INIT_FUNC(uct_rc_iface_t, uct_iface_ops_t *tl_ops,
 #endif
     max_ib_msg_size             = uct_ib_iface_port_attr(&self->super)->max_msg_sz;
 
-    if (config->ece == UCS_ULUNITS_AUTO) {
-        self->config.ece = UCT_IB_DEVICE_ECE_DEFAULT;
-    } else if (!md->ece_enable) {
+    if (!md->ece_enable && config->ece != UCS_ULUNITS_AUTO) {
```
Comment (yosefe) [inline src/uct/ib/rc/base/rc_iface.c]: `if (!md->ece_enable && (config->ece != UCS_ULUNITS_AUTO)) {`

File: src/uct/ib/rc/base/rc_iface.c [hunk 7]
```diff
@@ -864,21 +860,20 @@ ucs_status_t uct_rc_iface_qp_init(uct_rc_iface_t *iface, struct ibv_qp *qp)
...
-    uint64_t ece_val     = iface->config.ece;
+    unsigned long ece_val = iface->config.ece;
 #if HAVE_DECL_IBV_SET_ECE
     uct_ib_device_t *dev = uct_ib_iface_device(&iface->super);
     uct_ib_md_t *md      = ucs_container_of(dev, uct_ib_md_t, dev);
     struct ibv_ece ece;
     ucs_log_level_t log_level;
 
-    if ((ece_val == UCT_IB_DEVICE_ECE_DEFAULT) && !md->ece_enable) {
+    if ((ece_val == UCS_ULUNITS_AUTO) && !md->ece_enable) {
```
Comment (yosefe) [inline src/uct/ib/rc/base/rc_iface.c]: `if (!md->ece_enable) {`

File: src/uct/ib/rc/base/rc_iface.c [hunk 8]
```diff
@@ -864,21 +860,20 @@ ucs_status_t uct_rc_iface_qp_init(uct_rc_iface_t *iface, struct ibv_qp *qp)
...
         return UCS_OK;
     }
 
-    ucs_assertv_always(md->ece_enable, "device=%s, ece=0x%"PRIx64,
+    ucs_assertv_always(md->ece_enable, "device=%s, config_ece=0x%"PRIx64,
```
Comment (yosefe) [inline src/uct/ib/rc/base/rc_iface.c]: can remove this assertion if prev check changed to just !ece_enable

File: src/uct/ib/rc/base/rc_iface.c [hunk 9]
```diff
@@ -887,27 +882,30 @@ uct_rc_iface_set_ece(uct_rc_iface_t *iface, struct ibv_qp *qp)
...
 
-    if (ece_val != UCT_IB_DEVICE_ECE_DEFAULT) {
-        ece.options = ece_val;
+    if (ece_val != UCS_ULUNITS_AUTO) {
+        if (ece_val == UCS_ULUNITS_INF) {
+            ece.options = UCT_IB_DEVICE_ECE_MAX;
+        } else {
+            ece.options = ece_val;
+        }
     }
```
Comment (yosefe) [inline src/uct/ib/rc/base/rc_iface.c:886]:
```c
    if (ece_val == UCS_ULUNITS_INF) {
        ece.options = UCT_IB_DEVICE_ECE_MAX;
    } else if (ece_val != UCS_ULUNITS_AUTO) {
        ece.options = ece_val;
    }
```

File: src/uct/ib/rc/base/rc_iface.c [hunk 10]
```diff
@@ -887,27 +882,30 @@ uct_rc_iface_set_ece(uct_rc_iface_t *iface, struct ibv_qp *qp)
...
 
     if (ibv_set_ece(qp, &ece)) {
-        log_level = (ece_val == UCT_IB_DEVICE_ECE_DEFAULT?
-                     UCS_LOG_LEVEL_WARN : UCS_LOG_LEVEL_ERROR);
+        log_level = ((ece_val == UCS_ULUNITS_AUTO) ? UCS_LOG_LEVEL_DIAG :
+                                                     UCS_LOG_LEVEL_ERROR);
```
Comment (yosefe) [inline src/uct/ib/rc/base/rc_iface.c]: can remove the ( ) that surround the whole expression

File: src/uct/ib/rc/base/rc_iface.c (hunk 8 above)
Comment (tvegas1) [reply src/uct/ib/rc/base/rc_iface.c]: fixed

File: src/uct/ib/rc/base/rc_iface.c (hunk 7 above)
Comment (tvegas1) [reply src/uct/ib/rc/base/rc_iface.c]: fixed

File: src/uct/ib/rc/base/rc_iface.c (hunk 9 above)
Comment (tvegas1) [reply src/uct/ib/rc/base/rc_iface.c:886]: fixed

File: src/uct/ib/rc/base/rc_iface.c (hunk 10 above)
Comment (tvegas1) [reply src/uct/ib/rc/base/rc_iface.c]: fixed

File: src/uct/ib/rc/base/rc_iface.c (hunk 6 above)
Comment (tvegas1) [reply src/uct/ib/rc/base/rc_iface.c]: fixed
