### PR TITLE
UCP/RNDV: Fallback to PUT pipeline only if PUT protocol is supported

### LINKED ISSUE #6836: Rndv pipepline fails if the iface does not support put_zcopy
### Describe the bug
This issue showed up in my tests with SRD which only supports get_zcopy, and not put_zcopy. But, I can also reproduce it with RC on an IB cluster by manually removing `UCT_IFACE_FLAG_PUT_BCOPY` and `UCT_IFACE_FLAG_PUT_ZCOPY` flags in `uct_rc_iface_query`.

```
# OSU MPI Multiple Bandwidth / Message Rate Test v5.6.3
# Send Buffer on DEVICE (D) and Receive Buffer on DEVICE (D)
# [ pairs: 1 ] [ window size: 64 ]
# Size                  MB/s        Messages/s
1                       0.03          31094.26
2                       0.06          30796.78
4                       0.12          30850.47
8                       0.25          30934.21
16                      0.49          30926.95
32                      0.99          30863.00
64                      1.87          29231.43
128                     3.89          30379.40
256                     7.90          30872.14
512                    15.77          30796.30
1024                   31.00          30273.87
2048                   62.42          30477.93
4096                  122.95          30017.96
8192                  241.39          29466.10
16384                 323.60          19750.98
rndv.c:1991 Assertion `!(rreq->flags & UCP_REQUEST_FLAG_RNDV_FRAG)' failed
```
As far as I could figure out, a received rndv data _can_ correspond to a frag RTR, so I'm not sure why we have that assertion. However, removing it resulted in further assertion failures. For instance, after applying the following changes
```
diff --git a/src/ucp/rndv/rndv.c b/src/ucp/rndv/rndv.c
index 84aacc12d..e3a59be42 100644
--- a/src/ucp/rndv/rndv.c
+++ b/src/ucp/rndv/rndv.c
@@ -1156,7 +1156,7 @@ static void ucp_rndv_send_frag_rtr(ucp_worker_h worker, ucp_request_t *rndv_req,
         freq->recv.length                 = frag_size;
         freq->recv.state.dt.contig.md_map = 0;
         freq->recv.frag.offset            = offset;
-        freq->flags                       = UCP_REQUEST_FLAG_RNDV_FRAG;
+        freq->flags                       = UCP_REQUEST_FLAG_RNDV_FRAG | UCP_REQUEST_FLAG_RECV_TAG;

         ucp_request_set_super(freq, rreq);

@@ -1988,7 +1988,6 @@ UCS_PROFILE_FUNC(ucs_status_t, ucp_rndv_data_handler,

     rreq = ucp_request_get_super(rndv_req);
     ucs_assert(rreq != NULL);
-    ucs_assert(!(rreq->flags & UCP_REQUEST_FLAG_RNDV_FRAG));
     ucs_assert(rreq->flags &
                (UCP_REQUEST_FLAG_RECV_AM | UCP_REQUEST_FLAG_RECV_TAG));
```
I got to the failure below:
```
ucp_request.inl:747  Assertion `req->recv.remaining >= length' failed: req->recv.remaining=0 length=8238
```

### Steps to Reproduce
- `mpirun -n 2 --hostfile ~/hostfile --mca pml ucx --mca opal_common_ucx_tls any --mca opal_common_ucx_devices any -x UCX_TLS=rc,cuda_copy,cuda_ipc,self -x UCX_IB_GPU_DIRECT_RDMA=n ./osu_mbw_mr D D`
- `UCT version=1.11.0 revision 2175333`

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fallback to PUT pipeline only if PUT protocol is supported. 

## Why ?

Fixes #6836.

## How ?

When is going to fallback to PUT pipeline protocol, check PUT Zcopy support assuming symmetric configuration of sender and receiver, i.e. check that the length of the message is:
- greater than minimum PUT Zcopy
- maximum PUT Zcopy isn't `0`

### CODE REVIEW

**Comment by dmitrygx** [comment]
@bureddy

**Comment by dmitrygx** [comment]
@Akshay-Venkatesh @bureddy @SeyedMir could you review pls?

File: test/gtest/ucp/test_ucp_am.cc [hunk 1]
```diff
@@ -1267,3 +1267,41 @@ UCS_TEST_P(test_ucp_am_nbx_rndv_memtype, rndv)
...
+}
+
+UCS_TEST_P(test_ucp_am_nbx_rndv_memtype_disable_zcopy, rndv_disable_get_zcopy)
+{
+    disable_rndv_zcopy_config(sender(), UCT_IFACE_FLAG_GET_ZCOPY);
+    disable_rndv_zcopy_config(receiver(), UCT_IFACE_FLAG_GET_ZCOPY);
+
+    ucs_memory_type_t mt = static_cast<ucs_memory_type_t>(get_variant_value(0));
+    test_am_send_recv(64 * UCS_KBYTE, 8, 0, mt);
+}
```
Comment (brminich) [inline test/gtest/ucp/test_ucp_am.cc:1305]: can define a common function for these tests with caps parameter

File: src/ucp/rndv/rndv.c [hunk 2]
```diff
@@ -1401,34 +1450,33 @@ UCS_PROFILE_FUNC_VOID(ucp_rndv_receive, (worker, rreq, rndv_rts_hdr, rkey_buf),
...
+            put_zcopy = &ep_config->rndv.put_zcopy;
+            ucp_rndv_recv_data_init(rreq, rndv_rts_hdr->size);
+            if (ucp_rndv_is_put_pipeline_needed(rndv_rts_hdr->address,
+                                                rndv_rts_hdr->size, get_zcopy,
+                                                put_zcopy,
+                                                is_get_zcopy_failed)) {
+                /* send FRAG RTR for sender to PUT the fragment. */
+                ucp_rndv_send_frag_rtr(worker, rndv_req, rreq, rndv_rts_hdr);
                 goto out;
+            } else if (is_get_zcopy_supported) {
```
Comment (brminich) [inline src/ucp/rndv/rndv.c:1472]: isn't presence of remote addr in RTS already saying that get zcopy is supported?

File: src/ucp/rndv/rndv.c [hunk 3]
```diff
@@ -1091,6 +1122,12 @@ ucp_rndv_recv_start_get_pipeline(ucp_worker_h worker, ucp_request_t *rndv_req,
     ucp_rndv_req_init_zcopy_lane_map(rndv_req, rndv_req->send.mem_type,
                                      UCP_REQUEST_SEND_PROTO_RNDV_GET);
 
+    lane = ucp_rndv_zcopy_get_lane(rndv_req, &uct_rkey,
+                                    UCP_REQUEST_SEND_PROTO_RNDV_GET);
+    if (lane == UCP_NULL_LANE) {
+        goto err;
+    }
```
Comment (brminich) [inline src/ucp/rndv/rndv.c:1129]: when can it be NULL?

File: src/ucp/rndv/rndv.c [hunk 4]
```diff
@@ -544,33 +547,51 @@ ucp_rndv_progress_rma_zcopy_common(ucp_request_t *req, ucp_lane_index_t lane,
...
 
+    rndv_req = ucp_rndv_rma_get_zcopy_req(req);
+
     /* Figure out which lane to use for get operation */
-    rndv_req->send.lane =
-        ucp_rndv_zcopy_get_lane(rndv_req, &uct_rkey,
-                                UCP_REQUEST_SEND_PROTO_RNDV_GET);
-    if (rndv_req->send.lane != UCP_NULL_LANE) {
+    req->send.lane =
+            ucp_rndv_zcopy_get_lane(req, &uct_rkey,
```
Comment (brminich) [inline src/ucp/rndv/rndv.c:564]: minor: looks like it can fir single line now

File: src/ucp/rndv/rndv.c [hunk 5]
```diff
@@ -544,33 +547,51 @@ ucp_rndv_progress_rma_zcopy_common(ucp_request_t *req, ucp_lane_index_t lane,
...
     /* Remove statistics related to get_zcopy */
-    UCP_WORKER_STAT_RNDV(rndv_req->send.ep->worker, GET_ZCOPY, -1);
+    UCP_WORKER_STAT_RNDV(req->send.ep->worker, GET_ZCOPY, -1);
+
+    if (req != rndv_req) {
+        /* If GET Zcopy operation was issued as a part of fragmented protocol,
+         * release the fragmented request which is no longer needed */
+        ucs_mpool_put_inline((void*)req->send.mdesc);
+        ucp_request_put(req);
+    }
```
Comment (brminich) [inline src/ucp/rndv/rndv.c:589]: it's not supposed to be supported for fragmented protocols at all, is it? Maybe better assert here then

File: src/ucp/rndv/rndv.c (hunk 4 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:564]: unfortunately, no
the last argument `UCP_REQUEST_SEND_PROTO_RNDV_GET` breaks the 80 symbols per line rule

File: src/ucp/rndv/rndv.c (hunk 5 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:589]: > it's not supposed to be supported for fragmented protocols at all, is it?

it is supported by GET pipeline and GET protocols.
only PUT pipeline doesn't support it when doing GET GPU->HOST memory copy

File: src/ucp/rndv/rndv.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:1129]: like in normal GET Zcopy, it can be NULL if not able to select GET protocol due to RKEY
I had a reproducer for this. So, it was fixed in the same as in GET

File: src/ucp/rndv/rndv.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:1472]: it says that sender allows us to use GET Zcopy.
but we need to check local min/max of GET Zcopy to make sure GET Zcopy RNDV is supported by TLs

File: test/gtest/ucp/test_ucp_am.cc (hunk 1 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_am.cc]: done

File: src/ucp/rndv/rndv.c (hunk 4 above)
Comment (brminich) [reply src/ucp/rndv/rndv.c:564]: i meant
```
req->send.lane = ucp_rndv_zcopy_get_lane(req, &uct_rkey,
                                         UCP_REQUEST_SEND_PROTO_RNDV_GET);
```
anyway it's minor comment

File: src/ucp/rndv/rndv.c (hunk 5 above)
Comment (brminich) [reply src/ucp/rndv/rndv.c:589]: are you sure AM rndv flow is supported for fragmented protos?

File: src/ucp/rndv/rndv.c (hunk 3 above)
Comment (brminich) [reply src/ucp/rndv/rndv.c:1129]: what is the reproducer?

File: src/ucp/rndv/rndv.c (hunk 2 above)
Comment (brminich) [reply src/ucp/rndv/rndv.c:1472]: then should we set `is_get_zcopy_failed` to true if we do not get into this `else if`? Because we do not register recv buffer for AM flow

Comment (bureddy) [reply src/ucp/rndv/rndv.c:1472]: @dmitrygx shouldn't above check if (!is_get_zcopy_failed) ?
because is_get_zcopy_supported might be true but is_get_zcopy_failed is false because GDR not available at receiver?

File: src/ucp/rndv/rndv.c [hunk 6]
```diff
@@ -544,33 +547,51 @@ ucp_rndv_progress_rma_zcopy_common(ucp_request_t *req, ucp_lane_index_t lane,
...
 
+static UCS_F_ALWAYS_INLINE ucp_request_t*
+ucp_rndv_rma_get_zcopy_req(ucp_request_t *req);
+
 UCS_PROFILE_FUNC(ucs_status_t, ucp_rndv_progress_rma_get_zcopy, (self),
                  uct_pending_req_t *self)
 {
-    ucp_request_t *rndv_req = ucs_container_of(self, ucp_request_t, send.uct);
+    ucp_request_t *req = ucs_container_of(self, ucp_request_t, send.uct);
+    ucp_request_t *rndv_req;
```
Comment (bureddy) [inline src/ucp/rndv/rndv.c:557]: is changes in this func related to the reported issue (or) covering some other issue?

Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:557]: yes, it fixes issue appeared after fixing the original one.
normal GET Zcopy fallbacks to pipeline GET Zcopy, but it couldn't be done too, so it should send RTR. But need to correctly release all things allocated for GET.

File: src/ucp/rndv/rndv.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:1472]: > @dmitrygx shouldn't above check if (!is_get_zcopy_failed) ?

I tried it, but it disables pipeline GET Zcopy then.
since we do GET Zcopy first and if it fails (e.g. GDR is not available)m it sets `is_get_zcopy_failed` to `true` and then we should fallback to pipeline GET protocol.

> because is_get_zcopy_supported might be true but is_get_zcopy_failed is false because GDR not available at receiver?

yes, this check aims it. `is_get_zcopy_supported` should be `true` and since we get here it guarantees that `is_get_zcopy_failed` is `true`.

File: src/ucp/rndv/rndv.c (hunk 6 above)
Comment (bureddy) [reply src/ucp/rndv/rndv.c:557]: when is the pipeline GET ZCOPY can fail? it does GET on HOST memory which should always be a success with both IB and TCP.   is it because you explicitly force disabled UCT_IFACE_FLAG_GET_ZCOPY in the gtest?

Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:557]: > when is the pipeline GET ZCOPY can fail? it does GET on HOST memory which should always be a success with both IB and TCP. is it because you explicitly force disabled UCT_IFACE_FLAG_GET_ZCOPY in the gtest?

yes, when there is no `UCT_IFACE_FLAG_GET_ZCOPY` capability on transports.

Comment (bureddy) [reply src/ucp/rndv/rndv.c:557]: in that case,  isn't '`"is_get_zcopy_supported`" is false and `ucp_rndv_recv_start_get_pipeline`  is not called?

Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:557]: > in that case, isn't '`"is_get_zcopy_supported`" is false and `ucp_rndv_recv_start_get_pipeline` is not called?,

if `is_get_zcopy_supported` - `false`, then `ucp_rndv_recv_start_get_pipeline` is not called, since GET operation can't be done

Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:557]: @bureddy the changes is needed to release resources (mdesc, request) for fragmented GET protocol if it couldn't be used by some reason (i.e. `ucp_rndv_zcopy_get_lane()` returns `UCP_NULL_LANE`).

**Review by bureddy — APPROVED** [review]

**Comment by dmitrygx** [comment]
@brminich @yosefe could you review pls when you have time?

File: src/ucp/rndv/rndv.c [hunk 7]
```diff
@@ -816,16 +837,22 @@ static ucs_status_t ucp_rndv_req_send_rma_get(ucp_request_t *rndv_req,
                                      UCP_REQUEST_SEND_PROTO_RNDV_GET);
 
     rndv_req->send.lane =
-        ucp_rndv_zcopy_get_lane(rndv_req, &uct_rkey,
-                                UCP_REQUEST_SEND_PROTO_RNDV_GET);
+            ucp_rndv_zcopy_get_lane(rndv_req, &uct_rkey,
+                                    UCP_REQUEST_SEND_PROTO_RNDV_GET);
```
Comment (brminich) [inline src/ucp/rndv/rndv.c:841]: no need to change

File: src/ucp/rndv/rndv.c [hunk 8]
```diff
@@ -1091,6 +1122,12 @@ ucp_rndv_recv_start_get_pipeline(ucp_worker_h worker, ucp_request_t *rndv_req,
     ucp_rndv_req_init_zcopy_lane_map(rndv_req, rndv_req->send.mem_type,
                                      UCP_REQUEST_SEND_PROTO_RNDV_GET);
 
+    lane = ucp_rndv_zcopy_get_lane(rndv_req, &uct_rkey,
+                                    UCP_REQUEST_SEND_PROTO_RNDV_GET);
```
Comment (brminich) [inline src/ucp/rndv/rndv.c:1126]: alignment

File: src/ucp/rndv/rndv.c [hunk 9]
```diff
@@ -1355,11 +1400,12 @@ UCS_PROFILE_FUNC_VOID(ucp_rndv_receive, (worker, rreq, rndv_rts_hdr, rkey_buf),
         goto err;
```
Comment (brminich) [inline src/ucp/rndv/rndv.c:1400]: btw, this is incorrect `goto`, we have to do UNBLOCK as well

File: test/gtest/ucp/test_ucp_am.cc [hunk 10]
```diff
@@ -1267,3 +1267,42 @@ UCS_TEST_P(test_ucp_am_nbx_rndv_memtype, rndv)
...
+};
+
+UCS_TEST_P(test_ucp_am_nbx_rndv_memtype_disable_zcopy, rndv_disable_put_zcopy)
+{
+    test_disabled_rndv_zcopy(UCT_IFACE_FLAG_PUT_ZCOPY);
+}
+
+UCS_TEST_P(test_ucp_am_nbx_rndv_memtype_disable_zcopy, rndv_disable_get_zcopy)
+{
+    test_disabled_rndv_zcopy(UCT_IFACE_FLAG_PUT_ZCOPY);
```
Comment (brminich) [inline test/gtest/ucp/test_ucp_am.cc:1305]: `UCT_IFACE_FLAG_GET_ZCOPY`

File: test/gtest/ucp/test_ucp_am.cc [hunk 11]
```diff
@@ -1267,3 +1267,42 @@ UCS_TEST_P(test_ucp_am_nbx_rndv_memtype, rndv)
...
+    void disable_rndv_zcopy_config(entity &e, uint64_t zcopy_caps)
+    {
+        ucp_ep_h ep             = e.ep();
+        ucp_ep_config_t *config = ucp_ep_config(ep);
+
+        if (zcopy_caps == UCT_IFACE_FLAG_PUT_ZCOPY) {
+            ucp_ep_config_rndv_zcopy_commit(0, &config->rndv.put_zcopy);
+        } else {
+            ASSERT_TRUE(zcopy_caps == UCT_IFACE_FLAG_GET_ZCOPY);
+            ucp_ep_config_rndv_zcopy_commit(0, &config->rndv.get_zcopy);
```
Comment (brminich) [inline test/gtest/ucp/test_ucp_am.cc:1284]: what use case does it represent? We already run it on various transports, so what is emulated by hacking caps?

File: src/ucp/rndv/rndv.c (hunk 7 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:841]: rolled back

File: src/ucp/rndv/rndv.c (hunk 8 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:1126]: fixed

File: src/ucp/rndv/rndv.c (hunk 9 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:1400]: it goes to `err` and then to `out` from `err`:
https://github.com/openucx/ucx/blob/b7f8cc2dce80fd654356fbec527d957f0fedd520/src/ucp/rndv/rndv.c#L1449

File: test/gtest/ucp/test_ucp_am.cc (hunk 11 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_am.cc:1284]: we are emulating that either GET Zcopy or PUT Zcopy isn't supported by the transport.
the idea is to check how pipeline and normal RNDV will handle it.

File: test/gtest/ucp/test_ucp_am.cc (hunk 10 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_am.cc:1305]: nice catch, fixed

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by dmitrygx** [comment]
@brminich is it ok now?

**Review by brminich — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

File: src/ucp/rndv/rndv.c [hunk 12]
```diff
@@ -83,15 +83,18 @@ static int ucp_rndv_is_recv_pipeline_needed(ucp_request_t *rndv_req,
...
 }
 
-static int ucp_rndv_is_put_pipeline_needed(uintptr_t remote_address,
-                                           size_t length, size_t min_get_zcopy,
-                                           size_t max_get_zcopy,
-                                           int is_get_zcopy_failed)
+static int
+ucp_rndv_is_put_pipeline_needed(uintptr_t remote_address, size_t length,
+                                ucp_ep_rndv_zcopy_config_t *get_zcopy,
+                                ucp_ep_rndv_zcopy_config_t *put_zcopy,
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:89]: 1. const* for put/get zcopy
2. make it UCS_F_ALWAYS_INLINE?

File: src/ucp/rndv/rndv.c [hunk 13]
```diff
@@ -544,33 +547,51 @@ ucp_rndv_progress_rma_zcopy_common(ucp_request_t *req, ucp_lane_index_t lane,
     }
 }
 
+static UCS_F_ALWAYS_INLINE ucp_request_t*
+ucp_rndv_rma_get_zcopy_req(ucp_request_t *req);
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:551]: maybe move the function body here?

File: src/ucp/rndv/rndv.c [hunk 14]
```diff
@@ -544,33 +547,51 @@ ucp_rndv_progress_rma_zcopy_common(ucp_request_t *req, ucp_lane_index_t lane,
...
+
 UCS_PROFILE_FUNC(ucs_status_t, ucp_rndv_progress_rma_get_zcopy, (self),
                  uct_pending_req_t *self)
 {
-    ucp_request_t *rndv_req = ucs_container_of(self, ucp_request_t, send.uct);
+    ucp_request_t *req = ucs_container_of(self, ucp_request_t, send.uct);
+    ucp_request_t *rndv_req;
     uct_rkey_t uct_rkey;
 
+    rndv_req = ucp_rndv_rma_get_zcopy_req(req);
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:560]: init inline

File: src/ucp/rndv/rndv.c [hunk 15]
```diff
@@ -544,33 +547,51 @@ ucp_rndv_progress_rma_zcopy_common(ucp_request_t *req, ucp_lane_index_t lane,
...
      * NOTE: we do not register memory and do not send our keys. */
     ucp_trace_req(rndv_req, "remote memory unreachable, switch to rtr");
     ucp_rkey_destroy(rndv_req->send.rndv.rkey);
     ucp_rndv_recv_data_init(ucp_request_get_super(rndv_req),
                             rndv_req->send.length);
     /* Remove statistics related to get_zcopy */
-    UCP_WORKER_STAT_RNDV(rndv_req->send.ep->worker, GET_ZCOPY, -1);
+    UCP_WORKER_STAT_RNDV(req->send.ep->worker, GET_ZCOPY, -1);
+
+    if (req != rndv_req) {
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:584]: can we check FRAG flag instead?

File: src/ucp/rndv/rndv.c [hunk 16]
```diff
@@ -1816,6 +1866,29 @@ static ucs_status_t ucp_rndv_send_start_put_pipeline(ucp_request_t *sreq,
     return UCS_OK;
 }
 
+static UCS_F_ALWAYS_INLINE ucp_request_t*
+ucp_rndv_rma_get_zcopy_req(ucp_request_t *req)
+{
+    ucp_request_t *rndv_req;
+
+    if (req->send.state.uct_comp.func == ucp_rndv_recv_frag_get_completion) {
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:1874]: can we check FRAG flag instead?

File: src/ucp/rndv/rndv.c [hunk 17]
```diff
@@ -544,33 +547,51 @@ ucp_rndv_progress_rma_zcopy_common(ucp_request_t *req, ucp_lane_index_t lane,
...
                             rndv_req->send.length);
     /* Remove statistics related to get_zcopy */
-    UCP_WORKER_STAT_RNDV(rndv_req->send.ep->worker, GET_ZCOPY, -1);
+    UCP_WORKER_STAT_RNDV(req->send.ep->worker, GET_ZCOPY, -1);
+
+    if (req != rndv_req) {
+        /* If GET Zcopy operation was issued as a part of fragmented protocol,
+         * release the fragmented request which is no longer needed */
+        ucs_mpool_put_inline((void*)req->send.mdesc);
+        ucp_request_put(req);
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:588]: can we share code with get-frag completion?

File: src/ucp/rndv/rndv.c [hunk 18]
```diff
@@ -544,33 +547,51 @@ ucp_rndv_progress_rma_zcopy_common(ucp_request_t *req, ucp_lane_index_t lane,
...
     ucp_trace_req(rndv_req, "remote memory unreachable, switch to rtr");
     ucp_rkey_destroy(rndv_req->send.rndv.rkey);
     ucp_rndv_recv_data_init(ucp_request_get_super(rndv_req),
                             rndv_req->send.length);
     /* Remove statistics related to get_zcopy */
-    UCP_WORKER_STAT_RNDV(rndv_req->send.ep->worker, GET_ZCOPY, -1);
+    UCP_WORKER_STAT_RNDV(req->send.ep->worker, GET_ZCOPY, -1);
+
+    if (req != rndv_req) {
+        /* If GET Zcopy operation was issued as a part of fragmented protocol,
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:585]: shall we update the comment in line 575-576?

File: src/ucp/rndv/rndv.c [hunk 19]
```diff
@@ -819,13 +840,19 @@ static ucs_status_t ucp_rndv_req_send_rma_get(ucp_request_t *rndv_req,
...
 
     UCP_WORKER_STAT_RNDV(ep->worker, GET_ZCOPY, 1);
     ucp_request_send(rndv_req, 0);
 
     return UCS_OK;
+
+err:
+    ucp_request_reset_super(rndv_req);
+    ucp_rkey_destroy(rndv_req->send.rndv.rkey);
+
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:854]: remove spaceline

File: src/ucp/rndv/rndv.c [hunk 20]
```diff
@@ -544,33 +547,51 @@ ucp_rndv_progress_rma_zcopy_common(ucp_request_t *req, ucp_lane_index_t lane,
...
     /* Figure out which lane to use for get operation */
-    rndv_req->send.lane =
-        ucp_rndv_zcopy_get_lane(rndv_req, &uct_rkey,
-                                UCP_REQUEST_SEND_PROTO_RNDV_GET);
-    if (rndv_req->send.lane != UCP_NULL_LANE) {
+    req->send.lane =
+            ucp_rndv_zcopy_get_lane(req, &uct_rkey,
+                                    UCP_REQUEST_SEND_PROTO_RNDV_GET);
+    if (req->send.lane != UCP_NULL_LANE) {
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:566]: don't we check the same thing in line 821?

File: src/ucp/rndv/rndv.c [hunk 21]
```diff
@@ -1091,6 +1122,12 @@ ucp_rndv_recv_start_get_pipeline(ucp_worker_h worker, ucp_request_t *rndv_req,
     ucp_rndv_req_init_zcopy_lane_map(rndv_req, rndv_req->send.mem_type,
                                      UCP_REQUEST_SEND_PROTO_RNDV_GET);
 
+    lane = ucp_rndv_zcopy_get_lane(rndv_req, &uct_rkey,
+                                   UCP_REQUEST_SEND_PROTO_RNDV_GET);
+    if (lane == UCP_NULL_LANE) {
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:1127]: Don't we already check it inside ucp_rndv_progress_rma_get_zcopy, called from progress, as set by ucp_rndv_send_frag_get_mem_type in line 1137?
We can check if lanes are valid inside ucp_rndv_progress_rma_get_zcopy, or before it, but why need both?

File: src/ucp/rndv/rndv.c [hunk 22]
```diff
@@ -1109,6 +1146,12 @@ ucp_rndv_recv_start_get_pipeline(ucp_worker_h worker, ucp_request_t *rndv_req,
     }
 
     return UCS_OK;
+
+err:
+    ucp_request_reset_super(rndv_req);
+    ucp_rkey_destroy(rndv_req->send.rndv.rkey);
+
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:1153]: remove space line

File: src/ucp/rndv/rndv.c [hunk 23]
```diff
@@ -1890,9 +1964,14 @@ UCS_PROFILE_FUNC(ucs_status_t, ucp_rndv_rtr_handler,
                       ucp_ep_peer_name(ep), ucs_status_string(status));
         }
 
+        is_put_supported = ucp_rndv_test_zcopy_scheme_support(sreq->send.length,
+                                                              put_zcopy->min,
+                                                              put_zcopy->max,
+                                                              put_zcopy->split);
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:1970]: maybe pass "put_zcopy" to ucp_rndv_test_zcopy_scheme_support?

File: src/ucp/rndv/rndv.c [hunk 24]
```diff
@@ -1890,9 +1964,14 @@ UCS_PROFILE_FUNC(ucs_status_t, ucp_rndv_rtr_handler,
...
         is_pipeline_rndv = ((!UCP_MEM_IS_HOST(sreq->send.mem_type) ||
                              (sreq->send.length != rndv_rtr_hdr->size)) &&
-                            (context->config.ext.rndv_mode != UCP_RNDV_MODE_PUT_ZCOPY));
+                            (context->config.ext.rndv_mode != UCP_RNDV_MODE_PUT_ZCOPY)) &&
+                           is_put_supported;
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:1974]: rename is_pipeline_rndv to is_put_pipeline

File: test/gtest/ucp/test_ucp_am.cc [hunk 25]
```diff
@@ -1267,3 +1267,42 @@ UCS_TEST_P(test_ucp_am_nbx_rndv_memtype, rndv)
...
+
+class test_ucp_am_nbx_rndv_memtype_disable_zcopy :
+        public test_ucp_am_nbx_rndv_memtype {
+protected:
+    void disable_rndv_zcopy_config(entity &e, uint64_t zcopy_caps)
+    {
+        ucp_ep_h ep             = e.ep();
+        ucp_ep_config_t *config = ucp_ep_config(ep);
+
+        if (zcopy_caps == UCT_IFACE_FLAG_PUT_ZCOPY) {
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_am.cc:1280]: if (zcopy_caps & PUT) { disable put }
if (zcopy_caps & GET) { disable get }
...
test (disable put)
test (disable get)
test (disable put | disable get)

File: src/ucp/rndv/rndv.c (hunk 17 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c]: unfortunately, no.
it could not be shared with put completion that's called in the end of GET fragmented

File: src/ucp/rndv/rndv.c (hunk 16 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:1822]: unfortunately, we don't set FRAG for GET Zcopy

File: src/ucp/rndv/rndv.c (hunk 21 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:1078]: removed it from `ucp_rndv_progress_rma_get_zcopy()` - just added assertion to check that it is called when there are lanes to do GET Zcopy.

File: src/ucp/rndv/rndv.c (hunk 20 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c]: removed from here

File: src/ucp/rndv/rndv.c (hunk 21 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c:1078]: upd: unfortunately, i found out that we still need this code to get GET Zcopy lane to get correct UCT rkey.
but it `if (lane != UCP_NULL_LANE)` replaced with assertion

**Comment by dmitrygx** [comment]
@yosefe could you review pls again?
the failure isn't related, it is docker issue

File: src/ucp/core/ucp_ep.h [hunk 26]
```diff
@@ -633,9 +633,14 @@ unsigned ucp_ep_local_disconnect_progress(void *arg);
 
 size_t ucp_ep_tag_offload_min_rndv_thresh(ucp_ep_config_t *config);
 
+
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.h:636]: why added?

File: src/ucp/rndv/rndv.c [hunk 27]
```diff
@@ -1808,6 +1806,43 @@ static ucs_status_t ucp_rndv_send_start_put_pipeline(ucp_request_t *sreq,
     return UCS_OK;
 }
 
+static UCS_F_ALWAYS_INLINE ucp_request_t*
+ucp_rndv_rma_get_zcopy_req(ucp_request_t *req)
```
Comment (yosefe) [inline src/ucp/rndv/rndv.c:1810]: is this function still needed?

File: src/ucp/core/ucp_ep.h (hunk 26 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.h]: merge conflict issue
removed

File: src/ucp/rndv/rndv.c (hunk 27 above)
Comment (dmitrygx) [reply src/ucp/rndv/rndv.c]: good catch, the function is not needed anymore - removed
