### PR TITLE
UCP/WIREUP: Don't discard CM lane

### LINKED ISSUE #5875: all/test_ucp_sockaddr.concurrent_disconnect/6 corruption
```
[ RUN      ] all/test_ucp_sockaddr.concurrent_disconnect/6 <all/stream,cm>
[     INFO ] Testing 10.224.36.98:0
[     INFO ] < rdma_bind_addr(addr=10.224.36.98:0) failed: No such device >
[     INFO ] server listening on 10.224.36.98:37132
[swx-rdmz-ucx-gpu-02:31161:1:4047]   wireup_cm.c:771  Assertion `(&worker->async)->signal.tid == ucs_get_tid()' failed

/scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/ucp/wireup/wireup_cm.c: [ ucp_cm_disconnect_cb() ]
      ...
      768     uct_ep = ucp_ep_get_cm_uct_ep(ucp_ep);
      769     if (uct_ep == NULL) {
      770         UCS_ASYNC_BLOCK(&worker->async);
==>   771         discard_uct_ep = ucp_worker_is_uct_ep_discarding(worker, uct_cm_ep);
      772         UCS_ASYNC_UNBLOCK(&worker->async);
      773 
      774         if (discard_uct_ep) {

==== backtrace (tid:   4047) ====
 0 0x000000000005c098 ucs_debug_print_backtrace()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/ucs/debug/debug.c:656
 1 0x000000000009b4d7 ucp_cm_disconnect_cb()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/ucp/wireup/wireup_cm.c:771
 2 0x000000000002b2de uct_tcp_sockcm_ep_disconnect_cb()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/uct/tcp/tcp_sockcm_ep.c:58
 3 0x000000000002b2de uct_tcp_sockcm_ep_invoke_error_cb()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/uct/tcp/tcp_sockcm_ep.c:164
 4 0x000000000002b2de uct_tcp_sockcm_ep_handle_event_status()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/uct/tcp/tcp_sockcm_ep.c:211
 5 0x0000000000029d05 uct_tcp_sa_data_handler()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/uct/tcp/tcp_sockcm.c:118
 6 0x00000000000468fa ucs_async_handler_invoke()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/ucs/async/async.c:251
 7 0x00000000000468fa ucs_async_dispatch_handlers()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/ucs/async/async.c:305
 8 0x000000000004a17c ucs_async_thread_ev_handler()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/ucs/async/thread.c:87
 9 0x0000000000069d61 ucs_event_set_wait()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/ucs/sys/event_set.c:215
10 0x000000000004a9cc ucs_async_thread_func()  /scrap/azure/agent-04/AZP_WORKSPACE/2/s/contrib/../src/ucs/async/thread.c:128
11 0x0000000000007dd5 start_thread()  pthread_create.c:0
12 0x00000000000fdead __clone()  ???:0
=================================
[swx-rdmz-ucx-gpu-02:31161:1:4047] Process frozen...
```

it is a corruption, since `async` mode is not set to `signal` mode, but dereferencing an `async` object gives `signal`
looks like UCP EP has already been destroyed, when it comes to `ucp_cm_disconnect_cb()`
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=10520&view=logs&j=73bd2a9e-6688-5c22-d122-7b1a0b6cbb81&t=cd3d3953-51ff-5d5c-c5ca-2864f3c1d670&l=66183
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/10520/logs/175

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Don't discard CM lane.

## Why ?

Don't schedule UCT CM lane to be discarded, since UCP EP will be destroyed due to peer failure and `ucp_cm_disconnect_cb()` could be invoked on async thread after UCP EP is destroyed and before UCT CM EP is destroyed from discarding functionality. So, UCP EP will passed as a corrupted argument to `ucp_cm_disconnect_cb()`.
Fixes #5875

## How ?

Add `if` check into the `ucp_worker_iface_err_handle_progress()` to understand whether the lane is CM or not:
- if it is a CM lane, purge pending operations by calling `uct_ep_pending_purge()` and destroy UCT EP in-place by calling `uct_ep_destroy()`
- if it is not a CM lane, schedule UCT EP to be discarded

### CODE REVIEW

**Comment by dmitrygx** [comment]
The failure is unrelated
Similar to #5840

**Comment by dmitrygx** [comment]
@brminich @evgeny-leksikov @alinask could you review pls?

**Review by evgeny-leksikov — APPROVED** [review]

**Review by brminich — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

File: src/ucp/core/ucp_worker.c [hunk 1]
```diff
@@ -481,12 +481,27 @@ static unsigned ucp_worker_iface_err_handle_progress(void *arg)
...
+                                 ucp_ep_err_pending_purge,
+                                 UCS_STATUS_PTR(status));
+            uct_ep_destroy(ucp_ep->uct_eps[lane]);
+        } else {
+            ucs_trace("ep %p: discard uct_ep[%d]=%p", ucp_ep, lane,
+                      ucp_ep->uct_eps[lane]);
+            ucp_worker_discard_uct_ep(ucp_ep->worker, ucp_ep->uct_eps[lane],
+                                      UCT_FLUSH_FLAG_CANCEL,
+                                      ucp_ep_err_pending_purge,
+                                      UCS_STATUS_PTR(status));
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:502]: can we change discard logic, so it will destroy ep immediately, if flush is completed?
since cm flush should complete immediately

Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c]: ok, done

File: src/ucp/core/ucp_worker.c [hunk 2]
```diff
@@ -487,6 +487,15 @@ static unsigned ucp_worker_iface_err_handle_progress(void *arg)
...
                                   UCS_STATUS_PTR(status));
+        /* UCT CM lane mustn't be scheduled on worker progress when discarding,
+         * since UCP EP will be destroyed due to peer failure and
+         * ucp_cm_disconnect_cb() could be invoked on async thread after UCP EP
+         * is destroyed and before UCT CM EP is destroyed from discarding
+         * functionality. So, UCP EP will passed as a corrupted argument to
+         * ucp_cm_disconnect_cb() */
+        ucs_assert((lane != ucp_ep_get_cm_lane(ucp_ep)) ||
+                   !ucp_worker_is_uct_ep_discarding(worker,
+                                                    ucp_ep->uct_eps[lane]));
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:498]: this assert is good, i would write it like this to be more readable:
```
if (lane == ucp_ep_get_cm_lane(ucp_ep) {
  ucs_assert(!discarding)
}
```

File: src/ucp/core/ucp_worker.c [hunk 3]
```diff
@@ -2721,10 +2731,17 @@ ucp_worker_discard_tl_uct_ep(ucp_worker_h worker, uct_ep_h uct_ep,
...
+                          &req->send.state.uct_comp);
+    if (status == UCS_OK) {
+        ucp_worker_discard_uct_ep_destroy_progress(req);
+    } else if (status != UCS_INPROGRESS) {
+        uct_worker_progress_register_safe(worker->uct,
+                                          ucp_worker_discard_uct_ep_progress,
+                                          req, UCS_CALLBACKQ_FLAG_ONESHOT,
+                                          &cb_id);
+    }
 }
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:2745]: maybe just call "ucp_worker_discard_uct_ep_progress" and if returns 0 then schedule it?

Comment (yosefe) [reply src/ucp/core/ucp_worker.c:2745]: or maybe no need to schedule it, since ucp_worker_discard_uct_ep_progress would already schedule itself..

File: src/ucp/core/ucp_worker.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c]: done

File: src/ucp/core/ucp_worker.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c]: done

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
can this be related?
```
2020-11-07T14:45:30.4314575Z [     INFO ] Testing :::49294 Interface: eno1
2020-11-07T14:45:40.4414356Z /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/ib/test_sockaddr.cc:448: Failure
2020-11-07T14:45:40.4416016Z Value of: m_state & TEST_STATE_CONNECT_REQUESTED
2020-11-07T14:45:40.4417302Z   Actual: false
2020-11-07T14:45:40.4417884Z Expected: true
2020-11-07T14:45:49.7228411Z [  FAILED  ] sockaddr/test_uct_cm_sockaddr_multiple_cms.server_switch_cm/9, where GetParam() = sockaddr/eno1 (19299 ms)
2020-11-07T14:45:49.7229324Z [ RUN      ] sockaddr/test_uct_cm_sockaddr_multiple_cms.server_switch_cm/5 <sockaddr/ens4f1>
```

**Comment by dmitrygx** [comment]
> can this be related?

@yosefe thank you for pointing me out
Will investigate the failure

**Comment by dmitrygx** [comment]
> > can this be related?
> 
> @yosefe thank you for pointing me out
> Will investigate the failure

@yosefe I tried to reproduce this problem for a day. It did `1522554` iterations, but no luck to reproduce

**Comment by changchengx** [comment]
port below change to https://github.com/yosefe/ucx/pull/223 to simplify code logic
https://github.com/openucx/ucx/pull/5882/files#diff-68f50d5c8acc6ba66c30db814074690c7af4f019e8862ee6e8c320137746e85aR1088
https://github.com/openucx/ucx/pull/5882/files#diff-1a6cd9df9fc4c2ac2f3e662ca4ce0ff54e0ad405bab393e80090c8593745351cR2736
