### PR TITLE
UCT/SM/CMA, UCT/BASE: Simplify common Zcopy operations

### LINKED ISSUE #4134: failure in host/test_ucp_mem_type_alloc_before_init.xfer/0 with UCX_RNDV_SCHEME=put_zcopy under valgrind
```
$ UCX_RNDV_SCHEME=put_zcopy GTEST_FILTER=host/test_ucp_mem_type_alloc_before_init.xfer/0 make test_valgrind
env LD_LIBRARY_PATH="/usr/lib64/mlnx_ofed/valgrind::" \
stdbuf -e0 -o0 valgrind --tool=memcheck --leak-check=full --track-origins=yes --fair-sched=try --num-callers=25 --error-exitcode=1 --child-silent-after-fork=yes --suppressions=../../contrib/valgrind.supp  /labhome/dmitrygla/work_auto/ucx
/test/gtest/gtest --gtest_filter=host/test_ucp_mem_type_alloc_before_init.xfer/0
==29583== Memcheck, a memory error detector
==29583== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==29583== Using Valgrind-3.12.0 and LibVEX; rerun with -h for copyright info
==29583== Command: /labhome/dmitrygla/work_auto/ucx/test/gtest/gtest --gtest_filter=host/test_ucp_mem_type_alloc_before_init.xfer/0
==29583==
[     INFO ] checking dcx: no
[     INFO ] checking ud: no
[     INFO ] checking udx: no
[     INFO ] checking rc: no
[     INFO ] checking rcx: no
[     INFO ] checking shm_ib: yes
[     INFO ] checking ugni: no
[     INFO ] checking self: yes
[     INFO ] checking tcp: yes
[     INFO ] checking all: yes
[     INFO ] checking all_rcdc: no
[     INFO ] checking self_rcx: yes
[     INFO ] checking rc_x: no
[     INFO ] checking ud_mlx5: no
[     INFO ] checking shm: yes
[     INFO ] checking rc_ud: no
[     INFO ] checking dc_ud: no
[     INFO ] checking no_ud_ud_x: yes
[     INFO ] Using random seed of 23748
[     INFO ]  Setting for valgrind: UCX_IB_RX_QUEUE_LEN=512
[     INFO ]  Setting for valgrind: UCX_IB_RX_BUFS_GROW=512
[     INFO ]  Setting for valgrind: UCX_MM_RX_BUFS_GROW=128
[     INFO ]  Setting for valgrind: UCX_IB_TX_QUEUE_LEN=128
[     INFO ]  Setting for valgrind: UCX_IB_TX_BUFS_GROW=64
[     INFO ]  Setting for valgrind: UCX_RC_TX_CQ_LEN=256
[     INFO ]  Setting for valgrind: UCX_CM_TIMEOUT=600ms
[     INFO ]  Setting for valgrind: UCX_TCP_TX_BUFS_GROW=512
[     INFO ]  Setting for valgrind: UCX_TCP_RX_BUFS_GROW=512
[     INFO ]  Setting for valgrind: UCX_TCP_RX_SEG_SIZE=16k
Note: Google Test filter = host/test_ucp_mem_type_alloc_before_init.xfer/0
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from host/test_ucp_mem_type_alloc_before_init
[ RUN      ] host/test_ucp_mem_type_alloc_before_init.xfer/0
==29583== WARNING: valgrind ignores shmget(shmflg) SHM_HUGETLB
==29583== Syscall param process_vm_writev(lvec[...]) points to uninitialised byte(s)
==29583==    at 0x77F2F8A: process_vm_writev (in /usr/lib64/libc-2.17.so)
==29583==    by 0x8776B43: uct_cma_ep_common_zcopy (cma_ep.c:110)
==29583==    by 0x8776B43: uct_cma_ep_put_zcopy (cma_ep.c:129)
==29583==    by 0x5873BCB: uct_ep_put_zcopy (uct.h:2332)
==29583==    by 0x5873BCB: ucp_rndv_progress_rma_put_zcopy_inner (rndv.c:734)
==29583==    by 0x5873BCB: ucp_rndv_progress_rma_put_zcopy (rndv.c:693)
==29583==    by 0x5878410: ucp_request_try_send (ucp_request.inl:171)
==29583==    by 0x5878410: ucp_request_send (ucp_request.inl:206)
==29583==    by 0x5878410: ucp_rndv_rtr_handler_inner (rndv.c:1002)
==29583==    by 0x5878410: ucp_rndv_rtr_handler (rndv.c:917)
==29583==    by 0x53C1E05: uct_iface_invoke_am (uct_iface.h:628)
==29583==    by 0x53C2532: uct_mm_iface_invoke_am (mm_iface.h:151)
==29583==    by 0x53C2532: uct_mm_iface_process_recv (mm_iface.c:208)
==29583==    by 0x53C29DE: uct_mm_iface_poll_fifo (mm_iface.c:254)
==29583==    by 0x53C2B52: uct_mm_iface_progress (mm_iface.c:278)
==29583==    by 0x583417C: ucs_callbackq_dispatch (callbackq.h:211)
==29583==    by 0x583A8A9: uct_worker_progress (uct.h:2203)
==29583==    by 0x583A8A9: ucp_worker_progress (ucp_worker.c:1892)
==29583==    by 0x792CD0: ucp_test_base::entity::progress(int) (ucp_test.cc:655)
==29583==    by 0x78FB29: ucp_test::progress(int) const (ucp_test.cc:165)
==29583==    by 0x78FF44: ucp_test::wait(void*, int) (ucp_test.cc:222)
==29583==    by 0x6C4163: test_ucp_mem_type_alloc_before_init_xfer_Test::test_body() (test_ucp_mem_type.cc:119)
==29583==    by 0x5367E5: ucs::test_base::run() (test.cc:276)
==29583==    by 0x5369A8: ucs::test_base::TestBodyProxy() (test.cc:302)
==29583==    by 0x6625B5: ucp_test::TestBody() (ucp_test.h:143)
==29583==    by 0x518E93: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3562)
==29583==    by 0x514071: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
==29583==    by 0x4FB3F0: testing::Test::Run() (gtest-all.cc:3635)
==29583==    by 0x4FBBCB: testing::TestInfo::Run() (gtest-all.cc:3812)
==29583==    by 0x4FC25B: testing::TestCase::Run() (gtest-all.cc:3930)
==29583==    by 0x502A4B: testing::internal::UnitTestImpl::RunAllTests() (gtest-all.cc:5802)
==29583==    by 0x51A271: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest-all.cc:3562)
==29583==    by 0x514ED3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest-all.cc:3598)
==29583==  Address 0xaa95fd0 is 0 bytes inside a block of size 10,000 alloc'd
==29583==    at 0x4C29BE3: malloc (vg_replace_malloc.c:299)
==29583==    by 0x5274C9: mem_buffer::allocate(unsigned long, ucs_memory_type) (mem_buffer.cc:48)
==29583==    by 0x52832A: mem_buffer::mem_buffer(unsigned long, ucs_memory_type) (mem_buffer.cc:232)
==29583==    by 0x6C532D: test_ucp_mem_type_alloc_before_init::init() (test_ucp_mem_type.cc:88)
==29583==    by 0x53626E: ucs::test_base::SetUpProxy() (test.cc:228)
==29583==    by 0x662575: ucp_test::SetUp() (ucp_test.h:143)
==29583==    by 0x518E93: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3562)
==29583==    by 0x514071: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
==29583==    by 0x4FB39D: testing::Test::Run() (gtest-all.cc:3630)
==29583==    by 0x4FBBCB: testing::TestInfo::Run() (gtest-all.cc:3812)
==29583==    by 0x4FC25B: testing::TestCase::Run() (gtest-all.cc:3930)
==29583==    by 0x502A4B: testing::internal::UnitTestImpl::RunAllTests() (gtest-all.cc:5802)
==29583==    by 0x51A271: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest-all.cc:3562)
==29583==    by 0x514ED3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest-all.cc:3598)
==29583==    by 0x501687: testing::UnitTest::Run() (gtest-all.cc:5416)
==29583==    by 0x52364A: RUN_ALL_TESTS() (gtest.h:20059)
==29583==    by 0x523534: main (main.cc:102)
==29583==  Uninitialised value was created by a heap allocation
==29583==    at 0x4C29BE3: malloc (vg_replace_malloc.c:299)
==29583==    by 0x5274C9: mem_buffer::allocate(unsigned long, ucs_memory_type) (mem_buffer.cc:48)
==29583==    by 0x52832A: mem_buffer::mem_buffer(unsigned long, ucs_memory_type) (mem_buffer.cc:232)
==29583==    by 0x6C532D: test_ucp_mem_type_alloc_before_init::init() (test_ucp_mem_type.cc:88)
==29583==    by 0x53626E: ucs::test_base::SetUpProxy() (test.cc:228)
==29583==    by 0x662575: ucp_test::SetUp() (ucp_test.h:143)
==29583==    by 0x518E93: void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3562)
==29583==    by 0x514071: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
==29583==    by 0x4FB39D: testing::Test::Run() (gtest-all.cc:3630)
==29583==    by 0x4FBBCB: testing::TestInfo::Run() (gtest-all.cc:3812)
==29583==    by 0x4FC25B: testing::TestCase::Run() (gtest-all.cc:3930)
==29583==    by 0x502A4B: testing::internal::UnitTestImpl::RunAllTests() (gtest-all.cc:5802)
==29583==    by 0x51A271: bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest-all.cc:3562)
==29583==    by 0x514ED3: bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) (gtest-all.cc:3598)
==29583==    by 0x501687: testing::UnitTest::Run() (gtest-all.cc:5416)
==29583==    by 0x52364A: RUN_ALL_TESTS() (gtest.h:20059)
==29583==    by 0x523534: main (main.cc:102)
==29583==
common/test.cc:261: Failure
Failed
Got 3 valgrind errors during the test
[  FAILED  ] host/test_ucp_mem_type_alloc_before_init.xfer/0, where GetParam() = all (1204 ms)
[----------] 1 test from host/test_ucp_mem_type_alloc_before_init (1222 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1302 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] host/test_ucp_mem_type_alloc_before_init.xfer/0, where GetParam() = all

 1 FAILED TEST
==29583==
==29583== HEAP SUMMARY:
==29583==     in use at exit: 9,447 bytes in 39 blocks
==29583==   total heap usage: 166,888 allocs, 166,316 frees, 19,352,489 bytes allocated
==29583==
==29583== LEAK SUMMARY:
==29583==    definitely lost: 0 bytes in 0 blocks
==29583==    indirectly lost: 0 bytes in 0 blocks
==29583==      possibly lost: 0 bytes in 0 blocks
==29583==    still reachable: 9,447 bytes in 39 blocks
==29583==         suppressed: 0 bytes in 0 blocks
==29583== Reachable blocks (those to which a pointer was found) are not shown.
==29583== To see them, rerun with: --leak-check=full --show-leak-kinds=all
==29583==
==29583== For counts of detected and suppressed errors, rerun with: -v
==29583== ERROR SUMMARY: 3 errors from 1 contexts (suppressed: 0 from 0)
make: *** [test_valgrind] Error 1
```

Reproduced on hpc-test-node-upstream02

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

1. Improve Zcopy operations code by using common function for IOVs manipulation from UCS and UCT
2. UCS/IOVEC fixes

## Why ?

1. Improves Zcopy operations in UCT/SM/CMA - simplifies code and reduces number of cycles when need to do several attempts for sending a data
2. Fix assert() and add include guard

## How ?

1. Replace CMA's code by common functions from UCS and UCT, make TCP from UCT iov to iovec function common and move to the `uct/base/uct_iface.h` file
2. Compare `i` and total `iov_cnt`; add `ifndef`-`define`-`endif`

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12233/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 1 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/bd26eedaf8b52c0fc175fa076993156e/raw/229eb80afffd8922b70653f087517b0ae6370cdd/_main) | :x: FAILURE

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12234/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 29 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 11-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/97dab32c59ccee650089a3883606f7fd309511d4/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/3aba938d389ca7755fbdab7038b29a006098488a/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/f1fcc732afeaf0b6d709c67562feab81f2083560/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/17ca3a87a6330e7e397ceda00c4c2c4aafff769c/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/847c33c3b3df4d250151676266be60528c3c601e/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/3b8c3e28598d5011e55f3735ec16ab87fd78caf0/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/4410f151bd7cabbbfec20e2d8df12b5a5fef15db/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/556a35d8386d8501f5213b95792cc1015e27d1ef/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/15aab94bfb9526d9e6956ba14573bf6ddece2ad4/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/d6ad9a33fb9801f97136ea4b9d247c820fce5daa/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/6804ef1b301ef890c96d80b3848df864115a1614/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/2a711eabf59743daa67d19d0606a2fa348b51bf8/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/3dfbede1a0126a92aa2b898046091bc4e59b7c9a/hpc-test-althca_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/19872442614effe7979fa43c882b9d2969d54b22/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/97f7bb2820f736c022b7e9029beec9b5cf977ae7/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/732009307218ff833fcc054e659040fc732ef1f3/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/561e9e518990221e0be431e90333dcc4955a3309/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/941548cbb68b337b7b96875cd25727dc4b632382/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/e20d4dedc0823bf1813bf45f2fba06bde071232f/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/a5b3b7f3bbf432b1464863f18660b65c9ded63c7/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/514be259b75024a3292c31a6e70d1a6cfd6e1909/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/22892497362844d7233f703d8e436ec9e591d512/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/41a18c14fe3f3b6f71f971a66070005ef0c118bd/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/89a4f8acd1aae44fef89c9c10550a00788f77d48/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/2978f2916eeaa9bcdf6e8f4aa5e58af884913c91/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/58a80315f8f0adc3821da0b2afa0047b72c6b442/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/93bf2e658818a22012c859bc1a591959601ee665/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/f60fdca09d5f9c01ff534bc35d35b380f5003581/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0c14c230afaad6dbc069662f56886fdc/raw/07ca5bd912410b8d052cb876fef2d63cd1a2aacb/r-vmb-ppc-jenkins_W3) | :x: FAILURE

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12237/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 1 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/46e0bd64de97c1f653b57d6db1e25c6d/raw/21d7813c85510bab4e21d1c5ef4f5920d275fd88/_main) | :x: FAILURE

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12238/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 29 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/24bf17060ed2d8c62ec2359ff72913cb8cc6d002/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/2fb587effeebf152cb120d8600ba37f6619d9d28/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/bf1fda4efc4ae56e76eebaea18ff4c53f3c254a9/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/f4faa37988a5ad2850d41854850fddc6749f0a28/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/8bcb16c9d1457948e8f939478fc0e11c4f6fe554/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/c188fd9112ed010738fd25643be472aa233bbc25/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/937be1083571a4aa804e18660c4e1df2cf53e1e4/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/f1ba2b0faeeadbd94a21c4729d080f48a384fcff/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/d6c9df2430b8f684ab7dfc2d63d3aab3b01c82fa/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/422e8ddfaeba80aab177cda21ad21baeaad460d1/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/046f7a5c0d53a5c28a3e6221b894a985849d2a2c/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/e87cf4955d17f95d0116272a8073579d09049f91/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/0897c3889fe95d3d2e5b6749b012992ef2450175/hpc-test-althca_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/f763ed74e00e33139d48f6341c69ecbbc721587f/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/14a3d459ced224208add19485f3e477ef0171049/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/58e1c57384c984e8d692c6b4e1f18134ae7843bd/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/e452dad746ac84508c1c07b3585b5d61d4b74109/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/6ebc335c789837f9d767cbb0ebe64e3c80563ffb/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/707640d89d7b94150ee793e013d57aeccf454a47/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/1ca8c59cc87445fe5207713368aa23a1efd5a303/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/0f5ec3f1f215eae42ecb551ac226328681fc93d1/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/eaaa7018a2d84661e9ea93e3f0ef19121a3cd466/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/29c961e2f4581bed7b08bd4badc4cc9e0ba6eff8/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/2929386fd14396e7fe50c92b18e398b47370b591/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/70925a6537a963436fdbc3ddb704475c9873258e/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/7b19616ff67c478495ba070fbe1de2560b3ac459/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/ad1221a61fcfda65d65c4b6d0fa6630856aaccb6/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/69631b0a274da86f78144e31f52c09abd158519c/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/934324978392ac3b61af78e0a52e66eb/raw/d80b40fc8059747a56e2f9f54bde02493377c28e/r-vmb-ppc-jenkins_W3) | :x: FAILURE

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12242/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/a01aece4355e4473b5d7aec0bcadf7d52a242289/_main) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/19193a465a02127152634cf89b85d79d7f0849f1/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/78e893154f40c384f9e410cd25406df61fe3be67/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/c6822a9ab259b31e06cb93827f3ad42afeb3f2e3/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/b086653e42b137719782e903c5e8cbc12de1a36c/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/ed338e01efb80eba8e71c4af91bbe11a336bdae4/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/fd838a62a0ce1ae6a1185a43ca53d67622d536d9/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/0326257b1cc349661303289ca33fd5e1a6a0e949/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/b3180d873cb2b0a8939e857d29360fc86498328e/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/95a61555884b57f301c24da4f24b43c62920faf3/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/b7dc050b5d1fe9c5f23a3d19cf49446e19c64a73/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/d784b8980420c58287056cdee317da50a5ede7ef/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/61ec7763a2a15288d2a1784c151ded7c1453a1e9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/3f9c4a85c697afb17b888d563b01af951705b679/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/af1bc8454cc5deefa7e9eac858ea74ce835d5dec/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/04b5db3a4269afbfe486a11cc17472cacae15e29/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/07edc962fcc857abc69a09de867b7612ecc8ad8d/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/88749598238355eea241a3eabf67e5d87203cf35/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/f1b06ec4bd9c31f7c6514dbd7a19a19a76ebb876/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/61b46d52c44f5a445315f5c184cc7e95e3d9a97a/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/e01a82fa963b7e497e456b291e6ae7d7c1b0c3a0/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/63d20ee9d3e4b2408a538e4fc5f66602a7c98914/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/989a1e715a3898b8b350f71ddb09591f56547377/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/7c5d96c7464c2b16b87985b9d7bc51d69ef6ed4a/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/64c1d786fdfdd837eb16809866c8b51665661ff1/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/fb8caaffd70ca6f9d313f0815a41100c810e29ca/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/b1cb4109903ce1313631c8bc3d3c4e5c6e5cc341/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/121099cd76ff1d706692bbc464bb8f1683eda657/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3334badae3492cab9d20bfaec7a7a8d0/raw/850782684b092f9f441be71856fafa9ecee8cdbf/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12243/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/7695e57372cf162b3ea85a7763308a4b4f5b3bed/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/f11287efc08b084fe82a9c348d2e2a52a82f18c5/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/4203e5cc33ba438bcda89febe83e83df2d3dce9a/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/102ed402eb8f0b53169f46300b1e5d563ff5778f/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/28adef398fd8bf35859be41bdf1a3d295f804f3e/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/1d0af79374612d8b7e8682deaeb348373b587a02/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/931a166bdcd4b7fab2d9c63e93464e6fdbe0ece0/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/60405298481fc393634dd5210d99d71e2c050392/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/1dd38cade6937cee3a53f8cc1bf8811ca512b998/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/69523f703d0a1f2a0c62fd27947000bc98626c7c/hpc-test-althca_W0) | :question: UNKNOWN
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/478b09157394d63f9055892db71151d18c1dd1f3/hpc-test-althca_W1) | :question: UNKNOWN
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/c1e8326e45ee46e3f300f15a7d143af9f1be7007/hpc-test-althca_W2) | :question: UNKNOWN
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/5ac29fed8fce54e8855ab3af4259d31506d8fa45/hpc-test-althca_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/a00f45eb85186ecd4d34efcabc7da1d26ff8cba0/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/60e4aa78bcb5ac9bed28d3b67283b67b950f2739/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/a73acf063898aa92cac02444ae8e5de09b064328/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/9bfaf9eb3e3bf8ff0caaaa476866ac9534a15a2d/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/5072d24cb70ee1a7930a86c7c198957539e971bd/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/1ea1d889c3dff53c30e2aab46a2a2d5c8886484e/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/881dac2e003c32a87139219b47e0d51f616b1946/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/b04b21281dc9d69766e5866e3d1be6eca474be0b/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/31f0609f324f4273980faf51b604e1db0c8e3c80/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/1f01c1ffdbfd6cda78f5ec10ab600a0446d0e196/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/3496e2df6f56f09a7ff39cd743b81cc8195cf637/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/a823e9973021e02b241458b72302ed3ef5070c76/hpc-test-node-new_W3) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/960845041a6850c5a2c11e3b0498cc6003881cfc/r-vmb-ppc-jenkins_W0) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/90f17c1a954ba1245ad6e1774ea351a54a27fff7/r-vmb-ppc-jenkins_W1) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/16c5db27fde1462d3047d64d84d94ff36976402a/r-vmb-ppc-jenkins_W2) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1086a07978f15738e8a817dcf73e1538/raw/da8342b6abade7da4b9df6819711b7d72d6d97b6/r-vmb-ppc-jenkins_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12244/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/1c7d55d1f1ec04d1b5e6a86cb6577b6e2500b415/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/6c94d4f8227306ec4f4d5333cc51082133bf89ee/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/7687073fa3764b241ab23dbd69c41c3203365d7f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/84a5d5ebf532c129719c3eaa22ea90f647f4257b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/50b93315607549bc025075bf31062c626c217b2f/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/7f982983a3039e2f9a0499008ca22fa1cdef6d65/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/3516f40b1b0ea5ec6420a69a4f2751b6618925d3/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/01ee77e680e12d736500bffc90e26f4022718729/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/c971753f38b03e8ce22e88f1024e6c36f89f8562/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/3cc01b3d66f780a93569565e7770593a82de694c/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/253a28f39d761dabca57e7da17c77f98ebc9c6f9/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/34bfa431242081de1ec5f595a5b6ac52ca118389/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/62c93b24b2abba2964b6d68a8cb932d5f444dc67/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/7df6a9e3e886c97fbd3ab5cacb35d904dedc0787/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/4c3ad3a50dcaa3abedcf62e2c907470e886e28af/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/e9036204a0c0e618e272de2021e0026002671681/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/98fbf598b854e662e9f45f4c05b8bbf7aecf936c/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/e7a388a315b915ed3026200e3d7029e51b13e959/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/a06c88703b5e774d18bc762a5f65fb3385c1e79c/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/8a9af19edcad755fc108d271475c6978a3c49a33/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/97dea704c6193f9fb3ce72acf25c9289f814d259/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/0c7e5b8048c1808e105e03118757c9af391f3810/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/758880ec6cf0458377800dfe2f37ee36951a4075/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/a2fc53501f2f06391540b12418e068eb7e07d198/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/85ef0a70eaf44a1319b35157c7f13e79b190a1ef/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/4d6997c9ec8c41333d50911be0b02a45491d8c7e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/16296fe2bbe4da12ddc01ff8f80e6766a968c71f/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/a6b3d484f1c82b84508a367fb9dd5dc3d871c2be/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b629d920ddc3581473deea766ea4a501/raw/d26a938b54175b4f635c93232de58acf66854845/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@bureddy @brminich could you review pls?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12248/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/e40f9056af48fa2be329916d02c2c20f7eb569c1/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/41dfab0648ffe2c3e801dfa1d7f652773a3b8114/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/b0fe15f117113c2c96f73cdd451f757c9e63c460/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/2cb2c7b65d6327abfcf6cf1122f53a5bae83eb39/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/d3a3025a76250c9f71072fb6b19c8f58139a2a60/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/791c42958a563aa7413c27165c97f73702122597/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/0b3952b686e50d4b3b754de6810d3d74cd5f1771/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/7d0b2cd25b938eb4340e65622d635792d49b61eb/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/70af821f054ede530d13a59f63063ae9b8ac8d3c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/504f781c7a77723a73a4044a34e8aebdafb77f77/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/c3ecca250b6d78abc04d45baaee525f5bf57f0d4/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/b2d9cac6ca8611b4295b76f25b4ce559b0e546cc/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/3a5aa43ff867604b0723e8c0fa90725b2c76f134/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/61af5895fd06422700ee762b3a1cd2bb77241497/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/d3effeee54c9eb76d7682d68d82d9e49d199b3dc/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/49db164ee8d148772286c631478df1622f932447/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/b27d1a712bd9861be1c7f877e677350589591cb6/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/55267d7037b7f5b92f576bc8900618d221a7a007/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/50da4d8812bad8cf43da1e24f5357025280347a6/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/a442231296a16aafdde4e6c8329656f97de05360/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/ed0db19dce561317b143db4ad81d61ba792371e3/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/a659538503faed85a073e0fd0086c37c7a15da66/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/277ad5bccf62bbf609a29eb954037c43c0a8c6da/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/b9175c4450157d296f4d705a7a1bc78bd18df759/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/25e4a0f9da04a465d2fa15ac08bb5bc42b770c18/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/f73f7b53a1496e210d749b239e0d812150acc88f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/e5da829e927434ab45e4b45dbb827e8ab2b72667/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/bdb13389856499d2c94b4e7b10935d78d47dbbe2/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/34ff0ebc48eae5eed3e1b0a49d68c35d/raw/cf8452adc6a2337bbcd74a20b835e9a7149fe017/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/sm/cma/cma_ep.c [hunk 1]
```diff
@@ -55,66 +55,37 @@ ucs_status_t uct_cma_ep_common_zcopy(uct_ep_h tl_ep,
...
-            ++local_iov_it;
-        }
-        if (!delivered) {
-            length = iov_it_length; /* Keep total length of the iov buffers */
-        }
-
-        if(!length) {
-            return UCS_OK; /* Nothing to deliver */
-        }
+    local_iov_cnt = uct_iovec_fill_iov(local_iov, iov,
```
Comment (brminich) [inline src/uct/sm/cma/cma_ep.c]: do not you need to fill it by `UCT_SM_MAX_IOV` portions? (assuming UCT_SM_MAX_IOV < iov_cnt)

File: test/gtest/common/mem_buffer.cc [hunk 2]
```diff
@@ -45,17 +45,19 @@ void *mem_buffer::allocate(size_t size, ucs_memory_type_t mem_type)
 
     switch (mem_type) {
     case UCS_MEMORY_TYPE_HOST:
-        ptr = malloc(size);
+        ptr = calloc(1, size);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/common/mem_buffer.cc]: this fixes Valgrind error for UCP memtype test in case of PUT RNDV scheme
data must be filled out

File: src/uct/sm/cma/cma_ep.c (hunk 1 above)
Comment (dmitrygx) [reply src/uct/sm/cma/cma_ep.c]: good catch - fixed!

but looking in the previous code, it seems that the case when `iovcnt` > `UCT_SM_MAX_IOV ` didn't work

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12261/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 12-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/6d9965e3d7e9906f13677a55860aac3fe88103d8/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/1d94c63298b41604fc12fa9526de864dba1fe459/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/f72c6a81696f09388bb16a4150dee76fb70466fe/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/a58d4cbc2a1996101c0bf556566ee476f578aead/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/60d6c8d12f250742b5bfb252cea0ba114401dee7/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/73c2b088cb9ea055512cc6aab72025ed3398c2f1/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/b040f9a2ef52a82f86991d1d925417624576eb13/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/8d0de88add2a643089dea7c85c1882b530ac8e79/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/12bc89d0f73d776801a2908f1371afb0f85d6369/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/3352b2680cfd09a49b7dc601e76fa2386eec1424/hpc-test-althca_W0) | :question: ABORTED
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/635eabc2527bdfdb4619585bc6cdde60477471b2/hpc-test-althca_W1) | :question: ABORTED
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/2c93124c42840a0c2ae5c468d96d48a1ebc66f7d/hpc-test-althca_W2) | :question: ABORTED
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/ba3f763ba1e560aa5c5c108ae13b1d7275ab14c0/hpc-test-althca_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/9e6ef72b3fa3921bb8f8919a874e066bd1e50309/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/cb955d0cb49f5857400250d1f564bfd7cff032b9/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/451248a296ae292941e227db6b23515d712fb1c6/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/986105e254aa38f26cc5383d378873881bcaee47/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/0635f3dea46c06bcf577f659e7c3b4d1895ec0db/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/4ee1fde4dd5d871e284e0142fd478f32350d3677/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/33d0a962577caa310a526de86a14471601b07205/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/542f09ba170b540ae9033cd80dd1f1d582c916bc/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/114511ffb2fe40925c75017eed98ac4c6ada63c0/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/1f5f51c37a28cf2893a9a0edb7c739cf061e88fd/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/a44a602e5cc1da311b16b5ddbaef36f2db48a9b4/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/63fb5bf4a9a63cc06804468aa29d09892b47c630/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/dad22afabefc3bbfb08c3b493205125c09499a30/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/4acfda9462f632d597ba3392b1a885a45eef4fa1/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/be84fcce1111f299bacd981c4765163eb9178934/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a6e527601bf1bd14e2652d146346ac43/raw/92d448aa24aa7238fb2227f0f2b5aeed9372ad92/hpc-test-node-legacy_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12262/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/687e51f0d74985c7d5ffef8398d87bcf981f8957/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/d7d19ae2086fa25425324b6f7e790e9e6dcc6839/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/c2a0124bba10967fad96808d65e651d254284b26/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/0072e79ef84048042aff66e69458c9d20665590a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/fa20578304d5d039aece9c627e371f2ea0f1d07c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/dd06f7c255d4b38fcbb2cb336a49bc4e0ee77298/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/d9c09bb963cd94a7244ca0fe5d0411277bcd86af/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/ae9b87791e9a86358eb885f4955cdf33ce5d1cc7/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/d6b7d9a4ad369f94351b095907cf4f9ed8f57794/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/79118a0cb529587e34f56622bf9f7d7a0f2b00df/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/82d797b03eca3612eddc4c714998363d7208c054/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/b150c8d4df35c33e4bee368a356c97e54bba33d4/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/c2f94aebbee30d935c0516a399030dc51fd2348d/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/5cbb2c487914a8176faba1c35aec32256aa111be/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/345aa58b2f04f5c1acff89289935d8817c831fca/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/5f0b3cfe5698331aa610ff5bfa57806a26ba7a82/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/8eb65c0b5295ac069ae83a4f9367feedc4aa564b/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/20f092ebdec4e445be1f4f0119400def911a5e24/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/79631b9aa44835bcf89f25a99217bfcee5554296/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/ee7378fd87f7c96ee9da52370d9ef32c991c819c/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/c483cf9aa6d82762328567d626a5bf3090ab215f/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/15038fbda435f825d4030b85d219fffc613cc658/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/4ed1404526122fe5325d5f2556b6eeb532182f6e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/8cb9014bf74f4d2cc39758ce35c7a9af4f89e8c0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/1a10129220e763100d0b78affb58c78a2a91d839/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/98b77d110340a19a2d915ab2ffc41c74f592a640/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/65890f15cb781e9782fcf5f97d51aaefd4d5bd99/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/949a40c05d83f5cbd6095753bfbbc6142d5cbffb/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e78c945d4bc7dd454144da10acc7e358/raw/2b93a287e6ff656b36ea33c674b8af71435e9e67/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/7a8c52cf506326c78fba0f62649b8c560484dad2/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/9df54a28148a2bd60ae69735758bed197bb80d1d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/307e7a714b1cfc08e96f227fa07cfb23844ebf80/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/345e9a5eab201a2258727f4cc527587ee6f9a687/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/7e45fcf3eb430d78c55df59cc065e98377140dc2/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/e168ab7663c0eb8ad5d0786fea6c6d2799c8712e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/8ee755fbf7817191ae57f68546688b009008c9c7/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/6ede2443177934a83efb9228eb8b7c12468c37af/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/d91afa39eccb20225df7c746f772ff1299519be7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/84a088d158157225d48cf0dd2b4595a09ab6614d/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/3bdf951fd6dc0175ef3e00aa32d3a304d141d1de/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/67bb75fa760f8cdf865c5d27fc659b3df7b59a16/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/ffd54f867bb9fdda5a881906ea206cbbf01b0219/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/f134082fef796a4dba68112dbe5a600479d74ec4/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/39dc7a8b018cd12b1656b5eb10550dffede3ef2f/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/c26b279b26c125223acdc7283010b6fdc7edbb4d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/77c5ec95b3e7b442f7f497ff10b9763ef7f1c865/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/5a158933dd80aaaab807406d935a68765118ce7f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/6182cc3d78a9fd399f42ff08e7018fd095d0e0dd/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/f7fd1ea2d45dbcabc6101a50d43150fa59883647/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/1d67a28d104a3c6758fd9fa5cf88a6db80c5398a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/71a0858ec7775f6f3a4ed85567b0d4bb85c1a091/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/cdb5f6c87aaea308fb5ca1a0bf1ad342b9dba63a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/89e1212af4176b5d248f768aa7468064fc4378ef/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/273d83df3825238d20894efa5ce42d5cdaed39be/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/259980c32c48703fedac6fae909fda1b268f6e8c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/88b93f6467eb9684fd41b2c0c4a5415f9bdd9e98/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/1a4e7d937c8298c967231c2f6904ed5eb0a77820/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/def33188e60bdab1712b75e19163906b/raw/8c13ded3235fa4e04bcf58ca96b40967e61be113/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@brminich @hoopoepg could you review pls?

File: src/uct/base/uct_iface.h [hunk 3]
```diff
@@ -673,6 +673,33 @@ size_t uct_iov_total_length(const uct_iov_t *iov, size_t iovcnt)
...
+
+    *total_length = 0;
+
+    for (iov_it = 0; iov_it < iovcnt; ++iov_it) {
+        io_vec[io_vec_it].iov_len = uct_iov_get_length(&iov[iov_it]);
+
+        /* Avoid zero length elements in resulted iov_vec */
+        if (io_vec[io_vec_it].iov_len != 0) {
+            io_vec[io_vec_it].iov_base = iov[iov_it].buffer;
+            *total_length += io_vec[io_vec_it].iov_len;
```
Comment (yosefe) [inline src/uct/base/uct_iface.h]: minor: align = on column

File: test/gtest/common/mem_buffer.cc [hunk 4]
```diff
@@ -45,17 +45,19 @@ void *mem_buffer::allocate(size_t size, ucs_memory_type_t mem_type)
...
         if (ptr == NULL) {
             UCS_TEST_ABORT("malloc() failed");
         }
         return ptr;
 #if HAVE_CUDA
     case UCS_MEMORY_TYPE_CUDA:
         CUDA_CALL(cudaMalloc(&ptr, size));
+        CUDA_CALL(cudaMemset(ptr, 0, size));
```
Comment (yosefe) [inline test/gtest/common/mem_buffer.cc]: which test does not initialize the allocated buffer before sending it?
seems like test issue rather than allocator issue

File: src/uct/sm/cma/cma_ep.c [hunk 5]
```diff
@@ -55,67 +55,52 @@ ucs_status_t uct_cma_ep_common_zcopy(uct_ep_h tl_ep,
...
-    do {
-        iov_it_length = 0;
-        local_iov_it = 0;
-        for (iov_it = 0; iov_it < ucs_min(UCT_SM_MAX_IOV, iovcnt); ++iov_it) {
-            iov_slice_delivered = 0;
 
-            /* Get length of the particular iov element */
-            iov_slice_length = uct_iov_get_length(iov + iov_it);
+    while (iovcnt - iov_idx) {
+        cur_iov_cnt   = ucs_min(iovcnt - iov_idx, UCT_SM_MAX_IOV);
```
Comment (yosefe) [inline src/uct/sm/cma/cma_ep.c]: it looks like CMA is trying to support iovcnt>UCT_SM_MAX_IOV, even though it doesn't have to according to UCT API
can you pls take this opportunity to simplify the code and remove the external while loop?

File: test/gtest/common/mem_buffer.cc (hunk 4 above)
Comment (dmitrygx) [reply test/gtest/common/mem_buffer.cc]: yes, this is the test issue
ok to split this PR into two ones?
- CMA fix
- valgrind error fix

for valgrind fix, i'd add `mem_buffer::memset` that fills a buffer according to the memory type (device/host memory). wdyt?

File: src/uct/sm/cma/cma_ep.c (hunk 5 above)
Comment (dmitrygx) [reply src/uct/sm/cma/cma_ep.c]: CMA reports that it supports maximum available IOVs
https://github.com/openucx/ucx/blob/f2a2cb3c0dac90649781a0f9edcfa78562298186/src/uct/sm/cma/cma_iface.c#L42

File: test/gtest/common/mem_buffer.cc (hunk 4 above)
Comment (dmitrygx) [reply test/gtest/common/mem_buffer.cc]: created #4171

File: src/uct/base/uct_iface.h (hunk 3 above)
Comment (dmitrygx) [reply src/uct/base/uct_iface.h]: done

**Comment by dmitrygx** [comment]
@yosefe force-pushed, because the commit with valgrind fix was removed

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12277/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/bac6550f0f5753aa4787e330160d3bbc5330fa97/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/b7790002501b9328545b499db24c2a9cf32201fd/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/8ba22cb38b4a16f17e9f60f798af60af92a2e817/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/798aa184e2e50753e303ab8079d93738c7007504/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/05f58e470e85708af00d9a4909cd226d060c3aae/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/266842da005089b7ca51589f0dfa85dca3ea4fc7/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/898b64741dc92cf734337b2cc89376fdb6b59e9c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/94115a1e1d0f17bc2f5d278d626f3a936ad52f36/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/f38c07843fd0d9d9fb0bc08fcf3416f60da5ab91/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/3f5f00bde92e9b582c2c2f63a6ceb76ff74b3f5f/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/9fba5e20c0f07ca184b25b5ab47e1d756e37fd3f/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/a021cd2a983c5ff55d8da46414eb0c4eb0c405ca/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/48f2470bd70547ba43ee0581a26d2223f436e8b2/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/e5dfc510ada409774e4086657630c7e87bda9cc7/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/5479de35eef92930019ddaa6fb3887ab3eff00d8/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/34384ed17174b8baeb7be44b2b1245777d322402/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/2b99abd758eec6403a629b1ead3ebf2bca75fcae/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/1049798aa94bff284df4a3edd7372b8ad507ab77/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/ca52f6cd211981150066640923e4f892568f862e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/45183421ebe58eecb2d00efcaa7e03a057b6a96f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/3739b94373fc628d4bb34b3e8abaa5cc722cc43f/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/f4868f27441f4a2bfbe2933e1a1b4e8a78c3f991/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/d0044137165123535008eb4d9d92594f5ad2af1d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/c4aff71c346263edd31fab4c50be08b5d81157ae/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/c3ebcda5b0f1c23f4bfb0d1095305e5b75a04573/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/4d80d2526fe9fa68f5774d6a8b9c36abf809a1cd/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/6f361d412650bf3efb15924db5f2132bd1bfb9c2/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/28c9f993a2c0915793065b58bd00b4092897e203/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a33680ada43a833615532788e07a7882/raw/6a56899e21c838c15ee84b3974164b94206497a1/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/base/uct_iface.h [hunk 6]
```diff
@@ -673,6 +673,33 @@ size_t uct_iov_total_length(const uct_iov_t *iov, size_t iovcnt)
...
+static UCS_F_ALWAYS_INLINE
+size_t uct_iovec_fill_iov(struct iovec *io_vec, const uct_iov_t *iov,
+                          size_t iovcnt, size_t *total_length)
+{
+    size_t iov_it, io_vec_it = 0;
+
+    *total_length = 0;
+
+    for (iov_it = 0; iov_it < iovcnt; ++iov_it) {
+        io_vec[io_vec_it].iov_len = uct_iov_get_length(&iov[iov_it]);
```
Comment (yosefe) [inline src/uct/base/uct_iface.h]: maybe cache io_vec[io_vec_it].iov_len in a local variable?

File: src/uct/sm/cma/cma_ep.c [hunk 7]
```diff
@@ -55,67 +55,50 @@ ucs_status_t uct_cma_ep_common_zcopy(uct_ep_h tl_ep,
...
-        ret = fn_p(ep->remote_pid, local_iov, local_iov_it, &remote_iov, 1, 0);
-        if (ret < 0) {
-            ucs_error("%s delivered %zu instead of %zu, error message %s",
-                      fn_name, delivered, length, strerror(errno));
-            return UCS_ERR_IO_ERROR;
-        }
+            ret = fn_p(ep->remote_pid, &local_iov[local_iov_idx],
+                       local_iov_cnt - local_iov_idx, &remote_iov, 1, 0);
+            if (ret < 0) {
+                ucs_error("%s failed to deliver %zu bytes, error message %s",
```
Comment (yosefe) [inline src/uct/sm/cma/cma_ep.c]: probably will be a conflict with @brminich PR

File: src/uct/sm/cma/cma_ep.c [hunk 8]
```diff
@@ -55,67 +55,50 @@ ucs_status_t uct_cma_ep_common_zcopy(uct_ep_h tl_ep,
...
-
-    do {
-        iov_it_length = 0;
-        local_iov_it = 0;
-        for (iov_it = 0; iov_it < ucs_min(UCT_SM_MAX_IOV, iovcnt); ++iov_it) {
-            iov_slice_delivered = 0;
 
-            /* Get length of the particular iov element */
-            iov_slice_length = uct_iov_get_length(iov + iov_it);
+    while (iovcnt - iov_idx) {
```
Comment (yosefe) [inline src/uct/sm/cma/cma_ep.c]: `iov_idx < iovcnt` ?

File: src/uct/sm/cma/cma_ep.c [hunk 9]
```diff
@@ -55,67 +55,50 @@ ucs_status_t uct_cma_ep_common_zcopy(uct_ep_h tl_ep,
...
         }
 
-        if(!length) {
-            return UCS_OK; /* Nothing to deliver */
-        }
+        local_iov_idx = 0;
 
-        remote_iov.iov_base = (void *)(remote_addr + delivered);
-        remote_iov.iov_len  = length - delivered;
+        do {
```
Comment (yosefe) [inline src/uct/sm/cma/cma_ep.c]: maybe we can move the internal loop to a helper (CMA-olny) function, whose goal is to call fn_p with linux iovec repeatedly and handle partial read/write?

File: src/uct/base/uct_iface.h (hunk 6 above)
Comment (dmitrygx) [reply src/uct/base/uct_iface.h]: done

File: src/uct/sm/cma/cma_ep.c (hunk 8 above)
Comment (dmitrygx) [reply src/uct/sm/cma/cma_ep.c]: done

File: src/uct/sm/cma/cma_ep.c (hunk 9 above)
Comment (dmitrygx) [reply src/uct/sm/cma/cma_ep.c]: done

File: src/uct/sm/cma/cma_ep.c (hunk 7 above)
Comment (dmitrygx) [reply src/uct/sm/cma/cma_ep.c]: yes, it needs to be handled when @brminich  PR gets merged

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12283/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 1 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/75862e8fd101b9b739db736f24f4cf93/raw/d0fdc0bb4d17f7a648353ff28572210f4d0b96c1/_main) | :x: FAILURE

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12284/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 29 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/8606404f1474899f4e173233e1206c9360d57d30/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/a51afc0b2d69c936789e4e2f5cf74db38db5cb4b/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/8a823fc0627dd4060ce601251d7b0d3ec9e2bec2/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/8f043f62b55a6b2b0ed9069075fd6e9cf53d8284/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/e8463dde24c850cff166a03df7d2f181479749a5/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/5f5b459cbc87db435e60d3b8d02e1e3de314d747/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/85392903a2cec9ce54cdef9f64589bbf450d2b5d/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/cf7a9e30f3380b1ce5843d849f6bb6f74dddf426/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/0727c8f6559a87d5ce9dcf29325634d556a0b179/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/915cf1df23710460169002a950c4e660b00c617a/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/8b5543ace37cbefa49cda3a512e7f932d695c171/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/e221e21dca4eff747d680134396478e3edf506cc/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/f91947ef439b797571c20892cff495457e9ac36e/hpc-test-althca_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/62b4e8c0c04efec98854db3c6dcd94ec8fce212b/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/6c00b7f82bee52c49dc725591280d5794e5a03cd/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/88db1d453d4ba3798898f03ff2109bf5f389279b/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/55f7fabd56437b53ebe5447ff46060407970eaf5/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/5c451dd01bfd802ad683ab97d17422ddab1bb636/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/c30a1cf0098cd6be3d680c920cfbc6916cab6da3/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/11c47da62c4b6ae4efb5813bbbb3a6ff773efecd/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/25c003d00f0a2d01b8f1ae7e8bff66ab994d944f/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/034e77329042f5052108d6da5eed5ac00715cdd5/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/d97c6f6cbc5c711743cc411d40cb7a66557a5ed0/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/634b168fa063305d48e20fda85a9c12303ba3149/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/98d002a2bc0ec23363500e4327e90f4e915bc646/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/046340ed52358ad56605ee722745e231210eab1e/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/fbdc51e223d9c02e523559908007f375f45eb0d4/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/c516e14cb24c3f944cfab4eabc018cb18cfdab8e/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8c1de0e77c7881ed1a2a71c12787be7f/raw/ca227ab4b87335f7c3ae419d8333a3d3482d867e/r-vmb-ppc-jenkins_W3) | :x: FAILURE

**Comment by dmitrygx** [comment]
@yosefe thank you for the fixing merge conflicts!

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12285/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/ba08ee6b7ace3024ef0fc6bf7396abcb0de78a33/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/4bf77980aee9023cbd18ad4429fc3c1077579c25/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/3adbb2084052471511d77d0b652b0ff8db948159/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/8ef3494a40828f10722e83dea0849082fd54cd76/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/bb3ae389ae8da20f1381fb1565af5d0c62e1adc4/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/fb20c9ea3eb39fa036a9742568294c3da1b1a523/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/3d08dbb8c5d8fa7ed3ebd89d914794212c9cdefe/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/69e009229802daa16bd943428301e566e05ea40f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/264ada0af7d0693104835f2db0e2a514c3b36ff8/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/d8d8da34ccbaf3e1b1990d97ca9ae636d47ed81a/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/3141d41b5b13347af5a84325b43660bf28475e02/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/ae84da8d01c34000315330157f1de3b7169f0680/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/58bd34b55abbe0e898dfe17d37cc0e8c5cecf3ab/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/466632965922cc9c221e09e36a69ef793eb335ed/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/fecd0aebe9be5380b9b2090822a38ecfda411091/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/5fcfe9722853e191e5be0b58179946754953d5f0/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/6289e514e2ef0c7b499d8a9af7048e0b272307e7/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/6b2c28a574c23b1c219b3e9b8c90a2fdad43e23f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/5fb51e422027d7e73eb9bdc4943ec07ce47884ba/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/24197d3c34c21fec56a02ec9c1127c44d042f7d2/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/f7e75ccd1b0c6a4943f2c11c5a543688dedd64b2/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/10ab2806de97c5afe3107006c66b3807e2627704/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/b074280c75227e597ff75682bdc67679f28f583d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/8e6b846340222c1298e8c5e943b43b8b2221f85f/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/a672d91c0c4899a40fb197c560d126c898a70525/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/770fba5c3ecb23f05ef66745145ab4a5d93c78d5/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/d0546c2cba6be744a7b5d0966eac5b8a7ca045e9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/bf610f22db98cc9fb45e401d08a842f5a35c8e6d/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cf771c20ad750e9c28c5cabe3a3c293e/raw/0b3e381257cb2d06ede6fe788a4e20defcb90311/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/sm/cma/cma_ep.c [hunk 10]
```diff
@@ -41,6 +41,38 @@ UCS_CLASS_DEFINE_DELETE_FUNC(uct_cma_ep_t, uct_ep_t);
...
+static UCS_F_ALWAYS_INLINE
+ucs_status_t uct_cma_ep_do_zcopy(uct_cma_ep_t *ep, struct iovec *local_iov,
+                                 size_t local_iov_cnt, struct iovec *remote_iov,
+                                 ssize_t (*fn_p)(pid_t,
+                                                 const struct iovec *,
+                                                 unsigned long,
+                                                 const struct iovec *,
+                                                 unsigned long,
+                                                 unsigned long),
+                                 char *fn_name)
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/sm/cma/cma_ep.c]: done

File: src/uct/sm/cma/cma_ep.c [hunk 11]
```diff
@@ -41,6 +41,38 @@ UCS_CLASS_DEFINE_DELETE_FUNC(uct_cma_ep_t, uct_ep_t);
...
+                   local_iov_cnt - local_iov_idx, remote_iov, 1, 0);
+        if (ucs_unlikely(ret < 0)) {
+            ucs_error("%s(pid=%d length=%zu) returned %zd: %m",
+                      fn_name, ep->remote_pid, remote_iov->iov_len, ret);
+            return UCS_ERR_IO_ERROR;
+        }
+
+        ucs_iov_advance(local_iov, local_iov_cnt, &local_iov_idx, ret);
+        ucs_assert(ret <= remote_iov->iov_len);
+        remote_iov->iov_len  -= ret;
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/sm/cma/cma_ep.c]: done

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12290/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/f05e98b20fc913604016c5119ea0c5c74603a963/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/dfe01b7a5ebfcd9912e0f8c475a4e9a280bcffa5/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/70f0369359796dda1252eb89f4e6f8068673634d/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/7c4b49e2402b096c3e195f3d9e210c0e431e4ec5/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/1d7f84be951ebd71348c1901f06befcb898b0ad8/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/6f9c92607c7eadc60bc04512ee1be827aea84e6a/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/f63f0991f73a51e3e22262825ba8c1113dedf309/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/fcb9885b43a24c3fa6b52f7f19d00540bcaa6871/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/a7998c3fe5b8a5f0c8721a296eff0cfe7d4fc1ba/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/978f2710f9004bc5267ff00502333ce9f6f312b3/hpc-test-althca_W0) | :question: ABORTED
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/70faf36a8f060970ae45529bf523f588ecb6ae39/hpc-test-althca_W1) | :question: ABORTED
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/2150b3d94350c003501b38ffa01b48976dccf65e/hpc-test-althca_W2) | :question: ABORTED
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/9c296fe25c043c017cd551f2c8332167db9a3e3f/hpc-test-althca_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/0558147706bd0092f34bdd9e2df3972779c387a0/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/c95f68e1b85f538c1398aa137fcfc57ea446e874/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/b520f6a7168072e20bb254e50fb5de732224afb1/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/6ef402431308af87cdfd4074e285a058eac226d3/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/6b11d0b972e8a1220dec9d7e58a841f2603dd86c/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/dbe3c2b1ed67d13a42dd03be73f912fd4cc96317/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/3bd45d600ff1422384240520964aa4a09543c222/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/d5c2bbc619b20fc6118bc62a62b2078cb21dc4f5/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/99bcf8a83004424a7d02a0ef04e197ac690e144c/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/2b16a9758df1903bce70ef92807f491ac46ea6f0/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/1afa5f205801f67102ef751aec5f73be3df84a38/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/03dd909f304244f3e40f00771704a7216f768da2/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/20723b8eb1aedbb037eaa6d353c2d6b511f47fd5/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/6875a6e13e3f5a401c38b059bb2bbf9b92b85b95/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/badb4d6fdb647930170cbc3b1d74553c0cfae282/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3c82ddc2199b6cbcf5079ffc2c1734b/raw/5337210ad9c8b5d17d72765b9029a4d09b77a077/r-vmb-ppc-jenkins_W3) | :question: ABORTED

**Comment by dmitrygx** [comment]
@yosefe could you review the last commit? It updates `ucs_iov_advance`

File: src/uct/sm/cma/cma_ep.c [hunk 12]
```diff
@@ -53,69 +82,40 @@ ucs_status_t uct_cma_ep_common_zcopy(uct_ep_h tl_ep,
...
         }
 
-        delivered += ret;
-    } while (delivered < length);
+        remote_iov.iov_len = length;
+
+        status = uct_cma_ep_do_zcopy(ep, local_iov, local_iov_cnt,
+                                     &remote_iov, fn_p, fn_name);
+        if (ucs_unlikely(status != UCS_OK)) {
+            return UCS_OK;
```
Comment (brminich) [inline src/uct/sm/cma/cma_ep.c]: why `return UCS_OK`?

Comment (dmitrygx) [reply src/uct/sm/cma/cma_ep.c]: fixed

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12294/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/720c1560507fef90abd4bf4cca085c9785df4f9e/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/5b65d08b84a4b82f46fb4a19fb00b64ee964cc8e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/f6a63276606dd656f330cca9a831a4f02c62e5e1/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/0309920e63d758472fbf37b74a0359159016103a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/e53415a0d3dcda4d44fdd3ab2f4c0fe8d029824d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/6c0e8bd625c8ff49cf83cfa1184d08166ce90cd2/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/71db4fdb348a6b934eab6b00095267855c0605ce/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/a681a9c61e1f6a598a70b742ef6beb68464999e3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/a5df4d35b880ad0951bebaf256389b4a0c39f8e7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/334913ff9bc9d90f2319b527f6a6eb50a19d4f56/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/d18d0d87a65c71b15a4019dffd951931b56e67c7/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/b7e090ce33fc687854c45e04e1b8f74b1ac28361/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/c5676da2890d0a0ce995be5a663716908326bc8e/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/3d899d4fae7757e7cbafce90de358f8bedc01bbc/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/1bc1bd224d29dcb11c1c308f1d16bdd66c724bfb/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/3caba90bdba9ae7a3af7f70767301c359600868d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/5e222352803e3c9d1619d3f4975fa2e0ec2022e8/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/9a1069f580707b754b402ce173b398e33fac7d59/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/6adeef39af63af304a44440de395f903753a12eb/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/bddef988930796fae08628cfe86ac194e87b38b0/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/b2ca521d9a0a1e83eba580b5f410848231ced7e2/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/f9acdf275c7e5fdade982326d3cb1e971a861e60/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/fe85d39dc1aa6fa8c8753d2829aedee6a955ab63/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/26e82d651493ea4f147ebfe59938df59c13c08e9/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/8f5dcc72d8d5464ce0864592a6af8886bb0386b9/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/113c51ca2f382ff7f36ac724ba5be4f34f2b764d/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/366b344611eae7bdcab622aa5d8401707d7b8f79/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/076f6ecfffd53418231d9c188194a7715cd5ccfb/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cfe7aa73fead6666804267ee61de3aea/raw/bb82b488c27096b85cf1a7d862c54e2c94069d77/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12301/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/42aea05588f3b98d3c1f9dc756d0f80880aa89b0/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/2daf648e20609b42d7b50e339523f876846b4ff5/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/cba568fac9e98e81fcf48ce1d043e3b4c6bc8002/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/cb3fc1fd288d6b6c021c82a78d92c580d2d425aa/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/50c5be787de0b0698bb426e6be82f20b22deda59/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/30a079b536b2fa6c3222d1729dbea3375d13e9b8/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/a5d8aca09379c5e90d5ca4dcd8ed4afb1accb294/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/8521e6e6ad477ee401fb9b4c90742cd4416a84ec/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/e034728937e4d812825fa7ef300fdb205b18effd/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/7be0c0f3301869b3a712827c5b6779527ea84f0c/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/4532b1b5ded25b746b7b08d1f9c94c73aa9271f5/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/ae5d182fb30057f06a33828953f1a57426866381/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/37d17b9976073bf255e65457e7f62f43651a3ebb/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/f5958b435a1df849d140169db1a7d16c53798759/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/d8de713904fe0aed3e1723003270bc4437af2a6c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/c0a288896f4c90255666374a37081137b6de40a7/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/5765c2cba38c199389f3e3aeaeff60ca66e84c7d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/1f02ea3790dd7d13cb456c9cc6fe83994e12692d/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/73e9789ea579eee4b746b65c8053d78c69e8971b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/1b3e4728e1c67127b3e91b9be4b2bd6f558a5cc4/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/00f5339a60aa154746899b04d9f72a54604d7dd5/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/6553965e30632d41da56bd5132bd31e6fef6f8d0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/24ca02831c9272bdd56286a4668e0d1ae072c7af/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/4e2f059c7d302c4c9658db1dd362b23e46a3d044/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/d85d594d5a2f9e5632000a699661e184a9c14964/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/172eac7fd103f30edca7295399f18878e4628093/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/24a281e8c11f540dc7a0ae40e0b40d63200e4711/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/2b0790eefa4961c2399daac712fe3fc7cc46b606/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/253be4ec2e437311332c93b838cfc770/raw/c31e212d0fac67b34843040a9160d99b144d016e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
bot:pipe;retest

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

File: src/uct/sm/cma/cma_ep.c [hunk 13]
```diff
@@ -53,69 +82,40 @@ ucs_status_t uct_cma_ep_common_zcopy(uct_ep_h tl_ep,
...
-
-            local_iov[local_iov_it].iov_base = (void *)((char *)iov[iov_it].buffer +
-                                                        iov_slice_delivered);
-            local_iov[local_iov_it].iov_len  = iov_slice_length - iov_slice_delivered;
-            ++local_iov_it;
-        }
-        if (!delivered) {
-            length = iov_it_length; /* Keep total length of the iov buffers */
-        }
+    remote_iov.iov_base = UCS_PTR_BYTE_OFFSET(remote_addr, 0);
```
Comment (brminich) [inline src/uct/sm/cma/cma_ep.c]: is this to cast to `(void*)` ?

Comment (dmitrygx) [reply src/uct/sm/cma/cma_ep.c]: > is this to cast to `(void*)` ?

yep, I just want to not break @hoopoepg fixes for PGI
