### PR TITLE
Fix wakeup for UD and shared memory transports

### LINKED ISSUE #6304: Hangs in ucx_perftest and wakeup with specific transports
### Describe the bug
This [PR](https://github.com/openucx/ucx/pull/6224) exposed some potential issues with wakeup support. Adding a placeholder issue to track them.

### PR DESCRIPTION
**Pull request by yosefe**
# Why
Fix #6304

# How
* UD: Return correct event count from progress
* SM: Make sure arm() would fail if some endpoints can't send. Since we don't have a method to get notifications about send resource updates from the receiver.
* Re-enable gtests for UD and SM
* Some refactoring in SM transport: improve logging, remove unneeded fields

### CODE REVIEW

File: src/uct/ib/ud/base/ud_iface.c [hunk 1]
```diff
@@ -810,17 +810,21 @@ uct_ud_send_skb_t *uct_ud_iface_ctl_skb_get(uct_ud_iface_t *iface)
     return skb;
 }
 
-void uct_ud_iface_dispatch_async_comps_do(uct_ud_iface_t *iface)
+unsigned uct_ud_iface_dispatch_async_comps_do(uct_ud_iface_t *iface)
 {
     uct_ud_comp_desc_t *cdesc;
     uct_ud_send_skb_t *skb;
+    unsigned count = 0;
```
Comment (dmitrygx) [inline src/uct/ib/ud/base/ud_iface.c:817]: add declaration+initialization at the beginning of the declaration section

File: src/uct/sm/mm/base/mm_ep.c [hunk 2]
```diff
@@ -86,23 +86,25 @@ uct_mm_ep_get_remote_seg(uct_mm_ep_t *ep, uct_mm_seg_id_t seg_id, size_t length,
...
     char dummy = 0;
     int ret;
 
+    ucs_trace("ep %p: signal remote", ep);
+
     for (;;) {
         ret = sendto(iface->signal_fd, &dummy, sizeof(dummy), 0,
-                     (const struct sockaddr*)&ep->signal.sockaddr,
-                     ep->signal.addrlen);
+                     (const struct sockaddr*)&ep->fifo_ctl->signal_sockaddr,
```
Comment (dmitrygx) [inline src/uct/sm/mm/base/mm_ep.c:100]: do you think that it makes sense?
I guess it could additional overhead to get sockaddr from a shared region of memory.
or the idea that syscall adds more overhead than touching memory, right?
IMO this can vary, and better to not rely on this

Comment (yosefe) [reply src/uct/sm/mm/base/mm_ep.c:100]: cost of reading shared variable is negligible compared to syscall and interrupt to remote process to wake it, especially that we already read "head" so it's probably already in sender's cache.

Comment (yosefe) [reply src/uct/sm/mm/base/mm_ep.c:100]: on other hand, removing it from ep structure can reduce cache misses due to smaller memory footprint and simplify the code

Comment (dmitrygx) [reply src/uct/sm/mm/base/mm_ep.c:100]: > especially that we've just read "head" so it's probably already in sender's cache.

ah, makes sense then

Comment (dmitrygx) [reply src/uct/sm/mm/base/mm_ep.c:100]: > on other hand, removing it from ep structure can reduce cache misses due to smaller memory footprint and simplify the code

I see, good catch!

**Review by dmitrygx — APPROVED** [review]

**Comment by yosefe** [comment]
@dmitrygx can you pls look again? there is one more fix in UD

**Review by dmitrygx — APPROVED** [review]

**Comment by yosefe** [comment]
bot:pipe:retest
