### PR TITLE
IB/BASE: Fixes #8595

### LINKED ISSUE #8595: uct_ib_async_event_handler failure prevents from running on AWS machine with TCP transport
### Describe the bug
uct_tcp_iface_connect_handler fails because the handler was allocated non functional verb device.
The issue was discover on AWS instance with EFA nic. Error:
```
./ucx_perftest -c 0 -t ucp_am_bw  xxx
+--------------+--------------+------------------------------+---------------------+-----------------------+
|              |              |       overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+--------------+----------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | 50.0%ile | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+----------+---------+---------+----------+----------+-----------+-----------+
[1664907515.958582] [xxx]           async.c:212  UCX  ERROR async handler uct_ib_async_event_handler() uses id 5, new async handler uct_tcp_iface_connect_handler couldn't use this id
[1664907515.958596] [xxx]           async.c:224  UCX  ERROR Cannot add async handler uct_tcp_iface_connect_handler() - id range [5..6) is full
[1664907515.958689] [xxx]    perftest_run.c:334  UCX  ERROR Failed to run test: Element already exists
```

### Steps to Reproduce
Master ucx build with configure-release/configure-debug on a machine with EFA driver installed.
Current workaround is to rebuild UCX with `--without-verbs --without-rdmacm` . UCX_TLS=tcp does not solve this problem since md open is called anyways.  Since we know that EFA does not implement full verbs, it will be better to skip the NIC and prevent failure in TCP TL.

### PR DESCRIPTION
**Pull request by shamisp**
## What
The code prevents MD to create PD if the underlying transport is not supported by UCX.

## Why ?
Fixes #8595

## How ?
If the verbs transport layer is not ethernet, roce, or IB - skip the device

### CODE REVIEW

File: src/uct/ib/base/ib_device.c [hunk 1]
```diff
@@ -629,11 +629,37 @@ ucs_status_t uct_ib_device_query(uct_ib_device_t *dev,
...
+
 ucs_status_t uct_ib_device_init(uct_ib_device_t *dev,
                                 struct ibv_device *ibv_device, int async_events
                                 UCS_STATS_ARG(ucs_stats_node_t *stats_parent))
 {
     ucs_status_t status;
+    uint8_t port_num;
+    uint8_t usable_port_cnt = 0;
+
+    if (uct_ib_device_is_iwarp(dev)) {
```
Comment (yosefe) [inline src/uct/ib/base/ib_device.c:645]: IMO we should modify https://github.com/openucx/ucx/blob/a767face90f883dc3de61a9b275bc82b42dacda4/src/uct/ib/base/ib_device.c#L777-L787

1. move uct_ib_device_is_iwarp() from uct_ib_device_port_check to https://github.com/openucx/ucx/blob/ee5fa05ac5fdcacda190ec6f95a2c00475e6008d/src/uct/ib/base/ib_md.c#L1345
2. check that port is RoCE or IB in https://github.com/openucx/ucx/blob/a767face90f883dc3de61a9b275bc82b42dacda4/src/uct/ib/base/ib_device.c#L783

Comment (shamisp) [reply src/uct/ib/base/ib_device.c:645]: I agree that the solution does not look super clean. The logic between MD creating and the rest of the code is not unified. I was really puzzled when I went through the code.

Comment (shamisp) [reply src/uct/ib/base/ib_device.c:645]: @yosefe I implemented what you suggested and it does not look good.
1 - Will work but ...
2 - It is not going to work because `uct_ib_device_port_check` that you referenced is invoked after MD creation, which too late.

Just addressing #1 is possible but then you only execute the iwarp part of the check in `uct_ib_device_is_accessible` and the second half (not roce or IB) in uct_ib_device_init which makes code much more complex to understand. Essentially the logical check "not verbs compliant device that has verbs" gets spread over different places. IMHO current implementation is more reasonable.

**Comment by yosefe** [comment]
@shamisp does https://github.com/openucx/ucx/pull/8466 fix the issue?

**Comment by shamisp** [comment]
I will take a look but IMHO what I proposed here is cleaner - we should not create these MD all together.

**Comment by shamisp** [comment]
@yosefe #8466 fixes ucx_perftest run but with my patch I see less failures in gtest
with this patch:
```
[----------] Global test environment tear-down
[==========] 11097 tests from 500 test suites ran. (1752337 ms total)
[  PASSED  ] 11067 tests.
[  FAILED  ] 30 tests, listed below:
[  FAILED  ] test_uct_ib_sl_utils.query_ooo_sl_mask, where TypeParam =  and GetParam() = 
[  FAILED  ] ib/test_md.rkey_ptr/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.alloc/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.mem_type_detect_mds/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.mem_query/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.sys_device/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_perf/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_advise/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.alloc_advise/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_multi_thread/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.sockaddr_accessibility/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.invalidate/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_bad_arg/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.dereg_bad_arg/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.exported_mkey/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md_fork.fork/0, where GetParam() = rdmap0s6
[  FAILED  ] alloc_methods/test_mem.md_alloc/0, where GetParam() = 0
[  FAILED  ] alloc_methods/test_mem.md_alloc/1, where GetParam() = 2
[  FAILED  ] alloc_methods/test_mem.md_alloc/2, where GetParam() = 3
[  FAILED  ] alloc_methods/test_mem.md_alloc/3, where GetParam() = 4
[  FAILED  ] alloc_methods/test_mem.md_fixed/0, where GetParam() = 0
[  FAILED  ] alloc_methods/test_mem.md_fixed/1, where GetParam() = 2
[  FAILED  ] alloc_methods/test_mem.md_fixed/2, where GetParam() = 3
[  FAILED  ] alloc_methods/test_mem.md_fixed/3, where GetParam() = 4
[  FAILED  ] ib/test_ib_md.ib_md_umr_rcache/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.ib_md_umr_direct/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.ib_md_umr_ksm/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.relaxed_order/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.aligned/0, where GetParam() = rdmap0s6
```

with #8466 only
```
[----------] Global test environment tear-down
[==========] 11097 tests from 500 test suites ran. (1728054 ms total)
[  PASSED  ] 11065 tests.
[  FAILED  ] 32 tests, listed below:
[  FAILED  ] test_uct_ib_sl_utils.query_ooo_sl_mask, where TypeParam =  and GetParam() = 
[  FAILED  ] ib/test_md.rkey_ptr/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.alloc/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.mem_type_detect_mds/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.mem_query/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.sys_device/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_perf/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_advise/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.alloc_advise/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_multi_thread/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.sockaddr_accessibility/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.invalidate/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_bad_arg/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.dereg_bad_arg/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.exported_mkey/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md_fork.fork/0, where GetParam() = rdmap0s6
[  FAILED  ] alloc_methods/test_mem.md_alloc/0, where GetParam() = 0
[  FAILED  ] alloc_methods/test_mem.md_alloc/1, where GetParam() = 2
[  FAILED  ] alloc_methods/test_mem.md_alloc/2, where GetParam() = 3
[  FAILED  ] alloc_methods/test_mem.md_alloc/3, where GetParam() = 4
[  FAILED  ] alloc_methods/test_mem.md_fixed/0, where GetParam() = 0
[  FAILED  ] alloc_methods/test_mem.md_fixed/1, where GetParam() = 2
[  FAILED  ] alloc_methods/test_mem.md_fixed/2, where GetParam() = 3
[  FAILED  ] alloc_methods/test_mem.md_fixed/3, where GetParam() = 4
[  FAILED  ] cma/test_uct_perf.envelope/0, where GetParam() = cma/memory
[  FAILED  ] cma/test_uct_loopback.envelope/0, where GetParam() = cma/memory
[  FAILED  ] ib/test_ib_md.ib_md_umr_rcache/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.ib_md_umr_direct/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.ib_md_umr_ksm/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.relaxed_order/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.aligned/0, where GetParam() = rdmap0s6
```

**Comment by dmitrygx** [comment]
I see the difference:
```
[  FAILED  ] cma/test_uct_perf.envelope/0, where GetParam() = cma/memory
[  FAILED  ] cma/test_uct_loopback.envelope/0, where GetParam() = cma/memory
```
these failures couldn't be related to https://github.com/openucx/ucx/pull/8466

File: src/uct/ib/base/ib_device.c (hunk 1 above)
Comment (yosefe) [reply src/uct/ib/base/ib_device.c:645]: we are checking the port type after creating the md because in case some ports are supported and some are not, it makes more sense to disable only the unsupported ports and not the entire device.
if the device does not have any supported ports we would eventually close the md anyway.

**Comment by shamisp** [comment]
@dmitrygx I applied this patch on top of your patch and I don't see these two errors.
Probably some other leaks that is not covered by your original patch:
```
[  PASSED  ] 11067 tests.
[  FAILED  ] 30 tests, listed below:
[  FAILED  ] test_uct_ib_sl_utils.query_ooo_sl_mask, where TypeParam =  and GetParam() = 
[  FAILED  ] ib/test_md.rkey_ptr/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.alloc/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.mem_type_detect_mds/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.mem_query/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.sys_device/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_perf/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_advise/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.alloc_advise/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_multi_thread/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.sockaddr_accessibility/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.invalidate/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.reg_bad_arg/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.dereg_bad_arg/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md.exported_mkey/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_md_fork.fork/0, where GetParam() = rdmap0s6
[  FAILED  ] alloc_methods/test_mem.md_alloc/0, where GetParam() = 0
[  FAILED  ] alloc_methods/test_mem.md_alloc/1, where GetParam() = 2
[  FAILED  ] alloc_methods/test_mem.md_alloc/2, where GetParam() = 3
[  FAILED  ] alloc_methods/test_mem.md_alloc/3, where GetParam() = 4
[  FAILED  ] alloc_methods/test_mem.md_fixed/0, where GetParam() = 0
[  FAILED  ] alloc_methods/test_mem.md_fixed/1, where GetParam() = 2
[  FAILED  ] alloc_methods/test_mem.md_fixed/2, where GetParam() = 3
[  FAILED  ] alloc_methods/test_mem.md_fixed/3, where GetParam() = 4
[  FAILED  ] ib/test_ib_md.ib_md_umr_rcache/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.ib_md_umr_direct/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.ib_md_umr_ksm/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.relaxed_order/0, where GetParam() = rdmap0s6
[  FAILED  ] ib/test_ib_md.aligned/0, where GetParam() = rdmap0s6
```

File: src/uct/ib/base/ib_device.c (hunk 1 above)
Comment (yosefe) [reply src/uct/ib/base/ib_device.c:645]: > @yosefe I understand why you are checking port by port and the patch is doing the same in much earlier stage so we don't create MD for "non-verbs" devices.

@shamisp what is the reason we must avoid creating such MD?

Comment (shamisp) [reply src/uct/ib/base/ib_device.c:645]: @yosefe Because the TL does not work on transport layers other than `IBV_TRANSPORT_IB`, which cover both ROCE and IB.
We know that  IBV_TRANSPORT_USNIC, IBV_TRANSPORT_USNIC_UDP, and IBV_TRANSPORT_UNSPECIFIED. So, why to enable and then cause failures and leaks when on such systems only TCP has to be used in default mode.

Comment (yosefe) [reply src/uct/ib/base/ib_device.c:645]: LGTM

File: src/uct/ib/base/ib_md.c [hunk 2]
```diff
@@ -1230,6 +1230,36 @@ static uct_md_ops_t UCS_V_UNUSED uct_ib_md_global_odp_ops = {
...
+            return "Unknown";
+    }
+}
+
+static int uct_ib_device_is_supported(struct ibv_device *device)
+{
+    /* TODO: enable additional transport types when ready */
+    int ret = device->transport_type == IBV_TRANSPORT_IB;
+    if (!ret) {
+        ucs_debug("Device %s of type %s is not supported",
```
Comment (yosefe) [inline src/uct/ib/base/ib_md.c:1256]: small case (Device->device)

**Comment by shamisp** [comment]
@yosefe It seems there are pre-2014 rdma-core builds that don't have post 2014 defines.
```
/__w/1/s/contrib/../src/uct/ib/base/ib_md.c: In function 'uct_ib_device_transport_to_name':
/__w/1/s/contrib/../src/uct/ib/base/ib_md.c:1294:14: error: 'IBV_TRANSPORT_USNIC' undeclared (first use in this function)
         case IBV_TRANSPORT_USNIC:
              ^
/__w/1/s/contrib/../src/uct/ib/base/ib_md.c:1294:14: note: each undeclared identifier is reported only once for each function it appears in
/__w/1/s/contrib/../src/uct/ib/base/ib_md.c:1296:14: error: 'IBV_TRANSPORT_USNIC_UDP' undeclared (first use in this function)
         case IBV_TRANSPORT_USNIC_UDP:
              ^
/__w/1/s/contrib/../src/uct/ib/base/ib_md.c:1298:14: error: 'IBV_TRANSPORT_UNSPECIFIED' undeclared (first use in this function)
         case IBV_TRANSPORT_UNSPECIFIED:
              ^
```

To workaround this, instead of introducing bunch of m4 config scripts I'm thinking to go with numerical values. These are not expected to change. What do you thing ?

File: src/uct/ib/base/ib_md.c [hunk 3]
```diff
@@ -1230,6 +1230,36 @@ static uct_md_ops_t UCS_V_UNUSED uct_ib_md_global_odp_ops = {
     .detect_memory_type = ucs_empty_function_return_unsupported,
 };
 
+static const char *uct_ib_device_transport_to_name(struct ibv_device *device)
+{
+    switch (device->transport_type) {
+        case IBV_TRANSPORT_IB:
```
[the remark this answers is not in the document]
Comment (shamisp) [reply src/uct/ib/base/ib_md.c:1236]: kk

File: src/uct/ib/base/ib_md.c [hunk 4]
```diff
@@ -1230,6 +1230,36 @@ static uct_md_ops_t UCS_V_UNUSED uct_ib_md_global_odp_ops = {
...
+        case IBV_TRANSPORT_USNIC_UDP:
+            return "usNIC UDP";
+        case IBV_TRANSPORT_UNSPECIFIED:
+            return "Unspecified";
+        default:
+            return "Unknown";
+    }
+}
+
+static int uct_ib_device_is_supported(struct ibv_device *device)
```
[the remark this answers is not in the document]
Comment (shamisp) [reply src/uct/ib/base/ib_md.c:1251]: IMO stand alone static functions look cleaner and makes code easier to read.

**Review by yosefe — DISMISSED** [review]
pls squash

**Comment by shamisp** [comment]
> pls squash

done

**Review by yosefe — APPROVED** [review]
