### PR TITLE
GTEST/UCT/DC: Fix DC flow control test

### LINKED ISSUE #2263: failure in dc/test_dc_flow_control.flush_destroy/0
```
18:48:32 [ RUN      ] dc/test_dc_flow_control.flush_destroy/0
18:48:32 /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/uct/ib/test_dc.cc:429: Failure
18:48:32 Value of: _status
18:48:32   Actual: -2
18:48:32 Expected: UCS_OK
18:48:32 Which is: 0
18:48:32 Error: No resources are available to initiate the operation
18:48:32 [vulcan-jenkins:9099 :0:9099]       dc_ep.h:169  Assertion `( ((iface->tx.dcis[dci].flags) & ((UCT_DC_DCI_FLAG_EP_CANCELED | UCT_DC_DCI_FLAG_EP_DESTROYED))) == ((UCT_DC_DCI_FLAG_EP_CANCELED | UCT_DC_DCI_FLAG_EP_DESTROYED)) )' failed
18:48:33 
18:48:33 /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../src/uct/ib/dc/base/dc_ep.h: [ uct_dc_iface_dci_put_dcs() ]
18:48:33       ...
18:48:33       164         if (ep == NULL) {
18:48:33       165             /* The EP was destroyed after flush cancel */
18:48:33       166             ucs_assert(ucs_test_all_flags(iface->tx.dcis[dci].flags,
18:48:33 ==>   167                                           (UCT_DC_DCI_FLAG_EP_CANCELED |
18:48:33       168                                            UCT_DC_DCI_FLAG_EP_DESTROYED)));
18:48:33       169             return;
18:48:33       170         }
18:48:33 
18:48:34 ==== backtrace ====
18:48:34  0 0x0000000000068e37 uct_dc_iface_dci_put_dcs()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../src/uct/ib/dc/base/dc_ep.h:167
18:48:34  1 0x000000000052efba uct_test::short_progress_loop()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../src/ucs/datastruct/callbackq.h:208
18:48:34  2 0x00000000007421ef uct_test::wait_for_flag<unsigned int>()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/uct/uct_test.h:190
18:48:34  3 0x000000000074b3a6 test_dc_flow_control_flush_destroy_Test::test_body()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/uct/ib/test_dc.cc:436
18:48:34  4 0x0000000000479db6 ucs::test_base::run()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/common/test.cc:246
18:48:34  5 0x000000000046de43 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/common/gtest-all.cc:3562
18:48:34  6 0x00000000004622bd testing::Test::Run()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/common/gtest-all.cc:3635
18:48:34  7 0x000000000046238c testing::TestInfo::Run()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/common/gtest-all.cc:3812
18:48:34  8 0x00000000004624ef testing::TestCase::Run()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/common/gtest-all.cc:3930
18:48:34  9 0x0000000000466e87 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/common/gtest-all.cc:5802
18:48:34 10 0x000000000046718b testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/common/gtest-all.cc:5719
18:48:34 11 0x000000000040f8a3 main()  /scrap/jenkins/workspace/hpc-ucx-pr-4/label/vulcan-jenkins/worker/3/contrib/../test/gtest/common/gtest.h:20059
18:48:34 12 0x0000000000021c05 __libc_start_main()  ???:0
18:48:34 13 0x000000000044ca48 _start()  ???:0
18:48:34 ===================
```

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6150/label=vulcan-jenkins,worker=3/console

### PR DESCRIPTION
**Pull request by brminich**
- Need to make sure that ep_flush returns OK, before to destroy ep
- Removed misleading comment from uct_dc_ep_flush

fixes #2263

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6330/ for details (Mellanox internal link).

**Comment by brminich** [comment]
failure is #2336

**Comment by brminich** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6332/ for details (Mellanox internal link).

**Comment by brminich** [comment]
failure is #2339

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6344/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@hoopoepg

**Comment by brminich** [comment]
@yosefe, pls check

File: test/gtest/uct/ib/test_dc.cc [hunk 1]
```diff
@@ -448,10 +448,13 @@ UCS_TEST_P(test_dc_flow_control, soft_request)
     EXPECT_EQ(get_fc_ptr(m_e1)->fc_wnd, s_thresh - 1);
 }
 
-/* Check that flush returns UCS_OK even if there is an outgoing grant request */
+/* Check that:
+ * 1) flush returns UCS_OK even if there is an outgoing grant request
+ * 2) No crash when grant for destroyed ep arrives */
```
Comment (yosefe) [inline test/gtest/uct/ib/test_dc.cc]: how is this checked?

File: test/gtest/uct/ib/test_dc.cc [hunk 2]
```diff
@@ -448,10 +448,13 @@ UCS_TEST_P(test_dc_flow_control, soft_request)
     EXPECT_EQ(get_fc_ptr(m_e1)->fc_wnd, s_thresh - 1);
 }
 
-/* Check that flush returns UCS_OK even if there is an outgoing grant request */
+/* Check that:
+ * 1) flush returns UCS_OK even if there is an outgoing grant request
```
Comment (yosefe) [inline test/gtest/uct/ib/test_dc.cc]: how is this tested?

Comment (brminich) [reply test/gtest/uct/ib/test_dc.cc]: we send the whole window of messages which means that grant request was sent as well.
Then we perform a flush and check its return status. Need to do that in a loop, because we may not poll all send completions before the first poll call.

File: test/gtest/uct/ib/test_dc.cc (hunk 1 above)
Comment (brminich) [reply test/gtest/uct/ib/test_dc.cc]: we enable m_e2 entity and send a bunch of messages to m_e1 (which means that grant was sent back as well).
Grant is handled by m_e1, because we check that the last message from m_e2 is handled (checking the counter, which is increased in am callback)

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6353/ for details (Mellanox internal link).
