### PR TITLE
BINDINGS/GO: Fix memory leak for C allocated mem.

### LINKED ISSUE #7422: Possible cgo memory leak in golang binding
### Describe the bug
The functions `SetName` in `UcpParams, UcpEpParams, UcpWorkerParams` call the `C.CString`, which  allocates the c memory, which does not get freed in the current code base.

In addition, using the `runtime.SetFinalizer` might still incur memory leak, if `SetSocketAddress` are called twice for any reason.

As a result, does the development team think the introduction of a `Release` function which release memory a good idea. A possible pattern will be like:
```
ucpParams := &UcpParams{}
ucpParams.SetName("hello")
defer ucpParams.Release()
```

with an example implementation:

```
// Tracing and analysis tools can identify the context using this name.
func (p *UcpParams) SetName(name string) *UcpParams {
	FreeNativeMemory(unsafe.Pointer(p.params.name)) // force free existing memory, if not nil
	p.params.name = C.CString(name)
	p.params.field_mask |= C.UCP_PARAM_FIELD_NAME
	return p
}

// Release any resources allocated in the C space
func (p *UcpParams) Release() *UcpParams {
	FreeNativeMemory(unsafe.Pointer(p.params.name))
	return p
}
```

Really appreciate this port.

### Steps to Reproduce
Not applicable.

### Setup and versions
Not applicable.

### Additional information (depending on the issue)
Not applicable.

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
Prevent memory leak in C allocated memory. Checks if the memory is set - free it, and sets finalizer for all C allocated objects

Tested by adding loggers to finalizers and if statements. 

## Why ?
Fixes #7422

### CODE REVIEW

File: bindings/go/src/ucx/context_params.go [hunk 1]
```diff
@@ -55,7 +59,13 @@ func (p *UcpParams) SetEstimatedNumPPN(estimatedNumPPN uint64) *UcpParams {
 
 // Tracing and analysis tools can identify the context using this name.
 func (p *UcpParams) SetName(name string) *UcpParams {
+	if p.params.name != nil {
+		runtime.SetFinalizer(p, nil)
+		FreeNativeMemory(unsafe.Pointer(p.params.name))
+	}
```
Comment (yosefe) [inline bindings/go/src/ucx/context_params.go:65]: 1. where was this memory allocated?
2. maybe add common function for this logic?

Comment (petro-rudenko) [reply bindings/go/src/ucx/context_params.go:65]: 1. `p.params.name = C.CString(name)`
> // Go string to C string
// The C string is allocated in the C heap using malloc.
// It is the caller's responsibility to arrange for it to be
// freed, such as by calling C.free (be sure to include stdlib.h
// if C.free is needed).
func C.CString(string) *C.char
2. Ok

Comment (petro-rudenko) [reply bindings/go/src/ucx/context_params.go:65]: This if is for cases where params are reused:
```
ucpParams.SetName("Context1")
...
ucpParams.SetName("Context2")
```

**Review by yosefe — APPROVED** [review]
