### PR TITLE
UCP/WORKER: Select device atomics if there is a scalable device

### LINKED ISSUE #4199: [mtt] atomic tests fails in oshmem_test
Configuration
```
OMPI: 4.0.2rc2
MOFED: MLNX_OFED_LINUX-4.6-1.0.1.1
Module: hpcx-gcc (2019-09-16)
Test module: none
Nodes: orion x22 (ppn=28(x22), nodelist=clx-orion-[036-039,052-053,055-062,065-067,072,075,079,088-089])
```

MTT log: http://e2e-gw.mellanox.com:4080/hpc/scrap/users/mtt/scratch/shmem/20190917_002501_27577_460954_clx-orion-036/html/test_stdout_MXsFM2.txt

Details:
- Reproduces with and without HCOLL
- Reproduces with and without `UCX_UNIFIED_MODE`
- Passes with np=256

Cmd:
`oshrun -np 257 --bind-to core -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -mca coll_hcoll_enable 0 -mca coll ^hcoll -x HCOLL_POLLING_LEVEL=1 -x HCOLL_ENABLE_MCAST_ALL=0 -x HCOLL_BCOL=basesmuma,ucx_p2p -x HCOLL_SBGP=basesmsocket,p2p -mca spml ucx -mca pml ucx -x UCX_TLS=rc_x,self,sm -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_UNIFIED_MODE=n --map-by node -x SHMEM_SYMMETRIC_HEAP_SIZE=5708M /hpc/scrap/users/mtt/scratch/shmem/20190917_002501_27577_460954_clx-orion-036/installs/i00w/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=atomic`

Output:
```sh
OpenSHMEM Verification Tool ver."1.2.76"
**********************************
* Log file: none
* Host: clx-orion-036
* Output level: 4
* Log level: 0
**********************************
FAIL   atomic     int_swap       shmem_int_swap(): A simple test.
FAIL   atomic     long_swap      shmem_long_swap(): A simple test.
PASS   atomic     swap           shmem_swap(): A simple test.
FAIL   atomic     longlong_swap  shmem_longlong_swap(): A simple test.
FAIL   atomic     float_swap     shmem_float_swap(): A simple test.
FAIL   atomic     double_swap    shmem_double_swap(): A simple test.PASS   atomic     int_cswap      shmem_int_cswap(): A simple test.
PASS   atomic     long_cswap     shmem_long_cswap(): A simple test.
PASS   atomic     longlong_cswap shmem_longlong_cswap(): A simple test.
FAIL   atomic     int_fadd       shmem_int_fadd(): A simple test.
FAIL   atomic     long_fadd      shmem_long_fadd(): A simple test.
FAIL   atomic     longlong_fadd  shmem_longlong_fadd(): A simple test.
FAIL   atomic     int_finc       shmem_int_finc(): A simple test.
FAIL   atomic     long_finc      shmem_long_finc(): A simple test.
FAIL   atomic     longlong_finc  shmem_longlong_finc(): A simple test.
FAIL   atomic     int_add        shmem_int_add(): A simple test.
FAIL   atomic     long_add       shmem_long_add(): A simple test.
FAIL   atomic     longlong_add   shmem_longlong_add(): A simple test.
FAIL   atomic     int_inc        shmem_int_inc(): A simple test.
FAIL   atomic     long_inc       shmem_long_inc(): A simple test.
FAIL   atomic     longlong_inc   shmem_longlong_inc(): A simple test.

node=clx-orion-036, pid=18130:
Thread 4 (Thread 0x7ffff52e5700 (LWP 18155)):
#0  0x00007ffff64bb113 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff7b484b3 in epoll_dispatch (base=0x1da4e90, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff7b4bf00 in opal_libevent2022_event_base_loop (base=0x1da4e90, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff7b06a5e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007ffff6790dd5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff64bab3d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7ffff22f2700 (LWP 18172)):
#0  0x00007ffff64bb113 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007ffff7b484b3 in epoll_dispatch (base=0x1dff240, tv=<optimized out>) at epoll.c:407
#2  0x00007ffff7b4bf00 in opal_libevent2022_event_base_loop (base=0x1dff240, flags=flags@entry=1) at event.c:1630
#3  0x00007ffff442ff3e in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:232
#4  0x00007ffff6790dd5 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007ffff64bab3d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7fffe15cd700 (LWP 18290)):
#0  0x00007ffff64bb113 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007fffeae6941c in ucs_event_set_wait (event_set=<optimized out>, num_events=num_events@entry=0x7fffe15ccec0, timeout_ms=<optimized out>, event_set_handler=event_set_handler@entry=0x7fffeae56570 <ucs_async_thread_ev_handler>, arg=arg@entry=0x7fffe15cced0) at sys/event_set.c:196
#2  0x00007fffeae5692a in ucs_async_thread_func (arg=0x1f1dfa0) at async/thread.c:127
#3  0x00007ffff6790dd5 in start_thread () from /usr/lib64/libpthread.so.0
#4  0x00007ffff64bab3d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7ffff7fcd740 (LWP 18130)):
#0  0x00007fffeb17ac43 in uct_mm_iface_poll_fifo (iface=0x351a970) at sm/mm/base/mm_iface.c:237
#1  uct_mm_iface_progress (arg=0x351a970) at sm/mm/base/mm_iface.c:278
#2  0x00007fffeb3b0d32 in ucs_callbackq_dispatch (cbq=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/callbackq.h:211
#3  uct_worker_progress (worker=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/api/uct.h:2203
#4  ucp_worker_progress (worker=0x7fffb7a45010) at core/ucp_worker.c:1892
#5  0x00007fffb7ec64e3 in spml_ucx_default_progress () at spml_ucx_component.c:151
#6  0x00007ffff7b00bdc in opal_progress () at runtime/opal_progress.c:231
#7  0x00007fffe32df12c in hcoll_ml_progress_impl () from /hpc/local/benchmarks/daily/next/2019-09-16/hpcx-gcc-redhat7.4/hcoll/lib/libhcoll.so.1
#8  0x00007fffe32c6e32 in hmca_coll_ml_barrier_intra () from /hpc/local/benchmarks/daily/next/2019-09-16/hpcx-gcc-redhat7.4/hcoll/lib/libhcoll.so.1
#9  0x00007fffe35db23a in mca_coll_hcoll_barrier (comm=0x3615610, module=0x3aa1a60) at coll_hcoll_ops.c:29
#10 0x00007fffb7ab6153 in mca_scoll_mpi_barrier (group=0x351b4c0, pSync=0xff000010, alg=<optimized out>) at scoll_mpi_ops.c:25
#11 0x00007ffff6cf6b6f in pshmem_barrier_all () at pshmem_barrier.c:61
#12 0x00007ffff6cd4290 in _shfree (ptr=ptr@entry=0xff000090) at pshmem_free.c:55
#13 pshfree (ptr=ptr@entry=0xff000090) at pshmem_free.c:39
#14 0x0000000000410c98 in test_item1 () at atomic/osh_atomic_tc22.c:96
#15 osh_atomic_tc22 (node=0x4c0668 <atomic_tcs+1512>, argc=<optimized out>, argv=<optimized out>) at atomic/osh_atomic_tc22.c:43
#16 0x0000000000406a49 in __do_exec (node=0x4bef90 <osh_modes+144>, argv=0x7fffffffb9d0, argc=3, opt_obj=0x1d41080) at osh_exec.c:287
#17 proc_mode_exec (node=0x4bef90 <osh_modes+144>, argc=3, argv=0x7fffffffb9d0) at osh_exec.c:128
#18 0x00000000004056ce in main (argc=4, argv=0x7fffffffb9c8) at osh_main.c:138
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Select device atomics if there is a scalable device. Otherwise, use AMO over AM or CPU atomics (if no Device atomics at all)

## Why ?

Fixes #4199

## How ?

Select only scalable enough TL for Device atomics in `ucp_worker_init_device_atomics`

### CODE REVIEW

**Comment by dmitrygx** [comment]
@Akshay-Venkatesh @evgeny-leksikov could you review 1st commit? it fixes RDMACM and SOCKCM tls that don't inherit UCT base config table. Thanks in advance!

**Comment by Akshay-Venkatesh** [comment]
Is `", " ` the standard way to get base config? If yes, https://github.com/openucx/ucx/commit/867a4321acda4cd4d44a83708a3de165f6206823 looks good.

**Comment by dmitrygx** [comment]
> Is `", " ` the standard way to get base config? If yes, [867a432](https://github.com/openucx/ucx/commit/867a4321acda4cd4d44a83708a3de165f6206823) looks good.

yep, now it reports the following config for SOCKCM
```
#
# sockcm transport configuration
#

#
# The configuration parameter replaced by: UCX_<IB transport>_TX_MIN_INLINE for IB, UCX_MM_FIFO_SIZE for MM
#
# syntax:    N/A
# inherits:  UCX_MAX_SHORT
#
UCX_SOCKCM_MAX_SHORT (deprecated)

#
# The configuration parameter replaced by: UCX_<transport>_SEG_SIZE where <transport> is one of: IB, MM, SELF, TCP
#
# syntax:    N/A
# inherits:  UCX_MAX_BCOPY
#
UCX_SOCKCM_MAX_BCOPY (deprecated)

#
# Priority of methods to allocate intermediate buffers for communication
#
# syntax:    comma-separated list of: [thp|md|heap|mmap|huge]
# inherits:  UCX_ALLOC
#
UCX_SOCKCM_ALLOC=huge,thp,md,mmap,heap

#
# Level of network failure reporting
#
# syntax:    [FATAL|ERROR|WARN|INFO|DEBUG|TRACE|REQ|DATA|ASYNC|FUNC|POLL]
# inherits:  UCX_FAILURE
#
UCX_SOCKCM_FAILURE=ERROR

#
# Maximum number of endpoints that the transport interface is able to create
#
# syntax:    unsigned long: <number>, "inf", or "auto"
# inherits:  UCX_MAX_NUM_EPS
#
UCX_SOCKCM_MAX_NUM_EPS=inf

#
# Maximum number of pending connections for a listening socket.
#
# syntax:    unsigned integer
#
UCX_SOCKCM_BACKLOG=1024
```
instead of :
```
#
# sockcm transport configuration
#

#
# Maximum number of pending connections for a listening socket.
#
# syntax:    unsigned integer
#
UCX_SOCKCM_BACKLOG=1024
```

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12407/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/a7857ab5062ac077924a74fbc459070744c878a5/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/0f6b2a1807c4847caebd99cbe8ecc2b989562855/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/b444d0b2d998722454cad5cba3889b77aab0b775/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/325b4149537bcba5b6944edcdee9d835e0574157/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/f83769dd5f35acaa34652fcfa07fdc1ccf8d8afd/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/e255dd3944d0b16507e9897995176917c37fbab2/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/a0b82f5265dd34fcae15ddbe7c07ca915735beee/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/9d499f78cb9b83e50ec5ac139a97cc92b4a41879/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/7521327ff191166926b412cc4fa89683b6fc1f37/hpc-test-node-gpu_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/e41cf8a5c244b5b270b8a29a81b7644f7f44c43f/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/cbd5666416162304982b8f245f3ead2804d3ca53/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/9126123ec0ab1d7aac94e4c27f900661d09a774f/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/3456979dc66c0e794f91acd205a3b279a30afee2/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/6a08c857c89ac6f85752450ada6ab4bdf94e0267/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/e082465776028da20f801e4c92d3756505317dfa/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/5f12301982c791a04c36ac13cccbaa9c4360cdfe/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/c723a35b0da10bb32b312ec8c74d82778e023f64/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/c06fb377107fd253ad52c48e41a4d941e1804766/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/9530c4777bc13ab629ad679447304d76cb033118/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/cc935ccbc961960031f2c004144950f301ffbfea/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/0fe6364460873174e7c862dfc382f8b0f9dd2892/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/1de0a03ad9f32682f5f6dcd91484611e26ceb089/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/7d9643b985ad712d7879423a16179b0cf482c8cb/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/469050bf2d14ffd00e27db6f9dca9c95f22dbd99/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/970ac2939ecca58d056fd71b5a0a29c5e93710a1/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/a427b9f3c7c5b96e933641d5ff1e37f36118e14e/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/ef0d6d6f2d90acb8db683989580541261ca57a7e/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/d71d6382c2e8e42308ca671faf1ee5b16d5f14de/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e3e15c8ac3b28a158e2259363c62de64/raw/de7ebeca97d9e1f892bca18b5c18ed758757781b/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12410/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 9 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/d71b3d3f627754abefb8889a1f1a06ac7cd0bd6a/_main) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/a377c360c5f7d2dae9aed107b64b84ead28380de/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/f69c3890935b7b9db438d0c4221d9bc42a721895/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/d202ab03f6b1fab143eeaebe868dc0d09f9d9739/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/b6ee3bb3523db530e5e7deb6fd75c3c49a9c8b5c/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/a779330d8935b95a18de6ae613df2918abd3c5f6/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/a3897ed023c1906ac0eaafc80ae9aff043308b2a/hpc-test-node-new_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/2a8e18ebeafcd27330fa044fb00a746380fd8848/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/46c9af66089a544cdc2c0d2381e810ecbcc6187d/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/facbbd3098d4fd8894418d45abe2d593dde7f31b/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/5c95e08d1c90edf723d465b0ded39ef6799e7ea1/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/2eeb50470c32bc6828530e6082c378a1475b023e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/bc9a64853dce3432e23d7247f72140266930108e/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/8773d09c8def83f81eb01c6be6625ac4ff592fd5/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/b9124722b3ee0b971f00bd0dcdde945f02407b63/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/270ab3f1d21562e805b887108c8d039098936f8d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/031d6d8aee0c004c891fff177e93cf5b1cb3d261/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/c0b7926f008d9ad442ad6ba0016c296647b935ea/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/a695c7831d0c07023f1b4c7dcc58a2f42024e68f/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/b72ea471e9ad2d3ff25c57e12144bd5f42eb9a1c/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/f709c18f29a244497157637d2b8120bfacf3dba0/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/2bac3bccaae07ccd231cbad9e480760fc119fe23/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/406f50056bdd516add33352f3e10eb63772e099d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/c430e652d901a2b9acda4d09f706cc2b35b27724/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/e736cb9282822421cda226f93a6cfb8c19ed48b0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/3c0d07e8f465b3e0464fcecfd5c66f2218042198/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/e882bd7cb35c6668d056384224d9729193168424/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/4bbe0e1d545aa35bd51a747f0065ba9f86d4c42a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8f30b12075bcb2c9edaf803407cd0335/raw/3540887bbf75fb00303d20729e51073e1349c89a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
rnat
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12412/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 6 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Sep-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/1daa42f2eef9c2c52a1c3330e2b402c6045598f9/_main) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/c19650bd10c31c90f6576bc7051354195f1ba65c/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/c81dce95e5591257fe6d353dafb3b87c978f41fa/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/b91eae4f55eeea3b6631afdb1bf54f64b5ac9931/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/9364cf4a0d329cacddaec4fbd5334d3f768bb129/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/1ac9fb0459abd5c0f720442a4a17aaf5af956bac/hpc-test-node-new_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/c4d60df124808a36b83702aaa858f470f6259163/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/da62624e49df8bc400f878f1e11e9eb26cd38bf5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/bb592e2efd5522912ca01b8cca2a99911af4762a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/8a647dc2e996a3b44d3ed008f348580796f29ebf/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/889b9cb5b42746de7cb79d4ca66320b90105251a/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/c325ae9d8b98408c722ec0334ec965986b18f46c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/7633f00e6ef4657040a8ae4a14195f0be42ff786/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/c2a0bb3890eeff5a2ea5d9fea1ae1f859a75cc65/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/52231c84a869e7fd3da6e6932cf21db05fb4ff96/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/4c4e2edebbc6d3c3569ea9bda869ddeeb3acd7e0/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/1d207abfc97839810a517a2c3d843926cd9131ec/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/787bf2babd88a1203193070db4e4657b86eda15a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/331098569960673eebce235d1adb68fe1c642234/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/f9132c416313a74a4f5d75ca2eadfc898add598a/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/95582c38a49f19a6ce7ff099279ca50a17434e87/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/d680d492311aba5187d3736bfa903d160fba389c/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/3aad14f0d413ea93b79d808b53414c005cb6df82/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/049b8a917560876ac59c7f12d7208e64626e04f9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/207df221c9d378ac13fedfa563df9af7d0316984/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/3b71ea8b2042cd7b908c558cf814dbd788976913/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/bf48b481568ea9770593f1a5bb90f365332dad85/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/b230c42a843183c29790b00826534a4278204732/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0c4e0770214ae3d0be855d5c7d1b7b0f/raw/1d53f98b2ddd3c87ecf9ad6b588ef05539f8c21b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
```
[2019-09-23T20:47:07.903Z] [ RUN      ] sm_rc/test_ucp_wireup_fallback_amo.different_amo_types/0
[2019-09-23T20:47:07.903Z] [     INFO ] Testing 1 number of EPs
[2019-09-23T20:47:08.159Z] /scrap/jenkins/workspace/ucx-2/contrib/../test/gtest/ucp/test_ucp_wireup.cc:1029: Failure
[2019-09-23T20:47:08.159Z] Value of: have_amo_lanes(*i)
[2019-09-23T20:47:08.159Z]   Actual: false
[2019-09-23T20:47:08.159Z] Expected: should_have_amo
[2019-09-23T20:47:08.159Z] Which is: true
[2019-09-23T20:47:08.159Z] /scrap/jenkins/workspace/ucx-2/contrib/../test/gtest/ucp/test_ucp_wireup.cc:1029: Failure
[2019-09-23T20:47:08.159Z] Value of: have_amo_lanes(*i)
[2019-09-23T20:47:08.159Z]   Actual: false
[2019-09-23T20:47:08.159Z] Expected: should_have_amo
[2019-09-23T20:47:08.159Z] Which is: true
[2019-09-23T20:47:08.159Z] [     INFO ] Testing 257 number of EPs
[2019-09-23T20:47:08.416Z] [  FAILED  ] sm_rc/test_ucp_wireup_fallback_amo.different_amo_types/0, where GetParam() = sm,rc_x,rc_v (442 ms)
```

**Comment by dmitrygx** [comment]
> [2019-09-23T20:47:07.903Z] [ RUN      ] sm_rc/test_ucp_wireup_fallback_amo.different_amo_types/0
> [2019-09-23T20:47:07.903Z] [     INFO ] Testing 1 number of EPs
> [2019-09-23T20:47:08.159Z] /scrap/jenkins/workspace/ucx-2/contrib/../test/gtest/ucp/test_ucp_wireup.cc:1029: Failure
> [2019-09-23T20:47:08.159Z] Value of: have_amo_lanes(*i)
> [2019-09-23T20:47:08.159Z]   Actual: false
> [2019-09-23T20:47:08.159Z] Expected: should_have_amo
> [2019-09-23T20:47:08.159Z] Which is: true
> [2019-09-23T20:47:08.159Z] /scrap/jenkins/workspace/ucx-2/contrib/../test/gtest/ucp/test_ucp_wireup.cc:1029: Failure
> [2019-09-23T20:47:08.159Z] Value of: have_amo_lanes(*i)
> [2019-09-23T20:47:08.159Z]   Actual: false
> [2019-09-23T20:47:08.159Z] Expected: should_have_amo
> [2019-09-23T20:47:08.159Z] Which is: true
> [2019-09-23T20:47:08.159Z] [     INFO ] Testing 257 number of EPs
> [2019-09-23T20:47:08.416Z] [  FAILED  ] sm_rc/test_ucp_wireup_fallback_amo.different_amo_types/0,

@yosefe it was a gtest issue, fixed

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12415/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/8c204be738501f2c0ddd1876013ccb08713b2e53/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/37cc048397f78c4d9d9ae0e503081b8690cfc4e6/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/163a2d3fbdb9b4d3e7bacbafdf64d5ef980f8d40/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/b664703ab96cad5d45d85dae06b6077582ecd6be/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/345e21e66ebb7897a071329ede68b8aa0a137350/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/3b97db132741ed53852d1d86dda093c3f3a954b9/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/3baa24beacbf7adcd105bd2a0b4fe7518682381e/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/348013b2c60c96888f2b145eb4535beb1fb55802/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/03799aa60f85311a96c3906161e71c1ca1484771/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/b81d4054540512588f2d470e55172835ebb6fc5c/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/048e7ed8a24902b7c716715879d4ad470592cc2e/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/c0b3e24700af2377dbb2680caa6d79da7d4fb81e/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/0a1e3b72409a07249aa8f2390e0e1ee2be34dc80/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/cafb00ea64bdaf2cd5f52d1993d393e8da1d17bd/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/875caeaff1a5d4249bb3db397cf5ba77aef2ff7e/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/9d50463fa7bb944e46d73c63d5285cad40c7855a/hpc-test-node-new_W3) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/56e09d1c38f8b36ba4bceb6316f6a572af80ae74/hpc-test-althca_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/62fdaa6139e5d1536b8c6d2e3b59fb12d29396b9/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/6d0600573b14d8a0f25fa9b93d4ffdf080ad7c79/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/c9c60a5291d1ce6c2ee2afe5afd44041fb157e99/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/af679aba7fbc11ead63c1578ba3c5484cebbadb8/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/d1ab4bc6c0f74a643eb9866227690bfc84f089fc/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/6ea375a856a39ac0acc3c6fbc1f7e2689b926e40/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/85110e043080584e8d11e6978b6114b777a7f59d/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/501f540d700579cb4c5e6cc472f2e33b7f20e640/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/696200a81676edaa7df52db8a10257c9c0cc462e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/f494901ec1484c8ee6330978ba48de72f6f50bba/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/43be26768464b4311c71b8890b45e4af1284228e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7674aa913d8aa7cb042dd64e343f0e04/raw/7c9994cf96a8b5c310dc5cee81071d162a9a2fd1/hpc-test-node-gpu_W0) | :question: UNKNOWN

File: test/gtest/ucp/test_ucp_wireup.cc [hunk 1]
```diff
@@ -950,3 +952,151 @@ UCP_INSTANTIATE_TEST_CASE_TLS(test_ucp_wireup_fallback,
...
+        if (uct_ep == NULL) {
+            return false;
+        }
+
+        if (ucp_wireup_ep_test(uct_ep) || ucp_proxy_ep_test(uct_ep)) {
+            ucp_proxy_ep_t *proxy_ep = ucs_derived_of(uct_ep,
+                                                      ucp_proxy_ep_t);
+            uct_ep = proxy_ep->uct_ep;
+        }
+
```
Comment (brminich) [inline test/gtest/ucp/test_ucp_wireup.cc]: you can use `ucp_ep_get_iface_attr` for instance. No need to request attrs, they are stored in `worker->wiface[x].attrs`

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_wireup.cc]: done

File: src/uct/ib/rdmacm/rdmacm_iface.c [hunk 2]
```diff
@@ -15,6 +15,10 @@ enum uct_rdmacm_process_event_flags {
 };
 
 static ucs_config_field_t uct_rdmacm_iface_config_table[] = {
+    {"", "", NULL,
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/ib/rdmacm/rdmacm_iface.c]: the PR was closed (not merged)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12419/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 1 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/67d2b59958a19dceff7d22cbd6a797e2/raw/36e7cfcc66512718da26c31cecd9442938a7f43f/_main) | :x: FAILURE

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12417/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/5ffe2c9fbd96770a596012a0d1616caf80358e49/_main) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/45143c9e8927b9fa82dfb768f06c0ed202dc81fc/hpc-test-node-new_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/e53d4d94ca7eef1520781b5af6676ea22474f6da/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/c0da01242b002c04f8475cce8ce30c325feeb590/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/088070ab5f231b8ec18d2744446846eba78e6d04/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/b603c970cd8c4c788a6ab3c2df352d6853d7476a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/ec528573560ad8890426ba4a8795913bd320a3a1/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/8f756c6c6b5c7b740bf51032f79ec9e2d04ef44b/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/ee22ecd01bf7cc8980ff1623ae730435c6ae58b2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/5e733b17fde163f0edbf902a3f4d127d8eadd8a0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/f95cdddbe321d54fbbe3f2dc3d3c250c74f75876/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/77a4bcc3c4e2d2cc3e2751f41d046dcf0ce065b0/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/edaabfcfe05d3fa673159dd91bb7e3705a00860b/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/c32c66fbcdc59bdecef31845430659866c084248/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/eaff931e4eb6dbea6c83634ce44ee4accb2a8803/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/dc08a0300dfd667d9715acc6a3c120853941d0de/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/1a625bdf78f27f75b2b67b8acb997c10a774c594/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/a90b24d75691c567695ef7980ff1d2e67f79a3db/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/51f8068fe8a03621568681d34e4e14d029060ba4/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/7485b227962c6601151504cdb9e0a3e4dcb04951/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/e305f6616f37ca51e1063a2e1401bb3a4d91eec5/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/d1a3cffb7f0e259a42412e2f4eb2ae52e125ed5d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/fbe399bdb641293247433f8524b5693ed7b4d06b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/6fdec9fd597c8ccb5248b1e18926488ab14694c0/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/cd354f0049fd8029323943a185cdcc411cd1723d/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/cd962535ac9a121a2d5effd6d16a760be9676208/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/a4fe0cc686edd3f86a8f8a7abea94fb03d690367/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/209a0f4b1a2ef4285d8b2c7e84bacf730732b593/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/abe732c2de38cd932eba534ec906aaef/raw/59bebfba657d28f6f6262ad6b0e8a0dd5a261e86/hpc-test-node-legacy_W0) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12421/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/560bfaa6443b004fd4bbf0467142973e75254bc1/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/92318a8f95bfe37518523ee348d25777d26e4661/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/788a3a3b212a3af896b2a7870e3442ede78845a9/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/0572cc2e487c3b556b73d96787f69291a6ddd73e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/60dc6d558a8a9d3e804b9e47861fc12b8b809f2b/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/fecd0b1433bd3a4cf8952e95a4b20b4a5ec1c302/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/93fda2dce8d1e39254aad86566cff48acb141b59/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/e1b8922987a578cd2b45bd9b49895b513b049bb2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/70ebf319fbc4b43e75d9cfe6ebebc2264b9ec587/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/a22fdc5a0386f9ab81074781d5fa0428ff8cd7a9/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/ccc6e4bdc99bd1936f58d17077f34897a36e5453/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/7e31e6b5eb2a7365e0902157548bdbddb8555f68/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/b4901c1c82b762738a4cae050ed8d7e3339f91d0/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/2d635d82cd1e7ab140ce30c762781b68ee545614/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/3ea684b808f356f6f6bd6f390b57798ebd2cda9a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/4dc5d92cc5cb8cdf393739b5c65f7e3f64dd97dd/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/affd7e6332c27e230c2cc986c8d665058020c235/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/a02637110e9cdbc30eaf3585f518a0353db11b09/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/5972ddb306c625374e8941f07ce664d607eb52fe/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/b5e923cf60e304321b7a86023206d80eee0d41a2/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/f37bd731a4678e23aa7801d4424956c4031d27c9/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/8fb660c6c168406a343f11049da843980268780b/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/4745c821922d10dc12a3bfc55f1d9f9787839ece/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/a2d5c44dceedc92331f6c3999f919e053cd00166/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/d48b7fea2685477e1ed83cf08b35bdbad657e727/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/7c732e14e700a6929f74cec5d1955460e7f91be7/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/00d0f34ac05f433d27e943a713dfc478c264d11b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/ada1dc3f055195b0279eb3458ea904954cb5682c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/97bcdab1f7a7510314b06b393161c0d5/raw/f1c22f856178d7babce4fcabb35f3abcbae7dfdc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@yosefe could you review pls?
