### PR TITLE
UCP: Use mpool set for UCT AM descriptors

### LINKED ISSUE #7151: memory footprint is huge for short inlined - unexpected messages
**UCX version** : master
**MPI** : OMPI master

Huge heap memory is allocated for short inlined - unexpected messages, which sometimes causes OOM (out-of-memory). 

Here is the simplified test case used:

```
---------------------------------------
#include "mpi.h"

#include <stdio.h>
#include<stdlib.h>

int main( int argc, char *argv[])
{
        long count = strtol(argv[1], NULL, 10);
        long comm_count = strtol(argv[2], NULL, 10);
        static long size = 0;

        int numtasks, rank, dest = 0, source = 0, rc, tag=1;
        MPI_Status stat;
        MPI_Request req;

        MPI_Init(&argc,&argv);
        MPI_Comm_size(MPI_COMM_WORLD, &numtasks);
        MPI_Comm_rank(MPI_COMM_WORLD, &rank);


        while(comm_count != 0) {
          if(rank != 0) {
            char * outmsg = (char *) malloc(count);
            rc = MPI_Send(outmsg, count, MPI_CHAR, dest, tag, MPI_COMM_WORLD);
            free(outmsg);
            if(rc != 0)
            exit(1);
          }

          if(rank == 0) {
            int counter = 0;
            for(counter = 1; counter < numtasks; counter++) {
                size += count;
                char * inmsg = (char *) malloc(count);
                rc = MPI_Recv(inmsg, count, MPI_CHAR, counter, tag, MPI_COMM_WORLD, &stat);
                free(inmsg);
                if(rc != 0)
                    exit(1);
            }
          }

          comm_count--;
        }

        printf("size : %ld\n", size);

        MPI_Finalize();
}
```

In the above program all the processes expect `rank 0` sends multiple small messages to `rank 0`, whereas rank 0 receives all the messages from the other tasks. This scenario could cause the unexpected message queue to grow.

Here are some observations and steps to recreate the issue, the tests are executed with default `UCX_TLS (all)`, and on a single node. 

```
[n02 mem-test]$ pwd
/mem-test


[n02 mem-test]$ cat path 
export MPI_ROOT=/mem-test/ompi-install
export UCX_ROOT=/mem-test/ucx-install
export PATH=$MPI_ROOT/bin:$UCX_ROOT/bin:/heaptrack-install/bin/:$PATH
export LD_LIBRARY_PATH=$MPI_ROOT/lib:$UCX_ROOT/lib:$LD_LIBRARY_PATH

[n02 mem-test]$ source path 

[n02 mem-test]$ which mpicc
/mem-test/ompi-install/bin/mpicc
```

```
[n02 mem-test]$ mpicc sr.c -g -o sr
```

**Case 1**:
```
[n02 mem-test]$ $MPI_ROOT/bin/mpirun -np 8 --mca osc ucx,sm --mca pml ucx --mca btl ^vader,tcp,openib,uct -x LD_LIBRARY_PATH --mca coll basic,inter,libnbc,self /heaptrack-install/bin/heaptrack ./sr  93 1000000


[n02 mem-test]$  for file in heaptrack.a.out.*; do  heaptrack --analyze $file | grep "peak heap memory consumption"; done;
peak heap memory consumption: 151.91MB
peak heap memory consumption: 151.86MB
peak heap memory consumption: 151.86MB
peak heap memory consumption: 151.86MB
peak heap memory consumption: 151.86MB
peak heap memory consumption: 151.86MB
peak heap memory consumption: 151.86MB
peak heap memory consumption: 151.86MB
```

**Case 2**:  **(for proc: 0 : peak heap memory consumption: 15.30GB)**

```
[n02 mem-test]$ $MPI_ROOT/bin/mpirun -np 8 --mca osc ucx,sm --mca pml ucx --mca btl ^vader,tcp,openib,uct -x LD_LIBRARY_PATH --mca coll basic,inter,libnbc,self  /heaptrack-install/bin/heaptrack ./a.out  92 1000000


[n02 mem-test]$  for file in heaptrack.a.out.*; do  heaptrack --analyze $file | grep "peak heap memory consumption"; done;
peak heap memory consumption: 15.30GB
peak heap memory consumption: 151.86MB
peak heap memory consumption: 151.83MB
peak heap memory consumption: 151.83MB
peak heap memory consumption: 151.85MB
peak heap memory consumption: 151.86MB
peak heap memory consumption: 151.86MB
peak heap memory consumption: 151.85MB
```

In `Case 2` we take up the short inline path, 
https://github.com/openucx/ucx/blob/master/src/uct/sm/mm/base/mm_iface.c#L246

where we use `ucp_am_bufs` memory pool for the receive descriptor allocation, and when `UCX_TLS` is set to `all` even though TCP transport is not selected it uses `UCX_TCP_RX_SEG_SIZE` to allocat the memory pool elements, since it has the larger segment size among all the available transports, as below,

```
static ucs_status_t ucp_worker_init_mpools(ucp_worker_h worker)
{
    size_t           max_mp_entry_size = 0;
    ucp_context_t    *context          = worker->context;
    uct_iface_attr_t *if_attr;
    ucp_rsc_index_t  iface_id;
    ucs_status_t     status;

    for (iface_id = 0; iface_id < worker->num_ifaces; ++iface_id) {
        if_attr           = &worker->ifaces[iface_id]->attr;
        max_mp_entry_size = ucs_max(max_mp_entry_size,
                                    if_attr->cap.am.max_short);
        max_mp_entry_size = ucs_max(max_mp_entry_size,
                                    if_attr->cap.am.max_bcopy);
        max_mp_entry_size = ucs_max(max_mp_entry_size,
                                    if_attr->cap.am.max_zcopy);
    }

    ...
    ...
    ...
    ...
    
    status = ucs_mpool_init(&worker->am_mp, 0,
                            max_mp_entry_size + UCP_WORKER_HEADROOM_SIZE +
                            worker->am.alignment,
                            0, UCS_SYS_CACHE_LINE_SIZE, 128, UINT_MAX,
                            &ucp_am_mpool_ops, "ucp_am_bufs");
    if (status != UCS_OK) {
        goto err_rkey_mp_cleanup;
    }

}
```

This seems to increase the memory footprint for the `UCX_TLS=all` case even though it is not necessary.

If I force select some of the transports for shmem it seems to be allocating much lesser memory:
```
UCX_TLS=posix,self,dc  -  allocates a total of 1.72 GB
mpool ucp_am_bufs: check allocated chunk 0xa68738a4 of 1081492 bytes with 128 elements
```

Is this an expected behaviour? Any comments / suggestions to improve this will be helpful.

Thanks.

### PR DESCRIPTION
**Pull request by brminich**
## What
Use set of memory pools with different sizes for UCT AM descriptors in UCP.

## Why ?
Currently, single memory pool is used for any inlined data coming from UCT. Even if 1 byte message arrives, it consumes ~8KB element, which leads to huge memory consumption (or even 64K with tcp).
Initializing several memory pools of different sizes will help to preserve reasonable memory consumption

fixes #7151

### CODE REVIEW

**Comment by brminich** [comment]
@dmitrygx, @karasevb, can you please review?

**Comment by brminich** [comment]
@yosefe, plz review

File: src/ucp/core/ucp_worker.c [hunk 1]
```diff
@@ -1730,29 +1727,35 @@ static ucs_status_t ucp_worker_init_mpools(ucp_worker_h worker)
...
+                                    max_mp_entry_size, 0,
+                                    UCP_WORKER_HEADROOM_SIZE + worker->am.alignment,
+                                    0, UCS_SYS_CACHE_LINE_SIZE, 128, UINT_MAX,
+                                    &ucp_am_mpool_ops, "ucp_am_bufs");
+        if (status != UCS_OK) {
+            goto err_reg_mp_cleanup;
+        }
+    }
+
+    worker->max_uct_am_size = max_mp_entry_size;
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:1753]: maybe use a flag on worker instead?

Comment (brminich) [reply src/ucp/core/ucp_worker.c:1753]: maybe this value can be useful for something else in the future?

Comment (yosefe) [reply src/ucp/core/ucp_worker.c:1753]: seems it would already be saved in the mpool  set

Comment (brminich) [reply src/ucp/core/ucp_worker.c:1753]: imo, it does not look good to get it from there, it is just internals of specific data struct.

Comment (yosefe) [reply src/ucp/core/ucp_worker.c:1753]: also, it's not really max_uct_am_size 
it's max possible **received** active message length
IMO better remote and add if really needed

Comment (shamisp) [reply src/ucp/core/ucp_worker.c:1753]: ` possible received active message length`  - not sure if this make sense either

**Review by yosefe — APPROVED** [review]
