### PR TITLE
UCP/CORE/GTEST: Drain keeplive timer fd to not trigger unnecessary events on user's fd

### LINKED ISSUE #7864: ucx.1.12 and master continuously trigger worker->event_fd
### Steps to Reproduce

1.  Context and worker with WAKEUP_FEATURE .
2.  Reproduces on jazz with `UCX_TLS=rc UCX_NET_DEVICES=mlx5_4:1`
2.  Listener that creates backward endpoint on connection request + all endpoints with peer error handling mode. (Probably that's why doesn't reproduce with ucx_perftest since there's no sockaddr connection).
3.  Create connection from client -> do operation -> close endpoint (maybe just enough to establish connection).
4.  On server do:
```
while (true) {
    if (ucp_worker_progress(worker) == 0) {
        ucp_worker_wait();
    }
}
```
Server continuously exits from `ucp_worker_wait` because there's changes in `worker->event_fd`. Though next `ucp_worker_progress()` returns 0. Logs becomes full of continuously repeating: 

```
[1642794366.526620] [jazz12:167817:5]      ucp_worker.c:2788 UCX  FUNC  ucp_worker_wait(worker 0x7f028e8a0010)
[1642794366.526623] [jazz12:167817:5]      ucp_worker.c:2727 UCX  FUNC  ucp_worker_arm(worker=0x7f028e8a0010)
[1642794366.526626] [jazz12:167817:5]      ucp_worker.c:2761 UCX  DATA  arm iface 0x7f028ea22040 returned Success
[1642794366.526630] [jazz12:167817:5]      ucp_worker.c:2788 UCX  FUNC  ucp_worker_wait(worker 0x7f028e8a0010)
[1642794366.526633] [jazz12:167817:5]      ucp_worker.c:2727 UCX  FUNC  ucp_worker_arm(worker=0x7f028e8a0010)
[1642794366.526636] [jazz12:167817:5]      ucp_worker.c:2761 UCX  DATA  arm iface 0x7f028ea22040 returned Success
[1642794366.526640] [jazz12:167817:5]      ucp_worker.c:2788 UCX  FUNC  ucp_worker_wait(worker 0x7f028e8a0010)
[1642794366.526643] [jazz12:167817:5]      ucp_worker.c:2727 UCX  FUNC  ucp_worker_arm(worker=0x7f028e8a0010)
[1642794366.526646] [jazz12:167817:5]      ucp_worker.c:2761 UCX  DATA  arm iface 0x7f028ea22040 returned Success
[1642794366.526650] [jazz12:167817:5]      ucp_worker.c:2788 UCX  FUNC  ucp_worker_wait(worker 0x7f028e8a0010)
[1642794366.526652] [jazz12:167817:5]      ucp_worker.c:2727 UCX  FUNC  ucp_worker_arm(worker=0x7f028e8a0010)
[1642794366.526661] [jazz12:167817:5]      ucp_worker.c:2761 UCX  DATA  arm iface 0x7f028ea22040 returned Success
```
5. **Doesn't reproduce with ucx1.11**
6. Before connection established on listener progress works correctly:
```
#1  0x00007fb558c6255b in poll (__timeout=-1, __nfds=1, __fds=0x7fb5514c7830) at /usr/include/x86_64-linux-gnu/bits/poll2.h:46
#2  ucp_worker_wait (worker=<optimized out>) at /home/rladmin/peterr/ucx/contrib/../src/ucp/core/ucp_worker.c:2831
```
7. Breakpoint on `ucp_worker_wakeup_signal_fd` doesn't trigger, so something else changes that fd.

cc @abellina

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Drain keeplive `timerfd` to not trigger unnecessary events on user's fd.

## Why ?

Fixes #7864.
`timerfd`  should be drained by doing 64-bit `read()` to not re-trigger events.

## How ?

1. Update keepalive gtest to reproduce the issue by draining wakeup FD after detecting error and closing fdailed EP.
2. Added `ucp_worker_fd_read()`, used it for `eventfd`.
3. Made keepalive `timerfd` non-blocking, to call `read()` in non-blocking manner inside `ucp_worker_do_keepalive_progress()`.
4. Used `ucp_worker_fd_read()` in a loop while `status == UCS_ERR_BUSY` to drain keepalive `timerfd`.
5. If wakeup feature is used, use `ucp_worker_do_keepalive_progress()` directly instead of `ucp_worker_keepalive_progress()` which skips some keepalive attempts.

### CODE REVIEW

**Comment by dmitrygx** [comment]
@petro-rudenko

**Comment by dmitrygx** [comment]
@hoopoepg @brminich could you review pls?
testing passes, there are only IO-Demo failures which are unrelated to the changes in the PR.

File: src/ucp/core/ucp_worker.c [hunk 1]
```diff
@@ -2751,6 +2745,30 @@ ucs_status_t ucp_worker_arm(ucp_worker_h worker)
...
+
+    ucs_trace_func("worker=%p", worker);
+
+    UCP_CONTEXT_CHECK_FEATURE_FLAGS(worker->context, UCP_FEATURE_WAKEUP,
+                                    return UCS_ERR_INVALID_PARAM);
+
+    /* Read from event pipe. If some events are found, return BUSY,
+     * Otherwise, continue to arm the transport interfaces.
+     */
+    status = ucp_worker_fd_read(worker, worker->eventfd, "internal event fd");
```
Comment (hoopoepg) [inline src/ucp/core/ucp_worker.c:2767]: due to this change:
line 2785: ```status = UCS_OK;``` is not needed anymore
line 2781: ```goto out_unlock;``` may be replaced by ```break;```

**Comment by petro-rudenko** [comment]
Works with a spark benchmark. Thanks. Would need to port to 1.12 once merged in master

File: src/ucp/core/ucp_worker.c (hunk 1 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c:2767]: good catch, done

**Review by hoopoepg — APPROVED** [review]

**Comment by pentschev** [comment]
I also confirmed the performance regression with Dask and that this PR resolves it. Would be great to backport and have it make its way in UCX 1.12.1.

@quasiben FYI

**Comment by dmitrygx** [comment]
@brminich @yosefe could you review pls?

File: test/gtest/ucp/test_ucp_peer_failure.cc [hunk 2]
```diff
@@ -536,6 +552,15 @@ UCS_TEST_P(test_ucp_peer_failure_keepalive, kill_receiver,
 
     EXPECT_NE(0, m_err_count);
 
+    ucp_ep_h ep = sender().revoke_ep(0, FAILING_EP_INDEX);
+    void *creq = ucp_ep_close_nb(ep, UCP_EP_CLOSE_MODE_FORCE);
+    request_wait(creq);
+
+    /* make sure no remaining events are returned from poll() */
```
Comment (brminich) [inline test/gtest/ucp/test_ucp_peer_failure.cc:559]: minor: comments from upper case

**Review by brminich — APPROVED** [review]

File: test/gtest/ucp/test_ucp_peer_failure.cc (hunk 2 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_peer_failure.cc:559]: i'm following the code style of the file, here all comments start from the lower case.
is it ok?

Comment (brminich) [reply test/gtest/ucp/test_ucp_peer_failure.cc:559]: ок

Comment (yosefe) [reply test/gtest/ucp/test_ucp_peer_failure.cc:559]: it's copy/paste of previous code

File: src/ucp/core/ucp_worker.c [hunk 3]
```diff
@@ -3002,10 +3015,16 @@ ucp_worker_keepalive_timerfd_init(ucp_worker_h worker)
...
+        goto err_close_timerfd;
     }
 
     ucp_worker_wakeup_ctl_fd(worker, UCP_WORKER_EPFD_OP_ADD,
                              worker->keepalive.timerfd);
+
+    return;
+
+err_close_timerfd:
+    close(worker->keepalive.timerfd);
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:3027]: why need to close if we failed to open?

File: src/ucp/core/ucp_worker.c [hunk 4]
```diff
@@ -3120,8 +3149,13 @@ void ucp_worker_keepalive_add_ep(ucp_ep_h ep)
...
               ep->flags, ucp_ep_config(ep)->key.ep_check_map);
     uct_worker_progress_register_safe(worker->uct,
-                                      ucp_worker_keepalive_progress, worker,
-                                      UCS_CALLBACKQ_FLAG_FAST,
+                                      !(worker->context->config.features &
+                                        UCP_FEATURE_WAKEUP) ?
+                                      ucp_worker_keepalive_progress :
+                                      /* Do keepalive directly, no need to skip
+                                       * iterations */
+                                      ucp_worker_do_keepalive_progress,
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:3157]: maybe a call to ucp_worker_arm will make sure the next keepalive progress will not skip iterations? assuming worker_arm is done every time before a potentially long sleep.
and this way, we "don't skip iterations" only when wakeup feature is really used, and not just requested

Comment (yosefe) [reply src/ucp/core/ucp_worker.c:3157]: also need to add comment that the reason we do it is to not miss keepalive rounds after a long time without calling progress

File: test/gtest/ucp/test_ucp_peer_failure.cc [hunk 5]
```diff
@@ -517,14 +530,17 @@ UCS_TEST_P(test_ucp_peer_failure_keepalive, kill_receiver,
     /* flush all outstanding ops to allow keepalive to run */
     flush_worker(sender());
     if (get_variant_value() & WAKEUP) {
-        wait_for_wakeup({ &sender(), &failing_receiver() },
-                        100, true);
+        int ret = wait_for_wakeup({ &sender(), &failing_receiver() }, 1000,
+                                  true);
+        EXPECT_EQ(ret, 1);
+
+        wakeup_drain({ &sender(), &failing_receiver() });
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_peer_failure.cc:537]: why need to "drain"? pls add comment

File: test/gtest/ucp/test_ucp_peer_failure.cc [hunk 6]
```diff
@@ -488,6 +488,19 @@ class test_ucp_peer_failure_keepalive : public test_ucp_peer_failure
         add_variant_with_value(variants, UCP_FEATURE_AM | UCP_FEATURE_WAKEUP,
                                TEST_AM | WAKEUP, "am_wakeup");
     }
+
+    void wakeup_drain(const std::vector<entity*> &entities)
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_peer_failure.cc:492]: so it's not just "drain" ; it actually is waiting for "deadline" time to make sure no more events arrive?
the name is a bit misleading..

File: test/gtest/ucp/ucp_test.cc [hunk 7]
```diff
@@ -362,27 +363,34 @@ void ucp_test::wait_for_wakeup(const std::vector<entity*> &entities,
...
 
-        for (int fd : efds) {
-            pfd.push_back({ fd, POLLIN });
-        }
+    std::vector<struct pollfd> pfd;
+    for (int fd : efds) {
+        pfd.push_back({ fd, POLLIN });
+    }
+
+    do {
```
Comment (yosefe) [inline test/gtest/ucp/ucp_test.cc:378]: remove spaceline after

File: test/gtest/ucp/ucp_test.cc [hunk 8]
```diff
@@ -362,27 +363,34 @@ void ucp_test::wait_for_wakeup(const std::vector<entity*> &entities,
 
         ucs_status_t status = ucp_worker_arm(worker);
         if (status == UCS_ERR_BUSY) {
-            return;
+            return 1;
```
Comment (yosefe) [inline test/gtest/ucp/ucp_test.cc:366]: it means one fd was ready? maybe it should be -1?

File: src/ucp/core/ucp_worker.c (hunk 4 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c]: good idea, done

File: test/gtest/ucp/ucp_test.cc (hunk 8 above)
Comment (dmitrygx) [reply test/gtest/ucp/ucp_test.cc]: but then we have to check for `-1` too.
I guess it is ok to return `1`, because this means that there are some unhandled events that are ready to be read.

File: test/gtest/ucp/ucp_test.cc (hunk 7 above)
Comment (dmitrygx) [reply test/gtest/ucp/ucp_test.cc:382]: done

File: test/gtest/ucp/test_ucp_peer_failure.cc (hunk 6 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_peer_failure.cc:492]: I guess that the name `drain` is suitable here - we're trying to read all wakeup events while 'deadline' timer isn't expired.

File: test/gtest/ucp/test_ucp_peer_failure.cc (hunk 5 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_peer_failure.cc:538]: done

File: src/ucp/core/ucp_worker.c [hunk 9]
```diff
@@ -2769,6 +2769,27 @@ ucs_status_t ucp_worker_arm(ucp_worker_h worker)
...
+         */
+        while (ucp_worker_fd_read(worker, worker->keepalive.timerfd,
+                                  "keepalive fd") == UCS_ERR_BUSY) {
+            /* Reading of the event was successful, try again */
+        }
+
+        /* Make sure not missing keepalive rounds after a long time without
+         * calling UCP worker progress.
+         */
+        worker->keepalive.iter_count +=
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:2785]: maybe just reset to 0?
or use ucs_roundup_pow2?

File: src/ucp/core/ucp_worker.c [hunk 10]
```diff
@@ -2769,6 +2769,27 @@ ucs_status_t ucp_worker_arm(ucp_worker_h worker)
         return status;
     }
 
+    if (worker->keepalive.timerfd >= 0) {
+        /* Do read() of 8-byte unsigned integer containing the nubmer of
+         * expirations that have occured to make sure no events will be
+         * triggered again until timer isn't expired again.
+         */
+        while (ucp_worker_fd_read(worker, worker->keepalive.timerfd,
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:2777]: why not "if status!=OK return status"  - like we do for event fd

File: test/gtest/ucp/test_ucp_peer_failure.cc (hunk 6 above)
Comment (yosefe) [reply test/gtest/ucp/test_ucp_peer_failure.cc:492]: maybe something like "wakeup_check_no_events"

File: src/ucp/core/ucp_worker.c [hunk 11]
```diff
@@ -3071,6 +3070,11 @@ static UCS_F_NOINLINE unsigned ucp_worker_do_keepalive_progress(void *arg)
     ucs_time_t now;
     ucp_ep_h ep;
 
+    /* Must be called once per 'UCP_WORKER_KEEPALIVE_ITER_SKIP' iterations */
+    ucs_assertv(((worker->keepalive.iter_count - 1) %
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:3074]: seems redundant, it's not like this function really requires this condition in order to work properly

Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c]: removed

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
the test failure - hang in rcx/test_ucp_peer_failure_keepalive.kill_receive with valgrind - seems relevant:
```
[ RUN      ] rcx/test_ucp_peer_failure_keepalive.kill_receiver/1 <rc_x/am_wakeup>
/scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/test_helpers.cc:55: Failure
Failed
Connection timed out - abort testing
[swx-rdmz-ucx-new-02:4274 :0:4274] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
==== backtrace (tid:   4274) ====
 0 0x00000000000e2d47 __GI___sched_yield()  :0
 1 0x0000000000a14897 ucp_test::progress()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:169
 2 0x0000000000a14b59 ucp_test::wait_for_wakeup()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:387
 3 0x0000000000819d2e test_ucp_peer_failure_keepalive_kill_receiver_Test::test_body()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/test_ucp_peer_failure.cc:544
 4 0x0000000000819d2e ~vector()  /usr/include/c++/4.8.2/bits/stl_vector.h:416
 5 0x0000000000819d2e test_ucp_peer_failure_keepalive_kill_receiver_Test::test_body()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/test_ucp_peer_failure.cc:544
 6 0x00000000005f68d6 ucs::test_base::run()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/test.cc:356
 7 0x00000000005f68d6 ucs::test_base::TestBodyProxy()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/test.cc:382
```

**Comment by dmitrygx** [comment]
> the test failure - hang in rcx/test_ucp_peer_failure_keepalive.kill_receive with valgrind - seems relevant:

@yosefe you're right, the failure is related - keepalive timerfd was expired after returning from `ucp_worker_arm()` and waiting for events in `poll()`. So, we have `drain=true` and it tries to read all events, but the event on `keepalive.timerfd` is always triggered, but we don't do 8-byte `read()` to stop receiving it.
so, current implementation of draining in `wait_for_wakeup()` isn't correct and should be replaced by using `wakeup_drain_check_no_events()`.

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
> @dmitrygx can u pls port to 1.12?

@yosefe done - #7887, but it ports only UCP changes, GTEST changes rely on the code which was added only in the master branch.
