### PR TITLE
UCP/CORE: Remove EP ID dependant progress functions after releasing EP ID

### LINKED ISSUE #6568: failure on ud/test_ucp_sockaddr.connect_and_fail_wireup/3 on swx-rdmz-ucx-gpu-02.rdmz.labs.mlnx
```
2021-03-25T16:48:31.0408118Z [ RUN      ] ud/test_ucp_sockaddr.connect_and_fail_wireup/3 <ud_v/stream,mt>
2021-03-25T16:48:31.6446650Z [     INFO ] server listening on fe80::ba59:9fff:fe0a:75b9:35740
2021-03-25T16:48:31.7861360Z [swx-rdmz-ucx-gpu-02:10015:0:10015]    ucp_ep.inl:184  Assertion `ucp_ep_ext_control(ep)->local_ep_id != (18446744073709551615UL)' failed
2021-03-25T16:49:47.2376321Z 
2021-03-25T16:49:47.2479689Z /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/ucp/core/ucp_ep.inl: [ ucp_ep_local_id() ]
2021-03-25T16:49:47.2481736Z       ...
2021-03-25T16:49:47.2482696Z       181 
2021-03-25T16:49:47.2483901Z       182 static UCS_F_ALWAYS_INLINE ucs_ptr_map_key_t ucp_ep_local_id(ucp_ep_h ep)
2021-03-25T16:49:47.2485152Z       183 {
2021-03-25T16:49:47.2486937Z ==>   184     ucs_assert(ucp_ep_ext_control(ep)->local_ep_id != UCP_EP_ID_INVALID);
2021-03-25T16:49:47.2489340Z       185     return ucp_ep_ext_control(ep)->local_ep_id;
2021-03-25T16:49:47.2490513Z       186 }
2021-03-25T16:49:47.2491431Z       187 
2021-03-25T16:49:47.2492254Z 
2021-03-25T16:51:01.0687605Z ==== backtrace (tid:  10015) ====
2021-03-25T16:51:01.0706510Z  0 0x00000000000b8952 ucp_ep_local_id()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/ucp/core/ucp_ep.inl:184
2021-03-25T16:51:01.0739674Z  1 0x00000000000b8952 ucp_ep_local_id()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/ucp/core/ucp_ep.inl:184
2021-03-25T16:51:01.0742795Z  2 0x00000000000b8952 ucp_wireup_msg_prepare()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:193
2021-03-25T16:51:01.0745560Z  3 0x00000000000b8b3c ucp_wireup_msg_send()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:239
2021-03-25T16:51:01.0748442Z  4 0x00000000000b8c91 ucp_wireup_send_msg_ack()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:619
2021-03-25T16:51:01.0751358Z  5 0x000000000005219b ucs_callbackq_slow_proxy()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/ucs/datastruct/callbackq.c:402
2021-03-25T16:51:01.0754262Z  6 0x0000000000045daa ucs_callbackq_dispatch()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/ucs/datastruct/callbackq.h:211
2021-03-25T16:51:01.0757068Z  7 0x0000000000045daa uct_worker_progress()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/uct/api/uct.h:2559
2021-03-25T16:51:01.0759797Z  8 0x0000000000045daa ucp_worker_progress()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../src/ucp/core/ucp_worker.c:2451
2021-03-25T16:51:01.0762677Z  9 0x000000000090c38b ucp_test_base::entity::progress()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:873
2021-03-25T16:51:01.0766198Z 10 0x000000000090c977 ucp_test::progress()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:155
2021-03-25T16:51:01.0769052Z 11 0x000000000090c977 ucp_test::request_process()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:217
2021-03-25T16:51:01.0771945Z 12 0x000000000090cd06 ucp_test::request_wait()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:240
2021-03-25T16:51:01.0774781Z 13 0x000000000090cd78 ucp_test::cleanup()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:78
2021-03-25T16:51:01.0777737Z 14 0x00000000005e9590 ucs::test_base::TearDownProxy()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.cc:333
2021-03-25T16:51:01.0783335Z 15 0x00000000005cc669 HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3562
2021-03-25T16:51:01.0786594Z 16 0x00000000005c087c testing::Test::Run()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3643
2021-03-25T16:51:01.0789847Z 17 0x00000000005c0985 testing::TestInfo::Run()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3812
2021-03-25T16:51:01.0792772Z 18 0x00000000005c0aef testing::TestCase::Run()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3930
2021-03-25T16:51:01.0795836Z 19 0x00000000005c529d testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5808
2021-03-25T16:51:01.0799141Z 20 0x00000000005c5580 testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5725
2021-03-25T16:51:01.0802056Z 21 0x000000000055891d RUN_ALL_TESTS()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest.h:20059
2021-03-25T16:51:01.0804701Z 22 0x000000000055891d main()  /scrap/azure/agent-02/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/main.cc:105
2021-03-25T16:51:01.0806560Z 23 0x00000000000223d5 __libc_start_main()  ???:0
2021-03-25T16:51:01.0808510Z 24 0x00000000005aac01 _start()  ???:0
2021-03-25T16:51:01.0809895Z =================================
2021-03-25T16:51:01.1014356Z [swx-rdmz-ucx-gpu-02:10015:0:10015] Process frozen...
2021-03-25T18:30:52.0236458Z ==10015== 
2021-03-25T18:30:52.0241326Z ==10015== Process terminating with default action of signal 15 (SIGTERM)
2021-03-25T18:30:52.0243625Z ==10015==    at 0x7F26EFD: ??? (in /usr/lib64/libpthread-2.17.so)
2021-03-25T18:30:52.0244948Z ==10015==    by 0x50947D4: ucs_debug_freeze (debug.c:820)
2021-03-25T18:30:52.0246317Z ==10015==    by 0x5097BEB: ucs_error_freeze (debug.c:915)
2021-03-25T18:30:52.0247500Z ==10015==    by 0x5097BEB: ucs_handle_error (debug.c:1078)
2021-03-25T18:30:52.0248736Z ==10015==    by 0x50941B7: ucs_fatal_error_message (assert.c:37)
2021-03-25T18:30:52.0250014Z ==10015==    by 0x5094345: ucs_fatal_error_format (assert.c:53)
2021-03-25T18:30:52.0251321Z ==10015==    by 0x58E1951: ucp_ep_local_id (ucp_ep.inl:184)
2021-03-25T18:30:52.0252568Z ==10015==    by 0x58E1951: ucp_wireup_msg_prepare (wireup.c:193)
2021-03-25T18:30:52.0253871Z ==10015==    by 0x58E1B3B: ucp_wireup_msg_send (wireup.c:239)
2021-03-25T18:30:52.0255044Z ==10015==    by 0x58E1C90: ucp_wireup_send_msg_ack (wireup.c:619)
2021-03-25T18:30:52.0256377Z ==10015==    by 0x508A19A: ucs_callbackq_slow_proxy (callbackq.c:402)
2021-03-25T18:30:52.0257674Z ==10015==    by 0x586EDA9: ucs_callbackq_dispatch (callbackq.h:211)
2021-03-25T18:30:52.0258837Z ==10015==    by 0x586EDA9: uct_worker_progress (uct.h:2559)
2021-03-25T18:30:52.0260148Z ==10015==    by 0x586EDA9: ucp_worker_progress (ucp_worker.c:2451)
2021-03-25T18:30:52.0261453Z ==10015==    by 0x90C38A: ucp_test_base::entity::progress(int) (ucp_test.cc:873)
2021-03-25T18:30:52.0262785Z ==10015==    by 0x90C976: progress (ucp_test.cc:155)
2021-03-25T18:30:52.0264496Z ==10015==    by 0x90C976: ucp_test::request_process(void*, int, bool) (ucp_test.cc:217)
2021-03-25T18:30:52.0265793Z ==10015==    by 0x90CD05: request_wait (ucp_test.cc:240)
2021-03-25T18:30:52.0267053Z ==10015==    by 0x90CD05: flush_worker (ucp_test.cc:177)
2021-03-25T18:30:52.0268288Z ==10015==    by 0x90CD05: ucp_test::disconnect(ucp_test_base::entity&) (ucp_test.cc:193)
2021-03-25T18:30:52.0269606Z ==10015==    by 0x90CD77: ucp_test::cleanup() (ucp_test.cc:78)
2021-03-25T18:30:52.0270847Z ==10015==    by 0x5E958F: ucs::test_base::TearDownProxy() (test.cc:333)
2021-03-25T18:30:52.0272648Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:52.0274935Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:52.0278057Z ==10015==    by 0x5C087B: testing::Test::Run() (gtest-all.cc:3643)
2021-03-25T18:30:52.0279671Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:52.0281258Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:52.0283092Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:52.0284819Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:52.0286675Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:52.0288858Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:52.0290614Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:52.0291843Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:52.0292989Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:52.3598515Z ==10015== 
2021-03-25T18:30:52.3661212Z ==10015== HEAP SUMMARY:
2021-03-25T18:30:52.3662933Z ==10015==     in use at exit: 23,695,039 bytes in 208,673 blocks
2021-03-25T18:30:52.3664228Z ==10015==   total heap usage: 19,803,162 allocs, 10,663,275 frees, 96,004,053,392 bytes allocated
2021-03-25T18:30:52.3665872Z ==10015== 
2021-03-25T18:30:53.3701655Z ==10015== 5 bytes in 1 blocks are possibly lost in loss record 70 of 19,777
2021-03-25T18:30:53.3704098Z ==10015==    at 0x4C29BC3: malloc (vg_replace_malloc.c:299)
2021-03-25T18:30:53.3706819Z ==10015==    by 0x92270C9: strdup (in /usr/lib64/libc-2.17.so)
2021-03-25T18:30:53.3709153Z ==10015==    by 0x97EA444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.3711398Z ==10015==    by 0x9581810: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.3713618Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3715752Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3717305Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.3718718Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.3720093Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.3721533Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.3723002Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.3724359Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.3725795Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.3727176Z ==10015== 
2021-03-25T18:30:53.3728565Z ==10015== 5 bytes in 1 blocks are possibly lost in loss record 71 of 19,777
2021-03-25T18:30:53.3730291Z ==10015==    at 0x4C29BC3: malloc (vg_replace_malloc.c:299)
2021-03-25T18:30:53.3732448Z ==10015==    by 0x92270C9: strdup (in /usr/lib64/libc-2.17.so)
2021-03-25T18:30:53.3734766Z ==10015==    by 0x97EA444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.3737138Z ==10015==    by 0x9581890: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.3739342Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3742008Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3743551Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.3744950Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.3746399Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.3747858Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.3749286Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.3750651Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.3752106Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.3753408Z ==10015== 
2021-03-25T18:30:53.3754877Z ==10015== 7 bytes in 1 blocks are possibly lost in loss record 78 of 19,777
2021-03-25T18:30:53.3756673Z ==10015==    at 0x4C29BC3: malloc (vg_replace_malloc.c:299)
2021-03-25T18:30:53.3758914Z ==10015==    by 0x92270C9: strdup (in /usr/lib64/libc-2.17.so)
2021-03-25T18:30:53.3761118Z ==10015==    by 0x97EA444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.3763420Z ==10015==    by 0x95817C8: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.3765622Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3767765Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3769313Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.3770695Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.3772095Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.3773523Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.3774888Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.3776494Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.3777945Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.3779186Z ==10015== 
2021-03-25T18:30:53.3780631Z ==10015== 7 bytes in 1 blocks are possibly lost in loss record 79 of 19,777
2021-03-25T18:30:53.3782355Z ==10015==    at 0x4C29BC3: malloc (vg_replace_malloc.c:299)
2021-03-25T18:30:53.3784480Z ==10015==    by 0x92270C9: strdup (in /usr/lib64/libc-2.17.so)
2021-03-25T18:30:53.3786810Z ==10015==    by 0x97EA444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.3789129Z ==10015==    by 0x95817E0: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.3791249Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3793902Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3795449Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.3797011Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.3798086Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.3799435Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.3800771Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.3801982Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.3803271Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.3804434Z ==10015== 
2021-03-25T18:30:53.3805669Z ==10015== 7 bytes in 1 blocks are possibly lost in loss record 80 of 19,777
2021-03-25T18:30:53.3807319Z ==10015==    at 0x4C29BC3: malloc (vg_replace_malloc.c:299)
2021-03-25T18:30:53.3809581Z ==10015==    by 0x92270C9: strdup (in /usr/lib64/libc-2.17.so)
2021-03-25T18:30:53.3811633Z ==10015==    by 0x97EA444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.3813841Z ==10015==    by 0x9581848: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.3815903Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3817989Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3819406Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.3820645Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.3821901Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.3823207Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.3824491Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.3825716Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.3827111Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.3828271Z ==10015== 
2021-03-25T18:30:53.3829520Z ==10015== 7 bytes in 1 blocks are possibly lost in loss record 81 of 19,777
2021-03-25T18:30:53.3831504Z ==10015==    at 0x4C29BC3: malloc (vg_replace_malloc.c:299)
2021-03-25T18:30:53.3833507Z ==10015==    by 0x92270C9: strdup (in /usr/lib64/libc-2.17.so)
2021-03-25T18:30:53.3835728Z ==10015==    by 0x97EA444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.3838076Z ==10015==    by 0x9581878: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.3840249Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3842169Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.3843557Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.3844747Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.3846113Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.3847427Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.3848630Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.3849919Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.3851186Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.3852289Z ==10015== 
2021-03-25T18:30:53.4635607Z ==10015== 8 bytes in 1 blocks are possibly lost in loss record 1,883 of 19,777
2021-03-25T18:30:53.4637450Z ==10015==    at 0x4C29BC3: malloc (vg_replace_malloc.c:299)
2021-03-25T18:30:53.4639006Z ==10015==    by 0x92270C9: strdup (in /usr/lib64/libc-2.17.so)
2021-03-25T18:30:53.4640311Z ==10015==    by 0x97EA444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.4641645Z ==10015==    by 0x95817F8: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.4642938Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.4644130Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.4644923Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.4645545Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.4646330Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.4647020Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.4647705Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.4648393Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.4649067Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.4649619Z ==10015== 
2021-03-25T18:30:53.4650404Z ==10015== 9 bytes in 1 blocks are possibly lost in loss record 1,890 of 19,777
2021-03-25T18:30:53.4651539Z ==10015==    at 0x4C29BC3: malloc (vg_replace_malloc.c:299)
2021-03-25T18:30:53.4652716Z ==10015==    by 0x92270C9: strdup (in /usr/lib64/libc-2.17.so)
2021-03-25T18:30:53.4653988Z ==10015==    by 0x97EA444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.4655263Z ==10015==    by 0x9581860: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.4656492Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.4657688Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.4658473Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.4659090Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.4659784Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.4660413Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.4661097Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.4661781Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.4662476Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.4663082Z ==10015== 
2021-03-25T18:30:53.4663781Z ==10015== 13 bytes in 2 blocks are possibly lost in loss record 2,053 of 19,777
2021-03-25T18:30:53.4664617Z ==10015==    at 0x4C29BC3: malloc (vg_replace_malloc.c:299)
2021-03-25T18:30:53.4665765Z ==10015==    by 0x92270C9: strdup (in /usr/lib64/libc-2.17.so)
2021-03-25T18:30:53.4667073Z ==10015==    by 0x97EA444: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.4668261Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.4669435Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.4670224Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.4670840Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.4671800Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.4672489Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.4673120Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.4673800Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.4674483Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.4675034Z ==10015== 
2021-03-25T18:30:53.6581363Z ==10015== 32 bytes in 1 blocks are possibly lost in loss record 5,173 of 19,777
2021-03-25T18:30:53.6583541Z ==10015==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
2021-03-25T18:30:53.6586068Z ==10015==    by 0x97EA431: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.6588150Z ==10015==    by 0x95817C8: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.6590080Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6591897Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6593157Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.6594207Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.6595359Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.6596588Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.6597674Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.6598826Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.6599937Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.6600875Z ==10015== 
2021-03-25T18:30:53.6602059Z ==10015== 32 bytes in 1 blocks are possibly lost in loss record 5,174 of 19,777
2021-03-25T18:30:53.6603266Z ==10015==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
2021-03-25T18:30:53.6604557Z ==10015==    by 0x97EA431: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.6605901Z ==10015==    by 0x95817E0: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.6607941Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6609305Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6610309Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.6611192Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.6612047Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.6612951Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.6613841Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.6615144Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.6616200Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.6617079Z ==10015== 
2021-03-25T18:30:53.6617962Z ==10015== 32 bytes in 1 blocks are possibly lost in loss record 5,175 of 19,777
2021-03-25T18:30:53.6619067Z ==10015==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
2021-03-25T18:30:53.6620567Z ==10015==    by 0x97EA431: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.6622099Z ==10015==    by 0x95817F8: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.6623557Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6624956Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6625971Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.6626949Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.6627794Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.6628754Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.6629663Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.6630494Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.6631400Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.6632198Z ==10015== 
2021-03-25T18:30:53.6633062Z ==10015== 32 bytes in 1 blocks are possibly lost in loss record 5,176 of 19,777
2021-03-25T18:30:53.6634165Z ==10015==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
2021-03-25T18:30:53.6635622Z ==10015==    by 0x97EA431: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.6637239Z ==10015==    by 0x9581810: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.6638701Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6640105Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6641383Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.6642266Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.6643152Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.6644004Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.6644912Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.6645790Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.6646794Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.6647631Z ==10015== 
2021-03-25T18:30:53.6648483Z ==10015== 32 bytes in 1 blocks are possibly lost in loss record 5,177 of 19,777
2021-03-25T18:30:53.6649595Z ==10015==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
2021-03-25T18:30:53.6651086Z ==10015==    by 0x97EA431: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.6652532Z ==10015==    by 0x9581848: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.6653987Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6655403Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6656534Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.6657421Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.6658320Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.6659163Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.6660061Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.6660945Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.6661787Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.6662607Z ==10015== 
2021-03-25T18:30:53.6663615Z ==10015== 32 bytes in 1 blocks are possibly lost in loss record 5,178 of 19,777
2021-03-25T18:30:53.6664671Z ==10015==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
2021-03-25T18:30:53.6666180Z ==10015==    by 0x97EA431: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.6667696Z ==10015==    by 0x9581860: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.6669093Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6670509Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6671503Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.6672328Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.6673647Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.6674544Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.6675385Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.6676347Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.6677238Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.6678002Z ==10015== 
2021-03-25T18:30:53.6678918Z ==10015== 32 bytes in 1 blocks are possibly lost in loss record 5,179 of 19,777
2021-03-25T18:30:53.6679958Z ==10015==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
2021-03-25T18:30:53.6681505Z ==10015==    by 0x97EA431: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.6683019Z ==10015==    by 0x9581878: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.6684405Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6685816Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6686878Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.6687688Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.6688599Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.6689497Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.6690330Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.6691223Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.6692182Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.6692945Z ==10015== 
2021-03-25T18:30:53.6693862Z ==10015== 32 bytes in 1 blocks are possibly lost in loss record 5,180 of 19,777
2021-03-25T18:30:53.6694949Z ==10015==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
2021-03-25T18:30:53.6696412Z ==10015==    by 0x97EA431: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.6697934Z ==10015==    by 0x9581890: ??? (in /usr/lib64/libnl-route-3.so.200.23.0)
2021-03-25T18:30:53.6699656Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6701009Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.6702058Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.6702954Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.6703809Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.6704705Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.6705591Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.6706524Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.6707437Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.6708189Z ==10015== 
2021-03-25T18:30:53.8820363Z ==10015== 64 bytes in 2 blocks are possibly lost in loss record 8,499 of 19,777
2021-03-25T18:30:53.8823090Z ==10015==    at 0x4C2B955: calloc (vg_replace_malloc.c:711)
2021-03-25T18:30:53.8825619Z ==10015==    by 0x97EA431: __trans_list_add (in /usr/lib64/libnl-3.so.200.23.0)
2021-03-25T18:30:53.8827996Z ==10015==    by 0x400F902: _dl_init (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.8830055Z ==10015==    by 0x4001159: ??? (in /usr/lib64/ld-2.17.so)
2021-03-25T18:30:53.8831414Z ==10015==    by 0x5: ???
2021-03-25T18:30:53.8832683Z ==10015==    by 0x1FFEFFEEC6: ???
2021-03-25T18:30:53.8833681Z ==10015==    by 0x1FFEFFEF0A: ???
2021-03-25T18:30:53.8834577Z ==10015==    by 0x1FFEFFEF1B: ???
2021-03-25T18:30:53.8835451Z ==10015==    by 0x1FFEFFEF1E: ???
2021-03-25T18:30:53.8836395Z ==10015==    by 0x1FFEFFEF21: ???
2021-03-25T18:30:53.8837231Z ==10015==    by 0x1FFEFFEF24: ???
2021-03-25T18:30:53.8838032Z ==10015== 
2021-03-25T18:30:54.1987873Z ==10015== 120 bytes in 1 blocks are possibly lost in loss record 11,100 of 19,777
2021-03-25T18:30:54.1990552Z ==10015==    at 0x5091776: ucs_strided_alloc_get (strided_alloc.c:162)
2021-03-25T18:30:54.1992418Z ==10015==    by 0x5855DD4: ucp_ep_create_base (ucp_ep.c:139)
2021-03-25T18:30:54.1993959Z ==10015==    by 0x58562DA: ucp_worker_create_ep (ucp_ep.c:293)
2021-03-25T18:30:54.1995603Z ==10015==    by 0x585A6D8: ucp_ep_create_to_sock_addr (ucp_ep.c:588)
2021-03-25T18:30:54.1997370Z ==10015==    by 0x585A6D8: ucp_ep_create (ucp_ep.c:802)
2021-03-25T18:30:54.1999245Z ==10015==    by 0x90BEAC: ucp_test_base::entity::connect(ucp_test_base::entity const*, ucp_ep_params const&, int, int) (ucp_test.cc:562)
2021-03-25T18:30:54.2001686Z ==10015==    by 0x8EC969: client_ep_connect_basic (test_ucp_sockaddr.cc:452)
2021-03-25T18:30:54.2003534Z ==10015==    by 0x8EC969: test_ucp_sockaddr::client_ep_connect() (test_ucp_sockaddr.cc:457)
2021-03-25T18:30:54.2005568Z ==10015==    by 0x8D6CBD: test_ucp_sockaddr_connect_and_fail_wireup_Test::test_body() (test_ucp_sockaddr.cc:974)
2021-03-25T18:30:54.2007435Z ==10015==    by 0x5EBA35: run (test.cc:365)
2021-03-25T18:30:54.2009002Z ==10015==    by 0x5EBA35: ucs::test_base::TestBodyProxy() (test.cc:391)
2021-03-25T18:30:54.2011687Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2014782Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2017713Z ==10015==    by 0x5C08AC: testing::Test::Run() (gtest-all.cc:3635)
2021-03-25T18:30:54.2019976Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2022194Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2024646Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2027007Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2029555Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2032343Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2034812Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2037004Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:54.2038514Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:54.2039699Z ==10015== 
2021-03-25T18:30:54.2041140Z ==10015== 120 bytes in 1 blocks are possibly lost in loss record 11,101 of 19,777
2021-03-25T18:30:54.2042818Z ==10015==    at 0x5091776: ucs_strided_alloc_get (strided_alloc.c:162)
2021-03-25T18:30:54.2044382Z ==10015==    by 0x5855DD4: ucp_ep_create_base (ucp_ep.c:139)
2021-03-25T18:30:54.2046048Z ==10015==    by 0x58562DA: ucp_worker_create_ep (ucp_ep.c:293)
2021-03-25T18:30:54.2047787Z ==10015==    by 0x585A21F: ucp_ep_create_to_worker_addr (ucp_ep.c:538)
2021-03-25T18:30:54.2049439Z ==10015==    by 0x58EBD75: ucp_ep_cm_server_create_connected (wireup_cm.c:1100)
2021-03-25T18:30:54.2051155Z ==10015==    by 0x5856FF7: ucp_ep_create_server_accept (ucp_ep.c:657)
2021-03-25T18:30:54.2052852Z ==10015==    by 0x585A842: ucp_ep_create_api_conn_request (ucp_ep.c:672)
2021-03-25T18:30:54.2054404Z ==10015==    by 0x585A842: ucp_ep_create (ucp_ep.c:804)
2021-03-25T18:30:54.2056245Z ==10015==    by 0x90874D: ucp_test_base::entity::accept(ucp_worker*, ucp_conn_request*) (ucp_test.cc:628)
2021-03-25T18:30:54.2058280Z ==10015==    by 0x90C36A: ucp_test_base::entity::progress(int) (ucp_test.cc:868)
2021-03-25T18:30:54.2059956Z ==10015==    by 0x90C436: ucp_test::progress(int) const (ucp_test.cc:155)
2021-03-25T18:30:54.2061675Z ==10015==    by 0x8F27D1: check_events (test_ucp_sockaddr.cc:302)
2021-03-25T18:30:54.2063397Z ==10015==    by 0x8F27D1: test_ucp_sockaddr::wait_for_server_ep(bool) (test_ucp_sockaddr.cc:404)
2021-03-25T18:30:54.2065324Z ==10015==    by 0x8D6CC7: test_ucp_sockaddr_connect_and_fail_wireup_Test::test_body() (test_ucp_sockaddr.cc:975)
2021-03-25T18:30:54.2067294Z ==10015==    by 0x5EBA35: run (test.cc:365)
2021-03-25T18:30:54.2068786Z ==10015==    by 0x5EBA35: ucs::test_base::TestBodyProxy() (test.cc:391)
2021-03-25T18:30:54.2071322Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2074600Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2077696Z ==10015==    by 0x5C08AC: testing::Test::Run() (gtest-all.cc:3635)
2021-03-25T18:30:54.2079867Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2082056Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2084470Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2086988Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2090411Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2093218Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2095590Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2097415Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:54.2099029Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:54.2100552Z ==10015== 
2021-03-25T18:30:54.2101940Z ==10015== 120 bytes in 1 blocks are definitely lost in loss record 11,102 of 19,777
2021-03-25T18:30:54.2103614Z ==10015==    at 0x5091776: ucs_strided_alloc_get (strided_alloc.c:162)
2021-03-25T18:30:54.2105157Z ==10015==    by 0x5855DD4: ucp_ep_create_base (ucp_ep.c:139)
2021-03-25T18:30:54.2106833Z ==10015==    by 0x58562DA: ucp_worker_create_ep (ucp_ep.c:293)
2021-03-25T18:30:54.2108465Z ==10015==    by 0x585A6D8: ucp_ep_create_to_sock_addr (ucp_ep.c:588)
2021-03-25T18:30:54.2109972Z ==10015==    by 0x585A6D8: ucp_ep_create (ucp_ep.c:802)
2021-03-25T18:30:54.2112254Z ==10015==    by 0x90BEAC: ucp_test_base::entity::connect(ucp_test_base::entity const*, ucp_ep_params const&, int, int) (ucp_test.cc:562)
2021-03-25T18:30:54.2114291Z ==10015==    by 0x8EC969: client_ep_connect_basic (test_ucp_sockaddr.cc:452)
2021-03-25T18:30:54.2116199Z ==10015==    by 0x8EC969: test_ucp_sockaddr::client_ep_connect() (test_ucp_sockaddr.cc:457)
2021-03-25T18:30:54.2118301Z ==10015==    by 0x8D6CBD: test_ucp_sockaddr_connect_and_fail_wireup_Test::test_body() (test_ucp_sockaddr.cc:974)
2021-03-25T18:30:54.2120061Z ==10015==    by 0x5EBA35: run (test.cc:365)
2021-03-25T18:30:54.2121617Z ==10015==    by 0x5EBA35: ucs::test_base::TestBodyProxy() (test.cc:391)
2021-03-25T18:30:54.2124114Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2127289Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2130070Z ==10015==    by 0x5C08AC: testing::Test::Run() (gtest-all.cc:3635)
2021-03-25T18:30:54.2132283Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2134390Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2136903Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2139206Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2141729Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2144496Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2147002Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2148583Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:54.2150080Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:54.2151323Z ==10015== 
2021-03-25T18:30:54.2152594Z ==10015== 120 bytes in 1 blocks are definitely lost in loss record 11,103 of 19,777
2021-03-25T18:30:54.2154555Z ==10015==    at 0x5091776: ucs_strided_alloc_get (strided_alloc.c:162)
2021-03-25T18:30:54.2156249Z ==10015==    by 0x5855DD4: ucp_ep_create_base (ucp_ep.c:139)
2021-03-25T18:30:54.2157861Z ==10015==    by 0x58562DA: ucp_worker_create_ep (ucp_ep.c:293)
2021-03-25T18:30:54.2159584Z ==10015==    by 0x585A21F: ucp_ep_create_to_worker_addr (ucp_ep.c:538)
2021-03-25T18:30:54.2161308Z ==10015==    by 0x58EBD75: ucp_ep_cm_server_create_connected (wireup_cm.c:1100)
2021-03-25T18:30:54.2162940Z ==10015==    by 0x5856FF7: ucp_ep_create_server_accept (ucp_ep.c:657)
2021-03-25T18:30:54.2164612Z ==10015==    by 0x585A842: ucp_ep_create_api_conn_request (ucp_ep.c:672)
2021-03-25T18:30:54.2166288Z ==10015==    by 0x585A842: ucp_ep_create (ucp_ep.c:804)
2021-03-25T18:30:54.2168071Z ==10015==    by 0x90874D: ucp_test_base::entity::accept(ucp_worker*, ucp_conn_request*) (ucp_test.cc:628)
2021-03-25T18:30:54.2169902Z ==10015==    by 0x90C36A: ucp_test_base::entity::progress(int) (ucp_test.cc:868)
2021-03-25T18:30:54.2171621Z ==10015==    by 0x90C436: ucp_test::progress(int) const (ucp_test.cc:155)
2021-03-25T18:30:54.2173284Z ==10015==    by 0x8F27D1: check_events (test_ucp_sockaddr.cc:302)
2021-03-25T18:30:54.2174979Z ==10015==    by 0x8F27D1: test_ucp_sockaddr::wait_for_server_ep(bool) (test_ucp_sockaddr.cc:404)
2021-03-25T18:30:54.2177077Z ==10015==    by 0x8D6CC7: test_ucp_sockaddr_connect_and_fail_wireup_Test::test_body() (test_ucp_sockaddr.cc:975)
2021-03-25T18:30:54.2178825Z ==10015==    by 0x5EBA35: run (test.cc:365)
2021-03-25T18:30:54.2180305Z ==10015==    by 0x5EBA35: ucs::test_base::TestBodyProxy() (test.cc:391)
2021-03-25T18:30:54.2182846Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2186281Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2189050Z ==10015==    by 0x5C08AC: testing::Test::Run() (gtest-all.cc:3635)
2021-03-25T18:30:54.2191166Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2193342Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2195890Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2198111Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2200589Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2203254Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2205620Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2207761Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:54.2209317Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:54.2211041Z ==10015== 
2021-03-25T18:30:54.2419782Z ==10015== 136 bytes in 1 blocks are possibly lost in loss record 11,581 of 19,777
2021-03-25T18:30:54.2421910Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.2423003Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.2424037Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.2425036Z ==10015==    by 0x508F170: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.2426183Z ==10015==    by 0x508F170: ucs_pgtable_insert_page (pgtable.c:316)
2021-03-25T18:30:54.2427254Z ==10015==    by 0x508F170: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.2428245Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.2429276Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.2430287Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.2431272Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.2432580Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.2433657Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.2434628Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.2435631Z ==10015==    by 0x5BA3E96: uct_ud_iface_t_init (ud_iface.c:528)
2021-03-25T18:30:54.2436849Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_init (ud_verbs.c:665)
2021-03-25T18:30:54.2437883Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_new (ud_verbs.c:716)
2021-03-25T18:30:54.2438905Z ==10015==    by 0x53D877F: uct_iface_open (uct_md.c:266)
2021-03-25T18:30:54.2439913Z ==10015==    by 0x586A4A4: ucp_worker_iface_open (ucp_worker.c:1260)
2021-03-25T18:30:54.2440958Z ==10015==    by 0x586D5CE: ucp_worker_add_resource_ifaces (ucp_worker.c:1077)
2021-03-25T18:30:54.2442036Z ==10015==    by 0x586D5CE: ucp_worker_create (ucp_worker.c:2112)
2021-03-25T18:30:54.2443372Z ==10015==    by 0x90D727: ucp_test_base::entity::entity(ucp_test_param const&, ucp_config*, ucp_worker_params const&, ucp_test_base const*) (ucp_test.cc:532)
2021-03-25T18:30:54.2444762Z ==10015==    by 0x90DEB3: ucp_test::create_entity(bool, ucp_test_param const&) (ucp_test.cc:127)
2021-03-25T18:30:54.2445888Z ==10015==    by 0x90E052: create_entity (ucp_test.cc:122)
2021-03-25T18:30:54.2446964Z ==10015==    by 0x90E052: ucp_test::init() (ucp_test.cc:93)
2021-03-25T18:30:54.2447969Z ==10015==    by 0x90439C: test_ucp_sockaddr::init() (test_ucp_sockaddr.cc:68)
2021-03-25T18:30:54.2449074Z ==10015==    by 0x5EB6FB: ucs::test_base::SetUpProxy() (test.cc:314)
2021-03-25T18:30:54.2450945Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2453150Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2454897Z ==10015==    by 0x5C080D: testing::Test::Run() (gtest-all.cc:3630)
2021-03-25T18:30:54.2456384Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2457820Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2459403Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2460964Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2462847Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2464754Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2466412Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2467507Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:54.2468484Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:54.2469225Z ==10015== 
2021-03-25T18:30:54.2470162Z ==10015== 136 bytes in 1 blocks are possibly lost in loss record 11,582 of 19,777
2021-03-25T18:30:54.2471208Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.2472161Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.2473170Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.2474191Z ==10015==    by 0x508F007: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.2475149Z ==10015==    by 0x508F007: ucs_pgtable_expand (pgtable.c:164)
2021-03-25T18:30:54.2476228Z ==10015==    by 0x508F007: ucs_pgtable_insert_page (pgtable.c:287)
2021-03-25T18:30:54.2477279Z ==10015==    by 0x508F007: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.2478250Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.2479271Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.2480475Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.2481451Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.2482517Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.2483594Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.2484552Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.2485562Z ==10015==    by 0x5BA3E96: uct_ud_iface_t_init (ud_iface.c:528)
2021-03-25T18:30:54.2486684Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_init (ud_verbs.c:665)
2021-03-25T18:30:54.2487755Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_new (ud_verbs.c:716)
2021-03-25T18:30:54.2488789Z ==10015==    by 0x53D877F: uct_iface_open (uct_md.c:266)
2021-03-25T18:30:54.2489809Z ==10015==    by 0x586A4A4: ucp_worker_iface_open (ucp_worker.c:1260)
2021-03-25T18:30:54.2490836Z ==10015==    by 0x586D5CE: ucp_worker_add_resource_ifaces (ucp_worker.c:1077)
2021-03-25T18:30:54.2491924Z ==10015==    by 0x586D5CE: ucp_worker_create (ucp_worker.c:2112)
2021-03-25T18:30:54.2493259Z ==10015==    by 0x90D727: ucp_test_base::entity::entity(ucp_test_param const&, ucp_config*, ucp_worker_params const&, ucp_test_base const*) (ucp_test.cc:532)
2021-03-25T18:30:54.2494682Z ==10015==    by 0x90DEB3: ucp_test::create_entity(bool, ucp_test_param const&) (ucp_test.cc:127)
2021-03-25T18:30:54.2495819Z ==10015==    by 0x90439C: test_ucp_sockaddr::init() (test_ucp_sockaddr.cc:68)
2021-03-25T18:30:54.2496978Z ==10015==    by 0x5EB6FB: ucs::test_base::SetUpProxy() (test.cc:314)
2021-03-25T18:30:54.2498566Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2501056Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2502913Z ==10015==    by 0x5C080D: testing::Test::Run() (gtest-all.cc:3630)
2021-03-25T18:30:54.2504339Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2505819Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2507416Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2508918Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2510510Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2512236Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2513824Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2514920Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:54.2515980Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:54.2516774Z ==10015== 
2021-03-25T18:30:54.2517662Z ==10015== 136 bytes in 1 blocks are possibly lost in loss record 11,583 of 19,777
2021-03-25T18:30:54.2518706Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.2519664Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.2520683Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.2521701Z ==10015==    by 0x508F170: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.2522680Z ==10015==    by 0x508F170: ucs_pgtable_insert_page (pgtable.c:316)
2021-03-25T18:30:54.2523712Z ==10015==    by 0x508F170: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.2524734Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.2525710Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.2526779Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.2528001Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.2529023Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.2530098Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.2546371Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.2547981Z ==10015==    by 0x5BA3E96: uct_ud_iface_t_init (ud_iface.c:528)
2021-03-25T18:30:54.2549170Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_init (ud_verbs.c:665)
2021-03-25T18:30:54.2550236Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_new (ud_verbs.c:716)
2021-03-25T18:30:54.2551357Z ==10015==    by 0x53D877F: uct_iface_open (uct_md.c:266)
2021-03-25T18:30:54.2552420Z ==10015==    by 0x586A4A4: ucp_worker_iface_open (ucp_worker.c:1260)
2021-03-25T18:30:54.2553501Z ==10015==    by 0x586D5CE: ucp_worker_add_resource_ifaces (ucp_worker.c:1077)
2021-03-25T18:30:54.2554611Z ==10015==    by 0x586D5CE: ucp_worker_create (ucp_worker.c:2112)
2021-03-25T18:30:54.2555999Z ==10015==    by 0x90D727: ucp_test_base::entity::entity(ucp_test_param const&, ucp_config*, ucp_worker_params const&, ucp_test_base const*) (ucp_test.cc:532)
2021-03-25T18:30:54.2557443Z ==10015==    by 0x90DEB3: ucp_test::create_entity(bool, ucp_test_param const&) (ucp_test.cc:127)
2021-03-25T18:30:54.2558560Z ==10015==    by 0x90439C: test_ucp_sockaddr::init() (test_ucp_sockaddr.cc:68)
2021-03-25T18:30:54.2559647Z ==10015==    by 0x5EB6FB: ucs::test_base::SetUpProxy() (test.cc:314)
2021-03-25T18:30:54.2561388Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2563385Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2565315Z ==10015==    by 0x5C080D: testing::Test::Run() (gtest-all.cc:3630)
2021-03-25T18:30:54.2566797Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2568228Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2569789Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2571219Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2572850Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2574627Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2576195Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2577292Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:54.2578232Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:54.2578957Z ==10015== 
2021-03-25T18:30:54.2579807Z ==10015== 136 bytes in 1 blocks are possibly lost in loss record 11,584 of 19,777
2021-03-25T18:30:54.2580846Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.2581911Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.2582907Z ==10015==    by 0x508DAF3: ucs_mpool_get_inline (mpool.inl:23)
2021-03-25T18:30:54.2583872Z ==10015==    by 0x508DAF3: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.2585127Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.2586339Z ==10015==    by 0x508F007: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.2587349Z ==10015==    by 0x508F007: ucs_pgtable_expand (pgtable.c:164)
2021-03-25T18:30:54.2588312Z ==10015==    by 0x508F007: ucs_pgtable_insert_page (pgtable.c:287)
2021-03-25T18:30:54.2589337Z ==10015==    by 0x508F007: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.2590339Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.2591328Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.2592556Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.2593560Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.2594550Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.2595612Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.2596685Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.2597622Z ==10015==    by 0x5BA3E96: uct_ud_iface_t_init (ud_iface.c:528)
2021-03-25T18:30:54.2598654Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_init (ud_verbs.c:665)
2021-03-25T18:30:54.2599696Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_new (ud_verbs.c:716)
2021-03-25T18:30:54.2600645Z ==10015==    by 0x53D877F: uct_iface_open (uct_md.c:266)
2021-03-25T18:30:54.2601702Z ==10015==    by 0x586A4A4: ucp_worker_iface_open (ucp_worker.c:1260)
2021-03-25T18:30:54.2602765Z ==10015==    by 0x586D5CE: ucp_worker_add_resource_ifaces (ucp_worker.c:1077)
2021-03-25T18:30:54.2603768Z ==10015==    by 0x586D5CE: ucp_worker_create (ucp_worker.c:2112)
2021-03-25T18:30:54.2605140Z ==10015==    by 0x90D727: ucp_test_base::entity::entity(ucp_test_param const&, ucp_config*, ucp_worker_params const&, ucp_test_base const*) (ucp_test.cc:532)
2021-03-25T18:30:54.2606622Z ==10015==    by 0x90DEB3: ucp_test::create_entity(bool, ucp_test_param const&) (ucp_test.cc:127)
2021-03-25T18:30:54.2607723Z ==10015==    by 0x90E052: create_entity (ucp_test.cc:122)
2021-03-25T18:30:54.2608663Z ==10015==    by 0x90E052: ucp_test::init() (ucp_test.cc:93)
2021-03-25T18:30:54.2609702Z ==10015==    by 0x90439C: test_ucp_sockaddr::init() (test_ucp_sockaddr.cc:68)
2021-03-25T18:30:54.2610955Z ==10015==    by 0x5EB6FB: ucs::test_base::SetUpProxy() (test.cc:314)
2021-03-25T18:30:54.2612557Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2614551Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2616487Z ==10015==    by 0x5C080D: testing::Test::Run() (gtest-all.cc:3630)
2021-03-25T18:30:54.2617910Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2619264Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2620837Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2622631Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2624257Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2626096Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2627680Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2628598Z ==10015== 
2021-03-25T18:30:54.2629413Z ==10015== 136 bytes in 1 blocks are possibly lost in loss record 11,585 of 19,777
2021-03-25T18:30:54.2630450Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.2631422Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.2632434Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.2633454Z ==10015==    by 0x508F007: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.2634429Z ==10015==    by 0x508F007: ucs_pgtable_expand (pgtable.c:164)
2021-03-25T18:30:54.2635393Z ==10015==    by 0x508F007: ucs_pgtable_insert_page (pgtable.c:287)
2021-03-25T18:30:54.2636482Z ==10015==    by 0x508F007: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.2637494Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.2638447Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.2639662Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.2640663Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.2641718Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.2642776Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.2643766Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.2644706Z ==10015==    by 0x5BA3E96: uct_ud_iface_t_init (ud_iface.c:528)
2021-03-25T18:30:54.2645734Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_init (ud_verbs.c:665)
2021-03-25T18:30:54.2646846Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_new (ud_verbs.c:716)
2021-03-25T18:30:54.2647824Z ==10015==    by 0x53D877F: uct_iface_open (uct_md.c:266)
2021-03-25T18:30:54.2648826Z ==10015==    by 0x586A4A4: ucp_worker_iface_open (ucp_worker.c:1260)
2021-03-25T18:30:54.2649887Z ==10015==    by 0x586D5CE: ucp_worker_add_resource_ifaces (ucp_worker.c:1077)
2021-03-25T18:30:54.2650902Z ==10015==    by 0x586D5CE: ucp_worker_create (ucp_worker.c:2112)
2021-03-25T18:30:54.2652265Z ==10015==    by 0x90D727: ucp_test_base::entity::entity(ucp_test_param const&, ucp_config*, ucp_worker_params const&, ucp_test_base const*) (ucp_test.cc:532)
2021-03-25T18:30:54.2653679Z ==10015==    by 0x90DEB3: ucp_test::create_entity(bool, ucp_test_param const&) (ucp_test.cc:127)
2021-03-25T18:30:54.2654803Z ==10015==    by 0x90E052: create_entity (ucp_test.cc:122)
2021-03-25T18:30:54.2655792Z ==10015==    by 0x90E052: ucp_test::init() (ucp_test.cc:93)
2021-03-25T18:30:54.2656912Z ==10015==    by 0x90439C: test_ucp_sockaddr::init() (test_ucp_sockaddr.cc:68)
2021-03-25T18:30:54.2657931Z ==10015==    by 0x5EB6FB: ucs::test_base::SetUpProxy() (test.cc:314)
2021-03-25T18:30:54.2660041Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2662117Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2663905Z ==10015==    by 0x5C080D: testing::Test::Run() (gtest-all.cc:3630)
2021-03-25T18:30:54.2665319Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2666809Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2668377Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2669849Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2671369Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2673143Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2674701Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2675721Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:54.2676718Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:54.2677492Z ==10015== 
2021-03-25T18:30:54.2678299Z ==10015== 136 bytes in 1 blocks are possibly lost in loss record 11,586 of 19,777
2021-03-25T18:30:54.2679340Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.2680310Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.2681247Z ==10015==    by 0x508DAF3: ucs_mpool_get_inline (mpool.inl:23)
2021-03-25T18:30:54.2682337Z ==10015==    by 0x508DAF3: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.2683419Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.2684391Z ==10015==    by 0x508F007: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.2685389Z ==10015==    by 0x508F007: ucs_pgtable_expand (pgtable.c:164)
2021-03-25T18:30:54.2686663Z ==10015==    by 0x508F007: ucs_pgtable_insert_page (pgtable.c:287)
2021-03-25T18:30:54.2687638Z ==10015==    by 0x508F007: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.2688649Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.2689635Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.2690575Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.2691646Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.2692680Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.2693694Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.2694690Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.2695678Z ==10015==    by 0x5BA3E96: uct_ud_iface_t_init (ud_iface.c:528)
2021-03-25T18:30:54.2696994Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_init (ud_verbs.c:665)
2021-03-25T18:30:54.2698099Z ==10015==    by 0x5BB26B3: uct_ud_verbs_iface_t_new (ud_verbs.c:716)
2021-03-25T18:30:54.2699146Z ==10015==    by 0x53D877F: uct_iface_open (uct_md.c:266)
2021-03-25T18:30:54.2700109Z ==10015==    by 0x586A4A4: ucp_worker_iface_open (ucp_worker.c:1260)
2021-03-25T18:30:54.2701172Z ==10015==    by 0x586D5CE: ucp_worker_add_resource_ifaces (ucp_worker.c:1077)
2021-03-25T18:30:54.2702294Z ==10015==    by 0x586D5CE: ucp_worker_create (ucp_worker.c:2112)
2021-03-25T18:30:54.2703549Z ==10015==    by 0x90D727: ucp_test_base::entity::entity(ucp_test_param const&, ucp_config*, ucp_worker_params const&, ucp_test_base const*) (ucp_test.cc:532)
2021-03-25T18:30:54.2705035Z ==10015==    by 0x90DEB3: ucp_test::create_entity(bool, ucp_test_param const&) (ucp_test.cc:127)
2021-03-25T18:30:54.2706464Z ==10015==    by 0x90439C: test_ucp_sockaddr::init() (test_ucp_sockaddr.cc:68)
2021-03-25T18:30:54.2707551Z ==10015==    by 0x5EB6FB: ucs::test_base::SetUpProxy() (test.cc:314)
2021-03-25T18:30:54.2709093Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.2711126Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.2712902Z ==10015==    by 0x5C080D: testing::Test::Run() (gtest-all.cc:3630)
2021-03-25T18:30:54.2714302Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.2715654Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.2717279Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.2718767Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.2720293Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.2722115Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.2723692Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.2724715Z ==10015==    by 0x55891C: RUN_ALL_TESTS (gtest.h:20059)
2021-03-25T18:30:54.2725664Z ==10015==    by 0x55891C: main (main.cc:105)
2021-03-25T18:30:54.2726499Z ==10015== 
2021-03-25T18:30:54.6994571Z ==10015== 272 bytes in 2 blocks are possibly lost in loss record 15,319 of 19,777
2021-03-25T18:30:54.6996254Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.6997255Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.6998184Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.6999106Z ==10015==    by 0x508F007: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.6999935Z ==10015==    by 0x508F007: ucs_pgtable_expand (pgtable.c:164)
2021-03-25T18:30:54.7000841Z ==10015==    by 0x508F007: ucs_pgtable_insert_page (pgtable.c:287)
2021-03-25T18:30:54.7002083Z ==10015==    by 0x508F007: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.7002982Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.7003825Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.7004702Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.7005641Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.7006840Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.7007828Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.7008712Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.7009535Z ==10015==    by 0x508D997: ucs_mpool_get_grow (mpool.c:238)
2021-03-25T18:30:54.7010418Z ==10015==    by 0x5B467AE: ucs_mpool_get_inline (mpool.inl:23)
2021-03-25T18:30:54.7011327Z ==10015==    by 0x5B467AE: uct_ib_iface_prepare_rx_wrs (ib_iface.c:1397)
2021-03-25T18:30:54.7012278Z ==10015==    by 0x5BAD1C4: uct_ud_verbs_iface_post_recv_always (ud_verbs.c:607)
2021-03-25T18:30:54.7013260Z ==10015==    by 0x5BADA27: uct_ud_verbs_iface_post_recv (ud_verbs.c:628)
2021-03-25T18:30:54.7014191Z ==10015==    by 0x5BADA27: uct_ud_verbs_iface_poll_rx (ud_verbs.c:420)
2021-03-25T18:30:54.7015097Z ==10015==    by 0x5BADA27: uct_ud_verbs_iface_progress (ud_verbs.c:452)
2021-03-25T18:30:54.7016189Z ==10015==    by 0x508A19A: ucs_callbackq_slow_proxy (callbackq.c:402)
2021-03-25T18:30:54.7017141Z ==10015==    by 0x586EDA9: ucs_callbackq_dispatch (callbackq.h:211)
2021-03-25T18:30:54.7017997Z ==10015==    by 0x586EDA9: uct_worker_progress (uct.h:2559)
2021-03-25T18:30:54.7018888Z ==10015==    by 0x586EDA9: ucp_worker_progress (ucp_worker.c:2451)
2021-03-25T18:30:54.7020111Z ==10015==    by 0x90C38A: ucp_test_base::entity::progress(int) (ucp_test.cc:873)
2021-03-25T18:30:54.7021072Z ==10015==    by 0x90C436: ucp_test::progress(int) const (ucp_test.cc:155)
2021-03-25T18:30:54.7022031Z ==10015==    by 0x8F27D1: check_events (test_ucp_sockaddr.cc:302)
2021-03-25T18:30:54.7023042Z ==10015==    by 0x8F27D1: test_ucp_sockaddr::wait_for_server_ep(bool) (test_ucp_sockaddr.cc:404)
2021-03-25T18:30:54.7024187Z ==10015==    by 0x8D6CC7: test_ucp_sockaddr_connect_and_fail_wireup_Test::test_body() (test_ucp_sockaddr.cc:975)
2021-03-25T18:30:54.7025219Z ==10015==    by 0x5EBA35: run (test.cc:365)
2021-03-25T18:30:54.7026138Z ==10015==    by 0x5EBA35: ucs::test_base::TestBodyProxy() (test.cc:391)
2021-03-25T18:30:54.7027986Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.7029901Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.7031630Z ==10015==    by 0x5C08AC: testing::Test::Run() (gtest-all.cc:3635)
2021-03-25T18:30:54.7032962Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.7034279Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.7035718Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:54.7037425Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:54.7038947Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:54.7040616Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:54.7042105Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:54.7042973Z ==10015== 
2021-03-25T18:30:54.8110522Z ==10015== 408 bytes in 3 blocks are possibly lost in loss record 16,328 of 19,777
2021-03-25T18:30:54.8112767Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.8114338Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.8115400Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.8116700Z ==10015==    by 0x508F170: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.8117870Z ==10015==    by 0x508F170: ucs_pgtable_insert_page (pgtable.c:316)
2021-03-25T18:30:54.8118910Z ==10015==    by 0x508F170: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.8120008Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.8121115Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.8122143Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.8123249Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.8124370Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.8125447Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.8126676Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.8127756Z ==10015==    by 0x508D997: ucs_mpool_get_grow (mpool.c:238)
2021-03-25T18:30:54.8128764Z ==10015==    by 0x508DAF3: ucs_mpool_get_inline (mpool.inl:23)
2021-03-25T18:30:54.8129821Z ==10015==    by 0x508DAF3: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.8130885Z ==10015==    by 0x5BAF51A: uct_ud_iface_get_tx_skb (ud_inl.h:56)
2021-03-25T18:30:54.8131971Z ==10015==    by 0x5BAF51A: uct_ud_ep_get_tx_skb (ud_inl.h:124)
2021-03-25T18:30:54.8133064Z ==10015==    by 0x5BAF51A: uct_ud_am_skb_common (ud_inl.h:206)
2021-03-25T18:30:54.8134164Z ==10015==    by 0x5BAF51A: uct_ud_verbs_ep_am_bcopy (ud_verbs.c:247)
2021-03-25T18:30:54.8135398Z ==10015==    by 0x585D630: uct_ep_am_bcopy (uct.h:2811)
2021-03-25T18:30:54.8136634Z ==10015==    by 0x585D630: ucp_ep_do_uct_ep_keepalive (ucp_ep.c:2630)
2021-03-25T18:30:54.8137825Z ==10015==    by 0x585D7F9: ucp_ep_do_keepalive (ucp_ep.c:2657)
2021-03-25T18:30:54.8138921Z ==10015==    by 0x58685A3: ucp_worker_do_keepalive_progress (ucp_worker.c:2788)
2021-03-25T18:30:54.8140094Z ==10015==    by 0x508A19A: ucs_callbackq_slow_proxy (callbackq.c:402)
2021-03-25T18:30:54.8141214Z ==10015==    by 0x586EDA9: ucs_callbackq_dispatch (callbackq.h:211)
2021-03-25T18:30:54.8142343Z ==10015==    by 0x586EDA9: uct_worker_progress (uct.h:2559)
2021-03-25T18:30:54.8143378Z ==10015==    by 0x586EDA9: ucp_worker_progress (ucp_worker.c:2451)
2021-03-25T18:30:54.8144533Z ==10015==    by 0x90C38A: ucp_test_base::entity::progress(int) (ucp_test.cc:873)
2021-03-25T18:30:54.8145709Z ==10015==    by 0x90C436: ucp_test::progress(int) const (ucp_test.cc:155)
2021-03-25T18:30:54.8146896Z ==10015==    by 0x8F27D1: check_events (test_ucp_sockaddr.cc:302)
2021-03-25T18:30:54.8148131Z ==10015==    by 0x8F27D1: test_ucp_sockaddr::wait_for_server_ep(bool) (test_ucp_sockaddr.cc:404)
2021-03-25T18:30:54.8149518Z ==10015==    by 0x8D6CC7: test_ucp_sockaddr_connect_and_fail_wireup_Test::test_body() (test_ucp_sockaddr.cc:975)
2021-03-25T18:30:54.8150672Z ==10015==    by 0x5EBA35: run (test.cc:365)
2021-03-25T18:30:54.8151778Z ==10015==    by 0x5EBA35: ucs::test_base::TestBodyProxy() (test.cc:391)
2021-03-25T18:30:54.8153872Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.8156074Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.8158044Z ==10015==    by 0x5C08AC: testing::Test::Run() (gtest-all.cc:3635)
2021-03-25T18:30:54.8159566Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.8161126Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.8162064Z ==10015== 
2021-03-25T18:30:54.8163230Z ==10015== 408 bytes in 3 blocks are possibly lost in loss record 16,329 of 19,777
2021-03-25T18:30:54.8164571Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.8165665Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.8166852Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.8167950Z ==10015==    by 0x508F170: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.8168983Z ==10015==    by 0x508F170: ucs_pgtable_insert_page (pgtable.c:316)
2021-03-25T18:30:54.8170076Z ==10015==    by 0x508F170: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.8171160Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.8172179Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.8173247Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.8174333Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.8175398Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.8176740Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.8177779Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.8178836Z ==10015==    by 0x508D997: ucs_mpool_get_grow (mpool.c:238)
2021-03-25T18:30:54.8179918Z ==10015==    by 0x508DAF3: ucs_mpool_get_inline (mpool.inl:23)
2021-03-25T18:30:54.8180915Z ==10015==    by 0x508DAF3: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.8182037Z ==10015==    by 0x5BAF51A: uct_ud_iface_get_tx_skb (ud_inl.h:56)
2021-03-25T18:30:54.8183134Z ==10015==    by 0x5BAF51A: uct_ud_ep_get_tx_skb (ud_inl.h:124)
2021-03-25T18:30:54.8184159Z ==10015==    by 0x5BAF51A: uct_ud_am_skb_common (ud_inl.h:206)
2021-03-25T18:30:54.8185270Z ==10015==    by 0x5BAF51A: uct_ud_verbs_ep_am_bcopy (ud_verbs.c:247)
2021-03-25T18:30:54.8186664Z ==10015==    by 0x585D630: uct_ep_am_bcopy (uct.h:2811)
2021-03-25T18:30:54.8187700Z ==10015==    by 0x585D630: ucp_ep_do_uct_ep_keepalive (ucp_ep.c:2630)
2021-03-25T18:30:54.8188840Z ==10015==    by 0x585D31E: ucp_ep_do_uct_ep_keepalive (ucp_ep.c:2611)
2021-03-25T18:30:54.8190027Z ==10015==    by 0x585D7F9: ucp_ep_do_keepalive (ucp_ep.c:2657)
2021-03-25T18:30:54.8191114Z ==10015==    by 0x58685A3: ucp_worker_do_keepalive_progress (ucp_worker.c:2788)
2021-03-25T18:30:54.8192337Z ==10015==    by 0x508A19A: ucs_callbackq_slow_proxy (callbackq.c:402)
2021-03-25T18:30:54.8193473Z ==10015==    by 0x586EDA9: ucs_callbackq_dispatch (callbackq.h:211)
2021-03-25T18:30:54.8194562Z ==10015==    by 0x586EDA9: uct_worker_progress (uct.h:2559)
2021-03-25T18:30:54.8195648Z ==10015==    by 0x586EDA9: ucp_worker_progress (ucp_worker.c:2451)
2021-03-25T18:30:54.8197001Z ==10015==    by 0x90C38A: ucp_test_base::entity::progress(int) (ucp_test.cc:873)
2021-03-25T18:30:54.8198156Z ==10015==    by 0x90C436: ucp_test::progress(int) const (ucp_test.cc:155)
2021-03-25T18:30:54.8199459Z ==10015==    by 0x8D6D44: test_ucp_sockaddr_connect_and_fail_wireup_Test::test_body() (test_ucp_sockaddr.cc:987)
2021-03-25T18:30:54.8200667Z ==10015==    by 0x5EBA35: run (test.cc:365)
2021-03-25T18:30:54.8201701Z ==10015==    by 0x5EBA35: ucs::test_base::TestBodyProxy() (test.cc:391)
2021-03-25T18:30:54.8203510Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:54.8205646Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:54.8207611Z ==10015==    by 0x5C08AC: testing::Test::Run() (gtest-all.cc:3635)
2021-03-25T18:30:54.8209189Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:54.8210671Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:54.8211677Z ==10015== 
2021-03-25T18:30:54.9960977Z ==10015== 952 bytes in 7 blocks are possibly lost in loss record 17,846 of 19,777
2021-03-25T18:30:54.9962806Z ==10015==    at 0x508DADC: ucs_mpool_get_inline (mpool.inl:34)
2021-03-25T18:30:54.9964158Z ==10015==    by 0x508DADC: ucs_mpool_get (mpool.c:166)
2021-03-25T18:30:54.9965216Z ==10015==    by 0x509CB9F: ucs_rcache_pgt_dir_alloc (rcache.c:141)
2021-03-25T18:30:54.9966481Z ==10015==    by 0x508F170: ucs_pgt_dir_alloc (pgtable.c:73)
2021-03-25T18:30:54.9967569Z ==10015==    by 0x508F170: ucs_pgtable_insert_page (pgtable.c:316)
2021-03-25T18:30:54.9968633Z ==10015==    by 0x508F170: ucs_pgtable_insert (pgtable.c:420)
2021-03-25T18:30:54.9969631Z ==10015==    by 0x509EC82: ucs_rcache_create_region (rcache.c:811)
2021-03-25T18:30:54.9970675Z ==10015==    by 0x509EC82: ucs_rcache_get (rcache.c:926)
2021-03-25T18:30:54.9971737Z ==10015==    by 0x5B47DD4: uct_ib_mem_rcache_reg (ib_md.c:1010)
2021-03-25T18:30:54.9972747Z ==10015==    by 0x53D97E6: uct_iface_mem_alloc (uct_mem.c:376)
2021-03-25T18:30:54.9973843Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc_inner (uct_mem.c:423)
2021-03-25T18:30:54.9974943Z ==10015==    by 0x53D9899: uct_iface_mp_chunk_alloc (uct_mem.c:413)
2021-03-25T18:30:54.9976015Z ==10015==    by 0x508D720: ucs_mpool_grow (mpool.c:190)
2021-03-25T18:30:54.9977084Z ==10015==    by 0x508D997: ucs_mpool_get_grow (mpool.c:238)
2021-03-25T18:30:54.9978150Z ==10015==    by 0x5B467AE: ucs_mpool_get_inline (mpool.inl:23)
2021-03-25T18:30:54.9979195Z ==10015==    by 0x5B467AE: uct_ib_iface_prepare_rx_wrs (ib_iface.c:1397)
2021-03-25T18:30:54.9980340Z ==10015==    by 0x5BAD1C4: uct_ud_verbs_iface_post_recv_always (ud_verbs.c:607)
2021-03-25T18:30:54.9981474Z ==10015==    by 0x5BADA27: uct_ud_verbs_iface_post_recv (ud_verbs.c:628)
2021-03-25T18:30:54.9982566Z ==10015==    by 0x5BADA27: uct_ud_verbs_iface_poll_rx (ud_verbs.c:420)
2021-03-25T18:30:54.9983621Z ==10015==    by 0x5BADA27: uct_ud_verbs_iface_progress (ud_verbs.c:452)
2021-03-25T18:30:54.9984961Z ==10015==    by 0x508A19A: ucs_callbackq_slow_proxy (callbackq.c:402)
2021-03-25T18:30:54.9986177Z ==10015==    by 0x586EDA9: ucs_callbackq_dispatch (callbackq.h:211)
2021-03-25T18:30:54.9987239Z ==10015==    by 0x586EDA9: uct_worker_progress (uct.h:2559)
2021-03-25T18:30:54.9988312Z ==10015==    by 0x586EDA9: ucp_worker_progress (ucp_worker.c:2451)
2021-03-25T18:30:54.9989494Z ==10015==    by 0x90C38A: ucp_test_base::entity::progress(int) (ucp_test.cc:873)
2021-03-25T18:30:54.9990599Z ==10015==    by 0x90C436: ucp_test::progress(int) const (ucp_test.cc:155)
2021-03-25T18:30:54.9991699Z ==10015==    by 0x8F27D1: check_events (test_ucp_sockaddr.cc:302)
2021-03-25T18:30:54.9992848Z ==10015==    by 0x8F27D1: test_ucp_sockaddr::wait_for_server_ep(bool) (test_ucp_sockaddr.cc:404)
2021-03-25T18:30:54.9994134Z ==10015==    by 0x8D6CC7: test_ucp_sockaddr_connect_and_fail_wireup_Test::test_body() (test_ucp_sockaddr.cc:975)
2021-03-25T18:30:54.9995282Z ==10015==    by 0x5EBA35: run (test.cc:365)
2021-03-25T18:30:54.9996456Z ==10015==    by 0x5EBA35: ucs::test_base::TestBodyProxy() (test.cc:391)
2021-03-25T18:30:54.9998427Z ==10015==    by 0x5CC668: HandleSehExceptionsInMethodIfSupported<testing::Test, void> (gtest-all.cc:3562)
2021-03-25T18:30:55.0000537Z ==10015==    by 0x5CC668: void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) (gtest-all.cc:3598)
2021-03-25T18:30:55.0002446Z ==10015==    by 0x5C08AC: testing::Test::Run() (gtest-all.cc:3635)
2021-03-25T18:30:55.0003921Z ==10015==    by 0x5C0984: testing::TestInfo::Run() (gtest-all.cc:3812)
2021-03-25T18:30:55.0005320Z ==10015==    by 0x5C0AEE: testing::TestCase::Run() (gtest-all.cc:3930)
2021-03-25T18:30:55.0007061Z ==10015==    by 0x5C529C: testing::internal::UnitTestImpl::RunAllTests() [clone .part.343] (gtest-all.cc:5808)
2021-03-25T18:30:55.0008702Z ==10015==    by 0x5C557F: RunAllTests (gtest-all.cc:5725)
2021-03-25T18:30:55.0010294Z ==10015==    by 0x5C557F: HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3562)
2021-03-25T18:30:55.0012187Z ==10015==    by 0x5C557F: HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool> (gtest-all.cc:3598)
2021-03-25T18:30:55.0014024Z ==10015==    by 0x5C557F: testing::UnitTest::Run() (gtest-all.cc:5422)
2021-03-25T18:30:55.0014984Z ==10015== 
2021-03-25T18:30:55.1770091Z ==10015== LEAK SUMMARY:
2021-03-25T18:30:55.1771808Z ==10015==    definitely lost: 240 bytes in 2 blocks
2021-03-25T18:30:55.1772905Z ==10015==    indirectly lost: 0 bytes in 0 blocks
2021-03-25T18:30:55.1773996Z ==10015==      possibly lost: 3,484 bytes in 43 blocks
2021-03-25T18:30:55.1775002Z ==10015==    still reachable: 15,096,075 bytes in 196,932 blocks
2021-03-25T18:30:55.1776126Z ==10015==                       of which reachable via heuristic:
2021-03-25T18:30:55.1777288Z ==10015==                         stdstring          : 2,380,477 bytes in 58,252 blocks
2021-03-25T18:30:55.1778430Z ==10015==         suppressed: 9,643,988 bytes in 12,735 blocks
2021-03-25T18:30:55.1779521Z ==10015== Reachable blocks (those to which a pointer was found) are not shown.
2021-03-25T18:30:55.1781388Z ==10015== To see them, rerun with: --leak-check=full --show-leak-kinds=all
2021-03-25T18:30:55.1782386Z ==10015== 
2021-03-25T18:30:55.1783761Z ==10015== For counts of detected and suppressed errors, rerun with: -v
2021-03-25T18:30:55.1785006Z ==10015== ERROR SUMMARY: 32 errors from 32 contexts (suppressed: 49068 from 64)
2021-03-25T18:30:55.3918672Z make: *** [test_valgrind] Terminated
2021-03-25T18:30:55.4070108Z ##[error]Bash exited with code '124'.
2021-03-25T18:30:55.4105105Z ##[section]Finishing: Run ./contrib/test_jenkins.sh
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Remove EP ID dependant progress functions after releasing EP ID.
Release EP ID only when EP `refcount` reaches `0`

## Why ?

Fixes #6568
The bug was introduced in #6459 when moved filtering and removing progress functions to the place where EP is really destroyed, i.e. when UCP EP `refcount` reaches `0`.
So, it happens that UCP EP ID is released, but a progress function for sending WIREUP_MSG/ACK packet is scheduled and trying to get UCP EP ID which is released.

## How ?

1. Introduced `ucp_ep_set_failed()` that did all needed actions prior to setting `FAILED` flag to UCP EP, i.e. releases EP ID and deschedules progress callback for sending WIREUP_MSG/ACK packet.
2. Move releasing of UCP EP ID to the place when UCP EP is really destroyed, i.e. calling `ucp_ep_set_failed()` in `ucp_ep_destroy_base()`
3. Reset local EP ID set in TMP EP - just for debugging purposes.
4. When destroying UCP EP due to some failure in `ucp_worker_create_ep()`, call `ucp_ep_set_failed()` prior it to release ID if it was already allocated.

### CODE REVIEW

**Comment by yosefe** [comment]
isn't it enough to just release id after refcount reaches 0?

**Comment by dmitrygx** [comment]
> isn't it enough to just release id after refcount reaches 0?

Unfortunately, no. I tried this, but it happens that after moving to FAILED state (i.e. settign FAILED flag on UCP EP) and releasing the request ID, it can happen that sending `WIREUP_MSG/ACK` is scheduled on progress and will try to get a local ID.

File: src/ucp/wireup/wireup_cm.c [hunk 1]
```diff
@@ -482,6 +482,9 @@ void ucp_cm_client_restore_ep(ucp_wireup_ep_t *wireup_cm_ep, ucp_ep_h ucp_ep)
         }
     }
 
+    /* TMP EP is not an owner of local EP ID */
+    ucs_assert(ucp_ep_local_id(tmp_ep) == ucp_ep_local_id(ucp_ep));
+    ucp_ep_ext_control(tmp_ep)->local_ep_id = UCP_EP_ID_INVALID;
```
Comment (brminich) [inline src/ucp/wireup/wireup_cm.c:487]: is it really needed, given that we destroy `tmp_ep` on the line below?

Comment (dmitrygx) [reply src/ucp/wireup/wireup_cm.c:487]: I just wanted to make sure that `ucp_ep_destroy` function won't try to destroy `local_ep_id` for TMP EP (it will fail an assertion in `ucp_ep_release_id()` which expects that ID is not INVALID one), because a normal UCP EP (i.e. owner of this TMP EP) is responsible for it.
this is just for debugging purposes and was helpful for me to debug problem, when TMP EP released an EP ID, but UCP EP can't do it, because its EP ID is unknown for PTR MAP.

Comment (brminich) [reply src/ucp/wireup/wireup_cm.c:487]: ok

**Comment by yosefe** [comment]
> > isn't it enough to just release id after refcount reaches 0?
> 
> Unfortunately, no. I tried this, but it happens that after moving to FAILED state (i.e. settign FAILED flag on UCP EP) and releasing the request ID, it can happen that sending `WIREUP_MSG/ACK` is scheduled on progress and will try to get a local ID.
> So, after releasing local EP ID, we should remove from progress queue callbacks which are using local EP ID, i.e. now we have only sending `WIRERUP_MSG/ACK` callback that relies on local EP ID and is scheduled to callbackq.

Sorry, I meant releasing *endpoint* ID after refcount reaches 0

**Comment by dmitrygx** [comment]
> > > isn't it enough to just release id after refcount reaches 0?
> > 
> > 
> > Unfortunately, no. I tried this, but it happens that after moving to FAILED state (i.e. settign FAILED flag on UCP EP) and releasing the request ID, it can happen that sending `WIREUP_MSG/ACK` is scheduled on progress and will try to get a local ID.
> > So, after releasing local EP ID, we should remove from progress queue callbacks which are using local EP ID, i.e. now we have only sending `WIRERUP_MSG/ACK` callback that relies on local EP ID and is scheduled to callbackq.
> 
> Sorry, I meant releasing _endpoint_ ID after refcount reaches 0

I think we release endpoint IDs when detected peer failure to not handle messages from a remote peer and just will drop the messages

**Comment by dmitrygx** [comment]
@brminich @yosefe could you review pls?

**Review by brminich — APPROVED** [review]

File: src/ucp/core/ucp_ep.c [hunk 2]
```diff
@@ -259,6 +259,14 @@ static void ucp_ep_destroy_base(ucp_ep_h ep)
     ucs_assert(ep->discard_refcount == 0);
 
     ucp_ep_remove_progress_callbacks(ep);
+
+    /* Release UCP EP ID after all outstanding/pending operations are purged
+     * (e.g. using discarding) or flushed (i.e. UCP EP refcount reaches '0')
+     * and all progress callbacks are descheduled to avoid trying to get UCP EP
+     * ID for some operation (e.g. getting UCP EP ID for sending WIREUP_MSG/ACK
+     * from a progress callback) */
+    ucp_ep_set_failed(ep);
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:268]: why need to set UCP_EP_FLAG_FAILED flag here?

File: src/ucp/core/ucp_ep.c [hunk 3]
```diff
@@ -320,6 +328,9 @@ ucs_status_t ucp_worker_create_ep(ucp_worker_h worker, unsigned ep_init_flags,
     return UCS_OK;
 
 err_destroy_ep_base:
+    if (ucp_ep_ext_control(ep)->local_ep_id != UCP_EP_ID_INVALID) {
+        ucp_ep_set_failed(ep);
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:332]: why need to set UCP_EP_FLAG_FAILED flag here?

File: src/ucp/core/ucp_ep.c [hunk 4]
```diff
@@ -875,6 +879,18 @@ void ucp_ep_destroy_internal(ucp_ep_h ep)
...
 }
 
+void ucp_ep_set_failed(ucp_ep_h ep)
+{
+    if (!(ep->flags & (UCP_EP_FLAG_FAILED | UCP_EP_FLAG_INTERNAL))) {
+        ucp_ep_release_id(ep);
+    } else if (!(ep->flags & UCP_EP_FLAG_INTERNAL)) {
+        /* If FAILED flag set, EP ID was already released */
+        ucs_assert(ucp_ep_ext_control(ep)->local_ep_id == UCP_EP_ID_INVALID);
+    }
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:889]: pls inverse conditions to simplify this if

File: src/ucp/core/ucp_ep.c [hunk 5]
```diff
@@ -910,12 +926,7 @@ static void ucp_ep_set_lanes_failed(ucp_ep_h ep, uct_ep_h *uct_eps)
     uct_ep_h uct_ep;
 
     ucp_ep_check_lanes(ep);
-
-    if (!(ep->flags & (UCP_EP_FLAG_FAILED | UCP_EP_FLAG_INTERNAL))) {
-        ucp_ep_release_id(ep);
-    }
-
-    ucp_ep_update_flags(ep, UCP_EP_FLAG_FAILED, 0);
+    ucp_ep_set_failed(ep);
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:929]: can we set FAILED flag in ucp_ep_close_nbx() instead of in ucp_ep_set_lanes_failed()?
and here - only assert that ep->flags&FAILED

File: src/ucp/wireup/wireup.c [hunk 6]
```diff
@@ -221,6 +221,12 @@ ucp_wireup_msg_send(ucp_ep_h ep, uint8_t type, const ucp_tl_bitmap_t *tl_bitmap,
 
     ucs_assert(ep->cfg_index != UCP_WORKER_CFG_INDEX_NULL);
 
+    if (ep->flags & UCP_EP_FLAG_FAILED) {
+        ucs_debug("ep %p: not sending WIREUP message (%u), because ep failed",
+                  ep, type);
+        return UCS_ERR_CONNECTION_RESET;
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:227]: wouldn't it cause other things to fail?

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:227]: some callers just ignore the return value, some of them (send REQUEST) handles and destroy UCP EP

File: src/ucp/core/ucp_ep.c (hunk 3 above)
Comment (yosefe) [reply src/ucp/core/ucp_ep.c:332]: need to avoid releasing id (which was not allocated yet) in this constructor error flow, by moving release id to a better place

Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: it is not needed at all

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

File: src/ucp/core/ucp_ep.c (hunk 2 above)
Comment (yosefe) [reply src/ucp/core/ucp_ep.c:268]: - move this to non-internal-ep destroy function
- remove UCP_EP_FLAG_INTERNAL check

File: src/ucp/core/ucp_ep.c (hunk 5 above)
Comment (yosefe) [reply src/ucp/core/ucp_ep.c:929]: add comment that we release if here to drop incoming protocols

Comment (yosefe) [reply src/ucp/core/ucp_ep.c:929]: move this to close_nb, and here only assert that FAILED

Comment (yosefe) [reply src/ucp/core/ucp_ep.c:929]: /* Release ID here to prevent protocols from sending reply */

File: src/ucp/core/ucp_ep.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: unfortunately, TMP EPs are deleted by the same function as normal UCP EPs, i.e. `ucp_ep_disconnected()`

File: src/ucp/core/ucp_ep.c (hunk 5 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: > /* Release ID here to prevent protocols from sending reply */

done in `ucp_worker_set_ep_failed()`

Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: > move this to close_nb, and here only assert that FAILED

unfortunately, we can't do it only there - it should be done also for UCP EPs released in UCP Worker destroy.

**Comment by dmitrygx** [comment]
@yosefe your comments were fixed
can we somehow restart RTD?

File: src/ucp/core/ucp_ep.c [hunk 7]
```diff
@@ -330,13 +330,14 @@ static void ucp_ep_delete(ucp_ep_h ep)
...
-        ucp_ep_release_id(ep);
-    } else if (!(ep->flags & UCP_EP_FLAG_INTERNAL)) {
-        /* If FAILED flag set, EP ID was already released */
-        ucs_assert(ucp_ep_ext_control(ep)->local_ep_id == UCP_EP_ID_INVALID);
+        if (!(ep->flags & UCP_EP_FLAG_FAILED)) {
+            ucp_ep_release_id(ep);
+        } else {
+            /* If FAILED flag set, EP ID was already released */
+            ucs_assert(ucp_ep_ext_control(ep)->local_ep_id ==
+                       UCP_EP_ID_INVALID);
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:339]: can move this outside "else"

Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c:339]: done

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe @brminich ok to merge?
