### PR TITLE
UCT/RC: Print remote QP info for tx error CQEs

### LINKED ISSUE #6673: Retry exceed debuggability for RC QP - without rdma_cm
### Describe the bug
When any layer, like UCX, prints retry exceed error the next logical step is to see who is not responding. 
In case of RC QP and without RDMA_CM this information is missing from UCX log.

In order to debug retry_exceed - will need to run some kind of log gathering on all the nodes of mpi to identify the relevant host. which is time consuming and not always possible.
Instead of simply accessing the right target that is not responding and debugging it.

### Steps to Reproduce
- Command line
- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)
- **Any UCX environment variables used**
Based on customer's issue, below is example from their log when they ran UCX with MPI
[n212-185-036:2692432:0:2692725] ib_mlx5_log.c:145  Transport retry count exceeded on mlx5_1:1/RoCE (synd 0x15 vend 0x81 hw_synd 0/0)
[n212-185-036:2692432:0:2692725] ib_mlx5_log.c:145  RC QP 0x1957e wqe[0]: RDMA_READ s-- [rva 0x7ff72d077000 rkey 0x40c5d2] [va 0x7f1fe5013000 len 1024 lkey 0xc90563b]

There is an indication of relevant QP #, but no indication of who is the other side - how to identify which host is not responding.

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `cat /etc/issue` or `cat /etc/redhat-release` + `uname -a`
- For RDMA/IB/RoCE related issues:
    - Driver version:
        - `rpm -q rdma-core` or `rpm -q libibverbs`
        - or: MLNX_OFED version `ofed_info -s`
   - HW information from `ibstat` or `ibv_devinfo -vv` command
- For GPU related issues:
  - GPU type
  - Cuda: 
      - Drivers version
      - Check if peer-direct is loaded: `lsmod|grep nv_peer_mem` and/or gdrcopy: `lsmod|grep gdrdrv`

### Additional information (depending on the issue)
- OpenMPI version
- Output of `ucx_info -d` to show transports and devices recognized by UCX
- Configure result - config.log
- Log file - configure UCX with "--enable-logging" - and run with "UCX_LOG_LEVEL=data"

### PR DESCRIPTION
**Pull request by brminich**
## What
Print remote QP info for RC QPs when TX op fails.

## Why ?
With RC, WQEs do not contain av info, but it would be useful to have it printed when TX operation fails 

Output examples:
```
[     INFO ] < Transport retry count exceeded on mlx5_1:1/IB (synd 0x15 vend 0x81 hw_synd 0/0) >
[     INFO ] < RC QP 0x938 wqe[1]: RDMA_WRITE --- [rva 0x0 rkey 0x0] [rqpn 0x937 rlid 2 dgid fe80::1c34:da03:5b:b25d] >
```

```
[     INFO ] < send completion with error: transport retry counter exceeded [qpn 0x92c wrid 0x2vendor_err 0x81] [rqpn 0x92b rlid 2 dgid fe80::1c34:da03:5b:b25d] >
```

```
[     INFO ] < Transport retry count exceeded on mlx5_3:1/RoCE (synd 0x15 vend 0x81 hw_synd 0/0) >
[     INFO ] < RC QP 0xd1e wqe[1]: RDMA_WRITE --- [rva 0x0 rkey 0x0] [rqpn 0xd1d dgid ::ffff:2.1.3.16] >
```

fixes #6673

### CODE REVIEW

File: src/uct/ib/base/ib_log.c [hunk 1]
```diff
@@ -110,6 +110,31 @@ void uct_ib_log_dump_atomic_masked_cswap(int argsize, uint64_t compare, uint64_t
...
+    snprintf(s, ends - s, "[rqpn 0x%x", rqn);
+    s += strlen(s);
+
+    if (!uct_ib_iface_is_roce(iface)) {
+        snprintf(s, ends - s, " rlid %d", dlid);
+        s += strlen(s);
+    }
+
+    if (is_global) {
+        snprintf(s, ends - s, " dgid %s",
```
Comment (yosefe) [inline src/uct/ib/base/ib_log.c:130]: pls print all address parameters : src gid index, traffic class, path mtu, sl

File: src/uct/ib/base/ib_verbs.h [hunk 2]
```diff
@@ -326,4 +326,27 @@ static inline ucs_status_t uct_ib_qp_max_send_sge(struct ibv_qp *qp,
     return UCS_OK;
 }
 
+static inline ucs_status_t
```
Comment (yosefe) [inline src/uct/ib/base/ib_verbs.h:329]: 1. why inline?
2. maybe return the whole ah_attr from this function?

File: src/uct/ib/mlx5/dv/ib_mlx5_ifc.h [hunk 3]
```diff
@@ -1505,6 +1506,38 @@ struct uct_ib_mlx5_modify_qp_in_bits {
     uint8_t         reserved_at_60[0x20];
 };
 
+struct uct_ib_mlx5_query_qp_out_bits {
+	uint8_t         status[0x8];
```
Comment (yosefe) [inline src/uct/ib/mlx5/dv/ib_mlx5_ifc.h:1510]: seems wrong alignment

**Comment by brminich** [comment]
bot:pipe:retest

**Comment by brminich** [comment]
@yosefe, can you please review?

**Review by dmitrygx — APPROVED** [review]

File: src/uct/ib/mlx5/ib_mlx5_log.c [hunk 4]
```diff
@@ -71,17 +71,15 @@ ucs_status_t uct_ib_mlx5_completion_with_err(uct_ib_iface_t *iface,
...
-    int           is_global;
+    ucs_status_t       status         = UCS_ERR_IO_ERROR;
+    char               err_info[256]  = {};
+    char               wqe_info[256]  = {};
+    char               peer_info[128] = {};
+    uint16_t           wqe_index;
+    uint32_t           qp_num;
+    void               *wqe;
+    unsigned           rqn;
+    struct ibv_ah_attr ah_attr;
```
Comment (yosefe) [inline src/uct/ib/mlx5/ib_mlx5_log.c:82]: formatting seems inconsistent with other code, should not align var names (only =)

File: src/uct/ib/rc/verbs/rc_verbs_iface.c [hunk 5]
```diff
@@ -82,14 +82,12 @@ static void uct_rc_verbs_handle_failure(uct_ib_iface_t *ib_iface, void *arg,
     struct ibv_wc     *wc             = arg;
     uct_rc_iface_t    *iface          = ucs_derived_of(ib_iface, uct_rc_iface_t);
     ucs_log_level_t    log_lvl        = UCS_LOG_LEVEL_FATAL;
-    union ibv_gid      dgid           = {};
     char               peer_info[128] = {};
+    unsigned           rqn            = 0;
```
Comment (yosefe) [inline src/uct/ib/rc/verbs/rc_verbs_iface.c:86]: uint32_t remote_qpn
do we really need to initialize it?

**Review by yosefe — APPROVED** [review]

**Comment by brminich** [comment]
bot:pipe:retest

**Comment by brminich** [comment]
@yosefe, port to v1.11?
