### PR TITLE
UCP/UCT: Add flag for mem reg error supression

### LINKED ISSUE #2702: [mtt] ERROR failed to register address in mpi-small-tests
Configuration:
```
MOFED: MLNX_OFED_LINUX-4.3-1.0.1.0
OMPI: 3.1.1rc1
Nodes: vega x40 (ppn=36(x40), nodelist=clx-vega-[025-064])
Job: ucx-hwtm-dc
```

MTT log: http://e2e-gw.mellanox.com:4080//mnt/lustre/users/mtt/scratch/ucx_ompi/20180623_084048_26719_117558_clx-vega-025/html/test_stdout_G0xlOH.txt

Doesn't reproduce with `UCX_DC_VERBS_TM_ENABLE=n`. Same for `rc`, works without HWTM, fails with enabled HWTM. Can be related to Lustre issues on server.

Cmd:
`mpirun -np 305 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=dc,sm -x UCX_IB_SL=1 -x UCX_DC_VERBS_TM_ENABLE=y -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /mnt/lustre/users/mtt/scratch/ucx_ompi/20180623_084048_26719_117558_clx-vega-025/installs/W9jm/tests/mpi-small-tests/hpc_tests.git/mpi/misc/all2all_ibm`

Output:
```sh
...
Sat Jun 23 17:16:39 2018[1,0]<stdout>:iter 141
Sat Jun 23 17:16:39 2018[1,0]<stdout>:iter 142
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.428483] [clx-vega-025:10641:0]         rcache.c:534  UCX  WARN  failed to register region 0x9c03e0 [0x108abb0..0x108cbb0]: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.428494] [clx-vega-025:10641:0]         ucp_mm.c:105  UCX  ERROR failed to register address 0x108abb0 length 8192 on md[0]=ib/mlx5_0: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.428499] [clx-vega-025:10641:0]    ucp_request.c:259  UCX  ERROR failed to register user buffer datatype 0x20 address 0x108abb0 len 8192: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.440739] [clx-vega-025:10641:0]         rcache.c:534  UCX  WARN  failed to register region 0x9c03e0 [0x108abb0..0x108cbb0]: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.440745] [clx-vega-025:10641:0]         ucp_mm.c:105  UCX  ERROR failed to register address 0x108abb0 length 8192 on md[0]=ib/mlx5_0: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.440749] [clx-vega-025:10641:0]    ucp_request.c:259  UCX  ERROR failed to register user buffer datatype 0x20 address 0x108abb0 len 8192: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.450210] [clx-vega-025:10641:0]         rcache.c:534  UCX  WARN  failed to register region 0x9c03e0 [0x108abb0..0x108cbb0]: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.450215] [clx-vega-025:10641:0]         ucp_mm.c:105  UCX  ERROR failed to register address 0x108abb0 length 8192 on md[0]=ib/mlx5_0: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.450218] [clx-vega-025:10641:0]    ucp_request.c:259  UCX  ERROR failed to register user buffer datatype 0x20 address 0x108abb0 len 8192: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.460304] [clx-vega-025:10641:0]         rcache.c:534  UCX  WARN  failed to register region 0x9c03e0 [0x108abb0..0x108cbb0]: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.460308] [clx-vega-025:10641:0]         ucp_mm.c:105  UCX  ERROR failed to register address 0x108abb0 length 8192 on md[0]=ib/mlx5_0: Input/output error
Sat Jun 23 17:16:39 2018[1,80]<stdout>:[1529763398.460311] [clx-vega-025:10641:0]    ucp_request.c:259  UCX  ERROR failed to register user buffer datatype 0x20 address 0x108abb0 len 8192: Input/output error
Sat Jun 23 17:16:39 2018[1,11]<stdout>:[1529763398.428102] [clx-vega-036:25799:0]         rcache.c:534  UCX  WARN  failed to register region 0x9cacc0 [0x108ae00..0x108ce00]: Input/output error
Sat Jun 23 17:16:39 2018[1,11]<stdout>:[1529763398.428115] [clx-vega-036:25799:0]         ucp_mm.c:105  UCX  ERROR failed to register address 0x108ae00 length 8192 on md[0]=ib/mlx5_0: Input/output error
Sat Jun 23 17:16:39 2018[1,11]<stdout>:[1529763398.428121] [clx-vega-036:25799:0]    ucp_request.c:259  UCX  ERROR failed to register user buffer datatype 0x20 address 0x108ae00 len 8192: Input/output error
Sat Jun 23 17:16:39 2018[1,11]<stdout>:[1529763398.438322] [clx-vega-036:25799:0]         rcache.c:534  UCX  WARN  failed to register region 0x9cacc0 [0x108ae00..0x108ce00]: Input/output error
Sat Jun 23 17:16:39 2018[1,11]<stdout>:[1529763398.438328] [clx-vega-036:25799:0]         ucp_mm.c:105  UCX  ERROR failed to register address 0x108ae00 length 8192 on md[0]=ib/mlx5_0: Input/output error
...
```

### PR DESCRIPTION
**Pull request by brminich**
Add flag which would help to suppress errors happened during memory registration.

UCP may try to register the whole user receiver buffer when tag offload is used. In some cases just a part of the buffer may be valid/available (like described in #2702) 

Fixes #2702

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7303/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7305/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7306/ for details (Mellanox internal link).

File: src/uct/api/uct.h [hunk 1]
```diff
@@ -423,17 +423,18 @@ typedef enum {
...
+                                                   mapping may be deferred until
+                                                   it is accessed by the CPU or a
+                                                   transport. */
+    UCT_MD_MEM_FLAG_FIXED       = UCS_BIT(1), /**< Place the mapping at exactly
+                                                   defined address */
+    UCT_MD_MEM_FLAG_LOCK        = UCS_BIT(2), /**< Registered memory should be
+                                                   locked. May incur extra cost for
+                                                   registration, but memory access
+                                                   is usually faster. */
+    UCT_MD_MEM_FLAG_HIDE_ERRORS = UCS_BIT(3), /**< Hide errors on memory registration  */
```
Comment (shamisp) [inline src/uct/api/uct.h]: Please add a few words about the usecase. Why one would want to use this option

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7313/ for details (Mellanox internal link).

File: src/ucp/core/ucp_request.c [hunk 2]
```diff
@@ -195,26 +195,29 @@ static void ucp_request_dt_dereg(ucp_context_t *context, ucp_dt_reg_t *dt_reg,
 }
 
 UCS_PROFILE_FUNC(ucs_status_t, ucp_request_memory_reg,
-                 (context, md_map, buffer, length, datatype, state, mem_type, req_dbg),
+                 (context, md_map, buffer, length, datatype, state, mem_type, req_dbg, silent),
                  ucp_context_t *context, ucp_md_map_t md_map, void *buffer,
                  size_t length, ucp_datatype_t datatype, ucp_dt_state_t *state,
-                 uct_memory_type_t mem_type, ucp_request_t *req_dbg)
+                 uct_memory_type_t mem_type, ucp_request_t *req_dbg, int silent)
```
Comment (yosefe) [inline src/ucp/core/ucp_request.c]: let's replace 'silent' by 'uct_flags' to extend it later and avoid extra 'if'

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7315/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@yosefe is it good to go?

**Comment by yosefe** [comment]
@shamisp @gmegan pls take a look

File: src/ucp/core/ucp_mm.c [hunk 3]
```diff
@@ -99,10 +100,12 @@ ucs_status_t ucp_mem_rereg_mds(ucp_context_h context, ucp_md_map_t reg_md_map,
             status = uct_md_mem_reg(context->tl_mds[md_index].md, address,
                                     length, uct_flags, &uct_memh[memh_index]);
             if (status != UCS_OK) {
-                ucs_error("failed to register address %p length %zu on md[%d]=%s: %s",
-                          address, length, md_index,
-                          context->tl_mds[md_index].rsc.md_name,
-                          ucs_status_string(status));
+                level = (uct_flags & UCT_MD_MEM_FLAG_HIDE_ERRORS) ?
+                        UCS_LOG_LEVEL_DEBUG : UCS_LOG_LEVEL_ERROR;
```
Comment (gmegan) [inline src/ucp/core/ucp_mm.c]: Does this log message belong at debug level if errors are hidden? It seems more high volume (trace) level since presumably a failure to register the address when errors are hidden is just going to trigger some other appropriate action that will be logged.

Comment (brminich) [reply src/ucp/core/ucp_mm.c]: @gmegan, is this PR good to go?
