### PR TITLE
TEST/ASYNC: Do several retries with waiting for timer events

### LINKED ISSUE #2765: failure on thread/test_async.ctx_timer_block/0
```
13:49:30 [ RUN      ] thread/test_async.ctx_timer_block/0
13:49:30 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node/worker/1/contrib/../test/gtest/ucs/test_async.cc:516: Failure
13:49:30 Expected: (lt.count()) >= (1), actual: 0 vs 1
13:49:30 
[  FAILED  ] thread/test_async.ctx_timer_block/0, where GetParam() = 1 (45 ms)
```

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7372/label=hpc-test-node,worker=1/consoleFull

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2765

### CODE REVIEW

File: test/gtest/ucs/test_async.cc [hunk 1]
```diff
@@ -445,16 +447,29 @@ UCS_TEST_P(test_async, ctx_event) {
...
-    EXPECT_GE(lt2.count(), COUNT / 4);
+    for (int i = 0; i < TIMER_RETRIES; ++i) {
+        suspend_and_poll2(&lt1, &lt2, COUNT * 4);
+        if ((lt1.count() >= TIMER_EXP_COUNT) &&
+            (lt2.count() >= TIMER_EXP_COUNT)) {
+             break;
+        }
+        UCS_TEST_MESSAGE << "retry " << (i + 1);
+    }
+    EXPECT_GE(lt1.count(), int(TIMER_EXP_COUNT));
```
Comment (hoopoepg) [inline test/gtest/ucs/test_async.cc]: TIMER_EXP_COUNT is int... do we need additional cast?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/7919/ for details (Mellanox internal link).
