### PR TITLE
UCP/WIREUP: Fix hang due to wireup request message not being sent

### LINKED ISSUE #2452: [mtt] hang in mpich_tests_mpi_pt2pt/isendirecv
Configuration
```
OMPI: 4.0.0a1
vegas[07-08,25-28,32-34,36]
```

MTT log: http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180324_204339_18986_145540_vegas07/html/test_stdout_RCkXCk.txt

Cmd:
`mpirun -np 160 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc,sm -x UCX_RC_TM_ENABLE=n -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 -x UCX_MAX_EAGER_LANES=3 -x UCX_MAX_RNDV_LANES=3 --map-by node /hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20180324_204339_18986_145540_vegas07/installs/u273/tests/mpich_tests/mpich-mellanox.git/test/mpi/pt2pt/isendirecv`

This issue is hard to reproduce. Running the cmd in a loop usually helps.

Trace from mtt log:
```sh
node=vegas07, pid=23639:
Thread 4 (Thread 0x7f80ef5a7700 (LWP 23656)):
#0  0x00007f80f2afb923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007f80f24ba913 in epoll_dispatch (base=0x9f9dd0, tv=<optimized out>) at epoll.c:407
#2  0x00007f80f24be360 in opal_libevent2022_event_base_loop (base=0x9f9dd0, flags=flags@entry=1) at event.c:1630
#3  0x00007f80f247ad4e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007f80f2dcde25 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007f80f2afb34d in clone () from /usr/lib64/libc.so.6
Thread 3 (Thread 0x7f80ed254700 (LWP 23670)):
#0  0x00007f80f2afb923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007f80f24ba913 in epoll_dispatch (base=0xa358b0, tv=<optimized out>) at epoll.c:407
#2  0x00007f80f24be360 in opal_libevent2022_event_base_loop (base=0xa358b0, flags=flags@entry=1) at event.c:1630
#3  0x00007f80ee52c51e in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:109
#4  0x00007f80f2dcde25 in start_thread () from /usr/lib64/libpthread.so.0
#5  0x00007f80f2afb34d in clone () from /usr/lib64/libc.so.6
Thread 2 (Thread 0x7f80dd5a3700 (LWP 23734)):
#0  0x00007f80f2afb923 in epoll_wait () from /usr/lib64/libc.so.6
#1  0x00007f80df8d4c44 in ucs_async_thread_func (arg=0xc19350) at async/thread.c:93
#2  0x00007f80f2dcde25 in start_thread () from /usr/lib64/libpthread.so.0
#3  0x00007f80f2afb34d in clone () from /usr/lib64/libc.so.6
Thread 1 (Thread 0x7f80f3498740 (LWP 23639)):
#0  0x00007f80e4063df3 in uct_mm_iface_poll_fifo (iface=0xc6ed20) at sm/mm/mm_iface.c:217
#1  uct_mm_iface_progress (arg=0xc6ed20) at sm/mm/mm_iface.c:258
#2  0x00007f80e429eaf2 in ucs_callbackq_dispatch (cbq=<optimized out>) at /hpc/local/benchmarks/hpcx_install_2018-03-24/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/callbackq.h:208
#3  uct_worker_progress (worker=<optimized out>) at /hpc/local/benchmarks/hpcx_install_2018-03-24/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/api/uct.h:1617
#4  ucp_worker_progress (worker=0xbbb090) at core/ucp_worker.c:1277
#5  0x00007f80e44c9317 in mca_pml_ucx_progress () at pml_ucx.c:454
#6  0x00007f80f2474fac in opal_progress () at runtime/opal_progress.c:229
#7  0x00007f80f302ab15 in ompi_request_wait_completion (req=0x18239e0) at ../ompi/request/request.h:415
#8  ompi_request_default_wait (req_ptr=0x7ffc0393eda8, status=0x0) at request/req_wait.c:42
#9  0x00007f80f3067944 in ompi_coll_base_reduce_generic (sendbuf=sendbuf@entry=0x7ffc0393eeec, recvbuf=recvbuf@entry=0x7ffc0393eef4, original_count=original_count@entry=1, datatype=datatype@entry=0x60b9c0 <ompi_mpi_int>, op=op@entry=0x60cfc0 <ompi_mpi_op_sum>, root=<optimized out>, comm=comm@entry=0x60cdc0 <ompi_mpi_comm_world>, module=module@entry=0x1803370, tree=0x17d8290, count_by_segment=1, max_outstanding_reqs=max_outstanding_reqs@entry=0) at base/coll_base_reduce.c:182
#10 0x00007f80f30684c5 in ompi_coll_base_reduce_intra_binomial (sendbuf=0x7ffc0393eeec, recvbuf=0x7ffc0393eef4, count=1, datatype=0x60b9c0 <ompi_mpi_int>, op=0x60cfc0 <ompi_mpi_op_sum>, root=<optimized out>, comm=comm@entry=0x60cdc0 <ompi_mpi_comm_world>, module=module@entry=0x1803370, segsize=segsize@entry=0, max_outstanding_reqs=max_outstanding_reqs@entry=0) at base/coll_base_reduce.c:474
#11 0x00007f80de432b1e in ompi_coll_tuned_reduce_intra_dec_fixed (sendbuf=<optimized out>, recvbuf=<optimized out>, count=<optimized out>, datatype=<optimized out>, op=<optimized out>, root=<optimized out>, comm=0x60cdc0 <ompi_mpi_comm_world>, module=0x1803370) at coll_tuned_decision_fixed.c:391
#12 0x00007f80f304d8ba in PMPI_Reduce (sendbuf=<optimized out>, recvbuf=<optimized out>, count=<optimized out>, datatype=<optimized out>, op=0x60cfc0 <ompi_mpi_op_sum>, root=<optimized out>, comm=0x60cdc0 <ompi_mpi_comm_world>) at preduce.c:136
#13 0x0000000000402a67 in MTest_Finalize ()
#14 0x0000000000402650 in main ()
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2452

### CODE REVIEW

File: src/ucp/wireup/wireup.c [hunk 1]
```diff
@@ -737,9 +737,21 @@ ucs_status_t ucp_wireup_send_request(ucp_ep_h ep)
     return status;
 }
 
+static void ucp_wireup_connect_remote_purge_cb(uct_pending_req_t *self, void *arg)
+{
+    ucp_request_t *req = ucs_container_of(self, ucp_request_t, send.uct);
```
Comment (hoopoepg) [inline src/ucp/wireup/wireup.c]: align of ```=```

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6890/ for details (Mellanox internal link).
