### PR TITLE
UCT/TCP: Increase keepalive interval from 1 to 2 seconds and use system default for keepalive retries count

### LINKED ISSUE #6471: [mtt] ucx-emulation-tcp: tcp_ep 0x37b76c0 (state=CONNECTED): recv(42) faile
Configuration
```
OMPI: 4.1.1rc1
MOFED: MLNX_OFED_LINUX-5.1-2.5.8.0
Module: hpcx-gcc (2021-03-05)
Test module: none
Nodes: jazz x4 (ppn=28(x4), nodelist=jazz[05,07,13,15])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/shmem/20210305_043538_172128_28209_jazz05.swx.labs.mlnx/html/test_stdout_o_g4qM.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-03-05/hpcx-gcc-redhat7.6/ompi/bin/oshrun -np 112 --display-map --bind-to core -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -mca coll '^hcoll' -mca coll_hcoll_enable 0 -mca spml ucx -mca pml ucx -x UCX_HANDLE_ERRORS=bt -x UCX_TLS=tcp -x UCX_NET_DEVICES=p2p2 --map-by slot -x SHMEM_SYMMETRIC_HEAP_SIZE=128M /hpc/mtr_scrap/users/mtt/scratch/shmem/20210305_043538_172128_28209_jazz05.swx.labs.mlnx/installs/Be3t/tests/verifier/tests-mellanox.git/verifier/install/bin/oshmem_test exec --no-colour --task=analysis:tc2 --task=analysis:tc3 --task=analysis:tc4 --task=analysis:tc5 --duration 10`
 
Output:
```sh
PASS   analysis   reduce         Reduce performance.
[1614929386.419906] [jazz13:37304:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x2909ca0 (state=CONNECTED): recv(31) failed: Operation timed out
[1614929386.419906] [jazz13:37339:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x31a16c0 (state=CONNECTED): recv(62) failed: Operation timed out[1614929386.427160] [jazz07:181620:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x37b76c0 (state=CONNECTED): recv(42) failed: Connection reset by remote peer
[1614929386.427156] [jazz07:181643:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x2744ea0 (state=CONNECTED): recv(59) failed: Connection reset by remote peer[1614929386.628724] [jazz05:170975:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x2bd79d0 (state=CONNECTED): recv(28) failed: Operation timed out
[1614929387.927145] [jazz05:171018:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x28dc190 (state=CONNECTED): recv(36) failed: Operation timed out
[1614929387.927067] [jazz05:170997:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x23fa1d0 (state=CONNECTED): recv(36) failed: Operation timed out
[1614929387.927036] [jazz05:170966:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x2f60240 (state=CONNECTED): recv(59) failed: Operation timed out
[1614929387.927096] [jazz05:170979:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x323d270 (state=CONNECTED): recv(42) failed: Operation timed out[1614929387.934330] [jazz07:181608:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x2e86840 (state=CONNECTED): recv(34) failed: Operation timed out
[1614929387.934369] [jazz07:181616:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x3e51c80 (state=CONNECTED): recv(58) failed: Operation timed out
[1614929387.934381] [jazz07:181621:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x3d00010 (state=CONNECTED): recv(49) failed: Operation timed out[1614929387.995123] [jazz05:171004:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x29bd7c0 (state=CONNECTED): recv(30) failed: Connection reset by remote peer
[1614929388.005963] [jazz05:171009:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x39da640 (state=CONNECTED): recv(42) failed: Connection reset by remote peer
[1614929388.011493] [jazz05:170997:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x246d8e0 (state=CONNECTED): recv(43) failed: Connection reset by remote peer
[1614929388.644361] [jazz13:37298:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x2cdff90 (state=CONNECTED): recv(53) failed: Operation timed out
[1614929388.734877] [jazz07:181614:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x3aa10c0 (state=CONNECTED): recv(54) failed: Connection reset by remote peer
[1614929388.938531] [jazz07:181613:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x3cf01c0 (state=CONNECTED): recv(44) failed: Operation timed out
[1614929388.938494] [jazz07:181608:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x2e77ca0 (state=CONNECTED): recv(52) failed: Operation timed out[1614929388.974960] [jazz05:171018:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x2919820 (state=CONNECTED): recv(33) failed: Connection reset by remote peer
[1614929388.975050] [jazz05:170991:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x2520840 (state=CONNECTED): recv(57) failed: Connection reset by remote peer[1614929417.975222] [jazz15:193006:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x28dcb80 (state=CONNECTED): recv(33) failed: Connection reset by remote peer
[1614929417.975206] [jazz15:193016:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x38554f0 (state=CONNECTED): recv(57) failed: Connection reset by remote peer
[1614929417.975264] [jazz15:193024:0]          tcp_ep.c:1090 UCX  ERROR tcp_ep 0x330c420 (state=CONNECTED): recv(59) failed: Connection reset by remote peer
[jazz05.swx.labs.mlnx:170975] pml_ucx.c:890  Error: mca_pml_ucx_send_nbr failed: -25, Connection reset by remote peer[jazz05.swx.labs.mlnx:170997] pml_ucx.c:890  Error: mca_pml_ucx_send_nbr failed: -25, Connection reset by remote peer
[jazz05.swx.labs.mlnx:170991] pml_ucx.c:890  Error: mca_pml_ucx_send_nbr failed: -25, Connection reset by remote peer
[jazz05.swx.labs.mlnx:171009] pml_ucx.c:890  Error: mca_pml_ucx_send_nbr failed: -25, Connection reset by remote peer
[jazz05.swx.labs.mlnx:171004] pml_ucx.c:890  Error: mca_pml_ucx_send_nbr failed: -25, Connection reset by remote peer
[jazz05.swx.labs.mlnx:171018] pml_ucx.c:890  Error: mca_pml_ucx_send_nbr failed: -25, Connection reset by remote peer
node=jazz05, pid=171018:
Thread 4 (Thread 0x7f4dca343700 (LWP 171038)):
#0  0x00007f4dccc69483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f4dce511133 in epoll_dispatch (base=0x2733ae0, tv=<optimized out>) at epoll.c:407
#2  0x00007f4dce514b80 in opal_libevent2022_event_base_loop (base=0x2733ae0, flags=flags@entry=1) at event.c:1630
#3  0x00007f4dce4cf46e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007f4dccf3fdd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f4dccc68ead in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f4dc6d2f700 (LWP 171049)):
#0  0x00007f4dccc69483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f4dce511133 in epoll_dispatch (base=0x2759770, tv=<optimized out>) at epoll.c:407
#2  0x00007f4dce514b80 in opal_libevent2022_event_base_loop (base=0x2759770, flags=flags@entry=1) at event.c:1630
#3  0x00007f4dc947834e in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:232
#4  0x00007f4dccf3fdd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f4dccc68ead in clone () from /lib64/libc.so.6

```

### LINKED ISSUE #6705: [mtt] tcp_ep.c:1105 UCX  ERROR tcp_ep
Configuration
```
OMPI: 4.1.1rc1
MOFED: MLNX_OFED_LINUX-5.1-2.5.8.0
Module: hpcx-gcc (2021-04-25)
Test module: none
Nodes: jazz x10 (ppn=28(x10), nodelist=jazz[01,03,09,18,20,22-23,26,28-29])
```
 
MTT log:

http://hpcweb.lab.mtl.com//hpc/mtr_scrap/users/mtt/scratch/shmem/20210425_201246_176469_8732_jazz01.swx.labs.mlnx/html/test_stdout_UCEL1O.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-04-25/hpcx-gcc-redhat7.6/ompi/bin/oshrun -np 256 --display-map --bind-to core -mca oshmem_proc_group_cache_size 10000 -mca sshmem ucx -mca atomic ucx -mca coll '^hcoll' -mca coll_hcoll_enable 0 -mca spml ucx -mca pml ucx -x UCX_HANDLE_ERRORS=bt -x UCX_TLS=tcp -x UCX_NET_DEVICES=p2p2 --map-by node -x SHMEM_SYMMETRIC_HEAP_SIZE=128M /hpc/mtr_scrap/users/mtt/scratch/shmem/20210425_201246_176469_8732_jazz01.swx.labs.mlnx/installs/9P6K/tests/gups-shmem/mtt-tests.git/gups-shmem/gups`
 
Output:
```sh
[1619372637.777492] [jazz01:76429:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x1288210 (state=CONNECTED): recv(42) failed: Connection reset by remote peer
[1619372638.207882] [jazz03:12976:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0xea6930 (state=CONNECTED): recv(59) failed: Operation timed out
[1619372638.207884] [jazz03:12985:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x1916060 (state=CONNECTED): recv(60) failed: Operation timed out
[1619372638.329250] [jazz23:149559:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0xe33100 (state=CONNECTED): recv(35) failed: Operation timed out
[1619372638.329247] [jazz23:149548:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x1a98350 (state=CONNECTED): recv(41) failed: Operation timed out
[1619372638.341742] [jazz28:140289:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x1855ee0 (state=CONNECTED): recv(58) failed: Operation timed out
[1619372638.355654] [jazz20:180154:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x1e80e30 (state=CONNECTED): recv(54) failed: Operation timed out
[1619372638.562865] [jazz26:174806:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x1246010 (state=CONNECTED): recv(44) failed: Operation timed out
[1619372639.231880] [jazz03:12979:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x27a80f0 (state=CONNECTED): recv(59) failed: Operation timed out
[1619372639.379655] [jazz20:180161:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x155b620 (state=CONNECTED): recv(51) failed: Operation timed out
[1619372639.586863] [jazz26:174834:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x167b650 (state=CONNECTED): recv(54) failed: Operation timed out
[1619372639.633537] [jazz01:76452:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0xdd6a60 (state=CONNECTED): recv(58) failed: Operation timed out
[1619372639.633539] [jazz01:76430:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x17fc810 (state=CONNECTED): recv(45) failed: Operation timed out[1619372640.377242] [jazz23:149552:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x21425c0 (state=CONNECTED): recv(54) failed: Operation timed out
[1619372647.571627] [jazz20:180126:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x178c290 (state=CONNECTED): recv(55) failed: Connection reset by remote peer
[1619372647.626980] [jazz09:15924:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x11f0f20 (state=CONNECTED): recv(50) failed: Connection reset by remote peer
[1619372647.635744] [jazz20:180139:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x1c1f8b0 (state=CONNECTED): recv(59) failed: Connection reset by remote peer
[1619372647.784347] [jazz22:21259:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0xa09060 (state=CONNECTED): recv(52) failed: Connection reset by remote peer
[1619372647.801205] [jazz23:149556:0]          tcp_ep.c:1105 UCX  ERROR tcp_ep 0x211b8c0 (state=CONNECTED): recv(57) failed: Connection reset by remote peer

node=jazz01, pid=76454:
Thread 4 (Thread 0x7f7e11099700 (LWP 76481)):
#0  0x00007f7e1470b483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f7e13ec2133 in epoll_dispatch (base=0x15c6aa0, tv=<optimized out>) at epoll.c:407
#2  0x00007f7e13ec5b80 in opal_libevent2022_event_base_loop (base=0x15c6aa0, flags=flags@entry=1) at event.c:1630
#3  0x00007f7e13e8046e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007f7e149e1dd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f7e1470aead in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f7e0da85700 (LWP 76490)):
#0  0x00007f7e1470b483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f7e13ec2133 in epoll_dispatch (base=0x15ec750, tv=<optimized out>) at epoll.c:407
#2  0x00007f7e13ec5b80 in opal_libevent2022_event_base_loop (base=0x15ec750, flags=flags@entry=1) at event.c:1630
#3  0x00007f7e101ce34e in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:232
#4  0x00007f7e149e1dd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f7e1470aead in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f7e0525e700 (LWP 76677)):
#0  0x00007f7e1470b483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f7e065f919c in ucs_event_set_wait (event_set=<optimized out>, num_events=num_events@entry=0x7f7e0525dec0, timeout_ms=<optimized out>, event_set_handler=event_set_handler@entry=0x7f7e065e1930 <ucs_async_thread_ev_handler>, arg=arg@entry=0x7f7e0525ded0) at sys/event_set.c:198
#2  0x00007f7e065e1c8c in ucs_async_thread_func (arg=0x16904a0) at async/thread.c:130
#3  0x00007f7e149e1dd5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f7e1470aead in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f7e156fb740 (LWP 76454)):
#0  0x00007f7e1470b483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f7e065f919c in ucs_event_set_wait (event_set=<optimized out>, num_events=num_events@entry=0x7fff056fc3f0, timeout_ms=timeout_ms@entry=0, event_set_handler=event_set_handler@entry=0x7f7e0692cef0 <uct_tcp_iface_handle_events>, arg=arg@entry=0x7fff056fc3e0) at sys/event_set.c:198
#2  0x00007f7e0692cfef in uct_tcp_iface_progress (tl_iface=0x16c31f0) at tcp/tcp_iface.c:249
#3  0x00007f7e06b73762 in ucs_callbackq_dispatch (cbq=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/datastruct/callbackq.h:211
#4  uct_worker_progress (worker=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/api/uct.h:2592
#5  ucp_worker_progress (worker=0x16a4380) at core/ucp_worker.c:2530
#6  0x00007f7e13e7a5dc in opal_progress () at runtime/opal_progress.c:231
#7  0x00007f7e14c430d5 in ompi_request_wait_completion (req=0x1722310) at ../ompi/request/request.h:415
#8  ompi_request_default_wait (req_ptr=0x7fff056fc540, status=0x7fff056fc550) at request/req_wait.c:42
#9  0x00007f7e14c7e871 in ompi_coll_base_sendrecv_actual (sendbuf=sendbuf@entry=0x178b570, scount=scount@entry=1, sdatatype=0x1790660, dest=dest@entry=218, stag=stag@entry=-11, recvbuf=recvbuf@entry=0x178b570, rcount=rcount@entry=1, rdatatype=0x17924a0, source=source@entry=26, rtag=rtag@entry=-11, comm=comm@entry=0x1711660, status=status@entry=0x0) at base/coll_base_util.c:62
#10 0x00007f7e14c7d8ef in ompi_coll_base_sendrecv (stag=-11, rtag=-11, status=0x0, myid=250, comm=0x1711660, source=26, rdatatype=<optimized out>, rcount=1, recvbuf=0x178b570, dest=218, sdatatype=<optimized out>, scount=1, sendbuf=0x178b570) at base/coll_base_util.h:133
#11 ompi_coll_base_allgatherv_intra_bruck (sbuf=<optimized out>, scount=<optimized out>, sdtype=<optimized out>, rbuf=0x178b570, rcounts=0x178e990, rdispls=0x178e580, rdtype=0x7f7e14ed52a0 <ompi_mpi_byte>, comm=0x1711660, module=0x17339a0) at base/coll_base_allgatherv.c:181
#12 0x00007f7dfb5e4067 in ompi_coll_tuned_allgatherv_intra_do_this (sbuf=<optimized out>, scount=<optimized out>, sdtype=sdtype@entry=0x7f7e14ed52a0 <ompi_mpi_byte>, rbuf=<optimized out>, rcounts=<optimized out>, rdispls=<optimized out>, rdtype=<optimized out>, rdtype@entry=0x7f7e14ed52a0 <ompi_mpi_byte>, comm=<optimized out>, comm@entry=0x1711660, module=<optimized out>, module@entry=0x17339a0, algorithm=2, faninout=faninout@entry=0, segsize=segsize@entry=0) at coll_tuned_allgatherv_decision.c:147
#13 0x00007f7dfb5e0bca in ompi_coll_tuned_allgatherv_intra_dec_fixed (sbuf=<optimized out>, scount=<optimized out>, sdtype=0x7f7e14ed52a0 <ompi_mpi_byte>, rbuf=<optimized out>, rcounts=<optimized out>, rdispls=<optimized out>, rdtype=0x7f7e14ed52a0 <ompi_mpi_byte>, comm=0x1711660, module=0x17339a0) at coll_tuned_decision_fixed.c:1363
#14 0x00007f7e14c552e1 in PMPI_Allgatherv (sendbuf=sendbuf@entry=0x178b320, sendcount=sendcount@entry=48, sendtype=<optimized out>, recvbuf=recvbuf@entry=0x178b570, recvcounts=recvcounts@entry=0x178e990, displs=displs@entry=0x178e580, recvtype=0x7f7e14ed52a0 <ompi_mpi_byte>, comm=0x1711660) at pallgatherv.c:146
#15 0x00007f7e14f258d1 in oshmem_shmem_allgatherv (send_buf=send_buf@entry=0x178b320, rcv_buf=rcv_buf@entry=0x178b570, send_count=send_count@entry=48, rcv_size=rcv_size@entry=0x178e990, displs=displs@entry=0x178e580) at runtime/oshmem_shmem_exchange.c:34
#16 0x00007f7dfb1d2563 in oshmem_shmem_xchng (rsizes_p=<synthetic pointer>, roffsets_p=<synthetic pointer>, rdata_p=<synthetic pointer>, ucp_workers=<optimized out>, nprocs=256, local_size=0x1712400, local_data=0x17123e0) at spml_ucx.c:229
#17 mca_spml_ucx_add_procs (procs=0x1769c70, nprocs=256) at spml_ucx.c:325
#18 0x00007f7e14f250da in _shmem_init (argc=0, argv=0x0, provided=0x7fff056fc8d0, requested=0) at runtime/oshmem_shmem_init.c:359
#19 oshmem_shmem_init (argc=argc@entry=0, argv=argv@entry=0x0, requested=requested@entry=0, provided=provided@entry=0x7fff056fc8d0) at runtime/oshmem_shmem_init.c:166
#20 0x00007f7e14f27ea2 in _shmem_init (provided=0x7fff056fc8e8, required=0) at pshmem_init.c:77
#21 pshmem_init () at pshmem_init.c:44
#22 0x0000000000400c09 in main ()
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Increase keepalive interval from 1 to 2 seconds and use system default for keepalive retries count.

## Why ?

Fixes #6705.
Fixes #6471.
When the large amount of connections are started simultaneously, it leads to network congestions and some TCP EPs are failed, because they don't receive ACK on previously sent KEEPALIVE packet. Increasing timeout helps to resolve the issue. `1s` timeout between retries is too small one.

## How ?

1. Change value of `UCT_TCP_EP_DEFAULT_KEEPALIVE_INTVL` from `1` to `2`.
2. Update KEEPCNT configuration parameter to be ULUNITS and set `"auto"` as a default value. Handle it when setting socket options for KA.

### CODE REVIEW

**Review by brminich — APPROVED** [review]

File: src/uct/tcp/tcp.h [hunk 1]
```diff
@@ -65,7 +65,7 @@
 #define UCT_TCP_EP_DEFAULT_KEEPALIVE_IDLE    10
 
 /* The seconds between individual keepalive probes */
-#define UCT_TCP_EP_DEFAULT_KEEPALIVE_INTVL   1
+#define UCT_TCP_EP_DEFAULT_KEEPALIVE_INTVL   10
```
Comment (yosefe) [inline src/uct/tcp/tcp.h:68]: shouldn't TCP get the interval from UCP layer?

Comment (dmitrygx) [reply src/uct/tcp/tcp.h:68]: > shouldn't TCP get the interval from UCP layer?

we should get the interval from UCP layer for `UCT_TCP_EP_DEFAULT_KEEPALIVE_IDLE` - this parameter configures interval for starting KA if TCP socket is idle

Comment (yosefe) [reply src/uct/tcp/tcp.h:68]: what is the difference between them? maybe we should set both?

Comment (hoopoepg) [reply src/uct/tcp/tcp.h:68]: after KEEPALIVE_IDLE timeout kernel starts ping peer every KEEPALIVE_INTVL seconds till get response, after this kernel waits for KEEPALIVE_IDLE again

Comment (dmitrygx) [reply src/uct/tcp/tcp.h:68]: but I agreee that UCP should be responsible to set them. We could introduce iface input params to manage them.

Comment (dmitrygx) [reply src/uct/tcp/tcp.h:68]: `UCT_TCP_EP_DEFAULT_KEEPALIVE_IDLE` == `UCX_KEEPALIVE_INTERVAL`, i.e. 20 second by default if KA is requested along with error handling. Otherwise, it will be `inf`, i.e. disabled. So, TCP won't send any KA packets in case of MPI/SHMEM/etc which don't require error handling.

Comment (yosefe) [reply src/uct/tcp/tcp.h:68]: > after KEEPALIVE_IDLE timeout kernel starts ping peer every KEEPALIVE_INTVL seconds till get response, after this kernel waits for KEEPALIVE_IDLE again

so it seems that if we set both IDLE and INVL to same value as UCP keepalive interval, the behavior will be similar to other transports which use ep_check, where each ep_check is sent after same amount of time

Comment (dmitrygx) [reply src/uct/tcp/tcp.h:68]: ok, I agree. Let's implement through extending `uct_iface_open()` API for built-in keepalive case?

Comment (hoopoepg) [reply src/uct/tcp/tcp.h:68]: right, but here is issue: UCP KA may stop after N endpoints, but TCP KA will ping all EPs simultaneously.
that is why we didn't merge these values before.
not sure if this is issue, but there is different behaviour for timeouts

Comment (dmitrygx) [reply src/uct/tcp/tcp.h:68]: > UCP KA may stop after N endpoints, but TCP KA will ping all EPs simultaneously.

I see, this can happen

Comment (yosefe) [reply src/uct/tcp/tcp.h:68]: https://github.com/openucx/ucx/blob/b75809faa3e8c2015c5f5ab529ae90b0402c7ff0/src/uct/api/uct.h#L1097

File: src/uct/tcp/tcp.h [hunk 2]
```diff
@@ -440,7 +440,7 @@ typedef struct uct_tcp_iface_config {
     ucs_range_spec_t               port_range;
     struct {
         ucs_time_t                 idle;
-        unsigned                   cnt;
+        size_t                     cnt;
```
Comment (yosefe) [inline src/uct/tcp/tcp.h:443]: unsigned long

File: src/uct/tcp/tcp.h [hunk 3]
```diff
@@ -402,7 +402,7 @@ typedef struct uct_tcp_iface {
             ucs_time_t            idle;              /* The time the connection needs to remain
                                                       * idle before TCP starts sending keepalive
                                                       * probes (TCP_KEEPIDLE socket option) */
-            unsigned              cnt;               /* The maximum number of keepalive probes TCP
+            size_t                cnt;               /* The maximum number of keepalive probes TCP
```
Comment (yosefe) [inline src/uct/tcp/tcp.h:405]: unsigned long

File: src/uct/tcp/tcp_iface.c [hunk 4]
```diff
@@ -872,7 +872,7 @@ int uct_tcp_keepalive_is_enabled(uct_tcp_iface_t *iface)
 {
 #ifdef UCT_TCP_EP_KEEPALIVE
     return (iface->config.keepalive.idle != UCS_TIME_INFINITY) &&
-           (iface->config.keepalive.cnt != 0) &&
+           (iface->config.keepalive.cnt != UCS_ULUNITS_INF) &&
```
Comment (yosefe) [inline src/uct/tcp/tcp_iface.c:875]: why changed?

File: src/uct/tcp/tcp.h (hunk 3 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp.h]: fixed

File: src/uct/tcp/tcp.h (hunk 2 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp.h]: fixed

File: src/uct/tcp/tcp_iface.c (hunk 4 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_iface.c:875]: since, 0 is valid value and means no need to retry, fail immediately.
we should use `inf` as for other configuration parameters.

Comment (yosefe) [reply src/uct/tcp/tcp_iface.c:875]: need to document this in config param desc?

Comment (dmitrygx) [reply src/uct/tcp/tcp_iface.c:876]: done

File: src/uct/tcp/tcp_ep.c [hunk 5]
```diff
@@ -494,11 +494,18 @@ static inline void uct_tcp_ep_ctx_move(uct_tcp_ep_ctx_t *to_ctx,
...
 {
+    double time_sec;
+
     if (time_val == UCS_TIME_AUTO) {
         return auto_val;
     }
 
-    return ucs_max(1, (int)ucs_time_to_sec(time_val));
+    time_sec = ucs_time_to_sec(time_val);
+    if ((time_val == UCS_TIME_INFINITY) || (time_sec >= (double)INT_MAX)) {
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:504]:
```
if (time_val == AUTO)
 return AUTO_VAL
} else if (time_val == INFINITY)
  return INT_MAX
} else {
  return ucs_min(INT_MAX, ucs_max(1l, ucs_time_to_sec(time_val));
}
```

File: src/uct/tcp/tcp_ep.c [hunk 6]
```diff
@@ -527,9 +535,13 @@ static ucs_status_t uct_tcp_ep_keepalive_enable(uct_tcp_ep_t *ep)
     }
 
     if (iface->config.keepalive.cnt != UCS_ULUNITS_AUTO) {
+        if ((iface->config.keepalive.cnt == UCS_ULUNITS_INF) ||
+            (iface->config.keepalive.cnt >= (unsigned long)keepalive_cnt)) {
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:539]: seems keepalive_cnt can be un initialized here?

File: src/uct/tcp/tcp_ep.c (hunk 5 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: fixed

File: src/uct/tcp/tcp_ep.c (hunk 6 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c:534]: good catch, fixed

File: src/uct/tcp/tcp_ep.c [hunk 7]
```diff
@@ -494,18 +494,13 @@ static inline void uct_tcp_ep_ctx_move(uct_tcp_ep_ctx_t *to_ctx,
 
 static int uct_tcp_ep_time_seconds(ucs_time_t time_val, int auto_val)
 {
-    double time_sec;
-
     if (time_val == UCS_TIME_AUTO) {
         return auto_val;
+    } else if (time_val == UCS_TIME_INFINITY) {
+        return INT16_MAX;
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:500]: maybe pass max_val?

File: src/uct/tcp/tcp_ep.c [hunk 8]
```diff
@@ -536,8 +531,10 @@ static ucs_status_t uct_tcp_ep_keepalive_enable(uct_tcp_ep_t *ep)
 
     if (iface->config.keepalive.cnt != UCS_ULUNITS_AUTO) {
         if ((iface->config.keepalive.cnt == UCS_ULUNITS_INF) ||
-            (iface->config.keepalive.cnt >= (unsigned long)keepalive_cnt)) {
+            (iface->config.keepalive.cnt > INT8_MAX)) {
             keepalive_cnt = INT8_MAX;
+        } else {
+            keepalive_cnt = (uint8_t)iface->config.keepalive.cnt;
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c]: keepalive_cnt = ucs_min(INT8_MAX, iface->config.keepalive.cnt)

File: src/uct/tcp/tcp_ep.c (hunk 7 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: done

File: src/uct/tcp/tcp_ep.c (hunk 8 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: done

**Comment by dmitrygx** [comment]
@yosefe is it ok now?

**Review by yosefe — APPROVED** [review]
