### PR TITLE
UCT/TCP/GTEST: Protect against connection from non-UCX sock-based app

### LINKED ISSUE #4525: 1.7.0-rc1 showing tcp_ep.c:739  Assertion hdr->length <= (iface->config.rx_seg_size - sizeof(uct_tcp_am_hdr_t))
### Describe the bug
Got a sporadic
tcp_ep.c:739  Assertion `hdr->length <= (iface->config.rx_seg_size - sizeof(uct_tcp_am_hdr_t))' failed
when chasing issue #4406 

Could this be caused by outside connection attempts by port sniffers?

```
[b-cn0131:542585:0:542585]      tcp_ep.c:739  Assertion `hdr->length <= (iface->config.
rx_seg_size - sizeof(uct_tcp_am_hdr_t))' failed
==== backtrace (tid: 542585) ====
 0 0x000000000001f130 ucs_fatal_error_message()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-
7.3.0/ucx-1.7.0-rc1/src/ucs/debug/assert.c:33
 1 0x000000000001f2ce ucs_fatal_error_format()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucs/debug/assert.c:49
 2 0x0000000000019388 uct_tcp_ep_progress_rx()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/tcp/tcp_ep.c:738
 3 0x000000000001b2d9 uct_tcp_iface_handle_events()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/tcp/tcp_iface.c:180
 4 0x0000000000027575 ucs_event_set_wait()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucs/sys/event_set.c:213
 5 0x000000000001b39f uct_tcp_iface_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/tcp/tcp_iface.c:197
 6 0x0000000000022392 uct_iface_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/api/uct.h:2984
 7 0x0000000000022664 ucp_worker_iface_check_events_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucp/core/ucp_worker.c:746
 8 0x000000000001a16a ucs_callbackq_slow_proxy()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucs/datastruct/callbackq.c:397
 9 0x0000000000024d0a ucs_callbackq_dispatch()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucs/datastruct/callbackq.h:211
10 0x0000000000024d0a uct_worker_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/uct/api/uct.h:2203
11 0x0000000000024d0a ucp_worker_progress()  /scratch/eb-ake/UCX/1.7.0-rc1/GCCcore-7.3.0/ucx-1.7.0-rc1/src/ucp/core/ucp_worker.c:1897
12 0x0000000000003aa7 mca_pml_ucx_progress()  ???:0
13 0x000000000002c61c opal_progress()  ???:0
14 0x0000000000003c7d mca_pml_ucx_recv()  ???:0
15 0x00000000000a398d ompi_coll_base_allreduce_intra_recursivedoubling()  ???:0
16 0x000000000006275f MPI_Allreduce()  ???:0
17 0x0000000001cf5706 lj_vm_ffi_call()  crtstuff.c:0
18 0x0000000001d15baa lj_ccall_func()  crtstuff.c:0
19 0x0000000001cf1663 lj_cf_ffi_meta___call()  lib_ffi.c:0
20 0x0000000001cf3767 lj_BC_FUNCC()  crtstuff.c:0
21 0x0000000001ce26ac lua_pcall()  ???:0
22 0x000000000045477f main()  ???:0
23 0x0000000000020830 __libc_start_main()  /build/glibc-LK5gWL/glibc-2.23/csu/../csu/libc-start.c:291
24 0x0000000000454d09 _start()  ???:0
=================================
```

### Steps to Reproduce
- Command line
- UCX version used 1.7.0-rc1
- **Any UCX environment variables used**

### Setup and versions
- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
  Ubuntu 16.04.6, HWE kernel 4.15.0-70-generic

### Additional information (depending on the issue)
- OpenMPI 3.1.1
- MOFED 4.4

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Protect UCT/TCP listener against unexpected connections from non-UCX socked-based applications.

## Why ?

Fixes #4525 (master  branch):
UCT/TCP accepts a connection from some client isn't UCT/TCP and tries to receive data from it, but a client violates UCT/TCP AM protocol.

## How ?

1. UCT/TCP client: always send the first message that includes `CRC16(EP's peer address)` after a connection was established successfully.
2. UCT/TCP server: after some connection was accepted, do not move new EP to a main thread. Wait for the first message with `CRC16(iface's listener address)` and then move to the main thread.

### CODE REVIEW

**Comment by dmitrygx** [comment]
@akesandgren could test this solution pls?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/2f4b3f6a2432a364059da7c0f3973466790169b8/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/50722a488e87651464a963f4cf12df4baf084f29/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/d2ed97852661f751bb636ee935be366d6d7fbb25/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/b05bacf2c3b5cde2e476d65f3c6e7019b2e8d4c7/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/b81f28373e67265b3fcf96112b1cbfda97f18680/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/ff072897388803299931ba525d7a9ed2f4d445a1/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/4df028cbb99110b05af58c20bbf1873e47dd1a3e/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/15ff40c2b76e71afc9ba194a09c9981b22f0554b/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/9126e957c53b665b0fd4c62eee2f1cd2f49b7010/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/1633167a0698f679aa61a841ccd85bc136a51bb4/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/47be02745acdef72a7692314b3785083d923dfef/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/fdb80153d3b801e8aea48b055f5b52aa890dd671/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/7d856621c18f8c234516e5c185d112b07faa18b8/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/2551df1344dbacf175af2aeab5a9d274d24bcce1/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/323545922026c5d71edefc03a089a0c3e797eadb/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/e8095ce794e9a0eb2e8045b93d158c3c1542fc5d/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/20b2c7098614f7e0f410e72b43f5c6adb8c5e42e/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/497c655357242061941cbe44d1ce5ddf4933e322/hpc-test-node-new_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/a4db4651d3d7323a2588942c3e0b579379f881e0/hpc-test-node-gpu_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/17bbbc896bad0c1815633de3c9ee33f47303dfb2/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/37cb8ca15451a5d0c25e7ee285b8917024d9d449/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/5951ca85380a33c538c7000869339c94c5256ae9/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/8eb19497da493b30ec0902595b823784270aa8ba/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/d1d3fde7e0573b26b85b8c52a15d6b5efaeffa8e/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/6a5e97420a29a47797f0802bee6cd6f7/raw/99dd4bb37cc96505530e9201245c160657d976ca/hpc-test-node-legacy_W2) | :question: UNKNOWN

**Comment by akesandgren** [comment]
Tests running

**Comment by dmitrygx** [comment]
> Tests running

@akesandgren appreciate your help with the testing of my patches! thank you!

File: src/uct/tcp/tcp_cm.c [hunk 1]
```diff
@@ -569,6 +575,11 @@ ucs_status_t uct_tcp_cm_conn_start(uct_tcp_ep_t *ep)
         }
     }
 
+    status = uct_tcp_cm_send_crc(ep);
```
Comment (brminich) [inline src/uct/tcp/tcp_cm.c]: can't you send it in the  beginning of `CONN_REQ`?

File: src/uct/tcp/tcp_cm.c [hunk 2]
```diff
@@ -605,8 +660,17 @@ ucs_status_t uct_tcp_cm_handle_incoming_conn(uct_tcp_iface_t *iface,
         return status;
     }
 
+    status = ucs_async_set_event_handler(iface->super.worker->async->mode, fd,
```
Comment (brminich) [inline src/uct/tcp/tcp_cm.c]: why need async handler?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/ba65f532defe7cc96a253cd4bd9aa90f39311a88/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/082c2041611b022e0d54704e932a8521b70ecbb7/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/f5b875ca3ad76fdbce1705b771f5fba11a1a16f1/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/7240e21212b28c9435a4d1d438bbdc09f866d82e/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/50f2fcbecac109a8212ef28dcf199214cfc64962/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/1d3c5db6bd0be769dfae1243737d29f6a7ee4972/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/f4876e6ebc70bb66ab1d1456d35647b9a7d8d4dc/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/3a309402f48038cd0e16b36e4dff322f5d73096e/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/a6394ff0e908e6cb3c611c561edb5fbb60020e87/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/aca62c395137e9eca903e5260b908a89c38a06e5/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/801757c5183bd60cb08a7849bf8177bcb127c4f1/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/a80460f62dfd628aa4014900d0238b1374cd4cd5/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/21a9c2b63dd57f30a58b8adcecda8bfa93e62225/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/7a5dc323348f5e0e9c2a4c5c1ffb6be819563bf1/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/ebc85e22521e80a35b4ec60a8ffd38fabdbc0a28/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/97d152cf14d522b9a22621cf7630e64b85b7da33/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/4b26e2b7d5dfcfd6fcdeeb4da5992f2937178cbf/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/762f89f408bcc537886b7261050179b2206618e9/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/5275fe5978255dfc5d477e70abde5417eaa69d0d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/bf7eec4e661374b117b97a21b55f39fee45e2928/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/e6ff06a31d469201d0d40dafaf7be92a8c25c6cf/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/c67cd068fec87eb70e3c47f1d463f4a0d51b94cb/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/d823c098a0158a0606a531c84586c5167c45b489/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/2ae478dee3b33e0eae84c14404f8b5ea3fe871fe/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0bcf4a2391ee8143ace75052904b00e2/raw/cb5cdb094ca0e32e12dc4c776c3703cd4dafa68c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by akesandgren** [comment]
Kicked off two new test runs with that last commit. Two also running with the code prior to it.

**Comment by dmitrygx** [comment]
> Kicked off two new test runs with that last commit. Two also running with the code prior to it.

ok, thank you for keeping me updated!

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/7ff9f216fe0c0e5c13eac7c6e1074bad56921a0e/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/b10365d932021454074683a5291f23c5ab9ad87a/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/ab16cf9515a75039e0c484724b9323acf16f8f41/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/86bc70f84933b6501e023399291322de7e240ce5/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/e08ca2761d46b4f083d26f315c474efe2c6ac8a0/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/4c91382b33e494d0c4990b3b9f5815a64034652a/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/dc00777fb8d742e7033a324c1c696b79c967060a/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/520601cfe76c754311ee1eca34fb74f8c5251844/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/d56dd78f63fc64989eab20b1663d412c26ab8649/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/f664914cb09cc0ff2700165df243513ef858cc24/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/e92b44c4aded3cc0a5df7ce24850f5713ed2f4be/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/263ecc4133437008bcfc003a5f44b9efc95560d8/hpc-test-node-new_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/a001e4eaa9edf8edfae84056175ead8879ded1db/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/a2330cea2e26faf5f945ff33e449d42025531cdf/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/c82882a175e2520288a73fbc22a369d76d02d4cd/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/2d8db2e09adfb03b908cf1157a3edd1548115cd6/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/3e86aa49e3a8aa04a49ae54c4941b7b67650fdb8/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/19af861cf2bb770056f54bc318364830a15a5004/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/6219349abaa402ded043aa72699f391dc944e529/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/aa5a65c542490f918a15f7df2805660d408fdb51/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/f63fc7eb570db2f8d44314a32fa0024ba2650f9c/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/6d436af2512ee8fda01c8a2339e90bb7da2443b3/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/495d91c82f8d1845a1ff870e1ea545f97797192d/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/38ab0b15315ec6a9a46e7c8fe42bf5149705312f/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f393bffde71fcb1b750aa4b9a3f1b98d/raw/ea82dc1d8d240e28b6159700d59bfd3751b7337c/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/3c9c80f52b59dda7382893782d76a7bf54566867/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/0a0bcf5ba2467fd256e2678b1bd844e75f42d527/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/8beffb8badb150d49379e3d661521d1bbabbf165/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/72104460a6d46d839184b9bbc1e24e2abd836006/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/630f54c7a8e8465bba080b9f6d231fe80e460e1a/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/dc0a5dbecf9fbfedf62fef01bc2d61a2e8772388/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/baf7ddfe1a21c8b48ea9dfc68cfb86851d928b59/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/130bc5cce6d150023be9601a026be5a4356a724e/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/8eb3682322f563a419905f55ee6f2b63b852afbd/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/1eb197de7f27bd2ee6755d5a0a9b59c9fd30dcda/hpc-test-node-new_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/9da1512972c92b11afeae1127a6782918df373a3/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/859263760f0a5fe41e0a90d6091864aaae7b1cbf/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/1ada9cd90ba087dd59f7af8abc5b8a30f358e305/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/de3a7da70fd91d3f6bb1f6a7daf8d5d8bdbe7649/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/2e998592254fd59f52fbda255540461e9824f634/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/aa3bf18d78adbba4c39092e0c1e4fafc6322e17c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/d3e4ac323ec36d3d74ab25ee594bf2e236b048ba/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/44ea386a9ea4239b0d8fb9bc2697ee5eaa87b38a/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/a869fae65f75aa6a98351343eb9167ce94d2f8ff/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/6c820a91f2904d2a68b2f47e0c1e593d31a1fb85/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/9921213e22f18567241d0ecedb548ce0df700df9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/6d79081d2b16226e0c242ce295fa5228034a17d8/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/08f5848e03a1b9794b36a5dfad59f46c8a832ac6/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/110d48e516dd98f000f36fe484858b46b779e947/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/edf902e8c999d859e0796e6a6d62295d/raw/43fec2082f6438810f2ea308442425d22879fb75/hpc-test-node-new_W2) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/afbacdc7b24ed2cc3b267273be118550a8db9ace/_main) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/bd33cec03bd36b33cc1845226654f08ff7ed12b6/hpc-test-node-legacy_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/9d676dccbf61fe0a399a11d6d4f8a1e1b842493f/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/3f16d42212d5887c40ee42881620d3077d1ed40d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/743d2de9db7329622c530cd2adfbe7f53bb19437/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/0ec09e223bfecf0e21d42f385b222ec1f4ed80c4/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/5d582fdfa6555c8c8119e572256302bfead74bab/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/17e1eeb1077dcbe0a66cd4f25a54e76ec3fd1ccc/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/401592d5257ba22d0574663345402c7f2113ccd2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/0549a6aa42e98eba1fe8f7a5dbbc6af5fa850ef2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/df97049164f4e312c7461d102b4bd1c083e41276/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/db3f3b15af84d3757986e420d76c99ddb18fcd1f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/ecbec33732c1c71cacf57bfc996494a96acbcd44/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/6afd61e0001934837380abf1ade6ce95a8a47167/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/1bc5d33191342b459e2703a5aec823ee4a06e085/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/6d151a67fb7511178b658b926f3aa0ab1ccf35ba/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/4107a4bc0554f084f42264111096ce96425bfda6/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/316637927f839dd5379c06abfeb3b7414adbbf9b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/748d6908dc84f1c619d1c51b434fdfdd982d16b1/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/e48770d6de4ae5bb0ab2b063bd71f5062aa0aeba/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/5600a23116bee8f45400a954f6fe6c4568024639/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/f949bc40f1627e6de815c524ee3515a3bdce69f8/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/3cafbc03312ef69854624e298291689ed2764aa5/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/d6c758e75402bdc16e67caf4d0c988a5ccb2cd53/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b5b6a955904d9de70b0c8806c04e4c09/raw/809db5003066b69503abb8cdea3687d08a20bfec/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
lab configuration issue and #4616 
bot:mlx:retest

File: test/gtest/uct/uct_test.h [hunk 3]
```diff
@@ -439,6 +439,14 @@ std::ostream& operator<<(std::ostream& os, const resource* resource);
 #define UCT_INSTANTIATE_IB_TEST_CASE(_test_case) \
     UCS_PP_FOREACH(_UCT_INSTANTIATE_TEST_CASE, _test_case, UCT_TEST_IB_TLS)
 
+/**
+ * Instantiate the parametrized test case for the TCP transport.
+ *
+ * @param _test_case  Test case class, derived from uct_test.
+ */
+#define UCT_INSTANTIATE_TCP_TEST_CASE(_test_case) \
+    UCS_PP_FOREACH(_UCT_INSTANTIATE_TEST_CASE, _test_case, tcp)
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/uct_test.h]: it was done in the same way as we do for IB (i.e. `UCT_INSTANTIATE_IB_TEST_CASE`)
I agree with you - done

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 02-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/ccf65c103717eebcfb6316861a2fda5461ff0101/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/67931221d5af4b6b9c1e137c4caa613324967e72/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/ae8b4e41ed6541d48839ddc3a39527c7b55e3a92/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/23569ad887b886e3c2f6ee6a8f09bf137dbcc7e7/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/fa3c8c8f93ab7b139c6a24c25362507248abd576/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/84dea933c841bbddff8c2e1e45472822dcbfcd09/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/0c95df4562129e830039cde2ba2b03eb706175a3/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/586f672c08b617cc8619f80e27da713e4f44674c/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/c740143fa8cf200bc22069559811ede1999a7ce7/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/bfd0ed61de6b938152e9c44820e5a45c5faa2376/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/e91344ec82d5d1bb752ad5c89d09c171008a2466/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/bb1dcb81deff07a657982811335e1d63eb5fca4d/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/900ac3aa7e25f58f020c989137d31e7687be97d5/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/a648e8341d91981af38e040e6bda057d8901a28c/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/15a6f742c81624462b4e68c7e8b7f326cf714291/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/63a27c19039fb62a03c2a73fedce52768884e52b/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/cc6af6d42a9f2b5655d55dad1e9ce2960269815e/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/bff09c2e2ac07d365f41fcdca6435e7fb24eddf5/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/9fc41e4c07af14042e57c5852ddfc7bfb1235b2d/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/7f0f1923a9d44d26d44a0c9d5b208b385ef2545c/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/82cefd18b8ba8601304a3afd61be2fcb6a28fa96/hpc-test-node-new_W3) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/68cf4a76a1626a5f67683c18cd18a9d311159547/r-vmb-ppc-jenkins_W0) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/4238adc51b9fcabc1c175291cf271ea51b2d815e/r-vmb-ppc-jenkins_W1) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/037dc31811c7972a62db65e2a3b955e2c3c9a1a9/r-vmb-ppc-jenkins_W2) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0dfc63631c0838a974f380e2a1de8e17/raw/c5fa9a8adbf0cfbfe40a53b40ae89f3bcb16ceee/r-vmb-ppc-jenkins_W3) | :question: UNKNOWN

File: src/uct/tcp/tcp_cm.c (hunk 1 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_cm.c]: actually, not all `CONN_REQ` messages require sending a magic number prior, e.g. when a user creates TCP EP from UCT API call, UCT/TCP checks if it has a connection to the same peer - if yes, UCT/TCP just sends `CONN_REQ` to ensure `RX` capability will be set on a receiver's EP.
So, a receiver expects the packet with the magic number as the first message only in case of the connection was accepted, i.e. the first messages after `accept()` completed

**Comment by dmitrygx** [comment]
@brminich could you review when you get chance pls?

File: src/uct/tcp/tcp_cm.c [hunk 4]
```diff
@@ -511,31 +518,60 @@ unsigned uct_tcp_cm_handle_conn_pkt(uct_tcp_ep_t **ep, void *pkt, uint32_t lengt
...
 
     ucs_assertv((ep->tx.length == 0) && (ep->tx.offset == 0) &&
                 (ep->tx.buf == NULL), "ep=%p", ep);
-    return 1;
+
+out:
+    if (progress_count != NULL) {
+        *progress_count += count;
+    }
+    return UCS_OK;
```
Comment (brminich) [inline src/uct/tcp/tcp_cm.c]: either return status, or change func to return unsigned

File: src/uct/tcp/tcp_cm.c [hunk 5]
```diff
@@ -511,31 +518,60 @@ unsigned uct_tcp_cm_handle_conn_pkt(uct_tcp_ep_t **ep, void *pkt, uint32_t lengt
...
+
+    if (!ucs_socket_is_connected(ep->fd)) {
+        ucs_error("tcp_ep %p: connection establishment for "
+                  "socket fd %d was unsuccessful", ep, ep->fd);
+        goto err;
+    }
+
+    status = uct_tcp_cm_conn_complete(ep, &progress_count);
+    if (status != UCS_OK) {
+        return status;
```
Comment (brminich) [inline src/uct/tcp/tcp_cm.c]: function is supposed to return `unsigned` not `ucs_status_t`

File: src/uct/tcp/tcp_ep.c [hunk 6]
```diff
@@ -286,6 +286,15 @@ static UCS_CLASS_CLEANUP_FUNC(uct_tcp_ep_t)
 
     uct_tcp_ep_mod_events(self, 0, self->events);
 
+    if ((self->fd != -1) &&
+        (self->conn_state == UCT_TCP_EP_CONN_STATE_ACCEPTING)) {
+        /* It's safe to remove an async handler for file descriptors
+         * for which it was already remove or wasn't added at all,
```
Comment (brminich) [inline src/uct/tcp/tcp_ep.c]: removed

File: src/uct/tcp/tcp_cm.c (hunk 4 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_cm.c]: yes, return `status` here

File: src/uct/tcp/tcp_cm.c (hunk 5 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_cm.c]: fixed

File: src/uct/tcp/tcp_ep.c (hunk 6 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: fixed

File: src/uct/tcp/tcp_cm.c (hunk 4 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_cm.c]: done

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 02-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/1cd429c2cada72eb8d6922de0ce413ba9568f92e/_main) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/f4c8b804f66a1277c25117b69696d3eb15e1f3a6/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/9fb601f821aed2cb734167de4c1436255c0f71a3/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/4da42557dc5db5d2ef1ee2c7625efca54e12f35d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/4be8ecb595bfa3b6829f8ddccf2e17c34e459dc5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/85538a73b1bf960d7506235f6fcb6cc0219ee5ec/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/92c75b8d69af0e6ddce86a812d014fd99e60d2eb/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/6b9a16bc8d5403925c2f04d0eb0b7778134b597f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/b4aad314f34972c5e6510cf7da8c252525e64bc7/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/57e84e501e4e4527d9cd65e764235f427c9d7210/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/83b5f638bc98dd76ea7300632aa3ca8f2d4afdff/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/cd4b7df1d2fc7f8a813809a93006d5f4a1e598ca/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/9d7bf0d0d925dd356dd89d5f2f2cdadb5ccf1279/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/3171405e44719a2c759cab0d7dd943383b565d16/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/94d8a0d7d18c5d1a4f7af1064dd7d8a8826b16a4/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/0debc3dc1bbcf0fe40c07f732919b1e661867e11/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/3ef33695cf054577b2ae7adddd93da5a6d9dfb50/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/4c3fb105d77fa86b83cd3ecfcc0a3fadbbe209dc/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/83098801f18624f7c551a68703c4283412e74144/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/38eb57db5d4cafef174b13fa55409f7ea971224e/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/ed862c209b1b572ec127c8831347c2b6060c4ea5/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/2ead35d89b87673f140376cdb094709b868a021b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/2aae5fcdb5e6809d24f11abc915442deefc2042c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/29b59d3bf2a72e61d51e5ed6fcd7132bee3ba2ae/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f53f435706da8a5116ee4e0ae72788ae/raw/324784ae9ee02da0de38d7dbe41492102a8827e2/hpc-test-node-legacy_W0) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 02-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/7482db15b0e47d7530739cc4f3efd9d77bd84168/_main) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/b0f2b8777de787f05b55d9945048b218888e2517/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/3c8cbdfb563529f16dde55989b65640eff62456a/hpc-test-node-legacy_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/a9b42f06c2b486d8b506d1645e1f757c0245f695/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/1d311486d47e23939d9ce74151a518ebcab5a212/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/c2e07074f4facede279210339c3705d7c33de28e/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/4e341e1b56ba8fd08101d4453b89646cf141ed99/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/85a1d48c2f4bdd37e3dd9f824d9f6a13d398a90f/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/c057c297bbff7b463211a317b20e4952c0aa98ea/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/e675800bb0863f9676d7129aca1ac03dd600a969/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/b5ac642caadcb7392cb932c7339072880fa5c793/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/b4300e0ec98490e9a91f4035c840ce0bf25de306/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/937747aa5733aee73bc85fad38ebe94fb9625ed4/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/1678160771f4a0205c417c68cf87c9d410d1fa18/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/079924205aad46743babf881d108874b5b618ffe/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/df2386fbc88e637bada6968f7427ccdad8bcf3e7/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/a292bf49de970797e36558cfcf90d3e7920a17b1/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/4799fab04c7b4e7dc919c5ed81ff934bb395262c/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/bceb7d67e004e05949356710d795055457cdcb37/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/bb6dfdf4637449babaa4f042bfbd75b05313c3ed/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/1d01f393d51b9224e03e4d50a029a93fcd71be96/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/28b331fecbe810d0e100b40b8be17e4c629b50a5/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/b9501b11b71321588f4d743670b06e465d55d941/hpc-test-node-new_W3) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/ee35e99b1d60a63d9893e90ec721d82541a2cf48/r-vmb-ppc-jenkins_W1) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ba0fa19bc2c053fc177105fbcb9aa216/raw/f0760cd175caff1dca823d03508411e487ee5598/r-vmb-ppc-jenkins_W2) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 02-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/94209d6bfd46960ce5f4df04ebde208c7cd672a0/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/d92304b68246022814e76d4928cb61133eae5b85/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/b96b31ed77930384adc28eb0ca273388d6c2b536/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/3143c3e7694ac17f24994c545e50e18443f4fbec/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/939ef0503221775d13721f3dee0c5324ffd0a7be/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/6484d6b83ee0d8bcc58fbd218be0f5a85501bc46/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/2e7e6eb87abfed0cf66e1e4bf0aa9bdc06fd6e46/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/9c385154d2bf2854677a9ee198ebd67dd54938bf/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/f7bace59d04e779a31eb2ecf8596faa069d823f3/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/82266c2b502d3977d01971b9d799f7484e15a954/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/b45efeb106bed28062fe72c375da2c15a745b70a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/68280cd0b463111dca7379044682e936a3882d2f/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/983b147c9927f2ffa767f323eb5fcf1dd44aca5d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/ec16b628baf5dc4acbe71d81860a32fca5861fc9/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/daf95e18038dc27cd84bde929e5158e9cac979a0/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/19ce6222bdd9af908935db046a5e8efa20951373/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/faea01fa3f72c55d331eaa1918dcca09d2473604/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/8565c1af676d6b250aacaded3e2fb64dab8e3ded/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/6764b2f22bb4cff1fa0eba125c099f6b02cb0332/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/49b86397536f422b544674b16add42718683f2ef/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/39a480a8127823ba35d469fdab161c4bd3cd316d/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/2cec03108dc62b4bd646d5f5502b687b4c27de64/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/3b61f38f50e3eaec72b98395df781650a441c70a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/9e0e066a82dc5241466346f1642759084bbf6b03/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1a684348ff3e4e1792b537e5f83e8dad/raw/310910fc01b134f7887fb8b177497e2b2de069ba/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/tcp/tcp.h [hunk 7]
```diff
@@ -21,6 +21,8 @@
 
 #define UCT_TCP_CONFIG_PREFIX                 "TCP_"
 
+#define UCT_TCP_MAGIC_NUMBER                  0xCAFEBABElu
```
Comment (yosefe) [inline src/uct/tcp/tcp.h]: better define a full 64 bit constant, or use it as 32-bit

File: src/uct/tcp/tcp_cm.c [hunk 8]
```diff
@@ -500,27 +507,50 @@ unsigned uct_tcp_cm_handle_conn_pkt(uct_tcp_ep_t **ep_p, void *pkt, uint32_t len
...
+                                             unsigned *progress_count_p)
 {
+    unsigned progress_count = 0;
     ucs_status_t status;
 
-    if (!ucs_socket_is_connected(ep->fd)) {
-        ucs_error("tcp_ep %p: connection establishment for "
-                  "socket fd %d was unsuccessful", ep, ep->fd);
-        goto err;
+    status = uct_tcp_cm_send_magic_number(ep);
```
Comment (yosefe) [inline src/uct/tcp/tcp_cm.c]: can't we add just magic number to uct_tcp_cm_conn_req_pkt for simplicity?

File: test/gtest/uct/tcp/test_tcp.cc [hunk 9]
```diff
@@ -0,0 +1,234 @@
...
+    void detect_conn_reset(int fd) {
+        // Try to receive something on this socket fd - it has to be failed
+        ucs_status_t status = post_recv(fd);
+        ASSERT_TRUE((status == UCS_ERR_IO_ERROR) ||
+                    (status == UCS_ERR_CANCELED));
+        EXPECT_EQ(0, ucs_socket_is_connected(fd));
+    }
+
+    void test_listener_flood(entity& test_entity, size_t max_conn,
+                             size_t msg_size = 0) {
```
Comment (yosefe) [inline test/gtest/uct/tcp/test_tcp.cc]: no need default value for msg_size

Comment (dmitrygx) [reply test/gtest/uct/tcp/test_tcp.cc]: done

**Comment by yosefe** [comment]
```
[2019-12-27T13:28:09.785Z] "/scrap/jenkins/workspace/ucx-5/contrib/../src/uct/tcp/tcp_cm.c", line 182:
[2019-12-27T13:28:09.785Z]           error #1143: arithmetic on pointer to void or function type
[2019-12-27T13:28:09.785Z]       pkt_hdr         = (uct_tcp_am_hdr_t*)(pkt_buf + magic_number_length);
[2019-12-27T13:28:09.785Z]                                                     ^
```

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/83e67845d578ce5bfadc03f1b18657558602981b/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/42736dbbf721643f2ddbf38be79528d4c8f06328/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/24ce2b724ec01248551ba60da684c86ed981543e/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/be2ddba5c384d7907ab5501abc77a6e4e05f9a36/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/4a7f8928aeddbc693356fc7bb6ecef7d10578758/hpc-test-node-new_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/5932fec5bbdf7a05d1e4c2db29e4e497be066300/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/843cd3e29c38e353be3cfcf6bb59f678db183752/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/82e8c1f51487364fc164015a83533221af4b9177/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/08971b1364f50edd9e4a6c258714d1255d205ba6/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/6b0dd8d325ee89639151d32c2a8b55a2df8825d7/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/036c3c0c837fedd7aa405228ec41afc0004f5f8d/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/4b1e0a4ffc0733a66fa48fc52b3d6b771f168e48/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/d6b97e181d4b67d61400c54ab81cbed8408756c7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/2e555c37e5a7857fe04debdfbaab322b0495c021/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/bd1d113649c16b1d524fbcd6c67ee9b10ad28ddc/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/f8ae371d3a5fd9ab66663b7099a46a9d052bdd5f/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/16be796244c076a9095cb2ff67654fbe2e9904f6/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/f5a0cd464e56e2bad6aeaa856e9afdb63fd1fca6/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/961c3cd36b414b497d7c85073e8e71f5ede12e3b/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/f3799521da250a50096a2ca9872de34aac9ba61f/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/714b4c69d5c745b22a5666c9aae6170da60b47c2/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/a85cd831279103cd2b4671f37667cb10a0ab4851/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/884165a3d6e6469a00a1cea8178c132166d0500d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/336fd62061280064c161199645b2ebe46dbd41dd/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f5259176ee590d5f4897dea3312c6069/raw/cb7ec63359d2b72bbae67f356d2535bb24569747/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/6b6fae155bfa3503457c342828bef0fbfc7d4f2b/_main) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/59fcc8d990d97f4a110cd4bbe426589edd496242/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/8d1bd52d228f994061ef3c97dc8cfb7c65772ffa/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/af52994f5db854356599d3a094f9ff50707e72e9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/cbf5b2e3df5d1b54255a00e4597da49b61b9c1e0/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/dabe5f37bc3fbe823340daa3631f4bff783a9b7a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/b15393d308ec3c9fbc9afeeb7ff0692983144b57/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/54c453c91ac30535c201acee94b3dac30fb291c6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/ceabd866c010b7445141984876dd5b21a37556d3/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/3dcc07a4a9ce7b5bef0669d81034f8852af23d3a/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/06431ca0154715832f7e8b2eb1a5cdc6d6a617ee/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/7de636767aefbc161ed56def2483e090ac7f7142/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/1664c0e8c217b4fb4a34018416ee6372a1b7e98c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/dd15a6c968fb3ce56a825dcef44a8c86bc521b55/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/a2149f65b71aec79e1b832a944189c8f3db9bfcb/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/413d61913e886cf1990ee87a1ea99197366a19ec/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/8aebad2d981db4bb78d628453835b2abfd285d1b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/014998f9ab332f877547f9a2acfb6da90cd577b0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/54c5b09d94e07babf65a68459ba5e58e0f8588c4/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/1bb2f3d7ae1e55bf94d4ebec331464c70648b04f/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/6083d70733faec71b8b4a6cbb674eba958e70bed/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/7f972959e65784497e56dfd85c9f338039356bcd/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/97dda77e775db1bc46d011eeea1e96827a199027/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/99dae69b461f6b570bd87b4ecb4c1599a4580c0c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a3f6afbbc5eda0975288d36722467774/raw/f62e43bef8c34345554835ce9d33660839e6d0c5/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
> [2019-12-27T13:28:09.785Z] "/scrap/jenkins/workspace/ucx-5/contrib/../src/uct/tcp/tcp_cm.c", line 182:
> [2019-12-27T13:28:09.785Z]           error #1143: arithmetic on pointer to void or function type
> [2019-12-27T13:28:09.785Z]       pkt_hdr         = (uct_tcp_am_hdr_t*)(pkt_buf + magic_number_length);
> [2019-12-27T13:28:09.785Z]                                                     ^

@yosefe fixed two static analyzer issues in the 3rd commit

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/c5199cd4a458007da1b734ea15a2e7fbd924f68e/_main) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/6c170858031b8d74618404e17437f095bdab9cd8/hpc-test-node-new_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/2038b45fadcd78dfc4d0304ec9f3d97ae9680450/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/4b39af99542ae434e5a446d56fe19e97ee591f3d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/114dd16efbb5eaa4453f08624b8afbf05ff6e390/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/83f6e947e0c5af36e705ad4a87be86d0962aaa82/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/18d71588f7c3469ad9120967ac7efba1a261d11b/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/af94787ab98bdde2131d945a352a00cb27ac388f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/3a2e13d54ec6aa132b2a368daeece16e48635905/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/19f2bd1adf12f122328308cbb1a753dcc484dd64/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/8c268eaeee06dad6525455e945cf454d1dde1ea4/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/daaa56b9ba2176943e31a5a0b74f5ef896a36f6c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/427057d25fccbe07a77f7799692e0fe81e5e929d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/711126b39a6db2421ec6c83918105fe1db6cf326/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/9d2c6d2b6de3848ee7414e5d363148eca185b1ea/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/ad30d93d8917f4e7fa5bd23490eb86f7b557f632/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/5fb60dadef1d4e023b12f67e9d819dc8360d968a/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/16d74d1ab491535b29146ceaca19a3d1197cd621/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/6f9b7ee398e9f812c839406f865c57330f108cd2/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/ed3abb5e538415e97964af5613785972418fd5d0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/4f274436447710e78ebdc1d7d89032d7e8edcb80/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/0526c753c35ca79c041130514f0ef1171281c3ae/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/07891530d9e29f803274c5e627b8e642ce2d39c1/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/2471eb0974e75020b0ea17bb0d6620b8d87bd08f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/989100618a6ca093621cc8db8e1e4e48/raw/b146acbc2495e4125a16d18b1c43b569fcdc23b3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/046690c1936785c5d764f8ede809bb67f3add1f9/_main) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/fb1911628b4b575c96e0d081943fa54ec947bb91/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/c79a6e458123567bf4ff76f09c06774e750a7eb6/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/2de36f919686813da29d69c9a7b0a5ec28d4a63d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/761150ce33732aac93492af1eeda420d8b05a529/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/4b99df59e7cafb4b31cba4eadea2da2a8e0fba7a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/7b02e6e063262eae1123e335e26863afb0a4a253/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/4cbd7e1e11815fd5139a77b79a6d6c4990ca8edb/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/9d011d77bc8acdb2ecd9375aa44ced10383fadd4/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/e1a57759b7d5d701bf96f28e63badea8e073a288/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/680f0ea1aa3c99da6153a435d337cecb7b3dbdca/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/184827c75940a2b4dee6c8357ba73f3bba598bc1/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/46f8cbc554396a2274e6c80bd1fd0adaa9fecf7e/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/a3514f0067da4f7e50a6a1dbab1e2da08aaf9ca7/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/0199200a1f770f7488651bce9f7d96e2ec05bed5/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/a2411f8268b5f8ce9869ac89d37c90e47a9d64cd/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/3064e09ec297d0ff79f8b98a25147599420b5df6/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/f58d057a2a7aae872654decb8c3c2c2fc2bded48/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/9149a5a5eb619d429d11a8d01c316504e098dc05/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/f1d584cf7e9465a67ca84f2af5a5c768bd1dd95c/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/d24594e89938307c1c636c82043583043b6a1c4b/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/f124c074bde2683177548737e8bf8de373fa25f2/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/de61bc15e6d327d97012963f6b9c81ce63cef92d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/8398a5018ea4c3500d1a4215012f8bf094fbe761/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/49a9106d15c8109cdf72bad79a83318e/raw/2620f92890a2c5cfd6b1dd48a6b2dfece0597669/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 06-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/5db03a92a034fab18526e119f38dd7b9669fbf8a/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/da90b30eb871796aee96240431a0f9c17e027f30/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/dbc22eedfadbfe5ebf3b61efe3ffac51d02fb381/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/a2a6a4f9a98db8d2dd1301c475245daf743ef43a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/091fb5c6032168c832457e43454ce434e30d8276/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/6cedc8bdc603aadd72c493f9f62c580fb2399c30/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/f6ccdc36fcc516b4abfd5a9f25a5716e13655648/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/371bf02a19bb99a9138ef41d105809d4401c1775/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/fa0548bd3afa4a93bceea6df268e098e515a4a27/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/4596793f3479e03399ecbcdf1c40c4ca6cafe5a1/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/a922f536db99203bba9eb7a149d713f514316f74/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/90ebeeff223ee60dd746cd302486b493f9307344/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/2b50ae0aa0f9960c1e8304964ff363dcf1ee1f62/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/e3d06de0de1d9f711b558d2fee68d0340c72f7b6/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/7e3219958f66d440c1644a748b7f404416914b8a/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/929d88796946a912fed1c64754d8b860185b1a2d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/75534d9d119e3b6b4276d4b4c7010a451691f21a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/c0d3dd58ad3a2ccbe6ccbb6a7cf0dede08db5347/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/68f6f342d4bb4ac4fd12fa01de30729ec42a2cc9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/7a5a488d6675c204ca6a64c8b82c571d035ef443/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/026bc2e11ebb0fa7711a7965ab83e2c7e3d869c7/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/cdd71b94fd93d6766244f4e6cf9e31ddbfbacb26/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/d132b5d03ab1c73c8249d25fd7faf9f3da5a02cc/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/ef4c47d93485376ecc845d0e09f4e9e1bb65b591/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/060a3fe2346d78ea5f982835f2b732f8/raw/9adf353037d7de31ddaf565c2a417e55d22afddd/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
NFS issue
bot:pipe:retest
/azp run

**Comment by yosefe** [comment]
NFS issue
bot:pipe:retest

**Comment by dmitrygx** [comment]
@akesandgren do you have any news regarding testing with this patch?

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by akesandgren** [comment]
No crashes with commit 23f0ece7d8 after ~7 days. Haven't tried with anything newer yet.

Wan't me to try with the current head?

**Comment by dmitrygx** [comment]
> No crashes with commit [23f0ece](https://github.com/openucx/ucx/commit/23f0ece7d8d36cdd6d471640de5dbf38540f5c70) after ~7 days. Haven't tried with anything newer yet.
> 
> Wan't me to try with the current head?

@akesandgren good news.
I don't think that we need to tests the current head as it doesn't change fix, it just applies fixes for the comments from UCX community. I think we need to pick up the fix to 1.7.0 release, right?

File: src/uct/tcp/tcp.h [hunk 10]
```diff
@@ -360,6 +358,7 @@ typedef struct uct_tcp_iface_config {
 
 
 extern uct_component_t uct_tcp_component;
+extern const uint64_t uct_tcp_cm_magic_number;
```
Comment (yosefe) [inline src/uct/tcp/tcp.h]: the magic number could still be a `#define` but it has to be real 64 bit value
for example 0xCAFEBABE12345678lu

File: src/uct/tcp/tcp_cm.c [hunk 11]
```diff
@@ -167,16 +159,27 @@ ucs_status_t uct_tcp_cm_send_event(uct_tcp_ep_t *ep, uct_tcp_cm_conn_event_t eve
...
+        }
     } else {
-        cm_pkt_length = sizeof(event);
+        cm_pkt_length           = sizeof(event);
+    }
+
+    pkt_length += cm_pkt_length + magic_number_length;
+    pkt_buf     = ucs_alloca(pkt_length);
+
+    if ((event == UCT_TCP_CM_CONN_REQ) &&
```
Comment (yosefe) [inline src/uct/tcp/tcp_cm.c]: maybe put this inside lines 187-189? to check only UCT_TCP_EP_CONN_STATE_CONNECTING

File: src/uct/tcp/tcp_cm.c [hunk 12]
```diff
@@ -597,13 +597,15 @@ static ucs_status_t uct_tcp_cm_magic_number_handler_io_err_cb(void *arg,
...
-    uct_tcp_iface_t UCS_V_UNUSED *iface = ucs_derived_of(ep->super.super.iface,
-                                                         uct_tcp_iface_t);
+    uct_tcp_ep_t *ep       = arg;
+    uct_tcp_iface_t *iface = ucs_derived_of(ep->super.super.iface,
+                                            uct_tcp_iface_t);
     ucs_status_t status;
     uint64_t magic_number;
 
-    status = ucs_async_remove_handler(fd, 0);
+    UCS_ASYNC_BLOCK(iface->super.worker->async);
```
Comment (yosefe) [inline src/uct/tcp/tcp_cm.c]: are you sure we need UCS_ASYNC_BLOCK? 
ucs async operations are already thread-safe

File: src/uct/tcp/tcp_cm.c [hunk 13]
```diff
@@ -558,15 +583,55 @@ ucs_status_t uct_tcp_cm_conn_start(uct_tcp_ep_t *ep)
...
+    status = ucs_async_remove_handler(fd, 1);
+    UCS_ASYNC_UNBLOCK(iface->super.worker->async);
     if (status != UCS_OK) {
-        return status;
+        ucs_warn("failed to remove the magic number handler for "
+                 "client socket fd=%d", fd);
     }
 
-    uct_tcp_cm_change_conn_state(ep, UCT_TCP_EP_CONN_STATE_WAITING_ACK);
+    status = ucs_socket_recv(fd, &magic_number, sizeof(magic_number),
```
Comment (yosefe) [inline src/uct/tcp/tcp_cm.c]: is it possible we will receive only partial number and get UCS_ERR_NO_PROGRESS here?

File: src/uct/tcp/tcp_cm.c [hunk 14]
```diff
@@ -558,15 +583,55 @@ ucs_status_t uct_tcp_cm_conn_start(uct_tcp_ep_t *ep)
...
+                             uct_tcp_cm_magic_number_handler_io_err_cb, ep);
+    if (status != UCS_OK) {
+        goto err;
+    }
+
+    if (magic_number != uct_tcp_cm_magic_number) {
+        /* Silently close this connection */
+        ucs_debug("tcp_iface %p: received wrong magic number (expected: %zu, "
```
Comment (yosefe) [inline src/uct/tcp/tcp_cm.c]: print the IP/port of peer

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 12 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/6f660f1ddc9653029147cd9d0322793af1e4d1c2/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/fc18c6eb627cfceb25e40e11a0323331184ed43b/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/743f6758041cecf66a8b70aabb30264f5348d5d4/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/60c10fb87e215dbcb1fac2754c04e452051cadee/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/b333d1d5f789b6942c2ff12081b7d4e8a714cd69/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/190d54a61e8860c1ad1b484b164696f0e1493270/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/210cfaf20d03af2dfdd4cab05558f5f6a7a6114c/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/6eab88c58203a987bf8ef4c4af4a8342c9b892dc/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/e2d1f4fae37784206163916b23f7f4c3c9913a7a/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/0bc45c15aea29234726db005f3843bf049423eeb/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/89689cb1911654f0a366497e0378e8b822e94065/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/06ac0d2a2657dbf902e6b57c7f60bfbbb74160a9/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/331f973119e2caa9843b0e7f8ae1430f0e26f051/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/85df04591ee7f9c931a91720ac0c20b684ff8517/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/78c320124a4fd21090993f67f5244f6a2485c6d6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/9625ea70bb90982844423b8bdbeee55d53199d23/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/2537b931afe4d95920a8391c3a3b9bdc8f9a3026/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/6afe957a725acd360e12a1bb99879ead77f82a31/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/78b23a47ba3fac4027db2d6e1053fbd8358b9a2a/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/5244d938ebe30f1cdd1433f6aaacce84bf8ad4fb/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/c00fc283ff12e7a1b1dac0d688c8969315f6825c/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/58fd0d644f5cf83585f02adac39b669ef52aaa5d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/38176aefd2a1a3a9e8c43c3bb1a1ddbd805237d1/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/b88494574d185e2cd6d8d025afa4a22738785a97/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88ac2f0585bffd4ed66ffb39bf68843b/raw/a73355021210e056251b20a536137a9f909b91bc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/b632b46642dd12592f5581d0dd8c8c038357c28d/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/dc64210d39a7c9ac7300e49d204e7630473f16d7/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/6fcde9803dba48e95c8a15f50983c7c8b1f273c9/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/faa1f2c0990417271d277361b3694d8e98f42b99/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/4776b0b7591df37557ae8c8fb79beb051dc327b2/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/6fec97371ea8fc9a0bad285a1da2d6df9a6e01cb/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/958617a02b91cf7ecb94de6b1b164906710a9009/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/9269da305d66bc475d6bff6280a4f5ae85c1e0ca/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/913527b4967e92b02be42259615474ebe6edca26/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/7adf2e1afd46756d519d796bf01cb6d6f1c17f13/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/af6e1917d7edfaab06a6831c8f87a4ed24b6da90/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/e41d9468453455ee88b4a39bce0b8edd7cb5f0c6/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/71306a1339b9cc9e1192fc5be2d4e272ac739806/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/cced86ee8079727f21f9f0efa28dd22aad722043/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/55a3a707fa96f5824be0e87fe9b415c1b4362c52/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/ef390016c2b42e2644f7dd4d65f1afbfd3452941/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/0faec4eac3819eefa554ef6747cb4de3e78bc887/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/ee6cb60634fc73e5a6ffaccc719404a52938c063/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/9951040ec658a463af5867f4994f9d5fea8522ce/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/80a8328a68236c03699a30233c96e369b63656df/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/f0abc5b8a8404015e1cd6780183f59355b1933ac/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/4f950ee94eb4946ecaa1729d6426000f9bbf289a/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/514dea0c69ac1cc812bdb8d6fc63ce9e3d3140f1/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/62f455aad0439b46a4d43db6584ca13b31a270e0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cd30150ce6b6b7803518644526d11fe0/raw/c3367e965270554ec67af14c2ebd9e51f7e1c7ce/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/tcp/tcp_cm.c (hunk 12 above)
Comment (yosefe) [reply src/uct/tcp/tcp_cm.c]: still not removed for uct_tcp_iface_listener_init

File: src/uct/tcp/tcp_ep.c [hunk 15]
```diff
@@ -730,6 +748,58 @@ static inline unsigned uct_tcp_ep_recv(uct_tcp_ep_t *ep, size_t recv_length)
...
+    uct_tcp_iface_t *iface = ucs_derived_of(ep->super.super.iface,
+                                            uct_tcp_iface_t);
+    char str_local_addr[UCS_SOCKADDR_STRING_LEN];
+    char str_remote_addr[UCS_SOCKADDR_STRING_LEN];
+    ucs_status_t status;
+    size_t recv_length;
+
+    if (ep->rx.buf == NULL) {
+        /* Don't allocate from iface's RX memory pool to avoid data races */
+        ep->rx.buf = &ep->magic_number;
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c]: maybe would be simpler to read the magic number into rx buf and later compare it to the the known value ?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 12 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/8df82cb18222ce6b508d5cdaab691c491a6b2410/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/d62eb0eede6ea3777c894be6973b7117ae77f784/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/8b70023814ef749a8e28e78bde931968d205c51f/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/34c02abfe3635599bdd3afd32b00fdf9be1f1bbe/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/4ddebd46242a9916529c0fbd1211bc41bd9709f7/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/f87e220db71f3d5e8c260d68ddd08dafd0d4950b/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/49a35727ee1a99086b74edcc646fd4b78d40fdae/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/44d15a7d6aee79cb72b4b63c3c05fa84e8cfc20a/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/5f6380ad7f8317d202aa5638819878176123fee7/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/80f5dab82817e58bea062e5c2532a8ece4ff73e6/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/26f96d92f7b2c80a21cd816d5db46193b29fdb9a/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/8180ccd11470b7dec192a39e91ac18fa02ac7c2c/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/e89c794b8e3bcf4785d8a26c551ab6f85e422618/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/33aeac0aefb79be42730941fe038e48fbbd15e76/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/c0e7ad7ea865b133dbf6c7ee0e90ed7ff310801a/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/63c1625d589ceb46b55bf8b0830b6f430b629346/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/2f70dc5ab2b0aed19bf427563b444a8339ead5ba/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/ed0b64f29707df50e04d6e3ca8efe21b18d96294/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/27a31b216b416f59b74de4988244cbcc6104a546/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/65cbca5970c88e6ba05786e85b2dd17b34ea876e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/32060272426b4d0fec4f5d0584e96d22b45235a6/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/d5845156a3a7624a59260bdb707f75abd7689db1/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/04d070f63e2ce29c79a40e5c408cfb774c33ba9f/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/673efa7e8c996fc90f56408bd42bafe41ae8406a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e1b9a91f9aa1bd798d9667f3651091b/raw/21ed262eba71bd2448d474e8bdbf44fe446c20b2/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/bcbfdcd1e466d0f6b4a8ca9f916ec29389a34369/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/eafd601463b0e896c4c9bca1f4a7627b278285f7/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/045a19c22be7a674e6e7318d267b1ef18eed19ba/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/b31bb75de11ff6f6b8822462de9723b1d164727c/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/52422408d40828ccd22997a3505e1aab7e80b1d9/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/abd5c741d77608e077df3f2116e731ba852f75dd/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/9c4281efa9fc5e7bd6da45943469da2c92cae412/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/9f0eaad1713ff0a943a3f4fdac6499fc38342a64/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/46db0152c4d5fdc244c89f9c8639b589e537dfb5/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/2956f5c69d25947dcceb73a1141458dae48e2c3c/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/7d0b2a6e91b981117e488ed846399a9f3cafa3c8/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/6dbabd528e3b548d570a952178dd857e90f83327/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/25e6c1ae4d39f52cec33cfa18807039aed1618d3/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/754ea2deefedb5a3df0e22483f603cd55573f142/hpc-test-node-legacy_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/e68312b7dae2056ad2afbda122d8f0d677ee27b2/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/4a078f75b46d55aa89ff893723ab2bc9b8fa9f1a/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/51efb9361176366558515e86d0c74239ce7bec34/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/829b0d0e21eff13530f1bfa3e5e303fc6500e6c4/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/232445503f88ee589889ace623c92d19a34b1be2/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/32195d58cf41311ba63e833790273ed69decb3e4/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/2ccf670fef9bec57226094613b7d36bf3a6923d7/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/d2a0eb2a6923c4d02a5f124f679a807d354920b9/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/77b4ef6d2d8de4e2e645172bc7cc610722a52375/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/d9d16b7575c6eb28a951606dd61f65f19748abeb/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0e88907f3dcb8dc9d5cd25fab0331e5c/raw/920a5bca64dd2bffd26f284e2582a092e9778e31/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/e4d015dfe027094048f45db1b09c33e891036434/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/c94c1b691966ba7c6c28daecd7eca88eba3303bd/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/2bda1fd7be6101abd4ab036f04f5ecef71659a76/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/1406f2f81b4cf1c09a4ab7ab9961e67afa53f3e5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/82a632fa55fbc3b5e4dc4567e32fc65bc5d557de/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/c4c02a46191e3ed7c5f5f0d540b4756e54bf16dc/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/3566cee864b404f8e78124ab945f228225d5722c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/fe6720321ccf2b7e753455681822a357b5e59831/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/f06d19b86ff1c50c6840843c87c72d7c84a78856/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/491e0553204c7349d0fe873bbe27f2cd344d8cea/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/14e88313934c33846422b48635a454bd834b3304/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/3e4eddd65d3dec560f3635b5c659d08ec8ea6c25/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/e85c60a5f06d7c27bfaabee596ff115fa655411d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/80c87a8a81fbbde078e8c6396944a484e7642deb/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/504c762fb3d814d0ef30c5265ebbc9749711f257/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/25621021c97e8541890a8854a0a750a140437f88/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/cbb0aaee779517dbc8209e69fa7c8b456da64460/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/3ac2519b7627724816fab9ad07edf002ebc9d72c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/4be33f97b8f18af4660341de13d2a4adb093217c/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/0007184ca291bbc7fca3ee496e3329700fb71a77/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/28575edf3ddbf630c8613981962463d4126ac67f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/8165479c36d81498cc70045ee36270dc285a8eac/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/2ac6f8a5306cb49ba09906609d1912c1c3e4029d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/44b1543802d229e7fd5f78c178338dab8cdeb86b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9729a6392e8cefa5741a2ba63baff365/raw/a223378cd138b6090ef3f9d33b32065e39378c1a/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by shamisp** [comment]
I'm curious, what is typical protection in other TCP/IP based application assuming certain wire level protocols ? Shell we make the magic value user configurable, just in case it conflicts with something else ?

**Comment by akesandgren** [comment]
The main reason for the protection is against random port sniffers and the likes. I see no reason to have it configurable.

**Comment by shamisp** [comment]
@dmitrygx how much effort is to back port this to v1.7.0 ? (this is follow up on email thread)

**Comment by dmitrygx** [comment]
> @dmitrygx how much effort is to back port this to v1.7.0 ? (this is follow up on email thread)

@shamisp not a problem at all, since the TCP related code in v1.7.x is almost the same as in the master branch. Need to get @yosefe’s approval and squash&merge this to master.

**Comment by shamisp** [comment]
@yosefe can you please take a look. 👍 from my side.

**Comment by shamisp** [comment]
BTW actually @brminich can approve this as well and it should be enough.

**Comment by dmitrygx** [comment]
> BTW actually @brminich can approve this as well and it should be enough.

actually, the latest comments were from @yosefe, I don't know whether he is ok with changes or not

File: src/uct/tcp/tcp_cm.c [hunk 16]
```diff
@@ -160,20 +161,30 @@ ucs_status_t uct_tcp_cm_send_event(uct_tcp_ep_t *ep, uct_tcp_cm_conn_event_t eve
                 (ep->conn_state != UCT_TCP_EP_CONN_STATE_CONNECTED),
                 "ep=%p", ep);
 
-    pkt_length        = sizeof(*pkt_hdr);
+    pkt_length                  = sizeof(*pkt_hdr);
     if (event == UCT_TCP_CM_CONN_REQ) {
-        cm_pkt_length = sizeof(*conn_pkt);
+        cm_pkt_length           = sizeof(*conn_pkt);
+
+        if (ep->conn_state == UCT_TCP_EP_CONN_STATE_CONNECTING) {
```
Comment (brminich) [inline src/uct/tcp/tcp_cm.c]: is it possible to send  `UCT_TCP_CM_CONN_REQ` in non `UCT_TCP_EP_CONN_STATE_CONNECTING` state?

File: src/uct/tcp/tcp_ep.c [hunk 17]
```diff
@@ -1001,6 +1017,66 @@ unsigned uct_tcp_ep_progress_put_rx(uct_tcp_ep_t *ep)
     return 1;
 }
 
+static unsigned uct_tcp_ep_progress_data_rx(uct_tcp_ep_t *ep)
+{
+
```
Comment (brminich) [inline src/uct/tcp/tcp_ep.c]: extra line

File: src/uct/tcp/tcp_cm.c (hunk 16 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_cm.c]: yes, when UCT/TCP EP was in CONNECTED state after that EP was created from accepting the connection and then the user wants to create new EP to the same peer (we found this EP from khash and send CONN_REQ mesage to the peer to enable RX capability on peer's side)

File: src/uct/tcp/tcp_ep.c [hunk 18]
```diff
@@ -552,8 +565,9 @@ static void uct_tcp_ep_handle_disconnected(uct_tcp_ep_t *ep,
 
         uct_tcp_ep_mod_events(ep, 0, ep->events);
         uct_tcp_ep_close_fd(&ep->fd);
-    } else if (ep->ctx_caps & UCS_BIT(UCT_TCP_EP_CTX_TYPE_RX)) {
-        /* If the EP supports RX only, destroy it */
+    } else if ((ep->ctx_caps == 0) ||
+               (ep->ctx_caps & UCS_BIT(UCT_TCP_EP_CTX_TYPE_RX))) {
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: yes, this is the situation when we are trying to receive the "magic number" packet from the peer that connected to us and it fails by some reason

File: src/uct/tcp/tcp_ep.c (hunk 17 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: yes, fixed

File: src/uct/tcp/tcp_cm.c (hunk 16 above)
Comment (brminich) [reply src/uct/tcp/tcp_cm.c]: maybe always sending magic number would be simpler?

**Comment by shamisp** [comment]
👍

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 22 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/07cb4c094a9ad371db8e45d43898e0934081881c/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/8eb944545a3fbf68663df40de877c83657a65715/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/aa3abf09941ba3431873d71db81d5777c40a9dd0/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/61efdcdd6fe8eb7b7f62023fbc3cfd47ca3da6da/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/187b35de7dea6e5cf4bf6eba0c19bcd2a868a1db/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/737ebd1e5c2890a0225b7cd4f1e6f2a435d0f10b/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/f8854181cc822418bd74ef0d3ca4613e7a58dffa/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/add6c708b35b9fe92fc83c1a8d750f8ac7326f72/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/e0341635d87f2f6d673bdaed5239e2c9e6d3134d/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/51e95f8b2671dde6390b581bd49dc7b61cd83bde/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/8e06759141b1b80043809aa77234e8f138ba7d85/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/ea1bccb437cffb1d5f2e2c024310b8d4a5adde0b/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/71e4565128fac3b7b71ca7624a16bb612fbc2f3b/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/bd0059b9eb85bcfa72a7f9c842f2712f7cf6f6ae/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/b6b0e8aef50319b6b039f76a4f3b4d91276b9b21/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/5fe0d010f0297154d5f41279e005b5a2290ba097/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/a74f27ffef30a1cd3a43489f099e51e77d1ee376/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/67c07347b17e4cdaceaa2d8e7f324a42f10fc87d/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/45e6b15e57b5b19c932e978d71b86fd09c439244/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/d6141b9fab8fd125494c5880358b2682d8edb3e9/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/4bd94446ea72e9230d81c91b71302ecf8c1e2a25/hpc-test-node-new_W3) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/998853ec816f17fb41f836119da9b44e/raw/57ec837718db641da738f384bb8e39a9254620ad/r-vmb-ppc-jenkins_W1) | :question: UNKNOWN

**Comment by dmitrygx** [comment]
@shamisp @brminich force-pushed changes to fix the year in the new `test/gtest/uct/tcp/test_tcp.cc` file (`2019` -> `2020`) and removed trailing `;;` in `src/uct/tcp/tcp_cm.c:585` (`;;` -> `;`)

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/68ce220f0edc33a7ffac68dc594e9c5cb981dac2/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/c007f3ba758f96df72f89921160a48eddc96c74a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/14a96889105a85859be59ab0dd80b44832d12b24/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/f303209c2e06e13e9e5f99407d93d45277cd60c1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/dd0770b5cdd7a8c36c9c784f12a0a0e1351d4a40/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/01492d0ca208c0299fd29ddef692faa8a046474a/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/3781d3db9245e66291307ebb46bd04f838f46b08/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/04ba4effc21d3b8f581f6586822174b16ad2fa73/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/2f34faf4ed5ced4193b132ae58778653213701f7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/07b448ac04b1a35214c078ca4e1eef4b526c4b9e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/2f93979245bd00bbed3a0f72f7b77ce4ac43e31c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/571dd93bcd830cf3d93aec1547efd56ce8f9057a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/a1bd58ffc6344bbde80ac441421b87cd9d89a792/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/4d2d8c063d80d5806acb1a9f882611cc1b822d5e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/cab6ed42388f31d682177efedc3ab8267523f975/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/d12662619cc41e118c9a4ec93f7c4a367e7c6f24/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/4c9b0a176436ff4a72aed910d1b5b04ab920ea5c/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/e1707b8bfe52125e830b0403f0b4de1681410e23/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/71c98758f3d9d50abc0357030c5413b6a055f62e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/c68f2aa44e9e5a2a63e9ce734504967d23735f7a/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/7d084f301b6abed2da3ce3e349bae79ddbeae1f0/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/6591b79cca71e9723a3a79348a8432b10373a02b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/8b51a2ef7fe1016c463f9c2af9fe309c69a0020b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/e3ba10ac0c8ffa363a3b9791c55038b670e814b7/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9e3f15f1d43da1b81213e449c33ff59d/raw/5711db00abad30014f7f132d0532e50241b8c58e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
