### PR TITLE
UCP/PROTO/RECONFIG: Fix copy header handling in reconfig.

### LINKED ISSUE #10424: `UCP_AM_SEND_FLAG_COPY_HEADER` not working as expected with protov2
### Describe the bug
`UCP_AM_SEND_FLAG_COPY_HEADER` seems not to work as expected with protov2, leading to corrupted header data in the receiver callback while the length of the header is correct. It is hard to reproduce this issue and I've only managed to reproduce it where I have 8 or more processes communicating where they exchange peer information via AM upon connection, potentially generating up to 16 simultaneous send requests per process and 128 simultaneous requests for the whole cluster where all messages are no larger than 44 bytes, however, it requires a somewhat heavy stack that isn't easy to write a standalone reproducer.

In a call with @ofirfarjun7 we were able to determine that persisting the header and removing `UCP_AM_SEND_FLAG_COPY_HEADER` indeed resolves the issue, which supports the likelihood of this being a bug with that feature in protov2. With protov1 this is not reproducible, both with or without the use of `UCP_AM_SEND_FLAG_COPY_HEADER`.

### Steps to Reproduce
- Reproducing is difficult without a heavy stack, I can work on a Docker container if needed
- UCX version used (from github branch XX or release YY) + UCX configure flags (can be checked by `ucx_info -v`)
- Environment variables used:
  - `UCX_PROTO_ENABLE=n`: always works
  - `UCX_PROTO_ENABLE=y` + `UCX_TLS=rc_verbs,self,sm,cuda`: runs into corrupted header data for 8+ processes
  - `UCX_PROTO_ENABLE=y` + `UCX_TLS=rc_verbs,self,sm,cuda,tcp`: runs into corrupted header data for 8+ processes

### Setup and versions
- DGX-1 with 8 x NVIDIA V100
- Linux dgx13 5.4.0-182-generic #202-Ubuntu SMP Fri Apr 26 12:29:36 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- MLNX_OFED_LINUX-23.10-2.1.3.1
- NVIDIA driver: 535.161.08
- CUDA 12.2
- Built without gdrcopy support
- nv_peer_mem module loaded

### Additional information (depending on the issue)
- OpenMPI version 5.0.6

### PR DESCRIPTION
**Pull request by ofirfarjun7**
## What?
Handle copy of AM user header in `ucp_proto_reconfig_progress`.

## Why?
When using sockaddr to establish connection requests go into pending queue but user header is not being copy even if `UCP_AM_SEND_FLAG_COPY_HEADER` is enabled. It breaks API and can cause data corruption.

fix #10424 

## How?
Copy user header to internal UCX buffer if needed like done for other protocols.

### CODE REVIEW

File: src/ucp/proto/proto_reconfig.c [hunk 1]
```diff
@@ -51,6 +53,15 @@ static ucs_status_t ucp_proto_reconfig_progress(uct_pending_req_t *self)
         return UCS_OK;
     }
 
+    if (ucs_unlikely(ucp_proto_config_is_am(req->send.proto_config) &&
```
Comment (tvegas1) [inline src/ucp/proto/proto_reconfig.c:56]: Can there be `ucp_proto_request_restart()` call (from wireup) on this request before any other AM proto calls, but after `ucp_proto_reconfig_progress()`? If yes I suspect this could be an issue because of:
-https://github.com/openucx/ucx/blob/c4e66dce48b5e7ce9d1a1578be42aba07b0bc8f8/src/ucp/core/ucp_am.c#L1758

File: test/gtest/ucp/test_ucp_sockaddr.cc [hunk 2]
```diff
@@ -2550,8 +2551,12 @@ class test_ucp_sockaddr_protocols : public test_ucp_sockaddr {
             param.flags         = flags;
 
             ucs_status_ptr_t sreq = ucp_am_send_nbx(sender().ep(), 0,
-                                                    &shdr[0], hdr_size,
+                                                    &shdr_cpy[0], hdr_size,
                                                     &sb[0], size, &param);
+            if (flags & UCP_AM_SEND_FLAG_COPY_HEADER) {
+                ucs::fill_random(shdr_cpy);
```
Comment (tvegas1) [inline test/gtest/ucp/test_ucp_sockaddr.cc:2557]: maybe fill with specific value, and also free?

File: src/ucp/proto/proto_reconfig.c (hunk 1 above)
Comment (ofirfarjun7) [reply src/ucp/proto/proto_reconfig.c:56]: From what I see `ucp_proto_request_restart` calls reset then proto selection is done and `ucp_request_send` is called again.
If it choose ZCOPY then `ucp_am_eager_zcopy_pack_user_header` will be called and will set this flag to 0, but perhaps I'm wrong.

File: src/ucp/proto/proto_reconfig.c [hunk 3]
```diff
@@ -11,8 +11,10 @@
 #include "proto_debug.h"
 #include "proto_select.h"
 #include "proto_common.inl"
+#include "proto_am.inl"
 
 #include <ucp/core/ucp_worker.inl>
+#include <ucp/am/ucp_am.inl>
```
Comment (gleon99) [inline src/ucp/proto/proto_reconfig.c:17]: Order

File: src/ucp/proto/proto_reconfig.c [hunk 4]
```diff
@@ -11,8 +11,10 @@
 #include "proto_debug.h"
 #include "proto_select.h"
 #include "proto_common.inl"
+#include "proto_am.inl"
```
Comment (gleon99) [inline src/ucp/proto/proto_reconfig.c:14]: Order

File: src/ucp/proto/proto_reconfig.c [hunk 5]
```diff
@@ -30,10 +32,19 @@ static ucs_status_t ucp_proto_reconfig_select_progress(uct_pending_req_t *self)
     return req->send.uct.func(&req->send.uct);
 }
 
+static void ucp_proto_reconfig_abort(ucp_request_t *req, ucs_status_t status)
+{
+    if (ucp_proto_config_is_am(req->send.proto_config)) {
+        ucp_am_release_user_header(req);
+    }
+    ucp_request_complete_send(req, status);
```
Comment (gleon99) [inline src/ucp/proto/proto_reconfig.c:40]: Add blank line

File: src/ucp/proto/proto_reconfig.c [hunk 6]
```diff
@@ -30,10 +32,19 @@ static ucs_status_t ucp_proto_reconfig_select_progress(uct_pending_req_t *self)
...
+}
+
 static ucs_status_t ucp_proto_reconfig_progress(uct_pending_req_t *self)
 {
     ucp_request_t *req = ucs_container_of(self, ucp_request_t, send.uct);
     ucp_ep_h ep        = req->send.ep;
+    ucs_status_t status;
```
Comment (gleon99) [inline src/ucp/proto/proto_reconfig.c:47]: Move down

File: test/gtest/ucp/test_ucp_sockaddr.cc [hunk 7]
```diff
@@ -2526,6 +2526,7 @@ class test_ucp_sockaddr_protocols : public test_ucp_sockaddr {
             std::string sb(size, 'x');
             std::string rb(size, 'y');
             std::string shdr(hdr_size, 'x');
+            std::string shdr_cpy = shdr;
```
Comment (gleon99) [inline test/gtest/ucp/test_ucp_sockaddr.cc:2529]: `cpy` -> `copy`

File: test/gtest/ucp/test_ucp_sockaddr.cc [hunk 8]
```diff
@@ -2550,8 +2551,12 @@ class test_ucp_sockaddr_protocols : public test_ucp_sockaddr {
             param.flags         = flags;
 
             ucs_status_ptr_t sreq = ucp_am_send_nbx(sender().ep(), 0,
-                                                    &shdr[0], hdr_size,
+                                                    &shdr_cpy[0], hdr_size,
                                                     &sb[0], size, &param);
+            if (flags & UCP_AM_SEND_FLAG_COPY_HEADER) {
+                shdr_cpy[0] = 'X';
```
Comment (gleon99) [inline test/gtest/ucp/test_ucp_sockaddr.cc:2557]: Please add an explanation (comment)

File: test/gtest/ucp/test_ucp_sockaddr.cc [hunk 9]
```diff
@@ -2550,8 +2551,16 @@ class test_ucp_sockaddr_protocols : public test_ucp_sockaddr {
...
             ucs_status_ptr_t sreq = ucp_am_send_nbx(sender().ep(), 0,
-                                                    &shdr[0], hdr_size,
+                                                    &shdr_copy[0], hdr_size,
                                                     &sb[0], size, &param);
+            /* First message request triggers connection establishment and
+             * is placed into pending queue.
+             * To check UCP_AM_SEND_FLAG_COPY_HEADER we change AM header 
+             * content while the request is still in pending queue.*/ 
+            if (flags & UCP_AM_SEND_FLAG_COPY_HEADER) {
+                shdr_copy[0] = 'X';
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_sockaddr.cc:2561]: 1. the shdr_copy should remain the original value and shdr should be "corrupted"
2. i would fill entire "corrupted" header with aaa..

File: src/ucp/proto/proto_reconfig.c [hunk 10]
```diff
@@ -47,10 +59,19 @@ static ucs_status_t ucp_proto_reconfig_progress(uct_pending_req_t *self)
...
+        ucp_proto_reconfig_abort(req, UCS_ERR_CANCELED);
         return UCS_OK;
     }
 
+    if (ucs_unlikely(ucp_proto_config_is_am(req->send.proto_config) &&
+                     (req->send.msg_proto.am.flags &
+                      UCP_AM_SEND_FLAG_COPY_HEADER))) {
+        status = ucp_proto_am_req_copy_header(req);
+        if (ucs_unlikely(status != UCS_OK)) {
+            return status;
```
Comment (yosefe) [inline src/ucp/proto/proto_reconfig.c:71]: if copy fails we should abort the operation and return OK from progress. pls see how it's done in other places ucp_proto_am_req_copy_header is used

File: src/ucp/proto/proto_reconfig.c [hunk 11]
```diff
@@ -47,10 +59,19 @@ static ucs_status_t ucp_proto_reconfig_progress(uct_pending_req_t *self)
                                   ucp_operation_names, &strb);
         ucs_error("cannot find remote protocol for: %s",
                   ucs_string_buffer_cstr(&strb));
-        ucp_request_complete_send(req, UCS_ERR_CANCELED);
+        ucp_proto_reconfig_abort(req, UCS_ERR_CANCELED);
         return UCS_OK;
     }
 
+    if (ucs_unlikely(ucp_proto_config_is_am(req->send.proto_config) &&
```
Comment (yosefe) [inline src/ucp/proto/proto_reconfig.c:66]: This is not fast path so ucs_unlikely is not needed here

File: src/ucp/proto/proto_reconfig.c (hunk 10 above)
Comment (ofirfarjun7) [reply src/ucp/proto/proto_reconfig.c:71]: After checking code again we noticed that also for other protocols in protov2 `status != UCS_OK` case is not handled properly. I will fix it and add it to this PR.

**Review by yosefe — COMMENTED** [review]
i'm not sure the refactoring of copy header in this pr totally makes sense; can we keep only the minimal fix for copy header and add TODO/FIXME comments where there is an issue with passing the return value? so we can at least merge the bugfix

File: src/ucp/am/eager_multi.c [hunk 12]
```diff
@@ -134,8 +134,8 @@ static UCS_F_ALWAYS_INLINE ucs_status_t ucp_am_eager_multi_bcopy_send_func(
         packed_size = uct_ep_am_bcopy(uct_ep, UCP_AM_ID_AM_FIRST,
                                       ucp_am_eager_multi_bcopy_pack_args_first,
                                       &pack_ctx, 0);
-        status      = ucp_proto_bcopy_send_func_status(packed_size);
-        status      = ucp_proto_am_handle_user_header_send_status(req, status);
+        status      = ucp_am_handle_user_header_send_status_common(
```
[the remark this answers is not in the document]
Comment (ofirfarjun7) [reply src/ucp/am/eager_multi.c:137]: From what I see in case of an error status is handled by `ucp_proto_multi_handle_send_error` and it called `abort` function

File: src/ucp/am/eager_single.c [hunk 13]
```diff
@@ -72,9 +73,17 @@ ucp_am_eager_short_proto_progress_common(uct_pending_req_t *self, int is_reply)
...
-    status = ucp_proto_am_handle_user_header_send_status(req, status);
     if (ucs_unlikely(status == UCS_ERR_NO_RESOURCE)) {
         req->send.lane = spriv->super.lane; /* for pending add */
+        if (ucs_unlikely(req->send.msg_proto.am.flags &
+                         UCP_AM_SEND_FLAG_COPY_HEADER)) {
+            copy_status = ucp_proto_am_req_copy_header(req);
+            if (ucs_unlikely(copy_status != UCS_OK)) {
+                ucp_proto_request_abort(req, copy_status);
+                return UCS_OK;
+            }
```
[the remark this answers is not in the document]
Comment (ofirfarjun7) [reply src/ucp/am/eager_single.c:84]: How we will know if `ucp_am_handle_user_header_send_status_or_abort` succeed or failed? in case of a failure we need to return.
The only way is to compare `status` with the return value of `ucp_am_handle_user_header_send_status_or_abort`, but I think it's not a good practice.

File: src/ucp/proto/proto_am.inl [hunk 14]
```diff
@@ -125,22 +108,68 @@ ucp_do_am_bcopy_single(uct_pending_req_t *self, uint8_t am_id,
...
+    req->flags                       |= UCP_REQUEST_FLAG_USER_HEADER_COPIED;
+    req->send.msg_proto.am.header.ptr = user_header;
+
+    return UCS_OK;
+}
+
+static UCS_F_ALWAYS_INLINE ucs_status_t
+ucp_am_handle_user_header_send_status_common(ucp_request_t *req,
+                                             ucs_status_t status, int abort,
+                                             int release)
```
[the remark this answers is not in the document]
Comment (ofirfarjun7) [reply src/ucp/proto/proto_am.inl:139]: We still have the `eager_multi.c` case...
If we ignore the `eager_multi.c` case I want to reuse code, but your suggestion indeed make the code more clear.
I will try to come up with a better why to reuse code maybe.

File: src/ucp/proto/proto_reconfig.c [hunk 15]
```diff
@@ -47,10 +59,19 @@ static ucs_status_t ucp_proto_reconfig_progress(uct_pending_req_t *self)
                                   ucp_operation_names, &strb);
         ucs_error("cannot find remote protocol for: %s",
                   ucs_string_buffer_cstr(&strb));
-        ucp_request_complete_send(req, UCS_ERR_CANCELED);
+        ucp_proto_request_abort(req, UCS_ERR_CANCELED);
         return UCS_OK;
     }
 
+    if (ucp_proto_config_is_am(req->send.proto_config) &&
```
[the remark this answers is not in the document]
Comment (ofirfarjun7) [reply src/ucp/proto/proto_reconfig.c:66]: How we will know if ucp_am_handle_user_header_send_status_or_abort succeed or failed? in case of a failure we need to return.
The only way is to compare status with the return value of ucp_am_handle_user_header_send_status_or_abort, but I think 
we discussed it and decided that it's not a good practice.

**Comment by ofirfarjun7** [comment]
> i'm not sure the refactoring of copy header in this pr totally makes sense; can we keep only the minimal fix for copy header and add TODO/FIXME comments where there is an issue with passing the return value? so we can at least merge the bugfix

Hi. We can do it in a different PR.

**Review by yosefe — APPROVED** [review]
