### PR TITLE
UCT/TCP: add enable loopback flag. [v1.10]

### LINKED ISSUE #6695: UCX 1.10 with TCP-only is unable to reach destination
```
UCX_TLS=tcp ucx_perftest -t tag_bw -s 1000000 -n 1000 10.150.166.222
+--------------+--------------+-----------------------------+---------------------+-----------------------+
|              |              |      overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | typical | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
[1619044902.015564] [host:33810:0]           sock.c:261  UCX  ERROR connect(fd=23, dest_addr=127.0.0.1:47793) failed: Connection refused
[1619044902.015588] [host:33810:0]        libperf.c:1238 UCX  ERROR ucp_ep_create() failed: Destination is unreachable
[1619044902.015607] [host:33810:0]        libperf.c:1724 UCX  ERROR Failed to setup endpoints: Destination is unreachable
[1619044902.021124] [host:33810:0]       perftest.c:1652 UCX  ERROR Failed to run test: Destination is unreachable
```

But when I do the exact same command, by forcing the interface, I get:
```
UCX_NET_DEVICES=enp161s0 UCX_TLS=tcp ucx_perftest -t tag_bw -s 1000000 -n 1000 10.150.166.222
+--------------+--------------+-----------------------------+---------------------+-----------------------+
|              |              |      overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | typical | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
Final:                  1000     0.000   385.838   385.838     2471.70    2471.70        2592        2592
```
I have the loopback interface, and also the `enp161s0` interface. Here's ifconfig for my client:

```
enp161s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9000
        inet 10.150.166.223  netmask 255.255.255.192  broadcast 10.150.166.255
        inet6 fe80::e42:a1ff:fe61:4a8c  prefixlen 64  scopeid 0x20<link>
        ether 0c:42:a1:61:4a:8c  txqueuelen 1000  (Ethernet)
        RX packets 722009727  bytes 5372543023782 (5.3 TB)
        RX errors 0  dropped 5  overruns 0  frame 0
        TX packets 783147794  bytes 5957117294447 (5.9 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 123318880  bytes 2655187036841 (2.6 TB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 123318880  bytes 2655187036841 (2.6 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

And my server looks the same, just with the other ip address. Any ideas?

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
Configurable loopback address support

## Why ?
To fix #6695 in 1.10 without porting #6704

### CODE REVIEW

File: src/uct/tcp/tcp_iface.c [hunk 1]
```diff
@@ -766,7 +772,10 @@ ucs_status_t uct_tcp_query_devices(uct_md_h md,
             continue;
         }
 
-        if (!ucs_netif_is_active(entry->d_name)) {
+        uct_md_iface_config_read(md, "tcp", NULL, NULL, &config);
+        iface_config = ucs_derived_of(config, uct_tcp_iface_config_t);
+
+        if (!ucs_netif_is_active(entry->d_name, iface_config->loopback_enable)) {
```
Comment (dmitrygx) [inline src/uct/tcp/tcp_iface.c:778]: maybe it worth to introduce `ucs_netif_is_loopback` which gets iface flags and checks `(ifr.ifr_flags & IFF_LOOPBACK)`?
so it will be like this:
```suggestion
        if (!ucs_netif_is_active(entry->d_name) ||
            (iface_config->loopback_enable && ucs_netif_is_loopback(entry->d_name))) {
```
wdyt?

File: src/ucs/sys/sock.c [hunk 2]
```diff
@@ -112,6 +112,9 @@ int ucs_netif_is_active(const char *if_name)
         return 0;
     }
 
+    if (!enable_loopback && (ifr.ifr_flags & IFF_LOOPBACK)) {
+        return 0;
+    }
```
Comment (yosefe) [inline src/ucs/sys/sock.c:117]: minor: space line after

File: src/uct/tcp/tcp.h [hunk 3]
```diff
@@ -405,6 +405,7 @@ typedef struct uct_tcp_iface_config {
     uct_iface_mpool_config_t       tx_mpool;
     uct_iface_mpool_config_t       rx_mpool;
     ucs_range_spec_t               port_range;
+    int                            loopback_enable;
```
Comment (yosefe) [inline src/uct/tcp/tcp.h:408]: uint8

File: src/uct/tcp/tcp_iface.c [hunk 4]
```diff
@@ -766,7 +772,10 @@ ucs_status_t uct_tcp_query_devices(uct_md_h md,
             continue;
         }
 
-        if (!ucs_netif_is_active(entry->d_name)) {
+        uct_md_iface_config_read(md, "tcp", NULL, NULL, &config);
+        iface_config = ucs_derived_of(config, uct_tcp_iface_config_t);
```
Comment (yosefe) [inline src/uct/tcp/tcp_iface.c:776]: we can add configuration for tcp memory domain and put it there (so it will be available before creating the interface)

**Review by yosefe — COMMENTED** [review]
maybe remove unrelated whitespace fixes from this PR?

File: NEWS [hunk 5]
```diff
@@ -13,6 +13,7 @@
 * Fix build issues in gtest-all.cc and sock.c with GCC11
 * Fix performance degradation with cuda memory on self endpoint
 * Fix bug in JUCX listener connection handler.
+* Configurable loopback interface for TCP.
```
Comment (shamisp) [inline NEWS:16]: Maybe we should add that it is disabled by default

File: src/uct/tcp/tcp.h [hunk 6]
```diff
@@ -405,14 +405,20 @@ typedef struct uct_tcp_iface_config {
...
     ucs_range_spec_t               port_range;
-    int                            loopback_enable;
     struct {
         ucs_time_t                 idle;
         unsigned                   cnt;
         ucs_time_t                 intvl;
     } keepalive;
 } uct_tcp_iface_config_t;
 
+/**
```
Comment (yosefe) [inline src/uct/tcp/tcp.h:415]: 2 space lines in H file

File: src/uct/tcp/tcp.h [hunk 7]
```diff
@@ -405,14 +405,20 @@ typedef struct uct_tcp_iface_config {
...
+ * TCP md configuration
+ */
+typedef struct uct_tcp_md_config {
+    uct_md_config_t super;
+    uint8_t  loopback_enable;
+} uct_tcp_md_config_t;
```
Comment (yosefe) [inline src/uct/tcp/tcp.h:421]: align on column

File: src/uct/tcp/tcp.h [hunk 8]
```diff
@@ -405,14 +405,20 @@ typedef struct uct_tcp_iface_config {
...
         ucs_time_t                 intvl;
     } keepalive;
 } uct_tcp_iface_config_t;
 
+/**
+ * TCP md configuration
+ */
+typedef struct uct_tcp_md_config {
+    uct_md_config_t super;
+    uint8_t  loopback_enable;
```
Comment (yosefe) [inline src/uct/tcp/tcp.h:420]: should be int

File: src/uct/tcp/tcp_iface.c [hunk 9]
```diff
@@ -772,10 +768,14 @@ ucs_status_t uct_tcp_query_devices(uct_md_h md,
             continue;
         }
 
-        uct_md_iface_config_read(md, "tcp", NULL, NULL, &config);
-        iface_config = ucs_derived_of(config, uct_tcp_iface_config_t);
+        uct_md_config_read(md->component, "tcp", NULL, &md_config);
```
Comment (yosefe) [inline src/uct/tcp/tcp_iface.c:771]: should take it from tcp_md object (fill it when initializing tcp md), instead of read every time during query_resources

File: src/uct/tcp/tcp.h (hunk 8 above)
Comment (petro-rudenko) [reply src/uct/tcp/tcp.h:420]: https://github.com/openucx/ucx/pull/6720#discussion_r622269161

Comment (yosefe) [reply src/uct/tcp/tcp.h:420]: my previous comment was a mistake, since it's config parser structure it has to be int

**Review by shamisp — APPROVED** [review]

**Comment by yosefe** [comment]
bot:pipe:retest

File: src/uct/tcp/tcp.h [hunk 10]
```diff
@@ -413,6 +413,24 @@ typedef struct uct_tcp_iface_config {
...
+    int                 loopback_enable;
+} uct_tcp_md_config_t;
+
+
+/**
+ * TCP MD descriptor
+ */
+typedef struct uct_tcp_md {
+    uct_md_t            super;
+    uint8_t             loopback_enable;
```
Comment (yosefe) [inline src/uct/tcp/tcp.h:430]: 👍

File: src/uct/tcp/tcp_iface.c [hunk 11]
```diff
@@ -733,6 +733,7 @@ ucs_status_t uct_tcp_query_devices(uct_md_h md,
     unsigned num_devices;
     ucs_status_t status;
     DIR *dir;
+    uct_tcp_md_t *tcp_md = ucs_derived_of(md, uct_tcp_md_t);
```
Comment (yosefe) [inline src/uct/tcp/tcp_iface.c:736]: initialized vars should come 1st

File: src/uct/tcp/tcp_md.c [hunk 12]
```diff
@@ -12,6 +12,17 @@
 #include <uct/base/uct_md.h>
 
 
+static ucs_config_field_t uct_tcp_md_config_table[] = {
+    {"", "", NULL,
+     ucs_offsetof(uct_tcp_md_config_t, super), UCS_CONFIG_TYPE_TABLE(uct_md_config_table)},
+
+    {"LOOPBACK_ENABLE", "n",
+    "Enable loopback interface for TCP device selection.",
+    ucs_offsetof(uct_tcp_md_config_t, loopback_enable), UCS_CONFIG_TYPE_BOOL},
```
Comment (yosefe) [inline src/uct/tcp/tcp_md.c:21]: minor: indent

File: src/uct/tcp/tcp_md.c [hunk 13]
```diff
@@ -37,24 +48,40 @@ static ucs_status_t uct_tcp_md_mem_reg(uct_md_h md, void *address, size_t length
...
         .mem_dereg          = ucs_empty_function_return_success,
         .detect_memory_type = ucs_empty_function_return_unsupported
     };
-    static uct_md_t md = {
-        .ops          = &md_ops,
-        .component    = &uct_tcp_component
-    };
 
-    *md_p = &md;
+    tcp_md_config = ucs_derived_of(md_config, uct_tcp_md_config_t);
```
Comment (yosefe) [inline src/uct/tcp/tcp_md.c:73]: init inline?

Comment (petro-rudenko) [reply src/uct/tcp/tcp_md.c:73]: Just cast `md_config` to `uct_tcp_md_config_t` ?

Comment (yosefe) [reply src/uct/tcp/tcp_md.c:73]: `uct_tcp_md_config_t *tcp_md_config = ucs_derived_of(md_config, uct_tcp_md_config_t);`
and move initialized vars to function start

**Review by yosefe — APPROVED** [review]

**Comment by petro-rudenko** [comment]
squashed

**Comment by yosefe** [comment]
bot:pipe:retest
