### PR TITLE
UCP/WIREUP: Fix buffer overflow read in select logic

### LINKED ISSUE #4868: ucx_info fails with fail with `-fsanitize-address` enabled
```
$ ./install/bin/ucx_info -e -w -u tra
=================================================================
==10033==ERROR: AddressSanitizer: global-buffer-overflow on address 0x7ffff6e176f0 at pc 0x7ffff6b469c6 bp 0x7fffffffb6d0 sp 0x7fffffffb6c8
READ of size 8 at 0x7ffff6e176f0 thread T0
    #0 0x7ffff6b469c5 in ucp_wireup_get_missing_flag_desc wireup/select.c:154
    #1 0x7ffff6b46bf8 in ucp_wireup_check_flags wireup/select.c:200
    #2 0x7ffff6b489cc in ucp_wireup_select_transport wireup/select.c:353
    #3 0x7ffff6b4de51 in ucp_wireup_add_bw_lanes wireup/select.c:1033
    #4 0x7ffff6b4f2ca in ucp_wireup_add_rma_bw_lanes wireup/select.c:1195
    #5 0x7ffff6b506f0 in ucp_wireup_search_lanes wireup/select.c:1389
    #6 0x7ffff6b51e52 in ucp_wireup_select_lanes wireup/select.c:1536
    #7 0x7ffff6b67e4c in ucp_wireup_init_lanes wireup/wireup.c:964
    #8 0x7ffff6a0d2c9 in ucp_ep_create_to_worker_addr core/ucp_ep.c:341
    #9 0x7ffff6a0f19d in ucp_ep_create_api_to_worker_addr core/ucp_ep.c:613
    #10 0x7ffff6a0fb1a in ucp_ep_create core/ucp_ep.c:678
    #11 0x403e22 in print_ucp_info /labhome/dmitrygla/work_auto/ucx/src/tools/info/proto_info.c:186
    #12 0x40b16d in main /labhome/dmitrygla/work_auto/ucx/src/tools/info/ucx_info.c:214
    #13 0x7ffff4f77c04 in __libc_start_main (/usr/lib64/libc.so.6+0x21c04)
    #14 0x402958  (/auto/mtrswgwork/dmitrygla/install/bin/ucx_info+0x402958)

0x7ffff6e176f0 is located 32 bytes to the right of global variable 'ucp_wireup_md_flags' defined in 'wireup/select.c:103:20' (0x7ffff6e176c0) of size 16
0x7ffff6e176f0 is located 16 bytes to the left of global variable 'ucp_wireup_iface_flags' defined in 'wireup/select.c:108:20' (0x7ffff6e17700) of size 432
SUMMARY: AddressSanitizer: global-buffer-overflow wireup/select.c:154 in ucp_wireup_get_missing_flag_desc
Shadow bytes around the buggy address:
  0x10007edbae80: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007edbae90: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007edbaea0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007edbaeb0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007edbaec0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
=>0x10007edbaed0: 00 00 00 00 00 00 00 00 00 00 f9 f9 f9 f9[f9]f9
  0x10007edbaee0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007edbaef0: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007edbaf00: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0x10007edbaf10: 00 00 00 00 00 00 f9 f9 f9 f9 f9 f9 00 00 00 00
  0x10007edbaf20: 00 00 00 00 00 00 00 00 f9 f9 f9 f9 00 00 00 00
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==10033==ABORTING
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix buffer overflow read in select logic

## Why ?

Fixes #4868 

## How ?

Add missing entry in the `ucp_wireup_md_flags` array for `UCT_MD_FLAG_RKEY_PTR` flag that's used to search for RKEY PTR lane

### CODE REVIEW

**Comment by dmitrygx** [comment]
@brminich @hoopoepg could you review pls?

File: src/ucp/wireup/select.c [hunk 1]
```diff
@@ -103,6 +103,7 @@ typedef struct {
 static const char *ucp_wireup_md_flags[] = {
     [ucs_ilog2(UCT_MD_FLAG_ALLOC)]               = "memory allocation",
     [ucs_ilog2(UCT_MD_FLAG_REG)]                 = "memory registration",
+    [ucs_ilog2(UCT_MD_FLAG_RKEY_PTR)]            = "obtain remote memory pointer"
```
Comment (hoopoepg) [inline src/ucp/wireup/select.c]: shouldn't other flags be initialized as well?

Comment (dmitrygx) [reply src/ucp/wireup/select.c]: If I'm not mistaken, other flags don't participate in selection logic.
@yosefe @brminich do we need to add:
- `UCT_MD_FLAG_ADVISE`
- `UCT_MD_FLAG_FIXED`
- `UCT_MD_FLAG_SOCKADDR`?

Other flags just inform the local user if there are any restrictions (e.g. `UCT_MD_FLAG_NEED_MEMH` requires providing a memory handle for a local buffer)

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/0e4e9c13a7fc9129ff037372490cb25cb5ca8416/_main) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/06ec97aa1fb37ba6501edf425254ad2824bb994e/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/bfc7bf62e1ec3c2b13984e8260093203d2fc4593/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/9c109e3dff177f9d3050713017d61eff0989d371/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/c85d6f7a3dee3153f175564724c44dd2c530eccf/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/a29031f357ca6ded9204bca8bafa5044e5e2a4ba/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/b804adcfe482189f1d453030b6abc9df52f1fc40/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/c4628dc5c9a6a696ca42dcd0f2b5a45f0ff5da52/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/afc5c20f77c018c353324b5ebe942941369d5e1d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/b951dca6b7a2441da51a58a23cee6ef126f075d9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/583bef33c6793c268776cded7f408f6102777cb9/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/3adc3238703b158bb3d80d4f3b280514db7a8566/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/0d8bd9f1df90ef84a8db3e44c1cc91ff5289540d/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/385c6e0488d793de63cfcf40060d22addd840571/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/df1b114003816d8a31f1773157a917e230c22573/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/6ca92fd26033b3630b129017e5d9fda397dac998/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/648f110d00a4c192ec0cd28cefe2115f63db8918/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/4b78108aae86124da7440a1832523997c3bee848/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/820758219b4be686fbfe94b759cba3615ab3bd91/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/98a76615f52d3778708cac28500f236f820defbc/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/2778520061bdc19f8692649eb5c04dfba0bd32b8/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/16259e36ef664ac931f5e91df932a6123aaf3bca/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/3692b48527b6cce307641ac83a4cc721c1f88ce6/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/c136136891686dab7bb2ce5cfb6c485ef021c652/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4ef5189dd1535929af647fb33954f934/raw/4523f1722d1a9cf7db2d7f1b875650c13090b009/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 19-Mar-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/a80901355b9389220af85f81fbd304563d6bd51d/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/bce5bd0c703355a49e63eb6691ede993aa9c0de1/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/c10e986b3e5683c63dbd43a70b57e6aece3a3eb6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/7221de7ef24d79b3e1c54b81fc86ec8b8f68ad40/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/363cd6c72ee079c1c81fc366c0d724408c2fc979/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/02cae184d436a903cb6f66baf31f09ac759ce598/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/a7794fac104170a857ab38c65ade6b479a2dbd3c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/1f4666482f4cc66925ba0cba8b83ef9f3522a0bd/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/b1919719fb27b6d2b95815e967a5b3ba76c725e5/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/40e157ffbc83d173de7ca9abad8a571cc345bcaa/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/bcfc244ab1182d61230563b58b1261b10ab59616/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/10c17b4ed5728a2b1e01fb1df504bf84bd75e26c/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/2fa0c27cfc4303e059e51b733abf60df89b89482/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/d0c45b6840420294da3b0b39ff4bba6c07b504b2/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/901c7e454306a4c9427eb6d4f96e55f4952b8b10/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/0b9e558d97d9857d888d312f3aaab7f86c943d3e/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/80d9b078b8dd7c733feea37faec8579c4f4165fe/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/40805119d675ec8dae20dcb18a40a21118811261/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/d18858e87716f304c9d2c8bb8371a687048c6c26/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/b751a6305c6989ab7f9c29f5fe2a852a679eb92e/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/dc66d7aa29dfe77b08c6b2a518fa115b4a63efbb/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/ebb2eba835604a52790615b840c36f6d37f06ec4/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/c4e814e4857a5c5dd02acf589055da06c5f188c4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/f842289ef575defea9797b786da8d8c4a348c67a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fdf2adab60894e96df24aed3d5c10f01/raw/88d52fcfdf36b80549fb03a174021c6b94e9f9bc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
