### PR TITLE
UCS/ARBITER/TEST: Allow same-group rescheduling from dispatch callback

### LINKED ISSUE #4267: [SparkUCX] Arbiter assertion when submitting requests from ep_flush callback
Here's pseudocode what happens at the heart of [SparkUCX](https://github.com/openucx/sparkucx/pull/6/files#diff-fae1b3825d9911fcacb67248ff4093a3R114-R170):
```
void submit_n_nb_requests(endpoint ep) {
   for (i = 0; i < n; i++) {
       ucp_get_nbi(ep, ...);
   }
}

for (Endpoint ep: all_endpoints) { // fails when # of enpoints > 25
    submit_n_nb_requests(ep); // Submit n get requests
    ucp_ep_flush_nb({
        submit_n_nb_requests(ep); //Submit another one n requests -- fails here
        ucp_ep_flush_nb(do_something_else);
    });
}

}
```

When a number of nodes > 23-25 it starts to fail with a next exception:
```
[clx-hercules-063:6190 :0:6349]     arbiter.c:213  Assertion `(arbiter)->guard == 0' failed: scheduling group from the arbiter callback
[clx-hercules-063:6190 :1:6346]     arbiter.c:213  Assertion `(arbiter)->guard == 0' failed: scheduling group from the arbiter callback

/hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucs/datastruct/arbiter.c: [ ucs_arbiter_group_schedule_nonempty() ]
      ...
      210     ucs_arbiter_elem_t *current, *head;
      211
      212     UCS_ARBITER_GUARD_CHECK(arbiter);
==>   213
      214     ucs_assert(tail != NULL);
      215     head = tail->next;
      216


/hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucs/datastruct/arbiter.c: [ ucs_arbiter_group_schedule_nonempty() ]
      ...
      210     ucs_arbiter_elem_t *current, *head;
      211
      212     UCS_ARBITER_GUARD_CHECK(arbiter);
==>   213
      214     ucs_assert(tail != NULL);
      215     head = tail->next;
      216

==== backtrace (tid:   6349) ====
 0 0x000000000004d4d4 ucs_arbiter_group_schedule_nonempty()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucs/datastruct/arbiter.c:213
 1 0x0000000000023293 ucs_arbiter_group_schedule()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucs/datastruct/arbiter.h:261
 2 0x0000000000022342 uct_ep_pending_add()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/uct/api/uct.h:2570
 3 0x000000000003362d ucp_request_try_send()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucp/core/ucp_request.inl:188
 4 0x000000000003362d ucp_rma_nonblocking()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucp/rma/rma_send.c:172
 5 0x000000000003362d ucp_get_nbi()  /hpc/scrap/users/swat/jenkins/ucx/contrib/../src/ucp/rma/rma_send.c:291
 6 0x00000000000040dc Java_org_openucx_jucx_ucp_UcpEndpoint_getNonBlockingImplicitNative()  ???:0
```

### PR DESCRIPTION
**Pull request by yosefe**
# Why
Fixes #4267

### CODE REVIEW

**Comment by yosefe** [comment]
bot:pipe:retest

**Comment by yosefe** [comment]
@hoopoepg @brminich @dmitrygx can you pls review?

File: src/ucs/datastruct/arbiter.c [hunk 1]
```diff
@@ -174,6 +171,25 @@ void ucs_arbiter_group_purge(ucs_arbiter_t *arbiter,
     }
 }
 
+size_t ucs_arbiter_group_num_elems(ucs_arbiter_group_t *group)
+{
+    ucs_arbiter_elem_t *elem = group->tail;
+    size_t num_elems;
+
+    if (elem == NULL) {
```
Comment (dmitrygx) [inline src/ucs/datastruct/arbiter.c:179]: can use `ucs_arbiter_group_is_empty()` instead

File: src/ucs/datastruct/arbiter.c [hunk 2]
```diff
@@ -230,19 +240,47 @@ void ucs_arbiter_group_desched_nonempty(ucs_arbiter_t *arbiter,
...
+     }
+}
+
+static inline void
+ucs_arbiter_group_head_replace(ucs_arbiter_group_t *group,
+                               ucs_arbiter_elem_t *group_head,
+                               ucs_arbiter_elem_t *new_group_head)
+{
+    /* check if this is really the group head */
+    ucs_assert(group->tail->next == group_head);
```
Comment (dmitrygx) [inline src/ucs/datastruct/arbiter.c:259]: what about making sure that the group isn't empty?
so, the assert can be replaced with:
```
ucs_assert(!ucs_arbiter_group_is_empty(group) &&
           ucs_arbiter_elem_is_only(group, group_head));
```

File: src/ucs/datastruct/arbiter.c [hunk 3]
```diff
@@ -254,80 +292,112 @@ void ucs_arbiter_dispatch_nonempty(ucs_arbiter_t *arbiter, unsigned per_group,
...
-                    /* Last element */
-                    group->tail = NULL; /* Group is empty now */
-                    sched_group = 0;
-                    group_head  = NULL; /* for debugging */
+            /* should not push to head */
+            ucs_assert(group->tail->next == &dummy);
+
+            /* element is not removed */
+            if (ucs_unlikely(result != UCS_ARBITER_CB_RESULT_REMOVE_ELEM)) {
+
```
Comment (dmitrygx) [inline src/ucs/datastruct/arbiter.c:331]: minor: do we need this empty line?

File: src/ucs/datastruct/arbiter.c (hunk 1 above)
Comment (hoopoepg) [reply src/ucs/datastruct/arbiter.c:179]: this call is used in tests

File: test/gtest/ucs/test_arbiter.cc [hunk 4]
```diff
@@ -890,31 +892,47 @@ test_arbiter_random_resched::dispatch(ucs_arbiter_group_t *_group,
...
     /* Test ucs_arbiter_elem_is_only() */
     if (group->num_elems == 1) {
         ++m_num_only;
         EXPECT_TRUE(ucs_arbiter_elem_is_only(&group->super, elem));
     }
 
+    /* Randomly add few more elements to same group */
+    while ((ucs::rand() % 4) == 0) {
+        add_new_elem(group);
+        if (ucs::rand() % 2) {
```
Comment (dmitrygx) [inline test/gtest/ucs/test_arbiter.cc:910]: `((ucs::rand() % 2) == 0)` to be consistent with `if` statement above

File: test/gtest/ucs/test_arbiter.cc [hunk 5]
```diff
@@ -890,31 +892,47 @@ test_arbiter_random_resched::dispatch(ucs_arbiter_group_t *_group,
...
+            ucs_arbiter_group_schedule(&m_arb, &group->super);
+        }
+    }
+
     if (ucs::rand() % 2) {
```
Comment (dmitrygx) [inline test/gtest/ucs/test_arbiter.cc:915]: `((ucs::rand() % 2) == 0)` to be consistent with `if` statement above

File: src/ucs/datastruct/arbiter.c (hunk 1 above)
Comment (dmitrygx) [reply src/ucs/datastruct/arbiter.c:179]: > this call is used in tests

ah, didn't notice this

File: src/ucs/datastruct/arbiter.h [hunk 6]
```diff
@@ -383,7 +388,7 @@ ucs_arbiter_dispatch(ucs_arbiter_t *arbiter, unsigned per_group,
 static inline int
 ucs_arbiter_elem_is_only(ucs_arbiter_group_t *group, ucs_arbiter_elem_t *elem)
```
Comment (brminich) [inline src/ucs/datastruct/arbiter.h:389]: we do not need group here anymore

File: src/ucs/datastruct/arbiter.c [hunk 7]
```diff
@@ -46,23 +46,28 @@ static inline void ucs_arbiter_group_head_reset(ucs_arbiter_elem_t *head)
...
+{
+    elem->group = group;
+}
+
 void ucs_arbiter_group_push_elem_always(ucs_arbiter_group_t *group,
                                         ucs_arbiter_elem_t *elem)
 {
     ucs_arbiter_elem_t *tail = group->tail;
 
-    UCS_ARBITER_GROUP_GUARD_CHECK(group);
```
Comment (brminich) [inline src/ucs/datastruct/arbiter.c:54]: why is guard removed here?

File: src/ucs/datastruct/arbiter.c [hunk 8]
```diff
@@ -158,8 +155,8 @@ void ucs_arbiter_group_purge(ucs_arbiter_t *arbiter,
             prev->next = next;
         } else {
             /* keep the element */
-            ptr->next = next; /* Restore next pointer */
-            prev      = ptr;
+            ucs_arbiter_elem_set_scheduled(ptr, group);
+            prev       = ptr;
```
Comment (brminich) [inline src/ucs/datastruct/arbiter.c:159]: why don't need to restore ptr->next?

File: src/ucs/datastruct/arbiter.c [hunk 9]
```diff
@@ -230,19 +240,47 @@ void ucs_arbiter_group_desched_nonempty(ucs_arbiter_t *arbiter,
     ucs_arbiter_group_head_reset(head);
 }
 
+static inline void
+ucs_arbiter_remove_and_reset_if_scheduled(ucs_arbiter_elem_t *elem)
+{
+    if (ucs_unlikely(ucs_arbiter_group_head_is_scheduled(elem))) {
+         /* removing scheduled head of empty list */
```
Comment (brminich) [inline src/ucs/datastruct/arbiter.c:247]: why is list empty?

File: src/ucs/datastruct/arbiter.c [hunk 10]
```diff
@@ -254,80 +292,112 @@ void ucs_arbiter_dispatch_nonempty(ucs_arbiter_t *arbiter, unsigned per_group,
...
             ++group_dispatch_count;
 
-            if (result == UCS_ARBITER_CB_RESULT_REMOVE_ELEM) {
-                group_tail = group->tail;
-                if (group_head == group_tail) {
-                    /* Last element */
-                    group->tail = NULL; /* Group is empty now */
-                    sched_group = 0;
-                    group_head  = NULL; /* for debugging */
+            /* should not push to head */
```
Comment (brminich) [inline src/ucs/datastruct/arbiter.c:326]: why? we have api for this..

File: src/ucs/datastruct/arbiter.c (hunk 2 above)
Comment (yosefe) [reply src/ucs/datastruct/arbiter.c:259]: ucs_arbiter_elem_is_only() is not exactly the same check, so added assertion that group is not empty

File: src/ucs/datastruct/arbiter.c (hunk 3 above)
Comment (yosefe) [reply src/ucs/datastruct/arbiter.c]: removed

File: src/ucs/datastruct/arbiter.c [hunk 11]
```diff
@@ -254,80 +292,112 @@ void ucs_arbiter_dispatch_nonempty(ucs_arbiter_t *arbiter, unsigned per_group,
...
+            if (dummy.next == &dummy) {
+                group->tail = NULL; /* group is empty now */
+                group_head  = NULL; /* for debugging */
+                ucs_arbiter_remove_and_reset_if_scheduled(&dummy);
+                UCS_ARBITER_GROUP_ARBITER_SET(group, NULL);
+                break;
+            }
+
+            /* non-last element removed */
+            group_head        = dummy.next;  /* Update group head */
```
[the remark this answers is not in the document]
Comment (yosefe) [reply src/ucs/datastruct/arbiter.c:381]: it's not exactly the same, here we don't need to restore group_head->next pointer, and no need to check that the head is not the only element

File: test/gtest/ucs/test_arbiter.cc (hunk 4 above)
Comment (yosefe) [reply test/gtest/ucs/test_arbiter.cc]: fixed

File: test/gtest/ucs/test_arbiter.cc (hunk 5 above)
Comment (yosefe) [reply test/gtest/ucs/test_arbiter.cc]: fixed

File: src/ucs/datastruct/arbiter.h (hunk 6 above)
Comment (yosefe) [reply src/ucs/datastruct/arbiter.h]: removed

File: src/ucs/datastruct/arbiter.c (hunk 7 above)
Comment (yosefe) [reply src/ucs/datastruct/arbiter.c:54]: because now we allow recursive push during dispatch (which was the goal of the PR)

File: src/ucs/datastruct/arbiter.c (hunk 8 above)
Comment (yosefe) [reply src/ucs/datastruct/arbiter.c:159]: because now we reset ->group instead of ->next - added comment

File: src/ucs/datastruct/arbiter.c (hunk 9 above)
Comment (yosefe) [reply src/ucs/datastruct/arbiter.c]: removed comment

File: src/ucs/datastruct/arbiter.c (hunk 10 above)
Comment (yosefe) [reply src/ucs/datastruct/arbiter.c]: only push to tail is allowed during dispatch, push to head is harder to support and not needed for UCT pending add for now

**Comment by yosefe** [comment]
bot:pipe:retest
