### PR TITLE
UCT/TCP: Add support for messages with the length > 64k

### LINKED ISSUE #3382: assertion failure when Increasing seg_size and max_bcopy env params
Hi,

This error shows up with `UCX_TLS=tcp,sm` and not `UCX_TLS=rc`. Is there some other param required to safely increase `MAX_BCOPY/SEG_SIZE` to a larger value (`<=32768` works)?

```
[akvenkatesh@hsw211 build]$ UCX_SEG_SIZE=65536 UCX_MAX_BCOPY=65536 UCX_TLS=sm,tcp ./bin/ucx_perftest hsw210 -t tag_lat -c 0 -s 262144
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
[hsw211:52983:0:52983]   eager_rcv.c:83   Assertion `length >= hdr_len' failed
==== backtrace ====
    0  /home/akvenkatesh/ucx-github/build/lib/libucs.so.0(ucs_fatal_error_message+0xd0) [0x2b09fd0f0bab]
    1  /home/akvenkatesh/ucx-github/build/lib/libucs.so.0(+0x22d2b) [0x2b09fd0f0d2b]
    2  /home/akvenkatesh/ucx-github/build/lib/libucp.so.0(ucp_eager_first_handler+0x11c) [0x2b09fcc20fab]
    3  /home/akvenkatesh/ucx-github/build/lib/libuct.so.0(+0x1e95a) [0x2b09fcebb95a]
    4  /home/akvenkatesh/ucx-github/build/lib/libuct.so.0(uct_tcp_ep_progress_rx+0x44b) [0x2b09fcebd0df]
    5  /home/akvenkatesh/ucx-github/build/lib/libuct.so.0(uct_tcp_iface_progress+0x184) [0x2b09fcebdfdc]
    6  /home/akvenkatesh/ucx-github/build/lib/libucp.so.0(+0x1ed50) [0x2b09fcbffd50]
    7  /home/akvenkatesh/ucx-github/build/lib/libucp.so.0(ucp_worker_progress+0x137) [0x2b09fcc05431]
    8  ./bin/ucx_perftest() [0x483eb9]
    9  ./bin/ucx_perftest() [0x47dcee]
   10  ./bin/ucx_perftest() [0x47cd12]
   11  ./bin/ucx_perftest() [0x40b1c3]
   12  ./bin/ucx_perftest() [0x405f54]
   13  ./bin/ucx_perftest() [0x406185]
   14  ./bin/ucx_perftest() [0x4062bf]
   15  /usr/lib64/libc.so.6(__libc_start_main+0xf5) [0x2b09fe2bb445]
   16  ./bin/ucx_perftest() [0x403209]
===================
```

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What

Fixes #3382

## Why ?

TCP uses for AM header - `uint16_t` [0..65535], but it's not enough for messages > 65535.

## How ?

Use `unsigned` (i.e. 32-bit unsigned int) for TCP AM header instead, because internal `uct_iface_invoke_am` and  API `uct_ep_am_short` also uses this type.

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9349/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
MLX CI timed out:
```
09:51:46 [ RUN      ] dcx/test_ucp_rma.nonblocking_stream_put_nb_flush_ep/1
10:06:46 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/common/test_helpers.cc:42: Failure
10:06:46 Failed
10:06:46 Connection timed out - abort testing
10:06:46 [hpc-test-node3:22198:0:22198] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
10:06:47 ==== backtrace ====
10:06:47  0 0x00000000000dce47 __GI___sched_yield()  :0
10:06:47  1 0x000000000076c97b ucp_test::progress()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/ucp/ucp_test.cc:136
10:06:47  2 0x000000000069de8e test_ucp_memheap::test_nonblocking_implicit_stream_xfer()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/ucp/test_ucp_memheap.cc:113
10:06:47  3 0x00000000006b8a97 test_ucp_rma_nonblocking_stream_put_nb_flush_ep_Test::test_body()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/ucp/test_ucp_rma.cc:241
10:06:47  4 0x0000000000554cde ucs::test_base::run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/common/test.cc:262
10:06:47  5 0x00000000005441c3 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/common/gtest-all.cc:3562
10:06:47  6 0x000000000053863d testing::Test::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/common/gtest-all.cc:3635
10:06:47  7 0x000000000053870c testing::TestInfo::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/common/gtest-all.cc:3812
10:06:47  8 0x000000000053886f testing::TestCase::Run()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/common/gtest-all.cc:3930
10:06:47  9 0x000000000053d207 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/common/gtest-all.cc:5802
10:06:47 10 0x000000000053d50b testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/common/gtest-all.cc:5719
10:06:47 11 0x00000000004e5f23 main()  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-node3/worker/3/contrib/../test/gtest/common/gtest.h:20059
10:06:47 12 0x0000000000021c05 __libc_start_main()  ???:0
10:06:47 13 0x0000000000522dce _start()  ???:0
10:06:47 ===================
```

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9354/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9355/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

File: src/uct/tcp/tcp.h [hunk 1]
```diff
@@ -28,7 +28,7 @@ typedef unsigned (*uct_tcp_ep_progress_t)(uct_tcp_ep_t *ep);
  */
 typedef struct uct_tcp_am_hdr {
     uint8_t                       am_id;
-    uint16_t                      length;
+    unsigned                      length;
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp.h]: Better to use types with fixed size for wired protocols, i.e. uint32_t

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9362/ for details (Mellanox internal link).

File: src/uct/tcp/tcp.h (hunk 1 above)
Comment (dmitrygladkov) [reply src/uct/tcp/tcp.h]: Yes, I agreed that it is better. But `uct_ep_am_short` uses unsigned for length, I wanted to align them.
@yosefe wdyt?

Comment (yosefe) [reply src/uct/tcp/tcp.h]: uint32_t

Comment (dmitrygladkov) [reply src/uct/tcp/tcp.h]: @evgeny-leksikov @yosefe Thanks! Fixed

**Comment by dmitrygladkov** [comment]
> maybe add/extend some gtest to catch such an error?

Added the test that covers this situation

File: test/gtest/uct/test_p2p_am.cc [hunk 2]
```diff
@@ -457,27 +457,21 @@ class uct_p2p_am_misc : public uct_p2p_am_test
...
-    uct_p2p_am_misc() :
-        uct_p2p_am_test() {
+    uct_p2p_am_misc() : uct_p2p_am_test() {
         ucs_status_t status_ib_bufs, status_ib_qlen, status_bufs;
-        m_rx_buf_limit_failed = 0;
-        status_ib_bufs = uct_config_modify(m_iface_config, "IB_RX_MAX_BUFS" , to_string(RX_MAX_BUFS).c_str());
-        status_ib_qlen = uct_config_modify(m_iface_config, "IB_RX_QUEUE_LEN", to_string(RX_QUEUE_LEN).c_str());
-        status_bufs    = uct_config_modify(m_iface_config, "RX_MAX_BUFS"    , to_string(RX_MAX_BUFS).c_str());
+        m_rx_buf_limit_failed = false;
+        status_ib_bufs = uct_config_modify(m_iface_config, "IB_RX_MAX_BUFS" ,
```
Comment (evgeny-leksikov) [inline test/gtest/uct/test_p2p_am.cc]: extra white spaces here and line 469

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9371/ for details (Mellanox internal link).

File: test/gtest/uct/test_p2p_am.cc (hunk 2 above)
Comment (dmitrygladkov) [reply test/gtest/uct/test_p2p_am.cc]: fixed

**Comment by dmitrygladkov** [comment]
re-based on top of the master

File: test/gtest/uct/test_p2p_am.cc (hunk 2 above)
Comment (dmitrygladkov) [reply test/gtest/uct/test_p2p_am.cc]: fixed

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9374/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9387/ for details (Mellanox internal link).

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/9391/ for details (Mellanox internal link).
