### PR TITLE
TEST/UD: Fix race conditions in ca_md

### LINKED ISSUE #5112: Failure in  ud_verbs/test_ud.ca_md
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/5806/logs/111
without valgrind
```
2020-05-01T07:28:44.5174677Z [ RUN      ] ud_verbs/test_ud.ca_md/1 <ud_verbs/mlx5_2:1>
2020-05-01T07:28:44.6122216Z /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/ib/test_ud.cc:581: Failure
2020-05-01T07:28:44.6123973Z Expected: (tx_count) >= (new_cwnd - 1), actual: 1 vs 127
2020-05-01T07:28:44.6593777Z /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/ib/test_ud.cc:581: Failure
2020-05-01T07:28:44.6595788Z Expected: (tx_count) >= (new_cwnd - 1), actual: 1 vs 63
2020-05-01T07:28:44.7548434Z /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/ib/test_ud.cc:581: Failure
2020-05-01T07:28:44.7550216Z Expected: (tx_count) >= (new_cwnd - 1), actual: 1 vs 31
2020-05-01T07:28:44.9466431Z /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/ib/test_ud.cc:581: Failure
2020-05-01T07:28:44.9468396Z Expected: (tx_count) >= (new_cwnd - 1), actual: 1 vs 15
2020-05-01T07:28:45.3308873Z /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/ib/test_ud.cc:581: Failure
2020-05-01T07:28:45.3310591Z Expected: (tx_count) >= (new_cwnd - 1), actual: 1 vs 7
2020-05-01T07:28:46.1000397Z /scrap/azure/agent-01/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/ib/test_ud.cc:581: Failure
2020-05-01T07:28:46.1002257Z Expected: (tx_count) >= (new_cwnd - 1), actual: 1 vs 3
2020-05-01T07:28:47.0091614Z [  FAILED  ] ud_verbs/test_ud.ca_md/1, where GetParam() = ud_verbs/mlx5_2:1 (2491 ms)
2020-05-01T07:28:47.0093351Z [ RUN      ] ud_verbs/test_ud.connect_iface_single/0 <ud_verbs/mlx5_0:1>
2020-05-01T07:28:47.3448013Z [       OK ] ud_verbs/test_ud.connect_iface_single/0 (336 ms)
2020-05-01T07:28:47.3449589Z [ RUN      ] ud_verbs/test_ud.ep_destroy_simple/2 <ud_verbs/mlx5_3:1>
2020-05-01T07:28:47.3983371Z [       OK ] ud_verbs/test_ud.ep_destroy_simple/2 (54 ms)
2020-05-01T07:28:47.3985049Z [----------] 21 tests from ud_verbs/test_ud (6632 ms total)
2020-05-01T07:28:47.3985922Z 
```

### LINKED ISSUE #5114: Hang in ud/test_ucp_tag_match_rndv.exp_huge_mix
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=5795&view=logs&j=73bd2a9e-6688-5c22-d122-7b1a0b6cbb81&t=cd3d3953-51ff-5d5c-c5ca-2864f3c1d670

swx-rdmz-ucx-gpu-01

```
2020-04-30T15:24:24.2957901Z [ RUN      ] ud/test_ucp_tag_match_rndv.req_exp_auto_thresh/1 <ud_v>
2020-04-30T15:24:24.3849684Z [       OK ] ud/test_ucp_tag_match_rndv.req_exp_auto_thresh/1 (89 ms)
2020-04-30T15:24:24.3851280Z [ RUN      ] ud/test_ucp_tag_match_rndv.exp_huge_mix/2 <ud_v>
2020-04-30T15:39:24.3657267Z /scrap/azure/agent-03/AZP_WORKSPACE/2/s/contrib/../test/gtest/common/test_helpers.cc:49: Failure
2020-04-30T15:39:24.3658227Z Failed
2020-04-30T15:39:24.3659030Z Connection timed out - abort testing
2020-04-30T17:32:53.6339642Z ##[error]The operation was canceled.
```

### PR DESCRIPTION
**Pull request by yosefe**
# Why
Fixes #5112 : don't shrink send window before resends are done. fixes the failure when ca_wnd becomes lower, but tx_count is small.
Fixes #5114: don't dispatch send completions of skb's which are still in the outstanding queue. Otherwise they could be processed again when completion does arrive, leading to access to already released skb.

# How
List of all fixes:
- If the async thread runs after reading prev_cwnd, but before setting tx_count=0, the async progress can resend and reduce cwnd, but then tx_count would be set to 0, effectively losing count of all those resends.
- Add iface locking for ep create/destroy
- Separate completion-with-error handler from timeout handler
- Use callback_q to invoke timeout handler, instead of async_comps_q
- Count number of QP-outstanding resends per endpoint, and do not
  start a new resend session before all previous resends are sent.
- Fix releasing send window during flush(CANCEL) and error flow: do
  not release skb's which have reference from the outstanding queue.
- Reset skb flags when it's allocated rather than before it's released
  (cleaner code, less error prone)
- Remove all outstanding operations on the endpoint when it's released

### CODE REVIEW

File: src/uct/ib/ud/base/ud_def.h [hunk 1]
```diff
@@ -181,8 +184,10 @@ typedef struct uct_ud_ctl_desc {
     ucs_queue_elem_t        queue;       /* Queue element in outstanding queue */
     uint16_t                sn;          /* Sequence number in outstanding queue */
     uct_ud_send_skb_t       *self_skb;   /* Back-pointer to owner skb */
-    uct_ud_send_skb_t       *resent_skb; /* Points to a re-sent skb in the window.
-                                            Can be NULL. */
+    uct_ud_send_skb_t       *resent_skb; /* For resend skb: points to a re-sent
+                                            skb in the window. Can be NULL. */
```
Comment (dmitrygx) [inline src/uct/ib/ud/base/ud_def.h:188]: maybe do not add trailing `.` as other fields don't have it

File: src/uct/ib/ud/base/ud_ep.c [hunk 2]
```diff
@@ -140,15 +141,97 @@ static ucs_status_t uct_ud_ep_free_by_timeout(uct_ud_ep_t *ep,
...
+static UCS_F_ALWAYS_INLINE void
+uct_ud_ep_window_release(uct_ud_iface_t *iface, uct_ud_ep_t *ep,
+                         uct_ud_psn_t max_psn, ucs_status_t status, int is_async)
+{
+    uct_ud_send_skb_t *skb;
+
+    ucs_queue_for_each_extract(skb, &ep->tx.window, queue,
+                               UCT_UD_PSN_COMPARE(skb->neth->psn, <=, max_psn)) {
+        ucs_assert(!(skb->flags & UCT_UD_SEND_SKB_FLAG_INVALID));
+        if (ucs_likely(!(skb->flags & (UCT_UD_SEND_SKB_FLAG_RESENDING |
```
Comment (dmitrygx) [inline src/uct/ib/ud/base/ud_ep.c:153]: maybe unite this and next `if` to the one single `if`:
```
if (ucs_likely(!(skb->flags & UCT_UD_SEND_SKB_FLAG_RESENDING))) {
    if (!(skb->flags & UCT_UD_SEND_SKB_FLAG_COMP)) {
        /* fast path case: completed skb without completion callback */
        uct_ud_skb_release(skb, 1);
    } else {
        ... <the body of the second if>
    }
} else {
    ... <the body of the thrid if>
}
```

File: src/uct/ib/ud/base/ud_ep.c [hunk 3]
```diff
@@ -140,15 +141,97 @@ static ucs_status_t uct_ud_ep_free_by_timeout(uct_ud_ep_t *ep,
...
+
+    return 0;
+}
+
+static void uct_ud_ep_timer_backoff(uct_ud_ep_t *ep)
+{
+    uct_ud_iface_t *iface = ucs_derived_of(ep->super.super.iface, uct_ud_iface_t);
+
+    ep->tx.tick *= iface->tx.timer_backoff;
+    ep->tx.tick  = ucs_min(ep->tx.tick, UCT_UD_SLOW_TIMER_MAX_TICK(iface));
```
Comment (dmitrygx) [inline src/uct/ib/ud/base/ud_ep.c:225]: [q] maybe (`ucs_min` implementation will not compute `*` twice)
```
ep->tx.tick = ucs_min(ep->tx.tick * iface->tx.timer_backoff,
                      UCT_UD_SLOW_TIMER_MAX_TICK(iface));
```

File: src/uct/ib/ud/base/ud_def.h (hunk 1 above)
Comment (yosefe) [reply src/uct/ib/ud/base/ud_def.h:188]: sure, will unify

File: src/uct/ib/ud/base/ud_ep.c (hunk 2 above)
Comment (yosefe) [reply src/uct/ib/ud/base/ud_ep.c:153]: this is for optimization reason: so that fast path case could be checked by 1 branch (check 2 flags together)

File: src/uct/ib/ud/base/ud_ep.c (hunk 3 above)
Comment (yosefe) [reply src/uct/ib/ud/base/ud_ep.c:225]: yes, can unite, it will not compute twice

File: src/uct/ib/ud/base/ud_ep.c (hunk 2 above)
Comment (dmitrygx) [reply src/uct/ib/ud/base/ud_ep.c:153]: > this is for optimization reason: so that fast path case could be checked by 1 branch (check 2 flags together)

ah, I see, thank you for the explanation!

File: src/uct/ib/ud/base/ud_def.h (hunk 1 above)
Comment (brminich) [reply src/uct/ib/ud/base/ud_def.h]: I thought typical approach is that `.` maybe skipped for a single sentence, but should be used if there are more than one sentences

File: src/uct/ib/ud/base/ud_ep.c [hunk 4]
```diff
@@ -140,15 +141,97 @@ static ucs_status_t uct_ud_ep_free_by_timeout(uct_ud_ep_t *ep,
...
+                                           status);
+                uct_ud_skb_release(skb, 1);
+            } else {
+                /* Don't call user completion from async context. Instead, put
+                 * it on a queue which will be progressed from main thread.
+                 */
+                uct_ud_iface_add_async_comp(iface, skb, status);
+            }
+        } else {
+            /* slow-path case: the skb is still used by the QP, can happen in
```
Comment (brminich) [inline src/uct/ib/ud/base/ud_ep.c:172]: `in` is not needed

File: src/uct/ib/ud/base/ud_ep.c [hunk 5]
```diff
@@ -140,15 +141,97 @@ static ucs_status_t uct_ud_ep_free_by_timeout(uct_ud_ep_t *ep,
...
+
+    uct_ud_ep_window_purge(ep, UCS_ERR_ENDPOINT_TIMEOUT);
+
+    status = iface->super.ops->set_ep_failed(&iface->super, &ep->super.super,
+                                             UCS_ERR_ENDPOINT_TIMEOUT);
+    if (status != UCS_OK) {
+        ucs_fatal("UD endpoint %p: unhandled timeout error", ep);
+    }
+
+    return 0;
```
Comment (brminich) [inline src/uct/ib/ud/base/ud_ep.c:217]: maybe return 1 indicating that some work was done by this progress function?

File: test/gtest/uct/ib/test_ud.cc [hunk 6]
```diff
@@ -570,20 +568,27 @@ UCS_TEST_SKIP_COND_P(test_ud, ca_md,
 
     ep(m_e1)->tx.tx_hook = count_tx;
     do {
+        uct_ud_enter(iface(m_e1));
```
Comment (brminich) [inline test/gtest/uct/ib/test_ud.cc:571]: why need to protect it?

Comment (yosefe) [reply test/gtest/uct/ib/test_ud.cc:571]: in case ud async progress does re transmissions and changes tx_count and/or cwnd

Comment (brminich) [reply test/gtest/uct/ib/test_ud.cc:578]: afaiu, it should not affect test flow anyway
not that improtant comment though

Comment (yosefe) [reply test/gtest/uct/ib/test_ud.cc:578]: in theory, the async thread can do re-transmissions and reduce window size at the same time the main thread is reading tx_counf and cwnd,  on CPUs with weak mem ordering the main thread could see the "new" value of tx_count, but prev value of cwnd, so will fail the test because the window will shrink but nothing new will be sent

**Comment by yosefe** [comment]
/azp run
failure is #3897

**Comment by yosefe** [comment]
> /azp run

failure is #3897

**Comment by yosefe** [comment]
@brminich @dmitrygx your comments were applied + anther fix to handle tx_stop case, can you pls take a look?
