### PR TITLE
UCP/RNDV: Fix pipeline rndv protocol when tag recv_length > send_length

### LINKED ISSUE #4426: rndv send hangs for gpu buffers with ucx_rndv_scheme auto
After #4123 host to gpu send hangs if default rndv scheme is used. No freezes with UCX_RNDV_SCHEME=get_zcopy or UCX_RNDV_SCHEME=put_zcopy
@bureddy could you please check?

### PR DESCRIPTION
**Pull request by bureddy**
Fixes #4426

### CODE REVIEW

**Comment by yosefe** [comment]
@bureddy is it possible to add unit test?

**Comment by bureddy** [comment]
fixed https://github.com/openucx/ucx/issues/4426

**Comment by bureddy** [comment]
> @bureddy is it possible to add unit test?
> is pipelined protocol even tested today in gtest?

@yosefe currently cuda testing is not enabled in UCP gtest.  only with Jenkins mpi perfects.
we have some issues here. those should be fixed with https://github.com/openucx/ucx/pull/4418 and test pipelining here. but I think perfect do not cover the case where recv length != send length.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 22-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/1d08a54e3c4ec61789ef87c0bd21fe91a277ce46/_main) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/318a6a03d0475e1e93afdc43cde1e26d5c9c31ec/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/c1af66c2f70bded95c1a5fab62c1e232c29f902b/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/0564f65c80eefcea457addf54f2a12d0eeb4ded2/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/51a04afde39b15c51c1d91ada6e8c129703632a5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/fb055f0a581f3a144d90f21126e6122185a9c58c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/fd13dce688b00a4fe80290510368ab134f599a88/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/a1d1321e3615899b4001a578059b9e781757aca4/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/79ddfe92304913c9e5941ab608b020cc4508feea/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/ec5962576c93d09b63df2f458d73f45bbd00956a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/1114d4bd4b47e69f2af2672077526dc381d6fe1e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/828d4ebbc9a37baa2f7432112add771e3fbba988/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/66425c92fa4017ff638725eb43fd642436df1acf/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/cc1945f684790e1401c2c7267e77d98cf64a5b3d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/d914891df26051cae696c1e5d67a491c005b4bd4/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/b7b4fc3fb7702933b0cff12f0668467487ec610e/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/ec8ce4ba8fedc1760393325116fd3d08283d6f6b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/3d0952b6410046979053efa477e9720ec707053d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/c76f288c95cf15e0f9dcf4c0c087ee98caf98cd4/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/46a19e9548528dfcd3585953674a3173d8db0ec9/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/38dee2b5e9828266dc17a4f99a28aa9a1a77683e/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/ee10d0b5b7d6e01b9d0cf5d3770bdc3deab93d14/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/ad3e422a31aa8113164b32b3bf0f19cc0dd55a36/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/19a3e2a8c30cd9d8b6e178b9a19aafdc9d28e26d/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/454b7f64e0d0742171fb949e51e6a808/raw/78158d492152be4e6bec0a8e011aea02b3e5e42d/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
maven could not connect to central
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/1e628af6b341c224ccec1b73c1c21358bbed3b12/_main) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/0b3dadaf9c2f23bfc021f4240e2688201b9d1cf2/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/46fcc0f9c0d74017445e1b7e6e3ad1c6590ecb50/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/9d5bc47006249177213fc0c1fb97c8b83952cc58/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/5d6fe0776412cd942312800e4d2d7a047e0d29e5/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/45a8d5e75c57e39897c9851aa58a7e55c08d850b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/f93c910721974842b78244bd8999cc0acc9e2c9d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/9c95d53d38b73541ec70431aa01fb6a66ba5550c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/7fdfc1188a6135471337c48584778ab470c7a79c/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/5674cdaec7bc35851d4085f2944efe1641d4cf53/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/ee4882352aea21a39449254c4118210552768cdb/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/cdb2de903c335b3732cde923c87835caa153cdcb/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/f24526b7881e41930fc13780e64f1b7df979aaa2/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/f9b1d0cd5f0ffe0c594eef354486b4b77dd3e015/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/8177ac749c1708851f125008ba51df2afabc9b35/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/4ef710c93bbdfc376833ac917d3a0446c82669a5/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/1beafb763c28a3043786dfa2f771c33e110ec5f7/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/388564e2e5e9b4dce15bc723385f19d83c7914ac/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/6382f86e7d3ab1c44699056d4d11f36af22e1d13/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/58a663312b1b3344f5445d0bcb4db29833d93e97/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/ba1fb908b4877065970d15f5b4cdec175481e58e/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/b4f203d5eaded54511a0f1c7c00538dec2546b82/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/7a7da7cffc2b7d016a7cc003caf490f3c821eb7a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/8df0dc05738e171b775f612026f045ced0ad6186/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e029dfe50f25936b10c99e49c6fa5c80/raw/97ec94e0e2f4f197b0c8f8976b0b8ffec5eb3fd9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 24-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/3c4e73636fb28839d47bc848e470b09b4505898a/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/bb4085e1233d2a84db9686dae7b8761d5cf52629/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/20abf6e93242b4ac47572f54d1b247fc9cd664f6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/9b1251f485eb349ee1d74a16e686ba5e4430452a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/bd13cfb153683da194740324b1d078faf6f409fb/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/43c9d227714d24f7cabe431099ceee8e8704d916/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/4c07523bfaa79db6b0ee9aad938705d5b28759cb/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/ed1818221797cbe6016c78ad3f584be0447031c3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/9db7b654566c02e9fb769956453f4dab600ac5a9/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/f423a0a9865a21fa31dded6cadc5000a04c49ddb/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/deec01547f83e164e18be8e42ba0736ea86a89a0/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/329612ae12973993800a54bb1e07ccfd73cad66f/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/f96a9f37053de65ce77a6fba0c119845e142a8ca/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/38cb8307ec780ad5260e4dbbef190242a60f7a92/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/6f27b64a2e5e26744a64761ab721578bc9f34c8c/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/d3acb2c917aad5f6068f1d872da34dccf4bd3205/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/482934588b9f55a5aaaebe2f86dca937cbe1202c/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/bc4e26cd5ab81b586cdc7d3d1be5d40464e35545/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/8ef719c71cec10ce0a60cbcc55b1739d754370cc/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/3c9ca16dc044aa757cc75b37111b152c9c8506e1/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/bc9767386929a3077efb4416c9c2b3ebc220c645/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/5b9c7ad4ebba708ca3635bd08d66aed1ad1efff4/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/b3a620e9ce39f7bc3e59cd0720b2d1cdaecc2cfa/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/df6af83ef308dace0b25717e0b733b5b59847c6b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8c125cc7e8bc274e816a16f28be861db/raw/9a41ea6cf67d0c17f6d4d2b7c78a0465358dfe69/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/ucp/tag/rndv.c [hunk 1]
```diff
@@ -1015,7 +1015,7 @@ static ucs_status_t ucp_rndv_pipeline(ucp_request_t *sreq, ucp_rndv_rtr_hdr_t *r
         return UCS_ERR_UNSUPPORTED;
     }
 
-    rndv_size        = rndv_rtr_hdr->size;
+    rndv_size        = ucs_min(rndv_rtr_hdr->size, sreq->send.length);
```
Comment (evgeny-leksikov) [inline src/ucp/tag/rndv.c]: shouldn't `sreq->send.length` always be <= `rndv_rtr_hdr->size` due to receive buffer bust be >= send buffer? Otherwise it's truncate error, right?

Comment (bureddy) [reply src/ucp/tag/rndv.c]: in pipeline rndv case,  RTR request can be for a fraction of receive length,  which can be less than sreq->send.length

Comment (evgeny-leksikov) [reply src/ucp/tag/rndv.c]: i see, thanks for clarification!

**Comment by yosefe** [comment]
@bureddy now that jenkins fixes are merged and we have gpu-direct driver on the test nodes, can we tell if rndv pipelined protocol would run in gtest?

**Comment by bureddy** [comment]
@bureddy yes.
 pipeline protocol will be triggered if gpu-direct driver is not present.  in jenkins  GDR flag (UCX_IB_GPU_DIRECT_RDMA=n/y) toggled to makes it enable explicitly.

**Comment by yosefe** [comment]
so in this case, why are the tests passing without this fix?
i think we should add a gtest to test_ucp_mem_type.cc to reproduce this scenario with UCX_IB_GPU_DIRECT_RDMA=n, wdyt? is it enough to send large message when recv_length<send_length

**Comment by bureddy** [comment]
perftest runs both send and recv tag request with the same length and not triggered the issue.
will add a repro to test_ucp_mem_type.cc.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 13 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 21-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/80639ed7b80d16958889fea862db4fceec61967e/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/912a6e315b91d3626360a20d84cf3b28a972cc79/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/f293db21c662df52b45e123f3355449db8abe6fb/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/b5aa3ea8839e1c7ee0b6d00ae23bee097ef78aa1/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/46edbf5b11c7b4de17bd2adcf3fde32b9bd3b037/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/7e8198ef01c6c694613fd053f960de96b943aa12/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/3827addd2c9a544ba3175f796bce92d8de9493cd/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/32fd234e31e153a1c8e02cf7484b676b88da1edd/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/52e97038bb1abe8588dcfec447c2ea3acdc56c67/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/04e111b7cde9e094a99d3a82444a4faea0a9b29b/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/842b3b1da567f366fdeda42b78c3a87202da97c8/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/5337ea8b894f78160ea6fcd3af1c5ce6e4f9876e/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/8489fe0e1177d49fffca3b3f168216991531629b/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/45168661881d6bea0ac262bd6d2bd89cf5daae56/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/b6d03c139a358d8ea44c4f2b2f52520727ced219/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/2a41ab868182d2031483e158cf70ee12dfdd2d44/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/c8d8f02765f3f6edb79b9eefd857877585da5127/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/0de2c5de5e84c643b2e4a9668fe653fac1586f56/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/cf50e96c23cc2d3791fcd42d469d70a91d5df596/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/12940f7064b823cba5d216aa0e42f965bd2b23a1/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/8cf8536231e8f23e1bf79ab2fbb7db26ebbeb33e/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/c47036c5d84b6709d92c7c38d594bf07be9e6827/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/d6dc51672db1a6ffdef3a86a2a89c2462f1ba170/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/55885793b656aae13382c7acdee9ae3e2ce92374/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/420e83d1d11d3f3059a1f7e46325f6c1/raw/8cb58ce951b3b13152fd5f1b2c6c3cccfe239650/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by bureddy** [comment]
waiting for https://github.com/openucx/ucx/pull/4585 and https://github.com/openucx/ucx/pull/4579

File: src/ucp/tag/offload.c [hunk 2]
```diff
@@ -276,6 +276,10 @@ ucp_tag_offload_do_post(ucp_request_t *req)
             return status;
         }
 
+        if (!req->recv.state.dt.contig.md_map) {
```
Comment (brminich) [inline src/ucp/tag/offload.c]: Not needed. Per discussion in #4499 we have to fail `ucp_request_memory_reg` in case of memory mismatch to avoid such checks on every zcopy protocol.
Should be fixed by  #4499

File: src/ucp/tag/rndv.c [hunk 3]
```diff
@@ -181,7 +187,10 @@ ucs_status_t ucp_tag_send_start_rndv(ucp_request_t *sreq)
         return status;
     }
 
-    if (ucp_ep_is_tag_offload_enabled(ucp_ep_config(ep))) {
+    md_attr = ucp_ep_md_attr(ep, sreq->send.lane);
+
+    if (ucp_ep_is_tag_offload_enabled(ucp_ep_config(ep)) &&
+        md_attr->cap.reg_mem_types & UCS_BIT(sreq->send.mem_type)) {
```
Comment (brminich) [inline src/ucp/tag/rndv.c]: please move this check to `ucp_tag_offload_start_rndv`. When tag offload enabled we can't use regular protocols (otherwise messages can be matched in a wrong order by peer). Instead need to select `ucp_tag_offload_sw_rndv` inside `ucp_ep_is_tag_offload_enabled`

File: src/ucp/tag/rndv.c [hunk 4]
```diff
@@ -1209,6 +1218,7 @@ UCS_PROFILE_FUNC(ucs_status_t, ucp_rndv_rtr_handler,
         /* Do not deregister memory here, because am zcopy rndv may
          * need it registered (if am and tag is the same lane). */
         ucp_tag_offload_cancel_rndv(sreq);
+        sreq->flags &= ~UCP_REQUEST_FLAG_OFFLOADED;
```
Comment (brminich) [inline src/ucp/tag/rndv.c]: maybe move it to `ucp_tag_offload_cancel_rndv`?

File: test/gtest/ucp/test_ucp_tag_mem_type.cc [hunk 5]
```diff
@@ -0,0 +1,206 @@
...
+
+#include <iostream>
+
+
+class test_ucp_tag_mem_type: public test_ucp_tag {
+public:
+    enum {
+            VARIANT_DEFAULT     = UCS_BIT(0),
+            VARIANT_GDR_OFF     = UCS_BIT(1),
+            VARIANT_TAG_OFFLOAD = UCS_BIT(2),
```
Comment (brminich) [inline test/gtest/ucp/test_ucp_tag_mem_type.cc]: btw, gdr_off and tag_offload together are buggy:)
added fix and simple test for that in #4499 
maybe worth adding another variant combining them

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 13 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/a5d41aa07c7eab2e6fb48a22892fe0c8390dd2a5/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/4206dc45459efb5daea5cfcab24e08ad57a84470/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/7411c05fe4b2948e654bc98633bc76736c7fc6e0/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/029b9d9e08eeec40e54b125126a907b299bf4f70/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/0cd9f58d1477ca401b0a2e34482f87544b6c791b/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/7e457934306022e204683f3b73ef111a2ca0432c/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/f6605dada5656ff87971aa8b842986fe9090ac37/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/be2fa5178f3d09f148e04764830f0a4b2009c6a8/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/f1ae2bd4ac8c5b16af598dd5850fffb9e7dc3663/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/0b6c24ee3998766d8160bc657d6041020c4c62da/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/a9eddb61167265a183e14d8c2884e6b2375e548d/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/5838bb00c400febac38b201bbaed32b7478d7fb6/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/f5ceca5dbe90dd2c51d16673472e10d8cab5d787/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/fcceb1c44b6a842cb6aba27d209cf7a803b8e575/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/8b09691ba7810e57842b3c581656def37531ae98/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/cce421d28317b79ba64e9ae1a1130a8c5c70adff/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/ac460f4201cec20c50f3c91e1cdc25c901eb1fc7/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/e4555d0af307a1443c7488548dafb885f07f3047/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/bb06cb78ffcc25875fc5b2f1d87cc7e33e482fb9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/7d0698e10a8c7224590cb8c2a68f676263b0c950/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/0037881c24eaaae105f9aba55f3e1807419ba35d/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/99682beca5d9b4d5a0c37cd9e5181def9d61845e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/e27482a05ec03227e44e1fda6c4f6d5ca35aaeaa/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/9ac3b6b2a7b473b43cadcf3da99b884599ff4869/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d59d05d2132a482456771f36bd31aa16/raw/703f55613b91c8416d16c0e354fe4aea51555089/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/ucp/tag/rndv.c (hunk 4 above)
Comment (bureddy) [reply src/ucp/tag/rndv.c]: fixed

File: src/ucp/tag/rndv.c (hunk 3 above)
Comment (bureddy) [reply src/ucp/tag/rndv.c]: seems you already moved this in https://github.com/openucx/ucx/pull/4499 .  had fix assert in ucp_tag_offload_start_rndv.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 25 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/726046094b18a0ca1a54f373b2714eef26b36c0d/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/be7f1df31d20c4fb8b3146b8cfd1ce034313ff75/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/6e2c1b0aaf62a0ce6ca8d5057eb870679d8e3acd/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/11009b81f684dd305280ed7139019b56ff5946af/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/80717a9bf9686647877dface34e4f7cee7245719/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/33a7cf635b006c3bedb83797b4c2992f557cc848/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/a940f6c072391dc5f59ef85d1c17bd95462edb2f/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/f81b89bee9976f99d7755ff224e2df2f5d71e585/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/15623eaa2672b83a7b310a357401fd1d268c016d/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/815ddaeef4e05d7a92dac89b6fbe49e921bd9f98/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/6c7a0c82152e86fd126b1f643f5d27df32ba0166/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/d26236ccbfced441149559ea1d365c4114c2f30a/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/0af69e7fcf58c3170a656226150fdc0ddfd318b8/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/ea5c08d4a3fb0aa8a9b86fb30a2cbec02505e6ff/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/d537ab4351fcf528666f300da46c8cd42666c310/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/d4d804c9a11d6ff9cfcb978dad53813ea6743319/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/3487b32cf0b28b53913afb23c12efdbe88524a5b/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/26426029e9d8d43b50504765213299acb92aabff/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/442494b1bb26407c0c519066315b742163c1d150/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/1508dd264636c0fc6fec4ae667186927e42957a1/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/4aeaf71bf842dee79986e2916bb3751eb4852990/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/9db261a51ae03e64cf9d5c3670b478ade7f117c6/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/34c065c766eff111e66443c9fd245ac85ff044be/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/16f8249951ff16e82df8e9741883db9578686e95/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ebf39f5d9f4734c361df0b2eb474d591/raw/149821d163ae86dadcb86506e75fdb8a52db3b95/r-vmb-ppc-jenkins_W3) | :x: FAILURE

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/4e135086ffce7edc8fec19aabd259763a8d26b03/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/1a7ea00e791eaa880cae133a2c18514be6e0ffe6/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/ea4faa2f7c62220aaceb3ab50e2fd0fd9de8d315/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/736f553c19753aec494fafe5a6e09bb62396aeaa/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/1aee0839f4d04c87e898dd005851c269f2434dc8/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/92e3c00846c74b9e1a76c8d1207274f87ada8eca/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/143b03b3ef185d7d2d51b415f92b63496302108a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/cbc3fc6a315f401e784b54222bc4bcd2af46a577/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/a6a550c88eafbf656eabfb449b7126b7e95ceeec/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/469156519ed2550ef07059e80d4c62a1e7a2ce68/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/4f645f860165683e057e776c1dd904895c82b92f/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/735d6009e7e4ffc7dbe3f9dbcf3ae0e3f3752edf/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/8b28c3d12c60f8ff7aa9348ce94ca0780b84f258/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/b02eb09550a190ca1c1b8c450858bf2159549664/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/e9bdb724dd5c8234f15cff0bea54617799548c76/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/b8af1b94a039043877b21f8d2fa6f3598bdc339b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/8be4a4ef19994d943d5750229a1da78a34c411c8/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/54217fce899f7e3ba3965f3d63779e159ee0e68d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/c3a898c9ddf86b942e2ec96b36dc98928e403e5c/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/ed384d554e915f28d77851bc1b36798bca620832/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/9c08a89846d5e719df4f173ad9081a61ed7140e5/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/20363f35c62aef71af1c4ccc2095055967b617f2/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/7993c1486fb65f5d9f901e998b48a8b703b6ec33/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/f16cca20c96c0d4fe8da1e1faa5a2d83f2653ca1/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f28bf91a10974c622ae4e35359a33b42/raw/060a74f3a9e84bd4542dd1c7267e55d33763d3e4/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: test/gtest/ucp/test_ucp_tag_mem_type.cc [hunk 6]
```diff
@@ -0,0 +1,216 @@
...
+    }
+}
+
+UCS_TEST_P(test_ucp_tag_mem_type, xfer_mismatch_length)
+{
+    ucp_datatype_t type = ucp_dt_make_contig(1);
+    size_t length = ucs::rand() % ((ssize_t)pow(10.0, 7));
+
+    ucs::detail::message_stream ms("INFO");
+    ms <<"TEST: " << ucs_memory_type_names[m_send_mem_type] << " <-> "
```
Comment (dmitrygx) [inline test/gtest/ucp/test_ucp_tag_mem_type.cc]: pls add space between string and << operator

File: test/gtest/ucp/test_ucp_tag_mem_type.cc [hunk 7]
```diff
@@ -0,0 +1,216 @@
...
+                  << ucs_memory_type_names[m_recv_mem_type] << " length :" << length;
+
+    m_recv_mem_buf = new mem_buffer(length, m_recv_mem_type);
+    m_send_mem_buf = new mem_buffer(length, m_send_mem_type);
+
+    m_recv_mem_buf->pattern_fill(m_recv_mem_buf->ptr(), m_recv_mem_buf->size(),
+                                 1, m_recv_mem_type);
```
Comment (dmitrygx) [inline test/gtest/ucp/test_ucp_tag_mem_type.cc]:
```
m_recv_mem_buf->mem_type()
```
instead of
```
m_recv_mem_type
```
to align with `pattern_fill` below

File: test/gtest/ucp/test_ucp_tag_mem_type.cc (hunk 6 above)
Comment (dmitrygx) [inline test/gtest/ucp/test_ucp_tag_mem_type.cc]: better use `UCS_TEST_MESSAGE << ` instead

File: test/gtest/ucp/test_ucp_tag_mem_type.cc [hunk 8]
```diff
@@ -0,0 +1,216 @@
...
+    request_release(rreq);
+    return recvd;
+};
+
+UCS_TEST_P(test_ucp_tag_mem_type, basic)
+{
+    ucp_datatype_t type = ucp_dt_make_contig(1);
+
+    ucs::detail::message_stream ms("INFO");
+    ms <<"TEST: " << ucs_memory_type_names[m_send_mem_type] << " <-> "
```
Comment (dmitrygx) [inline test/gtest/ucp/test_ucp_tag_mem_type.cc]: better use `UCS_TEST_MESSAGE << ` instead

File: test/gtest/ucp/test_ucp_tag_mem_type.cc [hunk 9]
```diff
@@ -0,0 +1,216 @@
...
+                  << ucs_memory_type_names[m_recv_mem_type];
+
+    for (unsigned i = 1; i <= 7; ++i) {
+        size_t max = (long)pow(10.0, i);
+        size_t length = ucs::rand() % max + 1;
+
+        m_recv_mem_buf = new mem_buffer(length, m_recv_mem_type);
```
Comment (dmitrygx) [inline test/gtest/ucp/test_ucp_tag_mem_type.cc]: btw, what about do not allocate it dynamically? so, can just do (remove `m_recv_mem_buf` and `m_send_mem_buf` fields):
```
mem_buffer recv_mem_buf(length, m_recv_mem_type);
mem_buffer send_mem_buf(length, m_send_mem_type);
```

File: test/gtest/ucp/test_ucp_tag_mem_type.cc [hunk 10]
```diff
@@ -0,0 +1,216 @@
...
+UCS_TEST_P(test_ucp_tag_mem_type, xfer_mismatch_length)
+{
+    ucp_datatype_t type = ucp_dt_make_contig(1);
+    size_t length = ucs::rand() % ((ssize_t)pow(10.0, 7));
+
+    ucs::detail::message_stream ms("INFO");
+    ms <<"TEST: " << ucs_memory_type_names[m_send_mem_type] << " <-> "
+                  << ucs_memory_type_names[m_recv_mem_type] << " length :" << length;
+
+    m_recv_mem_buf = new mem_buffer(length, m_recv_mem_type);
```
Comment (dmitrygx) [inline test/gtest/ucp/test_ucp_tag_mem_type.cc]:
```
mem_buffer recv_mem_buf(length, m_recv_mem_type);
mem_buffer send_mem_buf(length, m_send_mem_type);
```
?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/6e9c645e2b55a81c955e824ebb65eeaebf827911/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/f5b3199afa233967e34eada13832673951a6b9a9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/0c0ac6f28c63c7231c714b38f9f092472c8e7756/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/2f08e74167706098aeb2532952ea973cf644810a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/d4c413891bb51477bf95b77870855860dd3c5abc/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/7e72049e11663eed57453cf938444c35ac70a1b8/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/99f5f3e1b825032b59c24cc457051e5c71e7ae2e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/02b0a049600dcc164abdf2a7cc766feb697e180d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/823bda37d0c862693623b5153310e751d22e48f4/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/8566430cb0eccb0d1f61ce6d60c0420f1649d3d4/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/3b687db175c6129ec14765ca6bad64f7fc986a40/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/e50a5a97f582c896f9519ccab612ed443657a77a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/bd11a3e31218a2c06cd552ce875a70431d860d11/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/bb80a9f637b6b4f23f646552f5db8e7785f56ce1/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/f6f5eab4e7fc68459a4f1b55f5b55dfe3be12beb/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/4ebac31c7fae7456d732a6f4c99c75bea84f44a0/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/afc35d17f78c5b47314f1ea4f65162c060f1ba7d/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/5a796e8712b7475a6a253b40cf2dc51ef3dda3bb/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/92e111e49d98869686f613f40d1b8586919dcfe4/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/78334c7e3cf77075abc308bf7a38555c6ee8ccd7/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/3f361399e7f72674cfff65d1cd118ed745cd8ab8/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/1bb3a8bbaba04c44ce4c27dbc475d26b456abb04/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/7245426c605d4034a8074a9b328889578f78c4bb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/f0e61d1252b226bb99619ceb25a66fd57a75d3b1/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8a43ec66430dca6b29e87527306901a0/raw/8be3ef1386a5ef88f7fd040f3b5c36b80ec653e6/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by bureddy** [comment]
@brminich plz review

**Comment by brminich** [comment]
bot:pipe:retest

File: src/ucp/tag/offload.c [hunk 11]
```diff
@@ -623,6 +625,8 @@ void ucp_tag_offload_cancel_rndv(ucp_request_t *req)
     if (status != UCS_OK) {
         ucs_error("Failed to cancel tag rndv op %s", ucs_status_string(status));
     }
+
+    req->flags &= ~UCP_REQUEST_FLAG_OFFLOADED;
```
[the remark this answers is not in the document]
Comment (bureddy) [reply src/ucp/tag/offload.c]: fixing a bug. in pipeline protocol, it will have multiple rtr ctrl messages on same sreq.  this will ensure we cancel the offload rndv only once.

File: src/ucp/core/ucp_worker.h [hunk 12]
```diff
@@ -154,7 +154,7 @@ enum {
     ({ \
         ucp_mem_desc_t *rdesc = ucs_mpool_get_inline((_mp)); \
         if (rdesc != NULL) { \
-            VALGRIND_MAKE_MEM_DEFINED(rdesc, sizeof(*rdesc)); \
+            VALGRIND_MAKE_MEM_DEFINED(rdesc, (_mp)->data->elem_size - sizeof(ucs_mpool_elem_t)); \
```
[the remark this answers is not in the document]
Comment (bureddy) [reply src/ucp/core/ucp_worker.h]: cuda pipelinine with tcp is complaining that stage buffer is pointed to uninitialized bytes.  this is because we are doing zcopy from CUDA memory to stage buffer and this is not recognized as a valid initialized buffer.

File: test/gtest/ucp/test_ucp_tag_mem_type.cc [hunk 13]
```diff
@@ -0,0 +1,211 @@
+/**
+* Copyright (C) Mellanox Technologies Ltd. 2001-2020.  ALL RIGHTS RESERVED.
```
[the remark this answers is not in the document]
Comment (bureddy) [reply test/gtest/ucp/test_ucp_tag_mem_type.cc]: fixed

File: test/gtest/ucp/test_ucp_tag_mem_type.cc [hunk 14]
```diff
@@ -0,0 +1,211 @@
...
+* Copyright (C) UT-Battelle, LLC. 2015. ALL RIGHTS RESERVED.
```
[the remark this answers is not in the document]
Comment (bureddy) [reply test/gtest/ucp/test_ucp_tag_mem_type.cc]: copied it from another file. not sure relevant or not. removed it.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/ba7a80e867922b99f472d6b154102c39e8a68f54/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/c27a3b553fc42d81b4fba2a7a244137ff6d45c51/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/80ccf00ececc70831ac8ff0862b64e5d8b6ee174/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/3f4a396fe6794bf9aa613c6bf57b32096c11c37c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/3e234cc9d1928990babf8eacec73f56737b7b806/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/2d96e4b806847d94be84203cee4186f6de210a18/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/596093a4b92fd41e73b256ef0b8c63c39c027a63/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/b84d403561ef2dad596df79d54f748b87ef4bb3d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/f37a9ea6aa030a8d16271a5272b695dc720a3b45/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/fa4c44e88b77d1c0bb652a2895951c22cc6d6999/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/b5b5dea10803386a8ca1be2cbba5b012ad6b254b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/32354caeb98b4a1ae6430dbdfe01d1f408a5480f/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/bf276355ab2f670d07dc47f44009c05c8f8ea54f/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/af71b64175f0ea2120d5113f8cf9c5058c3f60a2/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/d7f8dbbf519b1203ea2fadf4c872fd82d2d17776/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/9c9ac42645b7450879fcfa9cde700c130b39e5a2/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/ab7b8017d9ec6de71233728bc8fff4c439c16b66/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/f5895cb0583c263d49d9f744556e3d64125b8bd9/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/cf25f62af27d6bab983e79a14af17b2050be7d25/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/b0e457d24a272f3104621a60647dc640b7ac5070/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/ad17a1c1fac4a3939d93289b1ea4b78f17696f22/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/fd04bea7ffbeafa559491d784b3aab00a3e87e6c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/ccee4ad4a0c66cdc7b08c82cca37711be77c822a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/4c4d60fc9130fca79341b4c2b6edcf338ab4d6e7/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bf262b96164115fd28f2b5cb2de8926e/raw/3f853e098f114d5ae880fef2226a8cb1e0d64b40/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/ucp/core/ucp_worker.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (brminich) [reply src/ucp/core/ucp_worker.h]: how tcp is different? Why do we need stage buffer to be initialized?

[the remark this answers is not in the document]
Comment (bureddy) [reply src/ucp/core/ucp_worker.h]: It seems Valgrind checks if TCP send buffer is initialized or not. In this case, buffer is initialized/staged from CUDA using cudaMemCpy().
maybe this is not a problem in IB case because of RDMA

```
==44069== Syscall param sendmsg(msg.msg_iov[2]) points to uninitialised byte(s)
==44069==    at 0x78DCC6D: ??? (in /usr/lib64/libpthread-2.17.so)
==44069==    by 0x4EA0A28: ucs_socket_do_iov_nb (sock.c:388)
==44069==    by 0x4EA0C33: ucs_socket_sendv_nb (sock.c:444)
==44069==    by 0x51D00C3: uct_tcp_ep_am_sendv (tcp_ep.c:1086)
==44069==    by 0x51D1870: uct_tcp_ep_put_zcopy (tcp_ep.c:1379)
==44069==    by 0x568985E: uct_ep_put_zcopy (uct.h:2333)
==44069==    by 0x568985E: ucp_rndv_progress_rma_put_zcopy_inner (rndv.c:880)
==44069==  Address 0x3d7040c0 is 8 bytes inside a block of size 524,296 client-defined
==44069==    at 0x4E84817: ucs_mpool_get_inline (mpool.inl:34)
==44069==    by 0x4E853D3: ucs_mpool_get (mpool.c:165)
==44069==    by 0x4E857E3: ucs_mpool_get_grow (mpool.c:242)
==44069==    by 0x56818AB: ucs_mpool_get_inline (mpool.inl:23)
==44069==    by 0x568E196: ucp_rndv_pipeline (rndv.c:1105)
==44069==    by 0x568F958: ucp_rndv_rtr_handler_inner (rndv.c:1243)
==44069==    by 0x568F958: ucp_rndv_rtr_handler (rndv.c:1202)
```

[the remark this answers is not in the document]
Comment (brminich) [reply src/ucp/core/ucp_worker.h]: looks like, it needs to be fixed in TCP transport. 
@dmitrygx, can you please check?

[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/core/ucp_worker.h]: @brminich I investigated whether this valgrind issue is related to TCP or not. I added the` `printf()` for the first byte of the UCP's buffer in `uct_ep_put_zcopy()` and Valgrind complains that this memory read was unitialized. The buffer that's passed to UCT PUT Zcopy comes from UCP memory pool (this is a staging buffer - UCP does `cudaMemcpy()` from GPU buffer to this HOST buffer and then does UCT PUT Zcopy for this HOST buffer). Looks like, Valgirnd doesn't understand that we initialized this HOST buffer by the data from GPU buffer when doing `cudaMemcpy()`.
I see that @bureddy's test compare target buffer and initiator buffer - and they are equal, so it means that Valgrind is wrong here and we should suppress this. I think that the @bureddy's fix is a good way to do it. Wdyt?

[the remark this answers is not in the document]
Comment (brminich) [reply src/ucp/core/ucp_worker.h]: but it is not really `defined` when we get it from mpool. Maybe set it `defined` in rndv pipelining, or better when CudaMemcpy is done?

[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/core/ucp_worker.h]: > but it is not really `defined` when we get it from mpool.

yes

> Maybe set it `defined` in rndv pipelining, or better when CudaMemcpy is done?

makes sense to me
wdyt about adding `VALGRIND_MAKE_MEM_DEFINED` for HOST buffer in `ucp_mem_type_pack`?

[the remark this answers is not in the document]
Comment (brminich) [reply src/ucp/core/ucp_worker.h]: i think we'd need to define it somewhere in cuda_copy transport, like we do it for gets in IB.
@bureddy, @Akshay-Venkatesh , i'd try to add `VALGRIND_MAKE_MEM_DEFINED` macro in `uct_cuda_copy_progress_event_queue` or in `uct_cuda_copy_ep_get_zcopy`. For the former we would need to update `uct_cuda_copy_event_desc_t` to include data length

[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/core/ucp_worker.h]: > @bureddy, @Akshay-Venkatesh , i'd try to add `VALGRIND_MAKE_MEM_DEFINED` macro in `uct_cuda_copy_progress_event_queue` or in `uct_cuda_copy_ep_get_zcopy`. For the former we would need to update `uct_cuda_copy_event_desc_t` to include data length

@dmitrygx 👍

[the remark this answers is not in the document]
Comment (bureddy) [reply src/ucp/core/ucp_worker.h]: Fixed in uct_cuda_copy_ep_get_zcopy.

[the remark this answers is not in the document]
Comment (Akshay-Venkatesh) [reply src/ucp/core/ucp_worker.h]: Catching up a bit late. From what I understand, calling `VALGRIND_MAKE_MEM_DEFINED` on staging buffer about to passed to `cudaMemcpy` is equivalent to initializing it which avoids the issue of uninitialized bytes. Is that correct? If so, why do we do it per transfer attempt and not just do it for all the staging buffers at the time of cudaHostRegister or during memory pool init? Do we want to initialize per transfer?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/fdf0a12ab4e76126f9537ca7dba3371833b6dd7c/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/384620cd8652f4288636bc87d580fb39426286c4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/dd433f9f24ed43faac0689845425a2688601f0ef/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/d4a5d4a9d0a585c233ade336931aaa230ce24cbc/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/6b576f6cf72654e6ba3ac0c8b738b452915f0fd0/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/cf6f07139855b5281013587a95a7076386ff9b98/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/c702bf47d059e292692690810e54835917a8cab2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/b6891619448140887465cec54c6889a5a245cd49/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/d8dbbc57980e8c7ac660a944b5e38a4e0813bfa1/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/70ae10fd43acac97e767bd87a960bd3bb3e5ce49/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/fdd6b32de4ab34f86475d5158cb749a9445f672e/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/4ab911b0b8fbd29be4aaffcccedfca109d4f88cb/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/0a1411863b3c431e858f3c48ca999b8b5026cdd9/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/575aedb178eac2a5b1620511d6343b786aacca7b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/f9dcdbb6dcc0e1a8335c448dde7d3c940f96ed57/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/14a52519af7ddad1faba9a5a1fbc84c225576c43/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/553f87ff377fa64a4af865e450a8ad0ce0d1184c/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/0ee3bdcaf6cd8e12859d0bf9297576b063fd1a93/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/9a7565dfb8daf649732021554824387941872c57/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/78da0c0eeae634d50b931cb73f56d784124df797/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/a12f201069a9e6b0b5882790e06707ae9b3d02ab/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/4415d8a6d7a86e2e0422b28e54b210400cd43f06/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/c13c460b47c880c638b052f0c23ce7b1c1c4133c/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/6a4d79a07e45503923490506b4df2ba6a80195eb/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f3489aa06c92b1c5d46c69557dc999bc/raw/c9c30cafd8587f4f356aa9082606d2cc6684aa79/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/ucp/core/ucp_worker.h (hunk 12 above)
[the remark this answers is not in the document]
Comment (bureddy) [reply src/ucp/core/ucp_worker.h]: it is marking as defined for Valgrind.  I think it better here to just avoid suppressing real errors if making it in generic code

File: src/uct/cuda/cuda_copy/cuda_copy_ep.c [hunk 15]
```diff
@@ -93,6 +93,8 @@ UCS_PROFILE_FUNC(ucs_status_t, uct_cuda_copy_ep_get_zcopy,
 
     UCT_CUDA_COPY_CHECK_AND_CREATE_STREAM(iface->stream_d2h);
 
+    VALGRIND_MAKE_MEM_DEFINED(iov[0].buffer, iov[0].length);
```
Comment (brminich) [inline src/uct/cuda/cuda_copy/cuda_copy_ep.c]: i'd make memory defined if `status != error`

File: src/uct/cuda/cuda_copy/cuda_copy_ep.c [hunk 16]
```diff
@@ -93,12 +93,13 @@ UCS_PROFILE_FUNC(ucs_status_t, uct_cuda_copy_ep_get_zcopy,
 
     UCT_CUDA_COPY_CHECK_AND_CREATE_STREAM(iface->stream_d2h);
 
-    VALGRIND_MAKE_MEM_DEFINED(iov[0].buffer, iov[0].length);
-
     status = uct_cuda_copy_post_cuda_async_copy(tl_ep, iov[0].buffer, (void *)remote_addr,
                                                 iov[0].length, cudaMemcpyDeviceToHost,
                                                 iface->stream_d2h,
                                                 &iface->outstanding_d2h_cuda_event_q, comp);
+    if (status == UCS_INPROGRESS) {
```
Comment (brminich) [inline src/uct/cuda/cuda_copy/cuda_copy_ep.c]: maybe better `if (!UCS_STATUS_IS_ERR(status))?` (to not depend on `uct_cuda_copy_post_cuda_async_copy` behavior)

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 21-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/e8a8acd058ad99b98d68b7f0b3c9336af7d12710/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/6dae84986fb144bf369c7288acca1ea02a8f6a9b/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/c5994650f8fff90b101e29c168e294c2eb20fd38/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/21dff41c460a86ed86f0c68952d02fbbee9f2ea1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/1ce72d9368520089629a56c90cf017863e7187ac/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/c88f538142dc6328d2e3cd040eb21747971053c4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/1089ef2a79f5a0ddfdab763fa20b3871f03948da/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/c50e5918d5b63e6a8797e56da76e7edfa24d3eb2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/d9ff8ef7416827876c5a5ae11860b9560fa5c13b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/f47e413c43e3a4736f2655bd2f9d1e817cbf9784/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/d942b16ed187e9ed56822deb84d00ca02f346be6/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/98cd389d6c68be7883fbfb10777fa8297a71da04/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/37f506eba462c898b146d47495cb2936388172be/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/ab0199f0aba4b8b8fbb9335c95b22e2402438c33/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/deab16063d4dfc4a1607c02353fee68d970a9e71/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/dc0561e8fbbd98fa710a5de89007bb37164fa6d9/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/524833ac6855ee5fc4f3d089124d843bc921c690/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/baedb74349a7efa6fd06766ff599e2449a7fd1ed/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/45771bcbd66b34216aa89c8a26ba89518dbeac5d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/2a38b6f0a0435a14188736a60db8f6b5a7b899ef/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/481d0be8ec05cc4d2af16d526b884c6d21dfd4fc/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/2ec5f867a82b1db63195910c9e1a94c993986b9a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/574de6414f139f163c96632a65e836de5369c836/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/c87154a7ab04b26a99e0d50e196c7e497b1d4fff/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c21d28d78bb6388deedafac505c89121/raw/dfeabc5c0b341664669efb51720ee68d3b076991/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 22-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/2e23724c9125fc5df9f7877e70c51b49d8f01dcd/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/45252b6a42adae7e274e3e78397313d5cd9f1528/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/ecbc6ea7be70baaa2d9a02b85e1ef9b05bd85a6c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/56449d9047d1c54ee2e9883ba23c39f945d3d60c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/611513418a61c9c0e305675c7dad764a9605ed04/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/adca9b953a27b1c8076a11f40f496359206b3ac8/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/7a49876915c89b74c0cff73f2d394afa8a87b28c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/8e57faeea49e8d15f432df2f0d43cddc359cc943/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/69b396f6491f3323427ed4bc9eb47f6c58555536/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/a7873af34ee3e64d965ecc799c0bd1ffb9727487/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/a35d7c2c0a09bf63683cda99231dfdec1e599f49/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/2fd79efe6a9c867665e689fd65b9392ec1a57fbc/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/45fbe387d25e6d741fa0c4803c4004feb1291e3e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/542c19bc05a9474923e1f196701c9f60d3899a16/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/17a58bd7f33563476ed97a07d39fe5985cb52253/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/790311a377414ae0167f0f88c6529e71465f7994/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/39c320e284499832cdf4a29b469eac3a0e999656/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/4f12774f8f33fbb20ee112a96b9f3332f61bb033/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/507f85a76646faa8b32444070d22e871e8e0e60e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/cf6147dc6bf11043ba2242d8c451212286acbde2/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/51c615df59a286fbb09180d425e706f76c48f836/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/7f369b873ea9a8c85be3816b8b87700e3a650c54/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/7472efb75a4d0315055c424711ee333516fc21f2/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/1d8ec150b00442cdbe3c17f9a8ba4653f454cda3/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/925d9e53671a6aa1a328cda5dedef14d/raw/c2d99deb0b2f456559d58dcfa5967b8a9b69b98a/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: test/gtest/ucp/ucp_test.h [hunk 17]
```diff
@@ -266,4 +266,22 @@ std::ostream& operator<<(std::ostream& os, const ucp_test_param& test_param);
...
     UCP_INSTANTIATE_TEST_CASE_TLS(_test_case, tcp,    "tcp")
 
+/**
+ * Instantiate the parameterized test case for all transport combinations
+ * with CUDA memory awareness
+ *
+ * @param _test_case  Test case class, derived from ucp_test.
+ */
+#define UCP_INSTANTIATE_TEST_CASE_CUDA_AWARE(_test_case) \
+    UCP_INSTANTIATE_TEST_CASE_TLS(_test_case, dcx,        "dc_x,cuda_copy") \
```
Comment (yosefe) [inline test/gtest/ucp/ucp_test.h]: can we do "dc_x,cuda" for example for all cases? (cuda is alias for all cuda transports)

**Comment by yosefe** [comment]
unrelated failure on VM vmb-fedora16-x86-64:
```
[2020-01-14T21:18:02.822Z] ++ /usr/libexec/pk-command-not-found doxygen --version
[2020-01-14T21:18:03.078Z] bash: doxygen: command not found...
```
bot:pipe:retest

File: test/gtest/ucp/ucp_test.h (hunk 17 above)
Comment (dmitrygx) [reply test/gtest/ucp/ucp_test.h]: @yosefe I think it will cause using `cuda_ipc` for data transfers where we want to use `dc`

Comment (yosefe) [reply test/gtest/ucp/ucp_test.h]: good point

Comment (dmitrygx) [reply test/gtest/ucp/ucp_test.h]: > good point

@yosefe what do you think about moving my PR changes #4641 to the @bureddy's PR in order to test it on his usage of this macro?

Comment (yosefe) [reply test/gtest/ucp/ucp_test.h]: yes, @bureddy can you pls rebase?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 03-Feb-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/320e081eedb1a8f855227f4b9cabc994e18a16e5/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/31f40d950c803beacce303f36cd89fd0d23281f9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/458c5464b15ccaa26ac345e9a99dbdf6ba0323ca/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/6b737aa2bcafb8b47e251a0beb5f1398944db8b3/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/a99318f4409b0a055927ec26d4cf59b59e581048/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/7dfe95d92b8f410c823a27f312cfbc8dad127ab4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/975b3d51e6b1f49046029f99194e49662fd38105/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/348e5f15938c0d3d4b1b2af9d10ee70955544d37/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/15fe85f3673241ad6477e1453ce7cd8718dc44a6/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/207aa3818a7a6862d20046437f46cae43ecc1462/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/c1871c51d4132fcfdc1764333432dec304286c9b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/76a6fd7fbc9a7b8e7eb456a7d16ecd11a3952205/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/9f97831b3647317bf341b888340427f242fc88e1/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/0cee7cc4facc60d79d953d64b41870a86698e069/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/8998ed43357263d23e13b8628c1e9dbd014424eb/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/114e8bf986016933949d8b81e952a16de2d7833e/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/d7025672659d43592567ca1af421be0a9ac71634/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/1d30859966de58163bb3a47513eee5c8e7e32488/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/95cb86b66834dff445b9a8639d4668e0f535d181/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/974687a873b93f6bfb2d5b6977b85972260d9fa2/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/5d94756e8b45fc28cae2b0a79a05647d606bb241/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/c6178f18f0ea89c1431a8dc120f681a2dc2680ea/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/39404f15b6e2f88eea1ebd34f0b0b071e258b2e5/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/c473f192f26f1f18c60b51be510c3c3856470e8e/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8350450e295ebf1cb6342a04f3347457/raw/5c6f5b6c28b713dd0f6df9c9c9716644d7d2cf1b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
