### PR TITLE
UCP/WIREUP/GTEST: Stop processing client/server's connect if endpoint disconnected

### LINKED ISSUE #6966: tcp/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/6 fails on sputnik3
```
[ RUN      ] tcp/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/6 <tcp/stream,not_all_devs>
[     INFO ] Testing 10.224.36.172:0
[     INFO ] server listening on 10.224.36.172:46229
[sputnik3:2467 :0:2467]      wireup.c:1196 Assertion `new_key->wireup_msg_lane == ((ucp_lane_index_t)-1)' failed

/scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../src/ucp/wireup/wireup.c: [ ucp_wireup_check_config_intersect() ]
      ...
     1193     ucs_assert(old_key->wireup_msg_lane != UCP_NULL_LANE);
     1194     /* wireup lane hasn't been selected by the new configuration: only this
     1195      * function should select it */
==>  1196     ucs_assert(new_key->wireup_msg_lane == UCP_NULL_LANE);
     1197 
     1198     /* set the correct WIREUP MSG lane in case of CM */
     1199     reuse_lane = reuse_lane_map[old_key->wireup_msg_lane];

==== backtrace (tid:   2467) ====
 0 0x00000000000c47b9 ucp_wireup_check_config_intersect()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../src/ucp/wireup/wireup.c:1196
 1 0x00000000000ca646 ucp_cm_client_connect_progress()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../src/ucp/wireup/wireup_cm.c:588
 2 0x0000000000054a2b ucs_callbackq_slow_proxy()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../src/ucs/datastruct/callbackq.c:402
 3 0x000000000004a4ba ucs_callbackq_dispatch()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../src/ucs/datastruct/callbackq.h:211
 4 0x000000000004a4ba uct_worker_progress()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../src/uct/api/uct.h:2592
 5 0x000000000004a4ba ucp_worker_progress()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../src/ucp/core/ucp_worker.c:2636
 6 0x000000000093e50c ucp_test_base::entity::progress()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/ucp/ucp_test.cc:888
 7 0x000000000093e5c7 ucp_test::progress()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/ucp/ucp_test.cc:155
 8 0x000000000091cf41 test_ucp_sockaddr::one_sided_disconnect()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:558
 9 0x000000000090889c test_ucp_sockaddr_destroy_ep_on_err_onesided_client_sforce_Test::test_body()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1301
10 0x00000000005fb5d6 ucs::test_base::run()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/test.cc:365
11 0x00000000005fb5d6 ucs::test_base::TestBodyProxy()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/test.cc:391
12 0x00000000005dc9c9 HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/gtest-all.cc:3562
13 0x00000000005d0c0d testing::Test::Run()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/gtest-all.cc:3635
14 0x00000000005d0ce5 testing::TestInfo::Run()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/gtest-all.cc:3812
15 0x00000000005d0e4f testing::TestCase::Run()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/gtest-all.cc:3930
16 0x00000000005d55fd testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/gtest-all.cc:5808
17 0x00000000005d58e0 testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/gtest-all.cc:5725
18 0x0000000000565c8d RUN_ALL_TESTS()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/gtest.h:20059
19 0x0000000000565c8d main()  /scrap/azure/agent-06/AZP_WORKSPACE/3/s/contrib/../test/gtest/common/main.cc:109
20 0x00000000000223d5 __libc_start_main()  ???:0
21 0x00000000005baf6d _start()  ???:0
=================================
```
https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=19570&view=logs&j=7c8bfeef-839e-542c-7583-d350f4a310c0&t=c6310655-4648-579a-7a4e-2ab23c9d123f

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Stop processing client/server's connect if endpoint disconnected.

## Why ?

Fixes #6966 
If users does `ucp_ep_close_nbx()` while UCP endpoint is still connecting (e.g. `ucp_cm_client_connect_progress()` was scheduled on the callbackq, but not completed yet), we should stop all CM-related callbacks to make sure they won't be called after CM was already discontented.

## How ?

1. Check flag `LOCAL_CONNECTED` on `client_connect_progress`/`server_conn_notify_progress` as assertion.
2. Remove `client_connect_progress`/`server_conn_notify_progress` from callbackq if they are set.
3. Reproduce the problem in gtests by setting EP failed after cleint/server connect progress function added to callbackq.
4. In `ucp_ep_disconnected()`, if the EP is still locally conencted by CM, need to disconnect from a peer.

### CODE REVIEW

File: src/ucp/wireup/wireup_cm.c [hunk 1]
```diff
@@ -1345,6 +1345,10 @@ void ucp_ep_cm_disconnect_cm_lane(ucp_ep_h ucp_ep)
     ucp_ep_update_flags(ucp_ep, UCP_EP_FLAG_DISCONNECTED_CM_LANE,
                         UCP_EP_FLAG_LOCAL_CONNECTED);
 
+    /* Remove all CM-related callbacks from the callbackq to make sure they
+     * won't be invoked */
+    ucp_ep_cm_slow_cbq_cleanup(ucp_ep);
```
Comment (yosefe) [inline src/ucp/wireup/wireup_cm.c:1350]: 1. should we do it in ucp_ep_remove_progress_callbacks?
2. does it fix a test failure?

Comment (dmitrygx) [reply src/ucp/wireup/wireup_cm.c:1350]: `ucp_ep_remove_progress_callbacks()` - it is called when destroying EP.
but disconnect CM lane can be done even if EP is not going to be destroyed right now - e.g. handle failure.
`ucp_ep_cm_slow_cbq_cleanup()` is called also when destroying EP

Comment (dmitrygx) [reply src/ucp/wireup/wireup_cm.c:1350]: > does it fix a test failure?

yes, I though the problem in CI, but can't find the backtrace

**Comment by dmitrygx** [comment]
bot:pipe:retest

File: src/ucp/wireup/wireup_cm.c [hunk 2]
```diff
@@ -1345,7 +1365,14 @@ void ucp_ep_cm_disconnect_cm_lane(ucp_ep_h ucp_ep)
     ucp_ep_update_flags(ucp_ep, UCP_EP_FLAG_DISCONNECTED_CM_LANE,
                         UCP_EP_FLAG_LOCAL_CONNECTED);
 
-    /* this will invoke @ref ucp_cm_disconnect_cb on remote side */
+    /* Remove the client's connect_progress or the server's connect notify
+     * callbacks from the callbackq to make sure it won't be invoked after
+     * CM lane has already been disconnected */
+    ucs_callbackq_remove_if(&ucp_ep->worker->uct->progress_q,
+                            ucp_cm_connect_progress_remove_filter,
+                            ucp_ep);
```
Comment (yosefe) [inline src/ucp/wireup/wireup_cm.c:1373]: maybe we can check LOCAL_CONNECTED flag in these callbacks instead of removing them?

File: src/ucp/wireup/wireup_cm.c [hunk 3]
```diff
@@ -1374,23 +1401,14 @@ ucp_request_t* ucp_ep_cm_close_request_get(ucp_ep_h ep, const ucp_request_param_
...
-        client_connect_arg = elem->arg;
-        if (client_connect_arg->ucp_ep == arg) {
-            ucp_cm_client_connect_prog_arg_free(client_connect_arg);
-            return 1;
-        } else {
-            return 0;
-        }
-    } else if ((elem->cb == ucp_ep_cm_disconnect_progress)      ||
-               (elem->cb == ucp_cm_server_conn_notify_progress) ||
+    if (ucp_cm_connect_progress_remove_filter(elem, arg)) {
```
Comment (yosefe) [inline src/ucp/wireup/wireup_cm.c:1404]: why do we also need to remove callbacks here? isn't it enough to remove them in ucp_ep_cm_disconnect_cm_lane?

File: src/ucp/wireup/wireup_cm.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup_cm.c]: nice catch, done

File: src/ucp/wireup/wireup_cm.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup_cm.c]: no need anymore

**Comment by dmitrygx** [comment]
@yosefe the problem was reproduced in gtests, fixed as you suggested (i.e. checking `LOCAL_CONNECTED` flag absence in cleint/server's connect_progress functions)

File: test/gtest/ucp/test_ucp_sockaddr.cc [hunk 4]
```diff
@@ -1010,7 +957,87 @@ UCS_TEST_SKIP_COND_P(test_ucp_sockaddr, listener_invalid_params,
...
+    static void
+    get_test_variants(std::vector<ucp_test_variant>& variants,
+                      uint64_t features = UCP_FEATURE_TAG) {
+        /* It is enough to check TAG-only, since we are interested in WIREUP
+         * testing only */
+        get_test_variants_cm_mode(variants, features, CONN_REQ_TAG, "tag");
+    }
+
+protected:
+    static void cmp_cfg_lanes(ucp_ep_config_key_t *key1, ucp_lane_index_t lane1,
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_sockaddr.cc:974]: where is it used?

File: test/gtest/ucp/test_ucp_sockaddr.cc [hunk 5]
```diff
@@ -1010,7 +957,87 @@ UCS_TEST_SKIP_COND_P(test_ucp_sockaddr, listener_invalid_params,
...
+                 lane_idx < ucp_ep_num_lanes(e.ep()); ++lane_idx) {
+                uct_ep_h uct_ep = e.ep()->uct_eps[lane_idx];
+
+                uct_ep->iface->ops.ep_am_bcopy =
+                        reinterpret_cast<uct_ep_am_bcopy_func_t>(
+                                ucs_empty_function_return_bc_ep_timeout);
+            }
+        }
+
+        while (!(e.ep()->flags & wait_ep_flags)) {
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_sockaddr.cc:1012]: 1. ucs_test_all_flags
2. should use ASYNC_BLOCK?

File: src/ucp/wireup/wireup_cm.c [hunk 6]
```diff
@@ -572,6 +572,15 @@ static unsigned ucp_cm_client_connect_progress(void *arg)
               ucp_ep->flags, ucp_ep->cfg_index);
     ucs_log_indent(1);
 
+    if (!(ucp_ep->flags & UCP_EP_FLAG_LOCAL_CONNECTED)) {
+        /* If LOCAL_CONNECTED flag was removed from the endpoint, it means that
+         * the endpoint failed and CM was disconnected from a peer. So, no need
+         * for futher actions */
+        ucs_assert(ucp_ep->flags & UCP_EP_FLAG_FAILED);
+        status = UCS_OK;
+        goto out;
```
Comment (yosefe) [inline src/ucp/wireup/wireup_cm.c:581]: sorry, but looking at this again, maybe better to
1. remove notify/client_connect progress callbacks before calling cm_disconnect (**instead** of during ep destroy)
2. assume that CM will also not generate async events after disconnect is called
2. in here, assert that LOCAL_CONNECTED flag is set
WDYT?

Comment (dmitrygx) [reply src/ucp/wireup/wireup_cm.c:581]: done

File: test/gtest/ucp/test_ucp_sockaddr.cc (hunk 5 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_sockaddr.cc:1012]: nice catch - fixed

**Comment by dmitrygx** [comment]
@yosefe could you review pls?
gpu timeout was unrelated.

File: src/ucp/core/ucp_ep.c [hunk 7]
```diff
@@ -1044,6 +1044,12 @@ void ucp_ep_disconnected(ucp_ep_h ep, int force)
 
     UCP_WORKER_THREAD_CS_CHECK_IS_BLOCKED(worker);
 
+    if (ucp_ep_is_cm_local_connected(ep)) {
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:1047]: maybe move this if inside ucp_ep_cm_disconnect_cm_lane() ? 
and other places which call ucp_ep_cm_disconnect_cm_lane an also remove this if
maybe even rename it to `ucp_ep_cm_disconnect()`

File: src/ucp/wireup/wireup_cm.c [hunk 8]
```diff
@@ -1387,23 +1419,12 @@ ucp_request_t* ucp_ep_cm_close_request_get(ucp_ep_h ep, const ucp_request_param_
...
-        if (client_connect_arg->ucp_ep == arg) {
-            ucp_cm_client_connect_prog_arg_free(client_connect_arg);
-            return 1;
-        } else {
-            return 0;
-        }
-    } else if ((elem->cb == ucp_ep_cm_disconnect_progress)      ||
-               (elem->cb == ucp_cm_server_conn_notify_progress) ||
-               (elem->cb == ucp_cm_client_uct_connect_progress)) {
+    if ((elem->cb == ucp_ep_cm_disconnect_progress) ||
```
Comment (yosefe) [inline src/ucp/wireup/wireup_cm.c:1422]: maybe
return (cb==disconnect||cb==connect) && (elem->arg == arg)

File: test/gtest/ucp/test_ucp_sockaddr.cc [hunk 9]
```diff
@@ -1010,7 +957,103 @@ UCS_TEST_SKIP_COND_P(test_ucp_sockaddr, listener_invalid_params,
...
+        }
+
+        if (fail_wireup_type == FAIL_WIREUP_MSG_SEND) {
+            /* Emulate failure of WIREUP MSG sending by setting the AM Bcopy
+             * function which always return EP_TIMEOUT error */
+            UCS_ASYNC_BLOCK(&e.worker()->async);
+            for (ucp_lane_index_t lane_idx = 0;
+                 lane_idx < ucp_ep_num_lanes(e.ep()); ++lane_idx) {
+                uct_ep_h uct_ep = e.ep()->uct_eps[lane_idx];
+
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_sockaddr.cc:1016]: minor: can remove space line

File: test/gtest/ucp/test_ucp_sockaddr.cc [hunk 10]
```diff
@@ -1010,7 +957,103 @@ UCS_TEST_SKIP_COND_P(test_ucp_sockaddr, listener_invalid_params,
...
+        if (fail_wireup_type == FAIL_WIREUP_MSG_ADDR_PACK) {
+            /* Emulate failure of preparation of WIREUP MSG sending by setting
+             * the device address getter to the function that always returns
+             * error */
+            UCS_ASYNC_BLOCK(&e.worker()->async);
+            for (ucp_lane_index_t lane_idx = 0;
+                 lane_idx < ucp_ep_num_lanes(e.ep()); ++lane_idx) {
+                uct_ep_h uct_ep = e.ep()->uct_eps[lane_idx];
+
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_sockaddr.cc:1036]: minor: can remove space line

File: src/ucp/core/ucp_ep.c (hunk 7 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c:1047]: @yosefe but we still need the check for CM lane in
https://github.com/openucx/ucx/blob/bfca2be172b3a9903243eb1c71943f517d90a3f8/src/ucp/core/ucp_ep.c#L1134
https://github.com/openucx/ucx/blob/bfca2be172b3a9903243eb1c71943f517d90a3f8/src/ucp/core/ucp_ep.c#L1220

File: src/ucp/wireup/wireup_cm.c [hunk 11]
```diff
@@ -1387,23 +1419,12 @@ ucp_request_t* ucp_ep_cm_close_request_get(ucp_ep_h ep, const ucp_request_param_
...
+        (elem->cb == ucp_cm_client_uct_connect_progress)) {
```
Comment (yosefe) [inline src/ucp/wireup/wireup_cm.c:1423]: should also be part of ucp_cm_connect_progress_remove_filter, and rename ucp_cm_cbs_remove_filter to ucp_cm_disconnect_remove_filter

File: src/ucp/core/ucp_ep.c [hunk 12]
```diff
@@ -1209,6 +1215,10 @@ ucs_status_ptr_t ucp_ep_close_nbx(ucp_ep_h ep, const ucp_request_param_t *param)
     ucp_ep_update_flags(ep, UCP_EP_FLAG_CLOSED, 0);
 
     if (ucp_request_param_flags(param) & UCP_EP_CLOSE_FLAG_FORCE) {
+        if (ucp_ep_is_cm_local_connected(ep)) {
+            ucp_ep_cm_disconnect_cm_lane(ep);
+        }
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:1220]: can remove

Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: done

File: src/ucp/wireup/wireup_cm.c (hunk 8 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup_cm.c]: done

File: src/ucp/wireup/wireup_cm.c (hunk 11 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup_cm.c]: done

File: test/gtest/ucp/test_ucp_sockaddr.cc (hunk 9 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_sockaddr.cc]: done

File: test/gtest/ucp/test_ucp_sockaddr.cc (hunk 10 above)
Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_sockaddr.cc]: done

File: src/ucp/core/ucp_ep.c (hunk 7 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: decided not to do it

File: src/ucp/wireup/wireup_cm.c [hunk 13]
```diff
@@ -1385,29 +1418,22 @@ ucp_request_t* ucp_ep_cm_close_request_get(ucp_ep_h ep, const ucp_request_param_
     return request;
 }
 
-static int ucp_cm_cbs_remove_filter(const ucs_callbackq_elem_t *elem, void *arg)
+static int
+ucp_cm_disconnect_progress_remove_filter(const ucs_callbackq_elem_t *elem,
```
Comment (yosefe) [inline src/ucp/wireup/wireup_cm.c:1422]: why need this function?

Comment (dmitrygx) [reply src/ucp/wireup/wireup_cm.c]: removed

**Comment by dmitrygx** [comment]
@yosefe is this PR ok now?

**Review by yosefe — APPROVED** [review]
