### PR TITLE
UCP/TAG: Fix ucp_request_cancel for matched reqs

### LINKED ISSUE #4490: Canceling a request fails: tag_match.c:79   expected request not found
I am having trouble canceling submitted non-blocking tag send/recv requests with UCX 1.6.1 on our EDR platform. I start two ranks on different compute nodes. The attached test routine does the following:

- allocate 2 large buffers (10mb) on each rank
- submit non-blocking send / recv of the buffers to/from peer
- submit non-blocking send / recv of  a small (1b) messages to/from peer
- wait for the small messages to complete and verify that the large messages are still in-progress
- cancel the large `recv` requests

I run the code with a single thread per rank. UCX aborts with the following error:
```
small arrived
small arrived
large recv status: 1 1 (UCS_OK 0 UCS_INPROGRESS 1)
large recv status: 1 1 (UCS_OK 0 UCS_INPROGRESS 1)
[c3-4:40218:0:40218]   tag_match.c:79   Bug: expected request not found
==== backtrace (tid: 194528) ====
 0 0x000000000001e250 ucs_fatal_error_message()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucs/debug/assert.c:36
 1 0x000000000001e3b6 ucs_fatal_error_format()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucs/debug/assert.c:52
 2 0x000000000003b51e ucp_tag_exp_remove()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucp/tag/tag_match.c:79
 3 0x000000000003b51e ucp_tag_exp_delete()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucp/tag/tag_match.inl:98
 4 0x000000000003b51e ucp_tag_exp_remove()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucp/tag/tag_match.c:74
 5 0x0000000000018fdb ucp_request_cancel()  /cluster/projects/nn9999k/marcink/src/ucx-1.6.1/src/ucp/core/ucp_request.c:111
 6 0x00000000004035e8 main._omp_fn.0()  ghex_p2p_bi_cb_avail_mt.cpp:0
 7 0x000000000000df3f GOMP_parallel()  /cluster/work/users/vegarde/build/GCCcore/8.3.0/system-system/gcc-8.3.0/stage3_obj/x86_64-pc-linux-gnu/libgomp/../../../libgomp/parallel.c:168
 8 0x0000000000402175 main()  ???:0
 9 0x0000000000022495 __libc_start_main()  ???:0
10 0x000000000040230f _start()  ???:0
```

It seems that calling `ucp_request_cancel` on an ongoing `recv` request after another request submitted later has already arrived results in the above error. Am I doing something wrong, or is this a bug?

I'd appreciate any help.. Thanks!

As side question, in the test code I execute `ucp_worker_fence` between the large and small communication phases, but it seems that the has no effect on the tag send/recv requests. I am guessing that, as with`ucp_worker_flush_nb`, it only affects the the AMO and RMA comm? Just making sure, because it is not spelled out in the documentation.

Here is the code:

```
void test(){

    ucp_ep_h ep;
    int peer = (m_rank+1)%2;
    ucs_status_ptr_t rrequests[2];
    ucs_status_ptr_t srequests[2];
    ucs_status_t     status1, status2;
    unsigned char   *sbuffer, *rbuffer;
    unsigned char    sbuffer2[128], rbuffer2[128];

    int bsize = 10000000;
    sbuffer = (unsigned char*)malloc(bsize); memset(sbuffer, 0xf, bsize);
    rbuffer = (unsigned char*)malloc(bsize); memset(rbuffer, 0x1, bsize);

    ep = rank_to_ep(peer);

    /* submit large messages */
    rrequests[0] = ucp_tag_recv_nb(ucp_worker, rbuffer, bsize, ucp_dt_make_contig(1),
				   42, 0xfffffffffffffffful, ucx::empty_recv_cb);

    srequests[0] = ucp_tag_send_nb(ep, sbuffer, bsize, ucp_dt_make_contig(1),
				   42, ucx::empty_send_cb);

    /* should this order the two comm phases? */
    ucp_worker_fence(ucp_worker);

    /* submit small messages */
    rrequests[1] = ucp_tag_recv_nb(ucp_worker, rbuffer2, 1, ucp_dt_make_contig(1),
				   420, 0xfffffffffffffffful, ucx::empty_recv_cb);

    srequests[1] = ucp_tag_send_nb(ep, sbuffer2, 1, ucp_dt_make_contig(1),
				   420, ucx::empty_send_cb);

    /* wait for small messages to arrive */
    while(1){
	ucp_worker_progress(ucp_worker);
	if(UCS_OK != (uintptr_t)srequests[1])
	    status1 = ucp_request_check_status(srequests[1]);
	else
	    status1 = UCS_OK;
	status2 = ucp_request_check_status(rrequests[1]);
	if(UCS_OK == status1 && UCS_OK == status2) break;
    }
    fprintf(stderr, "small arrived\n");

    /* verify that the large messages haven't arrived yet */
    if(UCS_OK != (uintptr_t)srequests[0])
	status1 = ucp_request_check_status(srequests[0]);
    else
	status1 = UCS_OK;
    status2 = ucp_request_check_status(rrequests[0]);
    fprintf(stderr, "large recv status: %d %d (UCS_OK %d UCS_INPROGRESS %d)\n", status1, status2, UCS_OK, UCS_INPROGRESS);

    /* assertion failed */
    ucp_request_cancel(ucp_worker, rrequests[0]);
}
```

### PR DESCRIPTION
**Pull request by brminich**
## What
Fix `ucp_request_cancel` for already matched requests. In this case request should be completed OK, not canceled.  

## Why ?
Fixes #4490

### CODE REVIEW

File: src/ucp/core/ucp_request.c [hunk 1]
```diff
@@ -112,9 +113,9 @@ UCS_PROFILE_FUNC_VOID(ucp_request_cancel, (worker, request),
     if (req->flags & UCP_REQUEST_FLAG_EXPECTED) {
         UCP_WORKER_THREAD_CS_ENTER_CONDITIONAL(worker);
 
-        ucp_tag_exp_remove(&worker->tm, req);
+        removed = ucp_tag_exp_remove(&worker->tm, req);
         /* If tag posted to the transport need to wait its completion */
-        if (!(req->flags & UCP_REQUEST_FLAG_OFFLOADED)) {
+        if (removed && !(req->flags & UCP_REQUEST_FLAG_OFFLOADED)) {
```
Comment (dmitrygx) [inline src/ucp/core/ucp_request.c]: can remove `removed` variable and do:
```
if (ucp_tag_exp_remove(&worker->tm, req) &&
    !(req->flags & UCP_REQUEST_FLAG_OFFLOADED)) {
```
but it's probably bad for readability, wdyt?

File: test/gtest/ucp/test_ucp_tag_cancel.cc [hunk 2]
```diff
@@ -32,4 +44,42 @@ UCS_TEST_P(test_ucp_tag_cancel, cancel_exp) {
...
+    wait(rreq2);
+    EXPECT_EQ(UCS_OK, rreq2->status);
+
+    if (!rreq1->completed) {
+        ucp_request_cancel(receiver().worker(), rreq1);
+    } else {
+        UCS_TEST_MESSAGE << "nothing to cancel";
+    }
+
+    wait(rreq1);
```
Comment (dmitrygx) [inline test/gtest/ucp/test_ucp_tag_cancel.cc]: you can rename `release_send_req()` -> `release_req()` (or smth like that if it's already used by another function) and use it for `rreq1`. it should decrease code duplication, since you did the same for send requests

BTW, what if you call new added function `release_req()` for `rreq2`? Is it not so bad to do `wait(rreq2)` twice?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/7684aa5f255fc8fca642b1f8d0243c64066938b0/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/cf5ea8a4320c25a9112d80d0248b938ffff769d4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/21931552f6a706661ac67b86b2855df07a4cd485/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/40ca3bee3b7097ee91445563468357baca5a94f6/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/2201203b9a7dd75923b6cb13e4cece6d830f3b1f/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/0ec7cc5bf7013bf2b8540d30a9545c908862f321/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/08bbd65ac5f45c110adf0bccc02551660d647c9f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/7441f8438cab1f2c3dac6f83a1dc04930416c489/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/28fc9203fdd97990fb3d9a5947f7bda5914aa687/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/68e8e4527178bd5608e395b9c84b58a0c0843d1f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/f2e96a5ed6ec057532f6159e6742b38c8687085c/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/01bc6d73112f58c5d9072777af640db478d2674d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/f773b6782bc0dad5e75a2509a6fc4923215c0667/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/7e30200c31ac43115a5d5411bd657d1a02c82daa/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/e08cbbbf7693083e8c54293edc3dc257d1c6121b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/c2d52b274c84f6b89f367c9babff64a68243b5ea/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/d702bcfe8901771732b79be4f5d8464f82d57524/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/0c74eda165ba25e4da97cd08a308f6fcd8059d83/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/f6242a483512f8ede9f661b6ec0cb73dd266f333/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/ec9c9b14806c40f3afd3ca70c43a6851f9d2a8fe/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/717d4a27a97910f7313d0bb312a9e7ddff7314db/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/92bce3b824cb56cd3efb809650dde2afceeb7f0a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/f5fed0a063f515deb9cd3b2b2db0a611950df0d8/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/2dfca0e0b68e4079ee48ae66d9ec589d68908df5/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/6820a6df58904986c620815b1dd420b0/raw/23f167b2028abaadee609f2ce5ed52e8a45a3373/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: test/gtest/ucp/test_ucp_tag_cancel.cc [hunk 3]
```diff
@@ -32,4 +44,42 @@ UCS_TEST_P(test_ucp_tag_cancel, cancel_exp) {
...
+    EXPECT_EQ(UCS_OK, rreq1->status);
+    EXPECT_TRUE(rreq1->completed);
+
+    request_free(rreq1);
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_tag_cancel.cc]: use wait_and_validate() - for all requests in this test

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Dec-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/ee8107d33a2b9726f7ec33330f19a5f23b0de851/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/289eaad0fbcfcc49e1fe161a1f522e2fa3ec920e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/76bdfd77a044096b93a53a9d7acd7e1d47267a91/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/c4e13b9f27f24fbfcbfc33e1a1f22c1eedc4a19c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/f47d213647b40a1f2b7308be6bd4af1aff396624/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/17f9dfe31c3fdfb2d0f5092a694f86b0b9ebbf84/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/23afe07892d9e56d3aeba4a14e9cd46361c88fce/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/ae677115a764e0b3e57560c5afbcadcd972a8654/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/939bde2da9187bc8683714b9015bf3577a94fd52/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/c3e84474f29e414d10af1ee232a0268321499e88/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/5551ee523f6a0d955cc05efa2df6d0b8335878c9/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/44438990c9d9771faac9a20711f089de0b6b6247/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/ddcdb1062a25e1c26fe199ca6003f39cb3611a7d/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/b62a638d8077d02f1bd98502bcd89da1a2605f7b/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/02d79f44a2ccbcd7283e5c2e2975a33186dd2266/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/c506ad137d5514d5b2bb5649bdebc4f1bd01dcd0/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/5f89b044ab707802a5e640ad3c688a7a422b837d/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/45374dd2e0902ef858c7f8d2e294afa64f3cee63/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/1d18f873ae2da9fa9790b18a4cd50fab38272578/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/69dce82671eaf093da1ca83347ba918c466e5407/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/8cff93ff1f475a2c63950b8adc6f39dc2c0dbd21/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/ea85d51e7687386db5cfa7250c15196c71e5bbab/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/de08e56d4d6072ecbd38faa1a19533fd577caf1a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/c15b3c509dad29ebfca36e0b51116a5f17296d49/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3450d1f5a5161b72c16b04017dd56832/raw/432259d4f0c072082666c5ffe4607fd6c32ec5cd/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
