### PR TITLE
UCP/WIREUP: Don't select allocated memory access lanes for non-host

### LINKED ISSUE #9413: Assertion `ep_addr_index < address->num_ep_addrs' failed
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/70610/logs/811
```
[----------] 1 test from all/test_perf_node
[ RUN      ] all/test_perf_node.replace_node/0 <all>
[swx-rdmz-ucx-new-01:29823:0:29823]      wireup.c:346  Assertion `ep_addr_index < address->num_ep_addrs' failed: lane=3/7 tl_name_csum=0xd47a address_index=2 ep_addr_index=1 num_ep_addrs=1

/scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/ucp/wireup/wireup.c: [ ucp_wireup_match_p2p_lanes() ]
      ...
      339         address_index      = addr_indices[lane];
      340         address            = &remote_address->address_list[address_index];
      341         ep_addr_index      = ep_addr_indexes[address_index]++;
==>   342         ucs_assertv(ep_addr_index < address->num_ep_addrs,
      343                     "lane=%d/%d tl_name_csum=0x%02x address_index=%u "
      344                     "ep_addr_index=%u num_ep_addrs=%u",
      345                     lane, num_lanes, address->tl_name_csum, address_index,

==== backtrace (tid:  29823) ====
 0 0x0000000000137465 ucp_wireup_match_p2p_lanes()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/ucp/wireup/wireup.c:342
 1 0x000000000013caa6 ucp_wireup_process_request()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/ucp/wireup/wireup.c:689
 2 0x000000000013de49 ucp_wireup_msg_handler()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/ucp/wireup/wireup.c:932
 3 0x000000000009525e uct_iface_invoke_am()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/uct/base/uct_iface.h:942
 4 0x000000000009525e uct_ib_iface_invoke_am_desc()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/uct/ib/base/ib_iface.h:387
 5 0x000000000009525e uct_ud_ep_process_rx()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/uct/ib/ud/base/ud_ep.c:1064
 6 0x00000000000a1ec5 uct_ud_mlx5_iface_poll_rx()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/uct/ib/ud/accel/ud_mlx5.c:527
 7 0x00000000000a1ec5 uct_ud_mlx5_iface_poll_rx()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/uct/ib/ud/accel/ud_mlx5.c:534
 8 0x00000000000a1ec5 uct_ud_mlx5_iface_progress()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/uct/ib/ud/accel/ud_mlx5.c:585
 9 0x000000000006ac45 uct_iface_progress()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/uct/api/uct.h:3604
10 0x000000000006ac45 ucp_worker_iface_check_events_progress()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/ucp/core/ucp_worker.c:680
11 0x0000000000058ab1 ucs_callbackq_spill_elems_dispatch()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/ucs/datastruct/callbackq.c:383
12 0x00000000000714e2 ucs_callbackq_dispatch()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/ucs/datastruct/callbackq.h:215
13 0x00000000000714e2 uct_worker_progress()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/uct/api/uct.h:2787
14 0x00000000000714e2 ucp_worker_progress()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../src/ucp/core/ucp_worker.c:2986
15 0x0000000000aab4bc ucp_test_base::entity::progress()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:1037
16 0x0000000000aacb0f ucp_test::progress()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:167
17 0x0000000000aacb0f ucp_test::check_events()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:245
18 0x0000000000aad02e ucp_test::request_process()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:289
19 0x0000000000aaf1d0 ucp_test::request_wait()  /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/ucp/ucp_test.cc:311
```

### PR DESCRIPTION
**Pull request by yosefe**
## Why
Fix #9413 

## How
Avoid adding extra lanes for accessing RDMA memory type

### CODE REVIEW

File: src/ucp/wireup/select.c [hunk 1]
```diff
@@ -874,22 +874,21 @@ static void ucp_wireup_unset_tl_by_md(const ucp_wireup_select_params_t *sparams,
...
+        ucp_tl_bitmap_t *tl_bitmap, uint64_t *remote_md_map,
+        ucp_lane_type_t lane_type, ucp_wireup_select_context_t *select_ctx)
 {
     ucp_context_h context                = select_params->ep->worker->context;
     ucp_wireup_criteria_t mem_criteria   = *criteria;
     ucp_wireup_select_info_t select_info = {0};
     double reg_score                     = 0;
     int allow_am;
-    uint64_t remote_md_map;
+
```
Comment (brminich) [inline src/ucp/wireup/select.c:885]: pls remove

File: src/ucp/wireup/select.c [hunk 2]
```diff
@@ -874,22 +874,21 @@ static void ucp_wireup_unset_tl_by_md(const ucp_wireup_select_params_t *sparams,
 static UCS_F_NOINLINE ucs_status_t ucp_wireup_add_memaccess_lanes(
         const ucp_wireup_select_params_t *select_params,
         const ucp_wireup_criteria_t *criteria, ucs_memory_type_t mem_type,
-        ucp_tl_bitmap_t tl_bitmap, ucp_lane_type_t lane_type,
-        ucp_wireup_select_context_t *select_ctx)
+        ucp_tl_bitmap_t *tl_bitmap, uint64_t *remote_md_map,
```
Comment (brminich) [inline src/ucp/wireup/select.c:877]: why not `ucp_md_map_t`?

**Comment by brminich** [comment]
do you know why it did not fail in the corresponding PR?

**Comment by yosefe** [comment]
@brminich ok to squash?

**Review by brminich — DISMISSED** [review]

**Comment by yosefe** [comment]
Updated the PR to avoid adding extra lances for accessing RDMA memory type

**Comment by yosefe** [comment]
@brminich @roiedanino can you pls review?

**Review by roiedanino — APPROVED** [review]

**Review by brminich — APPROVED** [review]

**Comment by brminich** [comment]
wire compat still fails

**Comment by yosefe** [comment]
@brminich wire combat test passed now

File: src/uct/sm/scopy/base/scopy_iface.c [hunk 3]
```diff
@@ -16,6 +16,10 @@
 #include <uct/sm/base/sm_iface.h>
 
 
+#define UCT_SCOPY_IFACE_DEFAULT_OVERHEAD 2e-6
```
Comment (brminich) [inline src/uct/sm/scopy/base/scopy_iface.c:19]: Pls use it in `uct_scopy_iface_query`

File: src/uct/sm/scopy/base/scopy_iface.c [hunk 4]
```diff
@@ -16,6 +16,10 @@
...
+#define UCT_SCOPY_IFACE_OVERHEAD         500e-9
```
Comment (brminich) [inline src/uct/sm/scopy/base/scopy_iface.c:20]: can you pls add comment explaining why we need 2 values

File: src/uct/sm/scopy/base/scopy_iface.c (hunk 3 above)
Comment (yosefe) [reply src/uct/sm/scopy/base/scopy_iface.c:19]: It's used there

File: src/uct/sm/scopy/base/scopy_iface.c (hunk 4 above)
Comment (yosefe) [reply src/uct/sm/scopy/base/scopy_iface.c:20]: added

**Review by roiedanino — APPROVED** [review]

**Review by brminich — DISMISSED** [review]

**Review by brminich — APPROVED** [review]

**Review by roiedanino — APPROVED** [review]
