### PR TITLE
UCT/MM/XPMEM: Add remote regions cache for fast rkey_unpack

### LINKED ISSUE #4449: git master compile errors with newer compilers
master @ 803b4026c5c0a78ceda24a2ecc03c995ab613d96 with newer compiler versions, e.g. gcc 9.2.1, clang 8.0.0

```shell
Making all in knem
make[4]: Entering directory '/usr/local/src/ucx/ucx-git/src/uct/sm/knem'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/usr/local/src/ucx/ucx-git/src/uct/sm/knem'
Making all in mm
make[4]: Entering directory '/usr/local/src/ucx/ucx-git/src/uct/sm/mm'
Making all in xpmem
make[5]: Entering directory '/usr/local/src/ucx/ucx-git/src/uct/sm/mm/xpmem'
/bin/sh ../../../../../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I../../../../..  -DCPU_FLAGS="|avx" -I/usr/local/src/ucx/ucx-git/src -I/usr/local/src/ucx/ucx-git -I/usr/local/src/ucx/ucx-git/src -I/usr/include -O3 -g -Wall -Werror -mavx -fno-omit-frame-pointer -I/opt/xpmem/include  -MT libuct_xpmem_la-mm_xpmem.lo -MD -MP -MF .deps/libuct_xpmem_la-mm_xpmem.Tpo -c -o libuct_xpmem_la-mm_xpmem.lo `test -f 'mm_xpmem.c' || echo './'`mm_xpmem.c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I../../../../.. "-DCPU_FLAGS=|avx" -I/usr/local/src/ucx/ucx-git/src -I/usr/local/src/ucx/ucx-git -I/usr/local/src/ucx/ucx-git/src -I/usr/include -O3 -g -Wall -Werror -mavx -fno-omit-frame-pointer -I/opt/xpmem/include -MT libuct_xpmem_la-mm_xpmem.lo -MD -MP -MF .deps/libuct_xpmem_la-mm_xpmem.Tpo -c mm_xpmem.c  -fPIC -DPIC -o .libs/libuct_xpmem_la-mm_xpmem.o
mm_xpmem.c: In function ‘uct_xpmem_mkey_pack’:
mm_xpmem.c:197:42: error: taking address of packed member of ‘struct uct_xpmem_packed_rkey’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  197 |     status = uct_xpmem_get_global_xsegid(&packed_rkey->xsegid);
      |                                          ^~~~~~~~~~~~~~~~~~~~
mm_xpmem.c: In function ‘uct_xpmem_iface_addr_pack’:
mm_xpmem.c:216:40: error: taking address of packed member of ‘struct uct_xpmem_iface_addr’ may result in an unaligned pointer value [-Werror=address-of-packed-member]
  216 |     return uct_xpmem_get_global_xsegid(&xpmem_iface_addr->xsegid);
      |                                        ^~~~~~~~~~~~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
make[5]: *** [Makefile:602: libuct_xpmem_la-mm_xpmem.lo] Error 1
```

### PR DESCRIPTION
**Pull request by yosefe**
Also fixes #4449

### CODE REVIEW

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/3d89f6effc1015aa43d17aafd4f2c777c107009b/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/d30434fac88caf8e2d5341b8314984aa6bdcfe7e/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/fa80ed3b655ec071035c8195ac71f66aa10c6030/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/006545ee0cecc85998c6aaed9f5188f42dc1a16e/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/1cdadcc0cb48b7dd8eb443a7b519a133f95a9bfc/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/fac2a036560468a5043937c5c39590de7aa6614a/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/87222ec902f3489346625fe7fdcd1bf69c6357f1/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/0525a8fd089c2893d8e94cf9d82703287f025be3/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/32f2a923ea3366187cee006cffa85e8d227fa8ba/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/2ab5d16d834463c2a8c2866678e30cef6c720996/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/08f86143fcdc94c2623573e18531ce225483a956/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/87a065258c2a04e7a6539e779157f00b4d1c0969/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/6267aca8f0e940b337cd259689acd56686844ada/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/afc1bd0834b33f33070aaa21e8bf509e3125d823/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/c61e35246061d2be9105bdaaeb3f07175b4ad080/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/98087051df89e0df2b299f17296ac0421bf79bcc/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/88ca39e89d5813ef591ad84cbf2c24d55594c01c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/8e425bd332bbc258ba9b9383590338469ce03ad9/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/ecf7325d3beb603edac6a0d6b47aff415de77e9a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/ff7eb8739ca93200d97b3270563228c5c9c930fc/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/e5436d4a6de5cd4f9e99aba573fc5561a131914e/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/dc8772a62cc930761450cf7fcc3056a3316c53d6/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/2fb41e39c6c12cd6588ff81fe498ddb5dc50fdbc/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/f619ad9307af3d7a211462acc4531260d9d82337/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f5f19059ca1aa78500d69147ccf7eda2/raw/e661e486de0929cd9c87267e731dddfed01e9aa4/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 7 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/9339ce3b64977979b420a92b686289d398cf4723/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/fe623e210bee2499c8524db8321e2167a1254011/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/96b12a03369335377365af3cb3b38ee37e3563db/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/01780e0250c49a6db2b50c746c15dec37cf35301/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/70854b6d628234259bf8ccef8add751f85c11490/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/e4dc5a7d10390552a9471ee3dc2640a9d9a1d8ce/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/c5e8ad1e827d7f71dda6278dd34c1c953f2a5037/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/753984a59d3670540b53c47227b7d61ae22d7a28/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/b261f17f2edaca0d6644ab7ca1313caad954308b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/0e2f773e06671702cb7a8ca6d16757ed49340bdd/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/dcdc652e75c0c3ab06b3736790fa5772e2755747/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/4992b9bd6a37267456b6468fc39c9d757aee82ac/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/8b88f0b5e596a932a42dccf81b2546d2f2f0d945/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/5633c3aaace2f499679ef65b79dc6fdd6bbd94c4/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/30ace824232ea5ad8ffbc6149ac8d861c511069d/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/440d5c4b53fede7916aaa5cf4e1d0d747ca37b18/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/30fa832ebbb10c34b465ab022922745a56073e8d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/9582d8247afd8717ea33dacd82d6e0226f1070b6/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/d3680fc0e49c83f0c1a2271dbcbcbb066218eba0/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/a4fd0bd28c75c886ccba6a9e38da342ec879c896/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/7cda98ed9d6e7505b89d92b8e3ba9b30cf166693/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/5836b3f24d1c04aef30a25a11544f98be515d611/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/e0e9f2e724fb677a3a0070ac4dc43453dc654d53/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/78fe6bad2defe06c540f06585f93f25c295fc4f4/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1e10b86ef32043905945b73c1184100c/raw/fdf87ff9c17d7d8b6d61031e9ef52d42cfa31d3f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/26fdf200d00c2400c7a90eaaf3a146e7fe226476/_main) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/0d2e0d23c1347c512bacbf403b9b5735864a7fae/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/83ad458f76f1ab237df694ee4d6326a3fa84f891/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/42584309a3336146c799f4abed273b0e5cd0dea7/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/b655ba2aad128c715c6f573941deda48f538f145/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/6697f7e49daff7b04ca5ebe6cc3d4519d0e4a14c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/1330847a81793e586f6d1d37ef9d71b16ccd3304/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/040ea4efb1d7825f24024217b7a26778c45569f4/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/7ca0509acc362470045009d22e795602c9f4d3cd/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/e8ce9b60da93e644cc280c2f1217b4a7dc2aedf6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/56b47536c03ca908566135ffcb75506edd6769b9/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/a966424650a2e5620c253fcce133058a28c07295/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/1535c3ba9179306539387ebc902584181300d53c/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/619aaf9984d4639a91bc3cf9c1c6ef60198b501d/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/8000812f9462f54ad7d76208ea66831e14b9221a/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/1d7be1d3a71f282f5ad9c7de979c8638e997eae1/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/2dfac191d2683843e16318a1da5b5a3575c49134/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/1e75404b3ff95c9f9b06323a758c609a59918e01/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/2e2e697b0241f7ece3cb013497faa9600c816a5b/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/42bc1f4f168a2ad7b09fd7bf84dd3f98cbf82cb1/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/835e1ebedf73f1516fc50435446957162acece90/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/9dd9ad7293e148cb17b06bf6e1a1af1fa6e9c0fb/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/64c42036dbbcc43e1409dd609e006905effa98e2/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/81e12e4d1fdf2319232f2d36f662bc5fd413e1cf/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/121a3b81a44d2385ccb7550e3e504a5c/raw/ab45f841472c809c691286eb093f98eede7ab0fd/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/25d022b15727ecc445d76d1c112671b678f76a28/_main) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/dd7037d0f139116c5960979eaab139e6449f1dd3/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/5abe0375761904fe3a7d25fe45e929cf65bfdcd1/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/275941c663912902078e7c026ddb1a774d766ac9/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/b44e047ea58448699884f493b302b508df301c72/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/1a1d5a11ae979e05e3d1c83779182b50bb36d0ad/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/653d524287ba3099a743c1dc8cf7992bb29ad1f3/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/d7f4d98c43c62a8456d2319b2ccd936d03f78f4c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/5f48d809367b3ef8e4c7e14160206c05d91864b0/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/18442196a2b104a430028a47883af3c66058e214/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/befc0465bf1d55e0f72c0427b276a6af5468d856/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/4de2cb9d72de274f8117f8aca424eb2e2cc6a28c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/eed41be6312d7ffee54e4bca2f265e2c5a96a360/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/ae9557921a6ec56083c3b503167bf2bc0e9cc133/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/12b43f4c87c9a306725dffaaf52191a571598bf8/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/83664b62b1928093b81930e48f04b41104d73546/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/8698e2b1889af68ecda2140b4d17a91d8e9ff9b6/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/07499eae50803cf6fd975b76d98f0b770dad1758/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/a59225d3a05b58f3c0fefc18f9973034254f778a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/e2d253294376727361f60a6b79c4d6f5d335dd53/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/5735339ea1f16b80e28173d5a8141798cf379e53/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/5accb79a974a9b86ba498c39a77b29f41d073b31/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/032b02a03a22d594a1555e90eba4e3ecfd129661/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/0c80a90047f503860e13f310c3488a8130194c8a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a081214015453b7fd964924feddb230e/raw/0176f6a4b424213f462e499f8229f6f7a3d9d2ee/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 24-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/6b290f4643c399cba0d65e6eab5fd953db812030/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/9e933f32161c43fcc299a96fdd2532b640c229f3/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/c393d3ad5239ab1207a596699f749a17fd6b1f7f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/33ab9ea6be951cbb520d99c234b2c22c0710fbba/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/0699bffb5308d87a32608f5fc324f005c92203e5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/9771d40c4886c29a5951c8eb4f4cf6f23b161080/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/6efe494b06ff70b756f4d4c2faf068846fd7b5f2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/45aef9f8418154fd41882708fe796519787b110c/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/1912eee5bf7e0bbbda0a184f57e28f0597e0c8fe/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/602ffeb45bdf6cd45938e4b79990bb28e886d46b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/c6a7c8cc2bdb52c27a9b986e8fcc690746b5432a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/24e5554b9c191e9704c535c924b8c178fbde9827/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/5a734f8ea535b8fd6ded3c1f83a155a2689828cc/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/6083aaa25054623caab495de3ef53037037ef525/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/33e4c056fb6f3d872c5ec5351266b5ced4393eea/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/b53096d9bd0594c9f45be60383dbd460f3434968/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/d31a9bddb5dd837085a165e638bf0ccc042a1c1f/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/28a046114898422d7ebe9059d9d28b7646db217c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/18c794d77f276f0234a65bb8d41102af9b85d1ba/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/407ab1707c8d0a173994d800d33ba12c47185d4b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/a3ffdb1f21f68e744c76711756532f973a9c92ec/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/6e081885b1700d708403572e1167787b23c75560/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/c9ed3ddfcce6fe10c0ad5b781dd4b97ca8cff409/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/245beb805be1ff60a24e48922d0fd4683e6646d1/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a121ec979d841d45238a8f6ca7e007f7/raw/e26cc7e8ee890e4d3e889b4098bf96ba79c23ef9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/sm/mm/xpmem/mm_xpmem.c [hunk 1]
```diff
@@ -65,140 +116,321 @@ static ucs_status_t uct_xpmem_md_query(uct_md_h md, uct_md_attr_t *md_attr)
...
+    rcache_params.ucm_events         = 0;
+    rcache_params.ucm_event_priority = 0;
+    rcache_params.ops                = &uct_xpmem_rcache_ops;
+    rcache_params.context            = rmem;
+
+    status = ucs_rcache_create(&rcache_params, "xpmem_remote_mem",
+                               ucs_stats_get_root(), &rmem->rcache);
     if (status != UCS_OK) {
-        return status;
+        ucs_error("failed top create xpmem remote cache: %s",
```
Comment (brminich) [inline src/uct/sm/mm/xpmem/mm_xpmem.c]: `to create`

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/977913cbb7f138ca7d13afcf5b802e4767f85456/_main) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/13b2f190825273b9176b1ab2c1790741ebad2064/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/afb54f283aea91d94a3f223838e1a3c2313e7424/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/fdb99923fefed6e1f159fc1b5274b72e90d1fdd9/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/c195a4135923ecb4f68c07bc47ca483b86af3a8d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/97afda2841d90fb2246ef00f2e726567e9f8f70d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/c00ec40b877d602db9f14271c86fb07f2f5da610/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/9e7d7114413631c0e820431485caccdcad7bcce7/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/07a1270aebd25f064954e8f55d8e7410e9e8c06f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/cbf10c081a1f54cf44e8924fd3d64c645bf22936/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/a9aa11d5251d6f02408f9090fbf1e469e1bf52bd/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/c20d84231b53b1f6c750d859581102bf85a985e9/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/00b0e5d48a0a221c1862728f2a4d45b191ad8b51/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/95638556d8f263dc4521df1768181bb9c74ffdb2/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/b6c17e901cead7b3b94b104656707bc325031164/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/740e7eb5eafb431f6198343ae4e09aaac9df6ab8/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/3f603b7886c059c98bb71ba52f4f4b5ff97772cd/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/929fc9bf2ea348e533bcafeec6bf6733b9d66304/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/f99528d6fb36ed9ca846ba7182fc4be285f1511a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/bb83da920f4aec8a96de0d1a4c4c9c084cf17bf3/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/bd8f4668205f238b97051b474559aa3d7d91e266/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/fa95e501c81b23956a0b48419b5ee1ed5c69bfd1/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/bdd03f191962cf410f4e9b1ca6123d6c8bc5862c/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/b5031bd4062974a93218ad15d729c0c8ed812e7c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3fc0f571257775527e8b811609e4de9/raw/272f5a320458ba8df0701c127f1c3e26e8db6a60/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
issues with connecting to gid_index=1 on mlx4_0 device on hpc-test-node2 (neigh resolution failed)
removed ipaddr from mlx4_0:2/ens1d1 for now
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/3854ea260e75e2b7601309b269c2495a1e93d4f1/_main) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/bcb2e000dc442a43a44f78736a5bc8d45f3919dc/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/24f1622680fadf1f6dfcec63fe6392d730252d67/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/2747dfac154cfc082f44ce930777132cbb1aacea/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/b23f004d5670a8d5922054df8b3f14a63cf00d38/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/5b2eb815c08af6c3f36626177658af7576fd7b58/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/1de59735c47fcae2d1a471c14533a1f015f1381d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/74a5e3846f73efd0b1320b3932d68ec49a60ae50/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/11fbc8ed8f386fad97d5404991ddd83a18a43c3c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/d768a684737387e3465b9edd5bdd1885eafea8cf/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/5752e3e1d4261ab8157577527066e8c12ec73619/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/7798d5925c31d54e6ac22b7590bbfa456de9a9fc/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/73e1b152292867b9ff16b1142a08dd9b348ddaf9/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/69fe07bfd6ab45f0132de55af851e0a696b6742f/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/706046744c983e1468ff6ba804261681ae07bfc1/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/8f6703f90b7b9fd91d9b709ea0aa6b239ca0e730/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/53f6d2f1a457d56ac06b4faa5d2039a8de0a5d7b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/1e9b6d0a0f57079b6228e4224efbfb5cbdbc3abe/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/5cf7e240b7b0ab478e2ffa08a8faa5658191e17e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/54f7d50d81131a6a1d1df854807391f7b2b3385b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/1e01e7b43b0719399ae8ce112dfccd3dc659c577/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/284ef7bebace720c430b5b9dc68769b457606f3c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/d9367f9a70caaa532b3da569e6a9fbd6a4faf743/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/e7621b40d6bbe56cbd0fa6ca1700e9d1e420da3f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/960205ef3068e7a8da443de865797378/raw/4a6f9dd92357015ff9855376ca26212b3d1eed64/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 27-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/a6946a25efd548e33668a1d09cbae78864370d4c/_main) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/817de24aec90aa2aa19bc42a18624699095a9181/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/d0aeba95a8ba33a4d60854544017ef43dff4bc32/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/f7c6b8d2c2864cf9450ae20159c0100f7a7ec1bb/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/f5c5e1b6e21849396873673bb1f3979d94722bd4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/fc9eed17ef7e93c774c1ca3b27d9b54d7dcfa270/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/fbec3ad425bf3becad9a95a9d0684f8d261dd681/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/5b7e81cb7705db02b127727392c643b47b4d3c8e/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/19903ebe8d4f338896eb19677d992f94ec0f7a0b/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/ab5169d16eb4797a54fa13c9d6be74fc91b00535/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/55afc52b14b2d5cf896bae11a4c582a7470100c0/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/23d1d18bb88bb1d2074583cf01a344563d1de46c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/720b9ca548548812a7b625f35a0bc5f42a687446/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/5e6915f667f360a22e2ede9180871425da9eed92/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/7293320ba8b31c408b3bd8f225a131c11edc5a14/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/49d316337ccb3ef7992e8731c53d2f5be7571256/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/25c7b552a3be16993a3e28848bd744e522d0bd00/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/6e9cb1e5efde1f2c2915f7886d3771ec16c55d27/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/8e40aec9df5536f90eeb4ec780aaf7d5073db5d9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/3d95494033ed3db95f33b25a2ba03e9ab8df5df2/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/6164ef4ac84a383a5ce5e7f66e86685b5b23790f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/62182b7c08f3690a048ea7b4323d9134c009caa5/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/70eecd052c16a48e656384904c20cf0dcf6d70d5/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/6e243d1c0403699ce615bdfee77deb7b9ef95385/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d8a5e11f1a627ba134c6f826aca9148b/raw/b6172ba2ceb0113bc4d0a69965ce9931e33d2eb3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
driver issue https://redmine.mellanox.com/issues/1182031  on hpc-test-node2
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 27-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/b6a33928f35f1e601a251782a5ace2d1c172baa7/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/ad4ae08cc816df174127c10fcfda78ddfca2d709/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/7fd183c352bd59a68e2a3b1ce197aef4bf017476/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/9e51e8bc2fb3ebd2d6b95cacc79645b99da38474/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/ca846f50ad17452280473dea9da68e251822a6d1/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/e88351899b9a3c2c762dc05cd6229d58761feb85/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/5caea18400ae4a3d0b6526a66771c8a8949f4259/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/64b60fb8a6aeaa927ebe0ecb325cfb6acd5315fc/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/eb02f12894110d84b31c83d462377f3743af22a0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/5f3081598db1b73d5bfb2aaf8275df5d06173d18/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/a4e7de7a85a5efef518488e613f02adf189b52db/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/dfc6070059dbf8654d53de1b5eb265e2a4314448/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/e5986eecb145a19c0aae296460c14717a36a8180/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/465e3e172b1e282b4c6e9f4f149176a5011bc43e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/d8a63b2d0335332660338c93f1f9400dbd3b64e6/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/0da9e50e74403ef971024126a96315c9b6f0c17e/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/46357dcff2a23662f12b78bd5a646048b992ecc7/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/cb316f21eeb3a4a4179b274a680f19473bf244c9/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/c7755a9cac259bf85573e1a1594452025c9e1aaa/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/a5766ff54ecebc7018c4a54b302489bc584438d0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/a36bbf0d593286fd175bdb0c903792c77ce9d060/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/170174ef9687b9ae870815e6665df1df5fd0cdf9/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/5a262f76973950911f2190b6f359aaf2220b4eb7/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/edaedb1e670f326216335e169fb2b806002bc823/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e92e7ac9aed08b8d38910b0b20b3b72/raw/841dd5934df7bcaf499f9af6c25a3c8f152cde4f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
