### PR TITLE
UCS/ASYNC/UCP/UCT: Added checking of is_blocked

### LINKED ISSUE #6214: tcp/test_ucp_sockaddr_protocols_err.tag_rndv_unexp_put_scheme/4 failed on sputnik4
```
2021-01-27T06:26:20.9991226Z [ RUN      ] tcp/test_ucp_sockaddr_protocols_err.tag_rndv_unexp_put_scheme/4 <tcp/bidi_stop>
2021-01-27T06:26:21.0182979Z [     INFO ] server listening on 2.1.4.4:44253
2021-01-27T06:26:21.0229904Z [sputnik4:23310:0:23310]      wireup.c:1032 Assertion `new_key->wireup_msg_lane == ((ucp_lane_index_t)-1)' failed
2021-01-27T06:26:21.7245196Z 
2021-01-27T06:26:21.7248115Z /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c: [ ucp_wireup_check_config_intersect() ]
2021-01-27T06:26:21.7249456Z       ...
2021-01-27T06:26:21.7250927Z      1029     /* wireup lane hasn't been selected by the new configuration: only this
2021-01-27T06:26:21.7252590Z      1030      * function should select it */
2021-01-27T06:26:21.7254069Z      1031     ucs_assert(new_key->wireup_msg_lane == UCP_NULL_LANE);
2021-01-27T06:26:21.7255153Z ==>  1032 
2021-01-27T06:26:21.7256194Z      1033     /* set the correct WIREUP MSG lane in case of CM */
2021-01-27T06:26:21.7257716Z      1034     reuse_lane = reuse_lane_map[old_key->wireup_msg_lane];
2021-01-27T06:26:21.7258893Z      1035     if (reuse_lane != UCP_NULL_LANE) {
2021-01-27T06:26:21.7259789Z 
2021-01-27T06:26:22.4066229Z ==== backtrace (tid:  23310) ====
2021-01-27T06:26:22.4069497Z  0 0x000000000005ccb8 ucs_debug_print_backtrace()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucs/debug/debug.c:656
2021-01-27T06:26:22.4071660Z  1 0x00000000000a15b1 ucp_wireup_check_config_intersect()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:1032
2021-01-27T06:26:22.4073475Z  2 0x00000000000a15b1 ucp_wireup_connect_lane()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:858
2021-01-27T06:26:22.4075170Z  3 0x00000000000a15b1 ucp_wireup_init_lanes()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:1187
2021-01-27T06:26:22.4076935Z  4 0x00000000000a1cd7 ucp_wireup_init_lanes_by_request()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:363
2021-01-27T06:26:22.4078681Z  5 0x00000000000a1cd7 ucp_wireup_process_request()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:491
2021-01-27T06:26:22.4080385Z  6 0x00000000000a2bf1 ucp_wireup_msg_handler()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:664
2021-01-27T06:26:22.4082597Z  7 0x0000000000021e64 uct_iface_invoke_am()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/base/uct_iface.h:663
2021-01-27T06:26:22.4084313Z  8 0x0000000000021e64 uct_tcp_ep_comp_recv_am()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_ep.c:1158
2021-01-27T06:26:22.4086030Z  9 0x0000000000021e64 uct_tcp_ep_progress_am_rx()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_ep.c:1292
2021-01-27T06:26:22.4087725Z 10 0x0000000000021e64 uct_tcp_ep_progress_data_rx()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_ep.c:1389
2021-01-27T06:26:22.4089468Z 11 0x0000000000026854 uct_tcp_iface_handle_events()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_iface.c:232
2021-01-27T06:26:22.4091250Z 12 0x000000000006aac1 ucs_event_set_wait()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucs/sys/event_set.c:215
2021-01-27T06:26:22.4092953Z 13 0x0000000000026764 uct_tcp_iface_progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_iface.c:249
2021-01-27T06:26:22.4094667Z 14 0x000000000003e1fa ucs_callbackq_dispatch()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucs/datastruct/callbackq.h:211
2021-01-27T06:26:22.4096356Z 15 0x000000000003e1fa uct_worker_progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/api/uct.h:2436
2021-01-27T06:26:22.4098041Z 16 0x000000000003e1fa ucp_worker_progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/core/ucp_worker.c:2407
2021-01-27T06:26:22.4100015Z 17 0x00000000008daeeb ucp_test_base::entity::progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:870
2021-01-27T06:26:22.4101868Z 18 0x00000000008daf97 ucp_test::progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:155
2021-01-27T06:26:22.4103654Z 19 0x00000000008dafeb ucp_test::short_progress_loop()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:163
2021-01-27T06:26:22.4105577Z 20 0x00000000008c50ba test_ucp_sockaddr_protocols::do_unexp_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1080
2021-01-27T06:26:22.4107600Z 21 0x00000000008c50ba ucs::entities_storage<ucp_test_base::entity>::receiver()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.h:188
2021-01-27T06:26:22.4109602Z 22 0x00000000008c50ba test_ucp_sockaddr_protocols::do_unexp_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1081
2021-01-27T06:26:22.4111702Z 23 0x00000000008c5fae test_ucp_sockaddr_protocols::test_tag_send_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1186
2021-01-27T06:26:22.4113745Z 24 0x00000000008c5fae test_ucp_sockaddr_protocols::test_tag_send_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1187
2021-01-27T06:26:22.4115795Z 25 0x00000000008adb50 test_ucp_sockaddr_protocols_err::test_tag_send_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1585
2021-01-27T06:26:22.4117965Z 26 0x00000000008adb50 test_ucp_sockaddr_protocols_err_tag_rndv_unexp_put_scheme_Test::test_body()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1649
2021-01-27T06:26:22.4119927Z 27 0x00000000005d8b66 ucs::test_base::run()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.cc:347
2021-01-27T06:26:22.4121805Z 28 0x00000000005d8b66 ucs::test_base::TestBodyProxy()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.cc:373
2021-01-27T06:26:22.4123874Z 29 0x00000000005ba429 HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3562
2021-01-27T06:26:22.4125803Z 30 0x00000000005ae66d testing::Test::Run()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3635
2021-01-27T06:26:22.4127774Z 31 0x00000000005ae745 testing::TestInfo::Run()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3812
2021-01-27T06:26:22.4129589Z 32 0x00000000005ae8af testing::TestCase::Run()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3930
2021-01-27T06:26:22.4131557Z 33 0x00000000005b305d testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5808
2021-01-27T06:26:22.4133530Z 34 0x00000000005b3340 testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5725
2021-01-27T06:26:22.4135318Z 35 0x000000000054a2e8 RUN_ALL_TESTS()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest.h:20059
2021-01-27T06:26:22.4136946Z 36 0x000000000054a2e8 main()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/main.cc:102
2021-01-27T06:26:22.4138026Z 37 0x00000000000223d5 __libc_start_main()  ???:0
2021-01-27T06:26:22.4138890Z 38 0x00000000005989dd _start()  ???:0
2021-01-27T06:26:22.4139571Z =================================
```
Link to the job: https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=12925&view=logs&j=29aeebdb-3078-5ca1-e7df-02da2ddf99b4&t=ccac58dc-e7b6-5bfe-6f92-cc68fc64c085
Link to the log: https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/12925/logs/184

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

1. Add checking of async ownership.
2. Verify `ucp_ep_t::flags` set/unset + add async block/unblock in `ucp_worker_create()` and gtest.
3. Replace places where UCX has the comment "must call with lock held" by checking async ownership + Fix the bugs.

## Why ?

1. This is the method to catch possible issues with missing block/unblock. This mechanism was used to fix a bug in #6214.
2. To catch possible missing block/unblock when set/unset EP flags.
3. To have a check for async ownership to catch possible programming errors.

## How ?

1. Save `owner` (if `count == 0`) and increment `count` in ASYNC block; reset `owner` (if `count == 0`) and decrement `count` in ASYNC block.
2. Replace setting/unsetting EP flags by calling `ucp_ep_set_flags()`/`ucp_ep_unset_flags()` which checks ownership; Add `UCS_ASYNC_BLOCK`/`UCS_ASYNC_UNBLOCK` in `ucp_woker_create()` for consistency and test which discards UCT EPs.
3. Use `ucs_async_is_blocked()` to check that async blocked.

### CODE REVIEW

**Comment by dmitrygx** [comment]
@brminich @hoopoepg could you review pls?

File: src/ucp/core/ucp_worker.h [hunk 1]
```diff
@@ -47,10 +47,19 @@
...
 
 
+#define UCP_WORKER_THREAD_CS_CHECK_IS_BLOCKED_CONDITIONAL(_worker) \
+    do { \
+        if ((_worker)->flags & UCP_WORKER_FLAG_MT) { \
+            ucs_assert(ucs_async_is_blocked(&(_worker)->async)); \
+        } \
+    } while (0)
+
+
```
Comment (hoopoepg) [inline src/ucp/core/ucp_worker.h:57]: extra line?

File: src/ucp/core/ucp_ep.inl [hunk 2]
```diff
@@ -156,6 +156,20 @@ static UCS_F_ALWAYS_INLINE ucp_ep_ext_control_t* ucp_ep_ext_control(ucp_ep_h ep)
...
 
+static UCS_F_ALWAYS_INLINE void
+ucp_ep_set_flags(ucp_ep_h ep, ucp_ep_flags_t flags)
+{
+    ucs_assert(ucs_async_is_blocked(&ep->worker->async));
+    ep->flags |= flags;
+}
+
+static UCS_F_ALWAYS_INLINE void
+ucp_ep_unset_flags(ucp_ep_h ep, ucp_ep_flags_t flags)
```
Comment (hoopoepg) [inline src/ucp/core/ucp_ep.inl:167]: minor: may be name it ```ucp_ep_clear_flags``` or ```ucp_ep_reset_flags```?
@yosefe what do you think?

**Review by hoopoepg — APPROVED** [review]

File: src/ucp/core/ucp_ep.inl (hunk 2 above)
Comment (yosefe) [reply src/ucp/core/ucp_ep.inl:167]: should be reset

Comment (yosefe) [reply src/ucp/core/ucp_ep.inl:167]: but, why do we need a function for this?
also maybe add single function
ucp_ep_update_flags(ep, flags_add, flags_remove)

**Comment by dmitrygx** [comment]
@hoopoepg @yosefe could you review pls?

File: src/ucs/async/async.h [hunk 3]
```diff
@@ -90,20 +90,44 @@ static inline int ucs_async_check_miss(ucs_async_context_t *async)
     return 0;
 }
 
+/**
+ * Returns whether a context blocked or not.
+ *
+ * @param _async Event context to check `is_locked` status for.
```
Comment (brminich) [inline src/ucs/async/async.h:96]: pls remove `_` in `async`

Comment (brminich) [inline src/ucs/async/async.h:96]: pls use one term `is_locking` or `is_blocking`
btw why do you use `block(ing)` thru the code?

File: src/ucs/async/thread.h [hunk 4]
```diff
@@ -9,13 +9,52 @@
...
     };
 } ucs_async_thread_context_t;
 
+
+static UCS_F_ALWAYS_INLINE int
+ucs_recursive_mutex_is_locked(const ucs_async_thread_mutext_t *mutex)
+{
+    return mutex->owner == pthread_self();
+}
+
```
Comment (brminich) [inline src/ucs/async/thread.h:35]: extra line

File: src/ucs/async/thread.h [hunk 5]
```diff
@@ -9,13 +9,52 @@
...
+ucs_recursive_mutex_block(ucs_async_thread_mutext_t *mutex)
+{
+    (void)pthread_mutex_lock(&mutex->lock);
+    ucs_assert((mutex->owner == UCS_THREAD_OWNER_NULL) ||
+               /* can be locked again by the same thread, because it is
+                * recursive mutex */
+               (ucs_recursive_mutex_is_locked(mutex) &&
+                (mutex->count > 0)));
+    mutex->count++;
+    mutex->owner = pthread_self();
```
Comment (brminich) [inline src/ucs/async/thread.h:47]: may be no need to set, as it is supposed to be self already?

File: src/ucs/async/async.h (hunk 3 above)
Comment (dmitrygx) [reply src/ucs/async/async.h]: > pls use one term is_locking or is_blocking

done

> btw why do you use block(ing) thru the code?

because we have `UCX_ASYNC_BLOCK`/`UCS_ASYNC_UNBLOCK`

File: src/ucs/async/thread.h (hunk 4 above)
Comment (dmitrygx) [reply src/ucs/async/thread.h:35]: removed

File: src/ucs/async/thread.h (hunk 5 above)
Comment (dmitrygx) [reply src/ucs/async/thread.h]: done

**Comment by dmitrygx** [comment]
@brminich could you review pls?

File: src/ucs/type/spinlock.h [hunk 6]
```diff
@@ -73,11 +73,18 @@ void ucs_spinlock_destroy(ucs_spinlock_t *lock);
 void ucs_recursive_spinlock_destroy(ucs_recursive_spinlock_t *lock);
 
 static inline int
-ucs_recursive_spin_is_owner(ucs_recursive_spinlock_t *lock, pthread_t self)
+ucs_recursive_spin_is_owner(const ucs_recursive_spinlock_t *lock,
```
Comment (brminich) [inline src/ucs/type/spinlock.h:76]: seems no need to break line: unrelated and does not exceed 80 syms

File: src/ucp/core/ucp_ep.c [hunk 7]
```diff
@@ -344,11 +344,15 @@ ucs_status_t ucp_worker_create_mem_type_endpoints(ucp_worker_h worker)
         ucs_snprintf_zero(ep_name, UCP_WORKER_NAME_MAX, "mem_type_ep:%s",
                           ucs_memory_type_names[mem_type]);
 
+        /* create memtype UCP EPs after blocking async context, because they set
+         * INTERNAL flag (setting EP flags is expected to be guarded) */
+        UCS_ASYNC_BLOCK(&worker->async);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c:349]: it is just to prevent failing assert which protects `ep::flags`

File: src/ucs/type/spinlock.h (hunk 6 above)
Comment (dmitrygx) [reply src/ucs/type/spinlock.h:76]: it doesn't fit the 80 symbols per line requirement (it is `81`)

File: src/ucp/core/ucp_ep.c [hunk 8]
```diff
@@ -832,17 +836,18 @@ ucp_ep_local_disconnect_progress_remove_filter(const ucs_callbackq_elem_t *elem,
     return 1;
 }
 
-/* Must be called with async lock held */
 void ucp_ep_disconnected(ucp_ep_h ep, int force)
 {
     ucp_worker_h worker = ep->worker;
 
+    ucs_assert(ucs_async_is_blocked(&worker->async));
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.c:843]: maybe add inline function/macro:
ucs_worker_check_locked()

File: src/ucp/core/ucp_ep.h [hunk 9]
```diff
@@ -66,6 +66,7 @@ enum {
                                                         can be replaced with looking at local ID */
 
     /* DEBUG bits */
+#if ENABLE_DEBUG_DATA || UCS_ENABLE_ASSERT
```
Comment (yosefe) [inline src/ucp/core/ucp_ep.h:69]: why needed?
can we change ucp_ep_update_flags() func to handle this, instead of defining all debug flags twice?

File: src/ucp/core/ucp_worker.c [hunk 10]
```diff
@@ -2180,6 +2180,7 @@ ucs_status_t ucp_worker_create(ucp_context_h context,
                        &worker->discard_uct_ep_hash);
     kh_destroy_inplace(ucp_worker_rkey_config, &worker->rkey_config_hash);
     ucp_worker_destroy_configs(worker);
+
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:2183]: pls remove

File: src/ucp/wireup/wireup_cm.c [hunk 11]
```diff
@@ -581,9 +581,10 @@ static void ucp_cm_client_connect_cb(uct_ep_h uct_cm_ep, void *arg,
     ucs_assert_always(ucs_test_all_flags(connect_args->field_mask,
                                          (UCT_CM_EP_CLIENT_CONNECT_ARGS_FIELD_REMOTE_DATA |
                                           UCT_CM_EP_CLIENT_CONNECT_ARGS_FIELD_STATUS)));
-    remote_data    = connect_args->remote_data;
-    status         = connect_args->status;
-    ucp_ep->flags |= UCP_EP_FLAG_CLIENT_CONNECT_CB;
+    remote_data = connect_args->remote_data;
+    status      = connect_args->status;
+
```
Comment (yosefe) [inline src/ucp/wireup/wireup_cm.c:586]: remove space

File: src/ucs/async/async.h [hunk 12]
```diff
@@ -90,20 +90,44 @@ static inline int ucs_async_check_miss(ucs_async_context_t *async)
...
 }
 
+/**
+ * Returns whether a context blocked or not.
+ *
+ * @param async Event context to check `is_blocked` status for.
+ */
+static inline int ucs_async_is_blocked(const ucs_async_context_t *async)
+{
+    int is_blocked;
```
Comment (yosefe) [inline src/ucs/async/async.h:100]: no need for this local var
just return

File: src/ucs/async/thread.h [hunk 13]
```diff
@@ -9,13 +9,52 @@
 
 #include <ucs/type/spinlock.h>
 #include <ucs/sys/checker.h>
+#include <ucs/debug/assert.h>
+
+
+typedef struct ucs_async_thread_mutex {
```
Comment (yosefe) [inline src/ucs/async/thread.h:15]: IMO it's overkill to implement own mutex just for sake of assertion
we can check lock.__owner field, or just not check at all, and only the "spinlock" mode will have the assertion checks

**Review by yosefe — COMMENTED** [review]
maybe add simple test in test_async.cc: block a context and check it's locked.
should be true inside, false outside the scope

File: src/ucp/core/ucp_ep.h (hunk 9 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.h]: removed

File: src/ucs/async/thread.h (hunk 13 above)
Comment (dmitrygx) [reply src/ucs/async/thread.h:15]: fixed as discussed

File: src/ucp/core/ucp_ep.c (hunk 8 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.c]: done

File: src/ucs/async/thread.h [hunk 14]
```diff
@@ -9,13 +9,52 @@
...
+
+static UCS_F_ALWAYS_INLINE void
+ucs_recursive_mutex_block(ucs_async_thread_mutext_t *mutex)
+{
+    (void)pthread_mutex_lock(&mutex->lock);
+    ucs_assert((mutex->owner == UCS_THREAD_OWNER_NULL) ||
+               /* can be locked again by the same thread, because it is
+                * recursive mutex */
+               (ucs_recursive_mutex_is_locked(mutex) &&
+                (mutex->count > 0)));
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/async/thread.h]: removed

File: src/ucs/type/spinlock.h [hunk 15]
```diff
@@ -38,7 +38,7 @@ typedef struct ucs_recursive_spinlock {
     pthread_t      owner;
 } ucs_recursive_spinlock_t;
 
-#define UCS_SPINLOCK_OWNER_NULL ((pthread_t)-1)
+#define UCS_THREAD_OWNER_NULL ((pthread_t)-1)
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/type/spinlock.h]: done

File: src/ucp/core/ucp_ep.inl [hunk 16]
```diff
@@ -156,6 +156,14 @@ static UCS_F_ALWAYS_INLINE ucp_ep_ext_control_t* ucp_ep_ext_control(ucp_ep_h ep)
     return ucp_ep_ext_gen(ep)->control_ext;
 }
 
+static UCS_F_ALWAYS_INLINE void ucp_ep_update_flags(
+        ucp_ep_h ep, ucp_ep_flags_t flags_add, ucp_ep_flags_t flags_remove)
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucp/core/ucp_ep.inl]: done

File: src/ucs/async/thread.c [hunk 17]
```diff
@@ -355,12 +361,24 @@ ucs_async_thread_modify_event_fd(ucs_async_context_t *async, int event_fd,
 
 static int ucs_async_thread_mutex_try_block(ucs_async_context_t *async)
 {
-    return !pthread_mutex_trylock(&async->thread.mutex);
+    if (!pthread_mutex_trylock(&async->thread.mutex.lock)) {
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/async/thread.c]: done

File: src/ucs/async/thread.c [hunk 18]
```diff
@@ -355,12 +361,24 @@ ucs_async_thread_modify_event_fd(ucs_async_context_t *async, int event_fd,
...
+        /* locked */
+        if (async->thread.mutex.count++ == 0) {
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/async/thread.c]: anyway need to increment

File: src/ucs/async/thread.c [hunk 19]
```diff
@@ -355,12 +361,24 @@ ucs_async_thread_modify_event_fd(ucs_async_context_t *async, int event_fd,
...
+            async->thread.mutex.owner = pthread_self();
+        } else {
+            ucs_assert(ucs_recursive_mutex_is_locked(&async->thread.mutex));
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/async/thread.c]: removed

File: src/ucs/type/spinlock.h [hunk 20]
```diff
@@ -73,11 +73,18 @@ void ucs_spinlock_destroy(ucs_spinlock_t *lock);
...
 static inline int
-ucs_recursive_spin_is_owner(ucs_recursive_spinlock_t *lock, pthread_t self)
+ucs_recursive_spin_is_owner(const ucs_recursive_spinlock_t *lock,
+                            pthread_t self)
 {
     return lock->owner == self;
 }
 
+static inline int
+ucs_recursive_spin_is_locked(const ucs_recursive_spinlock_t *lock)
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/type/spinlock.h]: removed

File: src/ucs/async/thread.c [hunk 21]
```diff
@@ -293,10 +296,13 @@ static ucs_status_t ucs_async_thread_mutex_init(ucs_async_context_t *async)
...
 static void ucs_async_thread_mutex_cleanup(ucs_async_context_t *async)
 {
-    int ret = pthread_mutex_destroy(&async->thread.mutex);
+    int ret = pthread_mutex_destroy(&async->thread.mutex.lock);
 
     if (ret != 0) {
         ucs_warn("failed to destroy async lock: %s", strerror(ret));
+    } else {
+        ucs_assert(async->thread.mutex.owner == UCS_THREAD_OWNER_NULL);
+        ucs_assert(async->thread.mutex.count == 0);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/async/thread.c]: removed

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

File: src/ucs/async/thread.h [hunk 22]
```diff
@@ -14,46 +14,55 @@
 
 typedef struct ucs_async_thread_mutex {
     pthread_mutex_t lock;
+
```
Comment (yosefe) [inline src/ucs/async/thread.h:17]: minor: remove space line

File: src/ucs/async/thread.h [hunk 23]
```diff
@@ -14,46 +14,55 @@
...
 
 
 static UCS_F_ALWAYS_INLINE int
-ucs_recursive_mutex_is_locked(const ucs_async_thread_mutext_t *mutex)
+ucs_recursive_mutex_is_blocked(const ucs_async_thread_mutex_t *mutex)
 {
+#if UCS_ENABLE_ASSERT
     return mutex->owner == pthread_self();
+#else
+    ucs_fatal("must not be called without assertion");
```
Comment (yosefe) [inline src/ucs/async/thread.h:39]: maybe return 1?

File: test/gtest/ucs/test_async.cc [hunk 24]
```diff
@@ -313,11 +317,18 @@ class test_async_mt : public test_async {
     int thread_run(unsigned index) {
         LOCAL* le;
         m_ev[index] = le = new LOCAL(GetParam());
+  
+#if UCS_ENABLE_ASSERT
```
Comment (yosefe) [inline test/gtest/ucs/test_async.cc:321]: maybe move the ifdef inside is_blocked?
```
check_blocked(bool blocked) {
#ifdef ..
  EXPECT_EQ(blocked, ucs_async_is_blocked(..))
#endif
}
```

File: test/gtest/ucs/test_async.cc [hunk 25]
```diff
@@ -359,6 +374,29 @@ class test_async_mt : public test_async {
         return m_thread_counts[thread];
     }
 
+    void is_blocked_test()
+    {
+        spawn();
+        suspend();
+
+        if ((GetParam() == UCS_ASYNC_MODE_THREAD_SPINLOCK) ||
+            (GetParam() == UCS_ASYNC_MODE_THREAD_MUTEX)) {
```
Comment (yosefe) [inline test/gtest/ucs/test_async.cc:383]: why needed? can add comment?

File: test/gtest/ucs/test_async.cc [hunk 26]
```diff
@@ -603,6 +641,34 @@ UCS_TEST_P(test_async, warn_block) {
     }
 }
 
+#if UCS_ENABLE_ASSERT
```
Comment (yosefe) [inline test/gtest/ucs/test_async.cc:644]: why needed?

File: test/gtest/ucs/test_async.cc [hunk 27]
```diff
@@ -786,6 +852,14 @@ UCS_TEST_SKIP_COND_P(test_async_event_mt, multithread,
     EXPECT_GE(min_count, exp_min_count);
 }
 
+#if UCS_ENABLE_ASSERT
+UCS_TEST_SKIP_COND_P(test_async_event_mt, check_blocks_multithread,
+                     !(HAVE_DECL_F_SETOWN_EX))
```
Comment (yosefe) [inline test/gtest/ucs/test_async.cc:857]: why need to check HAVE_DECL_F_SETOWN_EX?
also, is_blocked_test is not needed both in timer and event
I think it should be under test_async fixture

File: test/gtest/ucs/test_async.cc (hunk 26 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_async.cc:644]: gtest can be compiled in release mode where this test will fail

File: test/gtest/ucs/test_async.cc (hunk 24 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_async.cc:321]: done

File: test/gtest/ucs/test_async.cc (hunk 25 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_async.cc:383]: done

File: test/gtest/ucs/test_async.cc (hunk 27 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_async.cc:857]: > why need to check HAVE_DECL_F_SETOWN_EX?

removed

> also, is_blocked_test is not needed both in timer and event

yes, it can be tested only once - done

> I think it should be under test_async fixture

it requires swan/stop infrastructure implemented in `test_asyn_mt<T>`

**Comment by dmitrygx** [comment]
@yosefe @brminich could you review pls?

File: src/ucs/async/thread.h (hunk 23 above)
Comment (yosefe) [reply src/ucs/async/thread.h:38]: ok

File: test/gtest/ucs/test_async.cc [hunk 28]
```diff
@@ -379,6 +380,9 @@ class test_async_mt : public test_async {
         spawn();
         suspend();
 
+        // The checking of is_blocked works only when async mode is THREAD
+        // (spinlock or mutext), because we rely on is_bloceked which can
+        // be changed by spawned threads
```
Comment (yosefe) [inline test/gtest/ucs/test_async.cc:385]: mutext->mutex
but is blocked still uses a counter right? are you sure it fails with other modes?
since other things in this function work, for example block()/unblock()

File: test/gtest/ucs/test_async.cc (hunk 26 above)
Comment (yosefe) [reply test/gtest/ucs/test_async.cc:648]: why would it fail? check_is_blocked is already NOP in release mode

File: test/gtest/ucs/test_async.cc (hunk 28 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_async.cc:385]: > 2\. why would it fail? don't we already run some other tests with multiple threads?

we run, but this test blocks async in two threads simultaneously - poll_block and signal don't allow it

Comment (yosefe) [reply test/gtest/ucs/test_async.cc:385]: i see, so pls add skip in `UCS_TEST_P(test_async_event_mt, check_blocks_multithread)` and write as a comment that "this test blocks async in two threads simultaneously - poll_block and signal don't allow it"

File: test/gtest/ucs/test_async.cc (hunk 26 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_async.cc]: need to use `check_is_blocked` here - done

File: test/gtest/ucs/test_async.cc (hunk 28 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_async.cc]: done

File: src/uct/tcp/tcp_sockcm_ep.c [hunk 29]
```diff
@@ -279,15 +279,14 @@ static void uct_tcp_sockcm_ep_mark_tx_completed(uct_tcp_sockcm_ep_t *cep)
...
- * This function should be called with the lock held.
- */
 ucs_status_t uct_tcp_sockcm_ep_progress_send(uct_tcp_sockcm_ep_t *cep)
 {
+    uct_tcp_sockcm_t UCS_V_UNUSED *tcp_sockcm = uct_tcp_sockcm_ep_get_cm(cep);
     ucs_status_t status;
     size_t sent_length;
     ucs_event_set_types_t events;
 
+    ucs_assert(ucs_async_is_blocked(tcp_sockcm->super.iface.worker->async));
```
Comment (yosefe) [inline src/uct/tcp/tcp_sockcm_ep.c:289]: can we use UCP_WORKER_THREAD_CS_CHECK_IS_BLOCKED here?

Comment (dmitrygx) [reply src/uct/tcp/tcp_sockcm_ep.c:289]: we can't use UCP macro in UCT code

**Review by yosefe — APPROVED** [review]

**Review by brminich — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe @brminich it seems readthedocs hangs
can we merge or retrigger docs build somehow?

**Comment by dmitrygx** [comment]
@yosefe ok to merge?

**Review by yosefe — APPROVED** [review]
