### PR TITLE
UCT/UCP/GTEST: Fix expected status in peer failure tests

### LINKED ISSUE #6203: dcx/test_ucp_peer_failure.zcopy/3 failed on swx-rdmz-ucx-arm-hwi
```
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from dcx/test_ucp_peer_failure
[ RUN      ] dcx/test_ucp_peer_failure.zcopy/3 <dc_x/rma_fail_imm>
[New Thread 0xfffff6d1f140 (LWP 55770)]
[Thread 0xfffff6d1f140 (LWP 55770) exited]
[New Thread 0xfffff6d1f140 (LWP 55778)]
[     INFO ] < request 0xaaaaac408ec0 completed with error Request canceled >
ucp/test_ucp_peer_failure.cc:332: Failure
Value of: status
  Actual: -16
Expected: m_err_status
Which is: -80
```
the issue was reproduced locally on `swx-rdmz-ucx-arm-hwi` and during Azure CI testing

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix expected status in peer failure tests.

## Why ?

Fixes #6203
Flow:
0. Error handling was called for the test due to KEEPALIVE, the status of failure is `UCS_ERR_ENDPOINT_TIMEOUT`.
1. CQ returns Work Completion Element (WCE) with WR_FLUSH_ERR syndrome for send operation after the receiver was destroyed.
2. uct_rc_verbs_wc_to_ucs_status()/uct_ib_mlx5_completion_with_err() returns `UCS_ERR_CANCELED` for this error.
3. UCP send request completed with `UCS_ERR_CANCLED` status.
4. But gtest expects that UCP send request's completion status will be the same as in error handling callback, i.e. `UCS_ERR_ENDPOINT_TIMEOUT`.

## How ?

1. Removed unreachable code in `uct_ib_mlx5_completion_with_err()` function, it checks `MLX5_CQE_SYNDROME_WR_FLUSH_ERR` syndrome twice.
2. Updated `test_ucp_peer_failure::do_test()`  main function to expect that UCP send request's completion status will be either the same as returned in an error callback (i.e. `UCS_ERR_ENDPOINT_TIMEOUT`) or `UCS_ERR_CANCELED`.

### CODE REVIEW

**Comment by dmitrygx** [comment]
the failure is #6220

**Review by brminich — APPROVED** [review]

File: src/uct/ib/mlx5/ib_mlx5_log.c [hunk 1]
```diff
@@ -86,9 +86,6 @@ ucs_status_t uct_ib_mlx5_completion_with_err(uct_ib_iface_t *iface,
     case MLX5_CQE_SYNDROME_LOCAL_PROT_ERR:
         snprintf(err_info, sizeof(err_info), "Local protection");
         break;
-    case MLX5_CQE_SYNDROME_WR_FLUSH_ERR:
-        snprintf(err_info, sizeof(err_info), "WR flushed because QP in error state");
-        break;
```
Comment (yosefe) [inline src/uct/ib/mlx5/ib_mlx5_log.c:91]: maybe move code from 74-76 in this case ? and remove the if?

Comment (dmitrygx) [reply src/uct/ib/mlx5/ib_mlx5_log.c]: done

File: src/uct/ib/mlx5/ib_mlx5_log.c [hunk 2]
```diff
@@ -86,6 +81,12 @@ ucs_status_t uct_ib_mlx5_completion_with_err(uct_ib_iface_t *iface,
     case MLX5_CQE_SYNDROME_LOCAL_PROT_ERR:
         snprintf(err_info, sizeof(err_info), "Local protection");
         break;
+    case MLX5_CQE_SYNDROME_WR_FLUSH_ERR:
+        snprintf(err_info, sizeof(err_info),
+                 "WR flushed because QP in error state");
+        log_level = UCS_LOG_LEVEL_TRACE;
+        status    = UCS_ERR_CANCELED;
+        break;
```
Comment (yosefe) [inline src/uct/ib/mlx5/ib_mlx5_log.c]: maybe add ucs_log_is_enabled(log_level) in line 127

**Review by brminich — APPROVED** [review]

File: src/uct/ib/mlx5/ib_mlx5_log.c (hunk 2 above)
Comment (dmitrygx) [reply src/uct/ib/mlx5/ib_mlx5_log.c]: done

File: src/uct/ib/mlx5/ib_mlx5_log.c [hunk 3]
```diff
@@ -124,6 +124,10 @@ ucs_status_t uct_ib_mlx5_completion_with_err(uct_ib_iface_t *iface,
         break;
     }
 
+    if (!ucs_log_is_enabled(log_level)) {
+        goto out;
```
Comment (yosefe) [inline src/uct/ib/mlx5/ib_mlx5_log.c:128]: minor: return status ?

**Review by yosefe — APPROVED** [review]
pls disregard prev comment

**Comment by dmitrygx** [comment]
CI failure was #6161 (will be fixed by #6190 - it wasn't merged yet)
