### PR TITLE
UCP/AM: Use correct ep for short send with reply

### LINKED ISSUE #6394: First AM with TLS posix get's dropped on 1.10-rc4
### Describe the bug
The first active message that is send with `UCP_AM_SEND_FLAG_REPLY` after wireup is dropped.

I am sending active messages with `UCP_AM_SEND_FLAG_REPLY` using UCX 1.10-rc4 and I observe the following:

```
    From worker 2:	[1614131887.522129] [odin:768998:0]       mm_iface.c:232  UCX  DATA  RX: AM_SHORT am_id 26 len 24 
      From worker 2:	[1614131887.522130] [odin:768998:0]         ucp_am.c:1181 UCX  DATA  worker 0x2124f80: ep id 0xffffffffffffffff was not found, dropAM (reply proto)
      From worker 2:	[1614131887.522132] [odin:768998:0]     ucp_worker.c:738  UCX  TRACE wiface 0x18c8460 progress returned 2, but no active messages were received
```
The full log is attached here: https://gist.github.com/vchuravy/bcffcc5a9d6e5b2af9ca6284ce0df797

Subsequent messages are received.

### Steps to Reproduce
- Command line
- 1.10-rc4
```
# UCT version=1.10.0 revision 
# configured with: --prefix=/workspace/destdir --build=x86_64-linux-musl --host=x86_64-linux-gnu --disable-debug --disable-assertions --disable-params-check --disable-static --disable-profiling --enable-shared --enable-mt --enable-frame-pointer --enable-cma --with-rdmacm=/workspace/destdir --with-cuda=/workspace/destdir/cuda --with-rocm=/workspace/destdir
```
- `UCX_TLS=posix,self`

I haven't written a reproducer in C, and found this while working on the Julia bindings for UCX.
My test case can be found here https://github.com/JuliaParallel/UCX.jl/pull/34/commits/97dca1496cef285d8053dcfdb1bc01f723df4dbe

### PR DESCRIPTION
**Pull request by brminich**
## What
Use correct ep for sending short AM with reply protocol

## Why ?
Fixes #6394

### CODE REVIEW

File: test/gtest/ucp/test_ucp_am.cc [hunk 1]
```diff
@@ -772,19 +772,38 @@ class test_ucp_am_nbx_dts : public test_ucp_am_nbx {
...
     {
         add_variant_values(variants, get_test_dts, 0);
         add_variant_values(variants, get_test_dts, UCP_AM_SEND_REPLY, "reply");
     }
 
+    static void get_test_variants(std::vector<ucp_test_variant>& variants)
+    {
+        add_variant_values(variants, get_test_dts_reply, 0);
+        add_variant_values(variants, get_test_dts_reply,
+                           UCP_EP_PARAM_FIELD_ERR_HANDLING_MODE, "errh");
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_am.cc:804]: can we pass UCP_ERR_HANDLING_MODE_PEER / UCP_ERR_HANDLING_MODE_NONE as the variant values?

File: test/gtest/ucp/test_ucp_am.cc [hunk 2]
```diff
@@ -772,19 +772,38 @@ class test_ucp_am_nbx_dts : public test_ucp_am_nbx {
                                        UCS_BIT(UCP_DATATYPE_IOV) |
                                        UCS_BIT(UCP_DATATYPE_GENERIC);
 
+    virtual ucp_ep_params_t get_ep_params()
+    {
+        ucp_ep_params_t ep_params    = test_ucp_am_nbx::get_ep_params();
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_am.cc:777]: minor: excess space

File: test/gtest/ucp/test_ucp_am.cc [hunk 3]
```diff
@@ -772,19 +772,38 @@ class test_ucp_am_nbx_dts : public test_ucp_am_nbx {
...
+
+        ep_params.field_mask |= UCP_EP_PARAM_FIELD_ERR_HANDLING_MODE;
+        ep_params.err_mode    = static_cast<ucp_err_handling_mode_t>(
+                                                          get_variant_value(2));
+
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_am.cc:782]: minor: excess space line

**Review by yosefe — APPROVED** [review]
pls port to 1.10.x as well
