### PR TITLE
UCS/ARBITER: Fix purge bug

### LINKED ISSUE #3259: [mtt] segfault in many tests with TLS=rc
Configuration
```
OMPI: 4.0.1rc1
MOFED: MLNX_OFED_LINUX-4.5-1.0.1.0
Module: hpcx-gcc (2019-02-23)
Test module: mtt-tests/hpcx-gcc
Nodes: hercules x8 (ppn=32(x8), nodelist=clx-hercules-[087-094])
Job: ucx-hwtm-rc
```

MTT log: http://e2e-gw.mellanox.com:4080/hpc/scrap/users/mtt/scratch/ucx_ompi/20190223_204135_11069_314975_clx-hercules-087/html/test_stdout_BVIgpN.txt

Works OK with `rc_x`, `dc/dc_x`, `ud/ud_x`.

Cmd (orig `np` was 256):
`mpirun -np 64 --report-bindings -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_2:1 -mca osc ucx -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc,self,sm -x UCX_RC_VERBS_TM_ENABLE=y -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/local/benchmarks/hpcx_install_2019-02-23/mtt-tests-gcc/installs/qQmc/tests/ibm-tests/ompi-tests/ibm/pt2pt/test1`

```sh
Sat Feb 23 20:47:48 2019[1,109]<stderr>:[clx-hercules-092:5133 :0:5133] address not mapped to object
Sat Feb 23 20:47:48 2019[1,69]<stderr>:[clx-hercules-092:5128 :0:5128] address not mapped to object
Sat Feb 23 20:47:48 2019[1,109]<stderr>:==== backtrace ====
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 0 0x0000000000043140 ucs_list_insert_replace()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/list.h:47
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 1 0x000000000003e889 ucs_arbiter_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/arbiter.h:318
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 2 0x0000000000038fcf uct_ud_iface_async_progress()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.c:831
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 3 0x000000000003c19f __ucs_async_poll_missed()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/async/async.c:579
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 4 0x0000000000019103 ucs_async_check_miss()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/async/async.h:78
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 5 0x000000000000540a mca_pml_ucx_send_nbr()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/pml/ucx/pml_ucx.c:817
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 6 0x000000000008fc28 ompi_coll_base_sendrecv_zero()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/coll_base_barrier.c:60
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 7 0x000000000005f928 PMPI_Barrier()  /hpc/local/benchmarks/hpcx_install_2019-02-23/src/hpcx-gcc-redhat7.4/ompi/ompi/mpi/c/profile/pbarrier.c:74
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 8 0x0000000000401069 main()  /hpc/local/benchmarks/hpcx_install_2019-02-23/mtt-tests-gcc/installs/qQmc/tests/ibm-tests/ompi-tests/ibm/pt2pt/test1.c:74
Sat Feb 23 20:47:48 2019[1,109]<stderr>: 9 0x00000000000223d5 __libc_start_main()  ???:0
Sat Feb 23 20:47:48 2019[1,109]<stderr>:10 0x0000000000400e49 _start()  ???:0
Sat Feb 23 20:47:48 2019[1,109]<stderr>:===================Sat Feb 23 20:47:48 2019[1,69]<stderr>:==== backtrace ====
```

### PR DESCRIPTION
**Pull request by brminich**
## What
Fixes #3259 bug, introduced in #3239. 

## How ?
If the currently scheduled group changes its head, arbiter pointer should be updated accordingly

### CODE REVIEW

File: src/ucs/datastruct/arbiter.c [hunk 1]
```diff
@@ -141,11 +141,17 @@ void ucs_arbiter_group_purge(ucs_arbiter_t *arbiter,
...
                 next_group->list.prev = &prev_group->list;
+                if (arbiter->current == orig_head) {
+                    arbiter->current = next_group;
+                }
             } else if (orig_head != head) {
                 /* keep the group scheduled, but with new head element */
                 ucs_list_insert_replace(&prev_group->list,
                                         &next_group->list,
                                         &head->list);
+                if (arbiter->current == orig_head) {
```
Comment (yosefe) [inline src/ucs/datastruct/arbiter.c]: can this 'if' be moved outside if/else?

Comment (brminich) [reply src/ucs/datastruct/arbiter.c]: we do not to change arbiter if the head is not changed. We can, but then we would need to add another alse branch with return statement.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8931/ for details (Mellanox internal link).
