### PR TITLE
UCT/DC: Fix number of CQEs for DCI pools

### LINKED ISSUE #6579: [mtt] Hung on UCX-CX6. test - mpi_test_suite
Configuration
```
OMPI: 4.1.1rc1
MOFED: MLNX_OFED_LINUX-5.1-2.5.8.0
Module: hpcx-gcc (2021-03-27)
Test module: mtt-tests/hpcx-gcc
Nodes: jazz x3 (ppn=28(x3), nodelist=jazz[03,07,20])
```
 
MTT log:
http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/ucx_ompi/20210327_113416_27583_31188_jazz03.swx.labs.mlnx/html/test_stdout_Nb7o4m.txt
 
Cmd:
`/hpc/local/benchmarks/daily/next/2021-03-27/hpcx-gcc-redhat7.6/ompi/bin/mpirun -np 84 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' -x UCX_ERROR_SIGNALS=SIGILL,SIGSEGV,SIGBUS,SIGFPE,SIGABRT -x UCX_HANDLE_ERRORS=bt -x UCX_IB_PCI_RELAXED_ORDERING=off --bind-to core -x UCX_NET_DEVICES=mlx5_0:1,mlx5_4:1 -mca osc ucx -x UCX_IB_ADDR_TYPE=ib_global -x UCX_IB_REG_METHODS=rcache,direct -x UCX_UD_TIMEOUT=10m -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 -x UCX_IB_NUM_PATHS=4 -x UCX_MAX_EAGER_LANES=4 -x UCX_MAX_RNDV_LANES=4 --map-by node /hpc/local/benchmarks/daily/next/2021-03-27/mtt-tests-gcc/installs/kgJN/tests/mpi-test-suite/ompi-tests/mpi_test_suite/mpi_test_suite -x relaxed -t 'All,^One-sided,^IO,^Environment' -n 300`
 
Output:
```sh
node=jazz03, pid=69634:
Thread 4 (Thread 0x7f21bbe39700 (LWP 69651)):
#0  0x00007f21bf7ad483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f21bef64133 in epoll_dispatch (base=0x1831a10, tv=<optimized out>) at epoll.c:407
#2  0x00007f21bef67b80 in opal_libevent2022_event_base_loop (base=0x1831a10, flags=flags@entry=1) at event.c:1630
#3  0x00007f21bef2246e in progress_engine (obj=<optimized out>) at runtime/opal_progress_threads.c:105
#4  0x00007f21bfa83dd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f21bf7acead in clone () from /lib64/libc.so.6
Thread 3 (Thread 0x7f21b8825700 (LWP 69660)):
#0  0x00007f21bf7ad483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f21bef64133 in epoll_dispatch (base=0x1857670, tv=<optimized out>) at epoll.c:407
#2  0x00007f21bef67b80 in opal_libevent2022_event_base_loop (base=0x1857670, flags=flags@entry=1) at event.c:1630
#3  0x00007f21baf6e34e in progress_engine (obj=<optimized out>) at runtime/pmix_progress_threads.c:232
#4  0x00007f21bfa83dd5 in start_thread () from /lib64/libpthread.so.0
#5  0x00007f21bf7acead in clone () from /lib64/libc.so.6
Thread 2 (Thread 0x7f21abfff700 (LWP 69677)):
#0  0x00007f21bf7ad483 in epoll_wait () from /lib64/libc.so.6
#1  0x00007f21b13d6bcc in ucs_event_set_wait (event_set=<optimized out>, num_events=num_events@entry=0x7f21abffeec0, timeout_ms=<optimized out>, event_set_handler=event_set_handler@entry=0x7f21b13c0f00 <ucs_async_thread_ev_handler>, arg=arg@entry=0x7f21abffeed0) at sys/event_set.c:198
#2  0x00007f21b13c125c in ucs_async_thread_func (arg=0x18e51a0) at async/thread.c:130
#3  0x00007f21bfa83dd5 in start_thread () from /lib64/libpthread.so.0
#4  0x00007f21bf7acead in clone () from /lib64/libc.so.6
Thread 1 (Thread 0x7f21c0190740 (LWP 69634)):
#0  0x00007f21b16ff9df in uct_mm_iface_fifo_has_new_data (iface=0x1960020) at sm/mm/base/mm_iface.c:279
#1  uct_mm_iface_poll_fifo (iface=0x1960020) at sm/mm/base/mm_iface.c:286
#2  uct_mm_iface_progress (tl_iface=0x1960020) at sm/mm/base/mm_iface.c:348
#3  0x00007f21b194a782 in ucs_callbackq_dispatch (cbq=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/ucs/datastruct/callbackq.h:211
#4  uct_worker_progress (worker=<optimized out>) at /build-result/src/hpcx-gcc-redhat7.6/ucx-master/src/uct/api/uct.h:2559
#5  ucp_worker_progress (worker=0x1940bb0) at core/ucp_worker.c:2451
#6  0x00007f21bef1c5dc in opal_progress () at runtime/opal_progress.c:231
#7  0x00007f21bfce50d5 in ompi_request_wait_completion (req=0x214a240) at ../ompi/request/request.h:415
#8  ompi_request_default_wait (req_ptr=0x7ffd8d3d6360, status=0x0) at request/req_wait.c:42
#9  0x00007f21bfd1b2ca in ompi_coll_base_bcast_intra_generic (buffer=<optimized out>, original_count=<optimized out>, datatype=<optimized out>, root=<optimized out>, comm=<optimized out>, module=<optimized out>, count_by_segment=300, tree=0x1bb11b0) at base/coll_base_bcast.c:210
#10 0x00007f21aa385c29 in ompi_coll_tuned_bcast_intra_dec_fixed (buff=<optimized out>, count=<optimized out>, datatype=<optimized out>, root=<optimized out>, comm=<optimized out>, module=<optimized out>) at coll_tuned_decision_fixed.c:649
#11 0x00007f21bfcf8351 in PMPI_Bcast (buffer=<optimized out>, count=<optimized out>, datatype=<optimized out>, root=<optimized out>, comm=0x6564e0 <ompi_mpi_comm_world>) at pbcast.c:114
#12 0x0000000000406a19 in tst_coll_bcast_run (env=0x7ffd8d3d6790) at coll/tst_coll_bcast.c:72
#13 0x0000000000436a24 in tst_test_run_func (env=0x7ffd8d3d6790) at tst_tests.c:1461
#14 0x0000000000412dc1 in main (argc=7, argv=0x7ffd8d3d6a48) at mpi_test_suite.c:636

```

### PR DESCRIPTION
**Pull request by brminich**
## What
Provide correct number of DC CQEs to CQ creation (and tx ops) routines, taking into account number of DCI pools.

Fixes #6579

### CODE REVIEW

**Review by hoopoepg — APPROVED** [review]

File: src/uct/ib/dc/dc_mlx5.c [hunk 1]
```diff
@@ -1218,30 +1220,34 @@ static UCS_CLASS_INIT_FUNC(uct_dc_mlx5_iface_t, uct_md_h tl_md, uct_worker_h wor
     }
 
     init_attr.qp_type     = UCT_IB_QPT_DCI;
-    init_attr.flags       = UCT_IB_CQ_IGNORE_OVERRUN;
+    init_attr.flags       = UCT_IB_CQ_IGNORE_OVERRUN |
+                            UCT_IB_TX_OPS_PER_PATH;
```
Comment (yosefe) [inline src/uct/ib/dc/dc_mlx5.c:1224]: instead of passing UCT_IB_TX_OPS_PER_PATH, can't we just update the calculation in line 1231-1233 below?

Comment (brminich) [reply src/uct/ib/dc/dc_mlx5.c:1224]: how can we update it?
ib_num_path will be initialized only in IB iface constructor, while we have to pass some CQ length to it as a parameter

Comment (yosefe) [reply src/uct/ib/dc/dc_mlx5.c:1224]: i see, maybe worth to comment this reason when passing this flag in dc_mlx5 code?

Comment (brminich) [reply src/uct/ib/dc/dc_mlx5.c:1224]: ok

**Comment by brminich** [comment]
@Artemy-Mellanox, can you please take a look?

**Review by Artemy-Mellanox — APPROVED** [review]

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Review by dmitrygx — APPROVED** [review]
