### PR TITLE
UCP/PROTO/UCT/TCP: Fix error handling in case of AM Zcopy failed

### LINKED ISSUE #5704: failure in tcp/test_ucp_peer_failure.zcopy/1
### Describe the bug
Happened here: http://hpc-master.lab.mtl.com:8080/blue/organizations/jenkins/ucx/detail/ucx/7119/pipeline/

```
[2020-09-16T09:40:00.862Z] [ RUN      ] tcp/test_ucp_peer_failure.zcopy/1 <tcp>
[2020-09-16T09:40:01.118Z] [     INFO ] < tcp_ep 0x1002d9abf90 (state=CONNECTED): send(31) failed: Connection reset by remote peer >
[2020-09-16T09:55:08.558Z] /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/test_helpers.cc:48: Failure
[2020-09-16T09:55:08.558Z] Failed
[2020-09-16T09:55:08.558Z] Connection timed out - abort testing
[2020-09-16T09:55:08.558Z] [r-vmb-ppc-jenkins:18870:0:18870] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
[2020-09-16T09:55:08.558Z] 
[2020-09-16T09:55:08.558Z] /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/api/uct.h: [ uct_ep_am_zcopy() ]
[2020-09-16T09:55:08.558Z]       ...
[2020-09-16T09:55:08.558Z]      2665                                             uct_completion_t *comp)
[2020-09-16T09:55:08.558Z]      2666 {
[2020-09-16T09:55:08.558Z]      2667     return ep->iface->ops.ep_am_zcopy(ep, id, header, header_length, iov, iovcnt,
[2020-09-16T09:55:08.558Z] ==>  2668                                       flags, comp);
[2020-09-16T09:55:08.558Z]      2669 }
[2020-09-16T09:55:08.558Z]      2670 
[2020-09-16T09:55:08.558Z]      2671 /**
[2020-09-16T09:55:08.558Z] 
[2020-09-16T09:55:08.558Z] ==== backtrace (tid:  18870) ====
[2020-09-16T09:55:08.558Z]  0 0x000000000005eba8 ucs_debug_print_backtrace()  /scrap/jenkins/workspace/ucx-3/contrib/../src/ucs/debug/debug.c:656
[2020-09-16T09:55:08.558Z]  1 0x0000000000078884 uct_ep_am_zcopy()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/api/uct.h:2668
[2020-09-16T09:55:08.558Z]  2 0x0000000000078884 ucp_do_am_zcopy_multi()  /scrap/jenkins/workspace/ucx-3/contrib/../src/ucp/proto/proto_am.inl:380
[2020-09-16T09:55:08.558Z]  3 0x0000000000078884 ucp_tag_eager_zcopy_multi()  /scrap/jenkins/workspace/ucx-3/contrib/../src/ucp/tag/eager_snd.c:186
[2020-09-16T09:55:08.558Z]  4 0x000000000002592c uct_tcp_ep_pending_queue_dispatch()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/tcp/tcp_ep.c:497
[2020-09-16T09:55:08.558Z]  5 0x000000000002d978 uct_tcp_cm_change_conn_state()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/tcp/tcp_cm.c:49
[2020-09-16T09:55:08.558Z]  6 0x000000000002e3d4 uct_tcp_cm_handle_conn_ack()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/tcp/tcp_cm.c:544
[2020-09-16T09:55:08.558Z]  7 0x000000000002e610 uct_tcp_cm_handle_conn_pkt()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/tcp/tcp_cm.c:568
[2020-09-16T09:55:08.558Z]  8 0x0000000000027980 uct_tcp_ep_progress_am_rx()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/tcp/tcp_ep.c:1004
[2020-09-16T09:55:08.558Z]  9 0x0000000000027980 uct_tcp_ep_progress_data_rx()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/tcp/tcp_ep.c:1079
[2020-09-16T09:55:08.558Z] 10 0x000000000002b784 uct_tcp_iface_handle_events()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/tcp/tcp_iface.c:205
[2020-09-16T09:55:08.558Z] 11 0x000000000006fbcc ucs_event_set_wait()  /scrap/jenkins/workspace/ucx-3/contrib/../src/ucs/sys/event_set.c:213
[2020-09-16T09:55:08.558Z] 12 0x000000000002acec uct_tcp_iface_progress()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/tcp/tcp_iface.c:222
[2020-09-16T09:55:08.558Z] 13 0x0000000000040b34 ucs_callbackq_dispatch()  /scrap/jenkins/workspace/ucx-3/contrib/../src/ucs/datastruct/callbackq.h:211
[2020-09-16T09:55:08.558Z] 14 0x0000000000040b34 uct_worker_progress()  /scrap/jenkins/workspace/ucx-3/contrib/../src/uct/api/uct.h:2405
[2020-09-16T09:55:08.558Z] 15 0x0000000000040b34 ucp_worker_progress()  /scrap/jenkins/workspace/ucx-3/contrib/../src/ucp/core/ucp_worker.c:2191
[2020-09-16T09:55:08.558Z] 16 0x00000000105dbf5c ucp_test_base::entity::progress()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/ucp/ucp_test.cc:764
[2020-09-16T09:55:08.558Z] 17 0x00000000105dc060 ucp_test::progress()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/ucp/ucp_test.cc:147
[2020-09-16T09:55:08.558Z] 18 0x000000001041666c test_ucp_peer_failure::do_test()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/ucp/test_ucp_peer_failure.cc:341
[2020-09-16T09:55:08.558Z] 19 0x0000000010203708 ucs::test_base::run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/test.cc:311
[2020-09-16T09:55:08.558Z] 20 0x0000000010203708 ucs::test_base::TestBodyProxy()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/test.cc:337
[2020-09-16T09:55:08.558Z] 21 0x00000000103d0210 ucp_test::TestBody()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/ucp/ucp_test.h:174
[2020-09-16T09:55:08.558Z] 22 0x00000000101dc61c HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3562
[2020-09-16T09:55:08.558Z] 23 0x00000000101dc61c testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3598
[2020-09-16T09:55:08.558Z] 24 0x00000000101cb7ac testing::Test::Run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3635
[2020-09-16T09:55:08.558Z] 25 0x00000000101cb90c testing::TestInfo::Run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3812
[2020-09-16T09:55:08.558Z] 26 0x00000000101cbb58 testing::TestCase::Run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3930
[2020-09-16T09:55:08.558Z] 27 0x00000000101d1b58 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:5808
[2020-09-16T09:55:08.558Z] 28 0x00000000101d1fa4 testing::internal::UnitTestImpl::RunAllTests()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:5725
[2020-09-16T09:55:08.558Z] 29 0x00000000101d1fa4 HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3562
[2020-09-16T09:55:08.558Z] 30 0x00000000101d1fa4 HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:3598
[2020-09-16T09:55:08.558Z] 31 0x00000000101d1fa4 testing::UnitTest::Run()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest-all.cc:5422
[2020-09-16T09:55:08.558Z] 32 0x000000001014f328 RUN_ALL_TESTS()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/gtest.h:20059
[2020-09-16T09:55:08.558Z] 33 0x000000001014f328 main()  /scrap/jenkins/workspace/ucx-3/contrib/../test/gtest/common/main.cc:102
[2020-09-16T09:55:08.558Z] 34 0x0000000000025100 generic_start_main.isra.0()  libc-start.c:0
[2020-09-16T09:55:08.558Z] 35 0x00000000000252f4 __libc_start_main()  ???:0
[2020-09-16T09:55:08.558Z] =================================
[2020-09-16T09:55:08.558Z] Sending notification to mikhailb@nvidia.com
[2020-09-16T09:55:08.558Z] [r-vmb-ppc-jenkins:18870:0:18870] Process frozen...
[2020-09-16T11:58:21.699Z] make: *** [test] Terminated
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix error handling in case of AM Zcopy failed

## Why ?

1. If EP AM Zcopy operation failed in-place (i.e. error was returned from `uct_ep_am_zcopy()`), UCP has to complete the request.
2. TCP has to return the same error from the EP send operation as it passes to the user error handling callback, i.e. `UCS_ERR_ENDPOINT_TIMEOUT`.

Fixes #5704

## How ?

1. Call user completion calbback if error was returned from `uct_ep_am_zcopy()` in-place.
2. Translate error status to `UCS_ERR_ENDPOINT_TIMEOUT` if error callback was specified by the user.

### CODE REVIEW

**Comment by dmitrygx** [comment]
#5710 and #5697 are solutions to fix #5704 issue

File: src/uct/tcp/tcp_ep.c [hunk 1]
```diff
@@ -610,6 +642,7 @@ static inline ssize_t uct_tcp_ep_sendv(uct_tcp_ep_t *ep)
             return 0;
         }
 
+        status = uct_tcp_ep_handle_send_err(ep, status);
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:645]: we we can both return error here, and also invoke completion?

File: src/uct/tcp/tcp_ep.c [hunk 2]
```diff
@@ -584,6 +615,7 @@ static inline ssize_t uct_tcp_ep_send(uct_tcp_ep_t *ep)
                                 &sent_length);
     if (ucs_unlikely((status != UCS_OK) &&
                      (status != UCS_ERR_NO_PROGRESS))) {
+        uct_tcp_ep_handle_send_err(ep, status);
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:618]: should we use the return value of uct_tcp_ep_handle_send_err()?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: done

File: src/uct/tcp/tcp_ep.c (hunk 1 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: done

File: src/uct/tcp/tcp_ep.c [hunk 3]
```diff
@@ -625,6 +624,16 @@ static inline ssize_t uct_tcp_ep_send(uct_tcp_ep_t *ep)
     return sent_length;
 }
 
+static inline ssize_t uct_tcp_ep_zcopy_complete_err(uct_tcp_ep_t *ep,
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:627]: we should not invoke completion in case we already return error

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c:627]: `uct_tcp_ep_sendv()` is only called from the progress function

File: src/uct/tcp/tcp_ep.c [hunk 4]
```diff
@@ -571,6 +571,37 @@ static void uct_tcp_ep_handle_disconnected(uct_tcp_ep_t *ep, ucs_status_t status
...
+        }
+    } else {
+        uct_tcp_ep_handle_disconnected(ep, status);
+        if (iface->super.err_handler != NULL) {
+            /* Translate the error to EP timeout error, since user expects that
+             * status returned from UCT error callback is the same as it is
+             * returned from the UCT EP send operation (or from UCT competion
+             * callback)
+             * TODO: revise this behavior */
+            return UCS_ERR_ENDPOINT_TIMEOUT;
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:598]: maybe uct_tcp_ep_set_failed should pass the status instead of always passing UCS_ERR_ENDPOINT_TIMEOUT?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c:598]: unfortunately, our gtests expect `UCS_ERR_ENDPOINT_TIMEOUT` and then replaced function pointers return `UCS_ERR_ENDPOINT_TIMEOUT`

Comment (yosefe) [reply src/uct/tcp/tcp_ep.c:598]: ok

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe ok to merge?
