### PR TITLE
UCS/MEMTYPE_CACHE: Align regions by Page Table alignment

### LINKED ISSUE #4222: Still seeing issues with UCX_MEMTYPE_CACHE
Hi,

I'm seeing issues with `memtype_cache` usage where pointers are detected incorrectly. I'm using `ucx_perftest` to provide a repro but I've seen the issue with multiple other tests (IMB/OMB). I'm using the following configuration at commit c0e2625 (ToT master at posting time):
```
# UCT version=1.8.0 revision c0e2625
# configured with: --prefix=$PWD --with-gdrcopy=/usr/local --enable-debug --enable-logging --with-cuda=/usr/local/cuda --enable-profiling --enable-frame-pointer --enable-stats --enable-memtrack --enable-fault-injection --enable-debug-data --enable-mt --with-java=no --enable-gtest --with-valgrind=$VALGRIND_HOME --enable-examples
```

I run ucx_perftest on the same node where there are at least two GPUs:
```
$ ucx_perftest -t tag_bw -m cuda -n 100 -s 1000000 &
$ ucx_perftest dgx03 -t tag_bw -m cuda -n 100 -s 1000000
[1569346885.084612] [dgx03:42393:0]       perftest.c:1376 UCX  WARN  CPU affinity is not set (bound to 40 cpus). Performance may
 be impacted.
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
+------------------------------------------------------------------------------------------+
| API:          protocol layer                                                             |
| Test:         tag match bandwidth                                                        |
| Data layout:  (automatic)                                                                |
| Message size: 1000000                                                                    |
+------------------------------------------------------------------------------------------+
[1569346886.433939] [dgx03:42393:0]        knem_md.c:126  UCX  ERROR KNEM create region failed: Bad address
[1569346886.433962] [dgx03:42393:0]         ucp_mm.c:116  UCX  ERROR failed to register address 0x2b37aba00000 length 1000000 on
 md[14]=knem: Input/output error
[1569346886.433968] [dgx03:42393:0]    ucp_request.c:268  UCX  ERROR failed to register user buffer datatype 0x8 address 0x2b37a
ba00000 len 1000000: Input/output error
[1569346886.433987] [dgx03:42393:0]        knem_md.c:126  UCX  ERROR KNEM create region failed: Bad address
[1569346886.433990] [dgx03:42393:0]         
...
ba00000 len 1000000: Input/output error
[1569346886.434058] [dgx03:42393:0]        knem_md.c:126  UCX  ERROR KNEM create region failed: Bad address
[1569346886.434061] [dgx03:42393:0]         ucp_mm.c:116  UCX  ERROR failed to register address 0x2b37aba00000 length 1000000 on
 md[14]=knem: Input/output error
[1569346886.434064] [dgx03:42393:0]    ucp_request.c:268  UCX  ERROR failed to register user buffer datatype 0x8 address 0x2b37a
ba00000 len 1000000: Input/output error
[1569346886.434075] [dgx03:42393:0]        knem_md.c:126  UCX  ERROR KNEM create region failed: Bad address
[1569346886.434078] [dgx03:42393:0]         ucp_mm.c:116  UCX  ERROR failed to register address 0x2b37aba00000 length 1000000 on
 md[14]=knem: Input/output error
[1569346886.434081] [dgx03:42393:0]    ucp_request.c:268  UCX  ERROR failed to register user buffer datatype 0x8 address 0x2b37a
ba00000 len 1000000: Input/output error
[1569346886.434092] [dgx03:42393:0]        knem_md.c:126  UCX  ERROR KNEM create region failed: Bad address
[1569346886.434096] [dgx03:42393:0]         ucp_mm.c:116  UCX  ERROR failed to register address 0x2b37aba00000 length 1000000 on
 md[14]=knem: Input/output error
[1569346886.434098] [dgx03:42393:0]    ucp_request.c:268  UCX  ERROR failed to register user buffer datatype 0x8 address 0x2b37a
ba00000 len 1000000: Input/output error
[1569346886.434109] [dgx03:42393:0]        knem_md.c:126  UCX  ERROR KNEM create region failed: Bad address
[1569346886.434112] [dgx03:42393:0]         ucp_mm.c:116  UCX  ERROR failed to register address 0x2b37aba00000 length 1000000 on
 md[14]=knem: Input/output error
[1569346886.434115] [dgx03:42393:0]    ucp_request.c:268  UCX  ERROR failed to register user buffer datatype 0x8 address 0x2b37a
ba00000 len 1000000: Input/output error
[1569346886.434126] [dgx03:42393:0]        knem_md.c:126  UCX  ERROR KNEM create region failed: Bad address
[1569346886.434129] [dgx03:42393:0]         ucp_mm.c:116  UCX  ERROR failed to register address 0x2b37aba00000 length 1000000 on md[14]=knem: Input/output error
[1569346886.434132] [dgx03:42393:0]    ucp_request.c:268  UCX  ERROR failed to register user buffer datatype 0x8 address 0x2b37aba00000 len 1000000: Input/output error
```

Things work as expected when UCX_MEMTYPE_CACHE is disabled though:
```
$ UCX_MEMTYPE_CACHE=n ucx_perftest -t tag_bw -m cuda -n 100 -s 1000000 &
[2] 42522
$ [1569346938.233119] [dgx03:42522:0]       perftest.c:1376 UCX  WARN  CPU affinity is not set (bound to 40 cpus). Performance may be impacted.
Waiting for connection...

$ UCX_MEMTYPE_CACHE=n ucx_perftest dgx03 -t tag_bw -m cuda -n 100 -s 1000000
[1569346948.037598] [dgx03:42539:0]       perftest.c:1376 UCX  WARN  CPU affinity is not set (bound to 40 cpus). Performance may be impacted.
+--------------+-----------------------------+---------------------+-----------------------+
|              |       latency (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| # iterations | typical | average | overall |  average |  overall |   average |   overall |
+------------------------------------------------------------------------------------------+
+--------------+---------+---------+---------+----------+----------+-----------+-----------+
| API:          protocol layer                                                             |
| Test:         tag match bandwidth                                                        |
| Data layout:  (automatic)                                                                |
| Message size: 1000000                                                                    |
+------------------------------------------------------------------------------------------+
           100     0.000    53.849    53.849   17710.09   17710.09       18570       18570
[2]+  Done                    UCX_MEMTYPE_CACHE=n ucx_perftest -t tag_bw -m cuda -n 100 -s 1000000
```

@bureddy @yosefe any thoughts on this?

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Uses alignment required by Page Table and it fixes caching regions that have one shared page, i.e. first and second regions shares its last and first pages, respectively

## Why ?

Fixes #4222

## How ?

Update MemoryType Cache alignment

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12622/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/862359e6fc64031c0cf34d1cb13ba0f8f6fd6c04/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/0191acf3b1beeb3f9decd890f617cfa052988f88/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/af1ce79ce20c785cc3c57136e9a9c0dc9e1d4c68/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/3ca2ccb99d05337e60ee3401c873d862ed45769b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/dcab7efa49544c270eef1fb0e6733314ee149579/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/7c09b0df209ddb7e6375d230d4eda8d28bc61aa6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/f927efaeae1b22072349ff0d8292b2efbba118c9/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/d4f853b05a36c8a77ee957a8a492eceb69e252a6/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/c3319fc937256865a1a91f9cb29df96436d84aab/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/c3fc713707cf8df65eef5b225b271e65aa844afb/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/a5887f11b2b0ab7c041b4db3e3e6b32039432f57/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/70a74e63ca86a3757d03c33e575c84e93f566ba8/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/9505579e9daa0b57e4e89d9c455df22e304281b7/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/9e6881d35580258111151f2dc1b13fddf7aed4c8/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/141e0492bb1ae2e386ba725f49bc7075b06fc68a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/708f8ec0fa421d0e41be1602763b7a4c025c0acd/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/3eb64c95df6bd763e8b6ea7a8c2549965a398a19/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/ea0625e71d327529736919a3076e1b1ec175e523/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/975b83f0dbe7094bd9fb4acea2295fcb11615eea/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/cd85adf39bb02e827c1eddd3eaf40997b8d2470e/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/a75e613809cd6f62ed307c0c5f7977b02b156fba/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/6f4d82d0b31b1bba274ec3d0def1200614c129bc/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/11632bec6db14ce8a04cd40e3146b51dd31c6889/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/f0e3d17bb5834f056e7fe90ed1a9643a0e975117/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/4c1623de630b7b020b27421620beca6c6a99fe09/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/c1ffd54d53a8708072a942b09f3d1c1c9aa41231/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/2f0b908e648aa6a8d7c12e3dc0bb8b28edc952d5/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/a4dec025ba95477c873fa11f640cb0eae9b281a2/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/61f4d7a8f57334521140f8db8c57da81/raw/7cdba6c426bd41fedab35278cb22c23e3f255f2c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@yosefe @hoopoepg could you review pls?

File: test/gtest/ucs/test_memtype_cache.cc [hunk 1]
```diff
@@ -47,38 +64,359 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
+        mem_buffer::supported_mem_types();
+
+    /* The tests try to allocate/simulate two buffers with different memory types */
+    for (std::vector<void*>::const_iterator initial_ptr = initial_ptrs.begin();
+         initial_ptr != initial_ptrs.end(); ++initial_ptr) {
+        for (std::vector<ucs_memory_type_t>::const_iterator iter =
+                 supported_mem_types.begin();
+             iter != supported_mem_types.end(); ++iter) {
+            /* 1. Allocate the same amount of memory for buffers */
+            {
```
Comment (brminich) [inline test/gtest/ucs/test_memtype_cache.cc]: why do we need to have separate cases with immediate buffer release?

File: test/gtest/ucs/test_memtype_cache.cc [hunk 2]
```diff
@@ -47,38 +64,359 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
+    }
+
+    void test_region_not_found(mem_buffer &b, size_t size) const {
+        test_ptr_not_found(b.ptr(), size);
+    }
+
+    void test_ptr_not_found(void *ptr, size_t size) const {
+        /* memtype cache is page-aligned, so need to step
+         * by page size to make something not found */        
+        test_lookup_notfound(ptr, size + ucs_get_page_size());
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: good catch
but we still have to step by `UCS_PGT_ADDR_ALIGN`

File: test/gtest/ucs/test_memtype_cache.cc [hunk 3]
```diff
@@ -47,38 +64,359 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
+
+    void test_ptr_released(void *ptr, size_t size,
+                           /* the flag indicates that the first/last page
+                            * maybe shared between two regions */
+                           bool page_maybe_shared = false) const {
+        if (!page_maybe_shared) {
+            test_lookup_notfound(ptr, size);
+            test_lookup_notfound(ptr, 1);
+        } else {
+            test_lookup_notfound(ptr, size - ucs_min(ucs_get_page_size(), size));
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: removed

File: test/gtest/ucs/test_memtype_cache.cc [hunk 4]
```diff
@@ -47,38 +64,359 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
+        event.mem_type.mem_type = mem_type;
+
+        ucm_event_enter();
+        ucm_event_dispatch(event_type, &event);
+        ucm_event_leave();
+    }
+
+    mem_buffer* allocate_mem_buffer(void *ptr, size_t size, ucs_memory_type_t mem_type,
+                                    std::deque<mem_buffer*> *allocated_buffers = NULL,
+                                    bool insert_inversed = false,
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: done in all places

File: test/gtest/ucs/test_memtype_cache.cc (hunk 1 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: this is the simplest test case that can test that after releasing 2nd buffer, we still can access the 1st one

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12632/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 24-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/6aaffbb5d79d3b667bf47283e06008f4caaaf0bd/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/d40359c05e5f85bc0672a8e3bba0fe33528f4676/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/578d98256f7b5a4ceae3f41cf962c3d6b277e381/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/363a548c07de2795c39677fb313c417758bb5ded/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/40e6796e77b36632a7d59b7d5189554181b21e83/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/af3b64c603a4cb5a5622feb75652bcf8ab9cc5e2/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/97a3f4cad0a659aa0f3d7e15ec76a0c760023485/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/7ac5c5c634531d198a3864c311378035503c931a/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/8c64aad48972b1ef488181a7a9a6e3e6743f494a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/58d199b362d83fbdf2d1d659b0de6c9d2d64bcac/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/9942523133db2de1f7d7947a4d80fa4793512dd8/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/1b46971b816ffd7044475bb40d210e1d7622c932/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/14a807eb4300f864cb87739411724bd139ee6cf7/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/b56578f122bb742cf0c43734117309e4c35fa69c/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/165da9b1cb306f32a117c21e7fb49651a9fb17bf/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/4500034e206065e21ac40dbeb6f63f35c73c5cd5/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/86bebf6cad04d8db4545496f1a43fecde186d0b2/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/395137ba8949535c8e4650685a3431ac00f101ef/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/34764475f802c1b35305d440b1694ca753b090bd/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/c8df3722637c5e483598f3060eff138e2ab9ed67/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/0ac0d9733571b0eb9e36429b9ae97c38a409a35a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/2a0305e8938c358321c7efa7120a23e2b54ba8b6/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/2c14b0e838aecf09252fa2c20227176ecdc20a1d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/6f7da7919b43eb8ab25384a4136d24c5ed33834c/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/408d47e5b7f7e98ef0975cd43ea03b39e0f15ee2/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/279b45b565ab408ba7bb04a4a7a98effacba1985/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/a28451f7d7b91f0c8154f166f77319db0c28fc05/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/752b6fc18195e5674e34c979f186eceb022657ba/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/fab173bf7345e3f13e25d0c8bb08b3c2/raw/66197e508dd9b8036d45dfb733b109c317a3e8a4/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@brminich could review it pls? your comments were applied

**Comment by dmitrygx** [comment]
@yosefe could you review, pls?

File: test/gtest/ucs/test_memtype_cache.cc [hunk 5]
```diff
@@ -20,22 +26,33 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
     }
 
     virtual void cleanup() {
         ucs_memtype_cache_destroy(m_memtype_cache);
         ucs::test_with_param<ucs_memory_type_t>::cleanup();
     }
 
-    void test_lookup_found(void *ptr, size_t size) {
+    void test_lookup_found(void *ptr, size_t size,
+                           ucs_memory_type_t expected_type = m_type) const {
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: why do we need to save m_type? seems test_lookup_found is always called with memory type parameter (from test_ptr_found)

File: test/gtest/ucs/test_memtype_cache.cc [hunk 6]
```diff
@@ -47,38 +64,349 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
               << " memtype=" << mem_buffer::mem_type_name(mem_type);
     }
 
+    void test_ptr_found(void *ptr, size_t size,
+                        ucs_memory_type_t expected_type) const {
+        if (expected_type != UCS_MEMORY_TYPE_HOST) {
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]:
```
if (expected_type == UCS_MEMORY_TYPE_HOST) {
    return;
}
```

File: test/gtest/ucs/test_memtype_cache.cc [hunk 7]
```diff
@@ -47,38 +64,349 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
+
+    mem_buffer* allocate_mem_buffer(void *ptr, size_t size, ucs_memory_type_t mem_type,
+                                    std::deque<mem_buffer*> *allocated_buffers = NULL,
+                                    bool push_front = false,
+                                    bool test_not_found = true) const {
+        mem_buffer *buf;
+
+        if (ptr != NULL) {
+            buf = new mem_buffer(ptr, size, mem_type);
+            simulate_ucm_mem_type_event(ptr, size, mem_type,
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: why do we need to simulate event, wouldn't it be generated already by the allocation itself?

File: test/gtest/ucs/test_memtype_cache.cc [hunk 8]
```diff
@@ -47,38 +64,349 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
+
+    const std::vector<ucs_memory_type_t> supported_mem_types =
+        mem_buffer::supported_mem_types();
+
+    /* The tests try to allocate/simulate two buffers with different memory types */
+    for (std::vector<void*>::const_iterator initial_ptr = initial_ptrs.begin();
+         initial_ptr != initial_ptrs.end(); ++initial_ptr) {
+        for (std::vector<ucs_memory_type_t>::const_iterator iter =
+                 supported_mem_types.begin();
+             iter != supported_mem_types.end(); ++iter) {
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: can we just test HOST memory vs GetParam(), instead of all possible combinations?

File: test/gtest/ucs/test_memtype_cache.cc (hunk 5 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: good catch - done

File: test/gtest/ucs/test_memtype_cache.cc (hunk 6 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: done

File: test/gtest/ucs/test_memtype_cache.cc (hunk 7 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: actually, no
real allocation doesn't generate a case when different memory types share same memory page
but, now our implementation supports such cases

File: test/gtest/ucs/test_memtype_cache.cc (hunk 8 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: it doesn't take so long
why only `HOST` vs `GetParam()`? CUDA and CUDA_MANAGED has to be tested, isn't it?
or when RoCM will be supported fully in gtest, it would be great to test with RoCM memory type

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12673/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 29 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/f34ecf387a82a879d501e329f48a9dfd5b2c1bff/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/4a85eb05d9bab3fb3c910fecbde7fcd97089c657/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/d4e433242d6a7f32ffef06fae78611a31fd3be77/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/6c8a28a6cd81d0c748daaa301ff701ed8a1a2cc2/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/a385d9dfd5032b99f49831f92e23e000271c19dc/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/52664b14fc6d44eb3b191380005a2a8f744b4b32/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/eb0af3459cfd3122ac81f0bb7e78738075b89746/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/84ff9fc9c4be89a0b6125e1567adfd535f67b48b/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/eb0532c381b58c6ff6b004e5887eda8b80364998/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/0914e4ece5c31b476536badf46985a0fa5ef56f6/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/865955566a14a7c99c3f646aaeb0b0db346eda0d/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/96a2562ca0c0cfa90ce9e0df661dc91c33d11034/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/855a35816666f6f03813971ea8187928d64be822/hpc-test-althca_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/67a1427fd37a49817d75818acfe9c938604fbcc6/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/263339df1b1668f75228450093c649b0777c67c1/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/9e39df124498a18f690886a2cc1590196d8e9c25/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/a9272a40938b465ed4aeb670ccacd5ea08848a73/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/68dffb541009b72c21def53fda53483e551e323c/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/5c947cbe4c88e0c52f60cce1eb245ebb27288580/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/9b5e2c1c4aee30eda072d9aba469f9ca8c489c8b/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/7d198f0b404ea5b0a4f76e3455350692a6494cb8/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/2e79c55cf4ea9ccedf973ac3ac66c58cf7c862f9/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/f49c8e6919ef0b366cef390cdacfbe093dddfd13/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/d7b8be921d8dd4ad50a558473c72b26161ab5f93/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/8e6ef10e62075f570e16ed644f1cd9cb7aa093e6/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/9f8b63ff4ac752b513a6f56ccadd4dd8e633af67/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/0503986deac5ca92d01401b185fc123ae6e9aba1/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/13234229a4660b9ff0e25d2d25acc1c040e465af/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/26f7a13a49593b4c3d0191ecc8f3f09c/raw/6ded3947e2609835b2d4e69078be240ce3f9c5bd/r-vmb-ppc-jenkins_W3) | :x: FAILURE

File: test/gtest/ucs/test_memtype_cache.cc (hunk 7 above)
Comment (yosefe) [reply test/gtest/ucs/test_memtype_cache.cc]: but we should install UCM hooks for cudaMalloc, aren't they sent?

Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: > but we should install UCM hooks for cudaMalloc, aren't they sent?

they set inside `ucs_memtype_cache_create()` (i.e. MemoryType Cache constructor)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12685/ for details (Mellanox internal link).

File: test/gtest/ucs/test_memtype_cache.cc (hunk 7 above)
Comment (yosefe) [reply test/gtest/ucs/test_memtype_cache.cc]: so in this case UCM should fire and event when we are doing cudaFree from mem_buffer release? so we won't need to simulate a UCM event

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/969f84a9731599b461d0a8f82e6ec4f6a4809647/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/9600e3fd19921a0321dd89bf5344b83f06a41fcb/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/08d04fa7577a0a74962bc62e2131c1a5e861de94/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/78f9ca4798584fa903b8b3d418bc4b39ed520207/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/0379eb709a41d314371c496bf8d08cd318333dcb/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/d47e1e42d7e432aa0bcedaa8e5255f75e8cbb445/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/4a71fe15ef013757dbd8fee5938e4bdd1dfaa9be/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/aa1f225c7c3375902f33499c3e497e1510340a1b/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/48eb7d33c9e9b4ec9a4fba91bb7e53639aea425b/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/79d5c75b1075de9cacfe6666ab2f95ebe0dc1272/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/619933e91bfb2afc1fb1dace4f1083aceffa001c/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/3a9fbf03e6c2864199443b2e54070bcfdc78f9aa/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/42ddee8b793ed14ac11e6b6359d7a858865af87d/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/49294bbdae49c3eb6be5fdd74154c404f0ae09ce/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/3ff8429880bb4c1f5fb4d0e9a36dd817180afe30/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/c76870151bc0151cd8eb6daf20cf40a62fcdd328/hpc-test-node-new_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/ef2fe88848cbc566c0d005f644f1a2c0ae390c19/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/b23401de052a0f33abbfbf662a6d727fc076a8b2/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/f42dfb91ef7c5178694b08a66b735844f05fc8de/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/86895cede4ba77a434757ee74446a09416fc52ab/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/f81ab60ee2a9fa24f31d88269d579f779bc3bb03/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/ae92a3c59969a1c19e00697b4fee63a2541e0242/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/64f533c232caf28934d844db5543f1dcbd5a981c/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/951908060468a0960aba69f56fcd7d578d824f0e/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/0f8c0554172f161edd4e13bb4ae931a21230d289/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/0ba24f40868b6139d73b88e4bae8188e07da1404/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/29897580a7f3a99bd13b0bf6433414dc48884108/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/340db3a8b35971399e081a7ce3378fdee7dda618/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/73a68ed63d928d12b30c8a174540c7e0/raw/7dd05e80ab355c154ba25b13680b9ae448bba19f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: test/gtest/ucs/test_memtype_cache.cc (hunk 7 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: > so in this case UCM should fire and event when we are doing cudaFree from mem_buffer release?

yes

> so we won't need to simulate a UCM event

ok, will remove

Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: > so we won't need to simulate a UCM event

done

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12694/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/104acc6d6d707dc5cedce0ed6518bfcd36c5111c/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/1eee348af1e637371f9fd0b4b35f3a71cfee0c29/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/f41ef7566eb331ce30ff4be0fb9caf2787c940ab/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/40cf7d069b30f6127d25347087881f27e9c9ed89/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/9172d5431e87fdd3887bc661045aa01be22d6151/hpc-test-node-new_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/3aca0b4fa5b84b68f83a91c261623cc7cfde0188/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/5f6090fe3bca4567e367379713fc69a50a2e46d5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/136057e737f061e445a4374bddebd132fdb5ba6d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/ab5f770133669fda951ca278e4ac5b86f970d044/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/85332c0af9d34cd43d71592b04ddf066abb5d92f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/4acb0f47a2d96741379fe854c10ca3e9d170b426/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/b7ea8f1c39437f3339f5e208d2c9bebcbec148f9/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/0e9e7026011f3e5781540c6a99b264f9cfce38b1/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/9bd9dde108cca872812b2de975098c399aa4c367/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/eae32d4483011b0922a1e1945dea48882aae5c27/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/c34092cbe8503553ad7203479722c02c1ccc9dcc/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/6921766927301bbfd6977a3c360f708cc7e547bf/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/1101da63f4a7d2075c2158ae03bc07fbc026c2e7/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/20bc1d89a7bd65a8702f3e2d343a2fbe66e059c5/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/9d7d687ae0806311f336fb63ff4a4dbd4b4eb0f4/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/e6edf4214f8ee6ab53b59173c83b8335d991e8ea/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/abd6884590da2ad36b698c1b8f0fbe7c19b87c3d/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/c9a94a5161664cd524314dcb7dc889a1ecd0af2d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/fe9c6283f2ad7d5c2f90f1e0d39645fdeac88d12/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/4e0e89d407281bfa109dbf1f742a279ced673378/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/7b757ff444536d3573cd8fda7e082ab7bb431283/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/8d374e94c99d908b8bc0cee59ab65e74c700d2f0/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/b8457313fc64fae274fb81a68a8d7e96567dc180/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c3fe636367943a7ff80c6eb45bc73cba/raw/08ae8850d4a321763a09cae9217b0edd6a1107d3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
> in general the test seems overly complicated

@yosefe the last commit simplified the tests. could you review pls?

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12709/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12753/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 13 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/86902b16b99575c8f1a5d03701c8789e1c9c5361/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/0a8e83d12cd74b11030ee8392ac0be49b3414868/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/91480ee81886d7c3d4d9440301d2be2023b9566a/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/fba7c1ec5fa6e2e25079b902d16959db4b7476c3/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/27adc2ceb6618ca9a314a00e7a148c5f1116110b/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/59d15217b46675e00838737383d1aa026fda7074/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/4851abb648e983f59128b8cf95a7d54f04f883f8/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/e7258b1af7e147b8c0285d0812fc0580f11744d9/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/1220a97711c365743bafcbb58bbe37a094e8c638/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/e7c9fa5af93db04ed5db27b22cdd9373234af852/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/5ad0be1e213f14a055ef624861272e34b8949799/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/d8258775569f24046490e476f8949a6669391e8e/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/402a6938081083b77de663fd6a7cfaf3ce5e296d/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/a0d9063ebf605de8afb9fef9ae558ad674f47105/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/816260d6a35105a2654e5914a4144943dfb409aa/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/e8b1718484fc55c1984b7590627f9c213a986a5e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/8bd81e0e944de6bbb46e2e5f410aed6115398a53/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/2f0e673f8d7ebab302ebaaad9b6e833ae3bd544e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/8b97b9a5fe65e14a2ebd45fa611282f541850a4c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/455003ca6f64be9d6eb12c34e1bc95d97ff408eb/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/64966b52035451d9132e103cde07398a99c22477/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/f8c90fdea11c4949c3271468560ecdc2b4cc48e9/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/97813280d5a20010536e21a5f30c0870b9b43c88/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/f60d900dac46e72994821627d94edee1a2cd6816/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/3a1825bfeedd574c12466d64a2973f8a537ac0b1/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/a91dc0f3fa65a8e049ad1cca3965e2d03531ad2a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/9ed6fa0503fa646ea676c6328b1bb3f7a4d52cb0/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/7210cfe18f8f4aeef96fdacef0336cead84de2cc/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bd5385ff1b40943f6402c832b9c367de/raw/ffc52e649dcb4104f90457694671d7253d807e59/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: test/gtest/ucs/test_memtype_cache.cc [hunk 9]
```diff
@@ -47,6 +62,162 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
+            mem_buffer::supported_mem_types();    
+
+        /* The tests try to allocate two buffers with different memory types */
+        for (std::vector<ucs_memory_type_t>::const_iterator iter =
+                 supported_mem_types.begin();
+             iter != supported_mem_types.end(); ++iter) {
+            for (size_t i = 1; i <= ucs_get_page_size(); i += step) {
+                mem_buffer *buf1 = allocate_mem_buffer(i, GetParam(),
+                                                       &allocated_buffers,
+                                                       from_head, 0);
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: how does it matter if the allocated buffer is added to head or the tail of the deque?

File: test/gtest/common/mem_buffer.cc [hunk 10]
```diff
@@ -228,8 +228,14 @@ uint64_t mem_buffer::pat(uint64_t prev) {
     return (prev << 1) | (__builtin_parityl(prev & polynom) & 1);
 }
 
-mem_buffer::mem_buffer(size_t size, ucs_memory_type_t mem_type) :
-    m_mem_type(mem_type), m_ptr(allocate(size, mem_type)) {
+void mem_buffer::create(void *ptr, size_t size, ucs_memory_type_t mem_type) {
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/common/mem_buffer.cc]: removed

File: test/gtest/ucs/test_memtype_cache.cc [hunk 11]
```diff
@@ -58,27 +229,78 @@ UCS_TEST_P(test_memtype_cache, basic) {
...
+        mem_buffer *buf1 = allocate_mem_buffer(size, GetParam());
+        mem_buffer *buf2 = allocate_mem_buffer(size, *iter);
+
+        test_region_found(*buf1, size);
+        test_region_found(*buf2, size);
+
+        buf2_ptr = buf2->ptr();
+        release_mem_buffer(buf2, &released_ptrs);
+
+        test_ptr_released(buf2_ptr, size);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: done

File: test/gtest/ucs/test_memtype_cache.cc (hunk 9 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: this changes the sequence of freeing memory

File: test/gtest/ucs/test_memtype_cache.cc [hunk 12]
```diff
@@ -47,6 +62,162 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
+    }
+
+    mem_buffer* allocate_mem_buffer(size_t size, ucs_memory_type_t mem_type,
+                                    std::deque<mem_buffer*> *allocated_buffers = NULL,
+                                    bool push_front = false,
+                                    bool test_not_found = true) const {
+        mem_buffer *buf = new mem_buffer(size, mem_type);
+
+        if (allocated_buffers != NULL) {
+            if (!push_front) {
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: done

File: test/gtest/ucs/test_memtype_cache.cc (hunk 9 above)
Comment (yosefe) [reply test/gtest/ucs/test_memtype_cache.cc]: but release_buffers() also accepts "from_head" parameter which tells which order to release
so why is it needed during allocation?
seems it has no effect really..

Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: removed it, now we are just using `std::vector` and insert into (remove from) vector's tail

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12839/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/4cbaacc666f820af40320c436913351759dc8e78/_main) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/0079c31d71b5160e1b6a38c16354b1ceda7794a6/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/d70c76ae50fc8104e10819c3d7a2faab5257144f/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/67d03d31ea2ced5e10f8c26d77baec78eed527df/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/19bcc6c9f7ba0bce7bc0926981af0cb52486b54b/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/a46dec2a98a621581caff002e2694f2d9ab50ff1/hpc-test-node-new_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/107c24f20dbc333716c1f3b2a523c7b31f559703/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/7832b4cea7c7da1c2ddd69d85921b54c9ad3dd3a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/c1c089f767f1fabb5904f85c68bbcad53013cde4/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/5c20971926b2482dd25b08cd4d73338f301b15f7/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/861e00cb872011fe7c7100b2b493b8a2765ac403/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/37c1caefb108f64b4ce7ff95dd9ec3df42067db6/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/1d9183e0635846ee03e3ced43927ac28641335c7/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/72ad93533a18b524ef33aec8a3a7f7679bc2d23c/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/eec9992e118cd31f3e4de01b7f58a9ad19b5be65/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/7cc08877b875bb8d59fec79906614c1a211fda1e/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/8e646f78d6b9d88b6d113a90f301bd64c203e38b/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/908fe646f15cfae0b5fc582159a2799b9bf58264/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/19e84866b9db81e09a9c8e5d909a0f989dfa1133/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/d6c41398475decd65d28c3f27d51b5db4b313353/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/1048bd8ba04e937c5203aa9d7e46fd35f5e62546/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/dc35e3fbfd7f46708c72939edb9e756c2c39fd01/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/bed4ba5fa081040b3e09eec638c3a16795650606/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/9f0a37dbd3bfe3860594c4b7984f007bfb51a785/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/a9d756b0cc476fcbe5da3682fab3188251280f89/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/4189116980500ef6155a954aec33b96714965c69/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/d236ced16688aa5f61986565b4f7a03b454bd3fd/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/ca8ba01842aaf4776450df395aa428c26b213fad/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/78d0e330bd460d08706b0d4e59bef4c9/raw/c0a897649a79ca4a0fd06d53426becd62a2c031e/hpc-test-node-legacy_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12846/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 9 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/0eb4f6a721dd5fd743338d31d52f21e717d362c8/_main) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/a2c8e3a2c6c62bac4315fce9b8094c6e28919c64/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/3f21ac2934ef842372da05f7c319dd426149cc5f/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/a926ff8cc8bb4c5f636a539c89b15642325f0af4/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/cfa1febc241c0866e11ae4b3740663538089d243/hpc-test-althca_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/0a1b382fc9124e9c6ca852bf8f475291a7395f47/hpc-test-node-gpu_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/6731fa5f4ddaa50239a2f4f2c1c26efe1e451236/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/02bdcd4f5fcfa1216f026fd7a4323e69e04f7218/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/4541bbd7c72fb6c5ea5558eb96579dbb65127b42/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/7e09ca5830e82b9d427a5cb02c497f66ca37241d/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/da901292077ef81125a6cc6eed0af05b954a3e1e/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/a589feffe5a5e60fd977f31d4598f43800828cc1/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/f4ae3c52f9ffcbe2f529d8d05e4da2f111aa63b2/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/225bc7b7412521185b16cc2d2995832e304bb50b/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/6b48f658890a8e80534afb53f35738c6a516e51f/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/d6e594b74b8d97ec03f13c29a157296d55480d47/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/fc37d7186b691eed96d7e5cb45baeb7ffa31d376/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/f4c8326b65d5f5d5c909a292de96a7f3d12fd9d0/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/334fc4f6c469580ca7d486c5e15a211224c31bb3/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/c7226ef1d08f9d1cd8324890abe0e1539fcbcdda/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/6511a0a80a815fae5b9696dbb9629e9b708c2ebd/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/f14a5b86fe6521594ffae105d764fcbcb082b990/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/f67d8aa7e4905a6ca28ac32fae70087748fbed83/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/2803cb6b00adf83d09d567fe9aa5786e6da9111a/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/bb73c3e37d2aa7d7e1e46af3cdf64c4018db2193/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/a36a1967fdbba076e6e528e623525c90904b47cd/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/0a835dab1d1368301b854bea8f12b99882714c93/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/3ca5d4d88e82ccde7d87e943652d38fb91c79ac0/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5cadb76bef2087cc725507aadbfac24c/raw/c6c9e2e728cd177adb80ad7a77dfb69642609d5d/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by dmitrygx** [comment]
squashed, waiting for the testing done

**Comment by yosefe** [comment]
@dmitrygx there is compilation failure in the test..

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12850/ for details (Mellanox internal link).

**Comment by dmitrygx** [comment]
> @dmitrygx there is compilation failure in the test..

@yosefe fixed

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 25 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/d8ea8bd9efe63d48734006ff658e73bff9fc3361/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/3debd8e8b732c6feab601092b62457f0a8051ecf/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/7c535fe12c8fc27697c6c2e0db13d76d4d3ed710/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/6570e936a580853bc944c848c59d2dae778e12eb/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/703aa60db2bdacf2c91b880bf8de4ac468225e3f/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/8dfaabfea0bc1d7af424b850b91d9dd37070b1ea/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/dbbfb672b3b496dae071238cd37d40782c4d6147/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/4c527a1f2c093846c3ef07c9fd9ccefb8a0ae111/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/afe80f62c2d5a462077c98fa30915feb8233dad2/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/bd2f15aec1d818915e361a3a370066b53f8fb4b1/hpc-test-althca_W0) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/5eeaf9e46b5e307801d899dc11273302dcfc5a8f/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/4bcd85f6db94fab1d461375cd4e156d13e2a7cbc/hpc-test-althca_W2) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/ebfd3d1014ab5af93229c8800a58342a6382e968/hpc-test-althca_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/d7d0f69d8e31a060fe1a1901b5e6d686352d6d92/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/41859891edc2971538bc248f78873c96a2f439b0/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/43101c9c10e86c321407dff45ad8c5dd44530702/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/94598ceed0202f4f1b423a1137ff5a270d056bc0/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/ffa8c9af1673bb042fb0c63ef458f8daacfb683d/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/88bfb993b0305dcbf9dce53e1d6797e4abf4d92f/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/f8d1d15741fb996eaf8811915786f05ffa87c102/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/43b1b43cde86ce91f0e8472239fa6f32b332a579/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/20d17e995beac847b869f792d9d079c2dfb761e3/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/b651ceb8ce88653bb7d4c6460336bdc865ac0801/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/902620e9e5a8fa63a1b2224643b15e870a1b05b4/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/8494e1406dfe7e01188a221616eac00a667ba628/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/e50173de304d3d05052024552b3be59993d270c5/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/d88865f607a499479c7085b70f0687ff65e790bc/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/d1e96ee795900cadaf217b277ce9c643424536a0/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8eafdc2f158d535603ea5090b714affc/raw/60c0cee8d88eb5e63f6c038be384a7e475be1aab/hpc-test-node-legacy_W2) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12851/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 6 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 04-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/7cd37e370b01706ce529947e2d2c7c8057f0de8a/_main) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/455966782f9dfcb326fa6c299582331fad22cbb1/hpc-test-node-new_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/2abe74d34220dc4c85fb91ea830515b92338557c/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/48d530c17f73aa828379bc296383118ffade7b4c/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/0f6edf0446e9407ee751c1585a5c7f057a81ba30/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/c411c792e2f7f793d2285124fcb43cba9e757988/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/afd4a124a56c269352d01d1a6d4b3d6af24cb88e/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/87ab1fdbf25c68cd17cc8dd4fc65657cc2294fe0/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/f78e705d62ff70dbf265a6ff997b0213aaa41cd3/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/7f1de126e89b1cb18da2ba67a326a70de3bb5c26/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/17ad02b5946a0b0d0f8db7c630da8d5d4fc206c8/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/f2f78d292bcb9d2146aea2d6bd4afb4e8412099b/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/c69d42ba2f2c7e5498340803d234bc99b54ae42e/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/78766e8b73a8ddd4aaa945d3b23f3301f5d30628/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/9c666559151ad0e1cdf0b05a7c6190d6967a074a/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/c8a7df929586d34a94a4d4fdfa0fc2bdffec81e0/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/192719c1ecda56c704237efe852c1593cc3452a3/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/011347f3ed0c6c3a5e088ec0838258905a0693c6/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/15783cc6f0c06edca9a26033d5043403a4cebfae/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/d68bb87ee7365dc637cbd79a284430119af83edf/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/23255381d8899eb47db8d4d606e0f725b8dab049/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/424f08f726413377604ecd6c187f6f033b7d1fbd/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/b7280f1c7605fe9bb1938ab734166e0d7dab02cf/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/5cb7c3092efc45e1f7b028e96f91300fbbb73107/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/d7a8dfc900e4a90a9b576daef5fcdf0369f8cd09/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/44f5224a588f5e2cf78c560c741783751460021d/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/6f675da1c072d3f1d1df16c5c943fd92d423e14f/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/0d294e5df983d53662aba1656b571c6e0fd67035/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/31939ad702a99e7f5709efbac04bf5e9/raw/8b0054918132647b555aa8e70c08f3186c2128cd/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12864/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/140e4f33ce827dedb2958939f79b4aa3732de66f/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/e89c645c92fd18df89746ee4cca1733677463eed/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/4f658f360a0169a2927619cc6ab94bc8557693bc/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/8f5b82e84c86768633f853454894608ad856b51a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/ea9d5e865341b61ef3fbe6db285574fe95c16e3a/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/baee828e4ea749d6149e6f5e195dc82a7ceb0fbd/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/48b472504b6ab941a3345ecc7dc9962a8ef2df59/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/cdf1847afe96ceb8c906a7a1fcf33bf46dc91fd3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/69fd89f69370693f83c0e338de5a194b100fa424/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/5b80b4c0d4ed95a22e99b8264c517cdfccecc7e8/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/27b673104aa332802a27f89ffdf1401d99e754a4/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/c7f3d944524a9e0f4e6bbfe2467a14d82e4df4af/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/0cbd71bc4bfffc2ee1fdb38254d5f1c99406e7bc/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/6191167279f0463f8a3b449934148831e61a1477/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/061ae2c2f6f7c04919b05c4b8c11bec6265bb468/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/248e9715b9007ee0f76830e57a404d6197e66202/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/01c7d5181fdec4a79c02d1a7d6977293a980ea23/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/3ec561cacb66e4f44d1379b7a3339c30718c0c60/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/2a1b9d8ace58a39fc5dfd4dd7add2fcf7eea0676/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/15c77552b9984e70f09379818e8a8d8c2ef4a161/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/9c0e487206cb58ef9ab716c60fe091a2ddfc53bd/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/8a8417d09db3d4d463ba332da18c80001cdf3068/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/6a858f02fc28a9755c43d93421068508a3498af6/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/08d253b34448d8dd39704575524b89e2aa957ad1/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/fb2857ea51d75660449b3bde58cd47fd887d5017/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/71e877e77ea275a289aabd3c852a147660e73cad/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/bf948f4724d95d33893477fc37cf014dc130e8ee/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/68bc16098cbb1ffe80fea5573c75f9dcef06808f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c06ec8a9bd55a83c9fd10a341a09585c/raw/71aca7ad0846507fe2f387455b3430ec08450e15/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@yosefe ok to merge?
