### PR TITLE
UCS/MEMTYPE: Merge regions that have same memory type

### LINKED ISSUE #4393: cudaHostRegister invalid argument in uct_cuda_copy_mem_reg
ucp_mem_map fails to register cuda memory. 
The exact error:
```
cuda_copy_md.c:86   UCX  ERROR cudaHostRegister(address, length, 0x01) is failed. ret:invalid argument
ucp_mm.c:121  UCX  ERROR failed to register address 0x7fb473081000 length 4915200 on md[0]=cuda_cpy: Input/output error
```
uct_cuda_copy_mem_reg first checks memory type and then if it's not a host pointer it calls cudaHostRegister. But cudaHostRegister in turn works only for host memory and it doesn't make sense to pass cuda pointer to it, probably that's why ucx prints "invalid argument" error.

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Add support for the following cases
1. when a user lookups a region that includes multiple buffers that were allocated separately and they are contiguous
2. when CUDA buffer consists of multiple regions that were detected by MemType Cache during existing allocation handling

## Why ?

Fixes #4393 

example:
1. [0x250 .. 0x500] was allocated by using `cudaMalloc()`
2. `ucp_init()` was called
3. Memtype Cache init: read [0x100 .. 0x900] from `proc/self/maps` and add it to Memtype Cache with LAST memory type
4. [0x100 .. 0x200] and [0x200 .. 0x250] were allocated using `cudaMalloc()`. So, cache has [0x100 .. 0x250] - CUDA, [0x250 ... 0x900] - LAST.
5. User calls `ucp_mem_map()` for [0x220 .. 0x500], it reports an error when tries to register it in cuda-copy UCT as it assumes that this memory is HOST (but has to be CUDA instead)

## How ?

1. Merge adjacent and overlap regions in Memtype Cache
2. Return LAST to force memory type detection by a user if a found region is not big enough

### CODE REVIEW

File: src/ucs/memory/memtype_cache.c [hunk 1]
```diff
@@ -201,22 +201,36 @@ UCS_PROFILE_FUNC(ucs_status_t, ucs_memtype_cache_lookup,
...
+                                      &memtype_cache->pgtable,
+                                      start);
+        if (pgt_region == NULL) {
+            status = UCS_ERR_NO_ELEM;
+            goto out_unlock;
+        }
+
+        region = ucs_derived_of(pgt_region, ucs_memtype_cache_region_t);
+        ucs_assert((mem_type == UCS_MEMORY_TYPE_LAST) ||
+                   (region->mem_type == mem_type));
```
Comment (yosefe) [inline src/ucs/memory/memtype_cache.c]: i think we should return some error which would fail UCP (not assertion) if memory type is not same in all regions
and in general, maybe merge regions with same memtype, and if we have only partial intersection return UCS_MEMORY_TYPE_LAST

Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: > i think we should return some error which would fail UCP (not assertion) if memory type is not same in all regions

ok, but if we will do merging - we don't need this loop

> and in general, maybe merge regions with same memtype,

let's do it

> and if we have only partial intersection return UCS_MEMORY_TYPE_LAST

i.e. if `ucs_pgtable_lookup` returns valid region, but `pgt_region->end < (start + size)` is false, we will return `UCS OK` and set `UCS_MEMORY_TYPE_LAST`, right?

Comment (yosefe) [reply src/ucs/memory/memtype_cache.c]: > > i think we should return some error which would fail UCP (not assertion) if memory type is not same in all regions
> 
> ok, but if we will do merging - we don't need this loop

I think we need it in this PR, instead of failing on assertion

> 
> > and in general, maybe merge regions with same memtype,
> 
> let's do it
> 
> > and if we have only partial intersection return UCS_MEMORY_TYPE_LAST
> 
> i.e. if `ucs_pgtable_lookup` returns valid region, but `pgt_region->end < (start + size)` is false, we will return `UCS OK` and set `UCS_MEMORY_TYPE_LAST`, right?

Yes, because we can't let the user think the memory type is "host" in such case.

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/40377c5284ba7889c3fbcf09a9729b619627a417/_main) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/8ef5f04d662dc17e7ba6985be5f24e12a88c5695/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/e3f8e18d551d94b6fc6d7275d592e3c79d3340d0/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/56eaf5c927cea98b632fc93aa0de01bd3f04b70d/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/4181ef83653829c4410788a3a105db4bbadb3378/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/0b3bf2cffa8e964ba6f13833378dc80ec1d52ae6/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/e9f457139869f1d28d2b4e262d8fd6305a439169/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/9f43653b974fc678cea20c18d707fab6061f6b98/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/665934f936791f7d63124933eb0be6389698036f/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/db25961cca3e4a1478747affa621f19efe1f32d8/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/6903db0126f737530adeb8582ec9d876ac758e59/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/660cf31043a6791939b23e4d7ab197befea86062/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/9964cac544a448edc699da4351912176d420ceda/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/b7ebabc14e44716976c649d7327c9bd91562ac0a/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/b0cb51abe2ac118218b7eaeea89f8d42d89be1f6/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/73bb7e76f57136593b8126bbaadf1969b29aca78/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/eb63d4ddb18bcbefff246c0b5a6dfa31014771cb/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/7871bb957e28292115f34c8a4fef8a4d1d81b47c/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/10266fe1d55944e4dcf0f27b04b151f97d7f0eb8/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/9c6b684a5f82d8132661297db84df5803be5c5f5/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/bd78a6e58a5c21776620b3bae8657ea5d43ec61f/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/49753483632995662d584d847a2d0e2fc640a3fd/hpc-test-node-new_W3) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/bef3fcff74bb14d3ebdafd2fa6c973792ecee648/r-vmb-ppc-jenkins_W1) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/3bf94b81c43e695dd275139c5a064a471c669fc8/r-vmb-ppc-jenkins_W2) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7c5f2e5f6f6409d5ae9f5615acc9a8de/raw/30c20a2aa32d87f7262aeb715d99f662bd6e065a/r-vmb-ppc-jenkins_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 21 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/7724259016eb573707c8393d578fb829751e535c/_main) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/e40ae34f02d6cc878a5ca410a8aff84c6bd06978/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/4cdae6794686eb1fd1e1f00f796cb0638aa3186d/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/171f2f246536f04445ebdb859804e6fcf388bfbb/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/8778c22ef8656e2cb20f56dc9b17173be38d7080/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/fbfc2e4716acffb3a4ce5d4392ec68296148e6b0/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/ccfd0a61093680949071e09eeb492b7c8f2f07ea/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/4060b3cd0f29a96300add3e89173c67bbe02d124/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/4303de9448ee427e382708d27f74df19006c05b7/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/dde6fc39fba1f843f040547f1b51f7ae3dbbb6a6/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/879b9df949e6b38ef4198edd73dfabdb5b51ff1c/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/ccbe8c32a2652234cabfb09e6762e4d5d35d496f/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/fc3f2b818e0e79aeb3edfc59836de4644636f873/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/5871c5cde32a5f5f6147bbb6b12da888d2feb517/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/eee12b411658246c732ab56580e76b332d43e07b/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/cddc73ae28f905e068d953ff9f8ff4af825328ba/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/1b4f05267bb58552e424c4f74972b2e38a1b7093/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/2ca039a38a6866f3463da523568f208ba593dc17/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/559d511523981efdbadc0ad79bfaea9e99edd7a3/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/97cb26b3c8f625103a8032a4af5b6492efc7b321/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5e37192fb2650b8a78633c7b4fae4e24/raw/d315ff295c365b99acd6d82bb8aad0b10afc871b/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 13-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/8dba978423c7b1ede7748e271d759ed76736451f/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/b16773bbc9b654f0df0fce7a9cd4ab762cb93e91/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/52ddb9d6f1642daffe0ffb88318e5f9a721a23de/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/398840517e424fe4596687d5632ab47f1f07ba78/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/c4cf338cdec8614a8ead7e765931621feee46ca5/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/52a7778d9d05f4d9a3c777b0ba57860529fca119/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/84f7590e5cde610d741a45b8b1575d0571dfb298/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/a7b67a50dfb13e617731d149230252251f97b114/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/41a97e6cc0e87854d88c3bb8f27da8b350ed586f/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/d7ba9d0daba803bc908bec12d616ff467e8c5a0f/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/68d2854ae13a2a0ecc22ffb18e5fb3ccf8bf0876/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/c1a11ca842183c6e00d1c1ceeb7d2a52bd2158b2/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/407f0294ed9c01a7ee709d75ddc7d90382777474/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/2ffd25be6bcef81a7e436a7c2d73584298b5c4bc/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/3668b2799308443f448b442a66313a7918eed71a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/455b2b28292966e0e0884d0a3aec7f6914fbfaa1/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/18c291e59d13fff4d90680996ddd2957ea65466b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/51b15ca4550d2d2c1393a4d7bfd42e419801353b/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/489ea89c79efcbd21a4f2cdb408724d8555ccbe0/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/5a29c6cf588360a333f1bcf1a53ce7738e3b6a1a/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/2b474dc2e2558699c1a4aaf26ffaa5dbfb742770/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/c744e4923167912911ecc49c2640c2e4792e0795/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/3c88f5b6f61f6d4ea6057d9759442b41d2ebbc36/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/3c84631411c89872ae2aceff0d686330d040c263/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/1b40e90d6d9fc8a7ba08ee4446eec10e/raw/4575027665fdd03f080779add9d321298ed0eb85/hpc-test-node-new_W2) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/45135bc4c7bab839b4f8a1d3a64b449b49cb1b7d/_main) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/710d973e54452dc2d12d68327820cc910e63e284/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/6e9a4dfeb20f270d50c88178b61b9d6d116dd08e/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/16d4eada15ceea471a8c8aebd95e1a44e84c4a4b/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/a9f4b72db858f7c5cb623e075a95d80c593a78e7/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/c1a4891bf1f3c1e00bd29b4be323f1f33a94c8d0/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/15a35dda69bb42ab3494b991c2ae1e1d36405df6/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/e5348ab30ccdfc7ee7b2b39640980ceb0f4e2c39/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/b6bf0e9b947c5b526c119bf27624f86b0a3a5b5f/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/a248c566955009eb786cbedaeabc2c959c3526f3/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/f99a27142ba3829b655ac73e1843b0d929eb707c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/59a2cb57d0f32f812d84d883b9070fff483f3ec4/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/1ff0dd60e602af223af359ee539c987d90729435/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/9bc733faf6b2da613de07e864770df21aa2c0da8/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/90c991c5f94cf8ac4fa5164228a87d9f342269a9/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/06247b6409a09039f5ca5c86482dfc7031355586/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/79d206aefa51d51792e602fc2ecc2d6ff2f08d1b/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/118e82a95cc99ada3dfa9b55c5dc20447268c6bf/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/6b07ab91f755f31530ad73dd912812efe273b806/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/e521885ed32ce917c66a8d963abb24fc4b5286a6/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/c451689ba9e0aea03852620eeb119148168f794e/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/2343f3baa85b0fea91a1c07ac06c74403646ebf4/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/2d06c8ce908eb89c18877a2e9b417ea926a2b6cc/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/f24404bf8e172f14fc2852cd26fbaad60e5c2a1f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5050fc9b52634f094895e953354c3a9b/raw/154e5a3c4bd4bf349cf6d78383dc4f74d9a44a47/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/6edec8cc7bf3ad495006461386bbdb970378a897/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/f9004e61f1edc30f1677f02e1b594447839d05dc/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/f9e4d24bb2b731ae4020a8cb6af448d45ab16486/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/3005f835ada21039f59550f45b8869b20b5c1632/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/0fa6d7ef79193cf00e1c5f64c0e266cbd35effcd/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/0a2a76dc55058024dedf741100fc5491dbb208bd/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/928d65d90acfb660455a0b175ad834f7aeb4664c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/8dd07a050a170d3322de0261745f908c18b66f38/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/055e80f0fd995b6225892d77c82acfb1929c4c41/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/a94a003b06d5061dae203aa88e3a728013b65d8a/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/bbbd418eb35ae6735952a898867b875acba76a68/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/3e3726f82e97d4aa4040c9fa0497717824bd8ab5/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/b360abe694d11319091362b4a22cff48ed01c267/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/1f6074a163d20015ec1ce3acfae560678845f668/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/cafc32560963e1297c5040d9ee0cb53385db9fb7/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/935c8a86dda8460b1ebfaa8dba47910936a550df/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/8f080a0b98160915bce14a732de322fa022073c8/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/a1e2546df146871bb448ed53d2778a959dd54fee/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/c1010e29a3a95f3ebf6de652230c271cdc650f88/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/33ecd145324da5e4741efef8867d7ee7be3740cf/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/c47d1bb426a962095ca5093a9b7c0f578fb6cab6/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/86de16027669c14cac6e92a22333d296841ac571/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/3cbe029209857c4d01843e5c37015258da5a2855/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/4b05521da70e0682f18953a0a69e89ed6380f87a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/06f74911bf117301406e51eb1c9767bd/raw/6a6ce779af94fceafa091c23ab0ecfd4b0feb25f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/1895432b20672dfc0fa25b91ec44ba61bdc0a60f/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/0b3d638d2ebc79e7adfb3d1f2f4f10d536ab6de5/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/721d73f61cb30ae41d6e8028444a375c5e2d8651/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/6055347c9d5bed63df2599f315f407c3db933151/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/4e43cb8d66eb05d29d572f597552d958c30c3017/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/100e156fec83d08a3fb846fc51aa310183aa14a6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/b0ca324d3545bdd49a69d3a57ee35263eece426d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/03f278eec2f20d823ff029f6176716c3c1de6c77/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/c701d1a67d9a680746decbc087661abf54e855e7/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/359061689fe81e55af2ee2fd1a287e35840066bc/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/6f9cf643d1df5aae258dd59769a4e38a1e774c41/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/908b7e00fbc1664ac41c1012e2ac07f4e80eb65e/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/39a6d319521c5e4efd1f305f18b0f3bd0692a320/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/ff5109c499dabccdfc226ad12256d1c7340ae431/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/c6209ecbaaa71f317fa6eaf52e1049e36f5f9c1b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/5f3a960b3432657958aae7b2f100ad394fc75ad2/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/0487a4514e042116b4f366afbe73aa58547166e3/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/e035efeb3339ac6eb0d4692b06459e749fa03c82/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/57a978194e15be4904c05cb38b85774e268dfb98/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/609498e0c157a6148f1588f9c9396306d197900a/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/85c70123992eb5ae310ba83e6a7a8f3efa20743d/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/9ab14004808a780028b7d64c2ed2d7255c0f52ac/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/7dea3576bcdf71893f386e31da2fcecd6320c569/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/251075b6d0ce4f2dd5986c59e8929b538be25a6d/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ebc102a819650fedb0042c01d760e0bc/raw/bcf7c70b58088946135b65a1f44389a182cc5f4f/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
bot:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/2e7f98d5b649d32402daa9bc03edd42d121458e1/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/5ed66aab645f0fdb540f2c8d0a5548d5e13c9b87/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/0fc89dd19257a43250a33019a7d593184eb86ebc/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/ebf0910ba40ee863c44648c07bdd761c6469749f/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/6a4882cb66f76eb5218cecbfd1681f0db8bffd25/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/dddaf718a9027bc8de5a7c138eadae503d7567fd/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/c2085a1e89d786ccbf36b6d3b0985e35e2c02d77/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/ee3fe2882a588597ca23854066f58af2cfdc31f3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/5a8a0ab97818ff938bb55881739b7c0fc137ed4f/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/bdde44fa838747e0923b3e2af9576a2c567c7710/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/52c00580c34dce5582d024aa8151a135b944f858/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/4bb16dc57962d588cb3d9dde3c42471cf9dc2dec/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/47768053cf2dc8a5857f9e0620cdd544f3522ef7/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/47567129cf518866bc89509730ade519a81b9f19/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/ac7ff74f7bc3203ececae1af2f4f1cd105ca3eaa/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/fb8589c6b916230565c4d4e9c8a4164236bfaad8/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/8b20b7dd0d210e6c06563bd1ffe7171d977bf26a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/846498e5769b46ed36a1333f630db5bc5cfcc6b3/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/6fffe94a33186a9738251cb66dc3ec9adc03f750/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/84981f171fc710065cf89dfd485116abc5bf7873/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/f0c5e7c2078987369158ab1e5a15a3319327d0ae/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/e085d4be2baebd825e6d1b3e39ddb8f90aac5d0c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/445f8374f555c40b4bf38ad3aa2e095f102af2ca/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/6464ba6f27ee51b17277c71da005b0681f03045e/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bef257fecc6bbb45063f20f0f4199280/raw/7d8f4ae3f65affa9c24b0d2f5eb69f09c6d9fcc5/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/ucs/memory/memtype_cache.c [hunk 2]
```diff
@@ -113,20 +113,45 @@ UCS_PROFILE_FUNC_VOID(ucs_memtype_cache_update_internal,
...
                              &region_list);
-    ucs_list_for_each(region, &region_list, list) {
+    ucs_list_for_each_safe(region, tmp, &region_list, list) {
+        if (action == UCS_MEMTYPE_CACHE_ACTION_SET_MEMTYPE) {
+            if (region->mem_type == mem_type) {
+                start = ucs_min(start, region->super.start);
+                end   = ucs_max(end, region->super.end);
+            } else if ((region->super.end < start) ||
+                       (region->super.start >= end)) {
+                /* can't merge them as they have different memory types */
```
Comment (yosefe) [inline src/ucs/memory/memtype_cache.c]: /* ignore regions which are not really overlapping and can't be merged because of different memory types */

File: src/ucs/memory/memtype_cache.c [hunk 3]
```diff
@@ -201,23 +226,49 @@ UCS_PROFILE_FUNC(ucs_status_t, ucs_memtype_cache_lookup,
...
 
-    region      = ucs_derived_of(pgt_region, ucs_memtype_cache_region_t);
-    *mem_type_p = region->mem_type;
-    status      = UCS_OK;
+        region = ucs_derived_of(pgt_region, ucs_memtype_cache_region_t);
+        if (region->mem_type == UCS_MEMORY_TYPE_LAST) {
+            unkwn_mem_type = 1;
+        } else if (ucs_unlikely((*mem_type_p != UCS_MEMORY_TYPE_LAST) &&
+                                (*mem_type_p != region->mem_type))) {
+            ucs_error("0x%lx..0x%lx (mem_type %s) and 0x%lx..0x%lx "
```
Comment (yosefe) [inline src/ucs/memory/memtype_cache.c]: why needed to change the lookup function?

File: src/ucs/memory/memtype_cache.c [hunk 4]
```diff
@@ -113,20 +113,45 @@ UCS_PROFILE_FUNC_VOID(ucs_memtype_cache_update_internal,
...
 
+    if (action == UCS_MEMTYPE_CACHE_ACTION_SET_MEMTYPE) {
+        /* try to find regions that are contiguous and instersected
+         * with current one */
+        search_start = start - 1;
+        search_end   = end;
+    } else {
+        /* try to find regions that are instersected with current one */
+        search_start = start;
+        search_end   = end - 1;
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: yes, good catch
fixed

File: src/ucs/memory/memtype_cache.c [hunk 5]
```diff
@@ -113,20 +113,45 @@ UCS_PROFILE_FUNC_VOID(ucs_memtype_cache_update_internal,
...
     /* find and remove all regions which intersect with new one */
-    ucs_pgtable_search_range(&memtype_cache->pgtable, start, end - 1,
+    ucs_pgtable_search_range(&memtype_cache->pgtable, search_start, search_end,
                              ucs_memtype_cache_region_collect_callback,
                              &region_list);
-    ucs_list_for_each(region, &region_list, list) {
+    ucs_list_for_each_safe(region, tmp, &region_list, list) {
+        if (action == UCS_MEMTYPE_CACHE_ACTION_SET_MEMTYPE) {
+            if (region->mem_type == mem_type) {
+                start = ucs_min(start, region->super.start);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: done

File: src/ucs/memory/memtype_cache.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: fixed

File: src/ucs/memory/memtype_cache.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: we don't merge regions that have exact and unknown memory type,
but we want to report them to a user if a user's region consists of multiple regions (when at least one of them is unknown). we will report LAST and UCP will do memory type detection and then will update MemType Cache

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/549257cf3cefe5849f56ea320be6f01d2e27b6e5/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/6005d782bf48aa23c57ff370333b89a5cf1c4298/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/c2316ff18c3c58533c10b679ae573cdfe2712b42/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/cc5daa169db8bdbee767e2205435ab97515bf5e4/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/4e3e972a3325cee929dd99008ff5a2f4622e6ef5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/6bdac50536c1a148bc93bbfe1bdde1e5a838d4d5/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/3d160f7eaf91c023c42c29d53a8d11de3e41264b/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/18575580cee49ebca0a4fb2a3a6692525499e441/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/b64265aa0997b4d3ef9defe0af4906ee78624929/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/fc13cd9e069682121d0a0269e30ae2d988e95909/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/0ae7e6ac48442141744ee76ee29764423ab0161b/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/102a903b4065edd27063a1700abe5c500b7ad794/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/dfa248fc652fc5ae518f8c25cda91cee8765c4a2/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/2118b93411320dcad142329dbf207665504cb017/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/10b6179059e3aa824ec2e1e67db32b9c2f87de5a/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/3ac3cfdc037064bb60903778831667fc8789324f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/e1daf1da767b08b79684002bb9a9aa8e876a7aa3/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/54d1ad744c178527c9a448d4a76fadb96e4a54fc/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/635c8bf569f2165733a367e1abdc05b9037e4afb/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/523a42f9601f4078b3b0d7d4b729c661b59f1a40/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/c677f616b494db4a851162aaf29edbebdb3ffe00/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/fa897e5956f27082f2676267df7224b669b21127/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/9d304dc0070d55f49020c12890a74eb19c2a140d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/93cfb80a9f0ca703a54d4118e2ef03df3e73f926/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/8c6c7e9c2336cb13926fc985a44f64be/raw/2e0796d27833ee1fcbff4368e92e47c41665c50a/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@yosefe could you review, pls?

File: src/ucs/memory/memtype_cache.c (hunk 3 above)
Comment (yosefe) [reply src/ucs/memory/memtype_cache.c]: i don't think this code really works for host memory case
pls check

Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: @yosefe this is common code for all memory types
btw, we don't do a lookup for HOST buffers in gtests (since malloc() interceptors don't add them to MemType Cache), so can't test them. can only simulate it by generating HOST memory allocations

Comment (yosefe) [reply src/ucs/memory/memtype_cache.c]: for host memory only start address is checked, if not found - we return NO_ELEM immediately. without checking other regions which may intersect.
also what happens if we hit LAST memory type with start address and then CUDA memory? seems an error will not be reported, but if the order is reverse then it will be reported

Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: > also what happens if we hit LAST memory type with start address and then CUDA memory? seems an error will not be reported, but if the order is reverse then it will be reported

lookup returns  `UCS_OK` and `*mem_type_p=LAST` in both cases

Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: removed lookup changes as per offline discussion

File: test/gtest/ucs/test_memtype_cache.cc [hunk 6]
```diff
@@ -197,7 +197,15 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
         }
     }
 
-private:
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: private -> protected?

File: test/gtest/ucs/test_memtype_cache.cc [hunk 7]
```diff
@@ -278,3 +286,109 @@ UCS_TEST_P(test_memtype_cache, diff_mem_types_diff_bufs_keep_mem) {
...
+
+    {
+        mem_buffer b(size, GetParam());
+
+        test_memtype_cache::init();
+
+        test_unknown_region_found(b);
+        test_region_not_found(b);
+
+        memtype_cache_update(b.ptr(), b.size(), GetParam());
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: in other tests we use b.mem_type() instead of GetParam()

File: test/gtest/ucs/test_memtype_cache.cc [hunk 8]
```diff
@@ -278,3 +286,109 @@ UCS_TEST_P(test_memtype_cache, diff_mem_types_diff_bufs_keep_mem) {
...
+
+    {
+        mem_buffer b(size, GetParam());
+
+        test_memtype_cache::init();
+
+        test_unknown_region_found(b);
+        test_region_not_found(b);
+
+        /* add two protions of the region that shares one adderss in order
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: add two adjacent regions

File: test/gtest/ucs/test_memtype_cache.cc [hunk 9]
```diff
@@ -278,3 +286,109 @@ UCS_TEST_P(test_memtype_cache, diff_mem_types_diff_bufs_keep_mem) {
...
+         * to get them merged in a MemType Cache (the last address of the
+         * 1st protion is eqaul to the first address of the 2nd portion): */
+        /* - add the 1st portion */
+        memtype_cache_update(b.ptr(), b.size() / 2, b.mem_type());
+        test_ptr_found(b.ptr(), b.size() / 2, b.mem_type());
+        /* - add the 2nd portion */
+        memtype_cache_update(UCS_PTR_BYTE_OFFSET(b.ptr(), b.size() / 2 - 1),
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: can we unite common code with lookup_merged_region
only difference seems that in once case they overlap in 1 byte?
we can pass "overlap_size" (0 or 1) as a parameter to a common helper function

File: test/gtest/ucs/test_memtype_cache.cc (hunk 6 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: this is not needed, `m_memtype_cache` has to be private

File: test/gtest/ucs/test_memtype_cache.cc (hunk 8 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: done

File: test/gtest/ucs/test_memtype_cache.cc (hunk 9 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: good catch, we can
done

File: test/gtest/ucs/test_memtype_cache.cc (hunk 7 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: fixed

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/b025136dbbeb79c6a2d8c01d9845394ed6855213/_main) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/c53ec29d8a736acf0e6b09470ba90f0ccc1f6e45/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/b33638be467ec44aaf37aa50251245254f3b7dbe/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/3b168a1c0144ebda6a7d465c0d3600ab20554b15/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/3ebca294835d4915baed2d7c042a35890fe5ed36/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/dac49781bc082a95910b35d6cdd22cf85338412d/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/46f6bad2d8866fbfd7fbb87bf9cbdb4ec0912469/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/707443d6e0c2297af73032cdc9e2dcfad37677d4/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/587c41ab60d2b38b0f67f9c13123ec25349440a5/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/d42f9644aab02f83557224610a1202c10115b65f/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/8c3b4b1f36583e2f5f2b723553cc569a83da55e2/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/ca2474d6f9b83db1f478d911e293e49d4c1e99c3/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/f09bea713293bfad31ec071039f720ed281fbddb/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/346d2cf76e1a8b1afcb1ab0c6b2d6647e2e56384/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/5e760b72986a6470ae5b71872fd6cabfb4176ce8/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/6e5c1b22cb3d4cce73a28099702289aa02732597/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/be25b13c264da9ac761cc051198cfb7588bc156e/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/ec275cddcb997acc13c3d88576b59a80f7dedb52/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/c653157e3b8e023d267137bc57925b017091d678/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/1f07f2aa58d8c5bcee304d957627c4c164b58f04/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/cf23a1c6cee44cb7e3a2aaf377ce42a4165c5b74/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/72a30c4ff407d4d572c2e272fdbc02561aaf716c/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/0cd563a2b91cdb565925664cc3c36437faeece97/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/0836a1e614e675c2adb1f807f7b831372380209d/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/64bdb4a6697d9625468e19a09aad9ad4/raw/79e407f7cecbb666f390ddc1682e0348e3c16966/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/1d274413d997b3cbeaef633cc347e29220834a35/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/4b9bfb6b366e5c7e4ffb935bd01f54005ec839ec/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/a8b1df59fbbdb56376bccc36eea6e1c138684c1f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/bba0a71cd6d2f641f2c4481ea702ee315a1d055b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/bc23a9e5cfecd23460cb04acfc879067a45ac3a1/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/bfc3700a1f45d104fe57101ea93a861be38be7e0/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/4fd04592655e5f0a93bb03e0401c113be1fbb958/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/df61e3366b64bbcdcd0672f7a34668b5c48fbdd7/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/a0de0e57413d224431f6b69addb503f870c76c5b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/ca5ad7fc12b9a0a945589b788b825015521cb6a7/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/c9174edadd0c4328c1cfbde6c5ac7b64c76c3f42/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/0a09756f5814b4e03c725ca4629c7500a6e1e702/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/08ef182394bd0256359ffb5dd334d94f512289d4/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/21b22825d2b91ce09d0252946a0a956845861c9a/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/135247b0797af27b24d93970d269fe1a35d43138/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/34f74ca686e220e0feaa8b65e08b1fd0da6dd0a9/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/600ad36a57a1c22cc2128cce79ed09f0669baea3/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/cd264eee67bba0f6c3f6faa66d8fda7bf4a93b73/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/1ac5f0066dca564e69b5fee450d077fdaf45b22e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/628d08a7d91ee481dbe974fe42590e902b306104/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/728b1d7406d381e20739d5077ce9a8e3746aa4bd/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/f2e685bac278d85cca661f8338b7df7723549006/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/9a7395b0128c6113592fdc7a098ee91a7dd6a1ed/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/e656c98feef9c9616556899aa1028f3f526898bd/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d25e69b49ef7c00e342f901e9f2ea077/raw/06e200a583a3ec067404e64f20d8ceef46f44371/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: test/gtest/ucs/test_memtype_cache.cc [hunk 10]
```diff
@@ -337,19 +356,7 @@ UCS_TEST_P(test_memtype_cache_deferred_create, allocate_and_update_portions) {
...
-        memtype_cache_update(b.ptr(), b.size() / 2, b.mem_type());
-        test_ptr_found(b.ptr(), b.size() / 2, b.mem_type());
-        /* - add the 2nd portion */
-        memtype_cache_update(UCS_PTR_BYTE_OFFSET(b.ptr(), b.size() / 2 - 1),
-                             b.size() / 2 + 1, b.mem_type());
-        test_ptr_found(b.ptr(), b.size() / 2, b.mem_type());
-
-        /* check that able to find the entire region */ 
-        test_region_found(b);
+        test_adjacent_regions(b, 1);
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: there is still code duplication between the tests which could be placed in test_adjacent_regions

Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: @yosefe introduced single function for 3 tests that can test adjacent regions when requested by a test thru parameter

File: test/gtest/ucs/test_memtype_cache.cc [hunk 11]
```diff
@@ -278,3 +291,69 @@ UCS_TEST_P(test_memtype_cache, diff_mem_types_diff_bufs_keep_mem) {
...
+
+    void test_unknown_region_found(const mem_buffer &b) const {
+        if (b.mem_type() == UCS_MEMORY_TYPE_HOST) {
+            return;
+        }
+
+        test_ptr_found(b.ptr(), b.size(), UCS_MEMORY_TYPE_LAST);
+    }
+
+    void test_alloc_before_init(size_t buf_size, bool test_adjacent = false,
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: ok, that looks better.
no need to have default values for params, pass them explicitly.

File: test/gtest/ucs/test_memtype_cache.cc [hunk 12]
```diff
@@ -278,3 +291,69 @@ UCS_TEST_P(test_memtype_cache, diff_mem_types_diff_bufs_keep_mem) {
...
                         ::testing::ValuesIn(mem_buffer::supported_mem_types()));
+
+class test_memtype_cache_deferred_create : public test_memtype_cache {
+protected:
+    virtual void init() {
+        /* do nothing */
+    }
+
+    void test_unknown_region_found(const mem_buffer &b) const {
+        if (b.mem_type() == UCS_MEMORY_TYPE_HOST) {
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: if memtype is host should we expect that ptr is *NOT* found?

Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: yes, let's check it

File: test/gtest/ucs/test_memtype_cache.cc (hunk 11 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: done

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 16 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/10fdb30201b252d3a1f10589f52fae8d9bcc34da/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/01aaecf16b322504fad4f2f6213bca1181534e4b/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/ecc1d4b8db0339d6ffc306f76a403a60ee857756/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/483f3e908d94c3d83a1af981405175b48ca08a62/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/5c4401701788cc1587355873e4bac31fc1f4f1f9/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/2a13e5f7444dbd1e89143d0e8ede02a0ffe00ed3/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/3d2fa74ec641d52e2bf32a47906bbb9b0f6c78ea/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/879e5191e9fe8ff50290693e38c2b67be02c8d72/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/99a431ceab4bbaee4ee3782dcdd9bdb4dc9d00c7/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/099428a5df59bcc5f6e7bcbf810a792581060e6e/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/767472c4ef971585b388575466e15def604e68a4/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/0e8c34be5e30584449929d19ee150b50ace3c489/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/08f128ab1718eb91d824869f5824f2cdcc234018/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/999ca33a597e5193d55d30eeb3f74eb88f73f76c/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/98ff0c6e2be2174c288a90ae85dbff20eba6da67/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e7f6743ed5afb08ad83a62c5b6049e94/raw/89eb079a226e123f7ac0d2cd85f5327f839aecf9/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/c1a32cf47e037cca2d4f549b92074a261bca9d46/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/e0649c08e59a947333f378c42b67d37b1ba56a1e/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/acecaff7152dff0a5d15c75c1b9366a87414747a/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/273b953967994b4040e72c3dc48d024793acb874/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/04d9cc128bb9f653d19fc86fe231e05ff48fbc8c/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/f0f90dcbbc6ec34d69d3b136d53a00401364eb1d/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/c7e6f810fefbcae14167c88118f5e9d46d6e1121/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/68bfb3c666711553c760ae909cbf2c47c8e0c20a/hpc-arm-hwi-jenkins_W2) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/f578d197374cb3cc383616544fc0b6f905489dc3/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/6b65387b1b9409219e0207ffae7afa037bb62569/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/8e76e82f7d5e92cd0d7a254d71341142f70c015b/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/19ccd5df228106fcdb37f629fbf896ba13a09306/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/4370cead9135dd9f7c88c016698d412bb71c9084/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/6d9375e2fe5a0b45003755817905ff1e49c27074/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/45ce27a8f4c9db219a2f5555e9bd2ecf22a4d5d9/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/add0234e1af0545116b72dd88cd99abde94322bf/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/85852dd509c5c86c4ee7338a3e8779c03f63e935/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/c97ef92f0ea7ddad046ec651136f27a1a7c17483/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/f47a7f24a6304951ceb1e3ba6cee8fa9e93d196d/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/6ff0636f39fa5555eb48ea2a9bc59b6369f9657b/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/f0ba813eccede247bd2a40ce0a0b5b8b87f8ba50/hpc-test-node-new_W3) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/4e246cf57bd666d868e2926b4726dd27b0ceff32/r-vmb-ppc-jenkins_W0) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/74c5ab7cf805e26ab6c37552e3fa10d684deb188/r-vmb-ppc-jenkins_W1) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/d63660c2a36e954a9b31bbdc2f129a546ea8f2e3/r-vmb-ppc-jenkins_W2) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/5e540b25f861fe0b47fd2960676909a7/raw/624851fa9c69afb14495e1b44b7a85882c4ee22f/r-vmb-ppc-jenkins_W3) | :question: UNKNOWN

**Comment by dmitrygx** [comment]
@yosefe @Sergei-Lebedev the last commit of this PR fixes the following issue:
```
[1573459983.980646] [clx-mld-063:52971:0]   cuda_copy_md.c:85   UCX  ERROR cudaHostRegister(address, length, 0x01) is failed. ret:invalid argument
[1573459983.980663] [clx-mld-063:52971:0]         ucp_mm.c:121  UCX  ERROR failed to register address 0x7fb387081000 length 4915200 on md[0]=cuda_cpy: Input/output error
```

when user's CUDA buffer [0x7fb387081000 .. 0x7fb387531000] consists of two regions (`/proc/<pid>/maps` format):
```
7fb386e00000 - 7fb387200000 ---p 00000000 00:00 0
7fb387200000 - 7fb387531000 ---p 00000000 00:00 0
```
and the CUDA buffer is allocated before `ucp_init()`. those regions from `/proc/<pid>/maps` are added into MemType Cache as UNKNOWN (i.e. `UCS_MEMORY_TYPE_LAST`) when handling exsisting allocations.
We should merge those buffers into a single one when handling `SET_MEMTYPE` action in MemType Cache in order to successfully return them from the MemType Cache lookup procedure.

File: src/ucs/memory/memtype_cache.c [hunk 13]
```diff
@@ -132,9 +132,10 @@ UCS_PROFILE_FUNC_VOID(ucs_memtype_cache_update_internal,
                              &region_list);
     ucs_list_for_each_safe(region, tmp, &region_list, list) {
         if (action == UCS_MEMTYPE_CACHE_ACTION_SET_MEMTYPE) {
-            if (region->mem_type == mem_type) {
+            if ((region->mem_type == mem_type) ||
+                (region->mem_type == UCS_MEMORY_TYPE_LAST)) {
```
Comment (yosefe) [inline src/ucs/memory/memtype_cache.c]: not sure this is right, what if the "real" memory type of the adjacent UNKNOWN region is not really the same?

Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: let's do not add them as UNKNOWN
we discussed offline today that we can call `cudaPointerGetAttributes` when scanning memory mapping from `/proc/self/maps` and check whether this buffer is a CUDA buffer or not and them add it to MemType Cache with `UCS_MEMORY_TYPE_CUDA`, wdyt?

Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: also, we can add them as `UCS_MEMORY_TYPE_CUDA` or `UCS_MEMORY_TYPE_CUDA_MANAGED` checking `isManaged` flag from attributes

Comment (yosefe) [reply src/ucs/memory/memtype_cache.c]: > we discussed offline today that we can call `cudaPointerGetAttributes` when scanning memory mapping from `/proc/self/maps` and check whether this buffer is a CUDA buffer or not and them add it to MemType Cache with `UCS_MEMORY_TYPE_CUDA`, wdyt?

Let's try that

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/9a581f72dd352f6b4f35b5c00dadfa893bf0c57f/_main) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/2f0c366dd4925134a7abb45300a2a8f8596fcf20/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/94e6d39a6be8d1ce2bc96cd9ac1f7c5e2a7785ff/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/b3ce25e551c200b988da9abd434a8921029e1c35/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/c72808afe0853202c751e1060adc709e43adbd2d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/9cc970fa8e5bc147cbab6d7a925191126e303936/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/629fb67a264e3509ee69525873afa8913434faeb/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/7504a861bf940aecd67fcf121db816652d757c33/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/e9025b6b76b1a87c869466dfb8a18a22d49d97a8/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/4310fd452b8abe70689fe817e00a96ee029b1904/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/ae3609755ddeb8a64a27dd9ea6d6160a52dedc7a/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/a0ef7ae859596957ff383a216db4514cc434ba11/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/d93dc6c791f79ae7eb81ca40e9eb0c47abe64284/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/e731eca0a3e01b1d250cf19ca0172e2033e9a8a9/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/126b1fa5d5706c4573f3ec402e01f94290c5a154/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/fa2fe11647ea88731ae9b31dd63b3ba8c0507c8f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/297ead3fee0ea9ad633fc9fb68eb6ff3c7cc26ef/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/ab20e08bf2ac7f57ac898045499d67bf9ed64486/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/2c75d5edfe72c7d5ad4e6ee7a58c4a5d29c05f90/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/d5d3e73be8b7b35d1e2aacc5f8e7236b0d6bf373/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/5cd7667a016b5e7876987ddd4b7de30542509077/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/c62fbf2eeb7a153a20ce889c964efe406d0c022e/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/30e3fdf6ca1fb13cc55237e75348ff3b556036e7/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/a275089dc8fbafbab1a80d77c652b73dc12c00f0/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4e0fa52f18747899cc2a7617f9a67f06/raw/d01db0273bfcfd4d461554e8e89b474ee33f2809/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 1 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/af47b50b9bdce3e924faed7db7c4a08f/raw/e98d4a2a85f073f75ec549389e78f1af576840b5/_main) | :question: ABORTED

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 23 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/fbd49b561b79ca58e78aa5a76a148fcce86d7b93/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/3f6d42f422e88ef186c14373108c9e0220695d64/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/dbbed5314949673a6185aca205a602dfa935160e/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/90f7ba0b27dd97f8ebad186114337ad227b27a14/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/9020c3fa48351a1f181b43c7f4f9c6bd20ff9a62/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/f2c0e357498276c1ff557f555bf8233eaa3401af/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/a6366826440198e31f03e7fae878e22711847865/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/d9f91dff756da9b506128461952c80cb8f466fa5/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/5540d77ca322d456f7f1ced3a7de26ca1e9e09c7/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/ea795a31873fc851b0daa2ff7c8cc05005349e4c/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/5f462649dc25e25a56338fff1294ec27fc281236/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/febd570bd37d843246fce8e1eb9435b3adb6eff4/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/6f0783bbbb54a33d85124bd7456091c7faab52f1/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/b4dd3c9e4b8d56dd9198156b2c1264b893e5e52b/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/563ffdf5a073af873f9a3ea7a6bb46275ab017c7/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/967a1fd4643a2c9b303c141d68ecda37fcd96988/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/e3a2614a84a6faaafee543affad3f16757537adb/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/3316b5e03f70342fa0bbd092e190b344d5143e59/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/639a253765a3697443d6df23a0a4ff0320f53917/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/78c1dd9dfe2b6116bb718d6b69931d084c1cb730/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/b271e60a7b68f5a1a270a856fadbb4cb34c26025/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/ab038a7549d02f0b5af9f70019417efb6e61e15b/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/0a0d389e8e831bd052c5848e19945d01dc640e73/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/1dd556abe001bab84f7781509e360378715053f2/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/be0b1066f37b698ef88ef92f3f08482f/raw/bf18e80ba0b624b802dacbcfa32b51f3c1daf9b6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
bot:mlx:retest

File: src/ucs/memory/memtype_cache.c [hunk 14]
```diff
@@ -113,20 +113,48 @@ UCS_PROFILE_FUNC_VOID(ucs_memtype_cache_update_internal,
...
-    ucs_list_for_each(region, &region_list, list) {
+    ucs_list_for_each_safe(region, tmp, &region_list, list) {
+        if (action == UCS_MEMTYPE_CACHE_ACTION_SET_MEMTYPE) {
+            if (region->mem_type == mem_type) {
+                /* merge current region with overlapping or adjacent regions
+                 * of same memory type */
+                start = ucs_min(start, region->super.start);
+                end   = ucs_max(end, region->super.end);
+            } else if ((region->super.end < start) ||
+                       (region->super.start >= end)) {
```
Comment (brminich) [inline src/ucs/memory/memtype_cache.c]: is this situation possible?

File: src/ucs/memory/memtype_cache.c [hunk 15]
```diff
@@ -210,13 +238,14 @@ UCS_PROFILE_FUNC(ucs_status_t, ucs_memtype_cache_lookup,
...
                                   start);
-    if ((pgt_region == NULL) || (pgt_region->end < (start + size))) {
+    if (pgt_region == NULL) {
         status = UCS_ERR_NO_ELEM;
         goto out_unlock;
     }
 
     region      = ucs_derived_of(pgt_region, ucs_memtype_cache_region_t);
-    *mem_type_p = region->mem_type;
+    *mem_type_p = ((pgt_region->end >= (start + size)) ?
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: discussed offline
report LAST to ensure memory detection by UCP and then update Memtype Cache in order to optimize lookup, do merging

File: src/ucs/memory/memtype_cache.c (hunk 14 above)
Comment (dmitrygx) [reply src/ucs/memory/memtype_cache.c]: yes, I checked it
let's suppose that
1. `[0x100 .. 0x200]` - LAST
`[0x200 .. 0x300]` - CUDA (new region)
or
`[0x100 .. 0x200]` - CUDA (new region)
`[0x200 .. 0x300]` - LAST
they won't be merged since they have different memtypes, and we should save `[0x100 .. 0x200]` (or `[0x200 .. 0x300]`) in the Cache 
2. `[0x100 .. 0x200]` - LAST
`[0x150 .. 0x300]` - CUDA (new region)
it will be updated as:
`[0x100 .. 0x150]` - LAST
`[0x150 .. 0x300]` - CUDA

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 19-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/4be660d3989c2623a18c39d10d0658eac46ac499/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/b9525125fffa67677d16c4b4e2e082fd98250d1d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/9fbb9c4cf8aee5c240892183e6d10c1f4839ddf2/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/cfac050edb9ea73dfda06587bb4367df187ce3c4/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/0275808276fefac04860f98298e65171626d1a74/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/8239c6c9f7d3fe10aa135e6f0a00b8c5c2e533c2/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/0bc8775e370a298c695a6d40d707c43a443b6c6b/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/83eb7fd07896185523f737bd4f5474f8a91a7f0f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/b1765faa00a7d824a95d9af1eddddad28e5b2f27/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/e108b3557ce4b2ed63a5e9c152dc25d90908f6be/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/99bf7a1191031199e8b8fd81939fc49da7ce2621/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/4edf9b550eacdb5b448b6ac377a66a43e9fe0a09/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/8b76b1bc205a54afd7bd99bf24da72c0353e504c/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/4f234d56b84ddbdef073a9ea649e9292cbe0f5a4/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/232657882bd74a289410922f39118ec4a01dd842/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/7dc66b5128964f370da2661acecf660c5ec34516/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/98d2866c20cd45a4ec1d4052a5d8376912e6137b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/2cee85b07c8b552ed887c0b0d97aae5d5e130fcd/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/f86e391d58e7a3885878f999be54832f7130ac7e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/3ebf92e3021a90a25986f2b80507220c6bd3072c/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/f788d85f305df9930d3f94a894ec172653e1e3d7/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/703c019177010a76de1b8ddd8760c21b29da505f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/07ce10cb963acb662d38089afb773cfda38154bf/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/7d9e816144aed666aa5b56cf7feb14a4856dc842/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9ef69fb35fc0ecc96b2fcf1d37a5917d/raw/aca8f8cebe90b20a4f2bd86665e70ada483a52a9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@brminich @yosefe could you review pls?

File: src/ucs/memory/memtype_cache.c (hunk 14 above)
Comment (brminich) [reply src/ucs/memory/memtype_cache.c]: ok

File: test/gtest/ucs/test_memtype_cache.cc [hunk 16]
```diff
@@ -41,32 +59,22 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
...
         ucs_memory_type_t mem_type;
         ucs_status_t status = ucs_memtype_cache_lookup(m_memtype_cache, ptr,
                                                        size, &mem_type);
-        /* memory type should be not-found or unknown */
-        EXPECT_TRUE((status == UCS_ERR_NO_ELEM) ||
-                    ((status == UCS_OK) && (mem_type == UCS_MEMORY_TYPE_LAST)))
-              << "ptr=" << ptr << " size=" << size << ": "
-              << ucs_status_string(status)
-              << " memtype=" << mem_buffer::mem_type_name(mem_type);
+        check_lookup(ptr, size, status, mem_type, false);
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: can we put ucs_memtype_cache_lookup() call inide check_lookup() to reduce code dup?

File: test/gtest/ucs/test_memtype_cache.cc [hunk 17]
```diff
@@ -32,7 +32,25 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
         ucs::test_with_param<ucs_memory_type_t>::cleanup();
     }
 
-    void test_lookup_found(void *ptr, size_t size,
+    void check_lookup(const void *ptr, size_t size,
+                      ucs_status_t status,
+                      ucs_memory_type_t mem_type,
+                      bool found,
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc]: found means if you expect it to be found, or if it was actually found?
pls rename accordingly

Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: it means this:

> found means if you expect it to be found

renamed to `expect_found`

File: test/gtest/ucs/test_memtype_cache.cc (hunk 16 above)
Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: good catch, done

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 4 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 19-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/bc6c4a5926d550d7d690a8f000e7a389bf1a9839/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/b511a34a1f96186616d60d8f424eb2870eb5edb5/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/48834e09eef1e3dcb74927854198d92c16ea8d9f/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/68c0a734205a7f690ec2b1a65a4e437a5b38b810/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/66930ec68b3aceab0c19e61b2efa38ccb909b04a/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/d3a83955b51bc7d1d7f5302d675a09fd96995675/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/86a187253d79b93520dbe3b31a3cd8251d290405/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/ca911766628b188376f84ca9295bf6d6c1964dba/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/a7f8bc4377e1cb2d69e6acd4e4f26e5b2675ea22/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/eff9fa233e80c616ddf5416a19dd295e1c3165bf/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/efd8f4fbfdd104836be06185f56a902518460550/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/8d0c0c3d706a3ebc2d904f02373de1ccc9e3ad08/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/cc26709a61184464b82eee64708cb9c4a8d8c0b4/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/f686c713c31cbbd8de94d4b9628cb98764d11415/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/2d29ca3fc31f4d03f124a58ef2ab32d2b74cd6b1/hpc-test-node-new_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/16473e450cd3be5e0bd43ff040e8e0bb6279a3aa/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/0cce513979a65df31abab1aa142d00c6c347d9e7/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/179a1919ea1619ab694baebf671a3ccd12d59e1a/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/5bead14a1e45f04d69d0bbc1da1f50292d61daa5/hpc-test-node-new_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/8ab80b24fe3d0fac0f25b7e8af262de4d233337a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/b49efbfa3383e869b8ac5a841569a2d283542946/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/425d8d8f08c9cac1eaf4a6d9ed843e4431e67b46/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/c48c88f8a0ea6950d4bafa047948d5b8edf9f929/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/10b16b7bf4d87f31d7489637aec7a2e2b811db5a/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cef99c9c9edc4c93a68aa6b428cbef34/raw/2a5d1622641ad908e57f845b5914a1a7dd7bbb4a/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/b1ba7544e4a1e0a2a9914b267b0ee5fb0f3d30a0/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/cb89c356290831491d1233c4b36ca3f4d10d9c6a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/f9932b70a195822937504cc3b2fc272ca48c1439/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/d8c57f22bdd01bc69fa09b7efd0c6f43cb4fd949/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/7dc2be81fa3e2cee5cc0be4486cc6b29cddd85d0/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/a0406547a32ba7cb783fae678dc341d15d460120/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/dfc8a5d0544fe95ec1127ca1c8379a29b607d030/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/fca22806cbc65b221668bb5f30a8e4b98596ecbd/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/f03402e076b67b32dc33df9d774397396ddbe32d/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/0b8e730dcd468ea79c35210ce205ee4b4f82c5a6/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/f6bd131e44321123bc6947d604d6c37f181fba74/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/53bbdb6c0a33ece338eeb715cd655b4ec87a1f59/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/e3a172a868d2ef729dad1ccc23183019373a516a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/9aac10d6d5bbb39ed463fecbcbcdd2d04c0aa891/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/ebee007b7f96ab70bba3eb6b69ef69afa0bfacb9/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/8be477ab7032cc9aa4b36ea4e9bbf8e70bcbb534/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/b80470b840d9f8681710f557136904f1e04268f2/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/3a60e79db8a196990d7972198e23608319e37c17/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/b8188fcab6538bd8b1cee91046c731a3c052d36b/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/9ba9482ffcd2b9910b81ddb43ace38a0aa306ffe/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/1484a782f2cfe971454494efa575688f82c451f1/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/a6b37dc6864dd77af377f73e2ac516d117fcb840/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/d4b154b6e03c3d3be11096ad78c36b12f6a07c3b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/e9dfd19b05fd1e417192e0e804d4eeefd76423b0/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aed625784bfb573478d52761ddf0b0e6/raw/3b82a8b3fec304ae3f617e3c3ef64c47b55836d4/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
> pls squash

@yosefe done, waiting for testing completion

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 6 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/c36135254d5043494235702de183621ee182b808/_main) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/d9e8485bae2e6fce1020aeb9b764aaa51a572890/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/1dcf0beddb39909b1f537857c3bfa174a7666e72/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/18b87ed8171173970faff01a229b51403557c8c3/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/8cc2594bd0f3e73e687b759cd40c853e1592744e/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/918bf15ca99429b7eff9d004012233af8b03bd99/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/a6057ddea3d29717dc77b0c5ca9663c1b75d1721/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/87d9a7dced0c245d68d4dd24f92d1aee634f8972/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/87edcc77b94c7bd6e403c6fd4d46f968f7d4b0fd/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/41a0037473f2e4ecdf34983052657c92b40b7fed/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/61771b8fd347c166e10feabf3613a2449a632144/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/94a1ae4ed7436e0b7c4e6f1680aca87c0150c3ff/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/8532734a73d665ac987b0341bc54fb5bddcc7f95/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/5a14092e806747fa50cf4148c36dfab8657cf404/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/af3b9e70986ef7b2b2bfe62fbcd08dbfb1a57a32/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/581ee3bc2f804e4fd33a622a0d6d985c0e1efe87/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/b21a6ea77d0d1fff4a24bc6b1eb4b9fcc3c76713/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/3ccc5c9e106b57c829350caafa1db7954a0d6310/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/80f6c14351b7934f2341833b488f76cfd74d9181/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/33210b88381a4986165a1acd5df94617422494c1/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/98b5c802ee9b7df73e8b8d7815525288c9236574/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/60c3e6bff7cd81945f6093e831d5bbad5216ef58/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/a6765ac19613ffdb84fd4e25ef8da841b795b957/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/f505fd8995b7a6b187a8536dcaf89cc5f737de7b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/a895d314ddc342a48d555340df8bf255/raw/3c1475230c61b22d70e7e75ae83f22b2c3d25a98/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
> Mellanox CI: FAILED on 6 of 25 workers (click for details)

rnat
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 20-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/66bd80aa8c4a174f0bc3cb6d110075b51eefbeaa/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/8335f591864d533b73de9485561361c49f36d7e2/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/060292bfbec098312d8bcff35702374be0767996/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/baa2c9b0eea99b27dc13b529fa99ab00eb4dfec5/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/8d5b83b1efe2602ef6873d20811d55594210e3e5/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/6c7ebcb4a8f2a91d9e88de2cc144e3e00efbebb4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/bc45eebfcad530ca700b73231e662008bd137453/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/a985b6a36750c38db699500c265dfc383885c88d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/78fdf4f0305dc80862578e8d1355f001c163a4a0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/5535e7b58bedee227814d20ca7bf08946a0c9612/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/fccd8b540f91d4f22ca5ed67a5c2bbc2104a5a03/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/094c8dc36bd8d36e929f019e65a75e4e475cbe12/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/aca7cad1d0e0d43951afddb26adc6ca341558fe2/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/8eb9cbcc7db0008cc0c4ac57247a0fc77bf09174/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/b0068ae2ae30bd0fba6f53d06ed0076254cf0295/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/4340f16fd147684e74e2db7073b3ae58c80486ac/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/091d01bf6c622f73226d902f1c519957e2c099ee/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/c5b173fc50d983abdcb5b7017ff6c136aef523c4/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/cca64beb62414f31800ecaa47219b8a39498ffec/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/bce3eaa08c586eb480a49f9f36ec4b201b237564/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/f853c5fd5c292fae0f642fc5e0fd0053acf49a09/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/a1423e58187e98425529fc7c1dedc03c145ca5a2/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/bfc18ec986606cba5cd9248482348de898e57a08/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/99b628997842e93a0d4dedec21b2985776d6b60a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ff9b348287c829939bf09d36e306776d/raw/f7acf55cbb0e4a5fc4fdd739ead118955120e05c/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@yosefe ok to merge?
