### PR TITLE
UCT/TCP: Fix sending PUT ACK for uncompleted operations

### LINKED ISSUE #4676: Assertion failed on Cray with TCP transport
I am running on Cray XC50 with OpenMPI 4.0.2 compiled against ucx master (`./contrib/configure-devel --without-valgrind --enable-debug --enable-mt`). When using the TCP transport, `osu_bibw` often, but not always experiences the following problem:

```
# OSU MPI Bi-Directional Bandwidth Test v5.6.2
# Size      Bandwidth (MB/s)
1                       0.64
2                       1.30
4                       2.65
8                       5.26
16                     10.67
32                     20.31
64                     42.12
128                    80.65
256                   157.92
512                   301.74
1024                  570.04
2048                 1054.92
4096                 1893.81
8192                 2774.02
16384                4298.43
32768                5652.81
65536                5735.01
131072               5722.59
262144               6691.47
524288               6977.68
1048576              7030.51
2097152              7285.46
[nid03508:21694:0:21694]      tcp_ep.c:529  Assertion `ep->ctx_caps & (1ul << (UCT_TCP_EP_CTX_TYPE_PUT_TX_WAITING_ACK))' failed
==== backtrace (tid:  21694) ====
 0  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libucs.so.0(ucs_handle_error+0x73) [0x2aaab78ce652]
 1  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libucs.so.0(ucs_fatal_error_message+0xd0) [0x2aaab78cbb84]
 2  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libucs.so.0(+0x26d00) [0x2aaab78cbd00]
 3  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libuct.so.0(+0x1ec9b) [0x2aaab7684c9b]
 4  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libuct.so.0(+0x2043d) [0x2aaab768643d]
 5  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libuct.so.0(+0x2076d) [0x2aaab768676d]
 6  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libuct.so.0(+0x22f24) [0x2aaab7688f24]
 7  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libucs.so.0(ucs_event_set_wait+0x327) [0x2aaab78da998]
 8  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libuct.so.0(uct_tcp_iface_progress+0x71) [0x2aaab7688ff2]
 9  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libucp.so.0(+0x2f7c9) [0x2aaab73b57c9]
10  /scratch/snx3000/mkrotkie/software/ucx/master/lib/libucp.so.0(ucp_worker_progress+0x137) [0x2aaab73bbcda]
11  /scratch/snx3000/mkrotkie/software/openmpi/4.0.2-master/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_progress+0x17) [0x2aaab672c737]
12  /scratch/snx3000/mkrotkie/software/openmpi/4.0.2-master/lib/libopen-pal.so.40(opal_progress+0x2c) [0x2aaaac5b989c]
13  /scratch/snx3000/mkrotkie/software/openmpi/4.0.2-master/lib/libmpi.so.40(ompi_request_default_wait_all+0x235) [0x2aaaaaf3a9d5]
14  /scratch/snx3000/mkrotkie/software/openmpi/4.0.2-master/lib/libmpi.so.40(PMPI_Waitall+0x7f) [0x2aaaaaf7f89f]
15  /scratch/snx3000/mkrotkie/runs/run.dmitry/./osu_bibw() [0x402480]
16  /lib64/libc.so.6(__libc_start_main+0xea) [0x2aaaabd31f8a]
17  /scratch/snx3000/mkrotkie/runs/run.dmitry/./osu_bibw() [0x40266a]
=================================
[nid03508:21694:0:21694] Process frozen...
```
It happens at different (large) message sizes.

I have not managed to reproduce this with the uni-directional test `osu_bw`.

### LINKED ISSUE #4680: Seeing an error with osu_bw from OSU microbenchmarks using TCP transport at 4MB size
Hi,

Any thoughts on what this error is pointing to? I used master @  ac88b4246660cc9aeb8914f06142232339fc3c72 ./contrib/configure-devel with cuda support build and ran this between two VMs:
```
mpirun -np 2 -host vm1,vm2 --oversubscribe -npernode 1 \
 -x LD_LIBRARY_PATH --mca pml ucx --mca btl ^openib,smcuda \
 -x UCX_MEMTYPE_CACHE=n ./get_local_ompi_rank ./mpi/pt2pt/osu_bibw 
```

```
tcp_ep.c:529  

Assertion `ep->ctx_caps & (1ul << (UCT_TCP_EP_CTX_TYPE_PUT_TX_WAITING_ACK))' failed
==== backtrace (tid:  16766) ====
 0  /ucx/build/lib/libucs.so.0(ucs_handle_error+0x124) [0x7f3ae0cada74]
 1  /ucx/build/lib/libucs.so.0(ucs_fatal_error_message+0x71) [0x7f3ae0caa6e1]
 2  /ucx/build/lib/libucs.so.0(ucs_fatal_error_format+0xf2) [0x7f3ae0caa832]
 3  /ucx/build/lib/libuct.so.0(+0x1c2da) [0x7f3ae08492da]
 4  /ucx/build/lib/libuct.so.0(+0x1fe77) [0x7f3ae084ce77]
 5  /ucx/build/lib/libucs.so.0(ucs_event_set_wait+0xff) [0x7f3ae0cb8d9f]
 6  /ucx/build/lib/libuct.so.0(uct_tcp_iface_progress+0x94) [0x7f3ae084cf74]
 7  /ucx/build/lib/libucp.so.0(ucp_worker_progress+0x7a) [0x7f3ae0f0af4a]
 8  /ompi/build/lib/openmpi/mca_pml_ucx.so(mca_pml_ucx_progress+0x1a) [0x7f3ae1593d8f]
 9  /ompi/build/lib/libopen-pal.so.0(opal_progress+0x3f) [0x7f3b2038204e]
10  /ompi/build/lib/libmpi.so.0(+0x60c1d) [0x7f3b21a54c1d]
11  /ompi/build/lib/libmpi.so.0(ompi_request_default_wait_all+0x206) [0x7f3b21a556fb]
12  /ompi/build/lib/libmpi.so.0(PMPI_Waitall+0x172) [0x7f3b21ad42f1]
13  ./mpi/pt2pt/osu_bibw(+0x215b) [0x55ce3ec8815b]
14  /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7) [0x7f3b21624b97]
15  ./mpi/pt2pt/osu_bibw(+0x23ca) [0x55
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Don't complete uncompleted PUT operation (this is the last received PUT operation) during sending ACK for previous already completed PUT operation(s)

## Why ?

Fixes #4676 
Fixes #4680 
Assume the following situation:
1. Received PUT Req with sn=0
2. Handled PUT data for PUT with sn=0
3. Sending PUT ACK for PUT with sn=0, but it can't be completed due to some TX operation is using the TX buffer
4. Received PUT Req with sn=1
5. TX operation was completed, now can send PUT RX ACK - PUT RX ACK will be sent for PUT with sn=1 -- this is a bug

## How ?

Remove `UCT_TCP_EP_CTX_TYPE_PUT_RX_SENDING_ACK` when handling PUT Request + add assert that `UCT_TCP_EP_CTX_TYPE_PUT_RX_SENDING_ACK` flag is not set.
PUT ACK will be sent for all completed operation when the last operation was completed

### CODE REVIEW

**Comment by dmitrygx** [comment]
@angainor thank you for finding the bug.
could pls confirm that this patch fixes the bug found by you?

**Comment by angainor** [comment]
@dmitrygx Great! with the patch I did not manage to reproduce the problem after 22 runs. looks good!

**Comment by dmitrygx** [comment]
@angainor great! thank you for sharing the result!

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 22-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/89db888ba2e08f9f4a8ee51f085d3e125f756476/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/4588cd7be4b6a0a4af3ba7926e6641bd5690b885/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/ed2bc219fd9713678a5dc5e6155a6161bae6f8e1/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/d39324f8d7b2c3be6559cce7fa30c5f786f23926/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/3f423c4272d4ce128fc1d3e304fb1dc6c4151b12/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/380b7384ba01d0c538e8117188c4db5bb7b40667/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/ef28872c356eb3c30aebd5a4b74b7fb167325c54/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/d576035889a611b79fc8f05cd7182533a01f068b/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/1227ec4d222ace876726006d9af1e32b5434849b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/18e0878b0be78d166f1d3813aa32bad566d8e9ce/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/523323cb69aecd560fa1ec8f40edb2390100fcd8/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/9413e3d51196d587159d7e1a02c09967616641fe/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/bab3b434ee91fc43a0299df8418a4a48d0904238/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/3b0f378d1b0fcc454208c4f0cc3b236c688732bb/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/d3b9c1dbc1f44be85c519e9ee33e31e8d61c3553/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/60adc60a815ba66dbf24514752ecbe25d5215d00/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/af530a1d3b060008f8bae2bb32c57269e3ba2484/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/1f2e8ad1a6bc2e943c5aa78a4230884d609e2080/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/77a8506db8223f5774d02578f25f7160cfd66c3e/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/5523f1608bb033c982e710e1c699f70825f4798f/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/b120471229d41438bbe9abbb3575376de99a5edb/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/e700d15fe3d09c61937380287cadd282d0b6fbf0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/df7d56d67e8e6c0f91ef953e98fcf4d2f2ef0d0d/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/da533f38b685ca515c1379bf8cdc96d2f3587ed2/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4b0c0070606551c038e9fdc0b74b0e48/raw/5a1312346d9436915c7fafb3394b1bd9dc2890d6/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@hoopoepg @alinask @brminich could you review pls?

**Comment by dmitrygx** [comment]
@brminich @hoopoepg I've reproduced the issue in GTEST/UCP/TAG tests. Could you re-review pls?

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/3cf1123cb9980c9284de3466e2e39403547f396b/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/f0b87b6d8f75c8e3fd427695142ac4981aba5d23/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/2e0dc1cf3b788af8c2af3a2e2d781f3b68e8afc0/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/37fd0077d941e97b7be09d207e1af112e1b6630b/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/20e904a9fc98bdf2ca2cb4fd861d1908135867ed/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/815ea4c965104ec80c1bad2d0e0cbcbe479c9fa1/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/b6eccef0c40c3bf0e8cf65491e34a62e7af4d741/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/47fe87045231e3829eada429519b83f558f86070/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/c659f8e4a6bd7ea73a2302bb784f84e8ef9d13e4/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/0c68146908deafc73ce9cbf20501c66c651ec4c4/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/2241586da1f0b70da9922bffc4ff71a7214bd355/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/1b6611f7eb96d6c58b9eb52d433eed54e92a1d60/hpc-test-node-new_W3) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/f13e01486ace0acaa02d993a7a8fa9c83057deee/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/d767bb1bcee9ab0a8cd04ab54a15aaf24c88c6c3/hpc-test-node-gpu_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/c0c8c4afc2bd9d5f81992e6ef09034d3ac4b30f6/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/35691893a9737230dd70d779e520ba1484f7bcdf/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/ccf73ba751ddfe5d09b6aa681c216c24d3ffd7af/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/bb8a42dceeff5a12c650adbec40b8c62ccd6e647/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/4d6a0d1f32fcdeaec97b05d052a99f83695cc54b/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/ce401c0652c2a9b411d0a4412e6ed5f3aa9ee44f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/8cf7e3aaafd7665ba37233596fd8380d8465a50f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/d7143c9b0fe4c961907a0461284eeba31b0332e0/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/1e76ad7846b5233c696bf703ea48f8b083734bfd/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/352724114cff3c285ab7e59b3946e7a2c08d030a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/47e06310218ed9a9347e68716e582b21/raw/bc988ad38e1b786097fa2f5a589b1652a099264d/hpc-test-node-gpu_W2) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 23-Jan-2020

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/b5f8750838ed426f543accb896f4f605b8af6125/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/5dbaef1f8c2a36377ee78ede24c6400da3559e27/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/add39337cb10f7439f1bf6a5716c4f545e15e933/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/c8377e315ef3addcf37e402c0bcb9e9c2b28d8b6/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/38a218e46316663b446fc19443828f8e1d5d0bb6/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/e2b44f7da7fb9124f1e8bb286094b6cc6fc3d368/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/3925d63e50f25d120200fcfaf0e10740e0e6d159/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/281465b35a76edf1a318d83a622016f220247ab8/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/affd44454799db6864a742c168c72ab91f539172/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/dca03a8da320e84018a4e556333d9afbb3f8af0e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/f5b4a2557ffc23f8423db813e88552a2753d95b7/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/2c7adf60f8472659e5c90437b6bed8923d24e94e/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/24944413d8b03e711f249fab6cc320cdb5d30d32/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/02585cc85aec13b15afd1adbceac3d353c10cf9d/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/5b672b3b23daec739577b54d1c854b17ee4a7ee8/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/7d5452ba38d0966d08b62620e9c8d06196caddd0/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/3845a2e0c1865e1e1e1801ebc807e2876d05d16b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/ace05e7717921e108e1d31ea6abc6468682943e4/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/86f9d442e3381a7770e82340ce624b9176a43278/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/f8e1dbbb069834be787d6131a34e62f963778af0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/0ca206d54aa7bef4ebc164c11fb485061217958e/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/bdaed6169d37e45464acc506fca57ec9c5524a18/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/e72b22daf146487a1464cba1a2b66570b9f72273/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/f426a6754b0583c38c82af9d45142cc5b49f5b5f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/0d0b639008d9ff19d81c9c124a0031db/raw/6c575a8853cf3ed3f40b17db90441b04f48e0fed/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
> * Received PUT Req with sn=0
> * Handled PUT data for PUT with sn=0
> * Sending PUT ACK for PUT with sn=0, but it can't be completed due to some TX operation is using the TX buffer
> * Received PUT Req with sn=1
> * TX operation was completed, now can send PUT RX ACK - PUT RX ACK will be sent for PUT with sn=1 -- this is a bug

@dmitrygx is it possible to receive PUT req with sn=1 before receiving PUT reg with sn=0?

**Comment by dmitrygx** [comment]
> @dmitrygx is it possible to receive PUT req with sn=1 before receiving PUT reg with sn=0?

@yosefe no, this is not possible. The intent of this PR is fixing bug when we receive PUT ack for the uncompleted PUT operation

File: src/uct/tcp/tcp_ep.c [hunk 1]
```diff
@@ -844,6 +845,12 @@ static inline void uct_tcp_ep_handle_put_req(uct_tcp_ep_t *ep,
     ep->rx.offset += copied_length;
     ep->rx.put_sn  = put_req->sn;
 
+    /* Remove the flag that indicates that EP is sending PUT RX ACK in order
+     * to not ack the uncompleted PUT RX operation for which PUT REQ is being
+     * handled here. ACK for both operations will be sent after the completion
+     * of the last received PUT operation */
+    ep->ctx_caps &= ~UCS_BIT(UCT_TCP_EP_CTX_TYPE_PUT_RX_SENDING_ACK);
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c]: move it to uct_tcp_ep_handle_put_req(), after `ep->rx.put_sn  = put_req->sn;` :
we should prevent sending ACK after we increment the ep->tx.put_sn, until all data is received.

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: @yosefe this is already there

Comment (yosefe) [reply src/uct/tcp/tcp_ep.c]: right, sorry

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > right, sorry

;)

File: test/gtest/ucp/test_ucp_tag.cc [hunk 2]
```diff
@@ -178,153 +178,158 @@ int test_ucp_tag::get_worker_index(int buf_index)
...
 
 test_ucp_tag::request *
 test_ucp_tag::send_sync_nb(const void *buffer, size_t count, ucp_datatype_t datatype,
                            ucp_tag_t tag, int buf_index)
 {
-    int worker_index = get_worker_index(buf_index);
-
-    return (request*)ucp_tag_send_sync_nb(sender().ep(worker_index), buffer, count,
-                                          datatype, tag, send_callback);
+    return send(sender(), SEND_SYNC_NB, buffer, count, datatype, tag, buf_index);
```
Comment (yosefe) [inline test/gtest/ucp/test_ucp_tag.cc]: what is the point of common function if we have this wrapper anyway?

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_tag.cc]: the main intent of having a common function is to be able to send a data using any UCP entity (not only `sender()`)
also. the same is applicable for `recv()` common function

Comment (dmitrygx) [reply test/gtest/ucp/test_ucp_tag.cc]: `test_ucp_tag`'s functions (`send_nb`/`send_b`/`send_sync_nb` and `recv_nb`/`recv_b`) as wrappers for common ones were left in order to not change every place where they used

**Comment by dmitrygx** [comment]
bot:pipe:retest
