### PR TITLE
UCP/CORE/WIREUP: Add missing async blocks

### LINKED ISSUE #6214: tcp/test_ucp_sockaddr_protocols_err.tag_rndv_unexp_put_scheme/4 failed on sputnik4
```
2021-01-27T06:26:20.9991226Z [ RUN      ] tcp/test_ucp_sockaddr_protocols_err.tag_rndv_unexp_put_scheme/4 <tcp/bidi_stop>
2021-01-27T06:26:21.0182979Z [     INFO ] server listening on 2.1.4.4:44253
2021-01-27T06:26:21.0229904Z [sputnik4:23310:0:23310]      wireup.c:1032 Assertion `new_key->wireup_msg_lane == ((ucp_lane_index_t)-1)' failed
2021-01-27T06:26:21.7245196Z 
2021-01-27T06:26:21.7248115Z /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c: [ ucp_wireup_check_config_intersect() ]
2021-01-27T06:26:21.7249456Z       ...
2021-01-27T06:26:21.7250927Z      1029     /* wireup lane hasn't been selected by the new configuration: only this
2021-01-27T06:26:21.7252590Z      1030      * function should select it */
2021-01-27T06:26:21.7254069Z      1031     ucs_assert(new_key->wireup_msg_lane == UCP_NULL_LANE);
2021-01-27T06:26:21.7255153Z ==>  1032 
2021-01-27T06:26:21.7256194Z      1033     /* set the correct WIREUP MSG lane in case of CM */
2021-01-27T06:26:21.7257716Z      1034     reuse_lane = reuse_lane_map[old_key->wireup_msg_lane];
2021-01-27T06:26:21.7258893Z      1035     if (reuse_lane != UCP_NULL_LANE) {
2021-01-27T06:26:21.7259789Z 
2021-01-27T06:26:22.4066229Z ==== backtrace (tid:  23310) ====
2021-01-27T06:26:22.4069497Z  0 0x000000000005ccb8 ucs_debug_print_backtrace()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucs/debug/debug.c:656
2021-01-27T06:26:22.4071660Z  1 0x00000000000a15b1 ucp_wireup_check_config_intersect()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:1032
2021-01-27T06:26:22.4073475Z  2 0x00000000000a15b1 ucp_wireup_connect_lane()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:858
2021-01-27T06:26:22.4075170Z  3 0x00000000000a15b1 ucp_wireup_init_lanes()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:1187
2021-01-27T06:26:22.4076935Z  4 0x00000000000a1cd7 ucp_wireup_init_lanes_by_request()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:363
2021-01-27T06:26:22.4078681Z  5 0x00000000000a1cd7 ucp_wireup_process_request()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:491
2021-01-27T06:26:22.4080385Z  6 0x00000000000a2bf1 ucp_wireup_msg_handler()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/wireup/wireup.c:664
2021-01-27T06:26:22.4082597Z  7 0x0000000000021e64 uct_iface_invoke_am()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/base/uct_iface.h:663
2021-01-27T06:26:22.4084313Z  8 0x0000000000021e64 uct_tcp_ep_comp_recv_am()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_ep.c:1158
2021-01-27T06:26:22.4086030Z  9 0x0000000000021e64 uct_tcp_ep_progress_am_rx()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_ep.c:1292
2021-01-27T06:26:22.4087725Z 10 0x0000000000021e64 uct_tcp_ep_progress_data_rx()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_ep.c:1389
2021-01-27T06:26:22.4089468Z 11 0x0000000000026854 uct_tcp_iface_handle_events()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_iface.c:232
2021-01-27T06:26:22.4091250Z 12 0x000000000006aac1 ucs_event_set_wait()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucs/sys/event_set.c:215
2021-01-27T06:26:22.4092953Z 13 0x0000000000026764 uct_tcp_iface_progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/tcp/tcp_iface.c:249
2021-01-27T06:26:22.4094667Z 14 0x000000000003e1fa ucs_callbackq_dispatch()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucs/datastruct/callbackq.h:211
2021-01-27T06:26:22.4096356Z 15 0x000000000003e1fa uct_worker_progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/uct/api/uct.h:2436
2021-01-27T06:26:22.4098041Z 16 0x000000000003e1fa ucp_worker_progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../src/ucp/core/ucp_worker.c:2407
2021-01-27T06:26:22.4100015Z 17 0x00000000008daeeb ucp_test_base::entity::progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:870
2021-01-27T06:26:22.4101868Z 18 0x00000000008daf97 ucp_test::progress()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:155
2021-01-27T06:26:22.4103654Z 19 0x00000000008dafeb ucp_test::short_progress_loop()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/ucp_test.cc:163
2021-01-27T06:26:22.4105577Z 20 0x00000000008c50ba test_ucp_sockaddr_protocols::do_unexp_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1080
2021-01-27T06:26:22.4107600Z 21 0x00000000008c50ba ucs::entities_storage<ucp_test_base::entity>::receiver()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.h:188
2021-01-27T06:26:22.4109602Z 22 0x00000000008c50ba test_ucp_sockaddr_protocols::do_unexp_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1081
2021-01-27T06:26:22.4111702Z 23 0x00000000008c5fae test_ucp_sockaddr_protocols::test_tag_send_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1186
2021-01-27T06:26:22.4113745Z 24 0x00000000008c5fae test_ucp_sockaddr_protocols::test_tag_send_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1187
2021-01-27T06:26:22.4115795Z 25 0x00000000008adb50 test_ucp_sockaddr_protocols_err::test_tag_send_recv()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1585
2021-01-27T06:26:22.4117965Z 26 0x00000000008adb50 test_ucp_sockaddr_protocols_err_tag_rndv_unexp_put_scheme_Test::test_body()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucp/test_ucp_sockaddr.cc:1649
2021-01-27T06:26:22.4119927Z 27 0x00000000005d8b66 ucs::test_base::run()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.cc:347
2021-01-27T06:26:22.4121805Z 28 0x00000000005d8b66 ucs::test_base::TestBodyProxy()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/test.cc:373
2021-01-27T06:26:22.4123874Z 29 0x00000000005ba429 HandleSehExceptionsInMethodIfSupported<testing::Test, void>()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3562
2021-01-27T06:26:22.4125803Z 30 0x00000000005ae66d testing::Test::Run()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3635
2021-01-27T06:26:22.4127774Z 31 0x00000000005ae745 testing::TestInfo::Run()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3812
2021-01-27T06:26:22.4129589Z 32 0x00000000005ae8af testing::TestCase::Run()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:3930
2021-01-27T06:26:22.4131557Z 33 0x00000000005b305d testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5808
2021-01-27T06:26:22.4133530Z 34 0x00000000005b3340 testing::internal::UnitTestImpl::RunAllTests()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest-all.cc:5725
2021-01-27T06:26:22.4135318Z 35 0x000000000054a2e8 RUN_ALL_TESTS()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/gtest.h:20059
2021-01-27T06:26:22.4136946Z 36 0x000000000054a2e8 main()  /scrap/azure/agent-04/AZP_WORKSPACE/1/s/contrib/../test/gtest/common/main.cc:102
2021-01-27T06:26:22.4138026Z 37 0x00000000000223d5 __libc_start_main()  ???:0
2021-01-27T06:26:22.4138890Z 38 0x00000000005989dd _start()  ???:0
2021-01-27T06:26:22.4139571Z =================================
```
Link to the job: https://dev.azure.com/ucfconsort/ucx/_build/results?buildId=12925&view=logs&j=29aeebdb-3078-5ca1-e7df-02da2ddf99b4&t=ccac58dc-e7b6-5bfe-6f92-cc68fc64c085
Link to the log: https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/12925/logs/184

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Add missing async blocks.

## Why ?

 Fixes #6214 (missed block/unblcok in ucp_listener_accept_cb_progress()).
+ Fixes missing locks when accessing `ep->flags` in:
- `ucp_worker_discard_uct_ep_flush_comp()`
- `ucp_wireup_msg_progress()`

## How ?

1. Update `UCP_AM_BCOPY_HANDLE_STATUS` macro to do user's exit action instead of `return ...`, fix all occurrences.
2. Update `ucp_wireup_msg_progress()` to do `goto out` instead of `return ...` to fix req and buffer leak and lack of async unblocking.
3. Wrap body of the following functions by `UCS_ASYNC_BLOCK`/`UCS_ASYNC_UNBLOCK`:
- `ucp_listener_accept_cb_progress()`
- `ucp_worker_discard_uct_ep_flush_comp()`
- `ucp_wireup_msg_progress()`

### CODE REVIEW

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by dmitrygx** [comment]
@evgeny-leksikov @rakhmets could you review pls?

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Review by evgeny-leksikov — APPROVED** [review]

**Comment by dmitrygx** [comment]
@brminich @hoopoepg could you review pls?

**Review by hoopoepg — APPROVED** [review]

**Review by rakhmets — APPROVED** [review]

**Comment by dmitrygx** [comment]
bot:pipe:retest

File: src/ucp/wireup/wireup.c [hunk 1]
```diff
@@ -100,11 +100,13 @@ static ucp_lane_index_t ucp_wireup_get_msg_lane(ucp_ep_h ep, uint8_t msg_type)
...
-    ucp_request_t *req = ucs_container_of(self, ucp_request_t, send.uct);
-    ucp_ep_h ep        = req->send.ep;
+    ucp_request_t *req  = ucs_container_of(self, ucp_request_t, send.uct);
+    ucp_ep_h ep         = req->send.ep;
+    ucs_status_t status = UCS_OK;
     ssize_t packed_len;
     unsigned am_flags;
-    ucs_status_t status;
+
+    UCS_ASYNC_BLOCK(&ep->worker->async);
```
Comment (brminich) [inline src/ucp/wireup/wireup.c:109]: what does it protect? can you please give potential raise scenario?
async is possible for UD, where UCT level is protected

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:109]: CM disconnected event which adds `UCP_EP_FLAG_DISCONNECT_CB_CALLED`, i.e. `ucp_cm_disconnect_cb()`
or `ucp_worker_set_ep_failed()` which adds `UCP_EP_FLAG_FAILED` flag

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:109]: CM disconnect and set_ep_failed could be called in async thread whereas sending WIREUP MSG is done in the main thread

**Comment by dmitrygx** [comment]
bot:pipe:retest

File: src/ucp/wireup/wireup.c [hunk 2]
```diff
@@ -153,10 +157,13 @@ ucs_status_t ucp_wireup_msg_progress(uct_pending_req_t *self)
...
     }
 
-out:
+out_free_req:
     ucs_free((void*)req->send.buffer);
     ucs_free(req);
-    return UCS_OK;
+out:
+    UCS_ASYNC_UNBLOCK(&ep->worker->async);
+    ucs_assert((status == UCS_OK) || (status == UCS_ERR_NO_RESOURCE));
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:165]: should be done by transports / pending_req_add

File: src/ucp/proto/proto_am.inl [hunk 3]
```diff
@@ -20,20 +20,22 @@
 
 #define UCP_STATUS_PENDING_SWITCH (UCS_ERR_LAST - 1)
 
-#define UCP_AM_BCOPY_HANDLE_STATUS(_multi, _status) \
+#define UCP_AM_BCOPY_HANDLE_STATUS(_multi, _status, _exit_action) \
```
Comment (yosefe) [inline src/ucp/proto/proto_am.inl:23]: can you pls document this macro: parameters, in which cases it calls _exit_action, etc

File: src/ucp/wireup/wireup.c (hunk 1 above)
Comment (yosefe) [reply src/ucp/wireup/wireup.c:109]: which data fields does this lock protect?

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:109]: `ep->flags`

File: src/ucp/proto/proto_am.inl (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/proto/proto_am.inl:34]: done

File: src/ucp/wireup/wireup.c (hunk 2 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup.c]: removed

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Review by yosefe — APPROVED** [review]

File: src/ucp/proto/proto_am.inl [hunk 4]
```diff
@@ -20,20 +20,33 @@
...
+/**
+ * @brief Handle status from AM Bcopy operation.
+ *
+ * @param [in]     _multi       Flags whether this is multi AM Bcopy or not.
+ * @param [in/out] _status      Completion status of send operation.
+ * @param [in/out] _exit_action Operation that should be done to stop macro
+ *                              execution, if a send operation completed:
+ *                              - for multi AM Bcopy with switcing to an another
+ *                                lane for pending.
+ *                              - with lack of resource status.
```
Comment (yosefe) [inline src/ucp/proto/proto_am.inl:32]: what is special about those 2 cases that they have exit action?
seems like a random choice of what case is handled by this macro vs. what is handler by the macro user

**Review by yosefe — CHANGES_REQUESTED** [review]

File: src/ucp/proto/proto_am.inl (hunk 4 above)
Comment (dmitrygx) [reply src/ucp/proto/proto_am.inl:32]: yes, I agree that this is not so clear
The special cases are about situations when operation is not completed 
I will think how to re-write it

File: src/ucp/proto/proto_am.inl [hunk 5]
```diff
@@ -35,19 +36,24 @@
     do { \
         if (_multi) { \
             if ((_status) == UCS_INPROGRESS) { \
-                return UCS_INPROGRESS; \
+                _status = UCS_OK; \
```
Comment (yosefe) [inline src/ucp/proto/proto_am.inl:39]: why? should be in progress

File: src/ucp/proto/proto_am.inl [hunk 6]
```diff
@@ -35,19 +36,24 @@
...
             ucs_assert((_status) != UCS_INPROGRESS); \
         } \
         \
         if (ucs_unlikely((_status) == UCS_ERR_NO_RESOURCE)) { \
             _status = UCS_ERR_NO_RESOURCE; \
-            _exit_action; \
+            goto out_exit; \
         } \
+        \
+        break; \
```
Comment (yosefe) [inline src/ucp/proto/proto_am.inl:54]: why need break?

File: src/ucp/proto/proto_am.inl [hunk 7]
```diff
@@ -35,19 +36,24 @@
...
+out_exit: \
```
Comment (yosefe) [inline src/ucp/proto/proto_am.inl:55]: why need common label?

**Review by yosefe — COMMENTED** [review]
still not clear what is the purpose of this macro
maybe remove it altogether?

**Comment by dmitrygx** [comment]
> still not clear what is the purpose of this macro
> maybe remove it altogether?

@yosefe removed the macro

**Review by brminich — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by dmitrygx** [comment]
@yosefe @brminich ok to merge?
