### PR TITLE
GTEST: A workaround for the GCC issue in FC35

### LINKED ISSUE #7705: Gtest build failure on Fedora 35 with inbox gcc
### Describe the bug
Gtest build failure on Fedora 35 with inbox gcc
```
 CXX      ucp/gtest-test_ucp_stream.o
../../../test/gtest/uct/uct_test.cc: In member function ‘bool uct_test::async_event_ctx::wait_for_event(uct_test::entity&, double)’:
../../../test/gtest/uct/uct_test.cc:1514:26: error: ‘int poll(pollfd*, nfds_t, int)’ writing 8 bytes into a region of size 4 overflows the destination [-Werror=stringop-overflow=]
 1514 |     int ret        = poll(&wakeup_fd, 1, timeout_ms);
      |                      ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/poll.h:1,
                 from ../../../test/gtest/uct/uct_test.h:15,
                 from ../../../test/gtest/uct/uct_test.cc:7:
/usr/include/sys/poll.h:38:9: note: destination object ‘pollfd::fd’ of size 4
   38 |     int fd;                     /* File descriptor to poll.  */
      |         ^~
/usr/include/sys/poll.h:38:9: note: destination object ‘pollfd::fd’ of size 4
/usr/include/sys/poll.h:54:12: note: in a call to function ‘int poll(pollfd*, nfds_t, int)’ declared with attribute ‘access (write_only, 1, 2)’
   54 | extern int poll (struct pollfd *__fds, nfds_t __nfds, int __timeout)
      |            ^~~~
  CXX      ucp/gtest-test_ucp_peer_failure.o

```

### Steps to Reproduce
- ``../configure --enable-gtest --enable-examples --with-valgrind --enable-profiling --enable-frame-pointer --enable-stats --enable-memtrack --enable-fault-injection --enable-debug-data --enable-mt --with-xpmem=/home/pavsha01/work/xpmem-install/ --prefix=/home/xxx/xxx/ucx-install/ --with-ugni PKG_CONFIG_PATH=:/home/xxx/xxx/ucx/build/../contrib/cray-ugni-mock PKG_CONFIG_TOP_BUILD_DIR=/home/xxx/xxx/ucx/build/..``

- Reproducible on master and v1.12.x branch

### Setup and versions
- Fedora release 35 (Thirty Five) , aarch64
- No rdma-core drivers/hardware
- gcc (GCC) 11.2.1 20210728 (Red Hat 11.2.1-1)

### PR DESCRIPTION
**Pull request by shamisp**
Fixes #7705

Signed-off-by: Pavel Shamis (Pasha) <pasharesearch@gmail.com>

### CODE REVIEW

**Review by yosefe — APPROVED** [review]

File: test/gtest/uct/uct_test.cc [hunk 1]
```diff
@@ -1494,24 +1494,27 @@ void uct_test::async_event_ctx::signal() {
...
+                                                         &local_fd.fd);
             ASSERT_UCS_OK(status);
         } else {
-            ucs_status_t status =
-                ucs_async_pipe_create(&aux_pipe);
+            ucs_status_t status = ucs_async_pipe_create(&aux_pipe);
             ASSERT_UCS_OK(status);
             aux_pipe_init = true;
-            wakeup_fd.fd = ucs_async_pipe_rfd(&aux_pipe);
+            local_fd.fd   = ucs_async_pipe_rfd(&aux_pipe);
```
Comment (yosefe) [inline test/gtest/uct/uct_test.cc:1511]: @shamisp this causes fd leaks and test failures
need to set wakeup_fd here. and copy to local_fd right before calling poll()

**Review by yosefe — CHANGES_REQUESTED** [review]

File: test/gtest/uct/uct_test.cc [hunk 2]
```diff
@@ -1494,24 +1494,27 @@ void uct_test::async_event_ctx::signal() {
 }
 
 bool uct_test::async_event_ctx::wait_for_event(entity &e, double timeout_sec) {
-    if (wakeup_fd.fd == -1) {
+    /* Caching fd locally to workaroud bug in gcc (GCC) 11.2.1 20210728 FC35
```
Comment (brminich) [inline test/gtest/uct/uct_test.cc:1497]: `workaround`

**Comment by shamisp** [comment]
@yosefe merge ?

**Review by yosefe — APPROVED** [review]
