### PR TITLE
UCS: Check rdtsc on the very first ucs_time call

### LINKED ISSUE #3087: [mtt] UCX Fatal: transport error: Endpoint timeout
Configuration:
```
OMPI: 4.0.1a1
MOFED: MLNX_OFED_LINUX-4.4-2.0.7.0
Module: hpcx-gcc-mt (2018-12-08)
Test module: none
Nodes: polar-sriov x4 (ppn=6(x4), nodelist=hpc-polar-01-vm[001-002],hpc-polar-02-vm[001-002])
```

MTT log: http://hpcweb.lab.mtl.com/hpc/mtr_scrap/users/mtt/scratch/hcol/20181209_115212_20832_13447_hpc-polar-01-vm001/html/test_stdout_S5IxYH.txt

Issue doesn't always reproduce. Had to use at least 20-30 iteration with NP=12, with NP=24 it appears more often.

Cmd (original np=24):
`mpirun -np 12 -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_0:1 -mca osc ucx -x UCX_IB_ADDR_TYPE=ib_global -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc_x,self,sm -x UCX_RC_MLX5_TM_ENABLE=n -mca pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 -mca pmix_base_collect_data 1 --map-by node /hpc/local/benchmarks/hpcx_install_2018-12-07/mtt-tests-gcc/installs/dbP8/tests/mpich_tests/mpich-mellanox.git/test/mpi/datatype/transpose-pack`

Output:
```sh
Mon Dec 10 08:18:05 2018[1,8]<stderr>:[hpc-polar-01-vm001:13210:0:13210]    ud_iface.c:732  UCX Fatal: transport error: Endpoint timeout
Mon Dec 10 08:18:05 2018[1,4]<stderr>:[hpc-polar-01-vm001:13209:0:13209]    ud_iface.c:732  UCX Fatal: transport error: Endpoint timeout
Mon Dec 10 08:18:05 2018[1,0]<stderr>:[hpc-polar-01-vm001:13208:0:13208]    ud_iface.c:732  UCX Fatal: transport error: Endpoint timeout
Mon Dec 10 08:18:05 2018[1,5]<stdout>: No Errors
Mon Dec 10 08:18:05 2018[1,1]<stdout>: No Errors
Mon Dec 10 08:18:05 2018[1,10]<stdout>: No Errors
Mon Dec 10 08:18:05 2018[1,6]<stdout>: No Errors
Mon Dec 10 08:18:05 2018[1,2]<stdout>: No Errors
Mon Dec 10 08:18:05 2018[1,9]<stdout>: No Errors
Mon Dec 10 08:18:05 2018[1,11]<stdout>: No Errors
Mon Dec 10 08:18:05 2018[1,7]<stdout>: No Errors
Mon Dec 10 08:18:05 2018[1,3]<stdout>: No Errors
Mon Dec 10 08:18:06 2018[1,4]<stderr>:
Mon Dec 10 08:18:06 2018[1,4]<stderr>:/hpc/local/benchmarks/hpcx_install_2018-12-09/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.c: [ uct_ud_ep_dis$
atch_err_comp() ]
Mon Dec 10 08:18:06 2018[1,4]<stderr>:      ...
Mon Dec 10 08:18:06 2018[1,8]<stderr>:
Mon Dec 10 08:18:06 2018[1,8]<stderr>:/hpc/local/benchmarks/hpcx_install_2018-12-09/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.c: [ uct_ud_ep_dis$
atch_err_comp() ]
Mon Dec 10 08:18:06 2018[1,8]<stderr>:      ...
Mon Dec 10 08:18:06 2018[1,0]<stderr>:
Mon Dec 10 08:18:06 2018[1,0]<stderr>:/hpc/local/benchmarks/hpcx_install_2018-12-09/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/ud/base/ud_iface.c: [ uct_ud_ep_dis$
atch_err_comp() ]
Mon Dec 10 08:18:06 2018[1,0]<stderr>:      ...
Mon Dec 10 08:18:06 2018[1,8]<stderr>:      729                                              skb->status);
Mon Dec 10 08:18:06 2018[1,8]<stderr>:      730     if (status != UCS_OK) {
Mon Dec 10 08:18:06 2018[1,8]<stderr>:      731         ucs_fatal("transport error: %s", ucs_status_string(status));
Mon Dec 10 08:18:06 2018[1,8]<stderr>:==>   732     }
Mon Dec 10 08:18:06 2018[1,8]<stderr>:      733 }
Mon Dec 10 08:18:06 2018[1,8]<stderr>:      734
Mon Dec 10 08:18:06 2018[1,8]<stderr>:      735 void uct_ud_iface_dispatch_async_comps_do(uct_ud_iface_t *iface)
```

### PR DESCRIPTION
**Pull request by brminich**
## What
fixes #3087 

## Why ?
The issue is that `ucs_arch_x86_enable_rdtsc` is initialized in `ucs_time_sec_value`. Thus, if `ucs_time` was called before `ucs_time_sec_value` (which is used by `ucs_time_to_sec`), it may provide completely different result than after  `ucs_arch_x86_enable_rdtsc` initialization. As example, it provoked false UD transport timeout in #3087

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8410/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@hoopoepg, plz review

File: src/ucs/arch/x86_64/cpu.c [hunk 1]
```diff
@@ -94,37 +102,48 @@ static double ucs_x86_tsc_freq_from_cpu_model()
...
+        freq = ucs_get_cpuinfo_clock_freq("cpu MHz", 1e6);
+    }
+
+    if (freq > 0.0) {
+        /* using rdtsc */
+        return freq;
+    }
+
+fallback:
+
```
Comment (hoopoepg) [inline src/ucs/arch/x86_64/cpu.c]: minor: extra empty line?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8411/ for details (Mellanox internal link).

**Comment by brminich** [comment]
@yosefe, plz check

File: src/ucs/arch/x86_64/cpu.c [hunk 2]
```diff
@@ -94,37 +102,47 @@ static double ucs_x86_tsc_freq_from_cpu_model()
...
-        result = ucs_x86_tsc_freq_from_cpu_model();
-        if (result == 0) {
-            /* Read clock speed from cpuinfo */
-            result = ucs_get_cpuinfo_clock_freq("cpu MHz", 1e6);
-        }
-        if ((result > 0.0) && ucs_arch_x86_enable_rdtsc) {
-            /* using rdtsc */
-            return result;
-        }
+    if (ret) {
```
Comment (yosefe) [inline src/ucs/arch/x86_64/cpu.c]: the space line before is now redundant

File: src/ucs/arch/x86_64/cpu.c [hunk 3]
```diff
@@ -18,7 +18,7 @@
 #define X86_CPUID_INVARIANT_TSC   0x80000007u
 
 
-int ucs_arch_x86_enable_rdtsc = 1;
+int ucs_arch_x86_enable_rdtsc = UCS_TRY;
```
Comment (yosefe) [inline src/ucs/arch/x86_64/cpu.c]: ucs_ternary_value_t

File: src/ucs/arch/x86_64/cpu.c [hunk 4]
```diff
@@ -94,37 +102,47 @@ static double ucs_x86_tsc_freq_from_cpu_model()
...
+        freq = ucs_get_cpuinfo_clock_freq("cpu MHz", 1e6);
+    }
+
+    if (freq > 0.0) {
+        /* using rdtsc */
+        return freq;
     }
 
-    /* fallback */
+fallback:
```
Comment (yosefe) [inline src/ucs/arch/x86_64/cpu.c]: seems there is a mismatch: the timer frequency depends on the result of ucs_get_cpuinfo_clock_freq(), while the decision of whether to call ucs_arch_generic_read_hres_clock() depends only on the result of ucs_x86_tsc_freq_from_cpu_model()

Comment (brminich) [reply src/ucs/arch/x86_64/cpu.c]: `ucs_get_cpuinfo_clock_freq` does not change the state of `ucs_arch_x86_enable_rdtsc`.

Comment (yosefe) [reply src/ucs/arch/x86_64/cpu.c]: this is the problem, ucs_get_cpuinfo_clock_freq() affects ucs_get_cpu_clocks_per_sec(), which is clock frequency, but does not affect ucs_arch_x86_enable_rdtsc, which is clock source. looks like there could be mismatch between clock source and assumed clock frequency?

Comment (brminich) [reply src/ucs/arch/x86_64/cpu.c]: was not this an intention? it worked the same way before, `ucs_get_cpuinfo_clock_freq()` did not change `ucs_arch_x86_enable_rdtsc`, we just took the max value. 
Results should be consistent anyway, because we always use the same clock  and its frequency values from the beginning.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8418/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8422/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8423/ for details (Mellanox internal link).

File: src/ucs/arch/x86_64/cpu.c [hunk 5]
```diff
@@ -94,37 +99,57 @@ static double ucs_x86_tsc_freq_from_cpu_model()
...
+    if (result > 0.0) {
+        return result;
+    }
+
+err_disable_rdtsc:
+    ucs_arch_x86_enable_rdtsc = UCS_NO;
+    return -1;
+}
+
+double ucs_arch_get_clocks_per_sec()
```
Comment (yosefe) [inline src/ucs/arch/x86_64/cpu.c]: maybe unite ucs_x86_init_tsc_freq() and ucs_arch_get_clocks_per_sec() to one function?

File: src/ucs/sys/sys.c [hunk 6]
```diff
@@ -932,7 +933,10 @@ double ucs_get_cpuinfo_clock_freq(const char *header, double scale)
     fclose(f);
 
     if (warn) {
-        ucs_warn("Conflicting CPU frequencies detected, using: %.2f", value);
+        level = ucs_global_opts.warn_inv_tsc ? UCS_LOG_LEVEL_WARN :
+                                               UCS_LOG_LEVEL_DEBUG;
+        ucs_log(level,
```
Comment (yosefe) [inline src/ucs/sys/sys.c]: maybe do some wrapper for the logging and checking warn_inv_tsc , e.g ucs_warn_inv_tsc() macro
it's used 3 times in the code

File: src/ucs/arch/x86_64/cpu.c (hunk 5 above)
Comment (brminich) [reply src/ucs/arch/x86_64/cpu.c]: I'd leave it as it is, because
- `ucs_arch_get_clocks_per_sec()` is a common function for different archs,  
- `ucs_x86_init_tsc_freq()` is a initialization part, which is used for getting time and we do not need to call  `ucs_arch_generic_get_clocks_per_sec` for it

Comment (yosefe) [reply src/ucs/arch/x86_64/cpu.c]: so, in `ucs_arch_get_clocks_per_sec()`, maybe better check the value of `ucs_arch_x86_enable_rdtsc` to in line 148 instead of 'freq' ?

Comment (brminich) [reply src/ucs/arch/x86_64/cpu.c]: but we have to get frequency in `ucs_arch_get_clocks_per_sec`, not the state of rdtsc

Comment (yosefe) [reply src/ucs/arch/x86_64/cpu.c]: return frequency, but use state of rdtsc to decide whether to call `ucs_arch_generic_get_clocks_per_sec()`

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8434/ for details (Mellanox internal link).

File: src/ucs/sys/sys.c [hunk 7]
```diff
@@ -933,14 +932,25 @@ double ucs_get_cpuinfo_clock_freq(const char *header, double scale)
...
-        ucs_log(level,
-                "Conflicting CPU frequencies detected, using: %.2f", value);
+        ucs_warn_inv_tsc("Conflicting CPU frequencies detected, using: %.2f",
+                         value);
     }
+
     return value * scale;
 }
 
+void ucs_warn_inv_tsc(const char *msg, ...)
```
Comment (yosefe) [inline src/ucs/sys/sys.c]: can we make it macro instead on inline function? would be simpler..

Comment (brminich) [reply src/ucs/sys/sys.c]: it's not inline (at least not requested and has declaration).
ok, will create macro instead

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8439/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/8444/ for details (Mellanox internal link).
