### PR TITLE
 UCT/RC/MLX5: Fix SRQ clean flow

### LINKED ISSUE #2328: ib_mlx5.c:438  Assertion `srq->tail == srq_info.tail' failed
When running
gtest --gtest_filter=rc_mlx5/test_uct_pending*
on hpc-test-node

Stacktrace
```
 0 0x00000000000338df uct_ib_mlx5_srq_cleanup()  /labhome/alexm/workspace/ucx/ucx/src/uct/ib/mlx5/ib_mlx5.c:437
 1 0x00000000000338df uct_ib_mlx5_get_srq_info()  /labhome/alexm/workspace/ucx/ucx/src/uct/ib/mlx5/ib_mlx5.c:111
 2 0x00000000000338df uct_ib_mlx5_srq_cleanup()  /labhome/alexm/workspace/ucx/ucx/src/uct/ib/mlx5/ib_mlx5.c:435
 3 0x0000000000059326 ucs_class_call_cleanup_chain()  /labhome/alexm/workspace/ucx/ucx/src/ucs/type/class.c:50
 4 0x00000000000520f0 uct_rc_mlx5_ep_t_delete()  /labhome/alexm/workspace/ucx/ucx/src/uct/ib/rc/accel/rc_mlx5_ep.c:608
 5 0x0000000000535ce2 ucs::handle<uct_ep*, void*>::release()  /labhome/alexm/workspace/ucx/ucx/test/gtest/./common/test_helpers.h:521
 6 0x00000000004790ca ucs::test_base::TearDownProxy()  /labhome/alexm/workspace/ucx/ucx/test/gtest/common/test.cc:247
 7 0x000000000046cd53 testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>()  /labhome/alexm/workspace/ucx/ucx/test/gtest/common/gtest-all.cc:3562
 8 0x000000000046119c testing::Test::Run()  /labhome/alexm/workspace/ucx/ucx/test/gtest/common/gtest-all.cc:3643
 9 0x000000000046129c testing::TestInfo::Run()  /labhome/alexm/workspace/ucx/ucx/test/gtest/common/gtest-all.cc:3812
10 0x00000000004613ff testing::TestCase::Run()  /labhome/alexm/workspace/ucx/ucx/test/gtest/common/gtest-all.cc:3930
11 0x0000000000465d97 testing::internal::UnitTestImpl::RunAllTests()  /labhome/alexm/workspace/ucx/ucx/test/gtest/common/gtest-all.cc:5802
12 0x000000000046609b testing::internal::UnitTestImpl::RunAllTests()  /labhome/alexm/workspace/ucx/ucx/test/gtest/common/gtest-all.cc:5719
13 0x000000000040f493 main()  /labhome/alexm/workspace/ucx/ucx/test/gtest/common/gtest.h:20059
14 0x0000000000021c05 __libc_start_main()  ???:0
15 0x000000000044b958 _start()  ???:0
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #2328

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6356/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6358/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6359/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6360/ for details (Mellanox internal link).

**Comment by brminich** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6362/ for details (Mellanox internal link).

File: src/uct/ib/dc/accel/dc_mlx5.c [hunk 1]
```diff
@@ -960,6 +960,7 @@ static uct_dc_iface_ops_t uct_dc_mlx5_iface_ops = {
     },
     .fc_ctrl                  = uct_dc_mlx5_ep_fc_ctrl,
     .fc_handler               = uct_dc_iface_fc_handler,
+    .destroy_qp               = uct_rc_iface_qp_destroy
```
Comment (brminich) [inline src/uct/ib/dc/accel/dc_mlx5.c]: why is mlx5_qp_destroy not relevant for dc_x?

File: src/uct/ib/rc/base/rc_ep.c [hunk 2]
```diff
@@ -216,7 +211,7 @@ static UCS_CLASS_CLEANUP_FUNC(uct_rc_ep_t)
     uct_rc_ep_tag_qp_destroy(self);
```
Comment (brminich) [inline src/uct/ib/rc/base/rc_ep.c]: should not we call ` ucs_derived_of(iface->super.ops, uct_rc_iface_ops_t)->destroy_qp` for tag qp as well?
some RNDVs may be in progress

Comment (yosefe) [reply src/uct/ib/rc/base/rc_ep.c]: yes

File: src/uct/ib/dc/accel/dc_mlx5.c (hunk 1 above)
Comment (yosefe) [reply src/uct/ib/dc/accel/dc_mlx5.c]: because for DC, there is no receive side, so there is no situation when destroying the QP generates SRQ-related CQEs

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6364/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6365/ for details (Mellanox internal link).

**Comment by MrBr-github** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6366/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6367/ for details (Mellanox internal link).

**Comment by MrBr-github** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6369/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6386/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6389/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6393/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6394/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6396/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/6400/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@brminich pls take a look
