### PR TITLE
UCT: fix #1502, #1513

### LINKED ISSUE #1502: Hang in MPI_Finalize with UCX_TLS=rc[_x],sm on the probe-unexp test
Command to reproduce:

> mpirun -x -np 2496 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_NET_DEVICES=mlx5_0:1 -mca btl_openib_if_include mlx5_0:1 -mca coll_hcoll_enable 0 -x UCX_TLS=rc,sm -mca opal_pmix_base_async_modex 0 -mca mpi_add_procs_cutoff 100000 --map-by node /hpc/scrap/users/mtt/scratch/ucx_ompi/20170510_132009_18827_734706_clx-hercules-113/installs/50e4/tests/mpich_tests/mpich-mellanox.git/test/mpi/pt2pt/probe-unexp

Reproducibility ~50% with rc and rc_x, ud works fine.

Most of processes (~2461) are in MPIx_Fence, others (~35) are in mca_pml_ucx_waitall.

@alinask

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
- Fix hang in MPI_Finalize with UCX_TLS=rc[_x],sm

### CODE REVIEW

File: src/uct/ib/ud/base/ud_ep.c [hunk 1]
```diff
@@ -138,8 +139,10 @@ static void uct_ud_ep_slow_timer(ucs_wtimer_t *self)
         uct_ud_ep_ctl_op_add(iface, ep, UCT_UD_EP_OP_ACK_REQ);
     }
 
-    ucs_wtimer_add(&iface->async.slow_timer, &ep->slow_timer,
-                   uct_ud_slow_tick());
+    /* Cool down the timer on rescheduling/resending */
+    ep->tx.slow_tick *= 2;
```
Comment (yosefe) [inline src/uct/ib/ud/base/ud_ep.c]: let's make it configuration option - UD_SLOW_TIMER_BACKOFF=2.0

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1700/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3638/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1704/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3641/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1712/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3649/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
@yosefe pls take a look again

**Comment by shamisp** [comment]
Looks like bagfix. Do we need it for v1.2

File: src/uct/ib/ud/base/ud_inl.h [hunk 2]
```diff
@@ -134,6 +134,7 @@ uct_ud_iface_complete_tx_inl(uct_ud_iface_t *iface, uct_ud_ep_t *ep,
                    uct_ud_iface_get_async_time(iface) -
                    ucs_twheel_get_time(&iface->async.slow_timer) +
                    uct_ud_slow_tick());
+    ep->tx.slow_tick = uct_ud_slow_tick();
```
Comment (yosefe) [inline src/uct/ib/ud/base/ud_inl.h]: let's avoid calling uct_ud_slow_tick() twice in fast path - move this line before ucs_wtimer_add(), and pass  ep->tx.slow_tick to  ucs_wtimer_add(). same for other locations in the code.

File: test/gtest/common/test.cc [hunk 3]
```diff
@@ -144,8 +144,8 @@ test_base::wrap_errors_logger(const char *file, unsigned line, const char *funct
                               ucs_log_level_t level, const char *prefix,
                               const char *message, va_list ap)
 {
-    /* Ignore warnings about empty memory pool */
-    if (level == UCS_LOG_LEVEL_ERROR) {
+    /* Ignore warnings about empty memory pool or EP failure */
+    if ((level == UCS_LOG_LEVEL_ERROR) || (level == UCS_LOG_LEVEL_WARN)) {
```
Comment (yosefe) [inline test/gtest/common/test.cc]: IMHO would be better to change  ucs_warn("Error %s was not handled for ep %p"...) to ucs_error("Unhandled error %s for ep %p"...)

File: src/uct/ib/ud/base/ud_iface.c [hunk 4]
```diff
@@ -433,6 +433,14 @@ UCS_CLASS_INIT_FUNC(uct_ud_iface_t, uct_ud_iface_ops_t *ops, uct_md_h md,
     self->config.tx_qp_len       = config->super.tx.queue_len;
     self->config.peer_timeout    = ucs_time_from_sec(config->peer_timeout);
 
+    if (config->slow_timer_backoff <= 0.) {
+        ucs_error("The slow timer back off should be > 0(%lf)",
```
Comment (yosefe) [inline src/uct/ib/ud/base/ud_iface.c]: pls add space after 0

File: src/uct/ib/ud/base/ud_ep.c [hunk 5]
```diff
@@ -402,6 +406,7 @@ uct_ud_ep_process_ack(uct_ud_iface_t *iface, uct_ud_ep_t *ep,
 
     ucs_arbiter_group_schedule(&iface->tx.pending_q, &ep->tx.pending.group);
 
+    ep->tx.slow_tick = uct_ud_slow_tick();
```
Comment (yosefe) [inline src/uct/ib/ud/base/ud_ep.c]: maybe would be better to remember then "backoff" multiplier instead of "slow_tick", so resetting the backoff would be simply assigning 1.0 instead of floating point multiplication?

**Comment by yosefe** [comment]
@alex-mikheev pls take a look as well

**Comment by yosefe** [comment]
@shamisp yes, will need to port to v1.2

File: src/uct/ib/ud/base/ud_ep.c (hunk 5 above)
Comment (evgeny-leksikov) [inline src/uct/ib/ud/base/ud_ep.c]: Then maybe even better to cache `uct_ud_slow_tick()` value in ud_iface.async?

Comment (yosefe) [inline src/uct/ib/ud/base/ud_ep.c]: yes, let's do that

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1718/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3659/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1722/ for details.

**Comment by evgeny-leksikov** [comment]
@yosefe done

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3662/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1725/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3665/ for details (Mellanox internal link).

**Comment by evgeny-leksikov** [comment]
bot:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1731/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3672/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3673/ for details (Mellanox internal link).
