### PR TITLE
UCP/AM: force eager protocol for old AM API

### LINKED ISSUE #6628: ucp_am_send_nb to self
### Describe the bug
Sending a non-zero length active message to self causes the message handler to execute with a zero length message. 

### Steps to Reproduce
- build and run this example (https://gist.github.com/raffenet/88d4577aa51d5f1121e6398a5112cbdf)
- ucx master branch revision 2823e3a
```
[raffenet@pmrs-gpu-240-02]~/ucx% ~/software/ucx-debug/bin/ucx_info -v
# UCT version=1.11.0 revision 2823e3a
# configured with: --enable-gtest --enable-examples --with-valgrind --enable-profiling --enable-frame-pointer --enable-stats --enable-memtrack --enable-fault-injection --enable-debug-data --enable-mt --prefix=/home/raffenet/software/ucx-debug --enable-debug
```
### Setup and versions
- CentOS Linux release 7.8.2003 (Core)
   - 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

### Additional information (depending on the issue)
See backtrace from an MPICH test case which fails on this issue. What I suspect is happening is the wrong handler is being invoked. The `flags=1048600` argument is actually what the length of the incoming message should be.

```
#7  0x00007fae30ae9717 in MPIDI_UCX_am_handler (arg=0x0, data=0x0, length=0, reply_ep=0x7fae2cb01ff0, flags=1048600)
    at src/mpid/ch4/netmod/ucx/ucx_progress.c:29
#8  0x00007fae2fec025f in ucp_am_rndv_process_rts (arg=0x159a310, data=0x158be40, length=42, tl_flags=0)
    at core/ucp_am.c:1527
#9  0x00007fae2ff3f1e7 in ucp_rndv_rts_handler_inner (tl_flags=0, length=42, data=0x158be40, arg=0x159a310)
    at rndv/rndv.c:1453
#10 ucp_rndv_rts_handler (arg=0x159a310, data=0x158be40, length=42, tl_flags=0) at rndv/rndv.c:1442
#11 0x00007fae2fc5f7af in uct_iface_invoke_am (iface=0x15c09a0, id=9 '\t', data=0x158be40, length=42, flags=0)
    at /home/raffenet/ucx/src/uct/base/uct_iface.h:703
#12 0x00007fae2fc5fdad in uct_self_iface_sendrecv_am (iface=0x15c09a0, am_id=9 '\t', buffer=0x158be40, length=42,
    title=0x7fae2fc7ae6a "SHORT") at sm/self/self.c:160
#13 0x00007fae2fc60826 in uct_self_ep_am_short (tl_ep=0x15be030, id=9 '\t', header=140386169597952,
    payload=0x7ffe70deb468, length=34) at sm/self/self.c:298
#14 0x00007fae2feef60d in uct_ep_am_short (length=34, payload=0x7ffe70deb468, header=140386169597952, id=9 '\t',
    ep=0x15be030) at /home/raffenet/ucx/src/uct/api/uct.h:2795
#15 ucp_do_am_single (self=0x16119d8, am_id=9 '\t', pack_cb=0x7fae2feb6335 <ucp_am_rndv_rts_pack>, max_packed_size=51)
    at proto/proto_am.c:69
#16 0x00007fae2ff340aa in ucp_rndv_send_rts (sreq=0x1611900, pack_cb=0x7fae2feb6335 <ucp_am_rndv_rts_pack>, rts_size=42)
    at rndv/rndv.c:365
#17 0x00007fae2feb6562 in ucp_proto_progress_am_rndv_rts_inner (self=0x16119d8) at core/ucp_am.c:739
#18 ucp_proto_progress_am_rndv_rts (self=0x16119d8) at core/ucp_am.c:733
#19 0x00007fae2feb9696 in ucp_request_try_send (pending_flags=0, req=0x1611900)
    at /home/raffenet/ucx/src/ucp/core/ucp_request.inl:296
#20 ucp_request_send (pending_flags=0, req=0x1611900) at /home/raffenet/ucx/src/ucp/core/ucp_request.inl:321
#21 ucp_am_send_req (flags=0, max_short=-1, proto=0x7fae3022b860 <ucp_am_proto>, param=0x7ffe70debe70,
    msg_config=0x159a960, count=2, req=0x1611900) at core/ucp_am.c:886
#22 ucp_am_send_nbx_inner (param=0x7ffe70debe70, count=2, buffer=0x7fae33b4f9f0 <MPIR_Request_direct+400>,
    header_length=0, header=0x0, id=0, ep=0x7fae33c53000) at core/ucp_am.c:987
#23 ucp_am_send_nbx (ep=0x7fae33c53000, id=0, header=0x0, header_length=0,
    buffer=0x7fae33b4f9f0 <MPIR_Request_direct+400>, count=2, param=0x7ffe70debe70) at core/ucp_am.c:914
#24 0x00007fae2feb9d0b in ucp_am_send_nb (ep=0x7fae33c53000, id=0, payload=0x7fae33b4f9f0 <MPIR_Request_direct+400>,
    count=2, datatype=2, cb=0x7fae30acbc08 <MPIDI_UCX_am_isend_callback>, flags=0) at core/ucp_am.c:1008
```

### PR DESCRIPTION
**Pull request by karasevb**
## What
Forced eager protocol for the old AM API due to that it does not support RNDV.

Fixes #6628

### CODE REVIEW

**Review by brminich — APPROVED** [review]

**Comment by brminich** [comment]
@yosefe, can you please take a look?

File: src/ucp/core/ucp_am.c [hunk 1]
```diff
@@ -1486,12 +1486,14 @@ ucs_status_t ucp_am_rndv_process_rts(void *arg, void *data, size_t length,
...
     uint16_t am_id             = rts->am.am_id;
     ucp_recv_desc_t *desc      = NULL;
+    ucp_am_entry_t *am_cb      = &ucs_array_elem(&worker->am, am_id);
     ucp_ep_h ep;
-    ucp_am_entry_t *am_cb;
     ucp_am_recv_param_t param;
     ucs_status_t status, desc_status;
     void *hdr;
 
+    ucs_assert(am_cb->flags & UCP_AM_CB_PRIV_FLAG_NBX);
```
Comment (yosefe) [inline src/ucp/core/ucp_am.c:1495]: pls improve the error message. smth like
```
if (ENABLE_PARAM_CHECK && !NBX) {
  ucs_error("active callback registered with XXX API does not support rendezvous protocol, the sender side should use YYY API")
  goto drop_packet
}
```

**Comment by raffenet** [comment]
Tested this branch with MPICH+UCX active messages and it works for me. Thanks!

File: src/ucp/core/ucp_am.c [hunk 2]
```diff
@@ -1486,12 +1486,20 @@ ucs_status_t ucp_am_rndv_process_rts(void *arg, void *data, size_t length,
...
     ucp_recv_desc_t *desc      = NULL;
+    ucp_am_entry_t *am_cb      = &ucs_array_elem(&worker->am, am_id);
     ucp_ep_h ep;
-    ucp_am_entry_t *am_cb;
     ucp_am_recv_param_t param;
     ucs_status_t status, desc_status;
     void *hdr;
 
+    if (ENABLE_PARAMS_CHECK && !(am_cb->flags & UCP_AM_CB_PRIV_FLAG_NBX)) {
+        ucs_error("active callback registered with ucp_worker_set_am_handler() "
```
Comment (brminich) [inline src/ucp/core/ucp_am.c:1496]: plz use either `active message callback` or just `callback`

**Review by yosefe — APPROVED** [review]

File: src/ucp/core/ucp_am.c (hunk 2 above)
Comment (karasevb) [reply src/ucp/core/ucp_am.c]: fixed

**Review by brminich — APPROVED** [review]

**Comment by brminich** [comment]
please port to 1.10
