### PR TITLE
GTEST/UCT/IB: Split IB tests into subclasses

### LINKED ISSUE #3745: test_uct_ib.non_default_gid_idx failure on ThunderX2
It fails in the same way with rc_mlx5, rc, ud, ud_mlx5:

````
[ RUN      ] rc_mlx5/test_uct_ib.non_default_gid_idx/1
[1561131611.232368] [vulcan2:11593:0]       rc_iface.c:774  UCX  ERROR error modifying QP to RTR: Connection timed out
/ucx.master/contrib/../test/gtest/uct/uct_test.cc:821: Failure
Error: Input/output error
/ucx.master/contrib/../test/gtest/common/test.cc:265: Failure
Failed
Got 1 errors during the test
[1561131611.249089] [vulcan2:11593:0]       rc_iface.c:654  UCX  WARN  some eps were not destroyed
[1561131611.249114] [vulcan2:11593:0]       rc_iface.c:665  UCX  WARN  failed to destroy SRQ: Device or resource busy
[1561131611.249679] [vulcan2:11593:0]       ib_iface.c:911  UCX  WARN  ibv_destroy_cq(recv_cq) returned 16: Device or resource busy
[1561131611.249699] [vulcan2:11593:0]       ib_iface.c:916  UCX  WARN  ibv_destroy_cq(send_cq) returned 16: Device or resource busy
[1561131611.249709] [vulcan2:11593:0]       ib_iface.c:921  UCX  WARN  ibv_destroy_comp_channel(comp_channel) returned 16: Device or resource busy
[  FAILED  ] rc_mlx5/test_uct_ib.non_default_gid_idx/1, where GetParam() = rc_mlx5/mlx5_2:1 (1108 ms)
[----------] 1 test from rc_mlx5/test_uct_ib (1108 ms total)
````

### PR DESCRIPTION
**Pull request by dmitrygladkov**
## What

Split IB tests into subclasses with the name `test_uct_ib_*`, where `*`:
- lmc
- gid_idx
- addr

## Why ?

Fixes #3745
Fixes bugs come with #3639

## How ?

Add `test_uct_ib::ib_init()` and `test_uct_ib::ib_cleanup()` that are responsible to initialize IB to perfrom some checks before UCT/IB are executed (e.g. available pkey or GID index). If a check is unsuccesful, a test is skipped

### CODE REVIEW

File: test/gtest/uct/ib/test_ib.cc [hunk 1]
```diff
@@ -181,12 +166,38 @@ void test_uct_ib::test_address_pack(uint64_t subnet_prefix) {
     free(ib_addr);
 }
 
+void test_uct_ib::test_uct_ib_init() {
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib.cc]: why not use the regular test init/cleanup functions which are already called before/after the test ?

Comment (dmitrygladkov) [reply test/gtest/uct/ib/test_ib.cc]: > why not use the regular test init/cleanup functions which are already called before/after the test ?

we have to check whether gid_index/pkey/pkey provided to the test is supported on a current setup
So, if we do UCT entities initialization inside regular `init()`, it results as a failure, because, for instance, gid_index=1 isn't supported (but we should just skip such tests) - as it was on `boo31`.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10679/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 25-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/f92f4e59451f225dc5608d998932b88b556a4718/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/41afadc27f6367e2291172babf3e2d2568895e79/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/2b144bf0d0726fdd641542e4603a64449fee79f5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/1eca0d62343b3af42554480cf4bad607f19a6a9d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/6cb6a644ade770965825e12f5b5276c79f4ce4fc/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/d2229fab3e22ac5773463fa854794389031bcd36/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/0f0ee1da0c85300341ff9a6a341328a8cac34e88/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/cf734eef28ce2c08c92ffe926cf6396eb6371c10/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/d498d32625e2ea76aed6fcaed1c2981c604a9276/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/716ef9724ca1ba1d4bda105532dab770972a9fda/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/27a4aa0d359aa3db70d5c5c499aac3e400bb8f14/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/b51513a3bed9225c75af410c914e4e91375c8bb7/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/0432de85578ad30872420a2201d7ecccb1f5cef0/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/97a088c214c86879b200ad7e0a1e28baeff7b24d/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/9ba62ad7b2fdb2fef47f9a88acc13f7186958c24/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/483282fba36236109a60bf25cd3a7dcc716d79cd/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/16eb7f62d284a901c8d7504907a37b1faf77fe50/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/e27d9bc47fe7bd167b86527546f36adde3f3cdf0/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/e16e69a2b82f20dd2f648ec7d8f904935f94206d/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/9a340f70c237f488c45089a42aa23f472d23274f/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/5f906e8a7e97518498e735a33f9006b4ac15ea5d/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/c25c6d65147add221bf1d98b44486cd649c6d33c/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/26ca7e289a99b169404d8443f1a6b50248aa74bd/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/955891c94c02e1c9ebfa597d5833135cd6a43066/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/6a64d9125cfb142afb8e0d8f7dd58f06eb68b344/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/10b8caa5ac9f4b20b4c31695d5cebed25ea87267/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/c76eb199fe61e387b9ff43926d9a4b169224d7cb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/9aed89613e011944f02ff9db49769f1258d8c2be/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/080f0a287edbef9775b1802cce251041ba8a1444/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/4d44d88e1fe632db3dea2e745f20651b176b692a/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/c031b9633eebae2ee816f4143ee4495b9049624e/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/41282991a2d8afbc6a2eda7b77fd1d960a782126/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e96db120de686f4a3d222fc89c890644/raw/3db290cd913e4a3ba8c020f095c35f9cd7c506f9/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
@yosefe I've force-pushed the new changes, the fix was completely changed

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10697/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/56a0b9f6914d61443a7fc66a0ab442867f96b65f/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/f012535b64e160e9b82b88a5789f408338392018/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/c23c2aaf7c4c39f19258cc6f1ac5ed4f7b7735bd/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/9ce7f285df71eb7f9b3026ceda4be4556bc01510/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/df8e9cadd0d856e506222e5ef8c95c5a63b1ec41/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/fde435e2264c16eac9a68ba7b6f2e0bb9b397813/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/c2fef9daadfc7b8c493d37905d40b754b7bc9eb2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/c86ed1ea29c1e109959cc9535c10e388ae3726d3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/d6f1eb1d90187bc614dc27d2d421060af4582df5/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/b7640785cd69c828d33c750708eb46dc56f66e5b/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/7ccb95724e55c5fe7e2839a7448a8162890834e9/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/2451e9eeef86e1bd076d6abcf0280314ae4b7709/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/e4b4e1244b600e909054be042797e3ed6f045a95/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/24b10ab2ab7b5554757fec9b3a7a1d8b86964908/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/d0e76e02cf5544d0ba34f65edda3c3a11d361353/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/65fd8c50bce767e1e0610eca523f14fea5b620dd/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/866e9de63ea04962477824a84dfc08767b046b34/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/60e089bcd925a65d769f6727ff07768593e11e50/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/9a68b0771c98f07ae36500801e40a1a03b9724e8/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/92bdb809febebfb8e59a5a482a4c198b67992440/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/162425bea16ecea7971b2a4c73a1f86562823a70/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/2cb3f077ddafbd28b9685328745a53bb70382ad0/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/1d47299139d65c01ce6770458044ba36a9a8e45b/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/305d307dbe29c470c70489aa36d7b9e501906319/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/6324c9771db976ce3cf9c9e4b688545c38dd83e8/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/e0794aab6b3ea4ab19e947e7f72fa1997a024cae/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/1256e7afd813002e640840d72eec1166f252d856/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/6f63662259857f2db9d8c403a94114c825a9b8c1/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/ed2b3e3db8c33a42e2e3cbdfd87ee4faf6166982/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/170b1fcc744bb9dce42498c354369fe0afb126b3/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/ffafda8e97fe14385d6cf6f613c6bf1c46d66025/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/b62028b1a5f525d0c38f3bf5adb3be63205ec2aa/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e3f1a0fc4f202cd3be98c27fd2cd4d6e/raw/b4eb96bae85eb51afc0d84009f1a2c5bc96aa936/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
@yosefe could you review pls?

**Comment by dmitrygladkov** [comment]
> [@dmitrygladkov](/dmitrygladkov) [dmitrygladkov](/dmitrygladkov) [force-pushed](/openucx/ucx/compare/d86dbd1ff1f3e8bd4e19a362fc7e3998b111cbd7..0f5695220dfdedd46f17046526e04c0c35aeff0d) the [ dmitrygladkov:topic/gtest/uct_ib ](/dmitrygladkov/ucx/tree/topic%2Fgtest%2Fuct_ib) branch from [`d86dbd1`](/openucx/ucx/commit/d86dbd1ff1f3e8bd4e19a362fc7e3998b111cbd7) to [`0f56952`](/openucx/ucx/commit/0f5695220dfdedd46f17046526e04c0c35aeff0d) [29 seconds ago](#event-2425185242)

rebased on top of the master

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10718/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 33 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/410c5495534bb6d6c4395f7f00d4e1a76b49d713/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/a9bd527ef385be3df2a7d6b33a15ea19c51bba4e/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/2e83cfbf3f960aa3c40eddd553d6e0f16ff9884f/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/ff2c89d597a86fe25aa7ade8e493617e2e741200/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/3b12a0984c234fcf1881787c76d887d7c90bf93f/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/2d2bdb4696a1509b78aff57235552fce10f86da2/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/f587d0b0fc1f55a5a04b33fad6d45c95cb7a6b80/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/3848970c9676aff947181be575dcee04870baab4/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/48d4c584d5fd9d36c0f6f5207cc0d5681dd84a19/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/13e9edc333a075d4bbd2b72a35359a64e3da38e3/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/5440d9d23a0df07dfc37c3d27302ef19c05fa557/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/4928cd58ed2b33a9604154a4b40fb2dc79688acc/hpc-test-node-upstream_W2) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/e2b51ac1b3014e3ce8357ea954f30791c68cf17c/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/550e4254eada80e51c38ecf3fd027a70cc95c984/hpc-test-node2_W0) | :x: FAILURE
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/0462b94c1cb0f8f61d0cf41808f1718caf010057/hpc-test-node2_W1) | :x: FAILURE
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/4ae05b8d0189ad08a9114546d5b48a246a1b89e6/hpc-test-node2_W2) | :x: FAILURE
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/0a3d4c1534ce115587d3b299bd89a9269f19fd45/hpc-test-node2_W3) | :x: FAILURE
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/ccceffa9032afbf5029836ac41d80f4e81c84c82/hpc-test-node3_W0) | :x: FAILURE
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/42171dd992341ac3a957a2ffd1797b3664625f9c/hpc-test-node3_W1) | :x: FAILURE
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/c97e78397aba2cd333b830caf48fc969c69f1691/hpc-test-node3_W2) | :x: FAILURE
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/df43a4ff2232c0c30a8b54cb880755b72c89fac8/hpc-test-node3_W3) | :x: FAILURE
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/0d3515b4e3778dc22140329bf3a5cf58cace230a/hpc-test-node_W0) | :x: FAILURE
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/b4d2e62f5755e816a71059429786691ec87434a1/hpc-test-node_W1) | :x: FAILURE
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/1508c7a5d0384ab1cfcb6e19330e9d8b1832b4d9/hpc-test-node_W2) | :x: FAILURE
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/7e6f926639f7448b60686a7b318d5850bc09cf23/hpc-test-node_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/906c3bb27c194acf07aa7861236cc68c741f26ee/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/6e3e611ad03787a787c59b9cae637384c1bef637/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/17c97690fb33c0df622721388de10363bdb32071/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/5d4551e426122a8c7fe6ad8eac05984da128cfd5/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/afa0f2b9eb3ab79e185a8d1516ff8b7e941f558e/vulcan-jenkins_W0) | :x: FAILURE
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/03be61b2dd98a6e395bf7bcd1dce71a2fbeb0e4d/vulcan-jenkins_W1) | :x: FAILURE
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/c7f0d4e30c3532cef5d73f2844fa052cbf7aa40c/vulcan-jenkins_W2) | :x: FAILURE
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/bc9993322958454d44dd3e0d4688bb20/raw/9390a4f2feafaec93778298196a83e4aa4d38078/vulcan-jenkins_W3) | :x: FAILURE

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10719/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/ae515e9bc4fe6112c56b0ba665e57e89641ed263/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/07c81b2f6480e054741c6f4e699f3449276774a6/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/fb408ec8c5bb66601d65d8cdbd7cce5678cf5fa5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/01a8c7f10e9f8f091bb90042870713bb65b269de/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/dd580a6406ad9f305775dc86e56d87cfdcdfe91f/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/6dc5291cf66111b0e4e350be9e6952b69dfef5a8/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/2f1a75235cdcabcf4eddc12a923dcad547fcdf95/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/a0c456d0bf1fc01e8e8a6931cf543771c86a490d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/fa4cdf9d2e5a2022b9d1fdff19e55f7158fc4922/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/3ecb485f3caa8fcf5630790846814b3ad3440245/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/d19e1682962ebd69a2353210ff176c79914530aa/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/66772cc0a4d2b9c155340c60d1a823d826791799/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/bb7c3ea764e0d236286e639ac506aba78421c89b/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/ee844cc59f791e308190f92eb64403c3b25757cc/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/b32fa8d835b9745d6e4f740f1dce5e20246c5429/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/5a57ca88c36f5fb63eea3fcdc26e407916a413a5/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/e90b1843c63e8d2c5bd730cd8b0a3ea544de24d8/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/e6d7fe68cc230cddc98ce97c90f254141b84801c/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/77cd35b8f931733e75c7531975c2b01ea895da7e/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/78aad8f8e9fa54802584846fba4e50f9e446fba1/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/2ab6b47c41a88153b0877ebfa3682af221bfea3c/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/9f35150922c4e862dbd954237ab2f7d4546a8310/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/5873c65c1b9bc87bc01ee0ba6b14009a75dab79e/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/035b6e4f1133f806f0dd842c96f90f9ab217afe8/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/e111b77198b8854840e38673437f0e375964e5f3/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/a8caa1db93eb7734fbbdf6b5398dbef6638175c5/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/fe7f203dec4f0411ad4bb5550a2f7d6aaf51ec39/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/e12dd5878e021d2f0363f473bab21d587351f37c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/8b72bffbe9fd7c2a8ebeb3fa703a630d297fbbb9/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/096beafa2658485faa03e11cbac00bf8300c5af2/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/a924f53295c4fd6d45e6c7df0c4b332cae198281/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/01a9ed99912a3ef34d0fa8e1d3f551cc59b89de3/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/88c050cab5fd2b422061a2934b36b220/raw/52ca551979fcb05f9ad68656bed552710fa0457a/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

File: test/gtest/uct/ib/test_ib.cc [hunk 2]
```diff
@@ -18,7 +17,7 @@ test_uct_ib::test_uct_ib() : uct_test() {
     memset(&m_port_attr, 0, sizeof(m_port_attr));
 }
 
-void test_uct_ib::init() {
+void test_uct_ib::ib_init() {
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib.cc]: still, why do we need to separate ib_init() from init()?
maybe need another test class, like test_ib_with_specific_port, which also tries to find and open GetParam()->dev_name?

Comment (dmitrygladkov) [reply test/gtest/uct/ib/test_ib.cc]: > still, why do we need to separate ib_init() from init()?

only `test_uct_ib_lmc` and `test_uct_ib_gid_idx` test cases require direct device initialization to perfrom checks
`test_uct_ib::ib_init()` was added to `test_uct_ib` class to avoid duplication in `test_uct_ib`  (`test_uct_ib_lmc` and `test_uct_ib_gid_idx` successors, other successors don't nned this)

> maybe need another test class, like test_ib_with_specific_port, which also tries to find and open GetParam()->dev_name?

do you mean to create the following hierarchical structure:
```
                            test_uct_ib
                          /            \
test_uct_ib_with_specific_port        ... (they don't open device directly)
(does actions from `ib_init`
 inside `init`)
   /                \
test_uct_ib_lmc     test_uct_ib_gid_idx
```

Comment (yosefe) [reply test/gtest/uct/ib/test_ib.cc]: yes, like you wrote above

Comment (dmitrygladkov) [reply test/gtest/uct/ib/test_ib.cc]: > yes, like you wrote above

@yosefe could you review new approach, pls?

`test_uct_ib_with_specific_port` is an interface, has two pure virtual methods used in `test_uct_ib_with_specific_port::init()`:
- `bool should_skip()`
- `void skip()`

`test_uct_ib_lmc`, `test_uct_ib_gid_idx` and `test_uct_ib_pkey` implements `should_skip` and `skip`.
Also, `test_uct_ib_pkey` re-implements `test_uct_ib::send_recv_short()` in the following way (it was in previous patch - 1st commit):
```
void test_uct_ib_with_specific_port::send_recv_short() {
    test_uct_ib::init();
    test_uct_ib::send_recv_short();
    test_uct_ib::cleanup()
}
```
This is needed to accept new pkey values when we do testing in a loop over all available pkeys

But now, we need to call `test_uct_ib::cleanup()` after `test_uct_ib_with_specific_port::init()` in `test_uct_ib_pkey::init` to avoid overwriting UCT entries, and then call `test_uct_ib:init()` before `test_uct_ib_with_specific_port::cleanup()` in `test_uct_ib_pkey::cleanup`

File: test/gtest/uct/ib/test_ib.cc [hunk 3]
```diff
@@ -6,19 +6,118 @@
...
+    m_e2 = uct_test::create_entity(0);
+    m_entities.push_back(m_e2);
+
+    m_e1->connect(0, *m_e2, 0);
+    m_e2->connect(0, *m_e1, 0);
 
+    test_uct_ib::m_ib_am_handler_counter = 0;
+}
+
+void test_uct_ib::cleanup() {
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib.cc]: this is redundant

File: test/gtest/uct/ib/test_ib.cc [hunk 4]
```diff
@@ -6,19 +6,118 @@
...
+UCS_TEST_P(test_uct_ib_addr, address_pack) {
+    test_address_pack(UCT_IB_LINK_LOCAL_PREFIX);
+    test_address_pack(UCT_IB_SITE_LOCAL_PREFIX | htobe64(0x7200));
+    test_address_pack(0xdeadfeedbeefa880ul);
+}
+
+UCT_INSTANTIATE_IB_TEST_CASE(test_uct_ib_addr);
+
+
+test_uct_ib_with_specific_port::test_uct_ib_with_specific_port() : test_uct_ib() {
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib.cc]: test_uct_ib() is redundant

File: test/gtest/uct/ib/test_ib.h [hunk 5]
```diff
@@ -42,3 +38,18 @@ class test_uct_ib : public uct_test {
     struct ibv_context *m_ibctx;
     struct ibv_port_attr m_port_attr;
 };
+
+class test_uct_ib_with_specific_port : public test_uct_ib {
+public:
+    test_uct_ib_with_specific_port();
+    void init();
+    void cleanup();
+    virtual bool should_skip() = 0;
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib.h]: this is not needed, each test case/class can check its own condition and skip

File: test/gtest/uct/ib/test_ib_pkey.cc [hunk 6]
```diff
@@ -6,16 +6,36 @@
...
+        /* no pkeys for Ethernet */
+        return IBV_PORT_IS_LINK_LAYER_ETHERNET(&m_port_attr);
+    }
+
+    void skip() {
+        UCS_TEST_SKIP_R("skip pkey test for port with Ethernet link type");
+    }
+
+    void send_recv_short() {
+        test_uct_ib::init();
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib_pkey.cc]: why is this needed here?

Comment (dmitrygladkov) [reply test/gtest/uct/ib/test_ib_pkey.cc]: to allow testing "invalid pkey" and "all available pkeys" cases:
1. "invalid pkey": we search for an invalid pkey value, modify config by the new pkey and test send-recv with it
2. "all available pkeys": go over all pkey table elements { takes pkeys with full membership, test send-recv with it }

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10728/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 19 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 27-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/0b920bb4e069d24e08b2123aad13c038ace0263b/_main) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/53c2ecbc549789b3ae3a64e672a8db6ccefa4d38/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/400dc5c85d1807d3210393eb2e89b5f87fff0fae/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/6fcdab950472d8e7db87650b0c806c3ae105de00/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/6d9990c4692bf85ab31ad47fd17aaa0b7b33bb59/hpc-test-node2_W0) | :x: FAILURE
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/ffb8f3d9e57cf1931be2726f193daed5c7f54a0b/hpc-test-node2_W1) | :x: FAILURE
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/05609e0a22207999a3574cea92c2b8c1f1a9870f/hpc-test-node2_W2) | :x: FAILURE
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/640e8b280fe81f1abe8702a4179d5324e9194b53/hpc-test-node2_W3) | :x: FAILURE
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/52f6b6c305330ef6ed36c550a6176e0e60869afc/hpc-test-node3_W0) | :x: FAILURE
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/ad991071a77e0cfa059e00a9f8049c16226e51cd/hpc-test-node3_W1) | :x: FAILURE
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/0e3ec3feab820d2a85769792b3e82a107b46d349/hpc-test-node3_W2) | :x: FAILURE
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/ba4124eedd7d140ecf2e63b06465c831a002cd70/hpc-test-node3_W3) | :x: FAILURE
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/656139c9fa46c18989dbdae624d491d27ae267a7/hpc-test-node_W0) | :x: FAILURE
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/4290c5b3775d61b477f6a80369866297acc1b73d/hpc-test-node_W2) | :x: FAILURE
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/d500c4d4c777251fff895cdb75624943697ef46f/hpc-test-node_W3) | :x: FAILURE
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/a80d4cbcbfb2647e3edfdb72dab767458b03361f/vulcan-jenkins_W0) | :x: FAILURE
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/8f11bf6401f098fe5c803aad987bc47fd76bf71b/vulcan-jenkins_W1) | :x: FAILURE
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/c570d05a9e3e81ce9110fc450db2afa33d3d4fde/vulcan-jenkins_W2) | :x: FAILURE
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/8cce5e75d8f4a980ec5649a752440f1c1937e1a2/vulcan-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/6207a8d5ce03e32e5b8cc47bbd8fbfd324d58f3c/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/fa4b338bf867446822728473c50f3faf73ff6e9e/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/93ca71ad8c0cf65904797267c40250bee3f85116/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/4958cf6a595713dd1b6e7457791772dc204d3920/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/b5d971b7902736a3bf8249292b62071c5822c113/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/92740bc12640bbd9646df501081bfb8a2eb36bba/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/a6a399a929f32b0efcc8180cac9cffb5bcac8746/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/a048f9f8fc1bd4eddfb13a2511f439bc06bd7be7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/a07181e54fa8f1d3c91a39239d384a0dd8f4eea2/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/dfd932839bd5d566df5de7039b042b33613e7ffb/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/cb5df659d11b64a87f2d77db8b78169e353daced/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/2770947411b9f1a3e6f0d2c80d6679603f326422/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/232879d4a3d6babc36df01595eab7c6d8fa871bf/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3fffe435fc44b13e4e0370736ea5cba0/raw/c4a80bf5e5b043b783804fc46ce2caf6be519a94/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10733/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 6 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 27-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/605bdf1661bd297c5a117cf7a4a09d59a42a2b7e/_main) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/4e4553b0a2cb4b1e97f96692b1c27eafec037f9f/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/540728c60c38fe85948ebc8da9095fda8884019d/hpc-test-node2_W3) | :x: FAILURE
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/24063d91100dcda0a3023336545dc2fc5da754f5/hpc-test-node3_W3) | :x: FAILURE
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/25abd04595fda7e6bf972f8d88343159770bb266/hpc-test-node_W3) | :x: FAILURE
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/34efe41e23a4208ad0809ca66a61e13c35ae97de/vulcan-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/99e9b8e061406376628cee14be5dd59fffb6d6c4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/c2af9a713cb5bd99a22fe740f3104e2bdf3e95dc/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/e7cfb7fd999ab756614209f473d07969c66f78f1/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/568e8cfcae9c09c7a592c86662a90f053f0b83dc/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/afeb25bfcffc28eaeb8fb66c899293ddf29508ef/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/f6a5babaedd451e19d515311433a9c18a833fef0/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/b04ba31eb480289b1a66ff04effd995cfeef6ac8/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/2ef01147a0162f69149bb8691fe48190deb8c464/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/16d95369af01e4169dab33d0daf3230b3f00841d/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/3fbbe6c1f117bc56aa19e710fa176e42ec134387/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/307824bc0b39bd57f2e681a28d25bb7f23e643de/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/c16c5d6c53cadcf5879d2ae14ae292c620df8350/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/0396c2b696867b8cb8b21d77d88df0ba8d6bef24/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/89c863a90312f36b03d99e07e5df444c96383da9/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/32692321716ef0dd7eda1b131b6efd2f44bce1c4/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/5611f920b9c7a2172e5e863ee692ebf125f37926/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/bae1c87ba02b7403e52d9edaa0e819c5fa038045/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/311172cb0e80bf623d34e69371b13d3a452894a6/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/4007a22df43b475564a0c4b5c5cb1268313c172e/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/caa01471e31e733c1426876aee4e330ccf481736/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/d815e5ef6654b8883a489bbad3a4bb9bc84a36c9/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/2d90bdaa0c0b9422cddd1b69f3c1ddb790297f3e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/4e24287c30a49a09cee16b6b42cefe990805b00a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/6e235683dce3a5edc406623881cf562f784245dc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/bdd5579ff18209e617572f1061cc12945a1a2523/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/de246bb08a5ca66a649ee23d6f71df529413499c/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/18eaebd51185b44106ff91ab3b49c75c/raw/021a1814427dfeb9c5b13c8c80b487e906da5037/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10736/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 27-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/a5cdd852f28a1fc7dcf0600c1200e6fabb80d751/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/ba7f69423dd2f75b38396593571c33c0f7e43569/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/0e1c2e3576215d9fe6177c77a8c81e653f9338f7/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/0fbe935f6b963153af1225c81f8eef309d8357fe/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/d2409da3c533cd33b35bddac090ee24b58490ed3/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/8d8150e5cb0646a68300d049343873692f5aea8c/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/9163101d3b4afa73e6f6faf8817ea2cd042688e3/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/82746e75fa62a40dca795279fff0f69ef397e272/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/39595f05e0c2286d215a7e471a674e0a9ecc9175/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/1f7e82cc250dfb321e479a3b802bb8164dc5a214/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/23a4449d386a3d412dc242f7526a4b709e166315/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/ac7bf8e83244622d4c9c745486bdc98a8551d70b/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/840bab9744ce2798df5926313d62e8c3287905e4/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/c3a3d39267641ffe2b9380c3fcca8ec6ccb13146/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/83cdda3cf14d9212fcc249b2ab63a3ec90130f96/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/a3269e37acab5ece4164d8acaf28ddf165ea4e05/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/114fa75c2d3ba05c6741e1de9ec9c8d3dea2d483/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/b67adddb5b991bba67e9119086e0685805d91d0d/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/563d38f590e72ea212401952a95d4f03843dc992/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/67375db53b2c52eba96a41bca2b0b3bcf7dd29a6/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/a9157bebcc21e48eb557008a086ff79ecb34e1e3/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/6657210ff1b2ae975967dd0497885447498ae144/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/5340a2192e311881b67d1cfe858ec2e00fc37a84/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/5192c1d377757140011eb68db296ff1c6782efbc/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/bb51a544dd67e5b497d4e96008d3befb27834934/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/db168cb5ceada8d47555109a9469dc614513cdb0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/13ae00dc5d225692b890f17b1b729af1af89ba59/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/051b55d6846ec4a0619fe546b7410571285de091/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/a628a5304b91b77ec45d0c08483c236d290c0e08/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/0778f4dfd4a1183b323af0b55f011d6c4074b296/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/1aed9b59cb8a8c3606a972076785b226a20debfc/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/b641b06b3a6b4b1607cff3a32d59556d23fa40d4/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3d18162d6e9eb6d503dec23b041bfd5d/raw/0499e841f6edbfbad59a27c38123f6475fede4a5/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

File: test/gtest/uct/ib/test_ib.cc (hunk 3 above)
Comment (yosefe) [reply test/gtest/uct/ib/test_ib.cc]: i think you can call test_ib::cleanup() without really defining it (from the places you described), it will default to uct_test::cleanup() if test_ib::cleanup() is not defined

File: test/gtest/uct/ib/test_ib.cc [hunk 7]
```diff
@@ -67,183 +166,102 @@ void test_uct_ib::init() {
...
-        EXPECT_TRUE(iface->is_global_addr);
-    } else {
-        EXPECT_EQ(lid_in, lid_out);
-    }
+UCT_INSTANTIATE_IB_TEST_CASE(test_uct_ib_lmc);
 
-    if (iface->is_global_addr) {
-        EXPECT_EQ(gid_in.global.subnet_prefix, gid_out.global.subnet_prefix);
-        EXPECT_EQ(gid_in.global.interface_id,  gid_out.global.interface_id);
+#if HAVE_DECL_IBV_LINK_LAYER_ETHERNET
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib.cc]: why do we need to put all test under this ifdef?
isn't using IBV_PORT_IS_LINK_LAYER_ETHERNET macro enough?

File: test/gtest/uct/ib/test_ib.cc [hunk 8]
```diff
@@ -67,183 +166,102 @@ void test_uct_ib::init() {
...
-    uct_ib_iface_t *iface = ucs_derived_of(entity->iface(), uct_ib_iface_t);
-    return uct_ib_iface_device(iface);
-}
-
-size_t test_uct_ib::m_ib_am_handler_counter = 0;
+        /* check the gid index */
+        if (ibv_query_gid(m_ibctx, m_port, gid_index, &gid) != 0) {
+            UCS_TEST_ABORT("Failed to query gid (index=" << gid_index << ")");
+        }
+        if (uct_ib_device_is_gid_raw_empty(gid.raw)) {
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib.cc]: uct_ib_md_close(uct_md);
return !uct_ib_device_is_gid_raw_empty(gid.raw)

File: test/gtest/uct/ib/test_ib_pkey.cc (hunk 6 above)
Comment (yosefe) [reply test/gtest/uct/ib/test_ib_pkey.cc]: so maybe send_recv_short() in test_uct_ib should create the entity when it starts, and destroy the entity when it finishes? same for test_address_pack
we should avoid calling init()/cleanup() directly during test itself, they should be called only before and after the test respectively. any other behavior unexpected and will create confusion and inconsistency.

File: test/gtest/uct/ib/test_ib.cc [hunk 9]
```diff
@@ -6,19 +6,117 @@
...
+    m_e1->connect(0, *m_e2, 0);
+    m_e2->connect(0, *m_e1, 0);
+}
+
+void test_uct_ib::init() {
+    uct_test::init();
+    create_connected_entities();
+    test_uct_ib::m_ib_am_handler_counter = 0;
+}
+
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib.cc]: redundant space line

File: test/gtest/uct/ib/test_ib_pkey.cc [hunk 10]
```diff
@@ -6,18 +6,20 @@
...
         if (IBV_PORT_IS_LINK_LAYER_ETHERNET(&m_port_attr)) {
-            test_uct_ib::cleanup();
             /* no pkeys for Ethernet */
             UCS_TEST_SKIP_R("skip pkey test for port with Ethernet link type");
         }
     }
 
+    void send_recv_short() {
+        create_connected_entities();
+        test_uct_ib::send_recv_short();
```
Comment (yosefe) [inline test/gtest/uct/ib/test_ib_pkey.cc]: we need to destroy the entities after the test, what if this function is called many times, it means a lot of resources will be consumed?

File: test/gtest/uct/ib/test_ib.cc (hunk 9 above)
Comment (dmitrygladkov) [reply test/gtest/uct/ib/test_ib.cc]: fixed

File: test/gtest/uct/ib/test_ib_pkey.cc (hunk 10 above)
Comment (dmitrygladkov) [reply test/gtest/uct/ib/test_ib_pkey.cc]: yes, this is a good point
we able to have 256 pkey configured that will create 512 entities

done

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10766/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/a7b971e6c515a91efa09f0f0136e75965729e0e6/_main) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/030e9cbe92d1cc627d115fca19f34680dce66681/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/984ee4dbba6eec1a40ab1e89c3e7e5cd0456c2c1/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/b7a6a145237647fdfe6be0aae1c52f59ad6630ca/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/422309a1c2ff806e798964cde937f3affb729d76/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/24efcfd7c438a8b92c82c1d121e867f9c08c1e7c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/f0743263cd2dea2dfeb02493cbf70ad476e8aaff/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/9611f9b17fca98da5b4149aee92e44fbe332a4d2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/816b047c88e6d752b508bd6af4dd1ac19af35b08/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/5e96290460da51303ece53c23343834cbdfff9ac/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/7b33d0d85ae8511150faafca2f2cf7e48f457532/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/0ac8ee0ce4675a66ee948da4054a54f445847723/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/3d61afa9132fe40c101eb0671e2ec66d8bc948af/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/013b5f477cf014382d43a385741efbddf833be51/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/560fd4c2980194353b0ce49a922a0991199c767e/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/ec3e14e01e985b9b3adbf377a067e5b97e835732/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/a679bf2252c49644694b4b46e8f96d3c9001fd38/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/96222ac8341256bb5c7ca26a4e0366becabf18b5/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/c7db4d8811fadf6a55668856f97f330fd99630ba/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/eb0f53a2dca1607cbc303b20c4ad08ac3bde8c59/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/404ef1552ff0c32d9062f7f769f0163c6493474e/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/10828b9f568dd9923a933aacf4938ce3799d15e8/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/5dc1d73c15e479b75b5c8b8e1bf3af4c9dbacc19/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/28ae0e7fcda2475adf22720db9a6674c4f42b503/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/58b78b86e0426df1323264b03d10617a00a0a5c6/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/13bf9b8c22e00a8f59289555e79ed604198fe109/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/224ce5879b74b6c48316c6707454a8394a787e14/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/250874d9464658125295014f6078512d33c798af/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/b6268dd676a97d0242d96f3e7bc88336bb269398/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/298a254fee58f74ad562ca675079667711689062/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/e92d770b3da249b14b8cb6b05bba0bd550b1774a/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/b73ed0253e53d79a0ab3a16d8cd42531d4e25bc9/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/43d8fce6ab96d6c698ac9a0fb7c68eba/raw/958c72dcff37c0b72e3830042e733eb15d679b8d/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10767/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 33 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Jun-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/4854f9aa0d02886816bf6086e2593394a59bac22/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/fa7158750127b8bae7ab22b8d7a66ba8b521a8bd/hpc-arm-cavium-jenkins_W0) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/6b69e20824a13d4b8f3a285dc7469e32a5f61799/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/c251d4e3298f34916c55ea9b3776fae1f9894853/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/52d9c30d3b09b118eb6d2c381ab07d93adbe0d10/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/6de0eb6f86fb9eea176dbfb893fada921cfac41f/hpc-arm-hwi-jenkins_W0) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/9dc8cc6cf043acc0e0705e7b7f07395078705219/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/90aebf3ac7fb7ccab87ee4bf89d6eb728838c2bc/hpc-arm-hwi-jenkins_W2) | :x: FAILURE
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/1a4ea7a2761f1c0f6c8633342a94a01fffbc1c26/hpc-arm-hwi-jenkins_W3) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/e5d4b2c340c741e353959cdbc4641fdc02ab701a/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/11a7b30a2e11961572c5ad4afbc76d5d31087390/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/1b48de14c0b67f01cec7a21b06992d334979f7c4/hpc-test-node-upstream_W2) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/32c09c3e97f855a86f9ac5db0c994be7965924e6/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/deca371200e7fb2d1591ad0426baa78d67696a74/hpc-test-node2_W0) | :x: FAILURE
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/0762eb8d794a6dcec8d6c469f954dffa622e5d42/hpc-test-node2_W1) | :x: FAILURE
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/14ebc02fafa8ac0beb33e171c9b60ac7a62c8ae8/hpc-test-node2_W2) | :x: FAILURE
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/eac73d85f9ec565e263c70011b703f863668476c/hpc-test-node2_W3) | :x: FAILURE
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/a3fdf08eca6c2e499685cd66260f29175af09573/hpc-test-node3_W0) | :x: FAILURE
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/e96c5a3a4c84374a531cdcace3cebb9ed5044150/hpc-test-node3_W1) | :x: FAILURE
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/ee837d26c5de2bb81adf18983b857ecd5ed898ea/hpc-test-node3_W2) | :x: FAILURE
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/398515d227b2ed70a626e1500c1806fce71eeaf8/hpc-test-node3_W3) | :x: FAILURE
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/3c47c77c7fb719601ab51e679e7bcf5fde59101a/hpc-test-node_W0) | :x: FAILURE
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/7fa0e31e910ce921fec73ab5cc8a1fdfa8a47ccd/hpc-test-node_W1) | :x: FAILURE
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/d12ca827192f3e3c69b470e5c0ed18fe7e543c85/hpc-test-node_W2) | :x: FAILURE
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/33d7aa6c71ef09d527d7f6dc60fa75e723e40630/hpc-test-node_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/c3de780046c78e96cf6b951e74db804dcea787cf/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/5cca68111c77887c0ae72246fbb9b9a2c85778f6/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/cd46c5d7d16fcf81e3fe87210729abb7156c62b4/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/66506ff943d67ddada873ed88253e3c1a9bf868a/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/de0c4c8e23e67111e8ec8d0d649c3b05680b43c9/vulcan-jenkins_W0) | :x: FAILURE
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/39a663c2cf0481c10ab3750d212d683654eaf0e1/vulcan-jenkins_W1) | :x: FAILURE
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/0286aad0df61314dadc0fe6e33a0d2681c9f1939/vulcan-jenkins_W2) | :x: FAILURE
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/d3f69f660867307aadae420a743e602c/raw/09863fadbc7748478ad7234d3a5bb64e95985336/vulcan-jenkins_W3) | :x: FAILURE

**Comment by yosefe** [comment]
@dmitrygladkov seems like test_uct_event_ib should create entities in its init()..
also, can you pls squash all commits after fixing this?

**Comment by dmitrygladkov** [comment]
> @dmitrygladkov seems like test_uct_event_ib should create entities in its init()..
> also, can you pls squash all commits after fixing this?

@yosefe fixed and all commits were squashed
thank you!

**Comment by dmitrygladkov** [comment]
> weren't the entities already created at this point, by test_ib::init()?

@yosefe 
yes, created, but they are `cleanup()`'ed when iteration through UCT entities vector.
I've changed the implementation of `test_uct_ib_with_specific_port::init` and `test_uct_ib_with_specific_port::cleanup` to not do this The calling `test_uct_ib::init()` and `test_uct_ib::cleanup` were moved to appropriate init-cleanup for lmc and gid_idx only.

**Comment by dmitrygladkov** [comment]
bot:pipe:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10775/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/6a869c998cec0cf45b0ca2f3ff756c7b9fd4f6a3/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/24b565a03cbd4d9fb7c312b106604025180cf5b7/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/2dc47fb53d00c8f4c1069dad331280593b7957aa/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/a8a18036b39553f6056b810c724da9be4a474729/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/87de256e29c899c6db6e1040cc9c72b0c2e719bf/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/dd420a58fd14dc220f4c2f61eec21e4fe970fa66/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/a0d32e44920b088ab1feee78ac2d0d5f238c647a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/cf68510a1dd1c147ad8d48af0495753430b866d4/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/e141ab3b53be0df5488c6f02fa77a3ea3c6a6f3a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/289488050cd45c4816b6ce2d5e0354e40dae6132/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/ce03ec0f2f6647f7e29e8fbe8f08ae3960489ab7/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/2121c77252ce0783348efaaea8e8de928d3d3346/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/60731edec3b322cdf38d2699e0e4b87a28d27997/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/ad3ae549a60f31794945f539d9d46b4fbf700662/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/e50250932f50d905ff80abb9c3ef6a57fb207e75/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/b793ab80946f400574e30e189c6ef0769ee639c0/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/cd3f2c3ffab190ce72286417809c7c671e724392/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/8f93cdefb6ab6516afc96576014113bd7bac98d7/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/cd10579390641d6291d4e1953a13a6b205a58b7e/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/046bd9b2123bbf90af5d20c82ba79d0fc73fc628/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/1b4c6cf38c810849425c66456627540361c79549/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/29818f870b1cf605d4d5d70642706736275ae5a8/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/45f344391a55a991045349f52ea11a8e3cfdfb55/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/2dd7a8be26869dc7db8684dd74cc32a8bb0333db/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/6b905d0942de57cde2ff3244870f082d5bfd7546/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/5763d0d31b2d6fd41bc3a1013cc59a002e3fca21/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/81ebfca5a726c07bdc4d80dc38a35f6237567f68/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/afa68d2887dd9e1341ac4cac521b730536225afc/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/a795a2507301f6fb699b8dc584e0b36112539776/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/cb93d2b720fa15b71b8c77cbac78597b167ab8ec/hpc-test-node-upstream_W0) | :question: UNKNOWN
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/35affe2d9637dd327c89720b9748607c15391cc3/hpc-test-node-upstream_W1) | :question: UNKNOWN
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/3e95b07bb628b4ca5567f98d6fe78e32a910e4f7/hpc-test-node-upstream_W2) | :question: UNKNOWN
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/57be31567bb113b5648c21711623bb7a/raw/60062164fef4c259d54ee999f0b3bf219e05d63c/hpc-test-node-upstream_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10782/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/9289b50631f0d4c887d7d92de74f92d58b0349fc/_main) | :x: FAILURE
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/745ccb5f5ac0efb62c94965f567ed293477534e0/hpc-test-node-upstream_W0) | :x: FAILURE
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/7d3b67bf887407aecaa3ee0c9ebac29703422a73/hpc-test-node-upstream_W1) | :x: FAILURE
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/0cc56bd38163f344439b5051427433a5fd800c7e/hpc-test-node-upstream_W2) | :x: FAILURE
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/1de5a10842ea444c1f43f00ff911e6a86d82ddb8/hpc-test-node-upstream_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/0a9465c6297b7228c36839e927ce8c3ca92a6f2c/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/f2fe0e927125b8b6a0544939602bd4236892721e/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/1832f3ed9fc24fccbdbe9179ad651af64da4a910/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/e7e800e43db22c2371397389a337cd56886c6124/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/acc833f580b97d6107387df17dbfd3d6ddc28afa/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/a7ae9ede95a2b82baacc9e163732c7f99ac5595f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/a0da6b6f3faf75367460e8308ba25b808db92181/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/e16d1d626ec01ddf324fd7deb0a27f66da064361/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/bc99116770b1a4e5f96a63104e89fef73f060339/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/07627b7746ea2165b0d4a44ea6d50853b1dba1f4/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/ab4499d41d38e1594dabebf06ca51ca1d4d6e548/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/de4a788a35df42ead8f57bd08c4dbf8c5e270e30/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/f251394129780ff85e50ea2eec96546843df662f/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/1c4fdbfeee34e801cd0ef0be960c12408ac319b3/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/aa4448fec1e6cf986898f4b1e111cca6324b3ada/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/ca0fcf53a04408815f49e82ee271aa081ab08eba/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/6aeca164028b4a1345eba6ea6490b3885ddd4481/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/a4c73a825069a3136708531c99bf4f492081999c/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/08d1087480fdb82480c6e159f11dd7471a5eba97/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/10245420ae839407d22689d47d4c3bf624fce860/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/e2539a779a89fe8667709f6a69481c1477a85a94/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/080d96e537fc1510908713d4d75738c58774c8c4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/75475d131a467f99c6dac8aac59c4f3686ec3ae2/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/dd6ae3f6e0bd043f478a355e8081b19f55670982/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/540c810f907f0f3c284d38498742c589a4a48988/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/98f89661c8a5c1ca2bd3b57f066608f8633a7fa3/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/874addb144f557ce8c252371bf9367d7352bdae8/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e204bbbc89aa12f0830e6eea1879cd86/raw/f9714e4b412899a62090675690f53d53f86f22f0/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
bot:pipe:retest

**Comment by dmitrygladkov** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/10795/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 01-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/8d4b63f397f784e7fdaffcfa1cfb6e4871e83b3a/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/70e3691f88eaf23245d66fc19966343f4e54311a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/c5bbd4c65bea175466421ce3eac1dcd328498233/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/99fe1f697cb3ef0f7d023c029adaad51ccc5da82/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/cad43d864c35907d556f90cb17db1c234fe35fe2/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/a02f63ef2ab096b1bf5e9840cf4df69789390614/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/4d3a2e11cd3305a12ad6a93a16c20e7ba6742a1e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/1cf433c0b4d6f5974f3c53bd6645f9ddf293eb2e/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/0c4df45adbc25aad3b0ecef227fefd9d57bf19e2/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/7269c1f6bbebc76984d85a556b04326ea0ecc7b0/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/3be4add1d5e6127cddc1168fd72e726eca7009c9/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/f70dc4655dbe515830ba0432fdb83a2bc66c3b2d/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/2b4a31c7ddd0dc123e8ec2bee26c8fd7941a4003/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/a4710fcc01b5d9f0f8f6a78df0147420bfc1a65b/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/5fa3c5c7bf2ef37ef1367626c25e3496716adc86/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/9ddbf50e37cab189e4c977365eaa53318ce06781/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/bafdfa5c083a92682473d4988189c44c86f5889c/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/967d152893281ee04d2526e754161c4d45e7587e/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/7b7c3eb79e6122a2eb2b2a5cee47ffbc2a2cd797/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/e63a105c7a41350caba523b1c4e09f6e7b3b6dfd/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/c0da4556d714b7bedc996ea5768c423d44497e01/hpc-test-node3_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/18a11d1e3b1def4d72923e3cf4c0c8016af00392/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/deed9da1a07a392aa4d8f83f5a0182dca6347b15/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/6fa67088e07e00ea6d710eb05f90206ac2619313/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/a208a9d82c5ae97bc692558850ce0a4e5038af7b/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/1bbcf60e1d766de6f8c0ea2632ecfe0d13850504/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/4e1683beb4da00dbcf85acdf9b72fb5fdd3d1d52/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/c19b67bc00b3ceb2fe96fad3aaaf64514ae1aae9/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/5d940b61f1d1a1bb3ca566e1b9388a5ffc73b00d/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/252548449b2d00b57ccbb711dcde65cc29e96f02/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/f66e1574d95e653134299a47c3b5ca9c56f1d016/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/34bbae9cfadcaba23026e7fea4527057d7982ccd/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4313999507342db78a2ccc408f3f3d23/raw/bbe5ce5f0ebd55a268cc1a44614ccb8fa3627c34/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygladkov** [comment]
@yosefe could you take a look pls?
