### PR TITLE
GTEST/UCS: Fix memtype cache testing

### LINKED ISSUE #7745: mem_type/test_memtype_cache.update_non_contig_regions_and_remove_subintervals/2 failed on GPU node
```
[ RUN      ] mem_type/test_memtype_cache.update_non_contig_regions_and_remove_subintervals/2 <2>
/scrap/azure/agent-01/AZP_WORKSPACE/1/s/contrib/../test/gtest/ucs/test_memtype_cache.cc:52: Failure
Error: No such elementptr=0x7f6ef0000000 size=268435456
[  FAILED  ] mem_type/test_memtype_cache.update_non_contig_regions_and_remove_subintervals/2, where GetParam() = 2 (1 ms)
```
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/32739/logs/377

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix memtype cache testing.

## Why ?

Fixes #7745.

## How ?

Update `init()` function of `test_memtype_cache` test suite to allocate `mem_buffer` on HOST and call `test_lookup_notfound()` to allocate global memory cache for further successful adding elements.

### CODE REVIEW

File: test/gtest/ucs/test_memtype_cache.cc [hunk 1]
```diff
@@ -22,6 +22,10 @@ class test_memtype_cache : public ucs::test_with_param<ucs_memory_type_t> {
 
     virtual void init() {
         ucs::test_with_param<ucs_memory_type_t>::init();
+        // try to lookup some host buffer to allocate global memory cache for
+        // futher successful updating memtype cache
+        mem_buffer b(128, UCS_MEMORY_TYPE_HOST);
+        test_lookup_notfound(b.ptr(), b.size());
```
Comment (yosefe) [inline test/gtest/ucs/test_memtype_cache.cc:28]: how about
```c
// Trigger on-demand create of the global memtype cache instance
test_lookup_notfound(NULL, 4096);
```

Comment (dmitrygx) [reply test/gtest/ucs/test_memtype_cache.cc]: much better, done

**Review by yosefe — APPROVED** [review]
