### PR TITLE
UCT/TCP: Close TCP socket when unable to send data

### LINKED ISSUE #4243: Error in ucs_socket_send_nb results in an infinite loop
As far as I can see, [`uct_tcp_ep_send()`](https://github.com/openucx/ucx/blob/master/src/uct/tcp/tcp_ep.c#L491) translate any error returned by [`ucs_socket_send_nb()`](https://github.com/openucx/ucx/blob/a5225ac407f8939c85d57ab9c190eba9fe43767a/src/ucs/sys/sock.h#L143) as a zero progress count.

Thus, when [`ucs_socket_handle_io_error`](https://github.com/openucx/ucx/blob/master/src/ucs/sys/sock.c#L217) returns `UCS_ERR_IO_ERROR` it is interpreted as _no progress_ and the system goes into an infinite loop where it keeps trying to send on the broken socket.

cc @Akshay-Venkatesh

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Close TCP socket when unable to send data anymore and report an error to a user from `uct_ep_am_short()` and `uct_ep_am_bcopy()` if `uct_tcp_ep_am_send()` is unable to send data

## Why ?

Fixes #4243 

## How ?

Return error code from `ucs_socket_send_nb()` to a caller

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12488/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/01fad1e01c7aa6551749b290bc9e1367858eb6f0/_main) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/af961dde76457f7a4799e99de5bca5ac458da237/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/a071fef87eeadce87d5c95c848934915476069d8/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/c33b74d12beac1ad0a541195ea4d83a00cee3b80/hpc-test-althca_W0) | :question: ABORTED
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/29ea75368dcfdd186a9e3fd53833295a5d828ca1/hpc-test-althca_W1) | :question: ABORTED
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/ead477f25334d96cd08d9eb9f3c1d0c0419835c9/hpc-test-althca_W2) | :question: ABORTED
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/bec53dcb51e11fa7066e77c9ef7d5ffe1dc4d733/hpc-test-althca_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/c512c6fcce94c670c9edd5817f2d065965dc395a/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/ded73e8ce95e7d98165e9a57345eafc1ed7a4c68/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/5a0af453da2387fd7cdce470fced1d686b48e526/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/6547581f05e11eb28bf0eb184f3d163587541f3f/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/f11eff727259cd6a094bfede7fecd3e0c4edaa08/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/d63849d44f39946836dfbdc94f985cf3cca4e591/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/7f7bed505602f4c9a193e1bfff7a800524963a2b/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/176e738294c850e0a72bea941514ccb69f0f3938/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/9b6ecf22d621cca6576e15fb9067725cc55d4066/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/762cae09615731ff2cc2bf74cae032ceb6f008ba/hpc-arm-hwi-jenkins_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/121f2d242ca3aa02271350e02ec557d6c4d0581e/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/8d54432e236b902168e39cfa8a4983c90d529674/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/b0500ae3ebf9cb0fe8cb93cf1e6cbb51cdc6355a/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/7addc560ea7a49d529b4065989904fe0f97973fd/hpc-test-node-gpu_W3) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/98854a85a82f4c35b56358775ffa40073ec9087d/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/c5887d23ebf7531e4c45417c7bc9cc4a6a286525/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/6c498743194e52da676118ebd884dcc5f75a4f24/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/546cda1be5b751b6e87aa21fe8270ce24d23244b/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/58786b084c9adb02d4b504d5c8e860162db9c50e/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/cec4c342df69c3baea0f9f9e351ff2fa6846b79a/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/23141cbfffaa3f44e04787b5f73e3028045d1664/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e0ba325d092a2f30944444ceab6286a6/raw/a8f92ef978d9fcea53d2c3ee47c92343189aee1a/hpc-test-node-new_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12489/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/1c941705d91e9504d984b0640dfd94fb44b4a00e/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/8dbaf46f72b209a385c12204dbc0d862ccde89e1/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/b2fa47b95cdaf22e8789f7ea17602d4424e2a13e/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/f4bb28547870f7fd3c72581f2cbbdcedd967f6a8/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/04abeab92b7d83be720ce63d7172fa5875ce2778/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/11da5962344794ec2d9e4233bdba111906ccb319/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/d1df1087bf27af303661eb8f584794b25510774b/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/eeddef79dd1a9784cf94fde840a8f353f354e5b4/hpc-test-althca_W0) | :question: ABORTED
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/126e524cd4bd7e93591b40e8a6f08d3dac3557db/hpc-test-althca_W1) | :question: ABORTED
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/637c3585c9af336c84c2d888f099caa3432f00db/hpc-test-althca_W2) | :question: ABORTED
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/49c4dc2aab9b7ba3bfdf2fa2cccd060bac69e17f/hpc-test-althca_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/5eeb86f28f1517114c208a3e4f455f87cb7ae4a2/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/ba54f7144dee980eebf557e5d9ecb98f67b59c27/hpc-test-node-gpu_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/3cdf2034a4dc83b788bbf3fff547e7ebbb7a8462/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/35678c35352738edba714f01768feda3b60fc8d6/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/9b158a62e227604648be55abfb9cbafaf1b5abcf/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/6af728d9f532d0aa9e783bb8d92a877ed43f6c45/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/55733930777ba993600575b6d03fc63829664b0a/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/9eaba8dad73a2e7a76338f4461921746e0fbb8d6/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/93c14b1829d95b10af6ed2ddf0350ff64ae27436/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/8adcf1d8c7db831a553ec7e9ba0a29fc03666f13/hpc-test-node-gpu_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/3de21d3bbf5b29a47c0c5b576e208304d07d3779/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/775d6e3d9dd88f73268d1888cfe1f16d750e352c/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/ec07ee528dcb311b66e4a10456d2bcb950ead769/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/7aa9763ffd3d4d803bf11f408cbd3c7c270a1bcc/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/73aa5b15f5b42227e56c8b3866596c175f732de8/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/e6981b915bb6416b8f589102db5ecd975102470b/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/59875012195c88174d3d2c3ec285e2e23f355c9c/hpc-test-node-new_W2) | :question: UNKNOWN
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9c6df4e8acb4faa8e2993e8cf81ab226/raw/7b4601a45913fc15ed3c0f14c9cd8e24e2a296c4/hpc-test-node-new_W3) | :question: UNKNOWN

File: src/uct/tcp/tcp_ep.c [hunk 1]
```diff
@@ -499,8 +500,9 @@ static inline unsigned uct_tcp_ep_send(uct_tcp_ep_t *ep, size_t *sent_length)
 
     status = ucs_socket_send_nb(ep->fd, UCS_PTR_BYTE_OFFSET(ep->tx.buf, ep->tx.offset),
                                 sent_length, NULL, NULL);
-    if (status != UCS_OK) {
-        return 0;
+    if (ucs_unlikely((status != UCS_OK) &&
+                     (status != UCS_ERR_NO_PROGRESS))) {
+        return (ssize_t)status;
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: why `(ssize_t)` is needed?

File: src/uct/tcp/tcp_ep.c [hunk 2]
```diff
@@ -534,6 +536,8 @@ static inline unsigned uct_tcp_ep_sendv(uct_tcp_ep_t *ep, size_t *sent_length)
         if (ctx->comp != NULL) {
             uct_invoke_completion(ctx->comp, status);
         }
+
+        return (ssize_t)status;
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: why `(ssize_t)` is needed?

File: src/uct/tcp/tcp_ep.c [hunk 3]
```diff
@@ -615,17 +619,22 @@ static inline unsigned uct_tcp_ep_recv(uct_tcp_ep_t *ep, size_t recv_length)
...
     if (uct_tcp_ep_ctx_buf_need_progress(&ep->tx)) {
-        if (!(ep->ctx_caps & UCS_BIT(UCT_TCP_EP_CTX_TYPE_ZCOPY_TX))) {
-            count += uct_tcp_ep_send(ep, &sent_length);
-        } else {
-            count += uct_tcp_ep_sendv(ep, &sent_length);
+        ret = (!(ep->ctx_caps & UCS_BIT(UCT_TCP_EP_CTX_TYPE_ZCOPY_TX)) ?
+               uct_tcp_ep_send(ep, &sent_length) :
+               uct_tcp_ep_sendv(ep, &sent_length));
+        if (ucs_unlikely(ret < 0)) {
+            //uct_tcp_ep_handle_disconnected(ep, &ep->tx);
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: leftover or useful comment? pls comment in c-style and add `TODO: ` if it's something useful

File: src/uct/tcp/tcp_ep.c [hunk 4]
```diff
@@ -799,15 +808,20 @@ uct_tcp_ep_set_outstanding_zcopy(uct_tcp_iface_t *iface, uct_tcp_ep_t *ep,
...
     size_t sent_length;
+    ssize_t ret;
 
     ep->tx.length       = sizeof(*hdr) + hdr->length;
     iface->outstanding += ep->tx.length;
 
-    uct_tcp_ep_send(ep, &sent_length);
+    ret = uct_tcp_ep_send(ep, &sent_length);
+    if (ucs_unlikely(ret < 0)) {
+        return (ucs_status_t)ret;
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: no need type casting

File: src/uct/tcp/tcp_ep.c (hunk 1 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: removed

File: src/uct/tcp/tcp_ep.c (hunk 2 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: removed

File: src/uct/tcp/tcp_ep.c (hunk 3 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: leftover - fixed

File: src/uct/tcp/tcp_ep.c (hunk 4 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: removed

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12493/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/c705c6c8074131f581e8a5d54b1d012df657acbb/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/10b865783dd015408f09667afb1c9054d0918938/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/4f128ec895f6030918126a1b5fa9a10f5b88906a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/6d5681728ce4c43e7bc0abfd612c1e1b3b61c067/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/96092d54a2c347bc372738834c204127b3f3fccf/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/a521fedc621e96e38449745e8ae7e567e01eac51/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/d5f2323adb134447d32dd1f465ca8d4a287e343e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/ccb4fd080b5b3df136dcc5d0844eef443236368d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/0a2803c89b43d2a22798ddeac32c6108f1390d3e/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/86b96f52b5ce858aa7834d0a4a2dfecb953c8897/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/900f4cba58b5134af6fbb0f97616b02355823031/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/633e6751d614167c33fa5d79487ffb8a9b4991db/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/01105e75f33cce3c784051aa4e15ebcf8ef3248c/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/c1ee15261b3a272a955cda25d1e7df526e5d2e6e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/597d93937c4abb54e8655d9353b5140d1b84058d/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/3fea6fc66013b5237c2d5867233060a9760edb00/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/9982d7b561291e9dc40ecb35fd679054e1a63d98/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/3e6c07a020479ae5d1a4b3e642fb7ef4a0beb031/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/e24d1499a8169b8a41c4c842b417dbcf5fe599b5/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/2b8deafa42d5bfcf145ca9d89708b50fe2843177/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/984b046704c5e72c93a0d6ca20083ae6f6be3b37/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/334d52befcc1eaf01a30ec09f7f1ec578fc6574c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/be08bd49b3447701605c5fff15b46999db58c047/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/411ca011b98f4b1e2e4164f404adde3a88383481/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/76bb1162e09bf5431ce3d94a458e61227c20a4e3/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/581da12d678405c41818f514f11f96ec776711c1/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/cc72bf960c2a9e050394bea56a8a0ffa46d8c732/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/070c9c80dc8ab3413bb033328e9611267bedd2ca/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/306457532d22c82599023d791b30c35d/raw/08bde9585aaf754e4b839d3f3205427c722d2996/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/tcp/tcp_ep.c [hunk 5]
```diff
@@ -499,8 +500,9 @@ static inline unsigned uct_tcp_ep_send(uct_tcp_ep_t *ep, size_t *sent_length)
 
     status = ucs_socket_send_nb(ep->fd, UCS_PTR_BYTE_OFFSET(ep->tx.buf, ep->tx.offset),
                                 sent_length, NULL, NULL);
-    if (status != UCS_OK) {
-        return 0;
+    if (ucs_unlikely((status != UCS_OK) &&
+                     (status != UCS_ERR_NO_PROGRESS))) {
+        return status;
```
Comment (brminich) [inline src/uct/tcp/tcp_ep.c]: maybe return -1 instead?
BTW, why need to return `ssize_t`

File: src/uct/tcp/tcp_ep.c [hunk 6]
```diff
@@ -534,6 +536,8 @@ static inline unsigned uct_tcp_ep_sendv(uct_tcp_ep_t *ep, size_t *sent_length)
         if (ctx->comp != NULL) {
             uct_invoke_completion(ctx->comp, status);
         }
+
+        return status;
```
Comment (brminich) [inline src/uct/tcp/tcp_ep.c]: return `int`? Also why need return value to be ssize_t?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12496/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/a5d7f21fe15c05353ff3d81bd7e6bd6c5602759d/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/13dd1dbb3dd9ec1c8c2c9c4db4bc68fc97909ffb/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/3e81202487cf0e081492e77c662134bafb64c07c/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/95b5b7a855d334c0760c16b7754b6e3fa440753b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/ccfa20222b8bf37f2f00e9de2a96adf914d23683/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/de66050992dfdf14af6f2f51f9d1654162c01fde/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/b7462abab15bf75c86b746b11c884bd5030ea91a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/54f051880703485ea24cc1a3066f1f6b0bf04c32/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/b2e6f472a2ca8111134306cdffab6306fc02089d/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/61e69e4e66e98b60c52d7bb2a159652bef09523e/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/00daa3d841278b0d65e4fa3cee66fa3bdeea4cf3/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/78d1cc532629a4f9772f037fdb6b1fb2765782a5/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/c7254611ffb8904026cec85105c25c467d25b8a5/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/f45a42614f312b8d23cfec000686e9e38e40506b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/a2bd049dc5cf6511817f45ad40a6690f16f33131/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/7d906634c68ff107a5f45fdd7bdfe8dd9f715506/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/0342e596fe276abe4d22c688702815a3e474040a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/b457ce3a54a98292eed0339ccfd1ffc6d1e55131/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/997bd4b13c1b99a624aa41343a7dcc86b2b203fa/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/a3a5b15874ee2836de8158ffa05db8d911a7a7c8/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/9d69b2ad15e11105c8a80b93cd9c0f252ff2e7df/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/97978d2ccb2cc8be9f7c6a37accec1e8e67301ca/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/c64c5c1af234f9febfd3c727e0fce82c3d6c0c2d/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/adf801e1e591b39d95998e74fac9e5df9f2ec16a/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/3cebadc3dc7dea1b2fe60575f6b4883a74a1507f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/85dcb2d8c18d88c935f3cad09fd7bd42e66eb8f7/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/7d8dccdd20dd3640ea7b572396d6473c99e1f000/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/4fc062594399386ea10b7bdb63daac140959cdd3/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cad1e2bb5fb87893d89ef73e62f35484/raw/4860d2350e3451a6b640eec32e184fbb37074f39/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/tcp/tcp_ep.c (hunk 5 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: we would like to return an error to a user for AM functions, so we need to return `ucs_status_t` rather just negative value (`-1`)

File: src/uct/tcp/tcp_ep.c (hunk 6 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: fixed everywhere

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12500/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/1258bd2ab81a74b19c6dd8444ed241ec6313ee1a/_main) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/06720c8a67e0b1ae14d71b743787801644d63cae/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/1e6e5ccb1fa68801dcce268a8aebfe07ed7128cf/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/cbc7f745036f31be082003727afb9f6387b2c66d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/782140602f67ed45c67e8e5b732b58d1c718297d/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/e55dc82a978b0dee86d9b240690f3c609b64861d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/ed08ae69b993d75935db23950602d686cf609a3d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/0518f3b06dba5f76ceced04705cd5389694966e2/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/004f44c3316dcf3c6fabf8409f8a6f9273954c87/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/9edf31a0db988151eebef499a0ab767ab00960bf/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/b7d7e4728bb7637651e54379a7cc3e8448b7f8db/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/4ae510ebf25675450015822e04d6acb3dcc989c9/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/c4d403e4b8147c110e555bf24bf879f7fa5a10ea/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/be655aca20088cbc7d70288cef88b4edf2bb27d3/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/df4aa00151b4e32fb90844a58a9d5f95e9af2d72/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/0b19a6b8f9f6b7d812af89c45435ef4b2a952819/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/d406ac10026d791ef09d9cd182ad2a92915122b2/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/bd48b463d579f5789cae4ab68913d1095a850d27/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/adc4b41bc1e867fe303b2e72450a61b71c67d245/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/00f53a084c7dc1b86d6e177c26ffefb0bdb40fa3/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/1af76e54bde53ce4aceab19fdca9facce82866f6/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/0c875728d4be5a415a15e3f0a09201b8b9dfd6db/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/426ec6cba3b6b1013d500ea445b29712f484ed9f/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/bd13bfef0424ba8e6575d4df15c1310c0da4ad29/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/4250c34b72052f17b578db0c315ce51f238fb0fa/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/260fa6f49fad429dd3473b0d3af6add7cbd96ddc/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/ffa5fd6b508dccda2f1fa2b8f92a20d93de7b0d9/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/e512e0dc09bc266c860d6166217ae8b702a71218/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ef7445968e2ddb5899200ad39c3a83df/raw/8420c59ae92da888fff0428b768c1995f879c953/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12503/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/9320b4fcddcba63909fb665f3dd92757a1d4ea84/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/a623c30f1ca2c128a5b77c585225f3413bd084c9/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/1921da63106418f1884a011bd23ceea63a147311/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/452881e23ac9c40caa8008ac105ca65822a6538c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/07a10670b5713abd723eccbaedb6ccfb23a3204d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/c01b2410721ec42efbe7f0eee3a0049db6435f81/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/bdf70ebcc9abf7f26f673052ce222ae2d96df207/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/9dfa3d8bfb861e611699a64fc0ae5b4cfbb2b86d/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/23b1ab7302d0993b41cd5182bf369f5a214f77bf/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/a244c2132230044acc9bd68f898a97e948542e6f/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/cd892d5910c4d6a42364d805494b4f04c96c5e50/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/8dbb7e8f9e6487911126cf76239c00ad9cab2b02/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/d6c0c0c26da8cf6b174a68ebaeab626275214ae6/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/5ef8f50ed3562a11e5ac09e1cac53d0386fe24f3/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/24fa063bb4075012d6c150b8751e7bf3b6e931a0/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/7a78361bb1070e9f620dc240c2ac680a63a1978d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/fde3b96e17524a9092f436b8b58a880531124ed0/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/00c463605551648d1c042e0fa4859a596e534558/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/6742e15403af9751919fe9d7d0b1cbeb68f4403c/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/44d2ae7829af95bbd55660bf9fdd4c5354668d53/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/87e35cd3886bc9b72895974a9ee7bf50f851573b/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/4f40889fec34a5ea940c91ea83ae91eb10df1810/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/15f786701724e4a10773712164a686ce322e9824/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/a348e328957a14506b7b57a468a5bacf1ac7e21a/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/857f07ed2f5bab904457291795e436be9b60f890/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/7b83a9d319ff8ff0c0a0092188ff9a0b709e11de/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/ccb7d382d61d265afce4fc4560b568f444029af8/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/08a6fbc86fc9e928b8ced0648da8657e2edde82a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9efb76d8ee40070b4b36e7b9cb1e9f33/raw/ac7ece2db64c5ec0eef82d2fd17ab5c7287e22cc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/tcp/tcp_ep.c (hunk 6 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: > return `int`? Also why need return value to be ssize_t?

because `ssize_t send (int __fd, const void *__buf, size_t __n, int __flags);`

`int` may be not enough

Comment (brminich) [reply src/uct/tcp/tcp_ep.c]: but it returns result of comparison only, not the length itself

Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: Ok, missed that

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by brminich** [comment]
@evgeny-leksikov, do you have other comments?

File: src/uct/tcp/tcp_ep.c [hunk 7]
```diff
@@ -616,16 +620,21 @@ static unsigned uct_tcp_ep_progress_data_tx(uct_tcp_ep_t *ep)
...
+    int ret;
 
     ucs_trace_func("ep=%p", ep);
 
     if (uct_tcp_ep_ctx_buf_need_progress(&ep->tx)) {
-        if (!(ep->ctx_caps & UCS_BIT(UCT_TCP_EP_CTX_TYPE_ZCOPY_TX))) {
-            count += uct_tcp_ep_send(ep, &sent_length);
-        } else {
-            count += uct_tcp_ep_sendv(ep, &sent_length);
+        ret = (!(ep->ctx_caps & UCS_BIT(UCT_TCP_EP_CTX_TYPE_ZCOPY_TX)) ?
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: There is a kind of mess of return values:
`count` should be changed in any case if something handled including `UCS_OK` and unrecoverable errors. 
`count` shouldn't be changed if return value is smth like `UCS_NO_RESOURCES` , `UCS_NO_PROGRESS`, `EAGAIN` etc.
I would suggest to use one from existing return value rules:
1) `SEND(2)` (then need to return `ssize_t`, check against `-1` (+ `errno` in case of failure) and no need `length` parameter)
2) or `ucs_status_t` (might require more checks)

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: Implemented 1st variant, but return UCS status instead of `-1`, because a negative value is an error. So, we don't need to check `errno`

Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: then you can't use `UCS_STATUS_IS_ERR` and other checks against `UCS_*` status values

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > then you can't use `UCS_STATUS_IS_ERR` and other checks against `UCS_*` status values

why?

Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: because it mixes 2 different approaches

File: src/uct/tcp/tcp_ep.c [hunk 8]
```diff
@@ -489,48 +489,52 @@ static void uct_tcp_ep_handle_disconnected(uct_tcp_ep_t *ep,
...
 
-    iface->outstanding -= *sent_length;
-    ep->tx.offset      += *sent_length;
+    iface->outstanding -= sent_length;
+    ep->tx.offset      += sent_length;
+
+    ucs_assert(sent_length <= SSIZE_MAX);
 
-    return (*sent_length > 0);
+    return (size_t)sent_length;
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: no need `(size_t)`

File: src/uct/tcp/tcp_ep.c [hunk 9]
```diff
@@ -540,7 +544,9 @@ static inline int uct_tcp_ep_sendv(uct_tcp_ep_t *ep, size_t *sent_length)
         return status;
     }
 
-    return (*sent_length > 0);
+    ucs_assert(sent_length <= SSIZE_MAX);
+
+    return (ssize_t)sent_length;
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: no need `(ssize_t)`

File: src/uct/tcp/tcp_ep.c [hunk 10]
```diff
@@ -619,24 +625,22 @@ static inline unsigned uct_tcp_ep_recv(uct_tcp_ep_t *ep, size_t recv_length)
...
     ucs_trace_func("ep=%p", ep);
 
     if (uct_tcp_ep_ctx_buf_need_progress(&ep->tx)) {
         ret = (!(ep->ctx_caps & UCS_BIT(UCT_TCP_EP_CTX_TYPE_ZCOPY_TX)) ?
-               uct_tcp_ep_send(ep, &sent_length) :
-               uct_tcp_ep_sendv(ep, &sent_length));
+               uct_tcp_ep_send(ep) : uct_tcp_ep_sendv(ep));
         if (ucs_unlikely(UCS_STATUS_IS_ERR(ret))) {
             uct_tcp_ep_handle_disconnected(ep, &ep->tx);
             return 0;
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: return 1

File: src/uct/tcp/tcp_ep.c [hunk 11]
```diff
@@ -814,21 +818,20 @@ static inline ucs_status_t
...
-    size_t sent_length;
-    int ret;
+    ssize_t ret;
 
     ep->tx.length       = sizeof(*hdr) + hdr->length;
     iface->outstanding += ep->tx.length;
 
-    ret = uct_tcp_ep_send(ep, &sent_length);
+    ret = uct_tcp_ep_send(ep);
     if (ucs_unlikely(UCS_STATUS_IS_ERR(ret))) {
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: `ret <= 0`

File: src/uct/tcp/tcp_ep.c (hunk 8 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: removed

File: src/uct/tcp/tcp_ep.c (hunk 9 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: removed

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: `0` means that call progressed no messaged

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: fixed to `ret < 0`. `ret == 0` is normal case

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12517/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/3cfbf25793b5332c31bb07f56bffc4dbde028525/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/b8feea84a2a4a108ed7d079374559091184c5ac4/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/d22fb6da67e824dcd44591dbdf27f535d098b012/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/93e3dc211d8f1e1205eb7aeebc988cdd865aae23/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/23066825e6b255fd467e8c9967d4f3342cfe3148/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/37e85b9a4f816d5305f2137860bd7411aeaab830/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/4bf6380eff0ee140c8f43cd8441c6ecc1eddd20b/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/822ad96770cc4e167707ee6341358ba7ebbaf3df/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/db17792e97fd1ef0852ff10ec415084a170c402f/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/454dff6edec1a02768901f86a739386b40d7f28e/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/e185e2e44eaae8fa170190bf6fb093ff7dce7e4e/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/5c3fb186c106dcea9180d8e9df5e23d8ad33bf4d/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/4c9b55f0dac3e515c2a394f0b079a13779b17682/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/4f85f9c925ed5c09d7b4c8455318e0955bf4f29c/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/03b7a468ebc649822953e1df3389b3d773db72ad/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/b2cdd8cdc726659a8b3b29c2da830ffa8730cea8/hpc-test-node-new_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/2d60150a180cd81b04314c71c01c7c8b85e6adf2/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/24876bfb8965a3d3bc4ce50154ba9d6011bfe8b5/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/4dc0590f713b4bc4e7ad0304cb4f0e32f7faae96/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/2ecf18c21ca85f1c099122d51669452a4b5d1149/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/82b4aa1d63b35a3d6d0da8af4adafd699618b964/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/6f43ebd6924a5439c8d8d35a71d872842ae1e90e/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/e5c2413d5fdf93c9f7821279ee04dff4c73e8be4/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/c98d7f4fe1a5a407fb5eab5e2634ecc570062cfc/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/77761b358992b521de1b89ead1160d833f0296dc/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/dd9a4cbe9f7553e635ca3b394dc7843720933986/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/fa2916662c95f154a04ed7c957f871c05779ab4b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/19ed4ba7901b0aa8696c481040cfe87dfb9f9751/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7dcf18bb29e618e05b0eb687bbef5e0c/raw/11b5bcfb3439d5f25080aa253049a585dc437020/hpc-test-node-gpu_W0) | :question: UNKNOWN

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: failure needs to be propagated to upper level well as successful messaging

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: only if send length = 0. how do you handle 'NO_PROGRESS'?

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: `uct_tcp_ep_progress_data_tx` is called from `uct_iface_progress()` that doesn't support returning an error to a user

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: if `NO_PROGRESS`, then `sent_length == 0`

File: src/uct/tcp/tcp_ep.c (hunk 7 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > because it mixes 2 different approaches

checking for `< 0` now:
- `< 0` - error occured
- `>= 0` - normal case, where `> 0` means some data were sent

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: I meant input send length parameter, like `send(fd, NULL, /*length = */ 0, 0)` then it's OK but if `send(fd, buf, length /* != 0 */, 0)` returns 0 that's NO_PROGRESS. How do you differentiate these cases?

Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: BTW, read comment above as a pseudocode because `send(2)` will return -1 and errno = EAGAIN in second case

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > anyway we have to return `> 0` value from `ucp_worker_progress` if something is handled, including failures.

IB returns 0 in case of failure:

https://github.com/openucx/ucx/blob/079359fcc9011efe547833c36072cf203a1d5d90/src/uct/ib/rc/verbs/rc_verbs_impl.h#L118

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > How do you differentiate these cases?

we don't need this
and also `ucs_socket_sendv_nb(length=0)` is impossible (we have assert for this)

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > BTW, read comment above as a pseudocode because `send(2)` will return -1 and errno = EAGAIN in second case

this will be returned by `ucs_socket_sendv_nb` as `sent_length=0` and `status=UCS_ERR_NO_PROGRESS`

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: IB returns >0 on TX
https://github.com/openucx/ucx/blob/079359fcc9011efe547833c36072cf203a1d5d90/src/uct/ib/rc/verbs/rc_verbs_iface.c#L119

failure on RX side is fatal
https://github.com/openucx/ucx/blob/079359fcc9011efe547833c36072cf203a1d5d90/src/uct/ib/base/ib_device.h#L303

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: and this info is missed here, right?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > and this info is missed here, right?

what info is missed here? do you mean to add some comment?

Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: > > How do you differentiate these cases?
> 
> we don't need this
> and also `ucs_socket_sendv_nb(length=0)` is impossible (we have assert for this)

I see only assertion for `iov_cnt`, number of bytes should be controlled by every implementation of `ucs_socket_iov_func_t iov_func`, so `ucs_socket_sendv_nb` can't guarantee this

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > IB returns >0 on TX

no, it returns `0` from foreach in case of failure for TX:
https://github.com/openucx/ucx/blob/079359fcc9011efe547833c36072cf203a1d5d90/src/uct/ib/rc/verbs/rc_verbs.h#L17

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: > > and this info is missed here, right?
> 
> what info is missed here? do you mean to add some comment?

You can't correctly handle `sent_length=0 and status=UCS_ERR_NO_PROGRESS` and `sent_length=0 and status=UCS_OK` cases

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: sorry, this is for `ucs_socket_sendv_nb` only:
https://github.com/openucx/ucx/blob/d2f67c6e48e59be8b52504b41d9def135658e629/src/ucs/sys/sock.c#L243

TCP removes zero-length buffers from IOV. I agree we need to add `assert()` for `ucs_socket_sendv_nb()` to check that all IOV buffers are non-zero-length

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: No, this case is also fatal

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: I don't think this is a right way, 0-byte messaging often is used for synchronization (not sure if it's possible for TCP)

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > You can't correctly handle `sent_length=0 and status=UCS_ERR_NO_PROGRESS` and `sent_length=0 and status=UCS_OK` cases

why should they be handled correctly from the caller's code?
Both of them are normal situations and don't require special handling from the caller's code.
They both mean that `0` bytes were sent and everything is good

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: yes
the same for TCP. if `send()`/`sendmsg()` returns `-1` and `errno != EAGAIN/EWOULDBLOCK/EINTR`, this is fatal error

Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: so you call `uct_tcp_ep_handle_disconnected` on `EAGAIN/EWOULDBLOCK/EINTR`?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: no, because this is `UCS_ERR_NO_PROGRESS`, i.e. `uct_tcp_ep_send` will return it

Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: Ok
1) when this branch is executed?
2) you have to return 1 here because of handling disconnect event

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > ucp_worker_progress might return wrong value

we have `assert()` ensuring that data to be transmitted `> 0`:
https://github.com/openucx/ucx/blob/e07916faf31aff2251d08a8a8982d9f24026af3e/src/uct/tcp/tcp_ep.c#L499

So, in TCP code real send of `0` bytes is impossible. The only case `uct_tcp_ep_send` returns `0` is when `UCS_ERR_NO_PROGRESS` occurred.

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: I got your idea, will be fixed

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > 1. when this branch is executed?

when an error occurred, i.e. neither `UCS_OK` nor `UCS_ERR_NO_PROGRESS` returned form `ucs_socket_sendv_nb()`

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: How does this assert ensure that TX data > 0? AFAIU it guarantee that sent data less or equal to buffer size

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > How does this assert ensure that TX data > 0?

```
sent_length = ep->tx.length - ep->tx.offset
``

`sent_length = 0` iff `ep->tx.length == ep->tx.offset`
but this is already handled in `assert(ep->tx.length > ep->tx.offset)`

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > AFAIU it guarantee that sent data less or equal to buffer size

yes, you're right - this check for this as well

Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: sent_length is in/out parameter, "out-value" can be LT "in-value"

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > sent_length is in/out parameter, "out-value" can be LT "in-value"

yes, right

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: do you mean that `sent_length` "out-value" can be `0` and `status=UCS_OK`? and we should return `1` from `uct_iface_progress()`?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12518/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/84fb635d1ee87b3ff43cc2dc4a11ef9ffae94d04/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/3e03b2f725e6c43b062ba5a21882a34ff5f72a89/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/bd9ea6038b7082f2940f8b3c4b1ff472e00bd03a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/88abe44335047b802737e7a75c6aa1836a2e0b58/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/2dc2c9de7f7abff161411f4e42fac979c42b50ec/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/0852f61edd439b50cf81b108a0090a631f5dccce/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/cabf6e8397d36afa6f0fdd89032f31f1d650d039/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/e542cba942194d0a4ebd487fdf4f65bad46aeaf5/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/7f23060ce8aca13194c5c8cac73a8aa6812cb536/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/e3262942992498df4a394d7ce097eaf3317f36bd/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/1bdc2d90d81a18b0aef295e61e2e418457c4b1e5/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/9bc5f06cfd93fbf2ce41bada24713fc4b5faf59f/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/e853b3ee16265c29c0fdedc72438b4bc2cd3e40d/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/fee86d59899f81594f96943ddbba43e7b63d30af/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/eefdb1511305315b3454dfdf2ccfd50bc5f1cdc2/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/7902a4da61dd07aedef05a89bd717670c1f6bdc4/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/29b8c3c28366f118bc7419b5df0080af27e70f44/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/77acbb62493a625b729da3df5e5c823f0f785cbf/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/c9dbae61e7864048d091f25998e9a02cdfc62ae9/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/b303c8a8416c466c9aa543d41f1d4b0a698a819b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/013636fe1def3f32837b40a777dc98acf2abfa61/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/20a9611da90ec1bf972067144c8bf098e8516a03/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/45666815181c3ada40a42987afbf5be33dc35d29/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/39bcea76f275a6b18a0053a2ad9ccbae645ecfb8/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/77cd1ab5d80930f3f0814bee0048d0b3fc7d40ee/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/bef9e6891acf28a6df3bea2023a3507c3ffe34ef/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/c1f69c63aa74f08ea78bf2d4ad72ab2413fbc86a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/517d2b984657d27bf82266629f88b49998e46524/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/26f1840ce6ec8fd1ddcc3f4a6e33ca03/raw/ffbe5aa1a915d24b17977ec7325a65c384369cf6/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: I mean `ucs_assert(ep->tx.length > ep->tx.offset);` doesn't guarantee explicitly that "in TCP code real send of 0 bytes is impossible", even if it's really impossible due to other implicit statements on different levels of the stack.

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > I mean `ucs_assert(ep->tx.length > ep->tx.offset);` doesn't guarantee explicitly that "in TCP code real send of 0 bytes is impossible"

ok, let's assume that `ep->tx.length > ep->tx.offset`, e.g. `ep->tx.offset == 63` and `ep->tx.length == 64`
could you pls share how `sent_length` can become `0`?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12520/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/cddf312076293021ad75ae30a16c25295ba37683/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/13ead4f5e1978add7abf6a9d091955039d71e250/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/7194159d81dd56551164850ac19b5bea6c6ab8d7/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/8478adddd166775c840871bbe6af2b057ce24751/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/d164f507c4f176cc230fd3e61af7db369afc7447/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/839be79e784c006a27631a56d6ea5c363cf55e7d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/2387313c92216a5b7df6b0f6105141280da8c354/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/32654b7ac40c05be4b4763d400df00a4d4066f9b/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/4ac04804e10be13d5de714d8371f02c59f790afd/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/91d34e2b7ebb4133bcd796462b203702c7fe488d/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/d81460772504c10dd2cfddf7bad8e8d4875fa3b7/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/cdf0ef357b0bf9546dcff0151686c6c0df7723aa/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/561f97be2abf2743498229e0319b45800d713fd4/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/cf44643f41c1a7c161bcc670d1d68cd1616d19d0/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/998dda9e9be35ede19fd91232a148439bb79f83a/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/98e68659aad2525915781f1fa41e14a616968062/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/a87c6f430e49f3e4a01b011af6820fa33419d426/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/dd404b5cc2e567270712bd9ec139e18b97d61fa2/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/91921ba7ca78a7282941a4293d5d6edb2800dc08/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/88a0175940ea8753e52ff3290360223872e35797/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/a9b1cf9ce660ddcc1ed5c4cbc3e8a33bc9912483/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/9c0cd84ebbe9a5c980d25d160578e5b56d4a8915/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/5be557f39ad213bf74981f8959c789c363476cd9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/74fd12facbac9b7359517a4a0b7d1f89fd95c329/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/5ad182578ec10b493a180353ee94b8fbb77ac16c/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/3b010252a81fc8c09bc191c44600c96ebb775f33/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/ccfe14221caed7520945eb37eacd3851b103688e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/6c7fc3223c84fd015d0b3527ff350a60505be1c6/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e0ac6759684474a6468ab51a2b359c3f/raw/43ac5d9cff203fe300a50100d8f569e14409a3c0/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/tcp/tcp_ep.c (hunk 11 above)
Comment (brminich) [reply src/uct/tcp/tcp_ep.c]: `ucs_assert(ep->tx.length > ep->tx.offset);` guarantees that we request to send non-zero number of bytes. In this case `0` can be returned in case of `NO_PROGRESS` only. Other errors would return something `<0`.

Comment (evgeny-leksikov) [reply src/uct/tcp/tcp_ep.c]: I would like don't investigate this every time when see this code, e.g. during debugging of hardly reproducible bugs. This is possible according to the docs and API.
My original concern was about mixing return code approaches and possible missed cases. I was not going to block or require any changes for the PR but I can't approve this as well. I just pointed to possible issue. @brminich if you are OK with this I have no objections.

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > I would like don't investigate this every time when see this code, e.g. during debugging of hardly reproducible bugs. This is possible according to the docs and API.

What is possible? `sent_length == 0` when `ep->tx.length > ep->tx.offset`? How?

```
ucs_assert(ep->tx.length > ep->tx.offset);
sent_length = ep->tx.length - ep->tx.offset;
```

pls, provide an example when `ep->tx.length - ep->tx.offset` gives `0`

File: src/uct/tcp/tcp_ep.c [hunk 12]
```diff
@@ -474,69 +474,79 @@ static void uct_tcp_ep_handle_disconnected(uct_tcp_ep_t *ep,
...
+    ucs_assert(ep->tx.length > ep->tx.offset);
+    sent_length = ep->tx.length - ep->tx.offset;
 
     status = ucs_socket_send_nb(ep->fd, UCS_PTR_BYTE_OFFSET(ep->tx.buf, ep->tx.offset),
-                                sent_length, NULL, NULL);
-    if (status != UCS_OK) {
-        return 0;
+                                &sent_length, NULL, NULL);
+    if (ucs_unlikely((status != UCS_OK) &&
+                     (status != UCS_ERR_NO_PROGRESS))) {
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: 👍 missed when this check was added on this level

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12525/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/9627a616445182bc9322796fa0f8f6d9c0c4533c/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/aba52a18cf9335f2a866ce0738f6247a2e3aa0ae/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/19f108db48eb4eea0820d10e3a7fd09e5c37ace1/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/4e3dc516abca36dbf5592cbccdbff7028d5251ef/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/613f9868c1d1323ed4f62a162f3f1b5af11957f2/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/76b0082ec199555cbd11becd4044df7b6e9ec47c/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/3bdab2dd6730a18facb910789b1f1ffefaed6351/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/c240387bc40b6278b6131f96bc6eacb8caf8995a/hpc-test-althca_W0) | :question: ABORTED
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/d0db21ab7728c0f201ea37838142a20b635a3eff/hpc-test-althca_W1) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/f8589fb319c77511850a2dc323ec39cadc1dd4ea/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/ec7dfa87be8e0ae982da1a645d42064c60d21625/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/0a287028f5bf93c34aff9cff1aa6b01b268428d0/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/ef130038713876e5ace3a153d685fcb4d3f1d114/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/89ead7737dca7a3b5e737d6c0829bcd7cc02ef6f/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/1a117c5589731b64a02ec82818103d1f536d1412/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/505f82ce3e329d8eb19b6192b1bada367fb6a59a/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/2809b09bf0439170d4ab44d9bb6870a77c82d253/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/60c38dd2901472c20ed9b1451b9971abcefd9782/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/ae7e886d6d73f82e8a7bdd117b374c1b50060235/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/da50c0a1cccc3818113f3da379164ef6f638b5bf/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/11b58781a1b210c5ae6292e50772ca94ce6659c5/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/e30a5565af8a30b1cf9b693115c44ff0c0e0d749/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/d1d0bb56304a3e510037e03abb4f87ffdfaf0fd1/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/e7983c95ac97d453d740809e6a5696a5809efdc1/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/569be8af6aa62cce451b021a99f1ddb8c52a80d1/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/661e7fd4f6f77bc8ded4d96738c1ec9c55432f97/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/ee2d06469670c7d24119abdb3ac39cab042cf3a3/hpc-test-node-legacy_W3) | :question: UNKNOWN
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/321ef9686a71c4e68740a7cee3fa33c6433cb0ab/hpc-test-node-new_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cc2fc830ebcdd88e382e046bb3bc5a0b/raw/f5f47e79e5ba06aeda2970c83431c3d641335938/hpc-test-node-new_W1) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12523/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/4bed1e1021c1d17aba3748e9c5ffc5f42c4d4e6d/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/0ac2ca1086b337936764985c69fed61f69b0f507/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/3de6ccd1432e87536fc6a8e54c0c34eb20ff186b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/296b808c1bdb68699218630f0a522a1591808c73/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/db008797d018c50334b20bd841a04b13ddd4e4ed/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/373f9d8ebf3e0b43a469b7f1ce0fa7801f873bb8/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/f5e5061b3a0da7f1ed7dab29fe3790182eba4f3e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/756500d7af8a429c239d26ffcfb620f4cef6ce29/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/a19eae3f07ead84149fa662a643353be927a0396/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/85c619da2ff902fa1a0781823e22ab1296ec5ff2/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/300283f291b2e1c3ca3c928c79d36fd6b41e1ba0/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/6288a186b80af8428ca8a3e38573c593598717b1/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/588dc459d1a31548b1e9677024e7d37e8d746b5b/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/690183d861899672546342ca382605db62b04c01/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/9f56052a3452958bbc4bcc86155b297945b43ef6/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/a5f27364d5d9378250ee677e3dd24b9aac75fd79/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/8443a8c8797e68c0b6d32efaf7db20508fbde721/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/99e14ac73c1e0a622765d09bdea298c1c56d6112/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/10ae24e9b6d54258dea247fd73983546a9174487/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/48bc4afcc3db0c26ffc4362d37e33ea1b565b11d/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/cc62186bf99ed3d30051d077b19a476fd871de74/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/8f6f591f7aaf4c2fd51400437f0a2d18e258123b/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/f7094732ac1b68e6c5ae69241a8792d5b893e475/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/a0ca82bafd5ae9f78d2ad6e5c64d3beef86d31a2/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/32c25ab2eb7d20a478e1e70942217d11aed6778f/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/cb5dcb390ed46e5da61b344a5934a0c9d1babdf9/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/462fa143d0b12e0ccb7ac5b61c1d7f906a2da73e/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/442242924f424f6bbc47e43dc58f2ef55442dac8/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/91cad9ad0d98fcd9fcd2270f478af9ea/raw/17b9db9387062444135487094bedd74d8bfdedca/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12527/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/379655822238817b98391fd8c44136eb5a9faaa0/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/a1cbc3950abaeb07d08543367b9211e5e95c9ca2/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/f6caf9fbe45e40d1a4e302a126e52bf4aa34b079/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/858fc85f462ed7dc92dc4c5caa5409ae18d1a4fa/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/0efcfc9813c711ad0c7eb101e38b5bbfdb14676c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/28ed4c6492e7a025e9108fa1b495b0b84c6813e7/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/a0a5119ecef18566d5e318b0676c50f7cfc4936f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/86d365f5a39890325a48ee9ec4b7dc8e5342f3e3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/07482ff29cc8dba6357119959c016439d42b9594/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/bed299e8775b808ea59b6e102d838a0b32927bfe/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/fa19bcd42c63c5eb6033b57da0d769ef34a2ccb1/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/cf3cc6940008c19b261ffc5e3709c2372fc35d8b/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/c3963401959fc7a7c8b437d89158abc9225d4754/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/eee5a9e47a082b8322c32e4e274bf90a0895acd0/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/31efa30b4cd5e65247ea6c0b33c750cf0f317d87/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/233f333c873ea9dda7ee3c7828ced9afbdf1e260/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/96c1ed5a2648443986c1eb7e146a63a34eda921a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/513bbce23ea8acf384b7f09d85bbe431721f7b1e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/0e1e85ff6ee7960b2c6143613b67ea76f70bf54e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/0d22e358701ac5f1cd3db62103c33425555aeeab/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/b9c2a5bc9716bf046de7d24d63cf8b6943639501/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/b10f2fc2e2ffbca1ca11539971d7af0ce6836c98/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/2c573d681227e027872afc41e91795dd5ba7d3e7/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/9a7acec2eb07aeb632fc07b93979fc8e330b0cf0/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/7829fa0a3e1da0f14012709e00e436454135a30a/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/997b6821769f75d880631e2da4c0a7a5a84c3b65/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/7020cf05b5a469ccc666080490bb3843f98ecd2a/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/093a86b5770d9bb9b1d3b7f607f9ca1db154cbfd/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/44ecdb24912b979bd834eae90b87caec/raw/62d7d7e09a84aeb4b3e0880ac6bddf8b25db7af7/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@evgeny-leksikov @brminich thank you for the review
ok to merge?

File: src/uct/tcp/tcp_ep.c [hunk 13]
```diff
@@ -799,26 +827,32 @@ uct_tcp_ep_set_outstanding_zcopy(uct_tcp_iface_t *iface, uct_tcp_ep_t *ep,
...
+    if (ucs_unlikely(ret < 0)) {
+        return ret;
+    }
 
     uct_iface_trace_am(&iface->super, UCT_AM_TRACE_TYPE_SEND, hdr->am_id,
                        hdr + 1, hdr->length, "SEND: ep %p fd %d sent "
-                       "%zu/%zu bytes, moved to offest %zu",
-                       ep, ep->fd, ep->tx.offset, ep->tx.length, sent_length);
+                       "%zu/%zu bytes, moved to offest %zd",
+                       ep, ep->fd, ep->tx.offset, ep->tx.length, ret);
```
Comment (brminich) [inline src/uct/tcp/tcp_ep.c]: looks like `ep->tx.offset` and `ret` parameters are mixed

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: yep, they will print the same value, but it was done to align with other printouts to simplify `grep`ing
see, e.g. `uct_tcp_ep_progress_data_tx`

Comment (brminich) [reply src/uct/tcp/tcp_ep.c]: let me clarify this. 
`ret` shows how many bytes were sent during out last send, while offset shows how many bytes of the message were sent in total so far.
Can't these 2 values be different at some point?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > Can't these 2 values be different at some point?

yes, the can

Comment (brminich) [reply src/uct/tcp/tcp_ep.c]: so need to fix it?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: `moved to offset %zd` -> `%zd bytes sent`?

Comment (brminich) [reply src/uct/tcp/tcp_ep.c]: I'd change parameters, like
`"SEND: ep %p fd %d sent %zu/%zu bytes, moved to offest %zd", ep, ep->fd,  ret, ep->tx.length, ep->tx.offset);`
Also please fix `offest` to `offset`

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: `%zu/%zu` but first `%zu` means total sent bytes

Comment (brminich) [reply src/uct/tcp/tcp_ep.c]: ic now. Please just change   `moved to offest` -> `moved by offset` then

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: sure

Comment (brminich) [reply src/uct/tcp/tcp_ep.c]: `offest` - > `offset` ;)

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12535/ for details (Mellanox internal link).

File: src/uct/tcp/tcp_ep.c (hunk 13 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: > `offest` - > `offset` ;)

fixed :)

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/119172d2b9aba1e76b0bfa2ba53fe3abfe1303d0/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/75bb19b007bab86300ea54ae6b0689969ec63ef7/hpc-arm-cavium-jenkins_W0) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/000ef2cd0ca3093361962bd53ba6ed061221695f/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/be69f2811b1155c65b130664aa2ac11d3bfc1ac2/hpc-arm-cavium-jenkins_W2) | :question: ABORTED
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/343f2c1ce1b1e059a34a1c2d0a583d279925bd51/hpc-arm-cavium-jenkins_W3) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/eb04ec5443a202419e04689a9faa7b869e199ca2/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/50f30c756c58704e37ad66f32fe43cb1e28ca546/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/8d1de86d4251f9f2db0d2fc25c84937a0b6ae7c0/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/b4b4d654a40730d93fbeb6cd65a7c81ee8607eb8/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/98d5fbdca3fff942124e0e509574bbd41bafee46/hpc-test-althca_W0) | :question: ABORTED
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/a6e3c4f4857caf64c0a425e5e7e02c6f5910e29f/hpc-test-althca_W1) | :question: ABORTED
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/f5fa2bddd57192d9f2cd1f6a32d1f737f19192c9/hpc-test-althca_W2) | :question: ABORTED
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/56a6d26c966b34ad99b42046a88f298261a023f5/hpc-test-althca_W3) | :question: ABORTED
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/c80cf2f5d8c4dae5a34bfa800a3e7922fd1b341f/hpc-test-node-gpu_W0) | :question: ABORTED
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/8977bfeae52ac5b1494afbe2f13b22b563438ffe/hpc-test-node-gpu_W1) | :question: ABORTED
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/963bfbe99aa621643925e4e781dbe7cff1c9682f/hpc-test-node-gpu_W2) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/76fb898ab86ceda4f003fd02ffd0e42d3d15992f/hpc-test-node-gpu_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/fa732c12c03208d50110677afa970ddbba6d201b/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/9292b36725ad39d7d6cdc5235423acec7206a3c9/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/fe7ebdff90b0cd9e812beaa15fe4f4d87d6e7b97/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/014afd0b1e16a6dcf70679a1a2c898637196d197/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/de379833019a296a98ea2278faf57284fc65add3/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/1b3427e823456943fe0673af1d7697f96f05502f/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/966e5e298b84b2fdce1e7dc728838f14f4a6f4ba/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/b9f3a29b9c9a7f1314c83d926cd23269ca3b612a/r-vmb-ppc-jenkins_W0) | :question: ABORTED
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/cc42b662a2b07fe6b7d6d7bd03647dc1ed74bdc3/r-vmb-ppc-jenkins_W1) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/aeebc056b2b687aa3ce7d13e07cb96c64cac1f01/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/64b2ee4527c7cd0e9ddb0d8f1df21a5523f86dae/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cc9d318b8521235cfc948aa753633157/raw/8a382dbb8fcc54d4fae56aaf766902f81c41dcea/hpc-test-node-legacy_W1) | :question: UNKNOWN

File: src/uct/tcp/tcp_ep.c (hunk 13 above)
Comment (brminich) [reply src/uct/tcp/tcp_ep.c]: where?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12536/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/6a07b23e63c13f1856e1338fb57596c0a532299d/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/57bfb4a5eb10e55890ee14da63ffa3b984acc4ca/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/30b558c3c1b2c2c8011582cc4d7cf5b7e2cf6b6d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/f672e654e79b981a0f2cc8d43e429157b8a7a96e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/db9710c6e076447350c1b0c167fe33deed2b1472/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/544ffb74937b5e8b3f57cd4c5e028b730808fc5d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/3c1facf99064874eaccc56597fdf8fb021f631f0/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/8c58ed442f4cbd8469bf9f4a19f43b610b7c7ea6/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/580691a428b637e749426f3c57254cc0f66eb7b7/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/66e9233cb556cd9810b00e05946b42cc39e9c9fb/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/31ad4de05c50e7873262d95fe79535e9a9ad2628/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/ba613ef6bdcac788a8ab2c8ed392fd6debee2526/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/09abafb88cf3ffb23a5cd582408886a6227ce266/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/dd7a90781dfd1d9f104c5c580e9e7d4dea2cee8f/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/ba71b18cef32b7eb59c6a8477d8fd1adddbad162/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/eaf88c58fc884db376a13116a50297cbaa915913/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/178822dc577959e099056c1029d8b9755f720d3b/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/b82e2f544717c0702698a3ae36bdf638a8f8f91e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/cf8374b990a87ba2df0b7cc63bd00c89c4b5132a/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/f610e308abf9d2de50926b652cea3bb8b589da05/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/5959f02a1827784f5bbd181eae3b61be84fef100/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/f9a81d98cbe458455f7a0c24ba28a26b11042f6d/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/ddc51f01b8ea94f1b142c580fb63ad717eeb0555/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/65e33bad06ff7a2f16dfb7a10e8c59bab2f998bd/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/ea868a12880b2d1ee9e8d196567530e5c173744a/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/b504d1331150d4e0d8e8fe58b9b04ff62b12777f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/699502d919e433776b59c232c4ebc630c4e4db81/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/e596c2f8b73a395aadd757276b5bec599fffe708/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/58db05ced4134d1cb1ea0e804c240028/raw/ab2abe084f6ca229e005baab488fcb2ccb0304d6/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/tcp/tcp_ep.c [hunk 14]
```diff
@@ -615,19 +638,22 @@ static inline unsigned uct_tcp_ep_recv(uct_tcp_ep_t *ep, size_t recv_length)
...
+        ret = (!(ep->ctx_caps & UCS_BIT(UCT_TCP_EP_CTX_TYPE_ZCOPY_TX)) ?
+               uct_tcp_ep_send(ep) : uct_tcp_ep_sendv(ep));
+        if (ucs_unlikely(ret < 0)) {
+            uct_tcp_ep_handle_disconnected(ep, &ep->tx);
+            return 1;
         }
 
-        ucs_trace_data("ep %p fd %d sent %zu/%zu bytes, moved to offest %zu",
-                       ep, ep->fd, ep->tx.offset, ep->tx.length, sent_length);
+        count += (ret > 0);
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: minor: seems like `count`, actually, is not a counter and this var can be just initialized here. maybe rename `ret` ->  `offset` like it's mentioned in trace below and `count` -> `ret` ?

File: src/uct/tcp/tcp_ep.c [hunk 15]
```diff
@@ -799,26 +827,32 @@ uct_tcp_ep_set_outstanding_zcopy(uct_tcp_iface_t *iface, uct_tcp_ep_t *ep,
...
 }
 
-static inline void uct_tcp_ep_am_send(uct_tcp_iface_t *iface, uct_tcp_ep_t *ep,
-                                      const uct_tcp_am_hdr_t *hdr)
+static inline ucs_status_t
+uct_tcp_ep_am_send(uct_tcp_iface_t *iface, uct_tcp_ep_t *ep,
+                   const uct_tcp_am_hdr_t *hdr)
 {
-    size_t sent_length;
+    ssize_t ret;
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp_ep.c]: offset by analogy with above?

File: src/uct/tcp/tcp_ep.c (hunk 14 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: good point - done

File: src/uct/tcp/tcp_ep.c (hunk 15 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: done

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12540/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 25 workers (click for details)</summary>

**Note:** the logs will be deleted after 15-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/f421f111e8e228b4e80c18e50a7f266d327b1dda/_main) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/2dd3270912a03240f8edad8a897df1c987880f96/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/f1e5ab11d9b5e7c593c813a3ab0751555ae089cb/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/b93b062446a09fa8b45af19495c610ca5a3c5e68/hpc-test-node-new_W1) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/f9f4cca23e30fd6259ce4fe7274c5b6316df50b6/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/c84b90766e96c2f18ce453773c786eb046c4dce6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/4334cf2d8992343835156e65875eb67d7e92dd3b/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/ed71c57cffe45bf8ddb94428587f260d449f46ca/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/1c785d1d26afee976d18de63d71b1a9391f00292/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/1cfa16d13ef4d66a089a98f3adc985c9939a0fdb/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/b078aac8d10fc9b8a95afa7a825713c359871610/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/08e1794a72a19da98854f2e3d11916ff4f06b7cc/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/e644d183ed4f9b9c1ad50b39c4377571831ba7f9/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/8fee2af4ad2c55fa57f05b634d09059f65a25abc/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/1e1576e0d537f67d0c9f42c25ea16b72283d6106/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/29d78e08c2d17187d48cecd21c5e7ecc38266798/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/e42c0c45374d4424395ee7f394d24a6d1b669a5e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/a5f98eb634a283809ee1f2b0c7e70ece20e1a490/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/af281b8eb9d0c8fb6c1bbf13d8e51be914d4597c/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/f370fdeea87e82e7701b28ad58c739e552fec10a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/46d4387357e25fb38d7078d6734d4bf6ffa341da/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/1077ca2140f083e018c59a47e936514f8a881299/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/e7b603bf777e6d5c8c20729943749d2ba63abef8/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/f0a28f83e1563cda96242248557537e7ea4ad0df/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/ffae3ecfb8f4b66058fc68e7aef8b281/raw/1b98f59eac339ee174cb4241a667bb9eef124796/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12541/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 5 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/af9fbfdc715969dd664ebe6250579f865df1abdc/_main) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/ff38354fe4cde7b356a080e84e0b0ce768b163a2/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/3655f81b1cf8f5acc3076a4c53bc783510efb218/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/5213601c3a99635d87c9b809c19e44d700a386cf/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/6a08bfcdeda71bd14812461f710cab48b170863b/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/2ef3bc17af4aeac2df447823127fa560b495affc/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/abc351a69689161307a835eab98fcffc29b190e5/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/3b26c56889214649d1edef0ed6479c1cb0310555/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/7f62848f71675b9df09ed2d1243bb8d7eea65a71/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/4b26930dca3d9ea9b4f41e9480a87ca5822f041e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/cd54c1c26b8f4af6a4f226c46a8a3931ee42242e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/b9f3e3577b9e51e490d7c94b9a5362dcf49076ba/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/dc31bd4f94a99931eadbeb1da8d489031489e848/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/50c29eac983e9eb4f7a175495d8a466caef8bda3/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/36efec548e5cc5352e9cabd684634424979fcbc1/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/ec1de9be8f7e137e2874a98f544aa98724bdbe89/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/64400db0980d4b639088aafaba64841d60696efa/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/f4ae40b11fd2c6d3136f270c4a25514d2a039dab/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/7373ee4229a49b1482066b678d2a1889dcf5afb0/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/b907a161cff40a20612970602fe13a900c410a5a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/751d55d0b030be947b4239c5ad33d122fbe4ac38/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/c8ff553b12596f512098d2fbc148d38a88768690/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/bbcf578ebec2a97d0579cfe751ebf757f1fc5dc7/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/b66f6eafac66f5e1fbd7c00a712d6a9c7255eeeb/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/e36729b85e8be162aa522b2154701df19f43c33e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/61688b1657ce5f085f07e9129ded72d79fae4311/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/4e966d693e9c132ea6fff08ce3b66d7b55eab597/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/7114464afaf1195cda37abe48a93a4d2f1d30a6e/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/705c813936d556ffb9349d3ed5082239/raw/1c0f48aa872a3774554e7e950b5a9d56080198dc/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12562/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 7 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/78924e2ffc1c3b64a6eb5b3a3b6c89a8/raw/b290e6d8f377737b071676ac96eb1bec6d76722f/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/78924e2ffc1c3b64a6eb5b3a3b6c89a8/raw/3c2d89e5aaebc60d47b0bf54f375606053eec45c/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/78924e2ffc1c3b64a6eb5b3a3b6c89a8/raw/daaa4eaa93d177e085051a9ae7723ef9df6fb3f9/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/78924e2ffc1c3b64a6eb5b3a3b6c89a8/raw/2ee2a0b7842b575fd8ab35596788262495a679ff/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/78924e2ffc1c3b64a6eb5b3a3b6c89a8/raw/c35ac2b0b88c957b5f90be398558367bb003e205/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/78924e2ffc1c3b64a6eb5b3a3b6c89a8/raw/a12ba83b7e1f60802e4a34612b4d91b322e26194/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/78924e2ffc1c3b64a6eb5b3a3b6c89a8/raw/2f0fa62dab6f40b17e2eaae3a422b3b836ec1610/hpc-test-node-gpu_W3) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12555/ for details (Mellanox internal link).

**Comment by dmitrygx** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>UNKNOWN</b> on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/af8edadd5a70e70b3eab1f2eb8951efed8adae1e/_main) | :question: ABORTED
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/4ec52ba1c7090ed723a782e11e98e2c2382e109e/hpc-test-node-new_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/6491241fa44382eeb2d90c4781ed7933fe46a3ab/r-vmb-ppc-jenkins_W2) | :question: ABORTED
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/a472debd28d2fec3a0c260f0831567a6d187a7ad/r-vmb-ppc-jenkins_W3) | :question: ABORTED
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/ac6ed9e17e86f4d1c4f33f4d155a8f42c26c63a8/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/66ae9cdf6f7d973d7a4aac2d4c5e49b7befdd217/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/757825b9688d6aaad7c427ba6d4e34a8d734ab5e/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/0b85ccd085fdc5a0375d2dfc5a8c41f06e514779/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/0a9914e2476fe71ee26d1577345009b03352c572/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/f22d71c5ce3f9d59c48f8de3a77777a9077228cd/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/8c6842767ac4b2adc8dc11a921ef791433b963e7/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/00234ce1d865dc5d0d2ff0305f5d227560ee9beb/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/70e9f5871d9447dd795c3ffb0336715c568d4c49/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/3296c281190adcbe9755f6afe46f553d5d82b63a/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/570d5f6cf07cea56023af3c1221e28552851a78a/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/b8fa1d1117b86c660f25e2f643ae9be8adbf99a0/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/e483efff3c05411029d16e026352b8a6f0f105e5/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/ce6dcad2b37aebeea2324a6687f2ffca9f159154/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/3e06ee0d9cfcf2925870bbdb617d366977da914f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/40845215b5a65cb6c1f82b8804407a7e55ae2382/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/d76a91ad65809de39f46aa6ea49a07b17765472f/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/887081fb40833db61b7f303270b9d3b2dec0a21a/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/4b17af5402a16d3e636d81daa2b5baa56783c23a/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/753e8f0e9f3dc40bb75d63e9f3918914645d6ae2/hpc-test-node-legacy_W0) | :question: UNKNOWN
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/0b61d69c51b5a18ffd117d7ea29315fcf86e0679/hpc-test-node-legacy_W1) | :question: UNKNOWN
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/4ac9422c345e446803c6d0db1c5643552e56aff7/hpc-test-node-legacy_W2) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/9a457526cd7c1003d774f82370addee5d4f0b540/hpc-test-node-new_W1) | :question: UNKNOWN
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/5248cfbb5d84612252620593a954a10e9249676c/hpc-test-node-new_W2) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/92df099883822bada220f32a84629c91/raw/6bc089dba54b00fdf5b3eeeafdb23fcd16c45323/r-vmb-ppc-jenkins_W1) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12563/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 6 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 17-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/040aec88fbd226a433f811410b13dfec2a3902de/_main) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/160fbbdd7ad62fe442fc5892e1805a267e5948af/hpc-test-node-legacy_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/40842787be1eea4a6137d091cf2dc3552e6c632a/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/5f95c9b6bd3610e1e212addc327f6352c2b7cf31/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/3d3f061dd29d4101639b2bec561516ee7b62197f/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/2564a89396bfe7a040f55354d6837788ca60f571/r-vmb-ppc-jenkins_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/ccab92883c405d0cb0851a0872fc329760924316/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/6aed9bbf0b5cc4bd659216e83038e3c82e45c82f/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/2a68372e6bd4bb2018ecf54294a779602d5a0100/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/f8e1b80d7bc285745fd6c0ffe903cddbca47864d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/8607f6b38f80c308e2c58bb6aa23278ae6ca4dbc/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/e0153cef752c553c51f8b0d58b28012c9060ce0f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/3156d51a55ed350d8c60a4f34055e9da4ae848f8/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/84add0aec87da7ee21d8ef377ae02865c96fe95d/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/d5ee51cd9e0d422311428a2115d7d634d698d376/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/bdd5d0629ce79132bc1c89a15b97a05eca10a3c1/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/115f954221978fdcab662fdeb1904a05400293af/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/109fbf0e164b1b58b781e5dfd4395da82f84bfc8/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/0485becf122561817835b09e02b5e82e7b437d20/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/b500689ce693fa6fa3231f260f9c41561b7b8879/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/59ade75e79618dd4b323a5cf95d1f3bd8d3be56d/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/ffec3951e22cecb996e3ef26d79cf4c3b537eb47/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/2b4395454d0083c5319b87cccb130a63bc8f86b4/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/6482fb70d405f8f319d8c6327c438ae5515478da/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/4a14b118b35dbc074b9084a746ef713e713d1be9/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/0be00a30b63b1605e2f0a03ae9beabd7c568f946/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/aba9162c4779d06afd46c3608833a40b8c198b84/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/e4893672eaa34094b15f7fb5200aabd53b7f14a2/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7a125f529cebbecb0abd2c3bc6abc19c/raw/86c13d48b14af1a837f4b87e2b128161222e1cdb/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12577/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/ca62971f3a5135034ad52632512fd00156d7b276/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/eb0ced9d8591b0f3e6c338b7d99534bdac8420fb/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/c560736a464b3ac9af38f3429b4183644f3848ce/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/d2f999f98542f8442fbfa12f02a3162b7dc81b16/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/90b3541214cdf5b497dee3333b546fa7b947cdb4/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/5de4284d541af6e23c3934a9efa55176059f5fb3/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/8f452423b98068a6928110166de2a6ea46266b90/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/fb62dde3d0bed302419c20a81adca74323ab609c/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/a979bb92c43c9862840dd0284515f7778f7871bb/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/3d32e7a0d8fbdd0eaea7ade8b9c59f56e69ad2de/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/9c18b3bcc60a276a0ed811cf4d57fb565fa06a39/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/a1c62280e689f8e66d79b6de68afedc746be183b/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/c9b7fb60d3112e114cadd6c8199c92e31cb74984/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/3f00ec27b2a95e3563182cdf219d0430c33c8b3b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/1b258975961a3d7b58147fd4611b82d6c874d30e/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/35e4bf549acc79f08fc0ebffac8662706d5e0c99/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/93c243fb8841d982de2c6d34e152239580014147/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/9296e5c7ffe2e0545f1d93a4498a083f542cc0d5/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/b8bdae28f458c36d69077294edd26cfa836912a2/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/9c841f8dd60458a08b13f2758bdc0c5d299126d2/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/8a177722febaa7b10a4af122429bfb94d0fc4f93/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/6e9a6a52eb94821643d15875903b1c60a1044b93/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/f68fc0f28c4f6a99cc5581c5b665efc85c39266a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/f58f7eee706d59cd314c3e45398da29d6d978a27/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/72686223f39762dfbede82b841127eba23376111/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/7c2487153b264231285e59c4c7b582c1309309e2/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/c83dbee7c778ece8b1bef1cc14242ec9bd4e00c1/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/57c2b18c542ea2d31be72fdcd24b4b86fcdc57da/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b94c8deeab67dea7f14b6a812f049fb3/raw/557a251135f00696502d7d975ea8f5495b832e00/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@brminich ok to merge?

**Comment by jakirkham** [comment]
Could this be backported to `v1.7.x`?

**Comment by dmitrygx** [comment]
> Could this be backported to `v1.7.x`?

@jakirkham sure, done - #4305

**Comment by jakirkham** [comment]
Thanks for doing that @dmitrygx! 😄
