### PR TITLE
UCT/TCP/BASE/GTEST: Fix reachability of loopback ifaces

### LINKED ISSUE #6695: UCX 1.10 with TCP-only is unable to reach destination
```
UCX_TLS=tcp ucx_perftest -t tag_bw -s 1000000 -n 1000 10.150.166.222
+--------------+--------------+-----------------------------+---------------------+-----------------------+
|              |              |      overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | typical | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
[1619044902.015564] [host:33810:0]           sock.c:261  UCX  ERROR connect(fd=23, dest_addr=127.0.0.1:47793) failed: Connection refused
[1619044902.015588] [host:33810:0]        libperf.c:1238 UCX  ERROR ucp_ep_create() failed: Destination is unreachable
[1619044902.015607] [host:33810:0]        libperf.c:1724 UCX  ERROR Failed to setup endpoints: Destination is unreachable
[1619044902.021124] [host:33810:0]       perftest.c:1652 UCX  ERROR Failed to run test: Destination is unreachable
```

But when I do the exact same command, by forcing the interface, I get:
```
UCX_NET_DEVICES=enp161s0 UCX_TLS=tcp ucx_perftest -t tag_bw -s 1000000 -n 1000 10.150.166.222
+--------------+--------------+-----------------------------+---------------------+-----------------------+
|              |              |      overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | typical | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
Final:                  1000     0.000   385.838   385.838     2471.70    2471.70        2592        2592
```
I have the loopback interface, and also the `enp161s0` interface. Here's ifconfig for my client:

```
enp161s0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9000
        inet 10.150.166.223  netmask 255.255.255.192  broadcast 10.150.166.255
        inet6 fe80::e42:a1ff:fe61:4a8c  prefixlen 64  scopeid 0x20<link>
        ether 0c:42:a1:61:4a:8c  txqueuelen 1000  (Ethernet)
        RX packets 722009727  bytes 5372543023782 (5.3 TB)
        RX errors 0  dropped 5  overruns 0  frame 0
        TX packets 783147794  bytes 5957117294447 (5.9 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 123318880  bytes 2655187036841 (2.6 TB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 123318880  bytes 2655187036841 (2.6 TB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```

And my server looks the same, just with the other ip address. Any ideas?

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix reachability of loopback ifaces in TCP transport, when those ifaces are running on different nodes.

## Why ?

Fixes #6695 
TCP ifaces on different nodes and using loopback interfaces (i.e. "127.0.0.1") shouldn't be reachable.

## How ?

1. Introduce common local address structure and add `get` and `is_reachable` functions to fill address and check reachability (the implementation is copied from SM).
2. Add `ucs_sockaddr_is_inaddr_loopback()` function to check whether the address is loopback or not.
3. Use common local address functions and structures for SM device addresses.
4. Remove `in_port_t` which was used as a TCP fiace address, since it is not needed and it is already part of the device address (`struct sockaddr_in`).
5. Use common local address functions and structures for TCP iface and EP addresses. In non-loopback case - `sizeof(TCP iface addr)` == `1` byte, in loopback case - `sizeof(TCP iface addr)` == `17` bytes. Before this change it TCP iface address was the same length for all cases - `2` bytes.
6. Added UCT/TCP gtest to check that iface and EP addresses have expected lengths.

### CODE REVIEW

File: src/ucs/sys/sock.h [hunk 1]
```diff
@@ -459,6 +459,17 @@ int ucs_sockaddr_ip_cmp(const struct sockaddr *sa1, const struct sockaddr *sa2);
  */
 int ucs_sockaddr_is_inaddr_any(struct sockaddr *addr);
 
+/**
+ * Indicate if given IP address is INADDR_LOOPBACK (IPV4) or in6addr_loopback
+ * (IPV6)
+ * 
+ * @param [in]   addr       Pointer to sockaddr structure.
+ *
+ * @return 1 if input is INADDR_LOOPBACL or in6addr_loopback
```
Comment (alinask) [inline src/ucs/sys/sock.h:468]: typo (loopback)

File: src/uct/tcp/tcp_iface.c [hunk 2]
```diff
@@ -119,18 +119,48 @@ static ucs_status_t uct_tcp_iface_get_device_address(uct_iface_h tl_iface,
...
+
 static int uct_tcp_iface_is_reachable(const uct_iface_h tl_iface,
                                       const uct_device_addr_t *dev_addr,
                                       const uct_iface_addr_t *iface_addr)
 {
+    uct_tcp_iface_addr_t *tcp_iface_addr = (uct_tcp_iface_addr_t*)iface_addr;
+
+    if (tcp_iface_addr->flags & UCT_TCP_IFACE_ADDR_FLAG_LOCAL) {
+        return uct_iface_local_is_reachable((uct_iface_ext_local_addr_t*)
+                                                    &tcp_iface_addr->ext_addr);
```
Comment (alinask) [inline src/uct/tcp/tcp_iface.c:161]: indentation

File: src/uct/tcp/tcp_iface.c [hunk 3]
```diff
@@ -119,18 +119,48 @@ static ucs_status_t uct_tcp_iface_get_device_address(uct_iface_h tl_iface,
...
 
-    *(in_port_t*)addr = iface->config.ifaddr.sin_port;
     return UCS_OK;
 }
 
+static size_t uct_tcp_iface_get_address_length(uct_tcp_iface_t *iface)
+{
+    size_t addr_len = sizeof(uct_tcp_iface_addr_t);
+
+    if (ucs_sockaddr_is_inaddr_loopback((struct sockaddr*)
```
Comment (alinask) [inline src/uct/tcp/tcp_iface.c:145]: indentation

File: src/uct/tcp/tcp.h [hunk 4]
```diff
@@ -280,13 +280,30 @@ typedef struct uct_tcp_ep_zcopy_tx {
 } uct_tcp_ep_zcopy_tx_t;
 
 
+/**
+ * TCP iface address flags
+ */
+typedef enum uct_tcp_iface_addr_flags {
+    UCT_TCP_IFACE_ADDR_FLAG_LOCAL = UCS_BIT(0)
```
Comment (alinask) [inline src/uct/tcp/tcp.h:287]: could you please document the meaning of this flag?

File: src/uct/base/uct_iface.c [hunk 5]
```diff
@@ -732,3 +732,53 @@ uct_ep_keepalive_check(uct_ep_h tl_ep, uct_keepalive_info_t *ka, unsigned flags,
...
+                         ~UCT_IFACE_LOCAL_ADDR_FLAG_EXT;
+
+    if (!ucs_sys_ns_is_default(UCS_SYS_NS_TYPE_IPC)) {
+        ext_addr->super.id |= UCT_IFACE_LOCAL_ADDR_FLAG_EXT;
+        ext_addr->ipc_ns    = ucs_sys_get_ns(UCS_SYS_NS_TYPE_IPC);
+    }
+}
+
+int uct_iface_local_is_reachable(uct_iface_ext_local_addr_t *ext_addr)
+{
```
Comment (alinask) [inline src/uct/base/uct_iface.c:764]: is this function really relevant for all ifaces? i mean, should it be in this file?

File: src/uct/tcp/tcp.h (hunk 4 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp.h]: done

File: src/uct/tcp/tcp_iface.c (hunk 3 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_iface.c]: fixed as proposed by clang code style analyzer

File: src/uct/tcp/tcp_iface.c (hunk 2 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_iface.c]: fixed as proposed by clang code style analyzer

**Comment by dmitrygx** [comment]
@evgeny-leksikov @hoopoepg @brminich could you review pls?

**Review by hoopoepg — APPROVED** [review]

File: src/uct/base/uct_iface.h [hunk 6]
```diff
@@ -25,6 +25,9 @@
 #include <ucs/datastruct/mpool.inl>
 
 
+#define UCT_IFACE_LOCAL_ADDR_FLAG_EXT UCS_BIT(63)
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/base/uct_iface.h:28]: added documentation

File: src/uct/tcp/tcp.h [hunk 7]
```diff
@@ -280,13 +280,35 @@ typedef struct uct_tcp_ep_zcopy_tx {
 } uct_tcp_ep_zcopy_tx_t;
 
 
+/**
+ * TCP iface address flags
+ */
+typedef enum uct_tcp_iface_addr_flags {
+    UCT_TCP_IFACE_ADDR_FLAG_LOCAL = UCS_BIT(0) /* Local address extension is
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp.h:287]: They have different meanings and included in different fields.
Rename this flag to make it more clear, since it indicates whether we have `ext_addr` valid or not.

File: src/uct/tcp/tcp.h [hunk 8]
```diff
@@ -284,10 +284,10 @@ typedef struct uct_tcp_ep_zcopy_tx {
...
  */
 typedef enum uct_tcp_iface_addr_flags {
-    UCT_TCP_IFACE_ADDR_FLAG_LOCAL = UCS_BIT(0) /* Local address extension is
-                                                * included to iface address:
-                                                * uct_iface_ext_local_addr_t for
-                                                * loopback reachability */
+    UCT_TCP_IFACE_ADDR_FLAG_EXT = UCS_BIT(0) /* IFACE address is extended by
+                                              * additional information:
+                                              * uct_iface_ext_local_addr_t for
+                                              * loopback reachability */
```
Comment (evgeny-leksikov) [inline src/uct/tcp/tcp.h:290]: - pls add `@ref  uct_iface_ext_local_addr_t`, this way doxygen CI could help us to keep doc up to date even the type name is changed or removed
 - it's preferable to use doxygen format in docs comments (even for internal code)
 - minor: long comment better place in lines before
```suggestion
    /**
     * IFACE address is extended by additional information:
     * @ref uct_iface_ext_local_addr_t for loopback reachability
     */
    UCT_TCP_IFACE_ADDR_FLAG_EXT = UCS_BIT(0) 
```

Comment (dmitrygx) [reply src/uct/tcp/tcp.h]: thanks
fixed

**Review by evgeny-leksikov — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

**Review by brminich — APPROVED** [review]

File: src/uct/tcp/tcp.h [hunk 9]
```diff
@@ -280,13 +280,36 @@ typedef struct uct_tcp_ep_zcopy_tx {
...
+/**
+ * TCP iface address flags
+ */
+typedef enum uct_tcp_iface_addr_flags {
+    /**
+     * IFACE address is extended by additional information:
+     * @ref uct_iface_ext_local_addr_t for loopback reachability
+     */
+    UCT_TCP_IFACE_ADDR_FLAG_EXT = UCS_BIT(0)
+} uct_tcp_iface_addr_flags_t;
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp.h:292]: the problem here is TCP_SOCKCM which has sockaddr_storage as device address.
so, we should extend TCP_SOCKCM's address too.

[the remark this answers is not in the document]
Comment (yosefe) [reply src/uct/tcp/tcp.h:292]: yes, let's extend it. the flag of looback is the property of the device, not iface. this is also the case for shared memory.

[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp.h:292]: yes, I see

[the remark this answers is not in the document]
Comment (yosefe) [reply src/uct/tcp/tcp.h:292]: BTW, tcp sockcm could pass only (base,flags), without extension (to connect callbacks) the since it should always provide a reachable device

**Comment by dmitrygx** [comment]
the failrue is #6741 
bot:pipe:retest

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by dmitrygx** [comment]
@yosefe could you review pls?
failures were unrelated

**Review by yosefe — COMMENTED** [review]
pls check clang format result and test on dockers

File: src/uct/tcp/tcp_ep.c [hunk 10]
```diff
@@ -696,17 +696,27 @@ static ucs_status_t uct_tcp_ep_connect(uct_tcp_ep_t *ep)
...
+    dest_addr->sin_family = tcp_dev_addr->sa_family;
+    dest_addr->sin_port   = port;
+
+    /* To silence Coverity warning */
+    ucs_assert(dest_addr->sin_family == AF_INET);
+    ucs_sockaddr_set_inet_addr((struct sockaddr*)dest_addr,
+                               (tcp_dev_addr->flags &
+                                        UCT_TCP_DEVICE_ADDR_FLAG_EXT) ?
+                               &loopback_addr :
+                               (const struct in_addr*)(tcp_dev_addr + 1));
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: done

File: src/uct/tcp/tcp_iface.c [hunk 11]
```diff
@@ -113,33 +113,85 @@ static UCS_CLASS_DEFINE_DELETE_FUNC(uct_tcp_iface_t, uct_iface_t);
...
+    const void *in_addr;
+    size_t ip_addr_len;
+    ucs_status_t status;
+
+    dev_addr->flags     = 0;
+    dev_addr->sa_family = iface->config.ifaddr.sin_family;
+
+    if (ucs_sockaddr_is_inaddr_loopback(saddr)) {
+        dev_addr->flags |= UCT_TCP_DEVICE_ADDR_FLAG_EXT;
+        uct_iface_get_local_address((uct_iface_ext_local_addr_t*)pack_ptr);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_iface.c]: removed

File: src/uct/tcp/tcp_iface.c [hunk 12]
```diff
@@ -113,33 +113,85 @@ static UCS_CLASS_DEFINE_DELETE_FUNC(uct_tcp_iface_t, uct_iface_t);
...
+    } else {
+        in_addr = ucs_sockaddr_get_inet_addr(saddr);
+        status  = ucs_sockaddr_inet_addr_sizeof(saddr, &ip_addr_len);
+        if (status != UCS_OK) {
+        }
+
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_iface.c]: forgot to add handler
fixed

File: src/uct/tcp/tcp_sockcm_ep.c [hunk 13]
```diff
@@ -545,42 +546,61 @@ ucs_status_t uct_tcp_sockcm_ep_send(uct_tcp_sockcm_ep_t *cep)
...
+           in_addr_len);
+
     remote_data.field_mask            = UCT_CM_REMOTE_DATA_FIELD_DEV_ADDR        |
                                         UCT_CM_REMOTE_DATA_FIELD_DEV_ADDR_LENGTH |
                                         UCT_CM_REMOTE_DATA_FIELD_CONN_PRIV_DATA  |
                                         UCT_CM_REMOTE_DATA_FIELD_CONN_PRIV_DATA_LENGTH;
-    remote_data.dev_addr              = (uct_device_addr_t *)&remote_dev_addr;
-    remote_data.dev_addr_length       = remote_dev_addr_len;
+    remote_data.dev_addr              = (uct_device_addr_t*)remote_dev_addr;
+    remote_data.dev_addr_length       = sizeof(remote_dev_addr) + in_addr_len;
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_sockcm_ep.c]: yes, in TCP SOCKCM.
no need to pack system ns information. they are 100% reachable, since `ucs_socket_getpeername()` completed with success.
we just always pack in_addr of loopback.

File: src/uct/tcp/tcp_sockcm_ep.c [hunk 14]
```diff
@@ -609,27 +629,46 @@ static ucs_status_t uct_tcp_sockcm_ep_server_invoke_conn_req_cb(uct_tcp_sockcm_e
...
+    }
+
+    remote_dev_addr = ucs_alloca(sizeof(*remote_dev_addr) + in_addr_len);
+    in_addr_ptr     = (void*)(remote_dev_addr + 1);
+
+    remote_dev_addr->flags     = 0u;
+    remote_dev_addr->sa_family = saddr.ss_family;
+    memcpy(in_addr_ptr, ucs_sockaddr_get_inet_addr((struct sockaddr*)&saddr),
+           in_addr_len);
+
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_sockcm_ep.c]: yes, reduced code duplication

File: src/uct/tcp/tcp_ep.c (hunk 10 above)
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: unfortunately, it leads to the Coverity false-positive error.
roll back this change

**Comment by dmitrygx** [comment]
@yosefe @brminich could you review pls?

File: src/ucs/sys/sock.c [hunk 15]
```diff
@@ -639,14 +639,16 @@ const void *ucs_sockaddr_get_inet_addr(const struct sockaddr *addr)
 }
 
 ucs_status_t ucs_sockaddr_set_inet_addr(struct sockaddr *addr,
-                                        const void *in_addr)
+                                        const void *in_addr, size_t in_addr_len)
```
Comment (yosefe) [inline src/ucs/sys/sock.c:642]: pls remove in_addr_len parameter

File: src/uct/base/uct_iface.c [hunk 16]
```diff
@@ -733,52 +733,41 @@ uct_ep_keepalive_check(uct_ep_h tl_ep, uct_keepalive_info_t *ka, unsigned flags,
...
-    return ucs_machine_guid();
-}
-
-void UCS_F_NOOPTIMIZE /* GCC failed to compile it in release mode */
-uct_iface_get_local_address(uct_iface_ext_local_addr_t *ext_addr)
-{
-    ext_addr->super.id = uct_iface_get_system_id() &
-                         ~UCT_IFACE_LOCAL_ADDR_FLAG_EXT;
+    ucs_assert((sys_ns_type == UCS_SYS_NS_TYPE_IPC) ||
+               (sys_ns_type == UCS_SYS_NS_TYPE_NET));
```
Comment (yosefe) [inline src/uct/base/uct_iface.c:743]: why needed?

File: src/uct/tcp/tcp_ep.c [hunk 17]
```diff
@@ -703,20 +703,23 @@ void uct_tcp_ep_set_dest_addr(const uct_device_addr_t *dev_addr, in_port_t port,
...
 
     /* TODO: handle AF_INET6 */
     dest_addr->sin_family = tcp_dev_addr->sa_family;
     dest_addr->sin_port   = port;
 
-    /* To silence Coverity warning */
+    if (tcp_dev_addr->flags & UCT_TCP_DEVICE_ADDR_FLAG_LOOPBACK) {
+        in_addr = &loopback_addr;
+    } else {
+        in_addr = (const struct in_addr*)(tcp_dev_addr + 1);
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c:717]: minor: no need to cast

File: src/uct/tcp/tcp_sockcm_ep.c [hunk 18]
```diff
@@ -546,56 +546,86 @@ ucs_status_t uct_tcp_sockcm_ep_send(uct_tcp_sockcm_ep_t *cep)
     return uct_tcp_sockcm_ep_progress_send(cep);
 }
 
+static ucs_status_t
+uct_tcp_sockcm_ep_get_remote_device_addr(const uct_tcp_sockcm_ep_t *cep,
+                                         struct sockaddr_storage *saddr,
+                                         socklen_t *saddr_len_p,
+                                         uct_tcp_device_addr_t **
+                                                 remote_dev_addr_p,
+                                         size_t *remote_dev_addr_len_p)
```
Comment (yosefe) [inline src/uct/tcp/tcp_sockcm_ep.c:555]: maybe caller can pass (large onstack) buffer and max size; this function will fill it and return ssize_t

File: src/uct/tcp/tcp_sockcm_ep.c [hunk 19]
```diff
@@ -546,56 +546,86 @@ ucs_status_t uct_tcp_sockcm_ep_send(uct_tcp_sockcm_ep_t *cep)
...
+    remote_dev_addr        = ucs_malloc(*remote_dev_addr_len_p,
+                                        "remote device address");
+    if (remote_dev_addr == NULL) {
+        return UCS_ERR_NO_MEMORY;
+    }
+
+    remote_dev_addr->flags     = 0u;
+    remote_dev_addr->sa_family = saddr->ss_family;
+
+    in_addr_ptr = (void*)(remote_dev_addr + 1);
```
Comment (yosefe) [inline src/uct/tcp/tcp_sockcm_ep.c:585]: no need cast

File: src/uct/tcp/tcp_sockcm_ep.c [hunk 20]
```diff
@@ -546,56 +546,86 @@ ucs_status_t uct_tcp_sockcm_ep_send(uct_tcp_sockcm_ep_t *cep)
...
+    memcpy(in_addr_ptr, ucs_sockaddr_get_inet_addr((struct sockaddr*)saddr),
+           in_addr_len);
+
+    *remote_dev_addr_p = remote_dev_addr;
+
```
Comment (yosefe) [inline src/uct/tcp/tcp_sockcm_ep.c:590]: minor:remove space

File: src/uct/tcp/tcp_sockcm_ep.c (hunk 18 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_sockcm_ep.c]: done

File: src/uct/tcp/tcp_sockcm_ep.c (hunk 19 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_sockcm_ep.c]: done

File: src/uct/tcp/tcp_sockcm_ep.c (hunk 20 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_sockcm_ep.c]: no need anymore

File: src/uct/tcp/tcp_sockcm_ep.c [hunk 21]
```diff
@@ -572,33 +571,29 @@ uct_tcp_sockcm_ep_get_remote_device_addr(const uct_tcp_sockcm_ep_t *cep,
...
+    remote_dev_addr_len = sizeof(*remote_dev_addr) + in_addr_len;
+    if (remote_dev_addr_len < max_remote_dev_addr_len) {
+        return UCS_ERR_BUFFER_TOO_SMALL;
     }
 
     remote_dev_addr->flags     = 0u;
     remote_dev_addr->sa_family = saddr->ss_family;
 
-    in_addr_ptr = (void*)(remote_dev_addr + 1);
+    in_addr_ptr = remote_dev_addr + 1;
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_sockcm_ep.c]: removed

File: src/uct/tcp/tcp_sockcm_ep.c [hunk 22]
```diff
@@ -572,33 +571,29 @@ uct_tcp_sockcm_ep_get_remote_device_addr(const uct_tcp_sockcm_ep_t *cep,
...
 {
-    uct_tcp_sockcm_priv_data_hdr_t *hdr = (uct_tcp_sockcm_priv_data_hdr_t*)
-                                                  cep->comm_ctx.buf;
-    struct sockaddr_storage saddr       = {0};
-    uct_tcp_device_addr_t *remote_dev_addr;
-    size_t remote_dev_addr_len;
+    uct_tcp_sockcm_priv_data_hdr_t *hdr    = (uct_tcp_sockcm_priv_data_hdr_t*)
+                                                     cep->comm_ctx.buf;
+    struct sockaddr_storage saddr          = {0};
+    ssize_t remote_dev_addr_len            = 32;
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_sockcm_ep.c]: done

File: src/uct/tcp/tcp_sockcm_ep.c [hunk 23]
```diff
@@ -655,28 +649,25 @@ uct_tcp_sockcm_ep_server_invoke_conn_req_cb(uct_tcp_sockcm_ep_t *cep)
...
+    uct_tcp_device_addr_t *remote_dev_addr = ucs_alloca(remote_dev_addr_len);
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply src/uct/tcp/tcp_sockcm_ep.c]: done

File: test/gtest/ucs/test_sock.cc [hunk 24]
```diff
@@ -267,15 +266,14 @@ UCS_TEST_F(test_socket, sockaddr_set_inet_addr) {
         scoped_log_handler log_handler(socket_error_handler);
 
         EXPECT_EQ(UCS_ERR_INVALID_PARAM,
-                  ucs_sockaddr_set_inet_addr((struct sockaddr*)&sa_un, NULL,
-                                             0));
+                  ucs_sockaddr_set_inet_addr((struct sockaddr*)&sa_un, NULL));
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/ucs/test_sock.cc:269]: yes, we don't dereference it there, since it is `AF_UNIX`, i.e. wrong address famility

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe could you review the last commit pls? it fixes Coverity without suppressing. Unfortunately, I don't find the correct way to suppress Coverity error in `ucs_sockaddr_set_inet_addr()`.

**Review by yosefe — APPROVED** [review]

**Comment by yosefe** [comment]
IMO it's even better to pass iface_addr than just port_num

**Comment by dmitrygx** [comment]
> IMO it's even better to pass iface_addr than just port_num

yep, I think so

**Comment by dmitrygx** [comment]
@yosefe could you review pls the second commit?
it fixes coverity for test (Coverity-devel)

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe ok to merge?

**Review by brminich — APPROVED** [review]
