### PR TITLE
UCT/TCP, UCS/SYS: Repeat connection establishment when a connection was dropped

### LINKED ISSUE #4237: tcp_ep.c:555  UCX  ERROR try to increase "net.core.somaxconn", "net.core.netdev_max_backlog", "net.ipv4.tcp_max_syn_backlog" to the maximum value on the remote node
output: http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12459/label=hpc-arm-hwi-jenkins,worker=3/console
```
14:08:26 [----------] 2 tests from ud/test_ucp_stream_many2one
14:08:26 [ RUN      ] ud/test_ucp_stream_many2one.send_recv_nb_iov/0
14:08:27 [       OK ] ud/test_ucp_stream_many2one.send_recv_nb_iov/0 (448 ms)
14:08:27 [ RUN      ] ud/test_ucp_stream_many2one.send_worker_poll/0
14:08:27 [       OK ] ud/test_ucp_stream_many2one.send_worker_poll/0 (451 ms)
14:08:27 [----------] 2 tests from ud/test_ucp_stream_many2one (900 ms total)
14:08:27 
14:08:27 [----------] 1 test from tcp/test_uct_ep
14:08:27 [ RUN      ] tcp/test_uct_ep.disconnect_after_send/0
**14:08:30 [1569582510.434017] [hpc-arm-hwi-jenkins:44977:0]         tcp_ep.c:555  UCX  ERROR try to increase "net.core.somaxconn", "net.core.netdev_max_backlog", "net.ipv4.tcp_max_syn_backlog" to the maximum value on the remote node**
14:08:30 [1569582510.434088] [hpc-arm-hwi-jenkins:44977:0]           sock.c:230  UCX  ERROR recv(fd=10) failed: Connection reset by peer
14:23:27 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/contrib/../test/gtest/common/test_helpers.cc:49: Failure
14:23:27 Failed
14:23:27 Connection timed out - abort testing
14:23:27 [hpc-arm-hwi-jenkins:44977:0:44977] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
14:23:27 ==== backtrace ====
14:23:27     0  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/src/ucs/.libs/libucs.so.0(+0x23350) [0xffffb7f33350]
14:23:27     1  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/src/ucs/.libs/libucs.so.0(+0x226e8) [0xffffb7f326e8]
14:23:27     2  [0xffffb7fc06c0]
14:23:27     3  /usr/lib64/libc.so.6(epoll_pwait+0x90) [0xffffb76eb80c]
14:23:27     4  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/src/ucs/.libs/libucs.so.0(ucs_event_set_wait+0x5c) [0xffffb7f3b660]
14:23:27     5  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/src/uct/.libs/libuct.so.0(uct_tcp_iface_progress+0x84) [0xffffb7edab70]
14:23:27     6  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x619e00]
14:23:27     7  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x6083b0]
14:23:27     8  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x564f48]
14:23:27     9  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x54ba9c]
14:23:27    10  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x5491e8]
14:23:27    11  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x548ef4]
14:23:27    12  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x548c40]
14:23:27    13  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x538ae8]
14:23:27    14  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x54c90c]
14:23:27    15  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x5385e4]
14:23:27    16  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x554b2c]
14:23:27    17  /usr/lib64/libc.so.6(__libc_start_main+0xf0) [0xffffb7630d64]
14:23:27    18  /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-arm-hwi-jenkins/worker/3/build-test/test/gtest/gtest() [0x525e2c]
14:23:27 ===================
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Repeat connection establishment, when a connection was dropped by a remote peer due to lack of resources (accept queue, inability to handle connection request, etc)

## Why ?

Fixes #4237

## How ?

1. Close old client socket on which failure was detected
2. Move connection to `CLOSED` state
2. Create a new client socket and call `connect()`

if an error occurred, report to a user possible solution on how to solve it setting new system limits

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12698/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 7 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 28-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/df3e7a7f1d9cf3ae39a4414fa13f1b2e0b92f6ea/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/3c3846ab15a5ce10afd80e340a6dbb0b2f141e7d/hpc-arm-cavium-jenkins_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/3adace4e1f5162eac7509681900f93e6f0870768/hpc-arm-cavium-jenkins_W3) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/fd95c83ce2a159c11f223465ac928ac7b9eda907/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/522050819c28c6cd153cd50bf35de95fed05c57a/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/c9d8635adad4e399a238fc25e3ee5f804fa0e7d0/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/dc9401218ba4f31fd367484d6a8f9e18c148003f/hpc-test-node-new_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/8eae0ceeaeb4585260440364433ea541f71ebe96/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/e3fb92a38bb085bdfb065cd00c83239bf9b35e84/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/193f6cd30a84eb2c3a1b89b2791f9d26011ce00f/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/fadd3cf12504d07a330bf92bde9bd78ebcc60d2c/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/700a2dbfe44b46dd1c1d61f85d9edd5689f8c9ec/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/181db8debe87ac9aaafe2f37bd1ab162e5326ea3/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/11661b74c4946a3c4d906fe80739ecfb2e0a03ac/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/b15a18b312e7de1658419f191a0662da159280c5/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/ba65b5b1d0252ccf3c1ec705037c81dc8638b9ea/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/5c41b9595ec7297a3ca637d3b0a25be1a407769b/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/0e0d621d0fd095d3d143d7c6e32a9bd463cb7089/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/5f7a1a402e89e28ee6ba5edb7c394cb94f208911/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/cf35a28817820df23ae3245564aea678ceabfd06/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/6374bbe187caf5ab9efadd9112f76f83e6d030b3/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/743a864ade460277ba0303ce1b3335d536423a1f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/f388b690c95158d0d1d060de4039fa15a9763218/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/3f417512ea0b58d2b91cd04b642806c368db89fe/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/8b2ec23c780170a8d58f8cdc223641b38256140b/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/40022a9ee1550eb37e016f727bbad9dd2f01e3d9/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/9d4d354532a7a575d4e176084fef48a888132942/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/4911edbf6d6e86c727e177e378bfa446ec15f22d/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4bd5276fa7de3b259235540a4bedd4c4/raw/559b433c4d7c66a5c3f83fad1e5dc0be0972b204/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12721/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 17 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 29-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/35102f95f835a87a1bf54cc6e2f29b8b3984cfc6/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/4e41b6c537c9391d39d556421c0ba3ab2fe336d8/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/8894bc385471ba322f0a0f6643ff300f9d5c1979/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/2e4904f7d8fd4f27493433dc94c63a55260ec9ab/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/16afad40ac420416998245139f9880da29aeab83/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/16ee73eaba8dc6a9319bdd9b2465451dee7dab6c/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/9660d17a22ad79091392c1eacbebc1e9647e8bbc/hpc-test-node-gpu_W2) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/c237fd36a1ed160ad2d72c99f2c8f5947a827052/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/e198fa90d508a01c0e8cd67d213b2b871529e11a/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/a321c62e9d7603936437e908b1356de3d5583c89/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/3b044be9479c0537a6f0eb2a3529955236e84b3a/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/a735149d3cd62907189116c9bdab1736e8517368/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/1b814b42f983c0db5d1aca990f57eec5bddd16c4/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/944dd5dd5873d975585591c04521ca512c8fa782/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/4cc5cc963d6e692d38acce35dd6c263cb3ebd7d8/hpc-test-node-new_W2) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/699f5430c30995f2014a3571f97a616544b943c4/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/256bb203f7eb265cc3eb63dae6620dce83bbf246/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/6d95e6c4c497791abad46c0841cb3265205512cb/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/a4794652ea2f1d6b2945608c70042e182c44fb8c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/e622c7e11fcb26482de835f1c259686e6ab3cdb8/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/24a548a65774292d7afc3ec297b0ae58d7ee7c32/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/74bdf2b9b71fa86e47be53fae9732c452516eebf/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/db607868ada0bf94e098e0a74213f2d97c675bb9/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/7e07171dc192925963795bd980a1efb05c660258/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/b08c46cb50ee20dde2ca43895f4bcd943132da6d/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/a50c4fe748294d1400c025d8e61a4c317f7a0105/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/9f19946f5f7ea207476c788d2fbf0d83ae62a492/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/44ea5cbffc0b2b47db62a581c20d64fb7e2ee9d6/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/56650d4b6c8ec5ddd714be50293a228a/raw/785d8fed636c3ad3de65738c82b908e0dd251212/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12723/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 14 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/867a5eef08d2f05859f815286158e9d3629ab5e9/_main) | :x: FAILURE
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/8ba8fe61e0e26fac2d70dea43fa1b09c38d2a585/hpc-arm-cavium-jenkins_W1) | :x: FAILURE
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/2e495bbacb76384bd3f200ad0bb480a08f6e3939/hpc-arm-hwi-jenkins_W1) | :x: FAILURE
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/a6c4e8212ff4672c93e208fe08f7d90ec21e37ca/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/2ffa61a9a7d73e6e1202f1bed98ab2412614a5f4/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/f9f6cc6caf020f0b797ac74d085886823b3abd1a/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/884615d53a7ee21a04e238c36d05d742168b50e8/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/812f4938a60ed296090cfe0693963ef0eb476dc1/hpc-test-node-legacy_W0) | :x: FAILURE
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/88343f22f4bba05895270bfea0d1862a9ae9ea86/hpc-test-node-legacy_W1) | :x: FAILURE
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/7ed5472cbc565989b214846d3decd0b3f67f060e/hpc-test-node-legacy_W3) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/6fd5b7da591c753033406aa62cad9e5ce04ada8a/hpc-test-node-new_W0) | :x: FAILURE
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/de7bc39db65970dfaf35a8d9a27c5564635b2439/hpc-test-node-new_W1) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/532abe251e78ca48bd9f2a927b0f49f231164413/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/d8595451f025e099d30c133d89202c89b88862b5/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/24fa9a6d9344de453e2796dc8d444a450981a563/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/f10475f46dd228b009b1599e9443abad6f791fd3/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/e65969637d8d5df8e93bba43995998801c4faa58/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/d644086017bb442d2c25695bde47a7486abb6378/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/abcbbe1cdf08762b8d6c0c6adb394d6723b44c32/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/ff825646abbb48225d0f1d65cf985a6c9588dba0/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/58715bfe0d3bfa6494d9ae37f6f83e570409d249/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/26fcf80cced6ed0bbbb3a3217edfd25a0a4ce240/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/3638f50cfb49a4ccfc7fd0a0299cdc226ca0331b/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/2c487281c8a451bab35354022e824fba2f602b36/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/2560e7990b0a010a2f5828eb16da3269bd40f660/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/e69e94d131837606542e510ce2a9bab7de26a978/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/ddca98ea9945ac3ccdf2885444cdf6c0e9167d02/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/d3efd88eca6d5d3689c4d656cbde33559f5776fa/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9ca6ec604eb9bc7b9641542468832d0c/raw/96e069ad1616f504d9572f0a421f9add6e12514b/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12730/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 6 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/f66842a20ad3f2e9b943b0190ba92ab4fed42f45/_main) | :question: ABORTED
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/e960039c2b14ede2b51240559a20679dbd2a426d/hpc-arm-cavium-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/69ee2632ec422b30eb30181f3fc86a1a9d3e5bff/hpc-arm-hwi-jenkins_W0) | :question: ABORTED
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/fefbd97778d70e92ef2f6f1e548bbf05aadcaf4d/hpc-arm-hwi-jenkins_W1) | :question: ABORTED
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/d797962505315554819ce55109e6caf401ea408f/hpc-arm-hwi-jenkins_W2) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/9c793db212c741c7d191c38c1936e16a5e45da81/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/61abe59a4836abae07fb99bc0acaf352a14e7d51/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/133b38bac63ebfbcd4e5f6b35c77a9be3c7769ad/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/371e51408d7779ed0f4415fa88967e09d6c01e78/hpc-test-node-legacy_W2) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/3146f32fd8091e4c963051f05a00a9c4ac5fd0ec/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/3366d56ea9ac24b8a01328a8e14aa84f444aab14/hpc-test-node-new_W0) | :question: ABORTED
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/c4e47745779c7eaf51b3ded444e22b768f59f3c2/hpc-test-node-new_W1) | :question: ABORTED
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/ab51a1cb9be5fc51ed97a17f9a76fd0f8bdfcd98/hpc-test-node-new_W2) | :question: ABORTED
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/f0311cb05688a9bfd1a05238f72fac1544833fc3/hpc-test-althca_W1) | :x: FAILURE
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/a63e26d2e72c7b7b45a0efd75fda02bcc5b94e2e/hpc-test-node-gpu_W0) | :x: FAILURE
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/9a78eb8af5435a78e51759723f804746b79c1318/hpc-test-node-gpu_W1) | :x: FAILURE
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/356d92c4afba6310dd2fbdcbcd7d06265e8909c6/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/1cbbd0caea0ef83daa461e648e6284d451b3032d/hpc-test-node-new_W3) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/7eb8b01bf629555cd3d9005dda8828fa31cb9434/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/fe17d88d327fd6e8c54fcc89bc824b6851186b1a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/46ccc998d153ed9422bd191d34821b176c0dde50/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/b7c792732f6a9f10502b8b4d9dc53c9b3a626a98/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/b856c8fd416fcdd914a365eb82691938d03ab58c/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/7b0ee9c472964588810a5156133078ab5d8bc76d/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/67e982d5182991d6b1030c76bc1d42729b2a19af/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/eecaa4d5b144823a0aade43d8ffd875f2c066456/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/8307fd3b6bac66ae1d085f9a8679dced96d15bb4/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/68774b160e65e4b218119cd8ffccf710109b430b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9685b39e476e096d154d09bfe243c92f/raw/f5663d5dc5052e8642763dcc66c406143d088cbc/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12746/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>ABORTED</b> on 1 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/5a084b20b1420f55e000cf2c59a4691f/raw/5a76cd3df98a17ec6252c592795991cf5994bd7a/_main) | :question: ABORTED

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12747/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 3 of 18 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/e099d6eff8566135e9bb5ff2a8ba4ac76140e724/_main) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/bcbd965788dcc5bee53077311ec756385ad52c9b/hpc-test-node-gpu_W3) | :question: ABORTED
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/aa5f9e24bcf5e33b00a3ab05c30cbe7dfc53c2ae/r-vmb-ppc-jenkins_W0) | :x: FAILURE
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/67e74f9b7b291dfb38182e7dcc4d15d30b85c6c2/r-vmb-ppc-jenkins_W1) | :x: FAILURE
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/8be611b0a0b5015e17e3621a82e8dbb284980897/r-vmb-ppc-jenkins_W2) | :x: FAILURE
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/628e95918d7eb260134bb5f49bb45290f0588311/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/9950c8b85fcf3eab62beaee3d7aa95966632866e/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/1881607cfa85e4079cfa5067df456b7b40b7df47/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/e1cafb21e469617b267221b01aa2fbd63023f12e/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/151e41665a20c3a9bd0a84339716f57095aa5bfd/hpc-arm-cavium-jenkins_W0) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/bb33e889a391f90e90258faea49c781bae0495c9/hpc-arm-cavium-jenkins_W1) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/657376b793737500181bd63f3f2d92a485ba5804/hpc-arm-cavium-jenkins_W2) | :question: UNKNOWN
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/b2e9a3210f47bdaa3b54c6a5a7c7016fe6cf21ea/hpc-arm-cavium-jenkins_W3) | :question: UNKNOWN
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/e7796d19ee93d8c4a2dc323216598172bbdb95c5/hpc-arm-hwi-jenkins_W3) | :question: UNKNOWN
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/900e19c0ea127410a394a8e2e5890ad50c51e720/hpc-test-node-gpu_W0) | :question: UNKNOWN
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/a891211b92dd7ad5efb079fbdf8f74f8db0d46dc/hpc-test-node-gpu_W1) | :question: UNKNOWN
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/82f015f029f90c18c60195a877a25b9a9823bd96/hpc-test-node-gpu_W2) | :question: UNKNOWN
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/772affaa80e9ee78762aa9db3dfc3d18/raw/9475aa7ed8ce10ee2cc5bec125bba764fd2fc79b/r-vmb-ppc-jenkins_W3) | :question: UNKNOWN

**Comment by dmitrygx** [comment]
rnat
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12755/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 30-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/2f649952d99397eb8623009666394142a61d329d/_main) | :x: FAILURE
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/e80fd2d1f048dfa7261f108cdd7b8cb50eeb6c81/hpc-test-node-new_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/eea94dca7a8f4994f393f4c069abd40fc468c0a5/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/4c1797e341690c95e8e130496844d6d949dd8fa6/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/32614ad5b477937b8f12daa11f350fad7b5eed69/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/22548b3eab0aee364a7b74ac2219d7c84b9238b1/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/1d1aa42825fd98fff2e6898d81a93384012bd9e7/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/d0edd0db5ca29604bd5d122bccb48ef0bedf4a97/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/df82442adb698eab4544c6cbd23033409f1e63c2/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/6464577cd0ae9da3343d159bfc2b775b82737966/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/f3a3871d589165b595ba03c2abe7b865d4a4d334/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/86fec0f3351e9c4864ef6b8b0e3d2dba4505d4d5/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/528e3bf9308f8b891b666620863f0b66d2584667/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/a8f2d91fc244b7370ae5dae84979aaa55d8c8551/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/05c590074b467eef39036897f72a764be17e4830/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/ef654853f02c8cab68f789fef5869824e07793a6/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/8cfd6adbb709c958310ef9eec0b9c9ba10078add/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/ddd5fc23bbe123e1a697cf48efbe4a8158fa3e48/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/cda364d971acdd120a6a38bd206bf3e5b145fe51/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/16661a96ff35c74b133a3c5bef510a13f985bfc7/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/4ac018c0cb7178e7e59cf7aef2d56f6463e9c19f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/f38423e82907794f358d26a75dc2620fb08f35c2/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/60df651287df5f5a3fb859d7946b2f90b9e48a60/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/c3e8ab27d3c19501b5d0275b80c06580d9adcb17/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/2b85d875be44e9fbf962421ad0a4ffb8bf4e8946/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/68dd2c7cc68d188867f8e06e09fc081fe202b5f3/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/c5c0cec0a31c5e35a1df87b7d4b62a8b49ccf8c9/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/e0b0fbe4ca569afd8be1f55a4abfeeef0c333ded/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/c304b1c360f2f8783052008de437f791/raw/503ad54aaf979e3f72b2557176b6c6f93e86078d/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12765/ for details (Mellanox internal link).

**Comment by dmitrygx** [comment]
> Test FAILed.
> See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12765/ for details (Mellanox internal link).

#4329
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12777/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 31-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/b22d35ffb14585b20af3b8dc7a0597fd99230b9d/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/4407cda1c9e66ba38dcb33556fd60c69750bc66d/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/0652ffe7aa5f8e205b948972467e2fc5921f8f57/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/1bf87da252f5e0c4af5068dbb32d6eab2a5edd09/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/44c3ffba3f99c939dee7a95cc89fc7a4ce9b7d0c/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/2c3cce6fc12fb1d813a77d4e5cff5968dd6903ab/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/b73869df48a5c563abb31b0ab0550f6a79492c46/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/997b8cf9da28d01eb97943a9813d51ec1f050a93/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/60ad1d2780881eb2a77131034240cfba1413073a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/13cf35051cbd787210ef2ec790b27bb845bca14c/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/2cafe6ee5cbccd01744e110b781665459a94ea07/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/d9ce42e4b556356911e45065af94d3e7f1299496/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/b29cadb4829b4f1a6a466fecda6a2cabbdb6abdb/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/75f63287d2eb762758a15f9e1b136a0df090ff1b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/4fe4df1158d6c4c24216661182335c599ab4e3b5/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/5b30935142782db1ea790ecbcf3efaa1d6c505fc/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/58e3cc253cb30f81fce6faa9473d9854d1408303/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/c7c7360a492dba80cd8d61bc2d9d57a71244c6dc/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/37719958e18692c1ea529953f5fb91b162235b33/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/6937e32c90ca76b4663763f8f08004b9e19e96be/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/2d7140f26b03f19b437e79042141255a386f61bc/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/69a9c8ec8512c4ac5a2c55c04d2c517b8ff78b19/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/f97136db0fa432cda93f4716f2b422f2b7ab37d6/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/888abcd59e7ebed5962b6689a3422ead914b32d9/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/772ae5155501cc065bad28327a79c39d1e87f58a/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/d5a740f7e1afb77b3b9516e1cb07db2ccf789a75/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/163f69ae43a5d379cd5995ca5d28d316ff2085a4/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/070d8ef89f33883c7c6894deb19d5b77762babaa/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/69e3afcbf7b03382adc834edb44baa9c/raw/9fe68c626d8e11a67f6324637af872aafcbc6d51/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@yosefe the PR has been updated to do `5` (by default) retries for a connection establishment
could you review pls?

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

File: src/uct/tcp/tcp_ep.c [hunk 1]
```diff
@@ -347,42 +348,74 @@ void uct_tcp_ep_set_failed(uct_tcp_ep_t *ep)
...
 
     status = uct_tcp_cm_conn_start(ep);
     if (status != UCS_OK) {
         goto err_ep_destroy;
     }
 
-    status = uct_tcp_ep_add_ctx_cap(ep, UCT_TCP_EP_CTX_TYPE_TX);
+    *ep_p = ep;
+
+    return UCS_OK;
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c]: seems like it's not needed in case line 377 is done?

File: src/uct/tcp/tcp.h [hunk 2]
```diff
@@ -372,7 +381,7 @@ void uct_tcp_iface_add_ep(uct_tcp_ep_t *ep);
 
 void uct_tcp_iface_remove_ep(uct_tcp_ep_t *ep);
 
-void uct_tcp_ep_dropped_connect_print_error(uct_tcp_ep_t *ep, int io_errno);
+ucs_status_t uct_tcp_ep_handle_dropped_connect_error(uct_tcp_ep_t *ep, int io_errno);
```
Comment (yosefe) [inline src/uct/tcp/tcp.h]: uct_tcp_ep_handle_dropped_connect

File: src/uct/tcp/tcp_ep.c [hunk 3]
```diff
@@ -591,21 +624,41 @@ static inline ssize_t uct_tcp_ep_sendv(uct_tcp_ep_t *ep)
...
+        uct_tcp_ep_close_fd(&ep->fd);
+
+        uct_tcp_cm_change_conn_state(ep, UCT_TCP_EP_CONN_STATE_CLOSED);
+
+        status = uct_tcp_ep_create_socket_and_connect(iface, NULL, &ep);
+        if (status != UCS_OK) {
+            ucs_error("try to increase \"net.core.somaxconn\", "
+                      "\"net.core.netdev_max_backlog\", "
+                      "\"net.ipv4.tcp_max_syn_backlog\" to the maximum value "
+                      "on the remote node or increase %s%s%s=%u to do more "
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c]: "on the remote node or increase %s%s%s (=%u)"

File: src/uct/tcp/tcp_ep.c [hunk 4]
```diff
@@ -591,21 +624,41 @@ static inline ssize_t uct_tcp_ep_sendv(uct_tcp_ep_t *ep)
...
+                      "more connection establishment attempts",
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c]: can remove this line - error message is already too long

File: src/uct/tcp/tcp_iface.c [hunk 5]
```diff
@@ -46,14 +46,19 @@ static ucs_config_field_t uct_tcp_iface_config_table[] = {
...
-   "Enables non-blocking connection establishment. It may improve startup "
+   "Enable non-blocking connection establishment. It may improve startup "
    "time, but can lead to connection resets due to high load on TCP/IP stack",
    ucs_offsetof(uct_tcp_iface_config_t, conn_nb), UCS_CONFIG_TYPE_BOOL},
 
   {"MAX_POLL", UCS_PP_MAKE_STRING(UCT_TCP_MAX_EVENTS),
    "Number of times to poll on a ready socket. 0 - no polling, -1 - until drained",
    ucs_offsetof(uct_tcp_iface_config_t, max_poll), UCS_CONFIG_TYPE_UINT},
 
+  {UCT_TCP_CONFIG_MAX_CONN_ATTEMPTS, "5",
```
Comment (yosefe) [inline src/uct/tcp/tcp_iface.c]: consider using the word "retries" instead of "attempts" all over, i think it's more standard terminology for networking

File: src/uct/tcp/tcp.h [hunk 6]
```diff
@@ -270,6 +274,7 @@ struct uct_tcp_ep {
     uint8_t                       ctx_caps;         /* Which contexts are supported */
     int                           fd;               /* Socket file descriptor */
     uct_tcp_ep_conn_state_t       conn_state;       /* State of connection with peer */
+    unsigned                      conn_attempts;    /* Number of connection attempts done */
```
Comment (yosefe) [inline src/uct/tcp/tcp.h]: maybe move 'conn_state' after the field 'ctx_caps' will reduce structure size

Comment (dmitrygx) [reply src/uct/tcp/tcp.h]: unfortunately, it doesn't help

File: src/uct/tcp/tcp.h (hunk 2 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp.h]: done

File: src/uct/tcp/tcp_ep.c (hunk 3 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: fixed

File: src/uct/tcp/tcp_ep.c (hunk 4 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: done

File: src/uct/tcp/tcp_iface.c (hunk 5 above)
Comment (dmitrygx) [reply src/uct/tcp/tcp_iface.c]: done

File: src/uct/tcp/tcp_ep.c [hunk 7]
```diff
@@ -383,7 +383,9 @@ uct_tcp_ep_create_socket_and_connect(uct_tcp_iface_t *iface,
         goto err_ep_destroy;
     }
 
-    *ep_p = ep;
+    if (*ep_p == NULL) {
```
Comment (yosefe) [inline src/uct/tcp/tcp_ep.c]: move this to line 374?

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: it wouldn't work, since we have check below (line 393) that it's not external EP (i.e. allocated here) and we should destroy it

Comment (dmitrygx) [reply src/uct/tcp/tcp_ep.c]: @yosefe is it ok?

Comment (yosefe) [reply src/uct/tcp/tcp_ep.c]: ok

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12875/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 1 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 05-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/127e80800841c1d394878314325cfaad726fa661/_main) | :question: ABORTED
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/d10704dfe98deac372269786bc850e4080ac6314/hpc-arm-hwi-jenkins_W3) | :question: ABORTED
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/b26218e04f0bd21b2e1cb37c803f9ccbda00e740/hpc-test-node-legacy_W0) | :question: ABORTED
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/82c49e7aa3266f4ed268ae7cc754af4058296b8d/hpc-test-node-legacy_W1) | :question: ABORTED
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/a36639c20ed7b6e410082590f5f7648062e541be/hpc-test-node-legacy_W3) | :question: ABORTED
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/88bfb39cf1df1ebb385b5eb0dfbd3416f110342b/hpc-test-node-gpu_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/a17b2ce92ae2cca74843bd1a977f255640999948/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/6a70fc9b14d4a201252368eb54bf7fdfc6267b22/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/fa0fe83e0933ad1fe9040b77fbf37669536a9341/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/5d2d250ce3b508705b25b18c1b8e41dfa4127f1d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/718bcff5e5c365277467c1890dbac9c73b0d1344/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/89b742600fcd24a85773367a1c46bbdec35c1f18/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/042c1fbfdd4436498aaf1af6a19d56694ba57ae4/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/03d5db2e14558e622c9314f54041b1e984c4762d/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/1106ed9f8c1b457c3addfb1334c5b0d847f53067/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/e234856c065d18f0813fa93d032b0966768de948/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/6753b9f4f9060f78278611c42989d13ee60a71a2/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/3ed42ece59d995703cf4ffc19d8c945342bb1687/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/70a91e87da70c310e7a8283410b83cd177cf6c83/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/c1b896f36dab4285b5282ec22fc5f864981f5c7f/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/1c1d5161d0e51a85b857a235ea90c58bcb037756/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/fa211c1d493817920ff5e757ec35e3140a5babdc/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/9fa924ac4e58238c1e367aaf07ae63c9289a0a9c/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/83518de585d7951fca01d546dc626d72d128089a/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/08f7fadcec18e757b85316498439339f8c38f724/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/d54208f4c96e9843453e47981cbbb4469b0966f5/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/e18b75c743dbd458ca5e86ba4064a4ee3268b433/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/eeab8c31867e43f2c90c5eb5c05fa3c0f6b34b44/hpc-arm-hwi-jenkins_W0) | :question: UNKNOWN
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9a40f94957022fbf62f117e3aa5280e2/raw/0616e29a30c8f11ddc4b50765c5340f6bdd79053/hpc-test-node-new_W1) | :question: UNKNOWN

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12882/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12902/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 06-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/bb22152c74860d58d4412ad617dafaa67a9f8372/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/13894aa01bc481cd2c5b3687fd1b39e63e2f2abe/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/a3013fcb7d26df5b789f3469b66d4e1f206bd657/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/b4da357df92224119d5e92aefd085455c88af510/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/f945712462ef3cdaa62cb39907ea0c43728ca3cf/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/f3bfc044f9b912b9d40c0990659abd0212f766eb/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/4d2cb8290af94313c7a8a4beab4334236b672659/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/6fdda24021cc70d6e60a33054186d62003320402/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/ba93f194b8ae2f085d0e41291c5ef1705511d0e9/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/e42ba0f5b3fd4a9745d5bfc8e723b29aeb267aa4/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/7e0c0c2a1f1815fb1167bc01e1518870c33e307f/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/17a28041a35c70017d4050bf9afad2395fb8da3e/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/a5b8307d3dde0dbaae548417df6a3a2f9ea53067/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/3abc7381282856e2926848fa88ac1587bfdb79fd/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/7e39aec1019942a8a081dc7f2766cbcc1ee106a6/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/fb34bc8d662d47bf9c1d2b76252ff3c351e45c95/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/ccfeefcc13d56c009d81e72e2d462a9601a05ac3/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/a69b60e5cdf16db03f9105bb4376980abcadba6c/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/97c86250d25ec360cf461cfab8f1f6c0a369fdef/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/6cda44dd48fcc1971bad1479f4334acbf6a1d9bf/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/3c7937b4b5c0b93e90dc8abea61878e23b5b19ce/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/cb1ea066a1f3bd0dc7d695c530cfcde6656de861/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/89f0b3ea5a32a608c4ee0c003e1c2b42511d4ce9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/b33262e6cae497f4eee75f6453c56e11f96f6360/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/dbf9ac11a2fc1579dd8aad04905c2902496609c1/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/def3b8f80ae5859a91f13edbe44728411c8f9441/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/b50a76a4e8d115e637fc557b1a56a3b32e0d6372/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/0a12ca14441a6e3f4448b0d5ca03044691bc3ad5/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/db50564a3be29160c8a64ad778c8bc93/raw/e8187b79d9f2b42cf08e54033a7c9a9dd9ece1f7/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by dmitrygx** [comment]
@yosefe ok to merge?
