### PR TITLE
Fix keepalive during wireup and failures in sockaddr gtests

### LINKED ISSUE #6225: hang in  all/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/1 <all/tag,mt>on r-vmb-ppc-jenkins
### Describe the bug
```
[2021-01-27T18:07:36.801Z] [ RUN      ] all/test_ucp_sockaddr_destroy_ep_on_err.onesided_client_sforce/1 <all/tag,mt>
[2021-01-27T18:07:37.057Z] [     INFO ] Testing 65.65.65.15:0
[2021-01-27T18:07:37.057Z] [     INFO ] server listening on 65.65.65.15:38923
[2021-01-27T18:08:45.031Z] /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc:724: Failure
[2021-01-27T18:08:45.031Z] Expected: (UCS_INPROGRESS) != (status), actual: 1 vs 1
[2021-01-27T18:08:45.031Z] free not completed EP close request: 0x10029f7c000
[2021-01-27T18:09:41.392Z] [1611770977.274603] [r-vmb-ppc-jenkins:15031:0]       ucp_test.cc:226  UCX  ERROR request 0x10029f7be80 did not complete on time
[2021-01-27T18:23:48.841Z] /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/common/test_helpers.cc:54: Failure
[2021-01-27T18:23:48.841Z] Failed
[2021-01-27T18:23:48.841Z] Connection timed out - abort testing
[2021-01-27T18:23:48.841Z] [r-vmb-ppc-jenkins:15031:0:15031] Caught signal 6 (Aborted: tkill(2) or tgkill(2))
[2021-01-27T18:23:48.841Z] 
[2021-01-27T18:23:48.841Z] /scrap/jenkins/workspace/ucx-8/contrib/../test/gtest/ucp/ucp_test.cc: [ ucp_test::progress() ]
[2021-01-27T18:23:48.841Z]       ...
[2021-01-27T18:23:48.841Z]       152          iter != entities().end(); ++iter)
[2021-01-27T18:23:48.841Z]       153     {
[2021-01-27T18:23:48.841Z]       154         count += (*iter)->progress(worker_index);
[2021-01-27T18:23:48.841Z] ==>   155         sched_yield();
[2021-01-27T18:23:48.841Z]       156     }
[2021-01-27T18:23:48.841Z]       157     return count;
[2021-01-27T18:23:48.841Z]       158 }
```

### PR DESCRIPTION
**Pull request by yosefe**
# Why
Fix #6225

Edit: Running ok about 16hrs with this fix. Before the fix - failed after 10-15min

# How
- 1st commit fixes the issue:
   - Enable keepalive on UCP client endpoint after getting connect response. init_lanes on wireup_ep->tmp_ep does not really enable keepalive
   - Fix uct endpoint search for lanes contained in wireup_ep->tmp_ep
- 2nd commit adds more detailed logging
- ~~5th commit sets ep_check_map on client ep to send keepalive on wireup_ep. Before this change, the ep_check map was 0, so keepalive was not sent.~~  5th commit has incomplete fix
- 8th commit fixes sending ep_check over wireup_ep: need to set ep_check_map right when creating client CM ep, and connect tmp_ep's lanes when getting reply from the server.

### CODE REVIEW

File: src/ucp/wireup/wireup.c [hunk 1]
```diff
@@ -327,16 +328,20 @@ ucp_wireup_connect_local(ucp_ep_h ep,
...
 
         status = uct_ep_connect_to_ep(ep->uct_eps[lane], dev_addr, ep_addr);
         if (status != UCS_OK) {
-            return status;
+            goto out;
         }
     }
 
-    return UCS_OK;
+    ucs_log_indent(-1);
```
Comment (dmitrygx) [inline src/ucp/wireup/wireup.c:340]:
```
    ...
    status = UCS_OK;

out:
    ucs_log_indent(-1);
    return status;
}
```

File: src/ucp/wireup/wireup_cm.c [hunk 2]
```diff
@@ -480,10 +491,17 @@ static unsigned ucp_cm_client_connect_progress(void *arg)
...
+        ucs_debug("ep %p flags 0x%x: restore initial configuration", ucp_ep,
+                  ucp_ep->flags);
         ucp_cm_client_restore_ep(wireup_ep, ucp_ep);
         ucp_wireup_remote_connected(ucp_ep);
     }
 
+    /* Add the client ep to worker's keeaplive, since init_lanes was called on
+     * wireup_ep->tmp_ep, which is INTERNAL, so did not add it to keepalive.
+     */
+    ucp_worker_keepalive_add_ep(ucp_ep);
```
Comment (dmitrygx) [inline src/ucp/wireup/wireup_cm.c:503]: 👍

File: src/ucp/wireup/wireup_ep.c [hunk 3]
```diff
@@ -628,8 +633,9 @@ int ucp_wireup_ep_is_owner(uct_ep_h uct_ep, uct_ep_h owned_ep)
         return 1;
     }
 
+    /* Check if owned_ep belongs to tmp_ep */
     if (wireup_ep->tmp_ep != NULL) {
-        return ucp_ep_lookup_lane(wireup_ep->tmp_ep, uct_ep) != UCP_NULL_LANE;
+        return ucp_ep_lookup_lane(wireup_ep->tmp_ep, owned_ep) != UCP_NULL_LANE;
```
Comment (dmitrygx) [inline src/ucp/wireup/wireup_ep.c:638]: 👍

**Review by dmitrygx — APPROVED** [review]
lgtm, besides the comment about log indent
thank you for fixing KA over TMP EP!

**Comment by yosefe** [comment]
> lgtm, besides the comment about log indent
> thank you for fixing KA over TMP EP!

Unfortunately, that fix is not complete, will push another one soon.
(I'd like to let it run for few hours to make sure it works, since the repro on PPC server takes about 10-15min)

**Comment by dmitrygx** [comment]
> (I'd like to let it run for few hours to make sure it works, since the repro on PPC server takes about 10-15min)

makes sense to me

**Review by dmitrygx — APPROVED** [review]

File: src/ucp/wireup/wireup.c [hunk 4]
```diff
@@ -364,6 +364,13 @@ void ucp_wireup_remote_connected(ucp_ep_h ep)
     }
 
     for (lane = 0; lane < ucp_ep_num_lanes(ep); ++lane) {
+        if (ep->uct_eps[lane] == NULL) {
```
Comment (dmitrygx) [inline src/ucp/wireup/wireup.c:367]: Does it mean that we call remote_connected for TMP EP?
I think we should not do it

File: src/ucp/core/ucp_ep.c [hunk 5]
```diff
@@ -366,6 +366,10 @@ ucs_status_t ucp_ep_init_create_wireup(ucp_ep_h ep, unsigned ep_init_flags,
     key.am_lane             = 0;
     if (ucp_ep_init_flags_has_cm(ep_init_flags)) {
         key.cm_lane         = 0;
+        /* Send keepalive on wireup_ep (which will send on aux_ep/tmp_ep) */
+        if (ep_init_flags & UCP_EP_INIT_ERR_MODE_PEER_FAILURE) {
```
Comment (dmitrygx) [inline src/ucp/core/ucp_ep.c:370]: Check also for `ucp_worker_keepalive_is_enabled()`?

Comment (yosefe) [reply src/ucp/core/ucp_ep.c:370]: yes, though it shouldn't matter since if keepalive is disabled we never get to use ep_check_map

File: src/ucp/wireup/wireup.c (hunk 4 above)
Comment (yosefe) [reply src/ucp/wireup/wireup.c:367]: yes, otherwise there is a problem in ucp_wireup_ep_check - from one hand, cannot call ep_check on next_ep if it's not connected, but from other hand, wireup_ep insite tmp_ep was never marked as connected even though it is
that said - I see I tests that doing this creates problems with config_intersect, checking...

File: src/ucp/wireup/wireup_cm.c [hunk 6]
```diff
@@ -491,9 +493,13 @@ static unsigned ucp_cm_client_connect_progress(void *arg)
     if (context->config.ext.cm_use_all_devices) {
         /* Connect tmp_ep so it will send keepalive messages while the new lanes
          * are being connected */
-        ucp_ep_update_remote_id(wireup_ep->tmp_ep,
-                                progress_arg->sa_data->ep_id);
-        ucp_wireup_remote_connected(wireup_ep->tmp_ep);
+        ucp_ep_update_remote_id(tmp_ep, progress_arg->sa_data->ep_id);
+        for (lane = 0; lane < ucp_ep_num_lanes(tmp_ep); ++lane) {
+            if ((ucp_ep_config(tmp_ep)->key.cm_lane != lane) &&
+                ucp_wireup_ep_test(tmp_ep->uct_eps[lane])) {
```
Comment (dmitrygx) [inline src/ucp/wireup/wireup_cm.c:499]: I thin they should be always wrapped by wireup_ep.
Do you see that the lane can be just UCT EP during client connect callback?
I'd change to assert that wireup_ep_test is always true

**Review by dmitrygx — APPROVED** [review]

**Review by dmitrygx — APPROVED** [review]

File: src/ucp/core/ucp_worker.c [hunk 7]
```diff
@@ -2729,8 +2732,11 @@ ucp_worker_do_keepalive_progress(ucp_worker_h worker)
         return 0;
     }
 
+    ucs_trace("worker %p: keepalive round", worker);
```
Comment (petro-rudenko) [inline src/ucp/core/ucp_worker.c:2735]: This calls in a loop! Maybe do log once per 100 or 1000 iterations, or decrease log level? Logs now full of it:
image and not much useful information
