### PR TITLE
TEST/ASYNC: Add retries to test_async.ctx_event_block

### LINKED ISSUE #4083: failure in thread_mutex/test_async.ctx_event_block/0
Happened here:

http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11986/label=hpc-test-node-legacy,worker=2/consoleFull#1664427763b7949d9e-3f09-4d9b-9be7-3ff694c6afcd
```
:47:31 [ RUN      ] thread_mutex/test_async.ctx_event_block/0
14:47:31 /scrap/jenkins/workspace/hpc-ucx-pr-3/label/hpc-test-node-legacy/worker/2/contrib/../test/gtest/ucs/test_async.cc:499: Failure
14:47:31 Expected: (le.count()) >= (1), actual: 0 vs 1
14:47:31 
[  FAILED  ] thread_mutex/test_async.ctx_event_block/0, where GetParam() = 2 (81 ms)
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #4083

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12965/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 07-Nov-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/3b3a2e96938fdd7a318b76ac1e1f3096f747eb41/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/6c6f2bb635485eea1a5f590e2e91d1653e42c22b/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/be411047a903e677677fad9caffb3d58e4db3050/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/09dd63b8e7dd68f08465c5aa35611db0fa99c51e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/4faa8f8b5d37ba9ad68e18ab09c2ba275db7b1f0/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/d87fdd6f199d696c011bac3b867eab6bb1b33916/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/1ca0ac2c762debe758362f207a2b52dba4ef76ac/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/ef90cc96ec014d41d781aaac022b2b45ff7e2bbc/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/c14b93442b2ca5098a7c2914c3415b69595c0bf6/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/5d81722f3e9c1d6bf733460e510b0b6e98b5268d/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/9ffbc3ea58ab1ee6943ae9477496217e5e323936/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/9d1019ab9fa6ff1d89e9a7b1a1741f9e033cb2c5/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/f0d9910a7c723f1b10a37dcbc4486d17ad4bb0ad/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/c4780b29e00f0961b943cbea72dba79e7c4fe617/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/3e33c62d07dbcea1f7b4cc99db3e6a60061c849d/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/e6e2077274afdd3c128fd7045e63c1cb345daef7/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/0707ae762943748dc9d0edb52910c45d34e8461a/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/d8d8c0324ed5a66385f95bfb6bb9547301956d4c/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/51524a33c15a74128a7655a5a75f0023e45af9dd/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/dd33a6eda3f953c53d94b941a8b8799622bd28eb/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/19f46994a89d9e8d2a171748e6c681598280172e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/4b5f10376a455e410ccb593e552b23f84301109e/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/c3f400559d78b1108dc9adcfcacbb9031929e64a/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/9e6fbe19a3cbb99cd9be37d0ee2cc7f0c4538034/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/2f02b288130bd070a89ccda73bb002b55a2381f1/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/0cde7b34f11ef96630813077f8aecdbdfc3588e0/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/b117100b81e8cc71b15cfbb71c0d74e18007305b/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/8a75327125c115f95e38970117d24bb508b25a9f/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/e83e8f7cb38c5b0e111afb883a69966e/raw/81a5ebe398268f74e8553b0a0f3363c01a13cfaa/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: test/gtest/ucs/test_async.cc [hunk 1]
```diff
@@ -810,6 +819,11 @@ UCS_TEST_P(test_async_timer_mt, multithread) {
     EXPECT_GE(min_count, exp_min_count);
 }
 
+std::ostream& operator<<(std::ostream& os, ucs_async_mode_t mode)
```
Comment (brminich) [inline test/gtest/ucs/test_async.cc]: where do you use it?

Comment (yosefe) [reply test/gtest/ucs/test_async.cc]: it's used (implicitly) by INSTANTIATE_xx to stringify the mode parameter and print it while test is running
without this it will be printed as number
