### PR TITLE
UCP/CORE: Fix printing invalid configuration

### LINKED ISSUE #8024: Segfault in ucp_worker_print_used_tls
### Describe the bug
```
#11 <signal handler called>
#12 0x00007fe9ea879ef9 in vfprintf () from /lib64/libc.so.6
#13 0x00007fe9ea8a4f39 in vsnprintf () from /lib64/libc.so.6
#14 0x00007fe9a6cbfac3 in ucs_string_buffer_appendf (strb=0x7fe9a7d2d3f0, fmt=0x7fe9a6390b00 "%s/%s ") at /hpc/mtr_scrap/users/peterr/
rapids/ucx/contrib/../src/ucs/datastruct/string_buffer.c:74
#15 0x00007fe9a623a6bd in ucp_worker_add_feature_rsc (context=0x7fe9e7852eb0, key=0x7fe9a7d2d480, lanes_bitmap=1 '\001', feature_str=0
x7fe9a6390b91 "am", strb=0x7fe9a7d2d3f0) at /hpc/mtr_scrap/users/peterr/rapids/ucx/contrib/../src/ucp/core/ucp_worker.c:1567
#16 0x00007fe9a623aab2 in ucp_worker_print_used_tls (key=0x7fe9a7d2d480, context=0x7fe9e7852eb0, config_idx=0 '\000', strb=0x7fe9a7d2d
3f0) at /hpc/mtr_scrap/users/peterr/rapids/ucx/contrib/../src/ucp/core/ucp_worker.c:1642
#17 0x00007fe9a623b37e in ucp_worker_get_ep_config (worker=0x7fe9a20e7b50, key=0x7fe9a7d2d480, ep_init_flags=54, cfg_index_p=0x7fe92ab
8c009 "\377\377\377\377") at /hpc/mtr_scrap/users/peterr/rapids/ucx/contrib/../src/ucp/core/ucp_worker.c:1885
#18 0x00007fe9a621132c in ucp_ep_init_create_wireup (ep=0x7fe92ab8c000, ep_init_flags=54, wireup_ep=0x7fe9a7d2d588) at /hpc/mtr_scrap/
users/peterr/rapids/ucx/contrib/../src/ucp/core/ucp_ep.c:658
#19 0x00007fe9a621169f in ucp_ep_create_to_sock_addr (worker=0x7fe9a20e7b50, params=0x7fe9a7d2d6a0, ep_p=0x7fe9a7d2d620) at /hpc/mtr_s
crap/users/peterr/rapids/ucx/contrib/../src/ucp/core/ucp_ep.c:745
#20 0x00007fe9a62122fe in ucp_ep_create (worker=0x7fe9a20e7b50, params=0x7fe9a7d2d6a0, ep_p=0x7fe9a7d2d7a0) at /hpc/mtr_scrap/users/pe
terr/rapids/ucx/contrib/../src/ucp/core/ucp_ep.c:1049
#21 0x00007fe9a5fc01a7 in Java_org_openucx_jucx_ucp_UcpEndpoint_createEndpointNative (env=0x7fe9b81c1340, jucx_ep=0x7fe9a7d2d8b8, ucp_
ep_params=0x7fe9a7d2d8b0, worker_ptr=140641422965584) at /hpc/mtr_scrap/users/peterr/rapids/ucx/contrib/../bindings/java/src/main/nati
ve/endpoint.cc:101
```

### Steps to Reproduce

```
>>> l
1562        ucs_string_buffer_appendf(strb, "%s(", feature_str);
1563
1564        ucs_for_each_bit(lane, lanes_bitmap) {
1565            ucs_assert(lane < UCP_MAX_LANES); /* make coverity happy */
1566            rsc_idx = key->lanes[lane].rsc_index;
1567            ucs_string_buffer_appendf(strb, UCT_TL_RESOURCE_DESC_FMT " ",
1568                                      UCT_TL_RESOURCE_DESC_ARG(
1569                                              &context->tl_rscs[rsc_idx].tl_rsc));
1570        }
1571
>>> p context->tl_rscs[rsc_idx].tl_rsc
$31 = {
  tl_name = "\000\000\000\000\000\000\000\000\000",
  dev_name = '\000' <repeats 31 times>,
  dev_type = UCT_DEVICE_TYPE_NET,
  sys_device = 0 '\000'
}
```

Seems like no varargs are passed to `ucs_string_buffer_appendf`

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Fix printing invalid configuration.
Now it is printed as follows:
```
[1647246206.076101] [swx-ucx07:40361:0]      ucp_worker.c:1899 UCX  INFO  ep_cfg[0]:
[1647246206.079982] [swx-ucx07:40361:0]      ucp_worker.c:1899 UCX  INFO  ep_cfg[1]: tag(rc_mlx5/mlx5_bond_0:1 rc_mlx5/mlx5_bond_0:1) rma(rc_mlx5/mlx5_bond_0:1) amo(rc_mlx5/mlx5_bond_0:1)
[1647246206.086670] [swx-ucx07:40361:0]      ucp_worker.c:1899 UCX  INFO    ep_cfg[2]: tag(rc_mlx5/mlx5_bond_0:1 rc_mlx5/mlx5_bond_0:1) rma(rc_mlx5/mlx5_bond_0:1) amo(rc_mlx5/mlx5_bond_0:1)
```

## Why ?

Fixes #8024
`print_cfg` parameter was removed from `ucp_worker_get_ep_config` function in 03e9f2b0052bf6e7e17c18c0c2d8cb6cf194acc0

## How ?

1. In `ucp_worker_get_ep_config`, check and add to lanes bitmap only valid TL resources.
2. In `ucp_worker_get_ep_config`, add AM lane for emualtion RMA/AMO lanes only if AM lane has value TL resource.
3. Add assertion in `ucp_worker_add_feature_rsc` to check that `rsc_idx` is valid.

### CODE REVIEW

**Comment by brminich** [comment]
can we avoid printing empty configs then?

**Comment by dmitrygx** [comment]
> can we avoid printing empty configs then?

@brminich done

File: src/ucp/core/ucp_worker.c [hunk 1]
```diff
@@ -1882,8 +1897,10 @@ ucs_status_t ucp_worker_get_ep_config(ucp_worker_h worker,
                                         UCP_PROTO_FLAG_AM_SHORT, key->am_lane,
                                         &ep_config->am_u.max_eager_short);
     } else {
-        ucs_info("%s", ucp_worker_print_used_tls(key, context, ep_cfg_index,
-                                                 &strb));
+        str = ucp_worker_print_used_tls(key, context, ep_cfg_index, &strb);
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:1900]: maybe ucp_worker_print_used_tls could call ucs_info() inside of it (and return void) ?

Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c]: done

**Review by yosefe — APPROVED** [review]

File: src/ucp/core/ucp_worker.c [hunk 2]
```diff
@@ -1573,23 +1574,32 @@ static void ucp_worker_add_feature_rsc(ucp_context_h context,
     ucs_string_buffer_appendf(strb, ") ");
 }
 
-const char *ucp_worker_print_used_tls(const ucp_ep_config_key_t *key,
-                                      ucp_context_h context,
-                                      ucp_worker_cfg_index_t config_idx,
-                                      ucs_string_buffer_t *strb)
+void ucp_worker_print_used_tls(const ucp_ep_config_key_t *key,
```
Comment (brminich) [inline src/ucp/core/ucp_worker.c:1577]: plz make it static

Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c]: done

**Review by brminich — DISMISSED** [review]

File: src/ucp/core/ucp_worker.c [hunk 3]
```diff
@@ -1574,9 +1574,9 @@ static void ucp_worker_add_feature_rsc(ucp_context_h context,
     ucs_string_buffer_appendf(strb, ") ");
 }
 
-void ucp_worker_print_used_tls(const ucp_ep_config_key_t *key,
-                               ucp_context_h context,
-                               ucp_worker_cfg_index_t config_idx)
+static void ucp_worker_print_used_tls(const ucp_ep_config_key_t *key,
```
Comment (yosefe) [inline src/ucp/core/ucp_worker.c:1577]: also change H file
(remove from H file)

**Comment by dmitrygx** [comment]
@yosefe is it ok?

File: src/ucp/core/ucp_worker.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/core/ucp_worker.c:1577]: it was removed

**Review by yosefe — DISMISSED** [review]

**Review by yosefe — APPROVED** [review]
