### PR TITLE
UCP/WIREUP: Create WIREUP EP for non-P2P TLs on a CM server side

### LINKED ISSUE #5908: dcx/test_ucp_sockaddr_destroy_ep_on_err.onesided_c2s_cforce/4 crashed on jazz
```
[ RUN      ] dcx/test_ucp_sockaddr_destroy_ep_on_err.onesided_c2s_cforce/4 <dc_x/tag,cm>
[New Thread 0x7ffff40ba700 (LWP 102524)]
[     INFO ] Testing 2.1.3.22:0
[     INFO ] server listening on 2.1.3.22:33672

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff749d64d in ucp_wireup_ep_pending_queue_purge (uct_ep=0x26f9ec0,
    cb=0x7ffff74a55ce <ucp_wireup_pending_purge_cb>, arg=0x7fffffffbae0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup_ep.c:215
215         ucp_worker_h worker        = wireup_ep->super.ucp_ep->worker;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7.x86_64 libgcc-
4.8.5-36.el7.x86_64 libgomp-4.8.5-36.el7.x86_64 libibverbs-50mlnx1-1.50100.0.x86_64 l
ibnl3-3.2.28-4.el7.x86_64 librdmacm-50mlnx1-1.50100.0.x86_64 libstdc++-4.8.5-36.el7.x
86_64 numactl-libs-2.0.9-7.el7.x86_64
(gdb) bt
#0  0x00007ffff749d64d in ucp_wireup_ep_pending_queue_purge (uct_ep=0x26f9ec0,
    cb=0x7ffff74a55ce <ucp_wireup_pending_purge_cb>, arg=0x7fffffffbae0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup_ep.c:215
#1  0x00007ffff74a4bc3 in ucp_wireup_check_config_intersect (ep=0x7fffdeabc000,
    new_key=0x7fffffffbb20,
    connect_lane_bitmap=0x7fffffffbba7 "\a\031[I\367\377\177",
    replay_pending_queue=0x7fffffffbae0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:1075
#2  0x00007ffff74a4fa4 in ucp_wireup_init_lanes (ep=0x7fffdeabc000,
    ep_init_flags=22, local_tl_bitmap=18446744073709551615,
    remote_address=0x7fffffffbd50, addr_indices=0x7fffffffbca0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:1147
#3  0x00007ffff74a1cec in ucp_wireup_init_lanes_by_request (worker=0x1e3f010,
    ep=0x7fffdeabc000, ep_init_flags=22, remote_address=0x7fffffffbd50,
    addr_indices=0x7fffffffbca0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:361
#4  0x00007ffff74a2055 in ucp_wireup_process_pre_request (worker=0x1e3f010,
    msg=0x7fffee3fcc02, remote_address=0x7fffffffbd50)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:405
#5  0x00007ffff74a32a4 in ucp_wireup_msg_handler (arg=0x1e3f010,
    data=0x7fffee3fcc02, length=185, flags=1)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:711
#6  0x00007ffff713be3a in uct_iface_invoke_am (iface=0x200a010, id=1 '\001',
    data=0x7fffee3fcc02, length=185, flags=1)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/uct/base/uct_iface.h:654
#7  0x00007ffff713f4cf in uct_rc_mlx5_iface_common_am_handler (byte_len=187,
    flags=1, hdr=0x7fffee3fcc00, cqe=0x7fffee4f9040, iface=0x200a010)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/uct/ib/rc/accel/rc_mlx5.inl:428
```

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Create WIREUP EP for P2P TLs on a CM server side.

## Why ?

Fixes #5908 
All lanes have to be WIREUP EP until CM and WIREUP_MSG phases of connection establishment are not done.
Fixes the following test failure on jazz nodes:
```
[10:44 AM] Evgeny Leksikov
    
[ RUN      ] dcx/test_ucp_sockaddr_destroy_ep_on_err.onesided_c2s_cforce/4 <dc_x/tag,
cm>
[New Thread 0x7ffff40ba700 (LWP 102524)]
[     INFO ] Testing 2.1.3.22:0
[     INFO ] server listening on 2.1.3.22:33672
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff749d64d in ucp_wireup_ep_pending_queue_purge (uct_ep=0x26f9ec0,
    cb=0x7ffff74a55ce <ucp_wireup_pending_purge_cb>, arg=0x7fffffffbae0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup_ep.c:215
215         ucp_worker_h worker        = wireup_ep->super.ucp_ep->worker;
Missing separate debuginfos, use: debuginfo-install glibc-2.17-260.el7.x86_64 libgcc-
4.8.5-36.el7.x86_64 libgomp-4.8.5-36.el7.x86_64 libibverbs-50mlnx1-1.50100.0.x86_64 l
ibnl3-3.2.28-4.el7.x86_64 librdmacm-50mlnx1-1.50100.0.x86_64 libstdc++-4.8.5-36.el7.x
86_64 numactl-libs-2.0.9-7.el7.x86_64
(gdb) bt
#0  0x00007ffff749d64d in ucp_wireup_ep_pending_queue_purge (uct_ep=0x26f9ec0,
    cb=0x7ffff74a55ce <ucp_wireup_pending_purge_cb>, arg=0x7fffffffbae0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup_ep.c:215
#1  0x00007ffff74a4bc3 in ucp_wireup_check_config_intersect (ep=0x7fffdeabc000,
    new_key=0x7fffffffbb20,
    connect_lane_bitmap=0x7fffffffbba7 "\a\031[I\367\377\177",
    replay_pending_queue=0x7fffffffbae0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:1075
#2  0x00007ffff74a4fa4 in ucp_wireup_init_lanes (ep=0x7fffdeabc000,
    ep_init_flags=22, local_tl_bitmap=18446744073709551615,
    remote_address=0x7fffffffbd50, addr_indices=0x7fffffffbca0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:1147
#3  0x00007ffff74a1cec in ucp_wireup_init_lanes_by_request (worker=0x1e3f010,
    ep=0x7fffdeabc000, ep_init_flags=22, remote_address=0x7fffffffbd50,
    addr_indices=0x7fffffffbca0)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:361
#4  0x00007ffff74a2055 in ucp_wireup_process_pre_request (worker=0x1e3f010,
    msg=0x7fffee3fcc02, remote_address=0x7fffffffbd50)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:405
#5  0x00007ffff74a32a4 in ucp_wireup_msg_handler (arg=0x1e3f010,
    data=0x7fffee3fcc02, length=185, flags=1)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/ucp/wireup/wireup.c:711
#6  0x00007ffff713be3a in uct_iface_invoke_am (iface=0x200a010, id=1 '\001',
    data=0x7fffee3fcc02, length=185, flags=1)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/uct/base/uct_iface.h:654
#7  0x00007ffff713f4cf in uct_rc_mlx5_iface_common_am_handler (byte_len=187,
    flags=1, hdr=0x7fffee3fcc00, cqe=0x7fffee4f9040, iface=0x200a010)
    at /labhome/evgenylek/wdir/git/ucx/contrib/../src/uct/ib/rc/accel/rc_mlx5.inl:428
```
Since DC (`CONNECT_TO_IFACE`) TL is not going to be used anymore as an AM lane (and it will be WIREUP MSG lane saved in CM lane until WIREUP_MSG phase is not done), it was dereferenced to move user's pending requests from its WIREUP EP to new created WIREUP lane for AM lane during reconfiguration.

## How ?

1. Always create WIREUP EP for non-P2P lanes in case of CM as we do for P2P lanes (if `uct_ep == NULL`).
2. Update `ucp_wireup_assign_lane()` to assign mark WIREUP EP as remote connected only if it is not a CM case.
3. Make `ucp_wireup_assign_lane()` function `static`, since it is used only in a single file, remove its declaration from `ucp/wireup/wireup.h` header file.

### CODE REVIEW

**Comment by dmitrygx** [comment]
bot:pipe:retest

**Comment by dmitrygx** [comment]
@evgeny-leksikov @brminich @alinask @hoopoepg could you review pls?

**Review by hoopoepg — APPROVED** [review]

**Comment by dmitrygx** [comment]
@evgeny-leksikov @brminich could you review pls?

**Review by evgeny-leksikov — APPROVED** [review]

File: src/ucp/wireup/wireup.c [hunk 1]
```diff
@@ -791,6 +797,17 @@ ucp_wireup_connect_lane_to_iface(ucp_ep_h ep, ucp_lane_index_t lane,
         return UCS_ERR_UNREACHABLE;
     }
 
+    if ((ep->uct_eps[lane] == NULL) && ucp_ep_has_cm_lane(ep)) {
+        /* create wireup EP in case of CM lane is used, since a WIREUP EP is
+         * used to keep user's pending requests and send WIREUP MSGs (if this
+         * is WIREUP MSG lane) until CM and WIREUP_MSG phases are not done */
```
Comment (brminich) [inline src/ucp/wireup/wireup.c:803]: minor: `until ... are done` or `while ... are not done`

**Review by brminich — APPROVED** [review]

File: src/ucp/wireup/wireup.c (hunk 1 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup.c]: done

**Review by brminich — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

File: src/ucp/wireup/wireup.c [hunk 2]
```diff
@@ -738,7 +738,13 @@ void ucp_wireup_assign_lane(ucp_ep_h ep, ucp_lane_index_t lane, uct_ep_h uct_ep,
         ucs_trace("ep %p: wireup uct_ep[%d]=%p next set to %p%s", ep, lane,
                   ep->uct_eps[lane], uct_ep, info);
         ucp_wireup_ep_set_next_ep(ep->uct_eps[lane], uct_ep);
-        ucp_wireup_ep_remote_connected(ep->uct_eps[lane]);
+        /* Don't mark a WIREUP EP as remote connected in case of CM, since it
+         * flushes and removes a WIREUP EP, but a WIREUP EP is used to keep
+         * user's pending requests and send WIREUP MSGs until CM and WIREUP_MSG
+         * phases are not done */
+        if (!ucp_ep_has_cm_lane(ep)) {
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:745]: maybe pass "remote_connected" boolean parameter from ucp_wireup_connect_lane_to_iface to ucp_wireup_assign_lane?
in case of ucp_wireup_connect_lane_to_iface() it will be 0, in other cases - 1

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:745]: `ucp_wireup_assign_lane()` is used only in `ucp_wireup_connect_lane_to_iface()`

Comment (yosefe) [reply src/ucp/wireup/wireup.c:745]: never set remote connected, replace by assert(has_cm)

Comment (yosefe) [reply src/ucp/wireup/wireup.c:745]: remove this function ucp_wireup_assign_lane altogether, merge into ucp_wireup_connect_lane_to_iface

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:745]: fixed

**Comment by dmitrygx** [comment]
@yosefe could you review pls?

**Comment by dmitrygx** [comment]
bot:pipe:retest

File: src/ucp/wireup/wireup.c [hunk 3]
```diff
@@ -825,7 +801,25 @@ ucp_wireup_connect_lane_to_iface(ucp_ep_h ep, ucp_lane_index_t lane,
...
-    ucp_wireup_assign_lane(ep, lane, uct_ep, "");
+    /* If EP already exists, it's a wireup proxy (only client-server),
+     * and we need to update its next_ep instead of replacing it.
+     */
+    if (ep->uct_eps[lane] == NULL) {
+        ucs_trace("ep %p: assign uct_ep[%d]=%p", ep, lane, uct_ep);
+        ep->uct_eps[lane] = uct_ep;
+    } else {
+        ucs_assert(ucp_wireup_ep_test(ep->uct_eps[lane]) &&
+                   (ucp_ep_has_cm_lane(ep) || !ucp_ep_is_sockaddr_stub(ep)));
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:812]: 1. will ucp_ep_is_sockaddr_stub also be removed when old sockaddr is removed? add comment
2. can we split to 2 asserts instead of &&, will make failure more clear

File: src/ucp/wireup/wireup.c [hunk 4]
```diff
@@ -808,7 +801,25 @@ ucp_wireup_connect_lane_to_iface(ucp_ep_h ep, ucp_lane_index_t lane,
         return status;
     }
 
-    ucp_wireup_assign_lane(ep, lane, uct_ep, "");
+    /* If EP already exists, it's a wireup proxy (only client-server),
+     * and we need to update its next_ep instead of replacing it.
+     */
+    if (ep->uct_eps[lane] == NULL) {
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:807]: can we move the block of code in line 776..786 to here, and unite with it?
some logic is duplicated

File: src/ucp/wireup/wireup.c (hunk 3 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup.c]: let's remove the assert for old sockaddr

File: src/ucp/wireup/wireup.c [hunk 5]
```diff
@@ -801,20 +790,29 @@ ucp_wireup_connect_lane_to_iface(ucp_ep_h ep, ucp_lane_index_t lane,
...
     if (ep->uct_eps[lane] == NULL) {
         ucs_trace("ep %p: assign uct_ep[%d]=%p", ep, lane, uct_ep);
         ep->uct_eps[lane] = uct_ep;
     } else {
-        ucs_assert(ucp_wireup_ep_test(ep->uct_eps[lane]) &&
-                   (ucp_ep_has_cm_lane(ep) || !ucp_ep_is_sockaddr_stub(ep)));
+        /* If EP already exists, it's a wireup proxy, and we need to update
+         * its next_ep instead of replacing it.
+         */
+        ucs_assert(ucp_wireup_ep_test(ep->uct_eps[lane]));
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c]: can we do like this
ucs_assert(ep->uct_eps[lane] == NULL)
if (ucp_ep_has_cm_lane(ep)) {
   ucp_wireup_ep_create
   ucp_wireup_ep_set_next_ep
   ...
} else {
  ep->uct_eps[lane] = uct_ep;
}

File: src/ucp/wireup/wireup.c [hunk 6]
```diff
@@ -790,28 +799,28 @@ ucp_wireup_connect_lane_to_iface(ucp_ep_h ep, ucp_lane_index_t lane,
...
     } else {
         /* If EP already exists, it's a wireup proxy, and we need to update
          * its next_ep instead of replacing it.
          */
         ucs_assert(ucp_wireup_ep_test(ep->uct_eps[lane]));
-        ucs_trace("ep %p: wireup uct_ep[%d]=%p next set to %p", ep, lane,
-                  ep->uct_eps[lane], uct_ep);
-        ucp_wireup_ep_set_next_ep(ep->uct_eps[lane], uct_ep);
+        ucs_assert(ucp_proxy_ep_extract(ep->uct_eps[lane]) == NULL);
+        ucp_wireup_ep_lane_set_next_ep(ep, lane, uct_ep);
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:823]: in which case the 2iface lane can already exist? old cm flow?

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:823]: added assertion to check that this is possible for old and new sockaddr flows only

File: src/ucp/wireup/wireup.c [hunk 7]
```diff
@@ -808,7 +799,38 @@ ucp_wireup_connect_lane_to_iface(ucp_ep_h ep, ucp_lane_index_t lane,
...
+            ucs_trace("ep %p: assign uct_ep[%d]=%p", ep, lane, uct_ep);
+            ep->uct_eps[lane] = uct_ep;
+        }
+    } else {
+        /* If EP already exists, it's a wireup proxy, and we need to update
+         * its next_ep instead of replacing it.
+         */
+        ucs_assert(ucp_wireup_ep_test(ep->uct_eps[lane]));
+        ucs_assert(ucp_proxy_ep_extract(ep->uct_eps[lane]) == NULL);
+        ucs_assert(ucp_ep_has_cm_lane(ep) ||
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:823]: can this happen for new CM flow ?
e.g is it possible that ucp_ep_has_cm_lane() is true, and ep->uct_eps[lane]!=NULL?

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:823]: > can this happen for new CM flow ?
> e.g is it possible that ucp_ep_has_cm_lane() is true, and ep->uct_eps[lane]!=NULL?

`uct_eps[lane] != NULL` on a client side
`uct_eps[lane] == NULL` on a server side

Comment (yosefe) [reply src/ucp/wireup/wireup.c:823]: > `uct_eps[lane] != NULL` on a client side

Is it because of endpoint reconfiguration?

Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:823]: no, this is the initial configuration for client and server.
during reconfiguration, it could be `!= NULL`, or `== NULL` depending on the case (re-used or new TL)

File: src/ucp/wireup/wireup.c [hunk 8]
```diff
@@ -808,7 +799,38 @@ ucp_wireup_connect_lane_to_iface(ucp_ep_h ep, ucp_lane_index_t lane,
         return status;
     }
 
-    ucp_wireup_assign_lane(ep, lane, uct_ep, "");
+    if (ep->uct_eps[lane] == NULL) {
+        if (ucp_ep_has_cm_lane(ep)) {
+            /* create wireup EP in case of CM lane is used, since a WIREUP EP is
+             * used to keep user's pending requests and send WIREUP MSGs (if it
+             * is WIREUP MSG lane) until CM and WIREUP_MSG phases are done */
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:806]: lane was added after wireup_msg exchange, or server created initial configuration after a connection request

File: src/ucp/wireup/wireup.c [hunk 9]
```diff
@@ -808,7 +799,38 @@ ucp_wireup_connect_lane_to_iface(ucp_ep_h ep, ucp_lane_index_t lane,
...
+            status = ucp_wireup_ep_create(ep, &ep->uct_eps[lane]);
+            if (status != UCS_OK) {
+                /* coverity[leaked_storage] */
+                return status;
+            }
+            ucp_wireup_ep_lane_set_next_ep(ep, lane, uct_ep);
+        } else {
+            ucs_trace("ep %p: assign uct_ep[%d]=%p", ep, lane, uct_ep);
+            ep->uct_eps[lane] = uct_ep;
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:815]: out-of-band address exchange

File: src/ucp/wireup/wireup.c [hunk 10]
```diff
@@ -808,7 +799,38 @@ ucp_wireup_connect_lane_to_iface(ucp_ep_h ep, ucp_lane_index_t lane,
...
+        }
+    } else {
+        /* If EP already exists, it's a wireup proxy, and we need to update
+         * its next_ep instead of replacing it.
+         */
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c:820]: wireup_ep created on client during pack_cb

File: src/ucp/wireup/wireup.c (hunk 8 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:806]: done

File: src/ucp/wireup/wireup.c (hunk 9 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:815]: done

File: src/ucp/wireup/wireup.c (hunk 10 above)
Comment (dmitrygx) [reply src/ucp/wireup/wireup.c:820]: done

**Review by yosefe — APPROVED** [review]

**Comment by dmitrygx** [comment]
@yosefe ok to merge?
