### PR TITLE
BINDINGS/GO: Check compiler minimum version.

### LINKED ISSUE #7669: Compile: error building go interface
### Describe the bug

Compile fails with

```
make[2]: Entering directory '/.../src/ucx/build/bindings/go'
cd /.../src/ucx/build/../ucx-git/bindings/go/src/examples/perftest ;\
go build -o /.../src/ucx/build/bindings/go/.libs/tmp/goperftest
# examples/perftest
./perftest.go:346:18: flag.CommandLine.Func undefined (type *flag.FlagSet has no field or method Func)
make[2]: *** [Makefile:634: goperftest] Error 2
```

### Setup and versions

ucx @ master ef9b1906d3598f67ba7cfb6e0894b3882e7e5db1

go version go1.13.3 linux/arm64 (from CentOS)

- OS version (e.g Linux distro) + CPU architecture (x86_64/aarch64/ppc64le/...)
   - `cat /etc/issue` or `cat /etc/redhat-release` + `uname -a`

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="8 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="8"

$ uname -a
Linux login1 4.18.0-147.el8.aarch64 #1 SMP Wed Dec 4 21:57:21 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```

### PR DESCRIPTION
**Pull request by petro-rudenko**
## What
Check go compiler version.

## Why ?
Fixes  #7669

### CODE REVIEW

File: contrib/check_go_compiler_version.sh [hunk 1]
```diff
@@ -0,0 +1,14 @@
...
+# Copyright (C) 2021, NVIDIA CORPORATION & AFFILIATES. ALL RIGHTS RESERVED.
+#
+# See file LICENSE for terms.
+#
+
+function ver { printf "%03d%03d%03d%03d" $(echo "$1" | tr '.' ' '); }
+
+goversion=`go version | awk '{print substr($3, 3, length($3)-2)}'`
+
+[ $(ver $goversion) -ge $(ver $1) ] && exit 0
```
Comment (yosefe) [inline contrib/check_go_compiler_version.sh:12]: maybe use m4_version_compare, so need another script file and put all inside go.m4?

File: config/m4/go.m4 [hunk 2]
```diff
@@ -18,7 +18,9 @@ AS_IF([test "x$with_go" != xno],
       [
             AC_CHECK_PROG(GOBIN, go, yes)
             AS_IF([test "x${GOBIN}" = "xyes"],
-                  [go_happy="yes"],
+                  [AS_VERSION_COMPARE(1.16, `go version | awk '{print substr($3, 3, length($3)-2)}'`,
```
Comment (yosefe) [inline config/m4/go.m4:21]: pls wrap the version check command with [ ]

**Review by yosefe — APPROVED** [review]
