### PR TITLE
UCS/RCACHE: Fix rcache merge while mappings are modified.

### LINKED ISSUE #1284: ibv_reg_mr registers the wrong size in mpi_test_suite
There is a an error on ibv_reg_mr which happens on the rndv flow.

Command line to reproduce:

/hpc/local/benchmarks/hpcx_install_Wednesday/hpcx-gcc-redhat7.2/ompi-v2.x/bin/mpirun -np 512 -mca btl_openib_warn_default_gid_prefix 0 --bind-to core --tag-output --timestamp-output --display-map -mca pml ucx -x UCX_SHM_DEVICES=all -x UCX_NET_DEVICES=mlx5_0:1 -x UCX_ACC_DEVICES=all -mca btl_openib_if_include mlx5_0:1 -mca coll_hcoll_enable 0 -x UCX_IB_ADDR_TYPE=ib_local -x UCX_TLS=dc,mm -mca opal_pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/scrap/users/mtt/scratch/ucx_ompi/20170128_072017_21640_78789_clx-hercules-081/installs/xl7O/tests/mpi-test-suite/ompi-tests/mpi_test_suite/mpi_test_suite -x relaxed -t 'All,^One-sided,^IO,^Environment' -n 300

May need to run several times to reproduce. This is 16 hosts with ppn=32.

Trace:

```
Sun Jan 29 12:27:18 2017[1,0]<stdout>:Collective tests Allgather with MPI_IN_PLACE (34/44), comm MPI_COMM_WORLD (1/14), type MPI_DOUBLE (12/28)
Sun Jan 29 12:27:18 2017[1,0]<stdout>:Collective tests Allgather with MPI_IN_PLACE (34/44), comm MPI_COMM_WORLD (1/14), type MPI_LONG_DOUBLE (13/28)
Sun Jan 29 12:27:18 2017[1,0]<stdout>:Collective tests Allgather with MPI_IN_PLACE (34/44), comm MPI_COMM_WORLD (1/14), type MPI_LONG_LONG (14/28)
Sun Jan 29 12:27:18 2017[1,308]<stderr>:[clx-hercules-053:19052:0]        rndv.c:144  Assertion `status == UCS_OK' failed
Sun Jan 29 12:27:18 2017[1,308]<stdout>:[1485685638.318672] [clx-hercules-053:19052:0]          ib_md.c:334  UCX  ERROR ibv_reg_mr(address=0x1058a70, length=4915920, access=0xf) failed: Bad address
Sun Jan 29 12:27:18 2017[1,308]<stdout>:[1485685638.318713] [clx-hercules-053:19052:0]  ucp_request.inl:106  UCX  ERROR failed to register user buffer [address 0x121aa70 len 614400 pd ib]: Input/output error
Sun Jan 29 12:27:18 2017[1,308]<stderr>:==== backtrace ====
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 0 0x000000000001260c ucp_proto_progress_rndv_get()  /hpc/local/benchmarks/hpcx_install_Friday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/tag/rndv.c:144
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 1 0x000000000000b77b ucp_request_try_send()  /hpc/local/benchmarks/hpcx_install_Friday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/core/ucp_request.c:143
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 2 0x000000000000b77b ucp_request_start_send()  /hpc/local/benchmarks/hpcx_install_Friday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/core/ucp_request.c:168
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 3 0x0000000000012f30 ucp_rndv_handle_recv_generic()  /hpc/local/benchmarks/hpcx_install_Friday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/tag/rndv.c:286
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 4 0x0000000000013ae0 ucp_tag_recv_common()  /hpc/local/benchmarks/hpcx_install_Friday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/tag/tag_recv.c:64
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 5 0x0000000000013ae0 ucp_tag_search_unexp()  /hpc/local/benchmarks/hpcx_install_Friday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/tag/tag_recv.c:65
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 6 0x0000000000013ae0 ucp_tag_recv_common()  /hpc/local/benchmarks/hpcx_install_Friday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/tag/tag_recv.c:151
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 7 0x0000000000013ae0 ucp_tag_recv_nb()  /hpc/local/benchmarks/hpcx_install_Friday/src/hpcx-gcc-redhat7.2/ucx-master/src/ucp/tag/tag_recv.c:224
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 8 0x0000000000002c57 mca_pml_ucx_irecv()  /hpc/local/benchmarks/hpcx_install_Friday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mca/pml/ucx/pml_ucx.c:471
Sun Jan 29 12:27:18 2017[1,308]<stderr>: 9 0x000000000006e151 ompi_coll_base_sendrecv_nonzero_actual()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mca/coll/base/coll_base_util.c:50
Sun Jan 29 12:27:18 2017[1,308]<stderr>:10 0x000000000006cacc ompi_coll_base_sendrecv()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mca/coll/base/coll_base_util.h:67
Sun Jan 29 12:27:18 2017[1,308]<stderr>:11 0x0000000000052681 PMPI_Allgather()  /hpc/local/benchmarks/hpcx_install_Wednesday/src/hpcx-gcc-redhat7.2/ompi-v2.x/ompi/mpi/c/profile/pallgather.c:119
Sun Jan 29 12:27:18 2017[1,308]<stderr>:12 0x00000000004046c3 tst_coll_allgather_in_place_run()  /hpc/scrap/users/mtt/scratch/ucx_ompi/20170128_072017_21640_78789_clx-hercules-081/installs/xl7O/tests/mpi-test-suite/ompi-tests/mpi_test_suite/coll/tst_coll_allgather_in_place.c:64
Sun Jan 29 12:27:18 2017[1,308]<stderr>:13 0x0000000000436ba3 tst_test_run_func()  /hpc/scrap/users/mtt/scratch/ucx_ompi/20170128_072017_21640_78789_clx-hercules-081/installs/xl7O/tests/mpi-test-suite/ompi-tests/mpi_test_suite/tst_tests.c:1461
Sun Jan 29 12:27:18 2017[1,308]<stderr>:14 0x0000000000412f01 main()  /hpc/scrap/users/mtt/scratch/ucx_ompi/20170128_072017_21640_78789_clx-hercules-081/installs/xl7O/tests/mpi-test-suite/ompi-tests/mpi_test_suite/mpi_test_suite.c:637
Sun Jan 29 12:27:18 2017[1,308]<stderr>:15 0x0000000000021b15 __libc_start_main()  ???:0
Sun Jan 29 12:27:18 2017[1,308]<stderr>:16 0x0000000000403e29 _start()  ???:0
Sun Jan 29 12:27:18 2017[1,308]<stderr>:===================
```

Attaching in gdb:
```
Thread 1 (Thread 0x7ffff7fb5740 (LWP 19052)):
#0  0x00007ffff7909a2d in pause () from /usr/lib64/libpthread.so.0
#1  0x00007fffea81d0f5 in ucs_debug_freeze () at debug/debug.c:720
#2  0x00007fffea81e985 in ucs_error_freeze (message=0x7fffffffac80 "       rndv.c:144  Assertion `status == UCS_OK' failed", error_type=0x7fffeaf88dd1 "assertion failure") at debug/debug.c:839
#3  ucs_handle_error (error_type=error_type@entry=0x7fffeaf88dd1 "assertion failure", message=message@entry=0x7fffea8b9300 "%13s:%-4u %s") at debug/debug.c:1003
#4  0x00007fffea81fe62 in __ucs_abort (error_type=error_type@entry=0x7fffeaf88dd1 "assertion failure", file=file@entry=0x7fffeaf89b41 "tag/rndv.c", line=line@entry=144, function=function@entry=0x7fffeaf89c00 <__FUNCTION__.12969> "ucp_proto_progress_rndv_get", message=message@entry=0x7fffeaf88dbb "Assertion `%s' failed") at debug/log.c:226
#5  0x00007fffeaf8160c in ucp_proto_progress_rndv_get (self=0xc7b0c0) at tag/rndv.c:144
#6  0x00007fffeaf7a77b in ucp_request_try_send (req_status=0x7fffffffb7a0, req=0xc7b040) at core/ucp_request.c:143
#7  ucp_request_start_send (req=req@entry=0xc7b040) at core/ucp_request.c:168
#8  0x00007fffeaf81f30 in ucp_rndv_handle_recv_generic (rndv_rts_hdr=<optimized out>, rreq=<optimized out>, rndv_req=<optimized out>) at tag/rndv.c:286
#9  ucp_rndv_matched (worker=0x9ed4f0, rreq=0xcd7ac0, rndv_rts_hdr=0x7fffe03f2dd8) at tag/rndv.c:322
#10 0x00007fffeaf82ae0 in ucp_tag_search_unexp (save_rreq=<synthetic pointer>, info=0xcd7b00, req=0xcd7ac0, tag_mask=18446744073709551615, tag=18446733078621847552, datatype=128, count=38400, buffer=0x121aa70, worker=0x9ed4f0) at tag/tag_recv.c:64
#11 ucp_tag_recv_common (req=0xcd7ac0, tag_mask=18446744073709551615, tag=18446733078621847552, datatype=128, count=38400, buffer=0x121aa70, worker=0x9ed4f0) at tag/tag_recv.c:151
#12 ucp_tag_recv_nb (worker=0x9ed4f0, buffer=buffer@entry=0x121aa70, count=38400, datatype=128, tag=tag@entry=18446733078621847552, tag_mask=tag_mask@entry=18446744073709551615, cb=0x7fffeb195140 <mca_pml_ucx_recv_completion>) at tag/tag_recv.c:224
#13 0x00007fffeb192c57 in mca_pml_ucx_irecv (buf=0x121aa70, count=<optimized out>, datatype=<optimized out>, src=<optimized out>, tag=<optimized out>, comm=<optimized out>, request=0x7fffffffb940) at pml_ucx.c:471
#14 0x00007ffff7b85151 in ompi_coll_base_sendrecv_nonzero_actual (sendbuf=0x1184a70, scount=38400, sdatatype=sdatatype@entry=0x7ffff7dc1d80 <ompi_mpi_long_double>, dest=dest@entry=436, stag=stag@entry=-10, recvbuf=<optimized out>, rcount=38400, rdatatype=rdatatype@entry=0x7ffff7dc1d80 <ompi_mpi_long_double>, source=source@entry=436, rtag=rtag@entry=-10, comm=comm@entry=0x6578e0 <ompi_mpi_comm_world>, status=status@entry=0x0) at base/coll_base_util.c:50
#15 0x00007ffff7b83acc in ompi_coll_base_sendrecv (stag=-10, rtag=-10, status=0x0, myid=308, comm=0x6578e0 <ompi_mpi_comm_world>, source=436, rdatatype=0x7ffff7dc1d80 <ompi_mpi_long_double>, rcount=<optimized out>, recvbuf=<optimized out>, dest=436, sdatatype=0x7ffff7dc1d80 <ompi_mpi_long_double>, scount=<optimized out>, sendbuf=<optimized out>) at base/coll_base_util.h:67
#16 ompi_coll_base_allgather_intra_recursivedoubling (sbuf=<optimized out>, scount=<optimized out>, sdtype=<optimized out>, rbuf=0x1058a70, rcount=300, rdtype=0x7ffff7dc1d80 <ompi_mpi_long_double>, comm=0x6578e0 <ompi_mpi_comm_world>, module=0xb44490) at base/coll_base_allgather.c:328
#17 0x00007ffff7b69681 in PMPI_Allgather (sendbuf=<optimized out>, sendcount=<optimized out>, sendtype=<optimized out>, recvbuf=<optimized out>, recvcount=<optimized out>, recvtype=<optimized out>, comm=0x6578e0 <ompi_mpi_comm_world>) at pallgather.c:119
#18 0x00000000004046c3 in tst_coll_allgather_in_place_run (env=0x7fffffffbde0) at coll/tst_coll_allgather_in_place.c:64
#19 0x0000000000436ba3 in tst_test_run_func (env=0x7fffffffbde0) at tst_tests.c:1461
#20 0x0000000000412f01 in main (argc=7, argv=0x7fffffffc098) at mpi_test_suite.c:637
```

Note: the trace may not be correct due to compiler optimizations.

Since on the recv side the count is 38400 and the type is ompi_mpi_long_double, which is 16B (ompi_mpi_long_double.dt.super.size), the length for registration should be 38400*16=614400 which is what ucp is trying to register:
```
 ucp_request.inl:106  UCX  ERROR failed to register user buffer [address 0x121aa70 len 614400 pd ib]
```
but ibv_reg_mr is attempting to register a different size and on a different address:
```
 ib_md.c:334  UCX  ERROR ibv_reg_mr(address=0x1058a70, length=4915920, access=0xf) 
```

### PR DESCRIPTION
**Pull request by yosefe**
Fixes #1284

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1575/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3502/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test FAILed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1581/ for details.

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3507/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
Test PASSed.
See http://bgate.mellanox.com/jenkins/job/gh-ucx-pr/1582/ for details.

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/3508/ for details (Mellanox internal link).

**Comment by yosefe** [comment]
@alinask pls review

File: src/ucs/sys/rcache.c [hunk 1]
```diff
@@ -442,12 +447,19 @@ ucs_rcache_create_region(ucs_rcache_t *rcache, void *address, size_t length,
...
-                                ucs_status_string(status));
-        goto out_unlock;
+        if (merged) {
+            /* failure may be due to merge, retry with original address */
+            ucs_debug("failed to register merged region " UCS_PGT_REGION_FMT ": %s, retrying",
+                      UCS_PGT_REGION_ARG(&region->super), ucs_status_string(status));
+            status = ucs_pgtable_remove(&rcache->pgtable, &region->super);
+            ucs_assert_always(status == UCS_OK);
+            ucs_mem_region_destroy_internal(rcache, region);
+            goto retry;
```
Comment (alinask) [inline src/ucs/sys/rcache.c]: can this create an endless loop?

Comment (yosefe) [inline src/ucs/sys/rcache.c]: no, because the next iteration 'merge' flag would be 0 - the previous overlapping regions are already destroyed, and no new regions could be created because we are under lock
