### PR TITLE
UCP/UCS/UCT: Fix memtype_cache region info after merge

### LINKED ISSUE #7575: `RDMA_READ` errors without `UCX_MEMTYPE_CACHE=n`
### Describe the bug
After whole alloc and memtype_cache changes from https://github.com/openucx/ucx/pull/7128 , we should now not need to set `UCX_MEMTYPE_CACHE=n` anymore. In most cases that works fine, but for some Dask workflows we see RDMA_READ errors such as bellow when we don't set any `UCX_MEMTYPE_CACHE`.

```
[1634937588.651064] [dgx13:4074 :0]     ib_mlx5_log.c:170  UCX  ERROR Local protection on mlx5_0:1/IB (synd 0x4 vend 0x33 hw_synd 0/157)
[1634937588.651064] [dgx13:4074 :0]     ib_mlx5_log.c:170  UCX  ERROR RC QP 0x1cd4a wqe[49]: RDMA_READ s-- [rva 0x7f8e37495908 rkey 0xa1909] [va 0x7f06cc06d200 len 100028216 lkey 0x3efdf] [rqpn 0xf8b2 dlid=47 sl=0 port=1 src_path_bits=0]
[1634937588.931040] [dgx13:4085 :0]     ib_mlx5_log.c:170  UCX  ERROR Local protection on mlx5_3:1/IB (synd 0x4 vend 0x33 hw_synd 0/157)
[1634937588.931040] [dgx13:4085 :0]     ib_mlx5_log.c:170  UCX  ERROR RC QP 0xf8bc wqe[32]: RDMA_READ s-- [rva 0x7f999b5e1000 rkey 0x16aa9a] [va 0x7fde77fcbc00 len 99986752 lkey 0xbf4e4] [rqpn 0xf88b dlid=46 sl=0 port=1 src_path_bits=0]
```

### Steps to Reproduce
- Simplest way to reproduce is run Dask cuDF benchmark using UCX-Py:
  - `UCX_MAX_RNDV_RAILS=1 UCX_MEMTYPE_REG_WHOLE_ALLOC_TYPES=cuda python dask_cuda/benchmarks/local_cudf_merge.py -d 0,1,2,3,4,5,6,7 --runs 5 -c 100_000_000 -p ucx --interface ib0`
- UCX master https://github.com/openucx/ucx/commit/5d34a0f5b8a2b0a2211c85b5a7decfa90c2dde7e

### Setup and versions
- DGX-1 with 8 x NVIDIA V100
- `Linux dgx13 4.15.0-76-generic #86-Ubuntu SMP Fri Jan 17 17:24:28 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- MOFED 5.3-1.0.5.0
- NVIDIA driver: 460.39
- CUDA 11.2
- Both `nv_peer_mem` and `gdrcopy` modules loaded

### PR DESCRIPTION
**Pull request by yosefe**
## Why
Fix #7575 
The issue was that whole-alloc logic returned wrong region boundaries, so the registered memory did not contain the actual communication buffer.

## How
- Track merged memtype cache region range by start/end only; drop base_addr/alloc_length
- Assert that "whole-alloc" really returns a region that contains the original one
- Add logging

## Test status
Currently, the test case fails with ibv_reg_mr: Bad address, instead of Local protection error, but it could be a driver issue. Reproducer:
```
$ ssh swx-dgx01
$ conda activate ucx
$ env UCX_MEMTYPE_CACHE=y UCX_MAX_RNDV_RAILS=1 UCX_MEMTYPE_REG_WHOLE_ALLOC_TYPES=cuda \
  python dask_cuda/benchmarks/local_cudf_merge.py -d 0,1,2,3,4,5,6,7 --runs 5 -c 100_000_000 -p ucx \
   --interface ib0 --enable-nvlink --enable-infiniband --enable-rdmacm
```

### CODE REVIEW

**Review by dmitrygx — APPROVED** [review]

**Review by Akshay-Venkatesh — APPROVED** [review]

File: src/ucp/core/ucp_mm.c [hunk 1]
```diff
@@ -126,6 +127,16 @@ ucs_status_t ucp_mem_rereg_mds(ucp_context_h context, ucp_md_map_t reg_md_map,
                 ucp_memory_detect_internal(context, address, length, &mem_info);
                 base_address = mem_info.base_address;
```
Comment (brminich) [inline src/ucp/core/ucp_mm.c:128]: i'd move `base_address` and `reg_length` initialization from lines 123-124 to the `else` branch of this `if`

File: src/ucs/memory/memtype_cache.c [hunk 2]
```diff
@@ -27,11 +27,25 @@ ucs_spinlock_t ucs_memtype_cache_global_instance_lock;
...
+
 typedef enum {
     UCS_MEMTYPE_CACHE_ACTION_SET_MEMTYPE,
     UCS_MEMTYPE_CACHE_ACTION_REMOVE
 } ucs_memtype_cache_action_t;
 
+struct ucs_memtype_cache_region {
+    ucs_pgt_region_t  super;    /**< Base class - page table region */
+    ucs_list_link_t   list;     /**< List element */
+    ucs_memory_type_t mem_type; /**< Memory type, use uint8 for compact size */
```
Comment (brminich) [inline src/ucs/memory/memtype_cache.c:44]: was the intent to use `uint8_t`?

**Comment by pentschev** [comment]
@yosefe as we discussed in our call earlier today, even with this PR I see the error below with driver 495.44/CUDA 11.5:

```
$ UCX_MEMTYPE_CACHE=y UCX_MAX_RNDV_RAILS=2 UCX_MEMTYPE_REG_WHOLE_ALLOC_TYPES="cuda" UCX_CUDA_COPY_MAX_REG_RATIO=1.0 UCX_IB_REG_MT_THRESH=inf python dask_cuda/benchmarks/local_cupy.py -d 0,1,2,3,4,5,6,7 --all-to-all --rmm-pool-size 29GiB --runs 10 -p ucx
...
[dgx13:34831:0:34831] Caught signal 11 (Segmentation fault: invalid permissions for mapped object at address 0x7f54bbebc400)
==== backtrace (tid:  34831) ====
 0  /datasets/pentschev/miniconda3/envs/ucx-tmp2/lib/libucs.so.0(ucs_handle_error+0x2e4) [0x7f5ea4523bb4]
 1  /datasets/pentschev/miniconda3/envs/ucx-tmp2/lib/libucs.so.0(+0x30dcf) [0x7f5ea4523dcf]
 2  /datasets/pentschev/miniconda3/envs/ucx-tmp2/lib/libucs.so.0(+0x310f4) [0x7f5ea45240f4]
 3  /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7f5f4543a980]
 4  /lib/x86_64-linux-gnu/libc.so.6(+0x18ea93) [0x7f5f44818a93]
 5  /datasets/pentschev/miniconda3/envs/ucx-tmp2/lib/ucx/libuct_ib.so.0(uct_rc_mlx5_ep_am_short+0x143) [0x7f5e70aaffb3]
 6  /datasets/pentschev/miniconda3/envs/ucx-tmp2/lib/libucp.so.0(+0xa28fb) [0x7f5eaccb48fb]
 7  /datasets/pentschev/miniconda3/envs/ucx-tmp2/lib/libucp.so.0(ucp_tag_send_nbx+0xacc) [0x7f5eaccc676c]
 8  /datasets/pentschev/miniconda3/envs/ucx-tmp2/lib/libucp.so.0(ucp_tag_send_nb+0x4e) [0x7f5eaccc5b7e]
 9  /datasets/pentschev/miniconda3/envs/ucx-tmp2/lib/python3.8/site-packages/ucp/_libs/ucx_api.cpython-38-x86_64-linux-gnu.so(+0x60e62) [0x7f5ea3ff2e62]
```

I created a [reproducer script](https://gist.github.com/pentschev/7e0c916bfe608dbc4056debf42c80071#file-reproducer-sh), but on Prom with driver 460.32.03 it caused the ibv_reg_mr error instead, so it will probably require a newer driver to trigger the error above.

File: src/ucp/core/ucp_mm.c [hunk 3]
```diff
@@ -126,6 +127,16 @@ ucs_status_t ucp_mem_rereg_mds(ucp_context_h context, ucp_md_map_t reg_md_map,
...
                 reg_length   = mem_info.alloc_length;
+                end_address  = UCS_PTR_BYTE_OFFSET(base_address, reg_length);
```
[the remark this answers is not in the document]
Comment (yosefe) [reply src/ucp/core/ucp_mm.c:130]: it's used for ucs_trace and ucs_assertv

File: src/ucs/memory/memtype_cache.c (hunk 2 above)
Comment (yosefe) [reply src/ucs/memory/memtype_cache.c:44]: no, since it's replacing ucs_memory_info_t which has ucs_memory_type_t

File: src/ucs/memory/memtype_cache.c [hunk 4]
```diff
@@ -256,36 +257,29 @@ UCS_PROFILE_FUNC_VOID(ucs_memtype_cache_update_internal,
...
 }
 
 void ucs_memtype_cache_remove(const void *address, size_t size)
 {
-    ucs_memory_info_t mem_info;
-
-    ucs_memory_info_set_unknown(&mem_info);
     ucs_memtype_cache_update_internal(ucs_memtype_cache_global_instance,
-                                      address, size, &mem_info,
+                                      address, size, UCS_MEMORY_TYPE_UNKNOWN,
```
[the remark this answers is not in the document]
Comment (yosefe) [reply src/ucs/memory/memtype_cache.c:275]: IMO setting to UNKNOWN is safer, since removing it completely is essentially marking it as host memory

File: src/ucs/memory/memtype_cache.c [hunk 5]
```diff
@@ -333,14 +333,23 @@ UCS_PROFILE_FUNC(ucs_status_t, ucs_memtype_cache_lookup,
...
         status = UCS_ERR_NO_ELEM;
         goto out_unlock;
     }
 
+    region = ucs_derived_of(pgt_region, ucs_memtype_cache_region_t);
     if (ucs_likely((start + size) <= pgt_region->end)) {
-        region    = ucs_derived_of(pgt_region, ucs_memtype_cache_region_t);
-        *mem_info = region->mem_info;
+        mem_info->base_address = (void*)region->super.start;
+        mem_info->alloc_length = region->super.end - region->super.start;
```
[the remark this answers is not in the document]
Comment (yosefe) [reply src/ucs/memory/memtype_cache.c:344]: yes, it's because of that (`search_end   = end - 1;`)

File: src/ucs/memory/memtype_cache.c (hunk 2 above)
Comment (brminich) [reply src/ucs/memory/memtype_cache.c:44]: then the comment is misleading

Comment (yosefe) [reply src/ucs/memory/memtype_cache.c:44]: yeah :)

**Comment by yosefe** [comment]
@brminich changed to memory_type_t; using uint8_t does not really improve the size - it's 24 in both cases
```
$ ./build-devel/src/tools/info/ucx_info -y|grep memory_in
    sizeof(ucs_memory_info_t) = ........... 24    
``

**Review by brminich — APPROVED** [review]
