### PR TITLE
UCP/WIREUP: Fix address packing (AMO)

### LINKED ISSUE #4276: Behavior change after recent commit (passive progress)
Until recently, I was able to get passive progress, e.g. as in

https://github.com/openshmem-org/openshmem-examples/blob/master/C/ptp.c

where one rank/PE makes no SHMEM calls.

Since commit 7dc71b3a9b70a0ca3a6e2fb36b67466d0eac934b, the program now hangs.

Interconnect is

```shell
$ lspci | grep -i band
06:00.0 Infiniband controller: Mellanox Technologies MT27600 [Connect-IB]
```

(mlx5 driver).  Same thing seen on another IB cluster.  With an added progress thread it works (as for older MLNX IB mlx4)

### PR DESCRIPTION
**Pull request by brminich**
## What
Fix a bug in UCP address packing (AMO tls were disabled)

## Why ?
Fixes #4276

### CODE REVIEW

**Comment by evgeny-leksikov** [comment]
just for reference https://github.com/openucx/ucx/issues/4276#issuecomment-541211917 maybe this place is better for conversation

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12585/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 18-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/9d01c31b6f8212e2d485d9c3b8c70e5f4f1d5e80/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/650c33f7857c56b3bde4a363bb0cf1c453f05758/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/a2ba0b06d152259a3064f199a8c55aa7b7cc9c93/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/9d77ebdb9d98b653262adff91369584d6b9044bf/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/7b4e2df4a63924de7970d931ebfd2010204e3377/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/b93606d3ca03530684ce34079a17283894c7289e/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/65c1ab8495a4e00ffdc876de8f75c9534efc48dd/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/799f9b744fbc1927137fb7f24d5b2e82ba68d4a6/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/bcc909596466a221f0eac661d33f11a038ad11a6/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/87f58fd861ed17da8fc2a4736d7d738be545cc4b/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/a17b484764dcde4e98315acb1695178a71d0f8ef/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/344c01979f34918bc9e954fc56e60c776fa1eadd/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/6eb304b2cdf2e4f7cfe93e6e3de2854ae9de5f1a/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/a700ac39738677ab0bdc4d1769d00bddb061aeb6/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/97e8d03c75acd1c81e7aaeb26ab09683d8013a4d/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/3a6acffa8ce8f3bec4201bfa5d3e378eb0aa2377/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/6abbefb8466aadc6565813a860de69acbcd8c374/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/46645f8ce311eecc254afe6f5cbfaf3bc2c904b7/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/6883c010ee63a109173ea0b86e181a8c9dec4539/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/f5e8e9d346148bd8f9c030ceb36ae7e6932ae3f7/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/e12076da9c71e894a8f02ad24b013c0cfbb1fdd7/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/494bf97ba502a5237d3dc1b4592e998816a52ee6/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/23ec4206a64d3584d3c599a36a7f64c3a7b586ce/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/b60f93aa7aa62be9baa08f26fe8dc663afd08ac7/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/8ca3cf9e5a98ad57a32979f9ec2ccfbab3c9a5dc/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/0a8523054eb76ac6fa02b2eab4a55527388583c8/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/bec98e67a28dde9958f7af3379dc776a0676df31/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/65b45d69a596067fc36f8017cf1c2b6e57e2baae/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/3eeeb3582836eed9d66c85d91e6bbd2d/raw/ec6a932fc4066f8815c256fbd0310058b17bdafb/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12592/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 19-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/064cd18106a54aa58fb5e175b2fea038e571174b/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/c10250bd5470b8091b98dec416ebe1657b41a422/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/bfb81f245b048e2c811c8d01073016508a0215e9/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/acb3aea580efeb0e3233c0b12b3b766d21b4a095/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/c61312f465618a7717d2137b3d04e7456c54291d/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/658cd191a90c0da21327e5601bc2ad8b43f5530d/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/101010e7e9e18e406f8382972ff1fd30885476f8/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/36570a048c46d17090ece3713ec0804342a1ebb3/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/f03ffc246214ea15954c6dc24fe363943f36823b/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/0368fd29e479e7965ec0fda6334dd534bfe51a78/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/e2440a835d29dcf56a0b8b30f07217a520bef56a/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/162cccd15a907711d387f93fa0c4ec14ad19f6c8/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/91891fc66cfff5479ca3080a827aef1df3ae4d74/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/de243a8dc7e1cdb15e03c7a1f50c96ef4542658e/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/440f67a7145e0d0051d4e6e53e7b21b6fb88b7f0/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/9c366e19f81ac04bb7196b9ca1ba4479aed9bed4/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/b0be4d320ab9d885829a5b9fb50e727bf4257f87/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/9dd4718d22192587341d6f53307fc1efa7ead219/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/625db2ca778f97b127bf495723620c520dd3b510/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/b539d646690ff6e270a3b252ee7b01a54ec6955b/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/856d8290d7a5ef1496670690a7e699efa9a8037e/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/fe05668b29bd53797036d11daae9dda018ed3601/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/d0e1854258b9f1ae6566781984a13aac30470abf/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/d6e9720231a65f781f6633218041a37ef82580a2/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/eb07d5f57da9bba1c7f3b9329f8a57a83124dec1/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/4f51996976775a0d944d218e127c23128a1ca81f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/c44b9697ef2d26c6be7da7d4d48e3df701e5cebd/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/22b1a4eaeb61c044fd27cfe569c63af9ad2a2fa6/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/9b2c62c80733f069e019e4880b900687/raw/a6a9201ae5d609178daa1586e9fe4720e4fb2969/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/ucp/wireup/wireup.c [hunk 1]
```diff
@@ -189,9 +189,8 @@ static ucs_status_t ucp_wireup_msg_send(ucp_ep_h ep, uint8_t type,
 
     /* pack all addresses */
     status = ucp_address_pack(ep->worker,
-                              ucp_wireup_is_ep_needed(ep) ? ep : NULL,
-                              tl_bitmap, -1, order, &req->send.length,
-                              &address);
+                              ucp_wireup_is_ep_needed(ep) ? ep : NULL, tl_bitmap,
+                              UINT64_MAX, order, &req->send.length, &address);
```
Comment (yosefe) [inline src/ucp/wireup/wireup.c]: maybe define a constant for UCP_ADDRESS_PACK_FLAG_ALL

File: src/ucp/wireup/wireup_cm.c [hunk 2]
```diff
@@ -36,12 +36,10 @@ static ucs_status_t ucp_cm_preinit_client_lanes(ucp_ep_h ucp_ep)
 {
     ucp_worker_h worker        = ucp_ep->worker;
     ucp_ep_config_key_t key    = ucp_ep_config(ucp_ep)->key;
+    /* Do not pack HW AMO TLS because ucp_ep lanes are bound to specific device
+     * which may be different form worker->atomic_tls */
```
Comment (dmitrygx) [inline src/ucp/wireup/wireup_cm.c]: `form` -> `from`

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12593/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 21-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/9bb828e94cf2cdf794ce5be079f2169b641e8894/_main) | :x: FAILURE
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/30e6624eb552dffb7918c41c33361bd602304709/hpc-test-althca_W3) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/e8bf0d3057f6c80f2d5d7f77c45fc0c642440ac4/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/dc27820e5f0c5e597cf9516c19b0343afcccc166/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/280aa4d512ce43abcd0b2873be2465094490659c/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/757e04855dd2a80ead1e544efa038c6a39840b97/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/e93cdf9eeb49de146210d80a0565384dd28be3ae/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/7ae602cfef2dcb39d44e8b8eed327ec88ea38363/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/48c9df21446645af34bf1b2f22fdc5d43d0a2541/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/362de2c8d7dd17e8498105dd9d40d9932a0153f2/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/95e510957d44595ac185d5af576ac10c21382bd0/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/b43c73725f88cb68a05b8db286d2324753d0384a/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/fa6033414bac6f81054fc5eb84468d9d4de6009f/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/51979e7218c7b63aae255ff25bb0e7eb4b797fb3/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/f40da58c6cee822da8e8c1bd690ef7e932ab11bb/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/92a5197702897029a380eb777c44094100a9e195/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/0dfd7efcba09db3efa0c67f246fe9f590470f8b1/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/6a0f478c8dc5065ba15b5a915ccbddb6e4746ba5/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/9e1e708a4d826f3029faf091a3267592810c5f52/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/90625ce512515b958a6b7d59bb45bc65e44f5b37/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/7a927bcb9135295b46f4259328456d734bb03ada/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/0c65f670e2a0cc38dd3415f440504aaa2bcd4966/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/ce7aa98797a8dc4b314552de8a125c854fe574a9/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/63eea702c4434d9b79af49e2fbc443a2facd9eb3/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/a2dcd58457e544aa10c3c4bd145f6a1267b34139/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/aa25bf8ddb429b6ab405d20b633eaf45f9873c8c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/1530d1c03189963b314ddd215ec2dd1a339f8a60/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/7614f8c38fc792724d4231ef98edb7458d7b77d3/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/79e61e1b1a5f28e89961e72e84289155/raw/7f443d808dfc6c5ba5113bec08523c6eee236707/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
one failure seems relevant:
http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12593/label=hpc-test-althca,worker=3/consoleFull
```
11:19:34 [ RUN      ] shm_rc/test_ucp_wireup_fallback_amo.different_amo_types/0
11:19:34 [     INFO ] Testing 1 number of EPs
11:19:34 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-althca/worker/3/contrib/../test/gtest/ucp/test_ucp_wireup.cc:1115: Failure
11:19:34 Value of: use_device_amo(sender().ep())
11:19:34   Actual: false
11:19:34 Expected: should_use_device_amo
11:19:34 Which is: true
11:19:34 /scrap/jenkins/workspace/hpc-ucx-pr/label/hpc-test-althca/worker/3/contrib/../test/gtest/ucp/test_ucp_wireup.cc:1115: Failure
11:19:34 Value of: use_device_amo(sender().ep())
11:19:34   Actual: false
11:19:34 Expected: should_use_device_amo
11:19:34 Which is: true
11:19:34 [     INFO ] Testing 257 number of EPs
11:19:34 
[  FAILED  ] shm_rc/test_ucp_wireup_fallback_amo.different_amo_types/0, where GetParam() = shm,rc_x,rc_v (631 ms)
11:19:34 [----------] 1 test from shm_rc/test_ucp_wireup_fallback_amo (631 ms total)
11:19:34 
```

**Comment by brminich** [comment]
yes, just fixed it

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12609/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 22-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/60757fa857885e4703b694c017f90341ce47dfd1/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/563f40d86cc0a42c0838c581b1fb1c4c1b7f1eec/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/f9421f501b37ea11f60e5532423830d8897ec95a/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/6ed7d8159ba78edbb7a037494529a9e9fada7eb0/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/4769d8f89622ced684f07bd2c46413d8b1bf087e/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/e0c61310a5ea7f1f70d5209609dc22e5a4b5b9c7/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/6de307647af3ffdf8f24945b9d8aabc372b4c713/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/08e3b8319804f4fd66ea20f0b000b3e937c9dbb4/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/2da52c469c69b4ef3a84e60b775d08269addcaf9/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/8047746725d152384511c37a9bd55d9fa452d7bd/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/5eca7a09367bc915d75d24a4ae49a940ac7f8594/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/f4f13e4127c78917fdc6081cc9363cde59221ca0/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/09e4c9b5dc47830166795fe75b70a49da28ef182/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/075496e7ea77698a8d54d703e38cf4d58d1262ac/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/7cf1232769bd807de812bc9f13194175ea03eeec/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/6e9cf215408e54640b120112fe7c5dac35dd916f/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/03a78108565365fe77866047732924c3be9bd23e/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/fa79e4ba2758edc6935b6439b20821128d7bbfa8/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/d535b9030a3d235f6a601ff5512b8b5dc6a40729/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/6fe26723b58f2fb076cdcab8c9cdebdacd18de07/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/65e57c2960d1e45a9ca4a0153a2966def7636c1a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/c5dc8dc577dc3fef12b75fc099dcb1b89d91c6d0/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/e006a0c2b108ff323df12076e3165e8fdfc87dd0/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/9a0f14a1e942df89553da579511ff55498699157/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/4a5cc83116b120eb5deec440e6193fed471aa2ea/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/f64be8209297c6246f26703d066c9b1606aff661/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/a5aa7b1b5f75af8d423e60892fb1efc5dedfd1e5/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/f04d30ef779b01719f1bb533a999d8072c8ab45a/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/7cc831290e3d0d73dbf40a50a6902b94/raw/fe188c4166b325ac1a20dafe466afbb249b42a77/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12614/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 22-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/91818e607d05b6842bd10a424d4c082d822e6480/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/5e3fa66fb71417fc15bd8ae4aaf1412ba09fdea7/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/93e3becc4d298ab42154ed6d3480f81977e06469/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/b7270fd9ba6da039c8f911592be1aff24114505a/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/2a322e3e6540adf264f5c78588e595c19924bf31/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/87327a30ec6d7b8da56cf53c45ac585cc3d2c1a4/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/21c04c4b3685d04caa141f907da3470e9173a48f/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/e88f584951080cf98dc00d28fc2c57b0f02b0a46/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/7d6d7052a65786c29e407af96520698ad939ceea/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/8d119275db5e8c70cc8460be716736072f9bc554/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/1cc3401b3248592af4343b18ff0ad6a5a93b9811/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/c785c58c795acd054eaf9788d076b56ece1bb829/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/3ccc7e9bb6363c02b6130a40424eff7f49119fef/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/1b4ca121b7c8794867245a8c66c6a06f03d6b301/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/9b937b340ae4e94957a7aee262a0b20e3a22cbb0/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/f6f5a26309bf5d65515bf8ce1f9f279c5222ccc4/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/e65841676ac7ab088d729b5fb7385ef6f715142b/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/7e909537799ec1b00748577ae3f7a9515f25404f/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/063cfdce2cb0047e2ba0dea231ce6d32b4b69fa2/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/479f5b98742dbd7f23be2fc219d77e1d43b015d4/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/2314ae7f03b02c2149b4a38e1cdb7e2d59d136b5/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/6d5822064974857b7308bb5bd77a716725b3ab58/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/17d45791fa612bb412046239cc5f998207b233c7/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/e3c5519e696814122f3aa55b0a20b65ac423eeb8/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/3740d12009704d799c79ea53be2e89fc26dd56ca/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/ce5773b10c7aacdc5ea43e11ff5dd15e0bd493d7/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/c877b9dc954b8952fac902254971fc43c51de5a7/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/fa346dcf42fe574ea5e3cf94c1da567e122ab581/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/aad8528a5dff25bd09452925521620e3/raw/b42d3deea7c027bbb3d6a932c55b3d0f4474afbe/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by brminich** [comment]
bot:bgate:retest
bot:pipe:retest
