### PR TITLE
UCT/RCX/DC: Fix HWTM unexp rndv key handling

### LINKED ISSUE #3827: [mtt] crash with HW TM enabled
Configuration
```
OMPI: 4.0.2a1
MOFED: MLNX_OFED_LINUX-4.5-1.0.1.0
Module: hpcx-gcc (2019-07-02)
Test module: mtt-tests/hpcx-gcc
Nodes: orion x8 (ppn=28(x8), nodelist=clx-orion-[050-053,056,058-059,061])
ucx-hwtm-rc
```

MTT log: http://e2e-gw.mellanox.com:4080/mnt/lustre/users/mtt/scratch/ucx_ompi/20190703_053156_10551_407297_clx-orion-050/html/test_stdout_cqV5_S.txt

Doesn't reproduce with `UCX_RC_MLX5_TM_ENABLE=n` and in debug mode (with enabled HW TM).

Cmd:
`mpirun -np 224 --display-map -mca btl self --tag-output --timestamp-output -mca pml ucx -mca coll '^hcoll' --bind-to core -x UCX_NET_DEVICES=mlx5_4:1 -mca osc ucx -x UCX_IB_ADDR_TYPE=ib_global -x UCX_IB_REG_METHODS=rcache,direct -x UCX_TLS=rc_x,self,sm -x UCX_RC_MLX5_TM_ENABLE=y -x UCX_IB_SL=2 -mca pmix_base_async_modex 1 -mca mpi_add_procs_cutoff 0 -mca pmix_base_collect_data 0 --map-by node /hpc/local/benchmarks/hpcx_install_2019-07-02/mtt-tests-gcc/installs/3vdU/tests/mpi-small-tests/hpc_tests.git/mpi/misc/fca_shm_hang_test`

Output:
```sh
Thu Jul  4 12:02:33 2019[1,0]<stderr>:[clx-orion-024:30990:0:30990] ib_mlx5_log.c:139  Remote access on mlx5_4:1/IB (synd 0x13 vend 0x88 hw_synd 0/0)
Thu Jul  4 12:02:33 2019[1,0]<stderr>:[clx-orion-024:30990:0:30990] ib_mlx5_log.c:139  RC QP 0x1e5 wqe[0]: RDMA_READ s-- [rva 0x7f19a0 rkey 0x6269] [va 0x817db0 len 3664 lkey 0x37f14]
Thu Jul  4 12:02:33 2019[1,0]<stderr>:==== backtrace (tid:  30990) ====
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 0 0x0000000000048a38 ucs_fatal_error_message()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/assert.c:36
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 1 0x000000000004d08c ucs_log_default_handler()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/log.c:140
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 2 0x000000000004d1b4 ucs_log_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/debug/log.c:193
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 3 0x000000000001c2d3 uct_ib_mlx5_completion_with_err()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/mlx5/ib_mlx5_log.c:132
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 4 0x0000000000029fa6 uct_rc_mlx5_iface_handle_failure()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/rc/accel/rc_mlx5_iface.c:206
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 5 0x000000000002b22d uct_ib_mlx5_poll_cq()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ucx-master/src/uct/ib/mlx5/ib_mlx5.inl:38
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 6 0x000000000001e2a2 ucs_callbackq_dispatch()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ucx-master/src/ucs/datastruct/callbackq.h:211
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 7 0x0000000000003717 mca_pml_ucx_progress()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/pml/ucx/pml_ucx.c:510
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 8 0x000000000003717c opal_progress()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ompi/opal/runtime/opal_progress.c:231
Thu Jul  4 12:02:33 2019[1,0]<stderr>: 9 0x000000000004b885 ompi_request_wait_completion()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ompi/ompi/../ompi/request/request.h:415
Thu Jul  4 12:02:33 2019[1,0]<stderr>:10 0x000000000008c07d ompi_coll_base_reduce_generic()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/coll_base_reduce.c:186
Thu Jul  4 12:02:33 2019[1,0]<stderr>:11 0x000000000008cac9 ompi_coll_base_reduce_intra_pipeline()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/base/coll_base_reduce.c:416
Thu Jul  4 12:02:33 2019[1,0]<stderr>:12 0x000000000000570b ompi_coll_tuned_reduce_intra_dec_fixed()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/tuned/coll_tuned_decision_fixed.c:420
Thu Jul  4 12:02:33 2019[1,0]<stderr>:13 0x0000000000001819 mca_coll_cuda_reduce()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ompi/ompi/mca/coll/cuda/coll_cuda_reduce.c:66
Thu Jul  4 12:02:33 2019[1,0]<stderr>:14 0x000000000006da0a PMPI_Reduce()  /hpc/local/benchmarks/hpcx_install_2019-07-03/src/hpcx-gcc-redhat7.4/ompi/ompi/mpi/c/profile/preduce.c:139
Thu Jul  4 12:02:33 2019[1,0]<stderr>:15 0x0000000000400af4 main()  /hpc/local/benchmarks/hpcx_install_2019-07-02/mtt-tests-gcc/installs/3vdU/tests/mpi-small-tests/hpc_tests.git/mpi/misc/fca_shm_hang_test.c:32
Thu Jul  4 12:02:33 2019[1,0]<stderr>:16 0x00000000000223d5 __libc_start_main()  ???:0
Thu Jul  4 12:02:33 2019[1,0]<stderr>:17 0x0000000000400969 _start()  ???:0
Thu Jul  4 12:02:33 2019[1,0]<stderr>:=================================

```

### PR DESCRIPTION
**Pull request by brminich**
## What
Fixes #3827 

`uct_md_fill_md_name` is used in both regular  and HWTM unexpected rndv flow (to generate "packed" rkey).
Check whether MD name is supposed to be packed inside this func

### CODE REVIEW

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11047/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 37 workers (click for details)</summary>

**Note:** the logs will be deleted after 14-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/eae793555575c7584cb58d488b56d8e7488cfe32/_main) | :x: FAILURE
[hpc-test-node3_W3](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/d501b3a775274312247fb9874ca586813df1c843/hpc-test-node3_W3) | :x: FAILURE
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/512db3007307ec8b35260c5bb52bce71f510026f/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/dd5ace8ba48aeb1c9c36ce06c247df1b00319164/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/0879f28cf459d1e629a813237c42ffcaaa3a4d44/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/ee889f202882cc9280fdf993680d4ab142b8082d/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/6bc1a8673ae346f7315f699fa521da81e5a842d5/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/5cf63d76a179f10e7ade5f86f45720bfef5709f1/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/633ae96004c33b71ef360724cc77ab0d5c09519e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/93750113b09c529f9432c838a70e87ca03b3e3a3/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/af214268582dde7cc0a79d32b06dc9fb59326a27/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/2a3944d2ed40a517d748de31e7eb7d1d3530d8bd/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/1f0d6ecc4ffe2b552937322d56dc3cebddb313c1/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/a48c47943bdfa97182e0e028ce17bb90518fdfed/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/12516836f24f1f27a2bb0828482074e3dfb427b5/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/c147c05928763aecea98a87a7438fe41504a7020/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/e232201625a57a29168bddd27485b695b2f89d61/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/555fd06b739157a76c599842c9d1ce5652c99130/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W0](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/8905efa2506adf7d1c5927d3e69713f20d544a7b/hpc-test-node2_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W1](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/e2bcf702adc4f9875178df55c052309c5a921346/hpc-test-node2_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W2](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/0097247b838de996ac30d4e9b6ff0556f27f8da8/hpc-test-node2_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node2_W3](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/fb757ba146eb982e426da58cb63b52f339bfb29e/hpc-test-node2_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W0](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/6e21c39e07d97ebc25f56180637ac294dbd4fa16/hpc-test-node3_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W1](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/be32f235dabad91b8839965334ae28a2f0690097/hpc-test-node3_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node3_W2](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/aa8ba2bcb43390c21f5c85afec583f67a5535ad7/hpc-test-node3_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W0](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/67a06bf2b276fc3ea76b52d039a983878764a2b1/hpc-test-node_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node_W1](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/35a12f65b0ae85cd59435cc724083b75640f2070/hpc-test-node_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node_W2](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/b72507c9bf45c21f4c79dc71c179dd63772655f9/hpc-test-node_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node_W3](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/699294690e2ef1b2e303380dcda90c8bb61d8105/hpc-test-node_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/0075666ecccd77b04b84f823041363892e41666f/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/706c3a9cc07fe8c0a8038eb96fbdaae8c67ebdfb/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/54d6f3af8efccb6e0254852613db8d4af65d1856/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/530d52b6be58d5a0ebf7bc6828950d3946368a67/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/b3625aa2d0be27cb7b5f31dc800f856179f7d46a/vulcan-jenkins_W0) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/15460f51f5e1ce89b0c9788a1247be994a4c029c/vulcan-jenkins_W1) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/a8752b9de4ca1934f9c8b602e310ac1419722a67/vulcan-jenkins_W2) | :heavy_check_mark: SUCCESS
[vulcan-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f9c85ad5a59dec1f7a15a4aea1f57d75/raw/45c085d122a19e0631a763904986cc80c69bb2e6/vulcan-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/base/uct_md.c [hunk 1]
```diff
@@ -333,11 +333,7 @@ ucs_status_t uct_config_modify(void *config, const char *name, const char *value
 
 ucs_status_t uct_md_mkey_pack(uct_md_h md, uct_mem_h memh, void *rkey_buffer)
 {
-#if ENABLE_DEBUG_DATA
```
Comment (yosefe) [inline src/uct/base/uct_md.c]: can we avoid packing rkey in release mode?

File: src/uct/base/uct_md.c [hunk 2]
```diff
@@ -346,8 +342,9 @@ ucs_status_t uct_rkey_unpack(uct_component_h component, const void *rkey_buffer,
 {
     char mdc_name[UCT_MD_COMPONENT_NAME_MAX + 1];
 
-    if (ENABLE_PARAMS_CHECK && ENABLE_DEBUG_DATA) {
-        if (strncmp(rkey_buffer, component->name, UCT_MD_COMPONENT_NAME_MAX)) {
+    if (ENABLE_DEBUG_DATA) {
```
Comment (yosefe) [inline src/uct/base/uct_md.c]: given the change in uct_md_mkey_pack, shouldn't we do ' rkey_buffer += UCT_MD_COMPONENT_NAME_MAX' unconditionally now?

File: src/uct/base/uct_md.c (hunk 1 above)
Comment (brminich) [reply src/uct/base/uct_md.c]: I moved the check to `uct_md_fill_md_name`, because it is used by both: normal packing function and hw tm one.

File: src/uct/base/uct_md.c (hunk 2 above)
Comment (brminich) [reply src/uct/base/uct_md.c]: no, the logic left the same, the check was moved to the common function

**Comment by yosefe** [comment]
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11103/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/3132383a6fc51b2c031133c7f41bfc61fab5692a/_main) | :x: FAILURE
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/0c8180d9dc06ef94ec2d3362d3c285c3204e6080/hpc-test-node-new_W0) | :x: FAILURE
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/3f865f14b3275f43ee8b4e444c918d5c74166891/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/07b19c6ecaf56f236fd54817e4a1cbbc7f2931ef/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/428b8bf4df48ff206d1d4a013440909b0f0d49de/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/56e625d58bdac9ea4da8c906e8a3133d61c93e29/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/3278cf149ecad08a2221430e3871437eec7b9fad/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/5dad97f9c3bc36afd29a33933405160b7f02e46b/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/903a3bc2e0a916f3330999d2e8a94c8c3f7ed705/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/a231259abff19076b71e631bda98f342d73e9854/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/464f23f31e1ec90219ae341268347624afb5ddf6/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/04b911cc9f691ed26ef8cf5f67c4012fa184852e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/417c7f8f4f311b3f9e338c6f922729f66d08e529/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/438daa495847165a5c2a870c7767219a3c42f885/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/dcb10ef589fdcd089f86f1681dec7edfff9f71d7/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/89c6553ef9ec7986f59eb97a63a5b74088e742cf/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/3fa015ecc21dc78471d53a9c4a6f0371986df2e0/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/6e38bb79874ac884a50cc20fd8c066c71680d8f8/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/fbdb5e20d66174c4a14f2888969db62c4441e638/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/954018f69747d17f81c9da7fd4dbed7db19cde88/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/14981bebfac9dafc1b2c2874dfe9c519d0a62c42/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/45f98aac404825ff61b87150cb789c7e5c1b509a/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/34bb9e4c422f63f144501c28879a8e41fc71ab25/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/99ac470c1a51d3dc349a597304591158247c4f69/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/b679f2aea01b60acb60280de07d36585456021fe/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/a72e5b92a927761e111b3a845b90901f46f63ee3/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/6a16c9d7ecff03ab4514b0ceaab7d0ab14b7146a/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/737630a09cb6d7e3a7a89daa14f0f4a93910c020/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/684e61587ca848fcf89343ef975738a5aee20d9f/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/2a1e686d1bc32666d375fb157b09a5ba1d0d7d2c/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/8c94852f2cf751663a36696d98ea65c70d76ab51/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/8f1f50b932c1f63f3f1c40c62832201d244ef4d6/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/b7bb9b78681d1fca7243bd91e5d56cfa/raw/2719951b7249af9e762578dfc2dcee6011c25aac/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by yosefe** [comment]
timeout on perf envelope test - checking if it's reproducible:
bot:mlx:retest

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11113/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 16-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/e66fead98e5a2a4c6baeb29e6b6d00563a6c21be/_main) | :heavy_check_mark: SUCCESS
[boo31_W0](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/8bdb090bf4a72503bb92ae8c35935f441f916935/boo31_W0) | :heavy_check_mark: SUCCESS
[boo31_W1](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/22705374320cf99766e2b20e1f0df4191b7876c5/boo31_W1) | :heavy_check_mark: SUCCESS
[boo31_W2](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/e34582c9a2156edaf9128f2e845982905f1e37e7/boo31_W2) | :heavy_check_mark: SUCCESS
[boo31_W3](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/a753ec786a7ec99daf9246bf21e97fb231302fc2/boo31_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/5d274c99ac19b2f0530d5042769faf5c95e2b100/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/593d2bed790cc7f02b44517a9d452f08555e6d5d/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/ac3ef33b092552d6546a6b7e3737efbb5ae83c1e/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/495801b819c722ba6665ce02efb74be53ba426da/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/1d5aeff5662710719dab6e7fce63946311f69e65/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/1d19cb225a60623615243d7fc409938739745c7e/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/4bd4e078e47b4642bdbea7d3bd7ffefd5a3283ed/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/bf7934b07a77b10aeb2a9b7edd30ba8ace63c553/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/b71b780d0b726d5702b98f4f39d729ee555b68b6/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/dc129227071def48e422427d07f3136a96f46dc7/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/0ebbb71f026bf5c1437e3fbd2719bd76b6807371/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/10073636f029907c96aa547307ac31a9c11c3fa5/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/228bc2e0ca1a1c7d767c6dc2d31364f20a330a37/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/ac035fb3695f1e12f30f1179e18605f34073c76e/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/9ecf5780c255344364d2ad4a6a119c76a28aaf05/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/9ab2510109345902321b15036123c05172c66fa5/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/e926268a5bb4430e0424322e8aadd70558022851/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/7636c6b3a432a4a4363c1809c79fa3e97a14f4b5/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/4b66f0739ed4be22661353da4eee94d1e0ac986d/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/12a89a4315dd364deacec28cebee7d972e2c25d9/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/c3790dd0927fbd281370c0e47c34d639203ccb91/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/a022a15c136549cf75fb5975d1be9b98dcbfd255/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/2840c39111e05b5f45e5249b4163f0a2928d40f6/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/0f414b0bf8d1004e87542ba3fdab9f4115c55455/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/4c4f002d62c310db78bc4c9605356e5e32953e10/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/566a56799ed96fbfd260023cbf0ea7af1aef4b2f/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/9a2fab3e7649489e9cff1b0bcb95ff673ca77e81/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/4902666725cb2c2005b2c81719d763d3/raw/6eb644350d0fbc1d25a98ef05134d6422e359db3/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/11365/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 33 workers (click for details)</summary>

**Note:** the logs will be deleted after 26-Jul-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/90b47ff78470a3812b8872b1f25586cbcafc23a8/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/c56a598547ca396395b6072db703164fe05b3320/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/047bc7996028112ddbba17ec139a9a81f46e6382/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/45f4b2e1a8debcecc1789c401d4188be750e3665/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/bcdf76735ac56f048c0aab7748fe35785895bd99/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/c6abe852cce4cfddbfde54957a52f3bb2ee94c68/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/e5411111d073a17c0645626fb55e786158cc54af/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/8083fe756b79177f63075f83bb80c213adc401f6/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/61188f16c8743c38fc371cad852d08125f631d91/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/7665956933c0d409a75e58993adcd4c8d56bc5f8/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/535f37fa7f46af68aab42548deea97bff95326d8/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/67c5098694dab54a3053588049e942cb57897e09/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/56d6a6dbd18e98b690ebf0833e8c5475e75d1b77/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/372365c658b84dc246298a19431e86cef3929df1/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/33ccf00990ee8fd6ff4ef30e022606612bc59dee/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/9df0dcb198290bf172291fab49d42a042bc2c4d5/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/b2b3772a7dbd7616624245ce863faa08eb7c9cb2/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/f32ae9c4a36c6a93b3e52b391e53cc177548658c/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/f51beca3cdd8dd319ad2493f4d3f9a9cb98692fd/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/5bd5947e7cbbd68e96b399a655b617bb2635f5a3/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/a3ed13dd5ff1281049ac3a1f36e643c792051220/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/d0540c6aa830479e89aa1b0a1dce104843eb27f1/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/b67acf0eb221e782b2eab66a01f02b4334a35509/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/d907ac760077af4926d55308fd4207200d190dfb/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/f7498cbf1edb203c932af6e919d31cb6222e357d/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W0](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/e2952e67d3036faadcdf5eb25fe37aa2438cb66e/hpc-test-node-upstream_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W1](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/7b895cb8d6acc073aab0f5144a954532945b145d/hpc-test-node-upstream_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W2](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/df04b22a92985b896c8247e6e0b79bbe49c13993/hpc-test-node-upstream_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-upstream_W3](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/81f01398a2d7e6b9221734f00e70fe7d25b6c3ac/hpc-test-node-upstream_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/20d9ba4be06c18dd70de12fc992c30887031c7bf/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/2998e5b74e3f15c0e2a6af72b5198e2480bc7594/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/bae72ab13d93d695e05bcca84aa0ef11003af49b/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/cb25f01d1b7797da7c7419bbdf91c96e/raw/98ee08cd336f084a59203e93cc9c8256f27e37a0/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: contrib/test_jenkins.sh [hunk 3]
```diff
@@ -1232,7 +1232,12 @@ run_gtest_release() {
 	export GTEST_REPORT_DIR=$WORKSPACE/reports/tap
 
 	echo "==== Running unit tests (release configuration) ===="
-	env GTEST_FILTER=\*test_obj_size\* $AFFINITY $TIMEOUT make -C test/gtest test
+	# Check:
+	# - Important object sizes
+	# - Unexpected RNDV test, to cover rkey handling in tag offload flow
```
Comment (yosefe) [inline contrib/test_jenkins.sh]: 👍
