### PR TITLE
UCT/SOCKCM/EP: fix error handling

### LINKED ISSUE #4207: Failure in sockaddr/test_uct_sockaddr.connect_client_to_server/13
happened here: http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12376/label=hpc-test-node-legacy,worker=2/consoleFull#1664427763b7949d9e-3f09-4d9b-9be7-3ff694c6afcd

```
18:51:48 [ RUN      ] sockaddr/test_uct_sockaddr.connect_client_to_server/13
18:51:48 [     INFO ] Testing :::59820 Interface: ens1d1
18:51:48 /scrap/jenkins/workspace/hpc-ucx-pr-8/label/hpc-test-node-legacy/worker/2/contrib/../test/gtest/common/test.cc:265: Failure
18:51:48 Failed
18:51:48 Got 1 errors during the test
18:51:48 /scrap/jenkins/workspace/hpc-ucx-pr-8/label/hpc-test-node-legacy/worker/2/contrib/../test/gtest/common/test.cc:269: Failure
18:51:48 Failed
18:51:48 Got 1 warnings during the test
18:51:48 
[  FAILED  ] sockaddr/test_uct_sockaddr.connect_client_to_server/13, where GetParam() = sockaddr/ens1d1 (13 ms)
```

### PR DESCRIPTION
**Pull request by evgeny-leksikov**
## What
Do not handle endpoint failure twice

## Why ?
partial fix for #4207

### CODE REVIEW

File: src/uct/tcp/sockcm/sockcm_ep.c [hunk 1]
```diff
@@ -91,6 +91,16 @@ static void uct_sockcm_change_state(uct_sockcm_ep_t *ep,
                                                uct_sockcm_iface_t);
 
     pthread_mutex_lock(&ep->ops_mutex);
+    ucs_debug("changing ep with status %s from state %d to state %d, status %s",
+              ucs_status_string(ep->status), ep->conn_state, conn_state,
+              ucs_status_string(status));
+    if ((ep->status != UCS_OK) && (ep->conn_state ==
```
Comment (dmitrygx) [inline src/uct/tcp/sockcm/sockcm_ep.c]: minor: Move entire 2nd condition to the next line?

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12490/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/13fcd408c2e8d7339aa862f1758a340ba38dceff/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/25b725f16be4dd3677eb976b7643f85f0a465b0a/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/251d0af669d33e29788ffc1f32c6393814c4f071/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/c12e935c06149727009dd3d6b6d0819d8d6acccd/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/cb362c52469682697d2ed16002df9f94759a9117/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/dacbf792d25b3d6767ff2f3330fcb572b3a59da7/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/9bf93f221dcbda89068ad57aa91cf7c97a52399a/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/6171e25650aaa3a8b2f56415b20ac1df7516ef41/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/1a7790b9fd745af0428766d68b0d58cb94934ef8/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/2ea061964f3af692093c78fad8d8239ccab29e8e/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/62aa7747db123d902ac394647044fd4475d36fd3/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/1b4132c6328cde4c86cb547fd0cdc45b63d884f7/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/d018811e7ccd0b7c475737f284688cf1ffb4ffdf/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/3b415542e93e1ec48a242ac2ea9dc553e7a64e6b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/822afe290c6f71540c8b83e18a4d617c7875f8b1/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/592aa9fd33d830986d78286f71e8c80029198ab3/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/6702f75c27579a8671c0469361bae1df8f1d3bee/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/b2674cd7690bb97260c65582e70af03c8ae513f1/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/97a041392ae002e9b8d1d474874b37ec213fe15b/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/502d588ca1ea37e11c644014f157e9dd8b6a61b1/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/177afc70135be8bf7ec75d13a8110066086ccb1c/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/bb0f01a5ad9c4f75f83862362deb96384a6be2af/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/dfbf511b67a60dbf657033ea695c536f928248e1/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/3e01226311cec9a63f7e82e2e99582d26b1dd216/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/cf91cc71d74258b1683ac647db80476eee2d9766/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/03567b2689dbd4db727a60bfc8a88cdd3d43661b/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/ca9c54f8262a9e6325c0157c67f7fcabe5e97aaa/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/1c62b47a7890b1d285644e150ca5b83f62f8d6c0/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/f34d34d5a1ef987625224e441230f43d/raw/39792ddd0986db4abcbede98a36a2adc1da6805e/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by mellanox-github** [comment]
Test FAILed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12491/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>FAILED</b> on 2 of 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 09-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/1b2480ca2e6e6db5f9d18d08039df58e02a06865/_main) | :x: FAILURE
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/b6cd4b2bbda142752cd18bde163cd8c4b335ff5d/hpc-test-node-legacy_W2) | :x: FAILURE
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/ba52ab28ed977c0b6d9539d49170ea3cf03253b3/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/f3d0b5fbac54609feba2cb6607f85d209faf9a32/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/4c62e349523fbf5a6bf35b37417197cea5ecb7ae/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/ed745a4c9a452c6e8d23c81109f19e591f8ca337/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/d69d924e4eda5166f25c0e31376b28d04899a55c/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/c95cf16154266bfa79741cce9043811359718291/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/ee52a64075bc3a22f409d34505224eb855f5e3ab/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/4aede8f56e23fdca04dc3acf13c2df2aa1d59bbf/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/a500a8ed25fb06123da4f0acec6eccdaaaf4666e/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/8e50d87c55ecd6b04a10917a859bdb5fbb34e307/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/87df6b3e2717dfb3327451be6636ee9a1549fdec/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/b90ceb1d5328c1d06b7ba33ed86d693a4b496a99/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/d385ada12534fcc163e6a9ab3e947e09a2a8a5fe/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/522883f6bc3a9811e4a063701b05dee44a182769/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/bd240999d208299b404fe48087bf2826b5b94517/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/e59898ed003de5e4c952bfb060fd8dfe118968b3/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/8ef79fe59039702b4d62cec4918fb6bba27245ff/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/b456ac37142f3ef1a66a5f4d3a6deb97ea371a0f/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/b88242d2b08d9ad0a26b80baa7b40a4f61879871/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/2935eb06aa5ddc63f41f0e251599904d9ff8da43/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/29a7fb50165152426725602ea8b4b86b2ec73194/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/79183c6c9b4912364ee97dcb02d637032f78cb51/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/69deee4d36b2f43b20cb2d71eaa4a336fa6f11e2/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/12722d6cb96d16485a24915cfe953b921261bd97/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/d89e0f6c430541abfd7bcf415eb74129f02bb079/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/58eb8c5b102cfb74c21bd102eadcbf4639eb230c/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/42d5883114fc6e53a579a8d7ef858812/raw/7a32486440365cf59531681257cdc44518a401ef/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

File: src/uct/tcp/sockcm/sockcm_ep.c [hunk 2]
```diff
@@ -83,6 +83,22 @@ ucs_status_t uct_sockcm_ep_send_client_info(uct_sockcm_ep_t *ep)
...
+    case UCT_SOCKCM_EP_CONN_STATE_SOCK_CONNECTING:
+        return "UCT_SOCKCM_EP_CONN_STATE_SOCK_CONNECTING";
+    case UCT_SOCKCM_EP_CONN_STATE_INFO_SENT:
+        return "UCT_SOCKCM_EP_CONN_STATE_INFO_SENT";
+    case UCT_SOCKCM_EP_CONN_STATE_CLOSED:
+        return "UCT_SOCKCM_EP_CONN_STATE_CLOSED";
+    case UCT_SOCKCM_EP_CONN_STATE_CONNECTED:
+        return "UCT_SOCKCM_EP_CONN_STATE_CONNECTED";
+    }
+    ucs_fatal("invaild sockcm endpoint state %d", state);
```
Comment (alinask) [inline src/uct/tcp/sockcm/sockcm_ep.c]: minor: we usually use 'default' in case-switch statements in ucx

**Comment by mellanox-github** [comment]
Test PASSed.
See http://hpc-master.lab.mtl.com:8080/job/hpc-ucx-pr/12494/ for details (Mellanox internal link).

**Comment by mellanox-github** [comment]
<details><summary>Mellanox CI: <b>PASSED</b#  > on 29 workers (click for details)</summary>

**Note:** the logs will be deleted after 10-Oct-2019

Agent/Stage | Status
-- | --
[_main](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/02c951733663d6d28ac7922b0c91318c327e1802/_main) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/4456d71be46e228a780e3b556f9c28ee38bae6b1/hpc-arm-cavium-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/12d5732c0c489557ed4332f09388b8fce8036b82/hpc-arm-cavium-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/77fb269fdcfbf0bfe65cef5257aaf12a64218203/hpc-arm-cavium-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-cavium-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/1522bc23cb697a1e4d5ff4df5fdfcde08b51fa22/hpc-arm-cavium-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/904a99a6210b6488d6f6a091720522d21696c82b/hpc-arm-hwi-jenkins_W0) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/42cb9c7c57ba962f7141f7d9158a794467294926/hpc-arm-hwi-jenkins_W1) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/61c5fc933dc0fe9ac0b635efc7689d52d892360f/hpc-arm-hwi-jenkins_W2) | :heavy_check_mark: SUCCESS
[hpc-arm-hwi-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/1a8a0c820ba5fa757bbe492587aaa8f56d62166a/hpc-arm-hwi-jenkins_W3) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W0](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/a0e6e89dc6afdb88e28bf00e59ff734d15e7e6ed/hpc-test-althca_W0) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W1](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/35d3eea014fb77b735d30b674d653e1308808c0f/hpc-test-althca_W1) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W2](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/59640e7c2b81ba85a36a4adc554457e376bd92c6/hpc-test-althca_W2) | :heavy_check_mark: SUCCESS
[hpc-test-althca_W3](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/5ca9783d07c8f649957446ba390f0ec3ba5fce35/hpc-test-althca_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W0](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/f52a319a3d18fd3b3fbf49fad7851e3de18bb75b/hpc-test-node-gpu_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W1](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/b8bbee568693009aa79f006bb627b9cfd757d9c9/hpc-test-node-gpu_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W2](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/19dd46f91cdda6ac316335fd8ad4747ef8783b14/hpc-test-node-gpu_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-gpu_W3](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/96b6cb7fab9c5860b03c017be20452d1d0549fab/hpc-test-node-gpu_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W0](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/48f6703c4173419b026dc075e69336728208b63e/hpc-test-node-legacy_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W1](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/98069c886a071dccf786c47206e533672c42b129/hpc-test-node-legacy_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W2](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/68ce69e6517b94a1c32ea9b89723189aec5305ce/hpc-test-node-legacy_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-legacy_W3](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/652094d58cf44a1636137591acb491bb717ac347/hpc-test-node-legacy_W3) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W0](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/130eb3481cd53dca98f14dc31b836839502d744c/hpc-test-node-new_W0) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W1](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/57bec48ed0046c97417f8e540a7c8c85a0640c02/hpc-test-node-new_W1) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W2](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/e50fc3255cd84035bb6b0a4e821ce24eab6ec952/hpc-test-node-new_W2) | :heavy_check_mark: SUCCESS
[hpc-test-node-new_W3](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/6ca3bc3490bff32bba6c90fbcdefce6f57fa648a/hpc-test-node-new_W3) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W0](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/df0aee2a244f4769f642c0c951d3b13d408dc9d2/r-vmb-ppc-jenkins_W0) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W1](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/8bf05762ecceaa045eefeb3aca2f724db3d7d8b7/r-vmb-ppc-jenkins_W1) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W2](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/c64f556b1e9b9925a8381d433c99e0b872341265/r-vmb-ppc-jenkins_W2) | :heavy_check_mark: SUCCESS
[r-vmb-ppc-jenkins_W3](https://gist.githubusercontent.com/mellanox-github/799f1c5ed544020eb350240cab7b62de/raw/e2ebb1cad4248b51015e3c61ce634eabbbef0767/r-vmb-ppc-jenkins_W3) | :heavy_check_mark: SUCCESS

**Comment by evgeny-leksikov** [comment]
@alinask good to merge?
