### PR TITLE
UCT/TCP: Don't allow connecting loopback with other devices

### LINKED ISSUE #7599: UCX 1.11.2 is not working between two AWS EC2 instances over TCP
This can be easily reproduced by creating 2 EC2 instances in AWS and making sure that the security group allows the eth0 ip address in both. 

The key seems to be that on a machine with both loopback and a NIC (lo and eth0) and if both interfaces are allowed, UCX is able to establish a connection between the NICs according to the DATA logs, but then it tries to connect eth0 -> lo. This second attempt fails and discards not only the failed attempt to the peer's loopback, but also the eth0->eth0 pair.

```
tcp/lo - Destination is unreachable, tcp/eth0 - Destination is unreachable
```

Once the instances and config is done, I installed UCX 1.11.2 and ran ucx_perftest. I got the following output:

Server
```
[ec2-user@ip-172-31-14-219 ~]$  ucx_perftest -t tag_bw -s 1000000 -n 10000 
Waiting for connection...
+------------------------------------------------------------------------------------------+
| API:          protocol layer                                                             |
| Test:         tag match bandwidth                                                        |
| Data layout:  (automatic)                                                                |
| Send memory:  host                                                                       |
| Recv memory:  host                                                                       |
| Message size: 1000000                                                                    |
+------------------------------------------------------------------------------------------+
[1635521253.605802] [ip-172-31-14-219:3382 :0]          select.c:514  UCX  ERROR   no active messages transport to <no debug data>: posix/memory - Destination is unreachable, sysv/memory - Destination is unreachable, self/memory0 - Destination is unreachable, tcp/lo - Destination is unreachable, tcp/eth0 - Destination is unreachable
```

Client just hangs:
```
[ec2-user@ip-172-31-14-108 ~]$ ucx_perftest -t tag_bw -s 1000000 -n 10000 172.31.14.219
+--------------+--------------+-----------------------------+---------------------+-----------------------+
|              |              |      overhead (usec)        |   bandwidth (MB/s)  |  message rate (msg/s) |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
|    Stage     | # iterations | typical | average | overall |  average |  overall |  average  |  overall  |
+--------------+--------------+---------+---------+---------+----------+----------+-----------+-----------+
```

The DATA-level logs are here: https://gist.github.com/abellina/72130e215f16cbe61ec746b4e9ad7169 for both side.

I see this in both the server and client:
```
[1635521364.126453] [ip-172-31-14-219:3391 :0]          tcp_cm.c:104  UCX  DEBUG tcp_ep 0xd707c0: WAITING_ACK -> CONNECTED for the [127.0.0.1:48903]<->[172.31.14.108:42543]:0 connection [Tx:-]
[1635521364.126519] [ip-172-31-14-219:3391 :0]           mpool.c:206  UCX  DEBUG mpool uct_tcp_iface_rx_buf_mp: allocated chunk 0x7fe186756010 of 1049176 bytes with 8 elements
[1635521364.126568] [ip-172-31-14-219:3391 :0]          tcp_cm.c:108  UCX  DEBUG tcp_ep 0x7fe180000b20: RECV_MAGIC_NUMBER -> ACCEPTING
[1635521364.126624] [ip-172-31-14-219:3391 :0]           flush.c:322  UCX  DEBUG flush_worker ep 0x7fe190593000
[1635521364.126690] [ip-172-31-14-219:3391 :0]          tcp_cm.c:104  UCX  DEBUG tcp_ep 0x7fe180000b20: ACCEPTING -> CONNECTED for the [172.31.14.219:40243]<->[127.0.0.1:39633]:0 connection [-:Rx]
[1635521364.127416] [ip-172-31-14-219:3391 :0]          select.c:514  UCX  ERROR   no active messages transport to <no debug data>: posix/memory - Destination is unreachable, sysv/memory - Destination is unreachable, self/memory0 - Destination is unreachable, tcp/lo - Destination is unreachable, tcp/eth0 - Destination is unreachable
[1635521364.127491] [ip-172-31-14-219:3391 :0]          ucp_ep.c:1061 UCX  DEBUG ep 0x7fe190593000: set_ep_failed status Destination is unreachable on lane[255]=(nil)
[1635521364.127525] [ip-172-31-14-219:3391 :0]          ucp_ep.c:1304 UCX  DEBUG ep 0x7fe190593000: discarding lanes
[1635521364.127565] [ip-172-31-14-219:3391 :0]          ucp_ep.c:1314 UCX  DEBUG ep 0x7fe190593000: discard uct_ep[0]=0xd707c0
[1635521364.127607] [ip-172-31-14-219:3391 :0]          ucp_ep.c:1101 UCX  DIAG  ep 0x7fe190593000: error 'Destination is unreachable' on NULL lane will not be handled since no error callback is installed
[1635521364.127665] [ip-172-31-14-219:3391 :0]          tcp_ep.c:379  UCX  DEBUG tcp_ep 0xd707c0: purge outstanding operations with status Request canceled
[1635521364.127733] [ip-172-31-14-219:3391 :0]          tcp_cm.c:104  UCX  DEBUG tcp_ep 0xd707c0: CONNECTED -> CLOSED for the [127.0.0.1:48903]<->[172.31.14.108:42543]:0 connection [-:-]
[1635521364.127773] [ip-172-31-14-219:3391 :0]          tcp_ep.c:426  UCX  DEBUG tcp_ep 0xd707c0: destroyed on iface 0xd5c070
```

@dmitrygx thought this could be due to the linux namespace assigned to the loopback interface (can be seen by inspecting `/proc/self/ns/net`). This namespace is the same in both AWS machines. I have, however, two boxes that are baremetal on prem and they have the same namespace for the loopbacks in either machine. I can't reproduce the issue on-prem.

@dmitrygx filed: https://github.com/openucx/ucx/pull/7598 as a workaround, and I'll test it in AWS but I know that if I set `UCX_NET_DEVICES=eth0` it works.

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

Don't allow connecting loopback with other devices.

## Why ?

1. If `ethtool` isn't configured on a system, TCP is unable to identify BW/latency characteristics. 
2. Let's assume both nodes has the following IP configuration:
```
lo: 127.0.0.1
eth0: 192.168.22.1
```
3. Firstly, TCP client tries to check `lo -> lo` connectivity, it fails reachability check since `boot_id` values are different (it is a part of additional NS information which is packed with `lo`).
4. Then, TCP client tries to check `lo -> eth0` connectivity, it succeeded reachability check since `eth0` address doesn't contain additional NS information.
5. Trying to establish `lo -> eth0` fails, since they are really unreachable.

Fixes #7599

## How ?

1. Always pack NS information for loopback and ordinary addresses.
2. AIf at least one of the interfaces of connection is loopback, check NS information for reachability.

### CODE REVIEW

File: src/uct/tcp/tcp_iface.c [hunk 1]
```diff
@@ -177,12 +177,23 @@ static int uct_tcp_iface_is_reachable(const uct_iface_h tl_iface,
                                       const uct_iface_addr_t *iface_addr)
 {
     uct_tcp_device_addr_t *tcp_dev_addr = (uct_tcp_device_addr_t*)dev_addr;
+    int is_local_loopback               =
+            ucs_sockaddr_is_inaddr_loopback(
+                    (const struct sockaddr*)&iface->config.ifaddr));
     uct_iface_local_addr_ns_t *local_addr_ns;
 
     if (tcp_dev_addr->flags & UCT_TCP_DEVICE_ADDR_FLAG_LOOPBACK) {
+        if (!is_local_loopback) {
```
Comment (yosefe) [inline src/uct/tcp/tcp_iface.c:186]: maybe add before line 185:

```
if (!!(tcp_dev_addr->flags & UCT_TCP_DEVICE_ADDR_FLAG_LOOPBACK) !=
    ucs_sockaddr_is_inaddr_loopback(
                (const struct sockaddr*)&iface->config.ifaddr))) {
    return 0;
}
```

Comment (dmitrygx) [reply src/uct/tcp/tcp_iface.c]: done

**Review by yosefe — APPROVED** [review]
