### PR TITLE
GTEST/UCT: Retry adding pending request if ERR_BUSY returned

### LINKED ISSUE #5373: ud_mlx5/test_uct_peer_failure.purge_failed_peer/0 failed
```
2020-07-08T09:11:15.9307708Z [ RUN      ] ud_mlx5/test_uct_peer_failure.purge_failed_peer/0 <ud_mlx5/mlx5_0:1>
2020-07-08T09:11:15.9666133Z [     INFO ] Testing component: ib
2020-07-08T09:11:16.3420325Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3422500Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3423880Z   Actual: -15
2020-07-08T09:11:16.3424963Z Expected: UCS_OK
2020-07-08T09:11:16.3425863Z Which is: 0
2020-07-08T09:11:16.3510356Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3512335Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3513611Z   Actual: -15
2020-07-08T09:11:16.3514628Z Expected: UCS_OK
2020-07-08T09:11:16.3515639Z Which is: 0
2020-07-08T09:11:16.3535677Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3537423Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3538709Z   Actual: -15
2020-07-08T09:11:16.3539656Z Expected: UCS_OK
2020-07-08T09:11:16.3540530Z Which is: 0
2020-07-08T09:11:16.3565705Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3567541Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3568864Z   Actual: -15
2020-07-08T09:11:16.3569819Z Expected: UCS_OK
2020-07-08T09:11:16.3570680Z Which is: 0
2020-07-08T09:11:16.3588922Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3591399Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3592659Z   Actual: -15
2020-07-08T09:11:16.3593622Z Expected: UCS_OK
2020-07-08T09:11:16.3594602Z Which is: 0
2020-07-08T09:11:16.3611484Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3613169Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3614512Z   Actual: -15
2020-07-08T09:11:16.3615619Z Expected: UCS_OK
2020-07-08T09:11:16.3616514Z Which is: 0
2020-07-08T09:11:16.3633856Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3635580Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3636884Z   Actual: -15
2020-07-08T09:11:16.3637862Z Expected: UCS_OK
2020-07-08T09:11:16.3638758Z Which is: 0
2020-07-08T09:11:16.3656308Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3658045Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3659356Z   Actual: -15
2020-07-08T09:11:16.3660329Z Expected: UCS_OK
2020-07-08T09:11:16.3661205Z Which is: 0
2020-07-08T09:11:16.3678807Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3680568Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3681873Z   Actual: -15
2020-07-08T09:11:16.3682839Z Expected: UCS_OK
2020-07-08T09:11:16.3683740Z Which is: 0
2020-07-08T09:11:16.3699855Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3701482Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3703420Z   Actual: -15
2020-07-08T09:11:16.3704459Z Expected: UCS_OK
2020-07-08T09:11:16.3705366Z Which is: 0
2020-07-08T09:11:16.3721693Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3723688Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3725024Z   Actual: -15
2020-07-08T09:11:16.3725840Z Expected: UCS_OK
2020-07-08T09:11:16.3726674Z Which is: 0
2020-07-08T09:11:16.3743639Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3745205Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3746288Z   Actual: -15
2020-07-08T09:11:16.3746719Z Expected: UCS_OK
2020-07-08T09:11:16.3756322Z Which is: 0
2020-07-08T09:11:16.3770345Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3771824Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3773030Z   Actual: -15
2020-07-08T09:11:16.3773876Z Expected: UCS_OK
2020-07-08T09:11:16.3774740Z Which is: 0
2020-07-08T09:11:16.3792896Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3794647Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3795832Z   Actual: -15
2020-07-08T09:11:16.3796685Z Expected: UCS_OK
2020-07-08T09:11:16.3797446Z Which is: 0
2020-07-08T09:11:16.3814853Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3816535Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3817724Z   Actual: -15
2020-07-08T09:11:16.3818539Z Expected: UCS_OK
2020-07-08T09:11:16.3819342Z Which is: 0
2020-07-08T09:11:16.3837210Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3838861Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3840080Z   Actual: -15
2020-07-08T09:11:16.3840923Z Expected: UCS_OK
2020-07-08T09:11:16.3841732Z Which is: 0
2020-07-08T09:11:16.3860133Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3862319Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3863558Z   Actual: -15
2020-07-08T09:11:16.3864503Z Expected: UCS_OK
2020-07-08T09:11:16.3865271Z Which is: 0
2020-07-08T09:11:16.3881616Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3883260Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3884536Z   Actual: -15
2020-07-08T09:11:16.3885630Z Expected: UCS_OK
2020-07-08T09:11:16.3886399Z Which is: 0
2020-07-08T09:11:16.3903302Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3905032Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3906262Z   Actual: -15
2020-07-08T09:11:16.3907076Z Expected: UCS_OK
2020-07-08T09:11:16.3907857Z Which is: 0
2020-07-08T09:11:16.3924724Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3926289Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3927442Z   Actual: -15
2020-07-08T09:11:16.3928255Z Expected: UCS_OK
2020-07-08T09:11:16.3929023Z Which is: 0
2020-07-08T09:11:16.3946196Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3947678Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3948837Z   Actual: -15
2020-07-08T09:11:16.3949665Z Expected: UCS_OK
2020-07-08T09:11:16.3950418Z Which is: 0
2020-07-08T09:11:16.3967678Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3969168Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3970947Z   Actual: -15
2020-07-08T09:11:16.3971783Z Expected: UCS_OK
2020-07-08T09:11:16.3972545Z Which is: 0
2020-07-08T09:11:16.3989751Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.3991454Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.3992724Z   Actual: -15
2020-07-08T09:11:16.3993584Z Expected: UCS_OK
2020-07-08T09:11:16.3994432Z Which is: 0
2020-07-08T09:11:16.4010723Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4012268Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4013432Z   Actual: -15
2020-07-08T09:11:16.4014349Z Expected: UCS_OK
2020-07-08T09:11:16.4015134Z Which is: 0
2020-07-08T09:11:16.4032491Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4034142Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4035398Z   Actual: -15
2020-07-08T09:11:16.4036224Z Expected: UCS_OK
2020-07-08T09:11:16.4036968Z Which is: 0
2020-07-08T09:11:16.4054469Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4056005Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4057208Z   Actual: -15
2020-07-08T09:11:16.4058014Z Expected: UCS_OK
2020-07-08T09:11:16.4058773Z Which is: 0
2020-07-08T09:11:16.4076579Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4078225Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4079404Z   Actual: -15
2020-07-08T09:11:16.4080240Z Expected: UCS_OK
2020-07-08T09:11:16.4081005Z Which is: 0
2020-07-08T09:11:16.4098893Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4100687Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4101947Z   Actual: -15
2020-07-08T09:11:16.4102767Z Expected: UCS_OK
2020-07-08T09:11:16.4103551Z Which is: 0
2020-07-08T09:11:16.4119737Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4121904Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4123126Z   Actual: -15
2020-07-08T09:11:16.4123943Z Expected: UCS_OK
2020-07-08T09:11:16.4124837Z Which is: 0
2020-07-08T09:11:16.4141573Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4143180Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4144458Z   Actual: -15
2020-07-08T09:11:16.4145303Z Expected: UCS_OK
2020-07-08T09:11:16.4146049Z Which is: 0
2020-07-08T09:11:16.4162829Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4164411Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4165672Z   Actual: -15
2020-07-08T09:11:16.4166467Z Expected: UCS_OK
2020-07-08T09:11:16.4167247Z Which is: 0
2020-07-08T09:11:16.4184430Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4186028Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4187198Z   Actual: -15
2020-07-08T09:11:16.4188032Z Expected: UCS_OK
2020-07-08T09:11:16.4188765Z Which is: 0
2020-07-08T09:11:16.4208062Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4209811Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4211027Z   Actual: -15
2020-07-08T09:11:16.4211843Z Expected: UCS_OK
2020-07-08T09:11:16.4212595Z Which is: 0
2020-07-08T09:11:16.4228953Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4230484Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4232287Z   Actual: -15
2020-07-08T09:11:16.4233191Z Expected: UCS_OK
2020-07-08T09:11:16.4233942Z Which is: 0
2020-07-08T09:11:16.4249960Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4251428Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4252622Z   Actual: -15
2020-07-08T09:11:16.4253440Z Expected: UCS_OK
2020-07-08T09:11:16.4254260Z Which is: 0
2020-07-08T09:11:16.4271404Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4272932Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4274200Z   Actual: -15
2020-07-08T09:11:16.4275018Z Expected: UCS_OK
2020-07-08T09:11:16.4275793Z Which is: 0
2020-07-08T09:11:16.4292881Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4294511Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4295812Z   Actual: -15
2020-07-08T09:11:16.4296615Z Expected: UCS_OK
2020-07-08T09:11:16.4297385Z Which is: 0
2020-07-08T09:11:16.4314850Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4316503Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4317695Z   Actual: -15
2020-07-08T09:11:16.4318505Z Expected: UCS_OK
2020-07-08T09:11:16.4319272Z Which is: 0
2020-07-08T09:11:16.4335835Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4337346Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4338550Z   Actual: -15
2020-07-08T09:11:16.4339375Z Expected: UCS_OK
2020-07-08T09:11:16.4340127Z Which is: 0
2020-07-08T09:11:16.4356774Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4358280Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4359498Z   Actual: -15
2020-07-08T09:11:16.4360326Z Expected: UCS_OK
2020-07-08T09:11:16.4361073Z Which is: 0
2020-07-08T09:11:16.4378476Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4380726Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4381958Z   Actual: -15
2020-07-08T09:11:16.4382804Z Expected: UCS_OK
2020-07-08T09:11:16.4383568Z Which is: 0
2020-07-08T09:11:16.4398767Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4400285Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4401545Z   Actual: -15
2020-07-08T09:11:16.4402388Z Expected: UCS_OK
2020-07-08T09:11:16.4403131Z Which is: 0
2020-07-08T09:11:16.4419944Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4421638Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4422861Z   Actual: -15
2020-07-08T09:11:16.4423682Z Expected: UCS_OK
2020-07-08T09:11:16.4424553Z Which is: 0
2020-07-08T09:11:16.4441004Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4442531Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4443708Z   Actual: -15
2020-07-08T09:11:16.4444637Z Expected: UCS_OK
2020-07-08T09:11:16.4445386Z Which is: 0
2020-07-08T09:11:16.4461645Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4463166Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4464442Z   Actual: -15
2020-07-08T09:11:16.4465277Z Expected: UCS_OK
2020-07-08T09:11:16.4466027Z Which is: 0
2020-07-08T09:11:16.4482799Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4484413Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4486198Z   Actual: -15
2020-07-08T09:11:16.4487066Z Expected: UCS_OK
2020-07-08T09:11:16.4487829Z Which is: 0
2020-07-08T09:11:16.4504175Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4505902Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4507081Z   Actual: -15
2020-07-08T09:11:16.4507971Z Expected: UCS_OK
2020-07-08T09:11:16.4508734Z Which is: 0
2020-07-08T09:11:16.4525776Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4527566Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4528752Z   Actual: -15
2020-07-08T09:11:16.4529554Z Expected: UCS_OK
2020-07-08T09:11:16.4530319Z Which is: 0
2020-07-08T09:11:16.4547720Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4549279Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4550503Z   Actual: -15
2020-07-08T09:11:16.4551303Z Expected: UCS_OK
2020-07-08T09:11:16.4552083Z Which is: 0
2020-07-08T09:11:16.4568584Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4570098Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4571251Z   Actual: -15
2020-07-08T09:11:16.4572111Z Expected: UCS_OK
2020-07-08T09:11:16.4572851Z Which is: 0
2020-07-08T09:11:16.4589816Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4591382Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4592553Z   Actual: -15
2020-07-08T09:11:16.4595815Z Expected: UCS_OK
2020-07-08T09:11:16.4599668Z Which is: 0
2020-07-08T09:11:16.4611067Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4612449Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4613680Z   Actual: -15
2020-07-08T09:11:16.4614597Z Expected: UCS_OK
2020-07-08T09:11:16.4615559Z Which is: 0
2020-07-08T09:11:16.4632346Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4634645Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4635931Z   Actual: -15
2020-07-08T09:11:16.4636761Z Expected: UCS_OK
2020-07-08T09:11:16.4637503Z Which is: 0
2020-07-08T09:11:16.4653782Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4655504Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4656729Z   Actual: -15
2020-07-08T09:11:16.4657531Z Expected: UCS_OK
2020-07-08T09:11:16.4658326Z Which is: 0
2020-07-08T09:11:16.4674795Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4676329Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4677524Z   Actual: -15
2020-07-08T09:11:16.4678345Z Expected: UCS_OK
2020-07-08T09:11:16.4679114Z Which is: 0
2020-07-08T09:11:16.4695719Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4697366Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4698544Z   Actual: -15
2020-07-08T09:11:16.4699349Z Expected: UCS_OK
2020-07-08T09:11:16.4700112Z Which is: 0
2020-07-08T09:11:16.4716902Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4718470Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4719669Z   Actual: -15
2020-07-08T09:11:16.4720462Z Expected: UCS_OK
2020-07-08T09:11:16.4721235Z Which is: 0
2020-07-08T09:11:16.4738220Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4739717Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4740927Z   Actual: -15
2020-07-08T09:11:16.4742332Z Expected: UCS_OK
2020-07-08T09:11:16.4743130Z Which is: 0
2020-07-08T09:11:16.4760499Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4762070Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4763268Z   Actual: -15
2020-07-08T09:11:16.4764163Z Expected: UCS_OK
2020-07-08T09:11:16.4764974Z Which is: 0
2020-07-08T09:11:16.4781948Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4783467Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4784745Z   Actual: -15
2020-07-08T09:11:16.4785565Z Expected: UCS_OK
2020-07-08T09:11:16.4786334Z Which is: 0
2020-07-08T09:11:16.4803004Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4804684Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4805892Z   Actual: -15
2020-07-08T09:11:16.4806709Z Expected: UCS_OK
2020-07-08T09:11:16.4807482Z Which is: 0
2020-07-08T09:11:16.4823983Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4825599Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4826788Z   Actual: -15
2020-07-08T09:11:16.4827619Z Expected: UCS_OK
2020-07-08T09:11:16.4828395Z Which is: 0
2020-07-08T09:11:16.4845109Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4846992Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4848202Z   Actual: -15
2020-07-08T09:11:16.4849024Z Expected: UCS_OK
2020-07-08T09:11:16.4849770Z Which is: 0
2020-07-08T09:11:16.4866053Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:308: Failure
2020-07-08T09:11:16.4867589Z Value of: uct_ep_pending_add(ep0(), &reqs[i].uct, 0)
2020-07-08T09:11:16.4868804Z   Actual: -15
2020-07-08T09:11:16.4869655Z Expected: UCS_OK
2020-07-08T09:11:16.4870425Z Which is: 0
2020-07-08T09:11:16.4942683Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:314: Failure
2020-07-08T09:11:16.4945275Z Value of: uct_ep_am_short(ep0(), 0, 0, __null, 0)
2020-07-08T09:11:16.4946223Z   Actual: 0
2020-07-08T09:11:16.4947043Z Expected: UCS_ERR_ENDPOINT_TIMEOUT
2020-07-08T09:11:16.4948174Z Which is: -80
2020-07-08T09:11:16.5037994Z /scrap/azure/agent-02/AZP_WORKSPACE/2/s/contrib/../test/gtest/uct/test_peer_failure.cc:317: Failure
2020-07-08T09:11:16.5039811Z Value of: m_req_purge_count
2020-07-08T09:11:16.5040680Z   Actual: 0
2020-07-08T09:11:16.5041475Z Expected: num_pend_sends
2020-07-08T09:11:16.5042250Z Which is: 64
2020-07-08T09:11:16.5767809Z [  FAILED  ] ud_mlx5/test_uct_peer_failure.purge_failed_peer/0, where GetParam() = ud_mlx5/mlx5_0:1 (641 ms)
2020-07-08T09:11:16.5776150Z [----------] 1 test from ud_mlx5/test_uct_peer_failure (646 ms total)
```
https://dev.azure.com/ucfconsort/0b36e3f0-8ab9-4a48-b68b-4b2350e02c88/_apis/build/builds/7568/logs/165

### PR DESCRIPTION
**Pull request by dmitrygx**
## What

GTEST/UCT: Retry adding pending request if ERR_BUSY returned

## Why ?

to avoid failures on expecting `UCS_OK` when `UCS_ERR_BUSY` error is returned form `uct_ep_pending_add()`
Fixes #5373 

## How ?

retry filling UCT resources when `uct_ep_pending_add()` returns `UCS_ERR_BUSY`

### CODE REVIEW

File: test/gtest/uct/test_peer_failure.cc [hunk 1]
```diff
@@ -300,6 +300,10 @@ UCS_TEST_SKIP_COND_P(test_uct_peer_failure, purge_failed_peer,
             UCS_TEST_ABORT("AM Short failed with " << ucs_status_string(status));
         }
 
+        /* disable UD async progress in order to prevent returning UCS_ERR_BUSY
+         * from uct_ep_pending_add() below */
```
Comment (yosefe) [inline test/gtest/uct/test_peer_failure.cc:304]: why not just handle BUSY return code?
e.g first pending_add can have BUSY, but once we get OK - the rest should also be OK

Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:304]: > why not just handle BUSY return code?

@yosefe do you mean check for BUSY? and if it returns BUSY, skip the test?

Comment (yosefe) [reply test/gtest/uct/test_peer_failure.cc:304]: we can either push more AMs, or pass the test (e.g not fail if returned BUSY)

Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc]: done

**Comment by dmitrygx** [comment]
@brminich could you review pls?

File: test/gtest/uct/test_peer_failure.cc [hunk 2]
```diff
@@ -280,32 +302,35 @@ UCS_TEST_SKIP_COND_P(test_uct_peer_failure, purge_failed_peer,
...
+                break;
+            } else {
+                EXPECT_EQ(UCS_ERR_BUSY, status);
+                fill_resources();
+            }
         }
 
-        kill_receiver();
+        if (retry_cnt == max_retry_num) {
+            UCS_TEST_SKIP_R("unable to add pending requests after "
```
Comment (brminich) [inline test/gtest/uct/test_peer_failure.cc:328]: looks excessive, because checked in `fill_resources` already in some way

File: test/gtest/uct/test_peer_failure.cc [hunk 3]
```diff
@@ -280,32 +302,35 @@ UCS_TEST_SKIP_COND_P(test_uct_peer_failure, purge_failed_peer,
...
+                            "filling UCT resources");
+        }
 
-        for (size_t i = 0; i < num_pend_sends; i ++) {
-            reqs[i].ep       = ep0();
-            reqs[i].uct.func = pending_cb;
-            EXPECT_EQ(UCS_OK, uct_ep_pending_add(ep0(), &reqs[i].uct, 0));
+        for (size_t i = 1; i < num_pend_sends; i++) {
+            EXPECT_UCS_OK(add_pending(ep0(), reqs[i]));
```
Comment (brminich) [inline test/gtest/uct/test_peer_failure.cc:333]: i'd just skip the test if can not add to pending without retries

File: test/gtest/uct/test_peer_failure.cc (hunk 2 above)
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:334]: @yosefe wdyt?
btw, added one more comment to fix case when AM short fails with error in `fill_resources()` after peer failure was detected

File: test/gtest/uct/test_peer_failure.cc (hunk 3 above)
Comment (yosefe) [reply test/gtest/uct/test_peer_failure.cc:339]: do you mean if add_pending returns BUSY even once?

Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:339]: > do you mean if add_pending returns BUSY even once?

it could be returned only from the 1st `add_pending()`, since pending callback don't return UCS_OK, it always tries to fill resource again

File: test/gtest/uct/test_peer_failure.cc (hunk 2 above)
Comment (yosefe) [reply test/gtest/uct/test_peer_failure.cc:334]: @brminich it's different, it means we got UCS_ERR_BUSY too many times from add_pending

File: test/gtest/uct/test_peer_failure.cc (hunk 3 above)
Comment (brminich) [reply test/gtest/uct/test_peer_failure.cc:339]: yes, just do not always expect `UCS_OK`, because:
- it will not disable this test for UD, the test will be skipped just when async progress ticks before adding to pending
- proposed change does not guarantee that this test will always be valid for UD, but imo adds unnecessary complexity

**Comment by brminich** [comment]
why is it different? We want to exhaust tx resources to be able to add to pending, right?

**Comment by yosefe** [comment]
> why is it different? We want to exhaust tx resources to be able to add to pending, right?

the retry cnt check is if fill_resources was called more than few times (successfully)

**Comment by brminich** [comment]
> > why is it different? We want to exhaust tx resources to be able to add to pending, right?
> 
> the retry cnt check is if fill_resources was called more than few times (successfully)

by `fill_resources` already has some logic which checks whether we can actually fill resources with the given time frame.

**Comment by yosefe** [comment]
> by `fill_resources` already has some logic which checks whether we can actually fill resources with the given time frame.

Do you mean that if we check time limit no need to also check retry count? Maybe can make time limit for all attempts instead of for every one

**Comment by brminich** [comment]
> > by `fill_resources` already has some logic which checks whether we can actually fill resources with the given time frame.
> 
> Do you mean that if we check time limit no need to also check retry count? Maybe can make time limit for all attempts instead of for every one

Yes. We could call `fill_resources` just once, but if adding to pending fails, just skip the test

**Comment by dmitrygx** [comment]
> Maybe can make time limit for all attempts instead of for every one

@brminich @yosefe this makes sense to me, can do filling resources until either ERR_NO_RESOURCES isn't returned or test timeout isn't expired

**Comment by dmitrygx** [comment]
> We could call `fill_resources` just once, but if adding to pending fails, just skip the test

yes

**Comment by dmitrygx** [comment]
@brminich @yosefe done

File: test/gtest/uct/test_peer_failure.cc [hunk 4]
```diff
@@ -181,6 +181,34 @@ class test_uct_peer_failure : public uct_test {
...
+        ucs_status_t status;
+        do {
+            status = uct_ep_am_short(ep0(), 0, 0, &send_data,
+                                     sizeof(send_data));
+        } while ((status == UCS_OK) && (ucs_get_time() < loop_end_limit));
+
+        if (status == UCS_OK) {
+            UCS_TEST_SKIP_R("unable to fill the UCT resources");
+        } else if (status != UCS_ERR_NO_RESOURCE) {
+            if (m_err_count == 0) {
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc]: it was my first idea, but I thought that the proposed version is better for you :)
done

File: test/gtest/uct/test_peer_failure.cc [hunk 5]
```diff
@@ -280,32 +307,41 @@ UCS_TEST_SKIP_COND_P(test_uct_peer_failure, purge_failed_peer,
...
-        kill_receiver();
+            status = add_pending(ep0(), reqs[0]);
+            if (UCS_OK == status) {
+                break;
+            }
+
+            EXPECT_EQ(UCS_ERR_BUSY, status);
+            if (status != UCS_ERR_BUSY) {
+                break;
+            }
```
Comment (yosefe) [inline test/gtest/uct/test_peer_failure.cc:335]: not needed, see next line

File: test/gtest/uct/test_peer_failure.cc [hunk 6]
```diff
@@ -280,32 +307,41 @@ UCS_TEST_SKIP_COND_P(test_uct_peer_failure, purge_failed_peer,
...
-        } while ((status == UCS_OK) && (ucs_get_time() < loop_end_limit));
+            fill_resources(receiver_killed, loop_end_limit);
 
-        if (status == UCS_OK) {
-            UCS_TEST_SKIP_R("unable to fill the UCT resources");
-        } else if (status != UCS_ERR_NO_RESOURCE) {
-            UCS_TEST_ABORT("AM Short failed with " << ucs_status_string(status));
-        }
+            if (!receiver_killed) {
+                kill_receiver();
```
Comment (yosefe) [inline test/gtest/uct/test_peer_failure.cc:323]: IMHO uniting it to one loop is confusing, better have separate code to fill+kill before the add_pending+fill loop

File: test/gtest/uct/test_peer_failure.cc [hunk 7]
```diff
@@ -181,6 +181,33 @@ class test_uct_peer_failure : public uct_test {
...
+        ucs_status_t status;
+        do {
+            status = uct_ep_am_short(ep0(), 0, 0, &send_data,
+                                     sizeof(send_data));
+        } while ((status == UCS_OK) && (ucs_get_time() < loop_end_limit));
+
+        if (status == UCS_OK) {
+            UCS_TEST_SKIP_R("unable to fill the UCT resources");
+        } else if (status != UCS_ERR_NO_RESOURCE) {
+            if (expect_error) {
```
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:201]: but it could be `UCS_ERR_IO_ERROR` in case of TCP

File: test/gtest/uct/test_peer_failure.cc (hunk 6 above)
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:323]: I see
done

File: test/gtest/uct/test_peer_failure.cc (hunk 5 above)
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:335]: fixed

File: test/gtest/uct/test_peer_failure.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (yosefe) [reply test/gtest/uct/test_peer_failure.cc:201]: why IO_ERR and not ENDPOINT_TIMEOUT?
also, AFAIK TCP does not even support err handling now

[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:201]: if TCP detects an error during doing `send()`, it returns IO_ERROR and calls base's `set_ep_failed()` that sets all function pointers to return ENDPOIN_TIMEOUT
yes, TCP doesn't support, but this is idea in #5294. do you think it's not correct?

[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:201]: IB TLs could detect error in progress() while TCP is able to detect it in AM/PUT operations

[the remark this answers is not in the document]
Comment (yosefe) [reply test/gtest/uct/test_peer_failure.cc:201]: TCP should return some error meaning code if there is send() failure, which will hold true for UCS_IS_ENDPOINT_ERROR

File: test/gtest/uct/test_peer_failure.cc [hunk 8]
```diff
@@ -280,32 +307,36 @@ UCS_TEST_SKIP_COND_P(test_uct_peer_failure, purge_failed_peer,
...
+                fill_resources(true, loop_end_limit);
+            }
 
-        if (status == UCS_OK) {
-            UCS_TEST_SKIP_R("unable to fill the UCT resources");
-        } else if (status != UCS_ERR_NO_RESOURCE) {
-            UCS_TEST_ABORT("AM Short failed with " << ucs_status_string(status));
-        }
+            EXPECT_EQ(UCS_ERR_BUSY, status);
+
```
Comment (yosefe) [inline test/gtest/uct/test_peer_failure.cc:330]:
```
do {
    status = add_pending(ep0(), reqs[0]);
    if (UCS_OK != status) {
       EXPECT_EQ(UCS_ERR_BUSY, status);
       fill_resources(true, loop_end_limit);
    }
} while ((status == UCS_ERR_BUSY) && (ucs_get_time() < loop_end_limit));

Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:330]: done

File: test/gtest/uct/test_peer_failure.cc (hunk 7 above)
[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:201]: done

[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:201]: I don't think that i would work, since if even UD does sends after peer failure detection, send will return `UCS_IS_ENDPOINT_ERROR` that is false from `UCS_IS_ENDPOINT_ERROR()`

[the remark this answers is not in the document]
Comment (yosefe) [reply test/gtest/uct/test_peer_failure.cc:201]: which error will it return? can you point to relevant UD code?

[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:201]: > which error will it return? can you point to relevant UD code?

I meant this is common code for all UCTs:
https://github.com/openucx/ucx/blob/6f2ee46e81da7db7d73936dd0929756e23709412/src/uct/base/uct_iface.c#L349

[the remark this answers is not in the document]
Comment (yosefe) [reply test/gtest/uct/test_peer_failure.cc:201]: right, ucs_empty_function_return_ep_timeout() return value would be "true" for `UCS_IS_ENDPOINT_ERROR()`

[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:201]:
```
#define UCS_IS_ENDPOINT_ERROR(_code) \
    (((_code) <= UCS_ERR_FIRST_ENDPOINT_FAILURE) && \
     ((_code) >= UCS_ERR_LAST_ENDPOINT_FAILURE))
```
where `UCS_ERR_FIRST_ENDPOINT_FAILURE = -60` and `UCS_ERR_LAST_ENDPOINT_FAILURE = -79`
but `UCS_ERR_ENDPOINT_TIMEOUT = -80`
so, status has to be `status <= -60` and `status >= -79` (`status = [-79; -60]`)
should we fix `UCS_ERR_ENDPOINT_TIMEOUT` to be `-79 <= x <= -60`, but I guess it is not backward compatible change

[the remark this answers is not in the document]
Comment (yosefe) [reply test/gtest/uct/test_peer_failure.cc:201]: > should we fix `UCS_ERR_ENDPOINT_TIMEOUT` to be `-79 <= x <= -60`, but I guess it is not ABI compatible change

Can we fix UCS_ERR_LAST_ENDPOINT_FAILURE to be -89 for example?

[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:201]: > Can we fix UCS_ERR_LAST_ENDPOINT_FAILURE to be -89 for example?

yes, it's better

[the remark this answers is not in the document]
Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc]: @yosefe done

File: test/gtest/uct/test_peer_failure.cc [hunk 9]
```diff
@@ -280,32 +307,32 @@ UCS_TEST_SKIP_COND_P(test_uct_peer_failure, purge_failed_peer,
...
     std::vector<pending_send_request_t> reqs(num_pend_sends);
 
     {
         scoped_log_handler slh(wrap_errors_logger);
-
         ucs_status_t status;
+
+        fill_resources(false, loop_end_limit);
+        kill_receiver();
+
```
Comment (brminich) [inline test/gtest/uct/test_peer_failure.cc:320]: what use case is fixed here?

you killed the receiver, so your sends will not be completed even if async progress gets invoked.

Why need another loop above `fill_resources`, which already tries to get `NO_RESOURCE` until timeout?

Comment (dmitrygx) [reply test/gtest/uct/test_peer_failure.cc:320]: > you killed the receiver, so your sends will not be completed even if async progress gets invoked.

yes, they won't be completed, it send will not report the error until we don't make some CQ progress
so, it may happen if we are able to fill the resources until we really get the peer failure
otherwise, test will be skipped, since ERR_TIMEOUT is returned from AM Short
